### ISSUE TITLE
use of Environment variables in Angular 6 Library

### ISSUE THREAD

**Issue by pattanayakabhijit1990** [ng-packagr/ng-packagr#1041]
## Type of Issue

I have a angular lib where i am using environment variables configured inside the environment.ts file which is reside inside the lib. when i am using the library in another angular 6 application how can i use those configuration variables present inside the environment.ts file for the library.

Those configuration variables inside the library environment.ts file are mostly clientID and tenantID which are being used for authentication and authorization  which may change for different environment .

![image](https://user-images.githubusercontent.com/42233043/43884544-05a34d78-9bd4-11e8-83f9-8ecb41964c7b.png)

 

```
[ ] Bug Report
[ ] Feature Request
```

## Description

_A bug: please describe the error that you encountered_

_A feature: please describe your use case and motivation_

#### How To Reproduce

_A bug: please include instructions how to reproduce. Issues without reproduction are likely to receive no feedback._

_Can you reproduce the error in the integration tests in ng-packagr?_
_If possible, take a look at the [`integration/samples`](./integration/samples) and try to break one of these builds!_

_Is the error you faced in an application importing the library_
_Try to break the Angular CLI app in [`integration/consumers/ng-cli`](./integration/consumers/ng-cli)!_

#### Expected Behaviour

_A bug: please describe what behaviour or result you expected_

_A feature: do you have a first draft or an idea how to implement?_

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: x.y.z
@angular/*: x.y.z
typescript: x.y.z
rxjs: x.y.z
node: x.y.z
npm/yarn: x.y.z
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by alan-agius4** [comment]
IMO, you should have such configuration inside the library but rather these should be provide to the library via a `forRoot()` method from the application. 

From an ng-packagr perspective, there is no such as a dev/production build. There is only a single type of build.

I suggest you do follow the forRoot pattern ex;
```ts
myLibraryModule.forRoot({
    clientId: 1,
    tenantId: 2
});

```

**Comment by pattanayakabhijit1990** [comment]
@alan-agius4 no, it's  not working. When i am trying to use forRoot in my aapModule i am getting error.
**Property 'forRoot' does not exist on type 'typeof AuthLibModule'.**

**Comment by alan-agius4** [comment]
Well, you need to create the forRoot method.

https://angular.io/guide/singleton-services

**Comment by jsdevtom** [comment]
What about if your library is lazily loaded? How do you provide the environment then?

**Comment by jsdevtom** [comment]
found it: https://github.com/nrwl/nx/issues/208
