### ISSUE TITLE
bug(ci): the latest versions aren't published under the "latest" dist tag ?

### ISSUE THREAD

**Issue by douglasduteil** [ng-packagr/ng-packagr#1043]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description

Looking at the Git history, it seems like since the release 3.0.6 no other versions actually made it to npm latest dist tag. 

By running  `npm info ng-packagr versions` you can see that the 4.x versions exist. But  `npm info ng-packagr dist-tags` _latest_ is still pointing to the 3.0.6 version

**Comment by alan-agius4** [comment]
@dherges most likely this is happening due to the fact that the `v3` branch is being published after the `master` branch.

**Comment by dherges** [comment]
Yes, you're right.

the deployment scripts checks for the pattern of the git tag (v1.2.3 or v1.2.3-something) whether it's _latest_ or _next_.

It should check whether the git tag is on the master branch, if yes, use the _latest_ tag for npm. I can't find a way to do that with `git` commands. Is the [`CIRCLE_BRANCH`](https://discuss.circleci.com/t/deploying-examples/8093) env set for a git tag?

**Comment by alan-agius4** [comment]
I think you also need to set up a different tag for V3, as by default `npm` will set `latest`.

I don't think that `CIRCLE_BRANCH` is set for a tag, it's more of a which branch it's checked out.
