### ISSUE TITLE
Import a JSON file at compile time

### ISSUE THREAD

**Issue by l0rn** [ng-packagr/ng-packagr#1050]
## Type of Issue

```
[ X ] Bug Report
[ X ] Feature Request
```

## Description

Im not really sure if I am looking at a bug or a missing feature.

What I need: I simply want do import a JSON file (containing my translation strings) at build time.
Typescript should be able to import a JSON file as long there is an appropriate module type declared. So this is my importing file `translations.ts`:

```ts
/// <reference path="./json.d.ts" />

import * as de from './de.json';
import * as en from './en.json';

export default {
    de,
    en
};
```

I use the triple slash notation to import a custom json type, like described [here](https://github.com/dherges/ng-packagr/issues/193). The type looks like in [this article](https://hackernoon.com/import-json-into-typescript-8d465beded79?gi=ba77cc733763).

json.d.ts
```ts
declare module "*.json" {
    const value: any;
    export default value;
}
```
Both imported json files are existent and valid. Anyway, the moment I build this, my JSON files won't be resolved resulting in this error message:
```
Building Angular Package
Building entry point 'demo'
Rendering Stylesheets
Rendering Templates
Compiling TypeScript sources through ngc
Bundling to FESM2015

BUILD ERROR
Could not resolve './de.json' from dist/demo/esm2015/assets/i18n/translation.js
Error: Could not resolve './de.json' from dist/demo/esm2015/assets/i18n/translation.js
    at error (/home/[truncated]/module-workbench/node_modules/rollup/dist/rollup.js:199:15)
    at /home/[truncated]/module-workbench/node_modules/rollup/dist/rollup.js:20784:25

Could not resolve './de.json' from dist/demo/esm2015/assets/i18n/translation.js
Error: Could not resolve './de.json' from dist/demo/esm2015/assets/i18n/translation.js
    at error (/home/[truncated]/module-workbench/node_modules/rollup/dist/rollup.js:199:15)
    at /home/[truncated]/module-workbench/node_modules/rollup/dist/rollup.js:20784:25
```

#### How To Reproduce

You would have to set up a simple case trying to import a JSON file.

#### Version Information

```
➜   module-workbench master $ node_modules/.bin/ng-packagr --version
ng-packagr:            3.0.6
@angular/compiler:     6.1.1
rollup:                0.59.4
tsickle:               0.32.1
typescript:            2.7.2
```

**Comment by alan-agius4** [comment]
Related to: https://github.com/dherges/ng-packagr/issues/966

**Comment by l0rn** [comment]
Oh that is good to know.... Although it doesn't in angular world, ran into this one:
https://github.com/angular/angular/issues/25456

Anyone already got a workaround?

**Comment by hesselbearda** [comment]
+1 here. Ran into the same problem as #11931.

It's a show-stopper on our side.

**Comment by dominique-mueller** [comment]
I personally think that "importing JSON into application code" and "importing JSON into library code" are equally important / valid, and come with very similar use cases:

1. What comes to mind, in particular, is i18n - a library author might decide to provide all i18n files as JSON files, but also use "english" as a default by directly importing it into the component.

2. Also, libraries might have JSON configuration files which not only get used by the library itself but also by some tooling (thus the requirement for the JSON format).

3. Content might be provided as a JSON file, e.g. as a result of some CMS tool or WYSIWYG editor), and should be integrated into a library.

Overall, I don't think making JSON imports work is much work. As explained in https://github.com/angular/angular-cli/issues/11931, it's working today (in apps at least), either by adding some custom JSON typings or by using a custom TypeScript configuration.

**Comment by l0rn** [comment]
So our use case is also 1.

Our i18n extractor produces JSON and it would be convenient to include it. Indeed my current fall back is this gulp task stupidly creating valid typescript from json:
```
    return gulp.src('modules/**/i18n/*.json')
        .pipe(replace(/({(.|\s)*})/, function (match) {
            return 'export default ' + match;
        }))
        
        .pipe(rename(function (path) {
            path.extname = ".ts";
        }))
        .pipe(gulp.dest('modules/'));
```
But apart from the fact that there is a use case, I would argue since its a feature of the actual typescript compiler there shouldn't be a reason for a member of the toolchain to not support it right?

**Comment by alan-agius4** [comment]
At the moment Angular Compiler doesn’t support the TypeScript
resolveJsonModules feature.

See:
https://github.com/angular/angular/issues/25456
