### ISSUE TITLE
why "dest", slip up?

### ISSUE THREAD

**Issue by Eusen** [ng-packagr/ng-packagr#1065]
version: lastest
![image](https://user-images.githubusercontent.com/14822175/45008237-13191900-b034-11e8-8d58-9811411f08bc.png)

**Comment by Eusen** [comment]
![image](https://user-images.githubusercontent.com/14822175/45008600-1e6d4400-b036-11e8-90f3-31653441a1cd.png)

**Comment by JoostK** [comment]
It's just short for "destination", i.e. target directory to write the results into.

**Comment by Eusen** [comment]
ok, i just don't like 'in word wave line', that's all~
