### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Domainv** [ng-packagr/ng-packagr#1068]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description

When I executing ng-packagr -p src/utils/ng-package.json
getting errors "../node_modules/@types/inline-css/node_modules/@types/bluebird/index.d.ts(579,23): error TS1005: ',' expected."

What can be wrong?
#### Version Information

```
ng-packagr: 4.1.1
@angular/core: 6.0.1
typescript: 2.7.2
node: 8.11.3
npm: 6.4.1
```
![screenshot from 2018-09-07 14-12-58](https://user-images.githubusercontent.com/14885427/45218709-3d2b3f00-b2b1-11e8-8f89-52483fd8bacf.png)

**Comment by alan-agius4** [comment]
The error is typical when using a deceleration which which is written using a newer version of `TypeScript` than the one you are using. In this case it is `TypeScript Version: 2.8`
