### ISSUE TITLE
How to use "styleIncludePaths" ?

### ISSUE THREAD

**Issue by Eusen** [ng-packagr/ng-packagr#1073]
## Type of Issue

```
[?] Bug Report
```

## Description
```
"styleIncludePaths": {
          "description": "Any additional paths that should be used to resolve style imports",
          "type": "array",
          "items": {
            "type": "string"
          }
}
```
I found this schema, but no matter how I try, it doesn't work.
My lib dir structure is like this:
```
/lib/module/src/styles/index.scss
/lib/module/ng-package.json
```
And I add styleIncludePaths in ng-packge.json like this:
```
"lib": {
    "entryFile": "src/public_api.ts",
    "styleIncludePaths": [
      "styles/index.scss" // and I have tried "index.scss" , "src/styles/index.scss", but nothing happened.
    ]
}
```

#### How To Reproduce
No error, but nothing happened.

#### Expected Behaviour
How do I use it?
If it doesn't work anyway, can u add a "staticAssetsPaths" schema, like angular.json's  architect.build.options.assets ?
I think more than me, many developers need to include static resources in the package, such as font icons. I now use Python to do this.

#### Version Information
```
$ node_modules/.bin/ng-packagr --version
ng-packagr: latest
@angular/*: latest
typescript: 2.9.2
rxjs: latest
node: latest
npm/yarn: latest
```

**Comment by alan-agius4** [comment]
styleIncludePaths doesn’t work as you are describing. Please take a look

https://github.com/ng-packagr/ng-packagr/blob/HEAD/docs/style-include-paths.md

**Comment by Eusen** [comment]
![image](https://user-images.githubusercontent.com/14822175/45288011-41a76000-b51c-11e8-96ef-009897ba437d.png)

I got this error.

this is my angular.json:
![image](https://user-images.githubusercontent.com/14822175/45288152-9519ae00-b51c-11e8-877e-438f14de72ff.png)
and this is my ng-package.json:
![image](https://user-images.githubusercontent.com/14822175/45288185-a2cf3380-b51c-11e8-8e3b-40f84b81a272.png)

**Comment by Eusen** [comment]
![image](https://user-images.githubusercontent.com/14822175/45288403-27ba4d00-b51d-11e8-91ec-15ae21e80fda.png)
![image](https://user-images.githubusercontent.com/14822175/45288415-30128800-b51d-11e8-9b7d-a4ab9098d040.png)
I add aot prop failed too,

**Comment by Eusen** [comment]
hello? Is anyone here?

**Comment by alan-agius4** [comment]
You need to follow the angular cli schema for libraries. https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_ng_packagr/src/build/schema.json

Those changes need to be added to `ng-packagr.json`

**Comment by Eusen** [comment]
The problem has not been solved yet. Why closed?
![image](https://user-images.githubusercontent.com/14822175/45288185-a2cf3380-b51c-11e8-8e3b-40f84b81a272.png)
If I just add this just like:
[style-include-paths.md](https://github.com/ng-packagr/ng-packagr/blob/HEAD/docs/style-include-paths.md)
It didn't work either!

**Comment by Eusen** [comment]
If I write something wrong, can you point it out for me?

**Comment by zjl1985** [comment]
I also encountered the same problem....

**Comment by chenTeacher** [comment]
我想你没有理解stylePreprocessorOptions是什么，它就是一个帮助你省略路径的作用：
// 相对路径工作
@import '../you-style-paths/variables';
在添加
"stylePreprocessorOptions": {
  "includePaths": [
    "src/you-style-paths"
  ]
},
后
你只需要这么写
@import 'variables';
同理你在开发包的时候不想写这么长串的路径时，可以这么写 "styleIncludePaths": ["./src/assets/styles"]，然后打包的时候cli会帮你匹配路径。这个是我的理解。
我想你是想将资源文件一起打包出来吧，很不幸 ng-packagr 不支持，或者我还没有找到方案。

**Comment by zjl1985** [comment]
> 我想你没有理解stylePreprocessorOptions是什么，它就是一个帮助你省略路径的作用：
> // 相对路径工作
> @import '../you-style-paths/variables';
> 在添加
> "stylePreprocessorOptions": {
> "includePaths": [
> "src/you-style-paths"
> ]
> },
> 后
> 你只需要这么写
> @import 'variables';
> 同理你在开发包的时候不想写这么长串的路径时，可以这么写 "styleIncludePaths": ["./src/assets/styles"]，然后打包的时候cli会帮你匹配路径。这个是我的理解。
> 我想你是想将资源文件一起打包出来吧，很不幸 ng-packagr 不支持，或者我还没有找到方案。

谢谢你，我解决了，是在打包之后，又加了一个脚本把我的资源文件加入到dist里面

**Comment by renyaoxiang** [comment]
> > 我想你没有理解stylePreprocessorOptions是什么，它就是一个帮助你省略路径的作用：
> > // 相对路径工作
> > @import '../you-style-paths/variables';
> > 在添加
> > "stylePreprocessorOptions": {
> > "includePaths": [
> > "src/you-style-paths"
> > ]
> > },
> > 后
> > 你只需要这么写
> > @import 'variables';
> > 同理你在开发包的时候不想写这么长串的路径时，可以这么写 "styleIncludePaths": ["./src/assets/styles"]，然后打包的时候cli会帮你匹配路径。这个是我的理解。
> > 我想你是想将资源文件一起打包出来吧，很不幸 ng-packagr 不支持，或者我还没有找到方案。
> 
> 谢谢你，我解决了，是在打包之后，又加了一个脚本把我的资源文件加入到dist里面

脚本代码怎么写？

**Comment by zjl1985** [comment]
> > > 我想你没有理解stylePreprocessorOptions是什么，它就是一个帮助你省略路径的作用：
> > > // 相对路径工作
> > > @import '../you-style-paths/variables';
> > > 在添加
> > > "stylePreprocessorOptions": {
> > > "includePaths": [
> > > "src/you-style-paths"
> > > ]
> > > },
> > > 后
> > > 你只需要这么写
> > > @import 'variables';
> > > 同理你在开发包的时候不想写这么长串的路径时，可以这么写 "styleIncludePaths": ["./src/assets/styles"]，然后打包的时候cli会帮你匹配路径。这个是我的理解。
> > > 我想你是想将资源文件一起打包出来吧，很不幸 ng-packagr 不支持，或者我还没有找到方案。
> > 
> > 
> > 谢谢你，我解决了，是在打包之后，又加了一个脚本把我的资源文件加入到dist里面
> 
> 脚本代码怎么写？

```javascript
// scripts\build\copy-style.js
const path = require('path');
const fs = require('fs-extra');

const sourcePath = path.resolve(__dirname, '../../src/app/package');
const targetPath = path.resolve(__dirname, '../../dist');


console.log('---------------copy style folder-----------------------');
fs.copySync(path.resolve(sourcePath, 'style'), path.resolve(targetPath, 'style'));
console.log('---------------done-----------------------');

```

package.json package后会执行
```json
"postpackage": "node ./scripts/build/copy-style.js"
```

**Comment by renyaoxiang** [comment]
> > > > 我想你没有理解stylePreprocessorOptions是什么，它就是一个帮助你省略路径的作用：
> > > > // 相对路径工作
> > > > @import '../you-style-paths/variables';
> > > > 在添加
> > > > "stylePreprocessorOptions": {
> > > > "includePaths": [
> > > > "src/you-style-paths"
> > > > ]
> > > > },
> > > > 后
> > > > 你只需要这么写
> > > > @import 'variables';
> > > > 同理你在开发包的时候不想写这么长串的路径时，可以这么写 "styleIncludePaths": ["./src/assets/styles"]，然后打包的时候cli会帮你匹配路径。这个是我的理解。
> > > > 我想你是想将资源文件一起打包出来吧，很不幸 ng-packagr 不支持，或者我还没有找到方案。
> > > 
> > > 
> > > 谢谢你，我解决了，是在打包之后，又加了一个脚本把我的资源文件加入到dist里面
> > 
> > 
> > 脚本代码怎么写？
> 
> ```js
> // scripts\build\copy-style.js
> const path = require('path');
> const fs = require('fs-extra');
> 
> const sourcePath = path.resolve(__dirname, '../../src/app/package');
> const targetPath = path.resolve(__dirname, '../../dist');
> 
> 
> console.log('---------------copy style folder-----------------------');
> fs.copySync(path.resolve(sourcePath, 'style'), path.resolve(targetPath, 'style'));
> console.log('---------------done-----------------------');
> ```
> 
> package.json package后会执行
> 
> ```json
> "postpackage": "node ./scripts/build/copy-style.js"
> ```

我用的less，会有图片、字体资源，

**Comment by Eusen** [comment]
@renyaoxiang 你这就有点强人所难了。本身这个工具就不支持这样做。

**Comment by renyaoxiang** [comment]
> @renyaoxiang 你这就有点强人所难了。本身这个工具就不支持这样做。

但是我需要这个需求啊，
就不能有一个俩者皆得的方案吗？

**Comment by Eusen** [comment]
> > @renyaoxiang 你这就有点强人所难了。本身这个工具就不支持这样做。
> 
> 但是我需要这个需求啊，
> 就不能有一个俩者皆得的方案吗？

你可以用webpack打包试试，自己写个配置。或者rollup也行。

**Comment by zjl1985** [comment]
> > > > > 我想你没有理解stylePreprocessorOptions是什么，它就是一个帮助你省略路径的作用：
> > > > > // 相对路径工作
> > > > > @import '../you-style-paths/variables';
> > > > > 在添加
> > > > > "stylePreprocessorOptions": {
> > > > > "includePaths": [
> > > > > "src/you-style-paths"
> > > > > ]
> > > > > },
> > > > > 后
> > > > > 你只需要这么写
> > > > > @import 'variables';
> > > > > 同理你在开发包的时候不想写这么长串的路径时，可以这么写 "styleIncludePaths": ["./src/assets/styles"]，然后打包的时候cli会帮你匹配路径。这个是我的理解。
> > > > > 我想你是想将资源文件一起打包出来吧，很不幸 ng-packagr 不支持，或者我还没有找到方案。
> > > > 
> > > > 
> > > > 谢谢你，我解决了，是在打包之后，又加了一个脚本把我的资源文件加入到dist里面
> > > 
> > > 
> > > 脚本代码怎么写？
> > 
> > 
> > ```js
> > // scripts\build\copy-style.js
> > const path = require('path');
> > const fs = require('fs-extra');
> > 
> > const sourcePath = path.resolve(__dirname, '../../src/app/package');
> > const targetPath = path.resolve(__dirname, '../../dist');
> > 
> > 
> > console.log('---------------copy style folder-----------------------');
> > fs.copySync(path.resolve(sourcePath, 'style'), path.resolve(targetPath, 'style'));
> > console.log('---------------done-----------------------');
> > ```
> > 
> > 
> > package.json package后会执行
> > ```json
> > "postpackage": "node ./scripts/build/copy-style.js"
> > ```
> 
> 不好意思，忘记说了，我使用了less，会有图片、字体资源。我希望构建的时候，我可以看到less的效果，拷贝的时候也可以拷贝less相应的css和图片、字体资源，有办法吗？

我这写的就是copy文件啊，你有啥想copy的就是写就行了

又不是只能写一个

**Comment by juanslingerURUIT** [comment]
@Eusen I have an example working using  `styleIncludePaths`.

Have two libraries, style and component. Could integrate styles library with component library.

The architect is something like this.
- libraries
  - components
    - component-1
      - component-1.scss
    - ng-package.json
  - styles
    - scss
      - components
        - component-1.scss

File ng-package.json
`"styleIncludePaths": ["../styles/scss"]`

Inside library component

By this, the component library will search at `styles/scss` so inside `component-1.scss` I added `@import 'components/component-1'.

This worked for me!

Let me know if you have an issue.

**Comment by maxmumford** [comment]
Note that the path is relative to the library you're compiling - this is particularly relavent if you're using a nrwl monorepo structure!
