### ISSUE TITLE
Error when is making npm package

### ISSUE THREAD

**Issue by vvenegasv** [ng-packagr/ng-packagr#1074]
## Type of Issue

```
[x] Bug Report
[  ] Feature Request
```

## Description

I'm trying to publish an angular's components on NPM, but when I run the command "npm run packagr", it shows me this error: "error TS2339: Property 'toString' does not exist on type 'number'"

But when I run "ng build" or "ng serve", my application run without problems,

#### How To Reproduce

To reproduce this error, you can download an example that I uploaded to [GitHub](https://github.com/vvenegasv/error-ng-packagr).

#### Expected Behaviour

ng-packagr should made a redistributable angular's component for NPM

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 4.1.1
@angular/*: 5.2.0
typescript: 3.0.3
rxjs: 5.5.6
node: 8.9.4
npm/yarn: 5.6.0
```

**Comment by alan-agius4** [comment]
Hi, thanks for reporting this.

However in your repo are using TypeScript 2.5, ng-packagr version 4
requires 2.7+

**Comment by vvenegasv** [comment]
Hi Alan, thanks for your reply. I upgrade TypeScript and Angular and the error disappear. But now I'm getting error that says that my component has private properties. The rare is that when I serve my application, it's run without errors. I updated my example on github to replicate this situation.

My current runtime configuration is:

Angular CLI: 6.2.1
Node: 8.9.4
OS: win32 x64
Angular: 6.1.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.1
@angular-devkit/build-angular     0.8.1
@angular-devkit/build-optimizer   0.8.1
@angular-devkit/build-webpack     0.8.1
@angular-devkit/core              0.8.1
@angular-devkit/schematics        0.8.1
@angular/cli                      6.2.1
@ngtools/json-schema              1.1.0
@ngtools/webpack                  6.2.1
@schematics/angular               0.8.1
@schematics/update                0.8.1
ng-packagr                        4.1.1
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.18.0

Thanks a lot!

**Comment by alan-agius4** [comment]
That’s a genuine error, inputs cannot be set as a private.

Note that ng serve is different then build as it
doesn’t compile the code in AOT mode. Apart from that when building a
library certain checks are more strict, which means that something might
work when doing at an application level but will fail if done at a library
level.
