### ISSUE TITLE
Support for Angular 7.x.x and Typescript 3.x.x

### ISSUE THREAD

**Issue by mastermsd** [ng-packagr/ng-packagr#1078]
## Type of Issue
Support for Angular 7.x.x and Typescrypt 3.x.x
```
[ ] Bug Report
[x] Feature Request
```

## Description

_A feature: Angular 7.x.x support 
Have a more stable base Angular Environment with 7.x.x for upgrading a 6.x.x app.

#### How To Reproduce

Current given dependencies of the latest 7.0.0-beta.5 are:
"dependencies": {
    "@angular-devkit/build-angular": "0.9.0-beta.2",
    "@angular/animations": "7.0.0-beta.5",
    "@angular/cdk": "7.0.0-beta.0",
    "@angular/cli": "7.0.0-beta.2",
    "@angular/common": "7.0.0-beta.5",
    "@angular/compiler-cli": "7.0.0-beta.5",
    "@angular/compiler": "7.0.0-beta.5",
    "@angular/core": "7.0.0-beta.5",
    "@angular/flex-layout": "6.0.0-beta.18",
    "@angular/forms": "7.0.0-beta.5",
    "@angular/http": "7.0.0-beta.5",
    "@angular/material": "7.0.0-beta.0",
    "@angular/platform-browser-dynamic": "7.0.0-beta.5",
    "@angular/platform-browser": "7.0.0-beta.5",
    "@angular/router": "7.0.0-beta.5",
    "@angular/service-worker": "7.0.0-beta.5",
    "core-js": "^2.5.4",
    "rxjs": "^6.2.2",
    "tsickle": "0.32.1",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"
}

#### Expected Behaviour

To not have these warnings:
`warning " > ng-packagr@4.1.1" has incorrect peer dependency "@angular/compiler@^6.0.0".`
`warning " > ng-packagr@4.1.1" has incorrect peer dependency "@angular/compiler-cli@^6.0.0".`
`warning " > ng-packagr@4.1.1" has incorrect peer dependency "typescript@^2.7.0".`

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 4.1.1
@angular/*: 7.0.0-beta.5
typescript: 3.0.3
rxjs: ^6.2.2
node: 10.10.0
yarn: 1.10.0
```

**Comment by alan-agius4** [comment]
This has been addressed and will be fixed in the next release https://github.com/ng-packagr/ng-packagr/blob/master/package.json#L57

**Comment by odahcam** [comment]
Was this released?

I'm asking because I'm unable to build to open source projects that are making use of ng-packagr (@zxing/ngx-scanner and ngx-avatar) after upgrading to Angular 7, tsickle (used by ng-packagr) says it doesn't supports TypeScript 3.x.

**Comment by imadhy** [comment]
> Was this released?
> 
> I'm asking because I'm unable to build to open source projects that are making use of ng-packagr (@zxing/ngx-scanner and ngx-avatar) after upgrading to Angular 7, tsickle (used by ng-packagr) says it doesn't supports TypeScript 3.x.

Same here, any news about this ?
