### ISSUE TITLE
Ability to build only specific bundle formats e.g only ESM2015

### ISSUE THREAD

**Issue by TvrtkoM** [ng-packagr/ng-packagr#1080]
## Type of Issue

```
[ ] Bug Report
[X ] Feature Request
```

## Description

ng-packagr always builds a package with FESM2015, ESM2015, and UMD formats, but I would like to force my users only to use e.g. FESM2015 bundle. Currently this is not possible

#### Expected Behaviour

New configuration/cli option exists e.g. "build-targets": ["ESM2015"] and built package would only contain esm2015 build with one entry in for it in package.json

#### Version Information

```
-> % ./node_modules/.bin/ng-packagr --version
ng-packagr:            3.0.6
@angular/compiler:     6.1.2
rollup:                0.59.4
tsickle:               0.32.1
typescript:            2.7.2
```

**Comment by JoostK** [comment]
ng-packagr follows [APF 6](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/edit), which dictates the exact structure of the generated package.

**Comment by Hobart2967** [comment]
In my opinion this should be configurable though. We for example use ng-packagr for internal use, which means that there's no public rollout of the packages (plugins for a big host). The host only accepts umd. Therefore it's totally non-sense to build all the formats.
