### ISSUE TITLE
FESM5 error: 'defineInjectable' not found in  @angular/core

### ISSUE THREAD

**Issue by karlnoelle** [ng-packagr/ng-packagr#1088]
## Type of Issue

```
[x] Bug Report…?
[ ] Feature Request
```

## Description

After building an Angular 6.0.0-rc.0 Library and importing into an Angular 5.2.0 app, I get this error:
```
WARNING in ./node_modules/my_library_name/fesm5/my_library_name.js
19:66-82 "export 'defineInjectable' was not found in '@angular/core'

webpack: Compiled with warnings.
```

#### How To Reproduce

Attempt to use an ng6 Library in an ng5 app.

#### Expected Behaviour

Successfully using an ng5 library in an ng6 app.

#### Version Information

```
ng-packagr: 4.1.0
@angular/*: 5.2.0
typescript: 2.6.0
rxjs: 6.2.0
node: 8.9.4
npm/yarn: 5.6.0
```

Are ng6 packages/libraries backwards-compatible? Any help/expertise would be greatly appreciated! Thanks.

**Comment by karlnoelle** [comment]
> Can you show the excerpt of the bundle where the issue occurs? Could you also show your original source code?

Here's the entire excerpt of the responses I get – is this what you're looking for?
```
a6001241@MACC02VN5GLHTD7 test-app-ng5 $ ng serve
Your global Angular CLI version (6.2.1) is greater than your local
version (1.7.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/**
Date: 2018-09-18T18:38:54.288Z
Hash: 2522e14bfe9d7a7ca694
Time: 6209ms
chunk {inline} inline.bundle.js (inline) 3.85 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 18.3 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 562 kB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 41.6 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 8.27 MB [initial] [rendered]

WARNING in ./node_modules/pattern-library-lib/fesm5/pattern-library-lib.js
19:66-82 "export 'defineInjectable' was not found in '@angular/core'

webpack: Compiled with warnings.
```
Do you want the source code for the entire app with the library inside, or just the library?

**Comment by karlnoelle** [comment]
> Can you show the excerpt of the bundle where the issue occurs? Could you also show your original source code?

> Can you show the excerpt of the bundle where the issue occurs? Could you also show your original source code?

Here's the entire excerpt of the responses I get – is this what you're looking for?
```
// test-app-ng5 $ ng serve
Your global Angular CLI version (6.2.1) is greater than your local
version (1.7.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/**
Date: 2018-09-18T18:38:54.288Z
Hash: 2522e14bfe9d7a7ca694
Time: 6209ms
chunk {inline} inline.bundle.js (inline) 3.85 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 18.3 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 562 kB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 41.6 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 8.27 MB [initial] [rendered]

WARNING in ./node_modules/pattern-library-lib/fesm5/pattern-library-lib.js
19:66-82 "export 'defineInjectable' was not found in '@angular/core'

webpack: Compiled with warnings.
```
Do you want the source code for the entire app with the library inside, or just the library?

**Comment by JoostK** [comment]
Thanks. It looks like you're using the `providedIn` feature of `@Injectable`, which is new in NG 6 and hence not backwards compatible with NG 5.

If you want your library to work in 5, you must not rely on any of the features that are only available since 6, as that won't work of course.

**Comment by dherges** [comment]
Yes, @JoostK s explanation sounds reasonable. NG6 features won't work in NG5.

**Comment by karlnoelle** [comment]
> Thanks. It looks like you're using the `providedIn` feature of `@Injectable`, which is new in NG 6 and hence not backwards compatible with NG 5.
> 
> If you want your library to work in 5, you must not rely on any of the features that are only available since 6, as that won't work of course.

very helpful, thanks. Is is possible to disable the `@Injectable` or specifically `providedIn` feature? I tried commenting-out the references in my service file:
```
// import { Injectable } from '@angular/core';

// @Injectable({
//   providedIn: null
// })
```
but am still getting the error.

**Comment by dherges** [comment]
Oh, understand. I think you will hit the error as soon as the Angular compiler emits a `defineInjectable()` in the library bundle.

This should happen for every `@Injectable()` annotated service in NG 6 - guessing. But does it also happen when there is no `@Injectable()`?

You could try to define all providers by hand like so:

```ts
import { Provider } from '@angular/core';

class FooService {}

const FOO_PROVIDER: Provider = {
  provide: FooService,
  useClass: FooService
};

@NgModule({
  providers: [
    FOO_PROVIDER
  ]
})
export class FooModule {}
```

**Comment by JoostK** [comment]
@dherges I checked the Angular compiler, it will only generate the `ngInjectableDef` field for `@Injectable()` usages that specify `providedIn`, so the syntax that is compatible with NG 5 should not generate such field.

IIRC, I have been able to use a bundle that was generated using NG 6's compiler in an NG 5 application. The metadata version has not changed from 5 to 6 so as long as none of the code uses NG 6 concepts, you should be fine.

@karlnoelle You would have to typecheck your code with NG 5's type files (d.ts) to verify your application doesn't use anything that isn't known in that version. Easiest would just be to compile using the lowest supported version, though.

**Comment by dhruvesh71** [comment]
ng update @angular/core -f 
works for me

**Comment by maksof-kashif** [comment]
For Angular 7 or greater version use
npm install ng2-charts@2.2.3 --save
npm install chart.js --save
