### ISSUE TITLE
build issue with ng-packagr(urgent)

### ISSUE THREAD

**Issue by Kuldeep-Kumar** [ng-packagr/ng-packagr#1094]
## Its a build issue of ng-packager

```
error TS6046: Argument for '--lib' option must be: 'es5', 'es6', 'es2015', 'es7', 'es2016', 'es2017', 'esnext', 'dom', 'dom.iterable', 'webworker', 'scripthost', 'es2015.core', 'es2015.collection', 'es2015.generator', 'es2015.iterable', 'es2015.promise', 'es2015.proxy', 'es2015.reflect', 'es2015.symbol', 'es2015.symbol.wellknown', 'es2016.array.include', 'es2017.object', 'es2017.sharedmemory', 'es2017.string', 'es2017.intl', 'esnext.asynciterable'.
```

## Description

i don't why i am facing, i tried all i know to fix it

**Comment by JoostK** [comment]
I'm sorry, but with this amount of information we are unable to provide any help.

Please remove *(urgent)* from the title, that really doesn't help your case.

**Comment by bartont** [comment]
I updated to 4.2.0 and get the same error. wasn't before

**Comment by alan-agius4** [comment]
Which typescript version are you using? Typescript 2.7+ is required.

**Comment by bartont** [comment]
That did it, thanks! Installed 2.9.2 and all is well

**Comment by vikash20186** [comment]
@alan-agius4 worked for me. thanks.

**Comment by strings-code** [comment]
Upgrading the typescript version is not the optimal solution here since the package you are creating out of this can be used by an application that are on lower version of tsc and that would cause bigger issues
