### ISSUE TITLE
"JavaScript heap out of memory" during build with a lot of secondary entrypoints

### ISSUE THREAD

**Issue by ffriedl89** [ng-packagr/ng-packagr#1099]
## FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

```
[x] Bug Report
[ ] Feature Request
```

## Description

During running `ng build` for our library I receive a Javascript heap out of memory Exception. We have a pretty big library at the moment with 34 secondary-entrypoints. I recognized that the heap is increased during transformSourceFiles the most for each entrypoint while creating the program. It seems that this is never freed up during the build. I've added a logging output to the https://github.com/ng-packagr/ng-packagr/blob/v3.0.6/src/lib/ngc/transform-source-files.ts#L30 right before and after the ng.createProgram call. As you can see on each iteration for each entrypoint the heap size keeps increasing. 

Stacktrace during build
https://gist.github.com/ffriedl89/0504b26280d3af99c887b55f2335ed8d

I can also provide heap snapshots if necessary.

#### Expected Behaviour

Expect the build to work even with very many secondary-entrypoints

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            3.0.3
@angular/compiler:     6.0.3
rollup:                0.59.4
tsickle:               0.27.5
typescript:            2.7.2
rxjs: 6.2.0
node: v8.9.4
yarn: 1.5.1
```

**Comment by peterbakonyi05** [comment]
Behavior is also same in v4.1.1. The more entry points you have, the memory memory it needs. Even though the entry points have the exact same dependencies
