### ISSUE TITLE
Angular 5 in Angular 1

### ISSUE THREAD

**Issue by keshav1007** [ng-packagr/ng-packagr#1102]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

_A feature: I have bundled an angular 5 module as a separate library using this ng-packagr. Now, I would like to know whether i can use that module in angular 1 App

**Comment by alan-agius4** [comment]
If you are planning to migrate you application to angular 5, you might be able to use it togather with the ngUpgradeModule. 
https://angular.io/guide/upgrade

Otherwise, it’s not possible as Angular 5 is not compatable with AngularJS
