### ISSUE TITLE
Stripping console.log() from production build

### ISSUE THREAD

**Issue by MadHatter122312** [ng-packagr/ng-packagr#1107]
I have recently updated to use ng-packagr in my project instead of gulp, and now I am not sure how to remove console.log() in a prod build.  With gulp this was a simple solution by adding `gulp-remove-logging `...

Now, in the root of my project I have the following:

{
  "name": "dev/module",
  "description": "My test module",
  "version": "2.0.0",
  "scripts": {
...
    "ng-build": "ng-packagr -p lib/package.json"
  },
...
  "devDependencies": {
    "@angular/compiler": "6.0.5",
    "@angular/compiler-cli": "6.0.5",
    "ng-packagr": "^3.0.0",
    "tsickle": ">=0.27.3",
    "tslib": "^1.7.1",
    "typescript": "2.7.2"
  },
  "publishConfig": {
    "registry": "http://10.76.146.127:0999"
  }
}

Any out-of-the box solution available from ng-packagr for stripping console.log()?

**Comment by alan-agius4** [comment]
Ng-packagr itself doesn’t do minification expect for UMD bundles.

So it’s more of what you write is what you get.

**Comment by alan-agius4** [comment]
These usually get removed by the build system of application.

And usually console.log are not used, or if used that are wrapped so that
they can be turned off via a configuration.

**Comment by alan-agius4** [comment]
Yeah indeed. In that case, you cannot remove it. You as a library author
need to provide a way to turn the logs off something similar to
https://angular.io/api/forms/ReactiveFormsModule
