### ISSUE TITLE
rxjs dependency should be a peer dependency

### ISSUE THREAD

**Issue by CarstenLeue** [ng-packagr/ng-packagr#1112]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description
ng-packagr defined the dependency on rxjs in 'dependencies' as:

  "dependencies": {
    "rxjs": "^6.0.0",
  },

Angular 6 defined "rxjs": "~6.2.0" as a dependency. This leads to ng-packagr installing "rxjs": "6.3.3" whereas the rest of an Angular project uses "6.2.2".

#### Expected Behaviour

I would expect my complete project to use the same version of rxjs.

Suggestion: specify the rxjs dependency as a peerDependency instead

#### Version Information

```
ng-packagr:            4.3.0
@angular/compiler:     6.1.9
rollup:                0.66.6
tsickle:               0.32.1
typescript:            2.9.2
```

**Comment by alan-agius4** [comment]
I don’t see why this is causing a bug. Rxjs is a not peerDependency because it is used internally.

That said, for instance Angular CLI version 7 uses rxjs 6.3.3. Having different RXjs versions is not a problem since these are used for building and thus they won’t be bundled at application level.
