### ISSUE TITLE
[Question] Resolve File Extensions

### ISSUE THREAD

**Issue by kyjus25** [ng-packagr/ng-packagr#1120]
## Type of Issue

```
[x ] Question
```

## Description
I've created a lazy loaded component that gets pulled out of a repo library. I'm trying to build the component to be as compact as possible. We're using ng-packagr for our other 'widgets', so I'd like to continue to only use it as opposed to Webpack.

My problem is, my component imports some of our other libraries; ones that are normally built in Webpack. When I try to build my 'widget' for deployment, it cannot compile correctly and says that it cannot find some of the import paths we are using in our .scss files. 

From my debugging, I've found that our full scale Angular applications have this resolve parameter in their webpack config:
`"resolve": {
        modules: [path.resolve(__dirname, 'app'), 'node_modules', path.resolve('node_modules')],
        "extensions": [
            ".ts",
            ".js",
            ".css",
            ".scss",
        ],
    },`

Does anyone more knowledgable in ng-packagr know if something similar to this extension resolver exists? 

Hoping someone can help. I've scoured the documentation but can't seem to find what i'm looking for. The documentation says that ng-packagr can be consumed by webpack, so maybe there is a solution, but I really don't want to have to use webpack **and** ng-packagr. Any help is appreciated.

**Comment by alan-agius4** [comment]
Hi, can you please provide a reproduction? As it’s hard to tell what’s happening.
