### ISSUE TITLE
"inlineSourceMap": true as default tsconfig.ngc option increases bundle size

### ISSUE THREAD

**Issue by Domainv** [ng-packagr/ng-packagr#1140]
ng-packagr 4.4.0
![screen shot 2018-11-08 at 12 22 12 pm](https://user-images.githubusercontent.com/14885427/48192659-12ad3f00-e351-11e8-8ebc-43424abc3bb9.png)

**Comment by alan-agius4** [comment]
Can you please elaborate? What do you mean by increase in bundle size?

**Comment by Domainv** [comment]
@alan-agius4 As I understand source maps are adding to bundle with this option. What became an increase in bundle size

**Comment by alan-agius4** [comment]
They are adding in the same file that will increase the size of the file,
but eventually they will be dropped by the bundlers and optimizers at
application level.

So there is no increase in the final bundle size.
