### ISSUE TITLE
How to properly confine module's dependencies?

### ISSUE THREAD

**Issue by arquadrado** [ng-packagr/ng-packagr#1146]
## Type of Issue

```
[x ] Bug Report
[ ] Feature Request
```
## Description

I have created an angular library with ng-packagr that goes along Angular Package Format guidelines.

I have created several modules inside the library with the purpose of importing only the ones that I want in a specific app. The problem is that if I have module 'A' that needs 'dependency X', when I use some other module of the library in an app, when I run the application and modules are build I get an error saying that the 'dependency X' cannot be found, eventhough I am not importing the module that used the 'dependency X'. This doesn't seem right to me since it doesn't make sense to be forced add a bunch of dependencies that are not of the application itself just because some module of the library, that is not even being used, needs it.

I have been searching the web for some time now to try to find the solution for this but I couldn't find any relevant information.

I messed a lot with the peerDependencies of the package.json since it is pointed here that the lib dependencies should go there (although it seems that the dependencies that should go here are the indispensable ones and not dependencies that are required for one module) and also with lib.externals of the ng-package.json that seems to have been removed in the last versions.

I was not able to solve my problem and I assume it must exist a solution to this problem. So my question is: What is the proper way to manage module's dependencies inside an angular 6+ library?

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 4.4.0
@angular/*: 7.0.3
typescript: 3.1.6
rxjs: 6.3.3
node: 10.4.1 
npm/yarn: 1.5.1
```

**Comment by alan-agius4** [comment]
Would you be able to share a reproduction? When you say you are not importing the module are you referring to a secondary entry point or an ngModule?

**Comment by arquadrado** [comment]
I have have several @NgModules being exported on my public_api.ts and one of them has a specific dependency. One an app where I use the library I am not importing that specific module of the library but the app still complains about not having the module dependency. is that clear?

**Comment by alan-agius4** [comment]
This is the expected behaviour. A dependency is required not when a module is used or not but rather when the package requires it. This is due that the output being using is FESM, meaning that all modules are within a single file. Check `dist/FESM`

If a library requires dependency X, you should always install it, even if you are using parts of it that are not using dependency X.

**Comment by arquadrado** [comment]
Okay, I see. It makes sense after you get some knowledge about how the package is actually built. It would be great to install only the dependencies of the modules of the library being used on the application, though. 
Well, thank you for the answer.
