### ISSUE TITLE
How to exclude some files from ng-packagr？

### ISSUE THREAD

**Issue by li10217** [ng-packagr/ng-packagr#1147]
## How to exclude some files from ng-packagr

```
My project
       src   --floder
       packages --floder
       package.json
       ng-package.json
```

## Description

My properties include the SRC and packages folders.

When I execute the NPM run packagr, it will contain the packages folder.

How to exclude it?

**Comment by alan-agius4** [comment]
I'm sorry, but we don't understand the problem you are reporting.

If the problem persists, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
