### ISSUE TITLE
BUILD ERROR : TypeError: Cannot read property 'length' of undefined     at new _Tokenizer 

### ISSUE THREAD

**Issue by chimanyans** [ng-packagr/ng-packagr#1148]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

_A bug: please describe the error that you encountered_

_A feature: please describe your use case and motivation_

#### How To Reproduce

_A bug: please include instructions how to reproduce. Issues without reproduction are likely to receive no feedback._

_Can you reproduce the error in the integration tests in ng-packagr?_
_If possible, take a look at the [`integration/samples`](./integration/samples) and try to break one of these builds!_

_Is the error you faced in an application importing the library_
_Try to break the Angular CLI app in [`integration/consumers/ng-cli`](./integration/consumers/ng-cli)!_

#### Expected Behaviour

_A bug: please describe what behaviour or result you expected_

_A feature: do you have a first draft or an idea how to implement?_

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: ^4.4.0
@angular/*: ~7.0.0
typescript: ~3.1.6
rxjs: ~6.3.3
node: 8.11.2
npm: 6.4.1
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by JoostK** [comment]
@chimanyans Would you be so kind to actually take the time to fill out the issue template?

Without a reproduction this can't be actioned on.

**Comment by Splaktar** [comment]
As mentioned in https://github.com/ng-packagr/ng-packagr/issues/976#issuecomment-418505044 and the comments after it, this can happen if the `templateUrl` of a component is incorrect.

ng-packagr should report a useful error here rather than throwing an exception.

**Comment by alan-agius4** [comment]
I think this is no longer a bug in version 10. If the problem persists after updating please re-open the issue with a minimal reproduction.

Thanks.
