### ISSUE TITLE
Template with @angular/material tags Does not package with ng-packagr

### ISSUE THREAD

**Issue by nchetbani** [ng-packagr/ng-packagr#1153]
**Bug, feature request, or proposal:**

When using ng-packagr, I receive a build error :

```
BUILD ERROR
: 'mat-toolbar' is not a known element:
1. If 'mat-toolbar' is an Angular component, then verify that it is part of this module.
2. If 'mat-toolbar' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<mat-toolbar style="height:100%;background: white;font-size:12px">

```
## Description
1. ng generate component test-material
2. export the component from the "entryFile" `public-api.ts` : 
`export { TestMaterialComponent } from './src/app/test-material/test-material.component';`
this file is defined in ng-package.json the as follows :

```
{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "lib": {
    "entryFile": "public_api.ts",
    ...
}
```

3. add the component test-material in my custom module (`FrmkSsjsComponentsModule`):

```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { TestMaterialComponent } from '../../test-material/test-material.component';

@NgModule({
  imports: [
    CommonModule
  ],
  declarations: [
    TestMaterialComponent
  ],
  exports: [
    TestMaterialComponent
  ]
})
export class FrmkSsjsComponentsModule { }
```

At this level, the `npm run ng-packagr -p ng-package.json` work without error. but when I add in my test-material.component.html any @angular/material tags, I get the error above. For example when I put in the template this tag : `<mat-icon>save</mat-icon>`, I get the following error:

```
BUILD ERROR
: 'mat-icon' is not a known element:
1. If 'mat-icon' is an Angular component, then verify that it is part of this module.
2. If 'mat-icon' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<mat-icon>save</mat-icon>")
```

as indicated [7681](https://github.com/angular/material2/issues/7681), I added @angular/material as an external library, but it did not solve my problem

```
{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "lib": {
    "entryFile": "public_api.ts",
    "externals": {
      "@angular/material": "ng.material", 
      "@angular/material/autocomplete": "ng.material.autocomplete", 
      "@angular/material/toolbar": "ng.material.toolbar",
      "@angular/material/icon": "ng.material.icon"
    }
  },
  ...
}
```

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:                 3.0.3
@angular/compiler:     6.0.9
rollup:                          0.59.4
tsickle:                          0.29.0
typescript:                    2.7.2
@angular/material:      6.4.7
rxjs:                              6.0.0
node:                           8.11.3
npm:                            5.6.0 
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by nchetbani** [comment]
Any help

**Comment by JoostK** [comment]
@nchetbani Your `FrmkSsjsComponentsModule` does not import any Material modules, so your template doesn't get to use Material components. That has nothing to do with ng-packagr or the way you package stuff.

**Comment by nchetbani** [comment]
It work !!! Many thank @JoostK
