### ISSUE TITLE
 SCSS URL change when running packagr - local and deployed relative URLs not working

### ISSUE THREAD

**Issue by MikeSav** [ng-packagr/ng-packagr#1154]
## Type of Issue

```
[ X] Bug Report
[ ] Feature Request
```
I'm very new to ng-packagr so please be patient. I'm not sure this is a bug or more a request for information but here goes...  

I've made my first ever Angular Component Library with the Angular CLI and ng-packagr using the following article: https://medium.com/@nikolasleblanc/building-an-angular-4-component-library-with-the-angular-cli-and-ng-packagr-53b2ade0701e 

Within the components in the component library I point SCSS/CSS background url() values to a localised assets folder like so:

file name is default-button.component.scss

```
&.btn--edit:before {
    background: url("~src/assets/images/icons/svg/ic_create_16x16.svg") no-repeat;
}
```

this works great in the local project of Component Library but when I distribute it, pack it and install it in another application the CSS obviously doesn't point to the correct location. As I copy the assets folder when running packagr (here is the scripts command in my package.json)

```
"scripts": {
"packagr": "ng-packagr -p ng-package.json && mkdir -p ./dist/src/assets/ && cp -r ./src/assets/images ./dist/src/assets/images"
}
```

I need the url in the SCSS to be changed to `url("node_modules/package_name/assets/images/icons/svg/ic_create_16x16.svg")`. I noticed this comment here (https://github.com/ng-packagr/ng-packagr/issues/66) and thought the tilda may help but it doesn't. How can I resolve this using ng-packagr? Can I resolve it? Any information would be appreciated.

#### How To Reproduce

In my file src/app/modules/buttons/default-button/default-button.component.scss I have a SCSS /CSS background property that has a url value of` background: url("~src/assets/images/icons/svg/ic_create_16x16.svg")`

#### Expected Behaviour

How can I config the package.json of my Component Library or the ng-package.json so facilitate the url chage when running packagr or do I need to use a separate library... naturally if I use a data value for the url value this would work but naturally I would rather not convert my icons to a data-uri and suffer the performance hit of this.

#### Version Information

```
devDependencies": {
    "@angular-devkit/build-angular": "~0.10.0",
    "@angular/animations": "~7.0.0",
    "@angular/cli": "~7.0.4",
    "@angular/common": "~7.0.0",
    "@angular/compiler": "~7.0.0",
    "@angular/compiler-cli": "~7.0.0",
    "@angular/core": "~7.0.0",
    "@angular/forms": "~7.0.0",
    "@angular/http": "~7.0.0",
    "@angular/language-service": "~7.0.0",
    "@angular/platform-browser": "~7.0.0",
    "@angular/platform-browser-dynamic": "~7.0.0",
    "@angular/router": "~7.0.0",
    "@compodoc/compodoc": "^1.1.6",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.5.0",
    "core-js": "^2.5.4",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ng-packagr": "^4.4.0",
    "protractor": "~5.4.0",
    "rxjs": "~6.3.3",
    "ts-node": "~7.0.0",
    "tsickle": "^0.33.1",
    "tslint": "~5.11.0",
    "typescript": "~3.1.1",
    "zone.js": "~0.8.26"
  }
```

**Comment by ywager** [comment]
I also encountered this problem. Is there any update?

**Comment by lubkoKuzenko** [comment]
I'm using 3rd party library that uses relative path to fonts inside and I have the same issue.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases.
