### ISSUE TITLE
Published package has dependency on tslib which causes issues when consumed in non-TS projects

### ISSUE THREAD

**Issue by roldengarm** [ng-packagr/ng-packagr#1159]
## Type of Issue

```
[X ] Bug Report
[ ] Feature Request
```

## Description

I'm publishing a package that only contains functions, nothing Angular specific. It adds a dependency on tslib. The consumers of my app are not Typescript based, they use JS, so they don't have/want a dependency on tslib.

I've enabled and disabled `importHelpers` but that does not make a difference. I assume that with importHelpers enabled, it should emit the tslib code in the generated JS, right? So then, why is still a dependency on tslib required?

I just don't want to have a dependency on tslib in my published package.

#### How To Reproduce

just run 
```
ng g library test
ng build test
```
Check the /dist/lib/test/package.json file, it has a dependency on tslib

#### Expected Behaviour
There is no dependency on tslib in my package.json such that it can be consumed by non-TS projects.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
λ node_modules\.bin\ng-packagr --version
ng-packagr:            4.4.0
@angular/compiler:     7.0.2
rollup:                0.66.6
tsickle:               0.33.1
typescript:            3.1.3
```

**Comment by alan-agius4** [comment]
At the moment `tslib` dependency is always added irrespective if importHelpers is enabled or disabled.

The reason being why importHelpers is enabled is to obtain the smallest possible final bundle. That said, we probably should not add tslib dependency if importHelpers is disabled.

**Comment by alan-agius4** [comment]
@roldengarm, you can add an addition integration test as suggested in your second point.

**Comment by sergiubologa** [comment]
Hello @roldengarm Have you made any progress on this? Do you need any help?

**Comment by maktarsis** [comment]
Are there any updates? Still, have no possibility to exclude it from the build output

**Comment by werts** [comment]
it seems no updates here?
