### ISSUE TITLE
Read `NgPackageConfig` from CLI arguments

### ISSUE THREAD

**Issue by Toxicable** [ng-packagr/ng-packagr#116]
## Type of Issue
- [x] Feature Request

Right now having a ng-package.json appears redundant.
I propose that we should optionally be able to configure via the CLI both the entry file and output name.
for example 
`ng-packagr --entryFile public_api.ts --libName myLibName`
I have a situation where all I want to use as config is a command line command, no extra files should be needed

**Comment by alan-agius4** [comment]
Thanks for this feature request, however it seems that there is not much interest in such feature from the community. Hence, I am going to close this.

Let’s revisit in the future if things change.
