### ISSUE TITLE
does it possible to use for non angular application?

### ISSUE THREAD

**Issue by SridharSathaSivam** [ng-packagr/ng-packagr#1161]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

_feature_
Can we use this packages for generating bundled d.ts, es2015, umd files in non-angular application?

#### Expected Behaviour

_A feature: Provide option turn off angular related thing like ahead of time?_

**Comment by dherges** [comment]
Hi @SridharSathaSivam,

As of now: yes, it's definitely possible to compile non-angular library code.

However, there is no option to turn off the angular compiler for the time being. As such, the generated library will always include a metadata.json even if it's not needed.

For the future: it would be a very nice and huge feature to make the build pipeline more pluggable.

**Comment by roldengarm** [comment]
It works :) I've created a publishable library and consume it in a React JSX app. Only issue is that a tslib dependency is always added, currently I'm removing that manually.

See also issue: https://github.com/ng-packagr/ng-packagr/issues/1159

**Comment by shlomiassaf** [comment]
@SridharSathaSivam You can do it now easily with [ng-cli-packagr-tasks](https://github.com/shlomiassaf/ng-cli-packagr-tasks)

I've even added an [example](https://github.com/shlomiassaf/ng-cli-packagr-tasks/tree/master/examples/node-library) how to do that...


> FYI: It does not replace `ng-packagr` it's just an angular cli architect recipie

**Comment by codeNoobie** [comment]
@dherges How should we use this to bundle vanilla ts code? It requires angular compiler. Is that a hard requirement? If it doesn't depend on angular compiler, then we can use this to bundle vanilla ts applications as well.

**Comment by alan-agius4** [comment]
Closing as it is not in the roadmap to compile a non Angular library.
