### ISSUE TITLE
exporting Angular Material as part of my library, into another library causes build errors of second library

### ISSUE THREAD

**Issue by mattiLeBlanc** [ng-packagr/ng-packagr#1163]
## Type of Issue

```
[X ] Bug Report
[ ] Feature Request
```

## Description

I have created a UI Library, which is using Angular Material design. I am importing for example `{ MatButtonModule, MatCheckboxModule, MatSelectModule, MatInputModule}`.
I might add some custom components in the future and also export them, but for now I just want to offer a package with Material as peerDependency and consume this in another library.

So the second library is a Business Logic library (BLL) that uses the UI Library. I can install the UI-Library just fine, but only when I build the Business Logic library I get pretty gnarly build errors which I can only resolve by installing `@angular/material` and `@angular/animation` in the demo app of the Business Logic Library and referencing them as peerDependencies.

Ideally, the consumer of the BLL should be notified of a missing dependency like Animations or Material. I believe you could do something with Whitelisting so you get a nice error?

I have also been playing with the `externals` in the ng-package.json to no avail.
```
"lib": {
    "entryFile": "src/public_api.ts",
    "externals": {
      "@angular/material": "ng.material",
      "@angular/material/button": "ng.material.button",
      "@angular/material/input": "ng.material.input",
      "@angular/material/checkbox": "ng.material.checkbox",
      "@angular/material/select": "ng.material.select",
      "@angular/animations": "ng.animtions"
    }
```
Only when I install the Materials an Animations in my BLL, I do not get a nasty build error. 

Are there any good examples of what I am doing and how to best approach this?

I can put some stuff together in GIT if someone wants to look at the code.

**Comment by alan-agius4** [comment]
Hi,

I am not sure what error your are getting but from the description above, it seems that you might either be missing to add the `peerDependencies` of  `@angular/material` in the package.json of your UI library. 

That said, failing to install `peerDependencies` in the application, will not result in an error, as it will only show an info message by default. 

In nutshell;
- UI Library, should have `peerDependencies` to `@angular/material` and `@angular/animation`
- BBL Library, should have `peerDependencies` to UI Library
- App should have all `peerDependencies` installed as dependencies -> During `npm install` it will show you which missing peerDependencies are not meet

**Comment by mattiLeBlanc** [comment]
It where template render errors with a lot of file references. Somewhere along the code I would read mention about either Animations package or Material design. If I would import the Library directly in the source app of the BLL library, I would get a clean error, but if I would use UI Library Ain the Library BLL project and build it, I would get template errors.
I am using the peerDependencies as you mention.

I will setup a little example to show you the errors, probably easier.

**Comment by mattiLeBlanc** [comment]
So these are the repos:
UI LIB
Relies on Angular Material and exports component that use MAT-BUTTON.
url: https://github.com/mattiLeBlanc/ng-ui-lib

BLL Lib:
Consumes UI-LIB in its own library project and exports a BLL component set.
url: https://github.com/mattiLeBlanc/ng-bll-lib

To reproduces:
1) clone ui-lib and do an `npm install`.
2) clone bll-lib do an `npm install`
3) go to ui-lib folder an run `npm run package`, this should result in a TGZ file in your dist folder.
4) install ui-lib package in bll-lib: `npm install ../ui-lib/dist/ui-lib/ui-lib-0.0.1.tgz`
5) no go back to bll-lib folder and run `npm run build bll-lib`.
This should trigger the error during the buid.

I am aware that I haven't added Material Peer dependency to the package.js of the BLL-Lib project. However, I want to consumer of the UI-Lib to get a nicer error message. I think that is what the bug is about for me.

**Comment by alan-agius4** [comment]
Hi, the error is clearly indicated that it cannot resolve `@angular/material ` and indeed you don't have any dependency on `@angular/material` in https://github.com/mattiLeBlanc/ng-bll-lib/blob/master/projects/bll-lib/package.json

Also when you do `npm install` you will get a info message saying that not all peerDependencies have been meet.

**Comment by mattiLeBlanc** [comment]
@alan-agius4 I see what you mean.
When you install `npm install ../ui-lib/dist/ui-lib/ui-lib-0.0.1.tgz` you get the peerDependency message. I was just doing a reinstall of all node_modules and then you don't see it.

I am just trying to remove all obstacles for people using our UI-LIB and I wan't to make sure there are no weird errors.

Cheers.
