### ISSUE TITLE
Cannot read property 'module' of undefined

### ISSUE THREAD

**Issue by azizkhani** [ng-packagr/ng-packagr#1173]
## Type of Issue

```
[ ] Bug Report
[ ] Feature Request
```

## Description

I can not found what is cause of my problem
BUILD ERROR
```
Cannot read property 'module' of undefined
TypeError: Cannot read property 'module' of undefined
    at MetadataBundler.convertSymbol (C:\Users\azizkhani\git\ng-baharan\node_modules\@angular\compiler-cli\src\metadata\bundler.js:312:61)
    at createReference (C:\Users\azizkhani\git\ng-baharan\node_modules\@angular\compiler-cli\src\metadata\bundler.js:438:27)
    at MetadataBundler.convertReference (C:\Users\azizkhani\git\ng-baharan\node_modules\@angular\compiler-cli\src\metadata\bundler.js:486:28)
    at MetadataBundler.convertExpression (C:\Users\azizkhani\git\ng-baharan\node_modules\@angular\compiler-cli\src\metadata\bundler.js:415:37)
    at MetadataBundler.convertValue (C:\Users\azizkhani\git\ng-baharan\node_modules\@angular\compiler-cli\src\metadata\bundler.js:396:29)
    at C:\Users\azizkhani\git\ng-baharan\node_modules\@angular\compiler-cli\src\metadata\bundler.js:399:62
    at Array.map (<anonymous>)
    at MetadataBundler.convertValue (C:\Users\azizkhani\git\ng-baharan\node_modules\@angular\compiler-cli\src\metadata\bundler.js:399:30)
    at MetadataBundler.convertValue (C:\Users\azizkhani\git\ng-baharan\node_modules\@angular\compiler-cli\src\metadata\bundler.js:405:36)
    at C:\Users\azizkhani\git\ng-baharan\node_modules\@angular\compiler-cli\src\metadata\bundler.js:399:62
```
#### Version Information

```
"@angular-devkit/build-angular": "~0.11.0",
    "@angular/cli": "~7.1.3",
    "@angular/compiler-cli": "~7.1.0",
    "@angular/language-service": "~7.1.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/jquery": "^3.3.29",
    "@types/node": "~8.9.4",
    "@types/socket.io": "^2.1.2",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ng-packagr": "^4.4.5",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tsickle": "^0.34.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.6"
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_
this is my library
https://github.com/azizkhani/ng-library

**Comment by alan-agius4** [comment]
I am sorry but this error is not caused by `ng-packagr` and is most likely not a bug. 

Typically this error is caused when you are trying to register dependencies incorrectly in your module.

**Comment by azizkhani** [comment]
Why project run and  build correctly with angular but `ng-packagr` can not build that. How can i found ,which part of my configuration make this exception?
error is very general .and i ca

**Comment by abhishekgoenka** [comment]
@azizkhani I am getting the same error. How did you solve it?

**Comment by jamv999** [comment]
I had the same problem. The problem is that ng-packer didn't work well with barrel routes.

For example:
```typescript
import { ElementService } from 'path_barrel';
```

If you change the barrel for the real path work well.

```typescript
import { ElementService } from 'path_element/element.service';
```

**Comment by cluetjen** [comment]
For me it was a feature module that was not referenced in public_api.ts but used by other modules. Adding it to public_api.ts solved it for me.

**Comment by dmitryrusakov** [comment]
For me the problem was when I had:
- an`./feature/index.ts` that re-exports `export { FeatureModule } from './feature.module'` from my `feature.module.ts`
- and in root module I imported it from index-interface as:
`import { FeatureModule } from './feature'`
instead of directly from file:
`import { FeatureModule } from './feature/feature.module'`

Once I did the latter variant - problem got solved.

**Comment by benwinding** [comment]
This is so frustrating. Using `index.ts` files is a necessary part of a flexible architecture.

Instead of this:

``` typescript
import { SomeComponent, SomeService } from '../something';
import { PathHelper, DialogHelper, Logger } from '../utils';
```

Now I have to **_explicitly_** reference every... single... file!??

``` typescript
import { SomeService } from '../something/some.service';
import { SomeComponent } from '../something/some.component';
import { PathHelper } from '../utils/pathhelper';
import { DialogHelper } from '../utils/dialoghelper';
import { Logger } from '../utils/logger';
```

Which as you can see is incredibly ridged, if I change a file name, I have to search and change all references to that file. 

Ironically it's more flexible to have all components in one file now...

Can anyone fix this?

**Comment by raphael22** [comment]
This error is indeed from @angular/compiler not from ng-packger.
See https://github.com/angular/angular/issues/20931.
