### ISSUE TITLE
Build warnings

### ISSUE THREAD

**Issue by 2RajShaikh** [ng-packagr/ng-packagr#1177]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description
I am trying to figure out what are these warnings and how to fix them. (I have huge lines of code as donation from different team)

Dropping unreachable code [0:2023,8]
Declarations in unreachable code! [0:2023,8]
Dropping unreachable code [0:2066,12]
Declarations in unreachable code! [0:2066,12]
Dropping unreachable code [0:2172,8]
Declarations in unreachable code! [0:2172,8]
Dropping unreachable code [0:2247,8]
Declarations in unreachable code! [0:2247,8]
Dropping unreachable code [0:2275,8]
Declarations in unreachable code! [0:2275,8]
Dropping unreachable code [0:2282,8]
Declarations in unreachable code! [0:2282,8]
Dropping unreachable code [0:2538,8]
Declarations in unreachable code! [0:2538,8]
Dropping unreachable code [0:2568,8]
Declarations in unreachable code! [0:2568,8]
Dropping unreachable code [0:2849,8]
Declarations in unreachable code! [0:2849,8]
Dropping unreachable code [0:3185,8]
Declarations in unreachable code! [0:3185,8]
Side effects in initialization of unused variable nF [0:4241,40]
Side effects in initialization of unused variable UJ [0:4820,40]
Dropping unreachable code [0:5050,12]
Declarations in unreachable code! [0:5050,12]
Side effects in initialization of unused variable ZM [0:5262,40]
Side effects in initialization of unused variable AN [0:5356,57]
Side effects in initialization of unused variable HN [0:5373,57]
Side effects in initialization of unused variable eO [0:5433,57]
Side effects in initialization of unused variable zO [0:5530,40]
Side effects in initialization of unused variable LP [0:5917,40]
Dropping duplicated definition of variable AQ [0:6224,16]
Dropping duplicated definition of variable KQ [0:6247,16]
Dropping duplicated definition of variable KQ [0:6256,16]
Side effects in initialization of unused variable sS [0:6846,40]
Side effects in initialization of unused variable zS [0:6858,40]
Side effects in initialization of unused variable VS [0:6933,40]
Side effects in initialization of unused variable WS [0:6933,56]
Side effects in initialization of unused variable lT [0:6982,40]
Dropping unreachable code [0:3597,8]
Declarations in unreachable code! [0:3597,8]

#### How To Reproduce

ng build library-name

#### Expected Behaviour

There should not be any warnings. Or when ng build reports warning at-least provide some sensible information (like file names, method names etc..)for a developer to fix them. Right now looking at the warning reported above I am not able to find out where to start.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            4.4.5
@angular/compiler:     7.0.1
rollup:                0.67.4
tsickle:               0.33.1
typescript:            3.1.1
rxjs: 6.3.3
node: 8.12.0
```

**Comment by dherges** [comment]
Hi @2RajShaikh,

can you tell whether the warnings are coming from rollup (EcmaScript bundles) or uglify-js (the UMD bundles)?

**Comment by 2RajShaikh** [comment]
Hi @dherges,

Looking at the complete logs it seems while minifying UMD bundles these warnings get reported.

Here is the complete log,

_ng build ktp-store_
Building Angular Package
Building entry point '@ktp/store'
Compiling TypeScript sources through ngc
Bundling to FESM2015
Bundling to FESM5
Bundling to UMD
Minifying UMD bundle
Dropping unreachable code [0:2023,8]
Declarations in unreachable code! [0:2023,8]
Dropping unreachable code [0:2066,12]
Declarations in unreachable code! [0:2066,12]
Dropping unreachable code [0:2172,8]
Declarations in unreachable code! [0:2172,8]
Dropping unreachable code [0:2247,8]
Declarations in unreachable code! [0:2247,8]
Dropping unreachable code [0:2275,8]
Declarations in unreachable code! [0:2275,8]
Dropping unreachable code [0:2282,8]
Declarations in unreachable code! [0:2282,8]
Dropping unreachable code [0:2538,8]
Declarations in unreachable code! [0:2538,8]
Dropping unreachable code [0:2568,8]
Declarations in unreachable code! [0:2568,8]
Dropping unreachable code [0:2849,8]
Declarations in unreachable code! [0:2849,8]
Dropping unreachable code [0:3185,8]
Declarations in unreachable code! [0:3185,8]
Side effects in initialization of unused variable nF [0:4241,40]
Side effects in initialization of unused variable UJ [0:4820,40]
Dropping unreachable code [0:5050,12]
Declarations in unreachable code! [0:5050,12]
Side effects in initialization of unused variable ZM [0:5262,40]
Side effects in initialization of unused variable AN [0:5356,57]
Side effects in initialization of unused variable HN [0:5373,57]
Side effects in initialization of unused variable eO [0:5433,57]
Side effects in initialization of unused variable zO [0:5530,40]
Side effects in initialization of unused variable LP [0:5917,40]
Dropping duplicated definition of variable AQ [0:6224,16]
Dropping duplicated definition of variable KQ [0:6247,16]
Dropping duplicated definition of variable KQ [0:6256,16]
Side effects in initialization of unused variable uS [0:6854,40]
Side effects in initialization of unused variable BS [0:6866,40]
Side effects in initialization of unused variable XS [0:6941,40]
Side effects in initialization of unused variable YS [0:6941,56]
Side effects in initialization of unused variable nT [0:6990,40]
Dropping unreachable code [0:3597,8]
Declarations in unreachable code! [0:3597,8]
Copying declaration files
Writing package metadata
Removing scripts section in package.json as it's considered a potential security vulnerability.
Built @ktp/store
Built Angular Package!

**Comment by blackSpiderMan** [comment]
I'm running into this as well. I've searched my entire code base and cannot find the variables named in the __Side effectis in...__ warning message (this includes searching the entirety of the built library package.)

**Comment by nayfin** [comment]
I'm getting similar bugs. I dug into my UMD bundle and the line referenced in the error is a pure function that is definitely being used. 

@dherges can you tell use some circumstances that might cause this error to be thrown and what the consequences of the error might be? As far as I can tell the code still works as intended. 

Also, thanks for all the work you folks put into this. I was using ng-packagr since before it was integrated into the cli, and I love how simple you folks have made packaging angular libraries!

**Comment by matheo** [comment]
@dherges first, thanks again for this awesome lib!
second, I'm having these too:
```
[build functions  ] Minifying UMD bundle
[build functions  ] Side effects in initialization of unused variable consts_1 [0:69,8]
[build functions  ] Side effects in initialization of unused variable consts_2 [0:70,8]
[build functions  ] Side effects in initialization of unused variable consts_3 [0:71,8]
[build functions  ] Side effects in initialization of unused variable consts_4 [0:72,8]
[build functions  ] Side effects in initialization of unused variable consts_5 [0:73,8]
[build functions  ] Side effects in initialization of unused variable firebase_1 [0:98,8]
[build functions  ] Side effects in initialization of unused variable firestore_2 [0:155,8]
[build functions  ] Side effects in initialization of unused variable common_1 [0:177,8]
[build functions  ] Side effects in initialization of unused variable common_2 [0:178,8]
[build functions  ] Side effects in initialization of unused variable common_3 [0:179,8]
[build functions  ] Side effects in initialization of unused variable common_4 [0:180,8]
[build functions  ] Side effects in initialization of unused variable common_5 [0:181,8]
[build functions  ] Side effects in initialization of unused variable common_6 [0:182,8]
[build functions  ] Side effects in initialization of unused variable common_7 [0:183,8]
[build functions  ] Side effects in initialization of unused variable emails_1 [0:259,8]
[build functions  ] Side effects in initialization of unused variable emails_2 [0:260,8]
[build functions  ] Side effects in initialization of unused variable formData_1 [0:315,8]
[build functions  ] Side effects in initialization of unused variable validations_1 [0:350,8]
[build functions  ] Side effects in initialization of unused variable request_1 [0:366,8]
[build functions  ] Side effects in initialization of unused variable request_2 [0:367,8]
[build functions  ] Side effects in initialization of unused variable threads_1 [0:409,8]
[build functions  ] Side effects in initialization of unused variable functions_1 [0:459,8]
[build functions  ] Side effects in initialization of unused variable tickets_1 [0:478,8]
[build functions  ] Side effects in initialization of unused variable tickets_2 [0:479,8]
[build functions  ] Side effects in initialization of unused variable tickets_3 [0:480,8]
[build functions  ] Side effects in initialization of unused variable tickets_4 [0:481,8]
[build functions  ] Side effects in initialization of unused variable esm5_1 [0:495,8]
[build functions  ] Copying declaration files
[build functions  ] Writing package metadata
```
I guess that an option to disable the `sideEffects` in the library `package.json` or `ng-package.json` would be good.

Also, searching about this issue, I saw that `UglifyJS` is the one reporting these, and there's an option to compress the dead-code. I'd like an option to just remove these unused variables that are generated in the umd.bundle like this:
```
unwrapExports(consts);
var consts_1 = consts.FORWARDED;
var consts_2 = consts.THREADS;
var consts_3 = consts.EMAILS;
var consts_4 = consts.SMS;
var consts_5 = consts.CALLS;
```
while my code is using them directly without needing these
```
email.text.split(common.FORWARDED)
```

**Comment by changhuixu** [comment]
same here. `Minifying UMD bundle` step has warnings about `Dropping side-effect-free statement`

Any ideas?
