### ISSUE TITLE
Disable opencollective in CI environments

### ISSUE THREAD

**Issue by macjohnny** [ng-packagr/ng-packagr#1178]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description
When installing / building a project with `ng-packagr` as a dependency in a CircleCI environment, the `npm install` part fails due to the following error:
```
> ng-packagr@4.4.5 postinstall /home/circleci/repo/node_modules/ng-packagr
> opencollective postinstall

sh: 1: opencollective: Permission denied
wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! ng-packagr@4.4.5 postinstall: `opencollective postinstall`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the ng-packagr@4.4.5 postinstall script.
```
See e.g. https://circleci.com/gh/bithost-gmbh/ngx-mat-select-search/114?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

I opened the following issue on opencollective: https://github.com/opencollective/opencollective-postinstall/issues/15

## Workaround
An easy workaround is to add the following to the `.circleci/config.yml`

```
jobs:
  build:
    ... 
    steps:
      ...
      - run: DISABLE_OPENCOLLECTIVE=true
      - run: npm install
```
See e.g. https://circleci.com/gh/bithost-gmbh/ngx-mat-select-search/115?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

## Suggested fix
Until https://github.com/opencollective/opencollective-postinstall/issues/15 is fixed, it should be detected whether the installation is running in a CircleCI environment and skip the opencollective postinstall script in https://github.com/ng-packagr/ng-packagr/blob/master/package.json#L136

**Comment by dherges** [comment]
1. Is it possible to run the script with per-env?

https://github.com/ericclemmons/per-env

2. Or include a custom postinstall.js script that checks for environment  variable.

```json
  "postinstall": "node postinstall"
```

```js
#!/usr/bin/env node

if (process.env.CI) {
  process.exit(0);
}

var spawnSync = require("child_process").spawnSync;

var args = ["posinstall"];

var result = spawnSync("opencollective", ["postinstall"], {
  cwd: process.cwd(),
  stdio: "inherit"
});

process.exit(result.status);
```




pro: Bash scripting in the postinstall would break on windows.

**Comment by macjohnny** [comment]
@dherges I think the second option you propose is fine. will you commit that?

**Comment by dherges** [comment]
@macjohnny Yes, "soon"

**Comment by mal90** [comment]
Is this fix released yet ? I am still getting the error with the latest 4.7.0 version.
![image](https://user-images.githubusercontent.com/8871285/52395122-e1204d00-2ad2-11e9-8450-bf69b31a0789.png)

**Comment by macjohnny** [comment]
@mal90 the fix is not included in `4.7.0`, but it will probably be included in the next release.
you can work around the issue by setting the environment variable `DISABLE_OPENCOLLECTIVE=true`

**Comment by mal90** [comment]
@macjohnny Thanks for the response. I have a question (pardon my ignorance) how can i set the DISABLE_OPENCOLLECTIVE=true locally ? I am running on a windows machine.

**Comment by macjohnny** [comment]
cmd: `set DISABLE_OPENCOLLECTIVE = "true"`

powershell: `$env:DISABLE_OPENCOLLECTIVE = "true"`

check it with command `printenv`

**Comment by mal90** [comment]
@macjohnny Thank you! I have set the environment variable. However i am still looking at the same error i've got earlier :|

![image](https://user-images.githubusercontent.com/8871285/52397469-b1297780-2adb-11e9-9ae0-1736d0b48ca7.png)

![image](https://user-images.githubusercontent.com/8871285/52397488-c0102a00-2adb-11e9-85eb-b77f70a80f9f.png)

**Comment by macjohnny** [comment]
@mal90 please post the full error log, since the relevant error message is not visible in your screenshot

**Comment by mal90** [comment]
Please find the full log below
```
npm WARN ng-packagr@4.7.0 requires a peer of tsickle@>=0.34.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ng-packagr@4.7.0 postinstall: `opencollective postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ng-packagr@4.7.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

**Comment by macjohnny** [comment]
@mal90 you need to install `tsickle`. Please run:
```
npm install tsickle
```
this has nothing to do with this issue

**Comment by mal90** [comment]
Thanks!. Indeed it was the issue ! Thanks alot. I guess i have missed it with the rest of the warnings. My bad.

**Comment by dev-xror** [comment]
@macjohnny I'm getting the same error when trying to install webpack globally... there's no specific errors to check..  I tried different approach which related to opencollective but with no luck... please help. :(

![image](https://user-images.githubusercontent.com/49257225/58103537-26afe400-7bb1-11e9-8e9a-d952abc558f4.png)
