### ISSUE TITLE
TypeScript 3.2 support

### ISSUE THREAD

**Issue by cyrilletuzi** [ng-packagr/ng-packagr#1181]
## Type of Issue

```
[x] Bug Report
```

## Description

`peerDependencies` about TypeScript 3.2 warning with Angular 7.2 and ng-packagr 4.4.5.

#### How To Reproduce

Install Angular 7.2 (`ng new`) and generate a library (`ng g library`).

#### Expected Behaviour

No warning.

Already fixed by @alan-agius4 in #1165, but wasn't released on npm.

**Comment by dherges** [comment]
being released in 4.5.0
