### ISSUE TITLE
Hooks in the build pipeline // Add afterWatchBuild cli flag

### ISSUE THREAD

**Issue by jimthedev** [ng-packagr/ng-packagr#1188]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

I am using ng-packagr in a monorepo to generate both Angular and React components plus a demo app that shows the usage of the various components. ng-packagr handles this well. The --watch cli option ensures that I can watch my directory for changes and re-run ng-packagr. The problem is that I'd love to be able to register a command to run each time the build completes following a watch trigger. The reason I want to do this is that I am copying the files to a place where my demo app can access them.  

#### Expected Behaviour

It seems like it should be possible but would probably require a new cli flag. Something like:

```
--afterWatchBuild 'cp -R ./dist ../../myfile'
```

**Comment by dherges** [comment]
I'd like a solution that's a little bit more generic: allow to register hooks in the build pipeline

**Comment by alan-agius4** [comment]
Closing as ng-packagr now support copying of assets.
