### ISSUE TITLE
Remove tsickle from direct peerDependencies

### ISSUE THREAD

**Issue by alan-agius4** [ng-packagr/ng-packagr#1202]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description
Users outside of Google don't usually need closure annotations hence `annotateForClosureCompiler`, should be turned off.

`tsickle` should be removed from the `peerDependencies` and it's usage should be similar to the one of `compiler-cli` https://github.com/angular/angular/blob/94e305f48e9f919f3163a50556f2fe9c517572dc/packages/compiler-cli/src/main.ts#L95

Related to: https://github.com/angular/angular-cli/pull/13546

**Comment by dherges** [comment]
Really? Once upon a time I read it was recommended to turn it on.

**Comment by alan-agius4** [comment]
Yup, unless you want your libraries to be compatable with Closure Compiler, there is no need to enable it.
