### ISSUE TITLE
Embedding specific packages into library bundle with ng-packagr?

### ISSUE THREAD

**Issue by slavafomin** [ng-packagr/ng-packagr#1205]
Hello!

Thank you for this great tool and your hard work.

I've done an extensive search and have tried several options (some of which appeared to be outdated), but couldn't achieve the desired result.

I have some internal packages that I want to embed into my library. It doesn't make any sense to distribute them as a standalone packages, therefore I don't want to add them to the `dependencies` or `peerDependencies`.

My `package.json` is looking like this:

```json
{
  "name": "@acme/library",
  "version": "0.0.0",
  "ngPackage": {
    "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
    "lib": {
      "entryFile": "index.ts"
    }
  },
  "peerDependencies": {
    "@angular/core": "^6"
  },
  "devDependencies": {
    "@angular/common": "^7.2.2",
    "@angular/compiler": "^7.2.2",
    "@angular/compiler-cli": "^7.2.2",
    "@angular/core": "^7.2.2",
    "ng-packagr": "^4.7.0",
    "tsickle": "^0.34.0",
    "tslib": "^1.9.3",
    "typescript": "^3.2.4",
    "@acme/internal": "0.0.0"
  },
  "bundledDependencies": [
    "@acme/internal"
  ]
}
```

As you can see I've added the `@acme/internal` package to the `devDependencies` and the `bundledDependencies` (as was suggested in one of the issues I've read), but whenever I build the library I can't find a source code of the `@acme/internal` in the generated files.

So, how do I actually embed the `@acme/internal` in my library?

Thanks!

**Comment by alan-agius4** [comment]
It will only get bundled in the UMD bundle. 

As for the other module formats `bundledDependencies` is the standard npm bundled dependencies which will preserve npm packages locally or have them available through a single file download.

See: https://docs.npmjs.com/files/package.json#bundleddependencies
