### ISSUE TITLE
Less executable not found in a monorepo with hoisted packages

### ISSUE THREAD

**Issue by henning96** [ng-packagr/ng-packagr#1206]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I'm using ng-packagr in a monorepo where dependencies are hoisted upwards. So, multiple packages depend on ng-packagr and those dependencies are hoisted upwards.
All of those packages use the less style processor. The problem is that since the incremental compilation feature was added to ng-packagr (which is really nice and helpful), the lessc executable is not found. It is expected to be in the node_modules folder of the package, but actually it is hoisted upwards. Therefore the compilation crashes.
I've took a short look at the code and the problematic line is in the file
`src/lib/ng-v5/entry-point/resources/stylesheet-processor.ts`, Line 59.
It expects the lessc executable to be in the node_modules directory of the current folder, but it isn't. It is hoisted.

#### How To Reproduce

This is quite simple. Just create a new monorepo with hoisted packages, for example with Yarn workspaces or Lerna. Create at least one package that uses ng-packagr and which dependencies are hoisted. Add at least one component with a less file to this package and build it. It will fail, because the lessc executable cannot be found.

#### Expected Behaviour
ng-packagr should also search for the lessc executable in an upper node_modules directory; not only in the current path.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 4.7.0
@angular/*: 6.1.10
typescript: 2.9.2
node: 11.8.0
yarn: 1.13.0
less: 3.9.0
```

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
