### ISSUE TITLE
Load dependencies from the project directory and not from monorepo's root

### ISSUE THREAD

**Issue by slavafomin** [ng-packagr/ng-packagr#1208]
Hello!

Thank you for this great tool!

However, we are using `ng-packagr` to build individual packages inside a monorepo repository.

The monorepo project is set up using [lerna](https://github.com/lerna/lerna) with [hoisting](https://github.com/lerna/lerna/blob/master/doc/hoist.md). This means that all dependencies of the individual packages are hoisted and put in the `node_modules` directory in the monorepo's root directory.

However, when one package's dependency version doesn't match the most commonly used one the individual version is installed in the `node_modules` directory of the specific package instead.

Node resolution algorithm is designed to load dependencies starting from the package's root and then going one level higher, until the installed module is found. So it will try to load the dependency from the package directory and then it will go to the monorepo's root.

I have the following directories:

- `./root/node_modules/typescript` <- here's the most commonly used typescript version
- `./root/my-package/node_modules/typescript` <- here's the specific typescript version used in the "my-package"

When I run the `ng-packagr -p package.json` inside of `./root/my-package` it's loading `typescript` dependency not from the package directory, but from monorepo's root. I think this happens because the `ng-packagr` dependency is itself hoisted to the monorepo's root.

This actually breaks the build, because in the root directory I have a newest version of the typescript, which is not supported by the Angular compiler.

I think that `ng-packagr` should load it's dependencies starting from the project directory where it's executed and not from directory where it's actually installed. This will allow to customize the dependencies on the package level.

What do you think?

Thanks!

**Comment by ike18t** [comment]
I was surprised when I ran into this as well. Is this the desired behavior? If so, what is the reasoning behind it?

Thanks,
Ike

**Comment by alan-agius4** [comment]
Hi all,

This is how Node.JS runtime module works. This is not specific to ng-packagr.
