### ISSUE TITLE
I get error when i run npm run packagr

### ISSUE THREAD

**Issue by kulandairaj** [ng-packagr/ng-packagr#1209]
## Type of Issue
>npm run packagr

Building Angular Package
error TS6046: Argument for '--lib' option must be: 'es5', 'es6', 'es2015', 'es7', 'es2016', 'es2017', 'esnext', 'dom', 'dom.iterable', 'webworker', 'scripthost', 'es2015.core', 'es2015.collection', 'es2015.generator', 'es2015.iterable', 'es2015.promise', 'es2015.proxy', 'es2015.reflect', 'es2015.symbol', 'es2015.symbol.wellknown', 'es2016.array.include', 'es2017.object', 'es2017.sharedmemory', 'es2017.string', 'es2017.intl', 'esnext.asynciterable'.

npm ERR! code ELIFECYCLE
npm ERR! errno 111
npm ERR! typescript-chat-client@0.0.0 packagr: `ng-packagr -p ng-package.json`
npm ERR! Exit status 111
npm ERR!
npm ERR! Failed at the typescript-chat-client@0.0.0 packagr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

#### Version Information

ng-packagr: 4.7.0
typescript: 3.3.1

**Comment by deebloo** [comment]
Can you share more info? Or perhaps create a minimally repeoducable repo folks can look at?

**Comment by kulandairaj** [comment]
this error gone when i install ng-packagr@2.0.0

**Comment by iAbhinav** [comment]
Installing v2 with angular 5 worked for me

```
npm i ng-packagr@2.0.0
```
