### ISSUE TITLE
Can't add whitelisted non peer dependencies when using the API

### ISSUE THREAD

**Issue by aekrylov** [ng-packagr/ng-packagr#1218]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

I'm using programmatic API to override tsconfig.json file. I also have dependencies that are not peer. Bulding the package fails saying something like 

```
...
Copying declaration files
Writing package metadata
Distributing npm packages with 'dependencies' is not recommended. Please consider adding @ng-bootstrap/ng-bootstrap to 'peerDependencies' or remove it from 'dependencies'.

Error: Dependency @ng-bootstrap/ng-bootstrap must be explicitly whitelisted.
BUILD ERROR
Dependency @ng-bootstrap/ng-bootstrap must be explicitly whitelisted.
```

Currently there's no way to use both tsconfig override and dependencies whitelist

#### How To Reproduce
There's no documented way to do what I want, one can check [JSON schema](https://github.com/ng-packagr/ng-packagr/blob/master/src/package.schema.json) and [TS typings](https://github.com/ng-packagr/ng-packagr/blob/master/src/lib/ng-v5/packagr.ts)

#### Expected Behaviour
I think it would be great If I could use all the features either in a json file or using the API

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 3.0.6
@angular/*: 5.2.11
typescript: 2.6.1
rxjs: 6.2.1
node: 11.7.0
npm/yarn: 6.0.1
```

**Comment by aekrylov** [comment]
Finally figured that out, it was a misunderstanding on my side. I was using `ng-package.json` as what the ts docs call "ng-package file", but specified my package.json in `forProject()`. With `forProject('ng-package.json')` I finally can use both json and API stuff.
Probably using `ng-package.json` should be documented more clearly?

**Comment by alan-agius4** [comment]
`package.json` is accepted in `forProject`
