### ISSUE TITLE
ngPackage.lib.languageLevel seems not working

### ISSUE THREAD

**Issue by aekrylov** [ng-packagr/ng-packagr#1219]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I use ngPackage.lib.languageLevel to include es2016 features, but ng-packagr compilation fails: 
```
> ng-packagr -p ng-package.json

Building Angular Package
Building entry point 'packager-language-level'
Rendering Stylesheets
Rendering Templates
Compiling TypeScript sources through ngc

BUILD ERROR
src/test.ts(3,27): error TS2339: Property 'includes' does not exist on type 'string[]'.
```

Although we can see clearly that `Array.includes` is present in es2016

#### How To Reproduce
See https://github.com/aekrylov/packager-language-level

#### Expected Behaviour
There should be no compilation errors since `Array.includes` is available in es2016

#### Version Information
```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 3.0.6
@angular/*: 5.2.11
typescript: 2.6.1
rxjs: 6.4.0
node: 11.7.0
npm/yarn: 6.0.1
```

**Comment by alan-agius4** [comment]
I don’t think there is a lib named es2016, as far as I recall it’s es2015, es2017 or es2018.

Can you try to change it?

(Sry but I am from my mobile)

**Comment by aekrylov** [comment]
@alan-agius4 `es2016` is a valid tsconfig target :) anyways, changing it to `es2017` gives same results. Moreover, passing incorrect values doesn't change anythinh either. Although if I move `ngPackage.lib` to the top level, languageLevel works properly.

**Comment by aekrylov** [comment]
Invalid `ng-package.json` usage, see https://github.com/ng-packagr/ng-packagr/issues/1218#issuecomment-465037049
