### ISSUE TITLE
Providing "umdId" is not enough and still have to use "umdModuleIds"

### ISSUE THREAD

**Issue by kkoo95** [ng-packagr/ng-packagr#1224]
## Type of Issue

```
[ ] Bug Report
[X] Feature Request
```

## Description

I have an angular workspace with 2 libraries (under `projects/` directory) _X_ and _Y_. _X_ has a dependency on _Y_ and it's declared in `peerDependencies`.

Because of the ``no name was provided for external module Y`` warning that I was getting during build of _X_, I ended up in the [doc](https://github.com/ng-packagr/ng-packagr/blob/master/docs/dependencies.md) and understood that an `umdId` must be provided explicitly (although i dont know why exactly, because i thought `rollup` would be able to guess a name from `package.name`, and mine is just plain alpha).

I tried to use `lib.umdId` in Y's in `ng-package.json` but it's not enough. I still get the warning. Is it expected ?
Must I repeat `lib.umdModuleIds.Y = "Y"`in all relevant `ng-package.json` ?

#### Version Information

```
ng-packagr:            4.7.1
@angular/compiler:     7.2.6
rollup:                0.67.4
tsickle:               0.34.3
typescript:            3.2.4
```

**Comment by alan-agius4** [comment]
Hi,

Yeah that is expected and you need to add the umdModuleIds of all your dependencies. If they are not guessed properly.

UmdId is different from umdModuleIds, the first being the id of the current library while they later is the used for the ids of dependencies.
