### ISSUE TITLE
peerDependency should install when u install the main package

### ISSUE THREAD

**Issue by mariohmol** [ng-packagr/ng-packagr#1226]
## Type of Issue

```
[ x ] Feature Request
```

## Description

I have a project with a peerDependency and when i install the module i expect that the peerdependencies should be installed as well.

#### How To Reproduce

I have a project called ng-brazil and this project uses another called js-brasil.

https://github.com/mariohmol/ng-brazil

Nowdays i have to ask the user to do a `npm i ng-brazil js-brasil`

#### Expected Behaviour

I would like to when i install ng-brazil, it installs js-brasil as well.

#### Version Information

```
ng-packagr:            4.4.5
@angular/compiler:     7.1.4
rollup:                0.67.4
tsickle:               0.27.2
typescript:            3.1.1
```

**Comment by deebloo** [comment]
This is how not works. Direct dependencies are installed when you install the package but peerDependencies require the and user to install the required package themselves. If you need that behaviour you should use dependencies instead.

**Comment by mariohmol** [comment]
Thanks for your answer.. 

nowdays i have 2 packegjson

https://github.com/mariohmol/ng-brazil/blob/master/package.json
https://github.com/mariohmol/ng-brazil/blob/master/ng-brazil/package.json

on each one should i have this on dependencies?

**Comment by mariohmol** [comment]
in the packagejson for the package.. i have as peer.. and in main packagejson i have as dependencies...

**Comment by mariohmol** [comment]
This is the message i have when including as dependencis in module 

``` Distributing npm packages with 'dependencies' is not recommended. Please consider adding js-brasil to 'peerDependencies' or remove it from 'dependencies'.

BUILD ERROR
Dependency js-brasil must be explicitly whitelisted.
Error: Dependency js-brasil must be explicitly whitelisted.```

**Comment by deebloo** [comment]
Yeah you will need to whitelist the package with ng-packagr. I don't remember the exact API I would check the documentation.

**Comment by mariohmol** [comment]
As i 'm using just package.json (and not ng-package.json) it worked that way

```
  "dependencies": {
    "js-brasil": ">=1.1.8"
  },
  "ngPackage": {
    "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
    "workingDirectory": "../.ng_build",
    "lib": {
      "entryFile": "src/public_api.ts"
    },
    "dest": "../dist/ng-brazil",
    "whitelistedNonPeerDependencies": [
      "js-brasil"
    ]
  }
```
https://github.com/mariohmol/ng-brazil/blob/master/ng-brazil/package.json#L31

Thanks for your support!!
