### ISSUE TITLE
Package.ts does not find whitelistedNonPeerDependencies during whitelistedNonPeerDependencies()

### ISSUE THREAD

**Issue by CraigHead** [ng-packagr/ng-packagr#1230]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

`ng-packagr` does not respect values in `whitelistedNonPeerDependencies` during `whitelistedNonPeerDependencies()` in `package.ts`

#### How To Reproduce

_A bug: please include instructions how to reproduce. Issues without reproduction are likely to receive no feedback._
Setup any `whitelistedNonPeerDependencies`  values in either the `ng-package.json` or `"ngPackage"` in `package.json`. 
e.g
` { ... "whitelistedNonPeerDependencies": [ "whatever you want"] ... } `

Set a breakpoint in package.ts on method public get `whitelistedNonPeerDependencies(): string[]` during 
`const value = (this.primary.$get('whitelistedNonPeerDependencies') as string[]) || defValue;`

`this.primary.$get('whitelistedNonPeerDependencies')` will return `undefined`. Thus, the new array that is initialized will always only contain `tslib`. 

_Can you reproduce the error in the integration tests in ng-packagr?_
**There are aren't any integration tests related to whitelistedNonPeerDependencies.**

_If possible, take a look at the [`integration/samples`](./integration/samples) and try to break one of these builds!_

_Is the error you faced in an application importing the library_
Yes. 

_Try to break the Angular CLI app in [`integration/consumers/ng-cli`](./integration/consumers/ng-cli)!_
Again, this failure doesn't have a integration/unit test. 

#### Expected Behaviour

_A bug: please describe what behaviour or result you expected_
I expected that values in whitelistedNonPeerDependencies would be respected. 

_A feature: do you have a first draft or an idea how to implement?_
I'm not sure what $get is supposed to do since that function returns undefined in a debugger. 

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 4.7.1
@angular/*: 6.0.x
typescript: 2.7.2
rxjs: 6.2.0
node: 9.11.2
npm: 5.6.0
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by alan-agius4** [comment]
Hi, can you provide the full configuration object please?

**Comment by alan-agius4** [comment]
Closing as no further details have been provided.
