### ISSUE TITLE
If you build a component library

### ISSUE THREAD

**Issue by jiayisheji** [ng-packagr/ng-packagr#1235]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

_A bug: please describe the error that you encountered_

I want to build a component library,
Increase ` material2 ` extension components,
I found a problem, if I have a few components, such as ` alert `, ` card ` etc.,
So I create a ` simple-lib ` component library,
How do I need in ` AppModule ` load one ` alert `,
Packaging will be the whole ` simple-lib ` packaged into ` main.js ` inside,
My reference ` material2 ` modify their format,
Found that it worked during development,
Packaging appears to find ` alert.module.js `,
How can I solve this problem?

_A feature: please describe your use case and motivation_

#### How To Reproduce

_A bug: please include instructions how to reproduce. Issues without reproduction are likely to receive no feedback._

_Can you reproduce the error in the integration tests in ng-packagr?_
_If possible, take a look at the [`integration/samples`](./integration/samples) and try to break one of these builds!_

_Is the error you faced in an application importing the library_
_Try to break the Angular CLI app in [`integration/consumers/ng-cli`](./integration/consumers/ng-cli)!_

#### Expected Behaviour

_A bug: please describe what behaviour or result you expected_
Can implement [material2-builds](https://github.com/angular/material2-builds)
_A feature: do you have a first draft or an idea how to implement?_

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            4.4.5
@angular/compiler:     7.0.0
rollup:                0.67.4
tsickle:               0.34.0
typescript:            3.1.3
node:                    8.11.1
npm:                     5.6.0
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by alan-agius4** [comment]
I'm sorry, but we don't understand the problem you are reporting.

If the problem persists, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

Thanks.
