### ISSUE TITLE
Make node-sass optional and allow support for dart-sass

### ISSUE THREAD

**Issue by Jordan-Hall** [ng-packagr/ng-packagr#1236]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

Angular cli uses node-sass as optional dependency which allows us to use dart-sass as an alternative.  I'm happy creating a PR which allows use to choice between node-sass and dart-sass. 

Companies tend to have to lock down internet access and 3rd party installation onto developers machines. As an alternative, many have to use painstaking workarounds or move over to dart-sass (npm sass) as it's a pure JavaScript implementation. We currently struggling to bind node-sass on our machines. As ng-packagr is a key package for Angular CLI i think it would be good to follow suite and allow each user to decide between dart-sass and node-sass

**Comment by alan-agius4** [comment]
I think this is a good idea. Go ahead a land a PR 😊
