### ISSUE TITLE
Document project structure

### ISSUE THREAD

**Issue by EdricChan03** [ng-packagr/ng-packagr#1245]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

Currently, contributing to this project can be hard especially for beginners like me who do not understand the project structure.

#### How To Reproduce

Put yourself into a beginner's shoes.

Let's say you want to contribute code to resolve a feature request (something like #1180, which introduces support for schematics and is most probably a wanted feature for Angular library devs).

Usually, most people would look at the [contributing guide](https://github.com/ng-packagr/ng-packagr/blob/master/CONTRIBUTING.md) located at the project's root.

Looking at the contributing guide, you will see a link to the developer guide. Clicking on that link will lead to a poorly documented [developer guide](https://github.com/ng-packagr/ng-packagr/blob/master/docs/DEVELOP.md) for beginners with no documentation whatsoever on the project structure.

You would then be stuck as to what to do, or maybe you'll look at the `src` folder since there's where the source code for the project would be. Clicking on it, you find that there's 2 folders and 7 files.

Since you want to contribute to the inner library, you then click on the `lib` folder, which leads you to even _more_ folders and files, which confuses you. You are unsure as to what to do now.

_P.S. Sorry for the long story. :sweat_smile:_

#### Expected Behaviour

I suggest a simple document on the project's structure. It can be in the `DEVELOP.md` file, or in the `CONTRIBUTING.md` file. It should also be easy to understand for beginners who would like to contribute back to the project.

#### Version Information

NIL

**Comment by alan-agius4** [comment]
If you're interested in contributing, starting with small bug fixes is a great way to get familiar with the codebase without needing to fully grasp the entire project structure. On the other hand, if you plan to implement a major feature, you'll likely need to create a design document and engage in discussions to make sure your work aligns with the project's architecture and goals before diving into the code.
