### ISSUE TITLE
Can't build the library which uses directive with output

### ISSUE THREAD

**Issue by vorant94** [ng-packagr/ng-packagr#1247]
## Type of Issue

```
[x] Bug Report
```

## Description

_When I create directive in custom library with some output event emiter it works perfectly for serving app, but when I try to build lib I get error_ `Directive ɵf, Expected 1 arguments, but got 0.` _despite the fact that this directive has no inputs, only one output_

#### How To Reproduce

_1) generate new angular app and library inside it
2) generate directive in this library with 1 output and no inputs
3) use this directive in library component template
4) try to build your library_

#### Expected Behaviour

_it should normally build library just like angular app normally build itself with using the same directory only generated inside the app_

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: ~0.10.0
@angular/*: ~7.0.0
typescript: ~3.1.1
rxjs: ~6.3.3
node: v10.13.0
npm: 6.9.0
```

**Comment by alan-agius4** [comment]
Kindly see: https://github.com/500tech/angular-tree-component/issues/534

**Comment by alan-agius4** [comment]
This is not an ng-packagr issue.

Most likely you have a missing parameter from an event handler.

Certain thing that work in an application might not work at a library level. Since the later is more strict.
