### ISSUE TITLE
Can't use regular expression literals on static fields in a component in a library

### ISSUE THREAD

**Issue by pmattke** [ng-packagr/ng-packagr#1251]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

If you have a library generated by angular CLI and you add a static field to one of the components in the library und want to initialize the field with regular expression literal, it won't compile:

```typescript
static regex = /asdf/gi;
```

This will break when you try to compile the library.

The following instead works:

```typescript
static regex2 = new RegExp("asdf", "gi");
```

The reported error is:

Error encountered in metadata generated for exported symbol 'MyLibComponent'

Metadata collected contains an error that will be reported at runtime: Expression form not supported.

#### How To Reproduce

Here is a repo that contains a sample project that can reproduce the issue. It was created using angular CLI using `ng generate library my-lib`:

https://gitlab.com/pmattke/ng-packagr-regex-issue

#### Expected Behaviour

Library should compile if I am using regular expression literals with correct syntax.

#### Version Information

```
ng-packagr:            4.7.1
@angular/compiler:     7.2.11
rollup:                0.67.4
tsickle:               0.34.3
typescript:            3.2.4
```

**Comment by alan-agius4** [comment]
Hi, I am sorry but this syntax is not supported by the NGC compiler. Running `ngc` directly does fail as well. Hence, it's not a problem related to ng-packagr.

Thanks.
