### ISSUE TITLE
 Compound selectors may no longer be extended.

### ISSUE THREAD

**Issue by kambbado** [ng-packagr/ng-packagr#1253]
## Type of Issue

Version 5.0.1 generates 

> Compound selectors may no longer be extended

 errors when running **ng serve** 

I have to revert to 4.7.1 to run my application

```
[X ] Bug Report
[ ] Feature Request
```

## Description

_A bug: please describe the error that you encountered_

```
ERROR in ./src/scss/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/scss/styles.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

undefined
                       ^
      Compound selectors may no longer be extended.
Consider `@extend .k-button, ::before` instead.
See http://bit.ly/ExtendCompound for details.

    ╷
101 │                 @extend .k-button::before;
    │                         ^^^^^^^^^^^^^^^^^
    ╵
  node_modules\@progress\kendo-theme-bootstrap\modules\@progress\kendo-theme-default\scss\toolbar\_layout.scss 101:25  root stylesheet
      in D:\TFS\Portal\Portal-Request\Portal.Web\node_modules\@progress\kendo-theme-bootstrap\modules\@progress\kendo-theme-default\scss\toolbar\_layout.scss (line 101, column 25)
i ｢wdm｣: Failed to compile.
```

#### How To Reproduce

_A bug: please include instructions how to reproduce. Issues without reproduction are likely to receive no feedback._

package.json

> "dependencies": {
    "@angular/animations": "^7.2.11",
    "@angular/cdk": "^7.3.6",
    "@angular/common": "^7.2.11",
    "@angular/compiler": "^7.2.11",
    "@angular/core": "^7.2.11",
    "@angular/flex-layout": "^7.0.0-beta.24",
    "@angular/forms": "^7.2.11",
    "@angular/http": "^7.2.11",
    "@angular/material": "^7.3.6",
    "@angular/platform-browser": "^7.2.11",
    "@angular/platform-browser-dynamic": "^7.2.11",
    "@angular/pwa": "^0.13.7",
    "@angular/router": "^7.2.11",
    "@angular/service-worker": "^7.2.11",
    "@progress/kendo-angular-buttons": "^4.3.3",
    "@progress/kendo-angular-dateinputs": "^3.7.1",
    "@progress/kendo-angular-dialog": "^3.11.0",
    "@progress/kendo-angular-dropdowns": "^3.5.2",
    "@progress/kendo-angular-excel-export": "^2.3.0",
    "@progress/kendo-angular-gauges": "^2.4.1",
    "@progress/kendo-angular-grid": "^3.13.1",
    "@progress/kendo-angular-inputs": "^4.2.1",
    "@progress/kendo-angular-intl": "^1.7.0",
    "@progress/kendo-angular-l10n": "^1.3.0",
    "@progress/kendo-angular-label": "^1.3.0",
    "@progress/kendo-angular-layout": "^3.3.0",
    "@progress/kendo-angular-menu": "^1.2.0",
    "@progress/kendo-angular-popup": "^2.5.0",
    "@progress/kendo-angular-resize-sensor": "^3.1.2",
    "@progress/kendo-angular-ripple": "^1.1.1",
    "@progress/kendo-angular-toolbar": "^1.1.0",
    "@progress/kendo-angular-treeview": "^3.1.0",
    "@progress/kendo-angular-upload": "^4.2.2",
    "@progress/kendo-data-query": "^1.5.1",
    "@progress/kendo-date-math": "^1.4.0",
    "@progress/kendo-drawing": "^1.5.9",
    "@progress/kendo-file-saver": "^1.0.7",
    "@progress/kendo-theme-bootstrap": "3.2.3",
    "@progress/kendo-theme-default": "^3.3.1",
    "@progress/kendo-theme-material": "^2.3.1",
    "@progress/kendo-ui": "^2019.1.327",
    "@telerik/kendo-intl": "^1.4.4",
    "@types/leaflet": "^1.4.3",
    "@types/leaflet.gridlayer.googlemutant": "^0.4.4",
    "@types/leaflet-polylinedecorator": "^1.1.3",
    "bootstrap": "^4.3.1",
    "browserify": "^16.2.3",
    "classlist.js": "^1.1.20150312",
    "cldr-data": "^34.0.0",
    "core-js": "^2.6.5",
    "enhanced-resolve": "^4.1.0",
    "govuk-frontend": "^2.9.0",
    "hammerjs": "^2.0.8",
    "install": "^0.12.2",
    "jwt-decode": "^2.2.0",
    "leaflet": "^1.4.0",
    "leaflet.gridlayer.googlemutant": "^0.8.0",
    "leaflet.markercluster": "^1.4.1",
    "leaflet-bing-layer": "^3.3.0",
    "leaflet-polylinedecorator": "^1.6.0",
    "minimatch": "^3.0.4",
    "moment": "^2.24.0",
    "ngx-bootstrap": "^3.2.0",
    "ngx-webstorage": "^3.0.2",
    "npm": "^6.9.0",
    "progress-tracker": "^1.4.0",
    "rxjs": "^6.4.0",
    "simple-line-icons": "^2.4.1",
    "typescript-collections": "^1.3.2",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.9.0"
  },
  "devDependencies": {
    "@angular/cli": "^7.3.7",
    "@angular/compiler-cli": "^7.2.11",
    "@angular/language-service": "^7.2.11",
    "@angular-devkit/build-angular": "^0.13.7",
    "@angular-devkit/build-ng-packagr": "^0.13.7",
    "@angular-devkit/build-optimizer": "^0.13.7",
    "@angular-devkit/schematics": "^7.3.7",
    "@angular-devkit/schematics-cli": "^0.13.7",
    "@cypress/webpack-preprocessor": "^4.0.3",
    "@fortawesome/fontawesome-free": "^5.8.1",
    "@types/jasmine": "^3.3.9",
    "@types/jasminewd2": "^2.0.6",
    "@types/node": "^11.10.5",
    "codelyzer": "^5.0.0",
    "cypress": "^3.2.0",
    "jasmine": "^3.3.1",
    "jasmine-core": "^3.3.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^4.0.1",
    "karma-chrome-launcher": "^2.2.0",
    "karma-cli": "^2.0.0",
    "karma-coverage-istanbul-reporter": "^2.0.5",
    "karma-jasmine": "^2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "ng-packagr": "4.7.1",
    "node-sass": "^4.11.0",
    "popper.js": "^1.14.7",
    "postcss-loader": "^3.0.0",
    "protractor": "^6.0.0",
    "rxjs-tslint": "^0.1.7",
    "sass-loader": "^7.1.0",
    "tsickle": ">=0.34.3",
    "tslib": "^1.9.3",
    "tslint": "^5.14.0",
    "ts-loader": "^5.3.3",
    "ts-node": "^8.0.3",
    "typescript": "3.3.1",
    "webpack-bundle-analyzer": "^3.1.0"
  }

_Can you reproduce the error in the integration tests in ng-packagr?_
I don't use ng-packagr, just installed it

_Is the error you faced in an application importing the library_
I have identified it to the 5.0x version the ng-packagr 

#### Expected Behaviour

_A bug: please describe what behaviour or result you expected_

To work like previous versions, why would installing a package break the build?

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            4.7.1
@angular/compiler:     7.2.11
rollup:                0.67.4
tsickle:               0.34.3
typescript:        3.3.1
rxjs:                6.6.0
node:             11.4.0
npm:              6.9.0
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by alan-agius4** [comment]
This is expected kindly see the changelog https://github.com/ng-packagr/ng-packagr/blob/master/CHANGELOG.md#breaking-changes

You can go back to the previous behaviour by installing node-sass.

**Comment by Eljah** [comment]
npm install node-sass --save-dev , right, not just --save ?

**Comment by Eljah** [comment]
should i remove a norma sass also, or I may leave sass and node-sass together?

**Comment by Eljah** [comment]
so, I had to remove 'sass' (default for dart-sass) and to point node-sass from the webpack like this: 

const sass = require('node-sass');

  {
            test: /\.scss$/,
            use: ['to-string-loader', 'css-loader', {
                loader: 'sass-loader',
                options: { implementation: sass }
            }],
            exclude: /(vendor\.scss|global\.scss)/
        },
