### ISSUE TITLE
npm run packagr  "Cannot read property ngPackage of Undefined"

### ISSUE THREAD

**Issue by SaranVairam** [ng-packagr/ng-packagr#1255]
## Undefined Issue

```
BUILD ERROR
Cannot read property 'ngPackage' of undefined
TypeError: Cannot read property 'ngPackage' of undefined
    at Object.<anonymous> (path\node_module
s\ng-packagr\lib\ng-v5\discover-packages.js:37:20)
    at Generator.next (<anonymous>)
    at fulfilled (path\node_modules\ng-pack
agr\lib\ng-v5\discover-packages.js:4:58)
    at <anonymous>
```

## Cannot read property of undefined in discover-packages.js

_A bug: Cannot read property of undefined in discover-packages.js
error getting on running npm-run pcakagr

_A feature: please describe your use case and motivation_

#### How To Reproduce

_A bug: please include instructions how to reproduce. Issues without reproduction are likely to receive no feedback._

_Can you reproduce the error in the integration tests in ng-packagr?_
_If possible, take a look at the [`integration/samples`](./integration/samples) and try to break one of these builds!_

_Is the error you faced in an application importing the library_
_Try to break the Angular CLI app in [`integration/consumers/ng-cli`](./integration/consumers/ng-cli)!_

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 5.0.1
@angular/*: 7.X
typescript: 3.2.2
rxjs: 6.3.3
node:8.12
npm/yarn: 1.12.3
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by alan-agius4** [comment]
This seems like a bug that we should handle more gracefully. Do you have invalid `package.json`
