### ISSUE TITLE
Aot compilation issue?

### ISSUE THREAD

**Issue by kumaresan-subramani** [ng-packagr/ng-packagr#1261]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I have created npm packages using 'ng-packagr'. using created package. i have created one sample. it is running fine in dev mode but if i run that sample in prod mode it throws below error:

> ERROR TypeError: Cannot read property 'viewContainerRef' of undefined

In My sample i have used **ng-template**

`
    <ejs-listview id='listview_template' #listviewInstance [dataSource]='dataSource' [cssClass]='cssClass'
[headerTitle]='headerTitle' (actionComplete)='onActionComplete($event)' [showHeader]='true'>
<ng-template #template let-dataSource="">

    <div class="{{dataSource.category ? 'clearfix desc e-list-wrapper e-list-multi-line e-list-avatar' : 'clearfix e-list-wrapper e-list-multi-line e-list-avatar'}}">
        <span *ngIf="dataSource.imgSrc !== ''" class="e-avatar e-avatar-{{dataSource.imgSrc}}"></span>
        <span class="e-list-item-header">{{dataSource.title}} </span>
        <span class="e-list-content e-text-overflow" [innerHTML]="dataSource.description"></span>
        <div id="list-logo" *ngIf="dataSource.timeStamp !== ''">
            <span class="bookmark"></span>
            <span class="comments"></span>
            <span class="share"></span>
        </div>
        <div class="timeStamp" *ngIf="dataSource.timeStamp !== ''">{{dataSource.timeStamp}}</div>
    </div>
</ng-template>
</ejs-listview>`

**Comment by kumaresan-subramani** [comment]
Any update on this

**Comment by alan-agius4** [comment]
Hi, this doesn't look like an issue caused by ng-packagr. 

If that's not the case kindly open a new issue with a minimal reproduction.

Thanks

**Comment by kumaresan-subramani** [comment]
Hi @alan-agius4 ,

I have solved this issue.

My issue is in **my third-party angular package**

In my package, i have 

> "sideEffects": true,

Due to this, while AOT compilation ng-template not working

When i turn it into false , my app working fine. is there any problem in it?

**Comment by kumaresan-subramani** [comment]
Any update on this?
