### ISSUE TITLE
Unable to get styles bundled using styleIncludePaths option

### ISSUE THREAD

**Issue by parky128** [ng-packagr/ng-packagr#1262]
I am attempting to build a component library with angular 7 and am having trouble getting my style files included in the generated dist folder.

My library project structure is as follows.

[![enter image description here][1]][1]

**styles.scss**

    @import "~primeicons/primeicons.css";
    @import "~primeng/resources/themes/nova-light/theme.css";
    @import "~primeng/resources/primeng.min.css";
    @import "~@al/design/styles/palette";
    @import "~@al/design/styles/utility";
    
    body {
      color: red;
    }

I have added `styleIncludePaths` to my ng-package.json as follows:

    {
      "$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
      "dest": "../../dist/design-client",
      "lib": {
        "entryFile": "src/public-api.ts",
        "styleIncludePaths": ["src/styles"]
      }
    }

But this does not add the styles alongside my generated output after running a build:

[![enter image description here][2]][2]

What am I doing wrong? Thanks

  [1]: https://i.stack.imgur.com/WIbAZ.png
  [2]: https://i.stack.imgur.com/iiuyg.png

**Comment by alan-agius4** [comment]
Hi, that is because styleIncludePaths is indented for something else.

See: https://github.com/ng-packagr/ng-packagr/blob/master/docs/style-include-paths.md and https://github.com/sass/node-sass/blob/master/README.md#includepaths

At the moment there is no support for sass bundling within ng packagr.

**Comment by alan-agius4** [comment]
Related to https://github.com/ng-packagr/ng-packagr/issues/123#issuecomment-330029214

**Comment by parky128** [comment]
Ok thanks for that, I will implement a post build step as per some of those suggestions in the comment.
