### ISSUE TITLE
LESS version mismatch

### ISSUE THREAD

**Issue by nfiles** [ng-packagr/ng-packagr#1276]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

While converting an Angular 6 library to use `ng-packagr`, I received this error message:

> Unable to interpret argument less-plugin-npm-import - if it is a plugin (less-plugin-less-plugin-npm-import), make sure that it is installed under or at the same level as less

The issue seems to be that `ng-packagr` requires `less@^3.8.0`, and my project was already using `less@2.3.1`. For processing LESS files, the [stylesheet-processor.ts](https://github.com/ng-packagr/ng-packagr/blob/master/src/lib/ng-v5/entry-point/resources/stylesheet-processor.ts#L74) uses a direct path into `node_modules/less/bin/lessc`, which pointed to my project's local `less@2.3.1` package, not the expected `less@^3.8.0`. Since these two versions have slightly different methods for specifying plugins in CLI arguments, the process failed.

This bug could be avoided by including the expected version of `less` (currently `less@^3.8.0`) as a peer dependency.

Related: PR #1060 

#### How To Reproduce

1. Create an angular project using the `ng new` command
2. Install a local dependency on `less@2.3.1`
3. Generate a library with `ng g library testlib`
4. Add a LESS stylesheet to the library
5. Try to build the `testlib` library with `ng build testlib`

#### Expected Behaviour

The `ng-packagr` package should specify that it expects `less@^3.8.0` to be installed as a peer dependency.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            4.7.1
@angular/compiler:     6.1.10
rollup:                0.67.4
tsickle:               0.32.1
typescript:            2.9.2

$ npm ls less
+-- @angular-devkit/build-angular@0.6.8
| `-- less@3.9.0
+-- less@2.3.1
`-- ng-packagr@4.7.1
  `-- less@3.9.0
```

**Comment by nfiles** [comment]
I would be happy to submit this change as a PR :)

**Comment by alan-agius4** [comment]
Actually rather than a peerDependency the ideal solution should be resolve the less binary path using `require.resolve` as changing that to a peer would be result in a breaking change.

**Comment by alan-agius4** [comment]
PRs welcome!

**Comment by JoostK** [comment]
@alan-agius4 I was just going to type that... :P

**Comment by nfiles** [comment]
Awesome! I'll take a look at this as soon as I can. :+1:
