### ISSUE TITLE
ng-packagr & angular 8 ivy

### ISSUE THREAD

**Issue by jmbarbier** [ng-packagr/ng-packagr#1278]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

This is a duplicate of https://github.com/angular/angular/issues/30265 as this may be a ng-packagr issue.

Testing with angular 8, ivy enabled.
Building a library created with `ng g library` and using it within another angular 8 project with ivy enabled raises an error
<pre><code>
core.js:7182 ERROR Error: Template error: Can't bind to 'ngIf' since it isn't a known property of 'p'.
    at createUnknownPropertyError (core.js:12560)
    at elementPropertyInternal (core.js:12426)
    at Module.ɵɵproperty (core.js:16519)
    at MylibComponent_Template (mylib.js:24)
    at executeTemplate (core.js:11998)
    at checkView (core.js:13349)
    at componentRefresh (core.js:13113)
    at refreshChildComponents (core.js:11701)
    at refreshDescendantViews (core.js:11607)
    at checkView (core.js:13350)
</code></pre>

#### How To Reproduce

The steps are given in https://github.com/angular/angular/issues/30265

summary : using angular 8 rc 2/3 fresh projects with --enable-ivy 

- create a lib with `ng g library mylib`, add an *ngIf somewhere in the template
- build this lib with `ng build mylib`
- use it in another fresh ng8 ivy project
- the above error appears on `ng serve`
- using ng build --prod or ng serve --prod, no error is raised, but the *ngIf part is skipped

#### Expected Behaviour

The library should be usable

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            5.1.0
@angular/compiler:     8.0.0-rc.3
rollup:                1.11.3
tsickle:               
typescript:            3.4.5
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by alan-agius4** [comment]
From ng-packagr perspective Ivy is no different than View Engine. As a matter of fact, ng-packagr doesn’t generate Ivy code. But rather VE code which is later transformed by NGCC in Angular CLI to make the library Ivy Compatible.

I believe that this issue is more related to NGCC. Better have a single issue tracked in the angular repo.
