### ISSUE TITLE
ng-packagr includes libraries into the build

### ISSUE THREAD

**Issue by ng-state** [ng-packagr/ng-packagr#1287]
Hi,

I hav a library X with import of other library. But that import is not relative path it is just how any other imports from node_modules 
``` import { A } from '@A/A'```

This totally works fine in development because i can specify pth in tsconfig.json but when building i library X, library @A/A is included into built sources of library X which i do no twant because @A is published separatly. I was tring to add paths and ignores to tsconfigs, i was removing all paths and configs from tsconfigs and angular.json files but nothing works. The only waythat works if to physically removing projects folder from root folder. Seems like ng-packagr somehow "magically" finds library @A/A if that library in the same root.

Is there any way to make ng-packagr not to include dependency libraries into build of library X?

**Comment by ng-state** [comment]
Finally i moved my library X to projects folder and issue is gone. However not sre if library dependencies would not be incuded when building app not library.

**Comment by alan-agius4** [comment]
I think what you are asking is explain here: https://github.com/ng-packagr/ng-packagr/issues/1106

If it's not the case please open an issue with a reproduction.

Thanks.

**Comment by ng-state** [comment]
Hi, thanks for response. 
However it looks lik emy problem was oposite - in issue you have pointed guy says that highchart is not bundled into final build. nmy case problem was that dependent library was included into final build and i did no want that.

**Comment by alan-agius4** [comment]
Can you kindly provide a reproduction? Also, which version of ng-packagr are you using?

**Comment by ng-state** [comment]
I am usng "@angular-devkit/build-ng-packagr": "^0.13.6",

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
