### ISSUE TITLE
Add support for pug/jade templates 

### ISSUE THREAD

**Issue by neilsoult** [ng-packagr/ng-packagr#1291]
## Type of Issue

```
[ ] Bug Report
[X] Feature Request
```

## Description

I know that pug/jade templating has fallen out of favor with the general development community, but there are still a (smallish?) set of devs that still prefer it to html. It would be nice to add a small bit of code to handle pug and jade templates, similar to the way css preprocessors are handled.

https://github.com/crexi-dev/ng-packagr/pull/1/files

#### Expected Behaviour

I have a fork and working version already. The code changes are fairly minimal. I would be glad to create a PR for this if this is something the maintainers would like to add.

new package requirements: 
`"pug": "^2.0.3"`

**Comment by alan-agius4** [comment]
Hi, thanks for your interest, however this is currently out of scope of ng-packagr as pug templates are also not supported by the Angular CLI.

**Comment by giniedp** [comment]
@alan-agius4 but it is supported by using a custom builder for example with https://github.com/just-jeb/angular-builders

It would be great if we could have a hook to transform source files, or is there one already?

**Comment by matheo** [comment]
@giniedp did you find a nice workflow?
I have my own build script to use `@crexi-dev/ng-packagr` but I'm looking forward an Angular builder.

It's sad that we don't have this simple support in `ng-packagr` to be able to support pug out of the box.

**Comment by giniedp** [comment]
No, i am still using a custom angular build chain in my main project because of this.

**Comment by neilsoult** [comment]
Just to update those that are interested, we switched our configuration to use `@angular-builders/custom-webpack`, which enabled us to use our own custom webpack config. This is a much easier and less obtrusive method than having to maintain a fork of ng-packagr.
Here is a sample webpack config we use: https://gist.github.com/neilsoult/1f3ea690f9fbe79f13ddb7f160781805
and we adjust our angular.json file as such: 
```
      "architect": {
        "build": {
          "builder": "@angular-builders/custom-webpack:browser",
          "options": {
            "customWebpackConfig": {
              "path": "./custom-webpack.config.js"
            },
...
```
and for `serve`, you can use `"builder": "@angular-builders/custom-webpack:dev-server"`

hope this helps!

**Comment by giniedp** [comment]
@neilsoult yes, custom-webpack does works for apps. But it does not for libraries when building with `@angular-devkit/build-ng-packagr` builder.

https://github.com/just-jeb/angular-builders/issues/238

**Comment by neilsoult** [comment]
oh yes, my apologies, I had completely forgotten the context of the original issue 😊
