### ISSUE TITLE
while using version 2.4.2 to generate angular package it throws error "Error: ng.readConfiguration is not a function:"

### ISSUE THREAD

**Issue by kumaresan-subramani** [ng-packagr/ng-packagr#1299]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

while try to generate angular package for my typescript package using ng-package@2.4.2 it throws below error:

> D:\workspace\components\ej2-grid-components\third-party\angular>npm run packagr

> @syncfusion/ej2-angular-grids@17.1.1 packagr D:\workspace\components\ej2-grid-components\third-party\angular
> ng-packagr -p ng-package.json && gulp npmrc-changelog-schematics-injection && gulp path-change

> D:\workspace\components\ej2-grid-components\third-party\angular\node_modules\injection-js\injection.bundle.js:1662
>             throw e;
>             ^

> Error: ng.readConfiguration is not a function: Error during instantiation of InjectionToken ng.v5.defaultTsConfig! (InjectionToken ng.v5.packageTransform -> InjectionToken ng.v5.initTsConfigTransform -> InjectionToken ng.v5.defaultTsConfig).
>     at wrappedError (D:\workspace\components\ej2-grid-components\third-party\angular\node_modules\injection-js\injection.bundle.js:512:17)
>     at injectionError (D:\workspace\components\ej2-grid-components\third-party\angular\node_modules\injection-js\injection.bundle.js:544:34)
>     at instantiationError (D:\workspace\components\ej2-grid-components\third-party\angular\node_modules\injection-js\injection.bundle.js:626:12)
>     at ReflectiveInjector_._instantiate (D:\workspace\components\ej2-grid-components\third-party\angular\node_modules\injection-js\injection.bundle.js:1669:19)
>     at ReflectiveInjector_._instantiateProvider (D:\workspace\components\ej2-grid-components\third-party\angular\node_modules\injection-js\injection.bundle.js:1647:25)
>     at ReflectiveInjector_._new (D:\workspace\components\ej2-grid-components\third-party\angular\node_modules\injection-js\injection.bundle.js:1635:21)
>     at ReflectiveInjector_._getObjByKeyId (D:\workspace\components\ej2-grid-components\third-party\angular\node_modules\injection-js\injection.bundle.js:1691:41)
>     at ReflectiveInjector_._getByKeyDefault (D:\workspace\components\ej2-grid-components\third-party\angular\node_modules\injection-js\injection.bundle.js:1723:28)
>     at ReflectiveInjector_._getByKey (D:\workspace\components\ej2-grid-components\third-party\angular\node_modules\injection-js\injection.bundle.js:1684:25)
>     at ReflectiveInjector_._getByReflectiveDependency (D:\workspace\components\ej2-grid-components\third-party\angular\node_modules\injection-js\injection.bundle.js:1674:21)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! @syncfusion/ej2-angular-grids@17.1.1 packagr: `ng-packagr -p ng-package.json && gulp npmrc-changelog-schematics-injection && gulp path-change`
> npm ERR! Exit status 1

#### How To Reproduce

_A bug: please include instructions how to reproduce. Issues without reproduction are likely to receive no feedback._

_Can you reproduce the error in the integration tests in ng-packagr?_
_If possible, take a look at the [`integration/samples`](./integration/samples) and try to break one of these builds!_

_Is the error you faced in an application importing the library_
_Try to break the Angular CLI app in [`integration/consumers/ng-cli`](./integration/consumers/ng-cli)!_

**But working fine while using ng-packagr 1.5.0 and 1.7.0 till 2.0.0**
#### Expected Behaviour

need to generate package without error

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 2.4.2
"@angular-devkit/schematics": "0.7.2",
        "@angular/common": "2.2.1 - 4.10.0",
        "@angular/compiler": "^7.2.15",
        "@angular/compiler-cli": "^4.4.7",
        "@angular/core": "2.2.1 - 4.10.0",
        "@angular/forms": "2.2.1 - 4.10.0",
        "@angular/http": "2.2.1 - 4.10.0",
        "@angular/platform-browser": "2.2.1 - 4.10.0",
        "@angular/platform-browser-dynamic": "2.2.1 - 4.10.0",
        "@angular/platform-server": "2.2.1 - 4.10.0",
        "@angular/router": "2.2.1 - 4.10.0",
        "@schematics/angular": "0.7.2",
typescript: 2.7.2
rxjs: x.y.z
node: 8.11.3
npm/yarn: x.y.z
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by kumaresan-subramani** [comment]
### reason why i create this issue

https://github.com/angular/angular-cli/issues/13171

**Comment by kumaresan-subramani** [comment]
https://github.com/ng-packagr/ng-packagr/issues/1164

**Comment by alan-agius4** [comment]
ng-packagr version 2 only supports Angular 5. Kindly update to ng-packagr version 5.


Thanks

**Comment by kumaresan-subramani** [comment]
if i install ng-packagr version 5.2.0, it throws below error:

> D:\workspace\components\ej2-grid-components\third-party\angular>npm run packagr

> @syncfusion/ej2-angular-grids@17.1.1 packagr D:\workspace\components\ej2-grid-components\third-party\angular
> ng-packagr -p ng-package.json && gulp npmrc-changelog-schematics-injection && gulp path-change

> D:\workspace\components\ej2-grid-components\third-party\angular\node_modules\ng-packagr\lib\ng-v5\packagr.js:101
>         return rxjs_1.of(new build_graph_1.BuildGraph()).pipe(buildTransformOperator, operators_1.catchError(err => {
>                       ^

> TypeError: rxjs_1.of is not a function
>     at NgPackagr.buildAsObservable (D:\workspace\components\ej2-grid-components\third-party\angular\node_modules\ng-packagr\lib\ng-v5\packagr.js:101:23)
>     at NgPackagr.build (D:\workspace\components\ej2-grid-components\third-party\angular\node_modules\ng-packagr\lib\ng-v5\packagr.js:82:21)
>     at exports.build.opts (D:\workspace\components\ej2-grid-components\third-party\angular\node_modules\ng-packagr\lib\commands\build.command.js:13:6)
>     at Object.execute (D:\workspace\components\ej2-grid-components\third-party\angular\node_modules\ng-packagr\lib\commands\command.js:9:27)
>     at Object.<anonymous> (D:\workspace\components\ej2-grid-components\third-party\angular\node_modules\ng-packagr\cli\main.js:28:14)
>     at Module._compile (module.js:652:30)
>     at Object.Module._extensions..js (module.js:663:10)
>     at Module.load (module.js:565:32)
>     at tryModuleLoad (module.js:505:12)
>     at Function.Module._load (module.js:497:3)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! @syncfusion/ej2-angular-grids@17.1.1 packagr: `ng-packagr -p ng-package.json && gulp npmrc-changelog-schematics-injection && gulp path-change`

### My dependencies

> "devDependencies": {
>         "@angular-devkit/schematics": "*",
>         "@angular/common": "*",
>         "@angular/compiler": "*",
>         "@angular/compiler-cli": "*",
>         "@angular/core": "*",
>         "@angular/forms": "*",
>         "@angular/http": "*",
>         "@angular/platform-browser": "*",
>         "@angular/platform-browser-dynamic": "*",
>         "@angular/platform-server": "*",
>         "@angular/router": "*",
>         "@schematics/angular": "*",
>         "@syncfusion/ej2-build": "*",
>         "core-js": "2.4.1 - 2.6.6",
>         "es6-module-loader": "^0.17.11",
>         "ng-packagr": "^5.2.0",
>         "reflect-metadata": "0.1.9 - 0.1.15 ",
>         "rollup": "^0.41.6",
>         "rollup-plugin-uglify": "^1.0.1",
>         "rxjs": "5.0.0 - 5.5.10",
>         "systemjs": "^0.19.40",
>         "systemjs-plugin-babel": "0.0.17",
>         "tsickle": "0.34.0",
>         "zone.js": "0.7.2 - 0.8.26"
>     }

**Comment by kumaresan-subramani** [comment]
Hi @alan-agius4 ,

Do you have a suggestion on this?

**Comment by alan-agius4** [comment]
I think this will require a reproduction, can you
Set it up please? Also which version of angular are you using?

**Comment by kumaresan-subramani** [comment]
okay, 
my angular version 7.2.15

can i share my sample with repo steps?

**Comment by kumaresan-subramani** [comment]
hi @alan-agius4 ,

Is my issue related to this? https://github.com/nestjs/typeorm/issues/25

**Comment by alan-agius4** [comment]
Yes please

**Comment by kumaresan-subramani** [comment]
Hi @alan-agius4 ,

Thanks for your quick update, you are awesome

can you check this one also https://github.com/angular/angular-cli/issues/13171

**Comment by alan-agius4** [comment]
Ng-packagr directly depends on rxjs version 6. Unless you are forcing resolution to a different version it shouldn’t happen

**Comment by kumaresan-subramani** [comment]
so what can i do now?


And can you update this one also please ?
https://github.com/angular/angular-cli/issues/13171

**Comment by alan-agius4** [comment]
I suggest you share a repo so that I can take a look

**Comment by kumaresan-subramani** [comment]
Hi @alan-agius4 ,

I have attached my sample here.

### Repo steps

1) Download below sample

[angular.zip](https://github.com/ng-packagr/ng-packagr/files/3230911/angular.zip)

2) Then check "ng-packagr" version - if it doesn't latest please change it to latest

3) give **npm i**

4) then give "npm run packagr" to generate angular package

**Comment by kumaresan-subramani** [comment]
Hi @alan-agius4 ,

Bro, are you checking on this?

### This is my actual issue because of this only i am upgrading my ng-packagr version now
in angular 8, if I take prod build it build es5 and es2015 packages. in this case, "main-es5.js" has only imported modules which I mean tree shaking is done well but in "main-es2015.js" has all modules no tree shaking

i have added my build screen shot here
<img width="960" alt="Screenshot (251)" src="https://user-images.githubusercontent.com/36756050/58468716-b3cbdd80-815b-11e9-9e93-3a2f632de1b4.png">

Here is my third-party package structure which is packaged using ng-packagr@1.5.7
https://unpkg.com/@syncfusion/ej2-angular-grids@17.1.38/

**Comment by kumaresan-subramani** [comment]
HI @alan-agius4 ,

Do you get anything regarding my issue?

**Comment by kumaresan-subramani** [comment]
HI @alan-agius4 ,

I have upgraded ng-packagr version to latest and angular version to 8.0.0

Now my third party angular package getting generated properly but in a production build tree-shaking not working properly

### My package structure which has same structure like angular packages but still in **"main-es2015.js"** has all modules [ even they don't imported ] no tree shaking is done

![Screenshot (253)](https://user-images.githubusercontent.com/36756050/58553700-3b385000-8233-11e9-83a3-7e18bb2b2446.png)

**Comment by kumaresan-subramani** [comment]
HI @alan-agius4 ,

i have solved my angular package generation issue but now i want to know tree-shaking issue

### Repo steps

1) download below sample  
[check.zip](https://github.com/ng-packagr/ng-packagr/files/3232801/check.zip)

2) run "npm i"

3) then give "ng build --prod"

4) check build source- 
 In that, "main-es5.js" has only **imported modules** which I mean **tree shaking** is done well but in "main-es2015.js" has all modules no tree shaking

i have added my build screen shot here
<img width="960" alt="Screenshot (251)" src="https://user-images.githubusercontent.com/36756050/58468716-b3cbdd80-815b-11e9-9e93-3a2f632de1b4.png">

Here is my third-party package structure which is packaged using ng-packagr@1.5.7
https://unpkg.com/@syncfusion/ej2-angular-grids@17.1.38/

**Comment by kumaresan-subramani** [comment]
HI @alan-agius4 ,

Can you update on this?

**Comment by alan-agius4** [comment]
Will try to look into this later today

**Comment by kumaresan-subramani** [comment]
okay Thanks

**Comment by alan-agius4** [comment]
Hi @kumaresan-subramani, I just tried to look into this, however I am not seeing any dependency on `@syncfusion/ej2-angular-grids`  can you please try using the tarball generated using ng-packagr version 5+? Thanks.

**Comment by kumaresan-subramani** [comment]
HI @alan-agius4 

can you place this in node_modules folder which will solve above

[@syncfusion.zip](https://github.com/ng-packagr/ng-packagr/files/3235783/%40syncfusion.zip)

**Comment by alan-agius4** [comment]
Please see:  https://github.com/angular/angular-cli/issues/14577

**Comment by kumaresan-subramani** [comment]
HI @alan-agius4 ,

Thanks for your quick response

**Comment by kumaresan-subramani** [comment]
HI @alan-agius4 ,

Any update on this?

**Comment by kumaresan-subramani** [comment]
Hi @alan-agius4 ,

still facing same issue, tree-shaking not working properly

https://github.com/angular/angular-cli/issues/15396
