### ISSUE TITLE
ES2015 problem since Angular 8

### ISSUE THREAD

**Issue by paulstelzer** [ng-packagr/ng-packagr#1307]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I have upgraded my apps to Angular 8, but if I use es2015 as target in tsconfig.json and use a browser with es2015 support, then the lib is not working correctly (see How to reproduce).

#### How To Reproduce

Take a look at my repo: https://github.com/paulstelzer/ngxs-issue

There are two branches: master and language. The difference between the two: Inside language branch, the source code is directly in the app. In master I am using the lib created with ng-packagr.

If you now build the repo with production (ng build --prod) a ES5 and ES2015 files will be created (the default since Angular 8).

If you now run the master branch (which is using the lib created with ng-packagr) and ES2015 the lib isn't working anymore. You can see it because the log "LANGUAGE checkLanguage" will not be shown in console. If you remove the es2015 part from index.html, the app is working again.

If you use the language branch (without a lib built with ng-packagr), ES2015 is working.

If you only build ES5, also the master branch with the lib built with ng-packagr will work.

For me it seems that ng-packagr made somehting that it's not working in ES2015

#### Expected Behaviour

Lib should work with ES2015 builded application

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            5.2.0
@angular/compiler:     8.0.0
rollup:                1.12.5
tsickle:               0.35.0
typescript:            3.4.5
node: 10.12.0
npm: 6.9.0
```

**Comment by alan-agius4** [comment]
Hi, I just had a look at the reproduction however in the master branch I cannot see any library with ng-packagr.

Does `ng build --no-build-optimizer` produces the same error?

**Comment by DenisSemionov** [comment]
@alan-agius4 , I have a similar problem I think. When `buildOptimizer` is disabled, everything works fine. But when `buildOptimizer` is enabled, some stuff does not work. I have created an issue in angular-cli and ngrx repositories, because I'm not sure which causes this. The issue is described here, with reproduction included:

https://github.com/ngrx/platform/issues/1905

**Comment by alan-agius4** [comment]
@DenisSemionov, the issue is within build-optimizer. 
See: https://github.com/angular/angular-cli/issues/14613#issuecomment-498960867

**Comment by paulstelzer** [comment]
@alan-agius4 I tried again, but the problem still exists.

I have updated my repo to the latest version -> https://github.com/paulstelzer/ngxs-issue

To reproduce:
- On master branch: Run ng build --prod and afterwards use http-server (or something else) on the www folder. You will see that you cannot switch the language.
- On language branch: This time the module is inside the repo and everything works
- If you set buildOptimizer to false on the master branch, it will be working there too

The lib build with ng-packagr can be found here -> https://github.com/paulstelzer/innomobile-library/tree/master/libs/language

Is it still a problem with `@angular-devkit/build-optimizer` ?

**Comment by DenisSemionov** [comment]
Happened to me as well last week once again. Just changed project target from es2015 to es5

**Comment by paulstelzer** [comment]
@DenisSemionov that's correct, it only happens in es2015 (added to my post)

**Comment by alan-agius4** [comment]
Most likely it’s related to https://github.com/angular/angular-cli/issues/15301

**Comment by SerkanSipahi** [comment]
@alan-agius4 I guess this issue is fixed! right? https://github.com/angular/angular-cli/issues/15301#ref-pullrequest-479780167

**Comment by alan-agius4** [comment]
@SerkanSipahi, yes

**Comment by SerkanSipahi** [comment]
@alan-agius4 is that already released in angular? when yes, in which version?
I think the problem in ngrx/data should also be solved so that! I hope
(https://github.com/ngrx/platform/issues/2048)

**Comment by alan-agius4** [comment]
It’s not yet realised
