### ISSUE TITLE
Package angular hybrid library

### ISSUE THREAD

**Issue by har1sh** [ng-packagr/ng-packagr#1309]
I need to achieve the below setup,

New - Angular Hybrid Project 
    App 1 
       |_ _ _ Lib 1 (angular / angularjs components)
       |_ _ _ Lib2 (angular Component)

Old - AngularJS project
    App 2  angularjs application
       |_ _ _ Need to consume Lib 1

I have been using angular-cli in a new hybrid(angular & angularjs component) project, and everything seems to work fine. But i need to spit out the library from this new setup in order for me to consume it in the old angularjs application. I tried my best to build the new project library in the hope of the bundle containing the html and everything. But the angularJS components doesn't seem to get bundled with the html files. Any suggestions would be much appreciated.

**Comment by matheo** [comment]
@har1sh `ng-packagr` was born with Angular 2+, I guess that Angular 1 doesn't have this kind of bundling, or at least it's quite possible that Angular 1 support is not a priority these days.

**Comment by alan-agius4** [comment]
Closing as the above comment pretty much sums it all up.
