### ISSUE TITLE
Autoprefixer latest upgrade provided Warning

### ISSUE THREAD

**Issue by 82antu** [ng-packagr/ng-packagr#1310]
## Type of Issue

```
[ X ] Bug Report
[ ] Feature Request
```

## Description

Not a Bug At all, just an Annoing Warning.

With Latest Autoprefixer version (9.6.0), comes up a waring like:

```
  Replace Autoprefixer browsers option to Browserslist config.
  Use browserslist key in package.json or .browserslistrc file.

  Using browsers option cause some error. Browserslist config 
  can be used for Babel, Autoprefixer, postcss-normalize and other tools.

  If you really need to use option, rename it to overrideBrowserslist.

  Learn more at:
  https://github.com/browserslist/browserslist#readme
  https://twitter.com/browserslist

```

Manually changing on stylesheet-processor.ts line 114 from:

`      autoprefixer({ browsers, grid: true })
`
to

`autoprefixer({ overrideBrowserslist, grid: true })
`

#### Expected Behaviour

No WArning at all

#### Version Information

```
$ node_modules/.bin/ng-packagr --version

ng-packagr :4.4.5

typescript: 3.1.6

```

**Comment by benwinding** [comment]
How do I get rid of this warning?

**Comment by p97z** [comment]
I'm trying to get rid of this warning also... How?

**Comment by camtthompson** [comment]
Updating my package.json to use `ng-packagr: "^5.1.0` from `ng-packagr: "4.1.0" did it for me.
