### ISSUE TITLE
Not compatible with Angular 8

### ISSUE THREAD

**Issue by fr0** [ng-packagr/ng-packagr#1312]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

The latest version of `ng-packagr` (`5.2.0`) has these peer dependencies

```
    "@angular/compiler": "^6.0.0 || ^7.0.0 || ^8.0.0-beta.0",
    "@angular/compiler-cli": "^6.0.0 || ^7.0.0 || ^8.0.0-beta.0",
```

Angular 8.0 was released officially on 5/28. The non-beta version of 8.0 should be listed here.

#### Expected Behaviour

`ng-packagr` should support the latest full version of each version of Angular as soon as it is available.

**Comment by alan-agius4** [comment]
Hi, thanks for opening this, but `^8.0.0-beta.0` does mean that version 8 stable is supported as per semver rules.

You can test it out here: https://semver.npmjs.com/
