### ISSUE TITLE
Incorrectly reported error for @HostListener

### ISSUE THREAD

**Issue by totszwai** [ng-packagr/ng-packagr#1313]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

When using ng-packagr to compile it gives misleading and wrong error message when there is not really an error. The code compile and ran perfectly fine with `ng build` or `ng build --prod`, AoT or JiT, however when using ng-packagr it throws error.

> Directive MyComponent, Expected 2 arguments, but got 1.
> at Object.<anonymous> (/home/project/node_modules/ng-packagr/lib/ngc/compile-source-files.js:53:68)
    at Generator.next (<anonymous>)
    at /home/project/node_modules/ng-packagr/lib/ngc/compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/project/node_modules/ng-packagr/lib/ngc/compile-source-files.js:3:12)
    at Object.compileSourceFiles (/home/project/node_modules/ng-packagr/lib/ngc/compile-source-files.js:19:12)
    at Object.<anonymous> (/home/project/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:26:32)
    at Generator.next (<anonymous>)
    at /home/project/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)

https://stackoverflow.com/questions/56432951/angular-input-inheritance-causing-weird-compilation-error-with-ng-packagr/56461529#56461529

#### How To Reproduce

Example:
```
@HostListener('document:click', ['$event'])
onClicked($event, fromComponent: boolean) {
```
Will result 
> Directive MyComponent, Expected 2 arguments, but got 1.

#### Expected Behaviour

Either, don't throw an error, because is not really an error.
Or
Print a better WARNING message highlighting the actual problem such as:
> In MyComponent, function onClicked, Expected 2 arguments, but got 1 from HostListener.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            3.0.6
@angular/compiler:     7.2.11
rollup:                0.59.4
tsickle:               0.35.0
typescript:            3.2.4
```

#### Workaround

A workaround is to put the second argument optional like `fromComponent?` however, it took me 3 days to troubleshoot this on and off, through process of elimination and stripping out code here and there one by one to pinpoint the real issue that ng-packagr complaining about! And it wasn't even a real error because the code itself ran completely fine!!

**Comment by alan-agius4** [comment]
Hi, thanks for reporting this. However please note that this error is being throw by the Angular Compiler. And hence, it should be addressed there.

**Comment by totszwai** [comment]
How is this thrown by angular compiler?
- ng build
- ng build --prod
- ng serve

None of them throw that error, only when using ng-packagr. In fact, isn't it using the ngc supplied by ng-packagr? `ng-packagr/lib/ngc/compile-source-files.js:53:68`

**Comment by alan-agius4** [comment]
What builds in an application doesn't necessarily mean it will built at a library level. Libraries have stricter compilation rules. 

Have you tried using NGC directly and see that indeed the error is not from Angular Compiler CLI?

```bash
node_modules/.bin/ngc -p projects/<project-name>/tsconfig.lib.json
```
