### ISSUE TITLE
Doc Request: Testing Modules with Secondary Entrypoints w/ intra-package dependencies

### ISSUE THREAD

**Issue by damienwebdev** [ng-packagr/ng-packagr#1314]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

Documentation Request: When testing Angular libs generated by the cli that have intra-package dependencies, it becomes necessary to _build_ the libraries before you test them. Is there a known workaround or way to avoid this?

#### How To Reproduce
```bash
git clone https://github.com/graycoreio/daffodil
git checkout develop
ng build core && ng test product (tests fail, missing dep)
```

working tests
```bash
git clone https://github.com/graycoreio/daffodil
git checkout develop
ng build core && ng build product && ng test product (tests pass)
```

#### Expected Behaviour
```bash
git clone https://github.com/graycoreio/daffodil
git checkout develop
ng build core && ng test product (tests pass)
```

#### Version Information

```bash
node_modules/.bin/ng-packagr --version
ng-packagr:            4.7.1
@angular/compiler:     7.2.10
rollup:                0.67.4
tsickle:               0.34.3
typescript:            3.2.4
```

**Comment by AmadejBukorovic** [comment]
I'm no expert so I might be overlooking something, but based on Nrwl's Nx schematics (and other projects, such as Material 2), pointing your path mappings of your tsconfig.json to your library's source folders instead of the dist folder solves that issue?

So instead of 
```
"paths": {
      "@daffodil/core": [
        "dist/core"
      ],
```

you could use

```
"paths": {
      "@daffodil/core": [
        "libs/core/src/index.ts"
      ],
```

Or is there a downside to such configuration? :)

**Comment by damienwebdev** [comment]
@AmadejBukorovic yes. That works.

**Comment by AmadejBukorovic** [comment]
I should warn you tho, that can break your build process if you have more than one library, where one is dependent on anotherl, as ng-packgr will detect the dependent library has source code that's not part of the declared the source root. In such cases, I override the paths in the tsconfig.json for the dependent library, setting the path of the imported library path back to the dist folder. You can leave the tsconfig.json for the specs as is, allowing you to run tests in a more simple manner, but you'll still have to build the primary library before attempting to build the dependent library. :) 

This, of course, isn't an issue if you're only working with secondary entry points and one library.

**Comment by damienwebdev** [comment]
@AmadejBukorovic yep. We're currently using lerna to manage the package graph/build order, but we're we facing struggles only within the package and its entrypoints.
