### ISSUE TITLE
in memory ng-packagr

### ISSUE THREAD

**Issue by qballer** [ng-packagr/ng-packagr#1317]
## Type of Issue
```
[ ] Bug Report
[x] Feature Request
```
## Description
I'm currently implementing an integration with ng-packagr to the [teambit/bit](https://github.com/teambit/bit) in order to provide component support the angular community. I feel that in my use case and perhaps others it makes sense to run ng-packagr in a memory based context. Meaning you will be able to run ng-packagr with a FS facade that by default reads from the actual file system and may be provided with an alternative implementation.

I'm going to play around with the code base and see how I achieve that and I wonder what do you guys think of this idea? Will there be need to pass this FS object to other tools which packagr uses? (ngc?)

#### Expected Behavior
Run ng-packagr programmatically with your own FS implementation.    
#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 5.3.0
@angular/compiler:     8.0.0
rollup:                1.14.2
tsickle:               
typescript:            3.4.5
node: 12.3.1
npm/yarn: 6.9.0
```

**Comment by alan-agius4** [comment]
Hi @qballer, this is an interesting idea however I do think that it would be quite a task to abstract the FS completely and not really something which would be scalable along.

While with TSC compiler, you can change the FS with your own implementation (This is generally done by using a a custom Compiler Host) there are other tools in the pipeline which do depend on the FS directly these are

- node-sass / dart-sass
- less
- stylus
- rollup

**Comment by qballer** [comment]
thanks a lot for the reply, I know of the compiler host in typescript which is why I offered this. I don't know about such possibilities in the CSS tools. I will look in to this and explore. 
Just a small thought, if you run those compilers via sub process you can load script which spoons the FS module of node. Something along the lines of node -r spoon-fs.js [compiler-script-path]
