### ISSUE TITLE
Configure the preferred main bundle

### ISSUE THREAD

**Issue by matheo** [ng-packagr/ng-packagr#1318]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

I'm building a library with `@nrwl/nx@8.1.0` and `ng-packagr@^5.2.0` for Firebase Functions. I've been deploying them successfully, but now that I'm trying to serve the built library with `firebase-tools` `emulate:start` I'm having an issue when it tries to compile the bundle:
```
⚠  TypeError: firebaseAdmin.hasOwnProperty is not a function
    at dist/functions/bundles/my-functions.umd.js:10:52
```
it's thrown at this line:
```
firebaseAdmin = firebaseAdmin && firebaseAdmin.hasOwnProperty('default') ? firebaseAdmin['default'] : firebaseAdmin;
```
and it's because `firebase-admin@8.0.0` exports a `FirebaseNamespace` esModule like this:
```
FirebaseNamespace {
>    __esModule: true,
>    credential:
>     { cert: [Function: cert],
>       refreshToken: [Function: refreshToken],
>       applicationDefault: [Function: applicationDefault] },
>    SDK_VERSION: '8.0.0',
>    Promise: [Function: Promise],
>    INTERNAL:
>     FirebaseNamespaceInternals {
>       firebase_:
>        FirebaseNamespace {
>          __esModule: true,
>          credential: [Object],
>          SDK_VERSION: '8.0.0',
>          Promise: [Function: Promise],
>          INTERNAL: [Circular],
>          default: [Circular] },
>       serviceFactories: {},
>       apps_: {},
>       appHooks_: {} },
>    default:
>     FirebaseNamespace {
>       __esModule: true,
>       credential:
>        { cert: [Function: cert],
>          refreshToken: [Function: refreshToken],
>          applicationDefault: [Function: applicationDefault] },
>       SDK_VERSION: '8.0.0',
>       Promise: [Function: Promise],
>       INTERNAL:
>        FirebaseNamespaceInternals {
>          firebase_: [Circular],
>          serviceFactories: {},
>          apps_: {},
>          appHooks_: {} },
>       default: [Circular] } }
```

#### Expected Behaviour

Modifying manually the `package.json` to use another bundle (like `esm5`) as the `main` package, it does run with no problems.

Only if we could have a new config option for the `ng-packagr.json` to pick the preferred bundle to be the main one in the resulting package.json, this issue could be avoided.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 5.3.0
@angular/compiler: 8.0.0
typescript: 3.4.5
rxjs: 6.5.2
node: 11.12.0
yarn: 1.16.0
```

**Comment by alan-agius4** [comment]
Hi, I am not quite sure what is the reason why you need to interop the firebase-admin module.

```js
firebaseAdmin = firebaseAdmin && firebaseAdmin.hasOwnProperty('default')
? firebaseAdmin['default']
: firebaseAdmin;
```

Can you explain why you need to interop the module yourself? and more over why you need to interop it for `firebase-admin`, seeing the module namespace above? 

If you really need to do interops, you should configure TSC do them for you.  https://www.typescriptlang.org/docs/handbook/compiler-options.html (esModuleInterop)

**Comment by matheo** [comment]
@alan-agius4 this is the generated bundle of the library, that went through `ng-packagr`.
As my library depends on `firebase-admin`, `ng-packagr` is doing this and I wonder if there's a way to avoid it, or just configure the `main` bundle to use the `esm5`, which works fine with `firebase-tools`.
Thanks Alan!

**Comment by alan-agius4** [comment]
Closing as we’ll not implement this. As we follow the APF spec.

The original problem should be fixed. If the problem persists please let us know.

Thanks
