### ISSUE TITLE
Exported const enum not declared in fesm5

### ISSUE THREAD

**Issue by landrito** [ng-packagr/ng-packagr#1319]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

When exporting const enum:

```
export const enum Toppings {
  CHEESE = 'Cheese',
  PEPPERONI = 'Pepperoni'
}
```

The enum is exported in the fesm5 js file, but is not declared causing the package to be broken when used. 

#### How To Reproduce

Export a constant enum in a ts file.

#### Expected Behaviour

I either expected an error from ng-packagr stating that `const enums` cannot be exported or that the enum would be changed to be a regular enum.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            4.4.0
@angular/compiler:     7.1.1
rollup:                0.66.6
tsickle:               0.34.0
typescript:            3.1.6
```

**Comment by alan-agius4** [comment]
Hi, can you please define a bit more what do you mean by broken?

Would you be able to share snippets of the output that you define as broken?

Thanks

**Comment by landrito** [comment]
Sure.

```ts
export const enum Toppings {
  CHEESE = 'Cheese',
  PEPPERONI = 'Pepperoni'
}
```

This would compile to the following in fesm5:

```js
export { Toppings }; // This line will throw an error since Toppings has not been defined previously in the file.
```

**Comment by alan-agius4** [comment]
Hi, can you try updating tsickle to version 0.35.x? I am trying to replicate this but I cannot.

**Comment by alan-agius4** [comment]
Hi again sorry for the delay you need to enable `preserveConstEnum` ts compiler option in your tsconfig as otherwise const enums will not be emitted.

https://www.typescriptlang.org/docs/handbook/enums.html
