### ISSUE TITLE
Add ability to specify dependencies in Libraries

### ISSUE THREAD

**Issue by ac566** [ng-packagr/ng-packagr#1322]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description
I have a library structure like [this](https://github.com/ng-packagr/ng-packagr/blob/master/docs/secondary-entrypoints.md)

Some of my libraries have dependencies on others, and some should absolutely not have specific dependencies.

I want to be able to declare in each package.json for each sub-library, which other libraries it depends on. Preferably defined with "include" and "exclude" glob patterns.

```json
"ngPackage": {
  "lib": {
    "entryFile": "./src/_index.ts",
    "allowLibs": [
      "**/*"
    ], 
    "bannedLibs": [
      "@lib/react-only"
    ]
  } 
}
```

If allowLibs is specified, then only specified libraries can be used, If bannedLibs is specified, then all libraries not specified can be used. If both are present, then libs that are allowed and not banned can be used. 

The paths specified should match up with the tsconfig.json "paths" argument, so this should be something that could get caught before even building.

As a sidenote, it would also be great to be able to specify external dependendencies at this level, in addition to the top-level package.json.

#### How To Reproduce
N/A

#### Expected Behaviour
N/A

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            5.3.0
@angular/compiler:     8.0.0
rollup:                1.14.6
tsickle:               0.35.0
typescript:            3.4.5
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by alan-agius4** [comment]
Thanks, for this feature request. However, this seems to a better fit if it was a lint rule.
