### ISSUE TITLE
"JavaScript heap out of memory" error occurs when build with lot of sub packages

### ISSUE THREAD

**Issue by johnny-mh** [ng-packagr/ng-packagr#1325]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

"JavaScript heap out of memory" error occurs when building with 15+ subpackages.

Here is console output and error reports

https://gist.github.com/johnny-mh/897f377424013e7f4b7048971c121b96

This project build successfully with angular7 versions

```
// angular 7 (works fine)
$ node_modules/.bin/ng-packagr --version
ng-packagr:            4.4.0
@angular/compiler:     7.0.1
rollup:                0.66.6
tsickle:               0.33.1
typescript:            3.1.3
```

#### How To Reproduce

Build library with many sub packages.

#### Expected Behaviour

Expect the build to work even with very many secondary-entrypoints

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            5.3.0
@angular/compiler:     8.0.2
rollup:                1.16.2
tsickle:               0.35.0
typescript:            3.4.5
```

#### package.json

```
{
  "name": "@commerce-ui/ng-modules",
  "version": "0.0.0-PLACEHOLDER",
  "peerDependencies": {
    "@angular/common": "^8.0.1",
    "@angular/core": "^8.0.1",
    "@commerce-ui/util": "^2.4.0",
    "lodash": "^4.17.11"
  },
  "dependencies": {
    "@egjs/agent": "^2.1.5",
    "@egjs/flicking": "^2.5.1",
    "billboard.js": "^1.9.2",
    "@commerce-ui/legacy-lib": "0.0.6"
  }
}
```

**Comment by alan-agius4** [comment]
To some extent this is experienced when having a lot of sub package. At the moment we only use a single process. And hence you’d need to increase the memory limit of that process using `max-old-space-size`.

**Comment by mistic100** [comment]
Has this issue been adressed in version 9 ?

Giving more and more RAM to Angular builds is not a correct persistent solution.

**Comment by johnny-mh** [comment]
@alan-agius4 @mistic100 I'll try it. thank you.

**Comment by mistic100** [comment]
@johnny-mh please keep the issue open. I really think increasing the available memory is not good solution and ng-packagr should improve it's memory usage.

**Comment by alan-agius4** [comment]
@mistic100, are you still hitting this with Node 12+?

**Comment by r-park** [comment]
I'm experiencing this issue with Node 12.16.1

- 1 primary entry point
- 14 secondary entry points

**Comment by peterreisz** [comment]
Hi, same here, tried with node version 14.3.0, but it uses too mush memory as well.
5G needed for 50+ secondary entry points.

**Comment by Sherloks** [comment]
Any news on this?

**Comment by johnny-mh** [comment]
Same error occurred when some of package export by directory path (using `index.ts`)
After fixed it to `from './server'` → `./server/index.ts` it disappeared.
There is another circumstance to occurring this errors.

**Comment by mistic100** [comment]
Today for no apparent reason (nothing updated) I had to increase the allows memory from 4GB to 8GB, this is plain crazy.

**Comment by peterreisz** [comment]
I've investigated a little bit this issue and it seems the [oldPrograms](https://github.com/ng-packagr/ng-packagr/blob/37e87f8231b9312f1dabd5d9adb7f900e2e0a6ea/src/lib/ng-package/nodes.ts#L71) cache causing the memory issue.

With cache (original code): memory increase by about 300MiB / entry point and goes up to 6GiB at the end.
```
real    2m39,621s
user    3m47,822s
sys     0m5,627s
```

When I clear the oldProgram cache after the entry point is built: memory usage goes up to 1.5GiB at the end.
```
real    3m11,655s
user    5m54,193s
sys     0m4,500s
```

When I clear all the caches after the entry point is built: max memory usage is 1.2GiB and decrease to 300MiB at the end
```
real    3m39,834s
user    6m38,052s
sys     0m5,612s
```

Still working on the issue, but if you are willing to trade time for less memory usage then patch the `entry-point.transform.js` in your `node_modules` and run the `ng-packagr` directly with `node --expose-gc node_modules/.bin/ng-packagr`. 

```patch
diff --git a/node_modules/ng-packagr/lib/ng-package/entry-point/entry-point.transform.js b/node_modules/ng-packagr/lib/ng-package/entry-point/entry-point.transform.js
index 4381e88..dc06044 100644
--- a/node_modules/ng-packagr/lib/ng-package/entry-point/entry-point.transform.js
+++ b/node_modules/ng-packagr/lib/ng-package/entry-point/entry-point.transform.js
@@ -15,6 +15,7 @@ const select_1 = require("../../graph/select");
 const transform_1 = require("../../graph/transform");
 const log = require("../../utils/log");
 const nodes_1 = require("../nodes");
+const ts = require("typescript");
 /**
  * A re-write of the `transformSources()` script that transforms an entry point from sources to distributable format.
  *
@@ -58,5 +59,15 @@ compileTs,
 writeBundles, writePackage, transform_1.transformFromPromise((graph) => __awaiter(void 0, void 0, void 0, function* () {
     const entryPoint = graph.find(nodes_1.byEntryPoint().and(select_1.isInProgress));
     entryPoint.state = node_1.STATE_DONE;
+    if (global.gc) {
+      entryPoint.cache.oldPrograms = undefined;
+      entryPoint.cache.sourcesFileCache.clear();
+      entryPoint.cache.analysesSourcesFileCache.clear();
+      entryPoint.cache.moduleResolutionCache = ts.createModuleResolutionCache(process.cwd(), s => s);
+      entryPoint.cache.rollupFESMCache = undefined;
+      entryPoint.cache.rollupUMDCache = undefined;
+      global.gc();
+      log.msg(`Clearing '${entryPoint.data.entryPoint.moduleId}' entrypoint cache (Heapsize: ${Math.round(process.memoryUsage().heapTotal / 1024 / 1024)} MiB)`);
+    }
 })));
 //# sourceMappingURL=entry-point.transform.js.map
```

You can use the [patch-package](https://www.npmjs.com/package/patch-package) to automatize the patching.
It does not work without the manual gc call, the memory for oldPrograms cache will not be deallocated.

**Comment by matheo** [comment]
great work @peterreisz 
I just ran into this issue today, and I'm going to try your patch :)

**Comment by alan-agius4** [comment]
Memory usage and performance have improved a lot since the issue was opened.

If this is still a problem please file a new issue.

Thanks.

**Comment by peterreisz** [comment]
Hi! Just upgraded to angular 12 and the issue is still there.
There was some improvement, because the same project now only use 4GiB memory instead of 6GiB.
The patch above still works if you willing to trade time for memory.
