### ISSUE TITLE
packagr a lib and publish like @am/core

### ISSUE THREAD

**Issue by yy7054wyq5** [ng-packagr/ng-packagr#1328]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description
I have a core lib. And i want to publish and use it as @am/core. After build, i must do 2 things.

* edit 'dist/core/package.json' file. Change name attr, 'core' to '@am/core'. At this step, npm can accept it as @am/core.
* edit 'dist/core/core.metadata.json' file. Change importAs attr, 'core' to '@am/core'.At this step, when i use this lib like 'import { xx } from '@am/core' aot-compile can work fine.

After these.i can publish and use core lib in aot. so, it can be supported  through some setting?

#### Expected Behaviour

Support use  ng g lib @am/core to implements it.But now, if use this, angular.json will tip "@am/core" is not be allowed.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: "^4.2.0"
@angular/*: "~7.2.0"
typescript: "~3.2.2"
rxjs: "~6.3.3",
node: v10.16.0
npm: 6.9.0
```

**Comment by alan-agius4** [comment]
Hi, you need to change the actual package.json that lives in the library directory and not the one in the dist directory.

**Comment by yy7054wyq5** [comment]
oh. i see. thanks.
