### ISSUE TITLE
Whether you can add a secondary entry depends on the dependency list

### ISSUE THREAD

**Issue by jiayisheji** [ng-packagr/ng-packagr#1337]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

You automatically extract the secondary entry dependency, which I found to be invalid.

package.transform.ts

```ts
entryPoints.forEach(entryPoint => {
        const deps = entryPoint.filter(isEntryPoint).map(ep => ep.url);
       console.log(deps)   => []   // Always returns an empty array
        depthBuilder.add(entryPoint.url, deps);
});
```

![image](https://user-images.githubusercontent.com/6111778/61050982-cd2e9d80-a41a-11e9-97b5-0773794a8f25.png)

The result is an alphabetical packing of folders

I wondered if I could manually add a dependency list configuration

```ts
     let initialValue = [];
      // WARNING in secondary entry points lib peerDependencies configuration Circular dependency detected
      entryPoints.forEach(entryPoint => {
        let peerDependencies = [];
        const secondaryData = entryPoint.data.entryPoint.secondaryData;
        if (secondaryData) {
          peerDependencies = secondaryData.peerDependencies.map(ngUrl);
        }
        initialValue = [...initialValue, entryPoint.url, ...peerDependencies];
        depthBuilder.add(entryPoint.url, peerDependencies);
      });
      initialValue = [...new Set(initialValue)];
      // The array index is the depth.
      const groups = depthBuilder.build();
      const groupsValue = array_1.flatten(groups);
      // If the initial value and the processed value
      if (initialValue.length !== groupsValue.length) {
        const untreatedValue = initialValue
          .filter(value => !groupsValue.includes(value))
          .map(ngPath);
        throw Error(
          `WARNING in secondary entry points lib peerDependencies configuration Circular dependency detected. \n Error folder: \n${untreatedValue.join(
            "\n"
          )}`
        );
      }
```

alert/package.json

```json
{
  "ngPackage": {
    "lib": {
      "entryFile": "index.ts",
      "umdModuleIds": {
        "simple-ui/core": "simple-ui-core"
      },
      "peerDependencies": ["core"]
    }
  }
}
````

my tree

lib
├─alert
├─autocomplete
├─button
├─card
├─checkbox
├─core
├─data-grid
├─date-picker
├─dialog
├─divider
├─echarts
├─form-field
├─icon
├─input
├─menu
├─multiple-picker
├─option
├─paginator
├─popover
├─progressbar
├─radio
├─role-permission
├─select
├─spinner
├─src
│  └─lib
├─switch
├─toast
├─tooltip
├─transfer
└─tree

![image](https://user-images.githubusercontent.com/6111778/61051499-c05e7980-a41b-11e9-9d12-db0bb013ea47.png)

![image](https://user-images.githubusercontent.com/6111778/61051013-de77aa00-a41a-11e9-8643-cbceb63fce60.png)

build ok

**Comment by alan-agius4** [comment]
Can you please provide a reproduction of the problem?

Thanks

**Comment by jiayisheji** [comment]
My problem is that if I press auto to get the dependency, there will be a packaging error. I want to manually set the dependency to fix this error.

Do you need me to provide the demo?

**Comment by alan-agius4** [comment]
I am sorry, but I am unable to understand the problem. Also please provide which version of ng-packagr you are using.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. 

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
