### ISSUE TITLE
Secondary entrypoint (testing) not exported as angular package

### ISSUE THREAD

**Issue by SuperITMan** [ng-packagr/ng-packagr#1341]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description

When I build a library with a second entrypoint, testing, it is not exported as it in angular packages. 

See `@angular/core` :

```txt
+--@angular/core
|  +--bundles
|  +--esm5
|  +-- ...
|  +--src
|  |  +-- ...
|  |  +-- core.d.ts
|  |  +-- ...
|  +--testing
|  |  +-- ...
|  |  +--testing.d.ts
|  |  +--testing.metadata.json
|  +-- ...
|  +--core.d.ts
|  +--core.metadata.json
|  +-- ...
|  +--testing.d.ts          <--- present here
|  +--testing.metadata.json <--- present here
...
```

When I build my own lib thanks to angular/cli + ng-packagr, I unfortunately don't get the same result. The testing.d.ts is only present in testing folder and not in the root...

See `mylib`:

```txt
+--mylib
|  +--bundles
|  +--esm5
|  +-- ...
|  +--src
|  |  +-- ...
|  |  +-- mylib.d.ts
|  |  +-- ...
|  +--testing
|  |  +-- ...
|  |  +--testing.d.ts
|  |  +--testing.metadata.json
|  +-- ...
|  +--mylib.d.ts
|  +--mylib.metadata.json
|  +-- ...
|  +--        <--- testing NOT present here
...
```

I don't know if it is intended or if I'm missing something in my configuration.

#### How To Reproduce

You can have a look here: https://github.com/SuperITMan/ngpackagr-testing-entry/tree/master/dist-lib to see the files.

You can also clone https://github.com/SuperITMan/ngpackagr-testing-entry and run "npm run build".

#### Expected Behaviour

I would like to generate the same format of library as angular.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 5.3.0
@angular/*: ^7.2.0
typescript: 3.2.4
rxjs: 6.3.3
node: 8.9.6
npm/yarn: 5.6.0
```

Thanks in advance for your help 😊

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent version.
