### ISSUE TITLE
A bug with extract scss files to dist

### ISSUE THREAD

**Issue by vasyliv** [ng-packagr/ng-packagr#1374]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description
The bug happens when I try to export a scss file from a library, and no error occurred. Following next guide (https://github.com/ng-packagr/ng-packagr/blob/HEAD/docs/style-include-paths.md) I did next config for ``ng-package.json``
```
"$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
  "dest": "../../dist/editor",
  "lib": {
    "entryFile": "src/public-api.ts",
    "styleIncludePaths": ["./src/lib/assets"]
  }
```
structure of files:
```
src>lib>assets>theme.scss
ng-packagr.json
```
Interesting thing when I set fake path such az ``"styleIncludePaths": ["123123asd123asd"]`` no error happens

#### How To Reproduce
No error, but nothing happened.
here is repo https://github.com/vasyliv/test-lib

#### Expected Behaviour
scss file exports to dist folder under lib name

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 5.1.0
@angular/*: 8.x.x
typescript: 3.4.5
rxjs: 6.5.2
node: 10.16.2
npm/yarn: 6.9.0
```

### Related issues
https://github.com/ng-packagr/ng-packagr/issues/1073

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem.

Can you please setup a reproduction?

**Comment by vasyliv** [comment]
https://github.com/vasyliv/test-lib

to reproduce the issue

- download project (``git clone https://github.com/vasyliv/test-lib.git``)
- npm i
- ng build test-lib
- check dist folder see no file theme.scss

**Comment by alan-agius4** [comment]
Hi, thanks for the repro. This is actually the correct behaviour,
styleIncludePaths are used for the compilation of sass to css.

Ng-packagr will not copy any assets such as scss themes

See:
https://github.com/ng-packagr/ng-packagr/issues/273

**Comment by vasyliv** [comment]
@alan-agius4 thanks a lot it works for me.
