### ISSUE TITLE
D3 in peerDependencies (and/or dependencies), explicitly whitelisted, but never found by app using library. 

### ISSUE THREAD

**Issue by tcoz** [ng-packagr/ng-packagr#1375]
Problem here: 

I have an Angular library with a pile of modules/components in it. Each imports whatever it needs, etc. One of the components is a chart that uses D3 and venn.js. 

I build the library, no errrors, then npm pack it, move the packed file to another app, npm install, no errors.

I run the app, and it says "module D3 not found" (and same for venn.js).  

If I manually install the D3 and venn.js modules in the app, everything is fine. But naturally, I don't want the app developer to have to do this. I just want them to take my library and install it. 

In the package.json you add to the library in order for ng-packagr to build it, I have added D3 and venn.js to dependencies, white listed dependencies, peer dependencies, everything I could find that seems to be the straightforward ways of going about this. It builds without errors, and in the generated package.json, I see D3 and venn.js listed predictably (e.g. if I put it in peerDeps, I see it there, if I see it in deps, I see it there). 

But whenever I install the built library into the test app (a completely vanilla Angular CLI app, version 8), same error. I have to manually install D3 and venn.js to get it to work. There are no warnings about "such and such are peerDeps you have to install them yourself" and so on. Everything just looks fine until I run the app, which is predictable, since D3 does not appear installed anywhere (node_modules, etc). 

I suspect this is a simple matter, but I'm definitely spinning my wheels here. 

What is the straightforward procedure to get D3 (and venn.js, though I figure whatever works for D3 would work for whatever else I need) onboard with the library such that the app developer using the library doesn't have to figure out (from errors) that they have to install it?

**Comment by alan-agius4** [comment]
Hi @tcoz, what you are facing here is entirely expected and as that is how peerDependencies work. peerDependencies don't get installed automaticlly in the consumer application. Instead the users will receive a warning that the peerDependency is not installed instead when using `npm install` or `yarn install` 

I suggest you take a look at this why peerDependency should be used in favour of dependencies and how to how to configure dependencies instead of peerDependency which is highly discouraged. 

https://github.com/ng-packagr/ng-packagr/blob/master/docs/dependencies.md#managing-dependencies

**Comment by tcoz** [comment]
Thank you for the response; I’ve looked extensively at the docs and believe I understand how peerDeps work (I’ve been using Angular for a long time). 

Please note that I mentioned in the body of the post, that I have tried installing these modules in every straightforward way I know of, including as explicitly whitelisted dependencies. Nothing works.

**Comment by alan-agius4** [comment]
Please provide a reproduction, thanks

**Comment by alan-agius4** [comment]
Are of consuming the library via `npm install` or tsconfig paths?

**Comment by tcoz** [comment]
I build the library using ng-packagr, pack it (npm pack) then drop it in the root of another app, point the package.json at it, and run npm install. The same result if I publish it to an npm catalog and install from there. 

In the package.json of the generated lib, I see the peer deps, or deps and whitelist, etc. depending on how I configured it before the ng package build. So when running install, I’d expect those config files to be recognized and the deps installed. 

The third party libs I mention never install with the lib. I have to explicitly install them in the app. Minimally, if there was a warning, “peer deps don’t install do it yourself” or some such, that’d be tolerable, at least the dev would know, “ok I have to install D3 and whatever else myself.” But there’s no such indication. No matter how I configure the dependencies, they don’t install.

**Comment by alan-agius4** [comment]
Hi @tcoz, I did a quick demo with the instructions you provided above.

Lib package.json
```
{
  "name": "@sample/apf",
  "version": "1.0.0-pre.0",
  "description": "A sample library testing Angular Package Format"
  "peerDependencies": {
    "my-peer-dep": "^4.1.2"
  },
  ...
}
```
App package.json
```
{
  "name": "my-app",
  "private": true,
  "devDependencies": {
    "@sample/apf": "../apf/dist/sample-apf-1.0.0-pre.0.tgz",
   ...
  }
}
```

```bash
$ yarn
yarn install v1.12.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > @sample/apf@1.0.0-pre.0" has unmet peer dependency "my-peer-dep@^4.1.2".
[4/4] 📃  Building fresh packages...

✨  Done in 0.33s.

```

**Comment by tcoz** [comment]
Thank you, this is a very basic example of how to add a peer dep, which is something I’ve already done, and it uses yarn to boot. I appreciate the effort but this doesn’t move me forward unfortunately.

**Comment by alan-agius4** [comment]
In the example I used both yarn and npm.

I am not fully grasping the issue you are having, as I shown above when peerDeps are not installed the users gets a warning. I am not following why the above is a non complex solution for peerDeps. The is one solution, either having them nor not.

Without a reproduction I cannot provide any further assistance

Thanks.

**Comment by tcoz** [comment]
I'll provide a repro when I get a chance.
