### ISSUE TITLE
Incorrect library paths

### ISSUE THREAD

**Issue by lellelskii** [ng-packagr/ng-packagr#1379]
## Type of Issue

```
[+] Bug Report
[ ] Feature Request
```

## Description

I am using Angular library and have the following folder structure:
```
coollibrary
  - components
    - my.component.ts
  - services
    - my.service.ts
public_api.ts
```
In public_api, I export the component and service and make the library build.
After that I can import the necessary things in my project using
```
import { MyComponent } from 'coollibrary';
```
but I can not use the following path:
```
import { MyComponent  } from 'coollibrary/components'
```
Can I use correct path?

Do I can use this guide (https://github.com/ng-packagr/ng-packagr/blob/master/docs/secondary-entrypoints.md) or I have other ways?

**Comment by alan-agius4** [comment]
Hi, yes you need to create secondary entry points instead of deep imports.

**Comment by alan-agius4** [comment]
Kindly check this guide: https://github.com/ng-packagr/ng-packagr/blob/master/docs/secondary-entrypoints.md
