### ISSUE TITLE
Build warnings "Declaring 'some name' as function"

### ISSUE THREAD

**Issue by 92yoghurt** [ng-packagr/ng-packagr#1380]
## Type of Issue

```
how to get rid of these warnings?
```

## Description

WARN: Declaring Da as function
WARN: Declaring ab as function
WARN: Declaring bb as function
WARN: Side effects in initialization of unused variable $d

#### How To Reproduce

ng build lib --prod

#### Expected Behaviour

build without warnings

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 4.4.5
@angular/*: 7.1.0
typescript: 3.1.6
rxjs: 6.3.3
node: 10.16.0
yarn: 1.13.0
```

**Comment by alan-agius4** [comment]
Should be addressed in 5.6
