### ISSUE TITLE
ERROR - export 'default' (imported as 'core') was not found in '@angular/core

### ISSUE THREAD

**Issue by netwobble** [ng-packagr/ng-packagr#1383]
Error when include a library into an Angular 8 app using Webpack 4 as build.

I will try to get a simple repo going to reproduce.  The library is just a single angular component generated from CLI.  We are using the latest Angular 8.

There should be no issue calling Angular Core during build.

NOTE this is the same error as issue #210 but not same cause.  
thoughts,
workarounds?

thanks,
AJ

*************************
Error Message shown in console on build
***********************

ERROR in ./node_modules/design-base/fesm5/design-base.js 29:9-13
"export 'default' (imported as 'core') was not found in '@angular/core'
ERROR in ./node_modules/design-base/fesm5/design-base.js 34:16-20
"export 'default' (imported as 'core') was not found in '@angular/core'
ERROR in ./node_modules/design-base/fesm5/design-base.js 70:16-20
"export 'default' (imported as 'core') was not found in '@angular/core'
ERROR in ./node_modules/design-base/fesm5/design-base.js 106:16-20
"export 'default' (imported as 'core') was not found in '@angular/core'
ERROR in ./node_modules/design-base/fesm5/design-base.js 137:16-20
"export 'default' (imported as 'core') was not found in '@angular/core'

*************************
Package.json
***********************
  "dependencies": {
    "@angular/animations": "^8.2.2",
    "@angular/cdk": "^8.1.3",
    "@angular/common": "~8.2.2",
    "@angular/compiler": "~8.2.2",
    "@angular/core": "~8.2.2",
    "@angular/forms": "~8.2.2",
    "@angular/http": "~8.0.0-beta.10",
    "@angular/material": "^8.1.3",
    "@angular/platform-browser": "~8.2.2",
    "@angular/platform-browser-dynamic": "~8.2.2",
    "@angular/router": "~8.2.2",
    "core-js": "2.5.4",
    "design-base": "file:dist/design-base/design-base-0.0.1.tgz",
    "material-components-web": "^3.1.1",
    "nativescript-angular": "~8.2.0",
    "nativescript-theme-core": "~2.0.5",
    "reflect-metadata": "~0.1.12",
    "rxjs": "~6.5.0",
    "tns-core-modules": "~6.0.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-ng-packagr": "~0.802.2",
    "@angular/cli": "~8.2.2",
    "@angular/compiler-cli": "~8.2.2",
    "@angular-devkit/build-angular": "~0.802.2",
    "@nativescript/schematics": "~0.7.0",
    "@nativescript/tslint-rules": "~0.0.2",
    "@types/jasmine": "~3.4.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~12.7.2",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.2.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "nativescript-dev-webpack": "~1.1.0",
    "ng-packagr": "^5.5.0",
    "protractor": "~5.4.0",
    "ts-node": "~8.3.0",
    "tsickle": "^0.36.0",
    "tslint": "~5.19.0",
    "typescript": "~3.5.3",
    "node-sass": "^4.7.1"
  }

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by ramuda** [comment]
We are experiencing the same issue. Didn't make any change but upgraded angular and ng-packgr.

**Comment by ramuda** [comment]
Some more observations. I have a library which builds on commonjs , when i use it in an app whose target is lets say esnext. You will get the above errors. If you build the library in es5 and use esnext in app. Then everything is ok.

**Comment by meyacine** [comment]
I have the same issue with an Angular library project that's using rxjs.
```"export 'default' (imported as 'rxjs') was not found in 'rxjs'```

## Reproduction using : 

- Create an Angular library.
- build it `ng build youLibrary`
- link it using `yarn link`
- use it in another Angular project using `yarn link "yourLibrary"`
- try to run your Angular Project

## Dependencies :

- "@angular/core": "^8.2.5",
- "rxjs": "^6.5.3",
- "@angular-devkit/build-ng-packagr": "~0.803.4",
- "ng-packagr": "^5.5.0",

**Comment by meyacine** [comment]
# EUREKA
Fixed by playing with the tsconfig in both the library, and the angular project : 

* tsconfig.lib.json
```
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    // 👍 these two lines
    "target": "es2015",
    "module": "esnext",
  },
  "angularCompilerOptions": {
    "annotateForClosureCompiler": true,
    "skipTemplateCodegen": true,
    "strictMetadataEmit": true,
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true,
    "enableResourceInlining": true
  },
  "exclude": [
    "src/test.ts",
    "**/*.spec.ts"
  ]
}
```

and in the target project :

* tsconfig.json 
```
{
   "compilerOptions": {
       "module": "esnext"
    }
}
```

* tsconfig.app.json 
```
{
   "compilerOptions": {
       "module": "esnext"
    }
}
```

**Comment by lukbdevlab** [comment]
We are experiencing the same issue. It works if we remove `angularCompilerOptions.module` in the global tsconfig:

```
{
  "angularCompilerOptions": {
    "module": "esNext"  // Delete this
  },
  ...
}
```

It can be reproduced when creating a new project from scratch. Adding the module option will break it.
