### ISSUE TITLE
[Feature Request] Integration with `rollup-plugin-alias`

### ISSUE THREAD

**Issue by JounQin** [ng-packagr/ng-packagr#1387]
## Type of Issue

- [ ] Bug Report
- [x] Feature Request

## Description

_A bug: please describe the error that you encountered_

_A feature: please describe your use case and motivation_

Support `rollup-plugin-alias` for aliasing from `loash-es` -> `lodash`.

#### How To Reproduce

_A bug: please include instructions how to reproduce. Issues without reproduction are likely to receive no feedback._

_Can you reproduce the error in the integration tests in ng-packagr?_
_If possible, take a look at the [`integration/samples`](./integration/samples) and try to break one of these builds!_

_Is the error you faced in an application importing the library_
_Try to break the Angular CLI app in [`integration/consumers/ng-cli`](./integration/consumers/ng-cli)!_

#### Expected Behaviour

_A bug: please describe what behaviour or result you expected_

_A feature: do you have a first draft or an idea how to implement?_

```json
{
  "alias": {
    "lodash": "lodash-es"
  }
}
```

Something like `parcel` resolution which reads it from `package.json`.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 5.5.0
@angular/*: 8.2.3
typescript: 3.5.3
rxjs: 6.5.2
node: v12.8.1
yarn: 1.17.3
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by alan-agius4** [comment]
Hi, thanks for the interest, however rollup is only used to generate FESM and UMD bundles and it will not process ESM bundles.

Hence, we cannot add any transformers/plugins in the pipeline unless they are a must to either generate FESMs or UMD bundles.
