### ISSUE TITLE
Multi-library which depends on each other build error: Cannot find module

### ISSUE THREAD

**Issue by s33h0w** [ng-packagr/ng-packagr#1388]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I create a repo which has two libraries, one of them depends on the other. When I build that library I get this error: Cannot find module xx.

#### How To Reproduce

You can reproduce it with the repo [here](https://github.com/s33h0w/ng-packagr-issue-example). It will be ok if you build lib-a by run `ng build lib-a`, but get error if you build lib-b which import lib-a in `lib-b/src/lib/lib-b.module.ts`. I have set the path-mapping in `lib-b/tsconfig.lib.json` like below.

```json
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "outDir": "../../out-tsc/lib",
    "target": "es2015",
    "declaration": true,
    "inlineSources": true,
    "types": [],
    "lib": ["dom", "es2018"],
    "baseUrl": "./",
    "paths": {
      "lib-a": ["../lib-a"]
    }
  },
  "angularCompilerOptions": {
    "annotateForClosureCompiler": true,
    "skipTemplateCodegen": true,
    "strictMetadataEmit": true,
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true,
    "enableResourceInlining": true
  },
  "exclude": ["src/test.ts", "**/*.spec.ts"]
}

```
Here is the error message when I run `ng build lib-b`
```
ERROR: projects/lib-b/src/lib/lib-b.module.ts(3,28): error TS2307: Cannot find module 'lib-a'.
projects/lib-b/src/lib/lib-b.module.ts(7,13): Error during template compile of 'LibBModule'
  Could not resolve lib-a relative to [object Object]..
projects/lib-b/src/lib/lib-b.module.ts(7,13): Error during template compile of 'LibBModule'
  Could not resolve lib-a relative to [object Object]..

An unhandled exception occurred: projects/lib-b/src/lib/lib-b.module.ts(3,28): error TS2307: Cannot find module 'lib-a'.
projects/lib-b/src/lib/lib-b.module.ts(7,13): Error during template compile of 'LibBModule'
  Could not resolve lib-a relative to [object Object]..
projects/lib-b/src/lib/lib-b.module.ts(7,13): Error during template compile of 'LibBModule'
  Could not resolve lib-a relative to [object Object]..

```

#### Expected Behaviour

Build multi-library which depends on each other successfully.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 5.1.0
@angular/*: 8.1.1
typescript: 3.4.3
rxjs: 6.4.0
node: 10.15.3
npm: 6.4.1
```

**Comment by alan-agius4** [comment]
Hi, @s33h0w, you should move the path dependencies to the main `tsconfig.json` so that it can be shared with all projects within the workspace. Also prior to building `lib-b` make sure you build it's dependencies which in this case is `lib-a`.

```
ng build lib-a
ng build lib-b
```

**Comment by s33h0w** [comment]
@alan-agius4  Thanks for help, it works! But I still have some questions, how to customize lib-level path-mapping or not the whole workspace. And why the `paths` doesn't work in `tsconfig.lib.json`?

**Comment by alan-agius4** [comment]
You can configure the path mappings at a library level given that the path mappings are correct and pointing to the compiler version of the library though personally I prefer that paths mappings are in the workspace config as it's it decreases maintenance when a workspace grows. 

In the above above case the path should have been:
```json
    "paths": {
      "lib-a": ["../../dist/lib-a"]
    }
```

**Comment by s33h0w** [comment]
Does the `paths` must point to the compiler version ? I change lib-b's `tsconfig.lib.json` like what you said , but it still doesn't work.

**Comment by alan-agius4** [comment]
edit: complied

**Comment by alan-agius4** [comment]
PS: you also need to add ` "lib-a/*": ["../../dist/lib-a/*"]` to your paths

**Comment by s33h0w** [comment]
It works again. This is important for me, thank you.
