### ISSUE TITLE
Usages of the different builds according to Angular package format

### ISSUE THREAD

**Issue by boyanio** [ng-packagr/ng-packagr#1389]
## Type of Issue

```
[ ] Bug Report
[ ] Feature Request
```

## Description

[Angular package format](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview) defines following builds:

- esm5/fesm5
- esm2015/fesm2015
- umd

What I am missing is their actual usage: can anyone describe with examples (e.g., Webpack configurations or any other configurations) the use case for each build? They are very briefly described in the Google document, but I am struggling to get a good understanding. Moreover, I cannot seem to find such information online. It would be a great way to enhance the documentation of ng-packagr as well, I believe. :-)

**Comment by alan-agius4** [comment]
Kindly see https://angular.io/guide/angular-package-format for more information about APF.
