### ISSUE TITLE
Secondary entry points breaking "no-implicit-dependencies" linting rule

### ISSUE THREAD

**Issue by klemenoslaj** [ng-packagr/ng-packagr#1391]
## Type of Issue

```
[x] Bug Report
[x] Feature Request
```

## Description

Not sure whether this is a bug or a feature request, but I want to enable `no-implicit-dependencies` in my monorepo to track that I am adding all the dependencies to my `package.json` files, however, this is breaking as soon as I have a library with secondary entry points.

This is because `no-implicit-dependencies` is checking nested `package.json` files, however, `ng-packagr` uses `package.json` to mark secondary entry points, but it is never directly installed in `node_modules`.

#### How To Reproduce

- create new angular workspace
- add `no-implicit-dependencies` rule to `tslint.config.json`
- generate a library
- create secondary entry point in generated library
- in secondary entry point import any package (_e.g. `@angular/core`_)
- Execute `ng lint <library>`

#### Expected Behaviour

I would expect it would be possible to use `ng-package.json` files instead of `package.json` for secondary entry points.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            5.3.0
@angular/compiler:     8.1.2
rollup:                1.17.0
tsickle:               0.35.0
typescript:            3.4.5
yarn:                  1.17.3
```

**Comment by alan-agius4** [comment]
Hi, I don’t think there is a fix for this. Secondary entrypoints do require to have a `package.json`.

**Comment by klemenoslaj** [comment]
@alan-agius4, yes, but wouldn't it be possible to instead use `ng-package.json` (_since that is the only content in current `package.json` anyway_), but generate `package.json` (_if required, dunno_) in the compile time?

And you could recommend `package.json`, while having the alternative, thus no breaking change.

**Comment by alan-agius4** [comment]
Good idea, that could be an option.

**Comment by klemenoslaj** [comment]
I would be open to submitting a PR, if that's appropriate issue for the new contributor.
