### ISSUE TITLE
cssUrl inline not working with secondary entry points

### ISSUE THREAD

**Issue by kreuzerk** [ng-packagr/ng-packagr#1393]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description
Ng-packagr allows us to set the `cssUrl` property to "inline". In this case svg's from the assets folder get inlined into the bundle.

This behaviour works great if we use ng-packagr to create a single bundle. But it breaks once we start using secondary entry points to create multiple bundles.

#### How To Reproduce
To reproduce the bug I created the following repository: https://github.com/kreuzerk/howdy
The repository contains a `weather.component.ts`and a stylesheet.

`a {
  background-image: url("../../assets/sun.svg");
}`

**Reproduce working example with single chunk**
1. Check out the branch: `feature/inlineCSS_singleChunk`
2. run npm install and npm run build
3. open the fesm2015 
4. The svg is inlined

`                styles: ["a{background-image:url(\"data:image/svg+xml,%3C%3Fxml version%3D%221.0%22...."]
`

**Reproduce broken example with multiple chunks**
1. Check out the branch: `feature/inlineCSS_multipleChunks`
2. run npm install and npm run build
3. open the fesm2015 (howdy-lib-weather.js)
4. The svg is not inlined

`
styles: ["a{background-image:url(../../assets/sun.svg)}"]
`
#### Expected Behaviour
assets should also be inlined when using multiple bundles

#### Version Information

```
ng-packagr:            5.4.3
@angular/compiler:     8.2.1
rollup:                1.19.4
tsickle:               0.36.0
typescript:            3.5.3
```

**Comment by alan-agius4** [comment]
Hi, the `cssUrl` option is per entrypoint. Hence, you need to specify `"cssUrl": "inline"` in the secondary entrypoint that you want their assets to be inlined.

Example in `/projects/howdy/src/lib/weather/package.json`
```js
{
  "ngPackage": {
    "lib": {
      "cssUrl": "inline",
      "entryFile": "public_api.ts"
    }
  }
}

```

**Comment by kreuzerk** [comment]
Awesome - works. Thanks a lot 👍
