### ISSUE TITLE
Feature Request: Add option to remove fields from publish-ready package.json

### ISSUE THREAD

**Issue by elliotleelewis** [ng-packagr/ng-packagr#1395]
## Type of Issue

```
[ ] Bug Report
[*] Feature Request
```

## Description

It would be nice to be able to remove sections from the package.json after its been copied into the published output. For example, whilst under development, we add in our tooling as `devDependencies` in our `package.json` file, as well as things such as prettier/stylelint configs, which sometimes can cause issues, and are not needed in the final package.json.

#### Expected Behaviour

I propose that we add a `blacklistedPackageSections` field to the configuration file, so that we can specify properties to be removed when the file is built and copied over into the output directory. The settings file would then read as:

```
{
  "$schema": "./node_modules/ng-packagr/package.schema.json",
  "ngPackage": {
    "blacklistedPackageSections": [
      "devDependencies",
      "browserslist",
      "prettier",
      "stylelint"
    ]
  }
}
``` 

We could even remove the need for the `keepLifecycleScripts` config option too, by making the default for `blacklistedPackageSections` the following:

```
"blacklistedPackageSections": [
  "scripts"
]
```

What do you guys think? 😃

**Comment by alan-agius4** [comment]
Kindly see: https://github.com/ng-packagr/ng-packagr/pull/1397#issuecomment-547820364
