### ISSUE TITLE
Could not resolve ng2-nvd3 relative to [object Object]..

### ISSUE THREAD

**Issue by diksha-v** [ng-packagr/ng-packagr#1398]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description

 Error during template compile of 'CommonUIModule'
    Could not resolve ng2-nvd3 relative to [object Object]..

#### How To Reproduce
I have an Angular library with some modules and components in it.  One of the components is a chart that uses ng2-nvd3.  

I build the library, no errors. then I use the library in my app and while building I get error 
"Error during template compile of 'CommonUIModule'
    Could not resolve ng2-nvd3 relative to [object Object].."

If I manually install the ng2-nvd3 in the app, everything is fine. But I don't want the app to do this. I just want them to take my library and install it.

I have tried following :

1) ng2-nvd3 as peer dependency 
"peerDependencies": {
    "@angular/common": "~7.2.0",
    "@angular/core": "~7.2.0",
    "ng2-nvd3": "^2.0.0"
  }

2) bundled dependency
"bundledDependencies": [
    'ng2-nvd3'
  ]

 but none works.

So how to I pack this third party library in my angular library so my app doesn't have to install third party library manually.?

#### Version Information

```
this is how my package.json looks like 

"dependencies": {
    "@angular/animations": "~7.2.0",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/http": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "core-js": "^2.5.4",
    "rxjs": "~6.3.3",
    "zone.js": "~0.8.26",
    "ng2-nvd3": "^2.0.0"
  }


{
    "ngPackage": {
        "lib": {
            "entryFile": "public_api.ts"
        }
    }
}

ng-package.json looks like : 
{
  "$schema": "../node_modules/ng-packagr/ng-package.schema.json",
  "dest": "../dist/diagnostics-common",
  "lib": {
    "entryFile": "public_api.ts"
  }
}
```

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent version.
