### ISSUE TITLE
 BrowserslistError: Unknown version 67 of android

### ISSUE THREAD

**Issue by sergidt** [ng-packagr/ng-packagr#1411]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

Recently I updated my Angular project dependency versions and I get this error when trying to build a library: 

```
ERROR: Unknown version 67 of android
An unhandled exception occurred: Unknown version 67 of android
See "C:\Users\doteteix\AppData\Local\Temp\ng-5ErChV\angular-errors.log" for further details.
```

I can get more detail from this angular-errors.log. This is the extra info: 

```
[error] BrowserslistError: Unknown version 67 of android
    at Function.select (C:\Projects\Source\html5-console\node_modules\ng-packagr\node_modules\autoprefixer\node_modules\browserslist\index.js:924:17)
    at C:\Projects\Source\html5-console\node_modules\ng-packagr\node_modules\autoprefixer\node_modules\browserslist\index.js:252:33
    at Array.reduce (<anonymous>)
    at resolve (C:\Projects\Source\html5-console\node_modules\ng-packagr\node_modules\autoprefixer\node_modules\browserslist\index.js:234:18)
    at browserslist (C:\Projects\Source\html5-console\node_modules\ng-packagr\node_modules\autoprefixer\node_modules\browserslist\index.js:353:16)
    at Browsers.parse (C:\Projects\Source\html5-console\node_modules\ng-packagr\node_modules\autoprefixer\lib\browsers.js:66:12)
    at new Browsers (C:\Projects\Source\html5-console\node_modules\ng-packagr\node_modules\autoprefixer\lib\browsers.js:48:26)
    at loadPrefixes (C:\Projects\Source\html5-console\node_modules\ng-packagr\node_modules\autoprefixer\lib\autoprefixer.js:101:20)
    at plugin (C:\Projects\Source\html5-console\node_modules\ng-packagr\node_modules\autoprefixer\lib\autoprefixer.js:112:20)
    at LazyResult.run (C:\Projects\Source\html5-console\node_modules\postcss\lib\lazy-result.js:295:14)
```

#### How To Reproduce

I try to build my lirary executing: 
```
ng build core
```

#### Expected Behaviour

The library is built as expected and as usual before I updated versions.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 5.5.1
@angular/*: 8.2.5
@angular/cli: ^8.3.3
@angular/material: 8.1.4
@angular/cdk: 8.1.4
typescript: ~3.4.3
rxjs: ^6.4.0
node: 12.8.0
npm: 6.10.2

```

**Comment by mrtijn** [comment]
I'm having the same issue, expect having built before. 
Tried to go back to older versions but no luck.

**Comment by andrewryan1906** [comment]
I too am having this issue... unable to resolve...

**Comment by andrewryan1906** [comment]
@mrtijn I was able to fix it by taking these steps:

1.Deleting the entire node_modules directory
2.Deleting package-lock.json from the root directory
3. Making sure the latest @angular-devkit projects were referenced in package.json:

`
    "@angular-devkit/build-angular": "^0.801.3",
    "@angular-devkit/build-ng-packagr": "^0.801.3",
`

4. Running npm install

That fixes it. Have no idea why.

**Comment by mrtijn** [comment]
@andrewryan1906 Seems to do the trick, thanks!

**Comment by alan-agius4** [comment]
Yeah, this is a hoisting issue, what @andrewryan1906 mentioned is the correct solution.

Thanks

**Comment by robbiedigital** [comment]
This is still causing PROBLEMS!!!!

**Comment by zsdycs** [comment]
@andrewryan1906 mentioned is the correct solution.

Thanks

**Comment by robbiedigital** [comment]
I have tried @andrewryan1906 solution.
I deleted my node_modules and package-lock.json file, re-installed with `"@angular-devkit/build-angular": "^0.801.3"` and  `"@angular-devkit/build-ng-packagr": "^0.801.3"`

I am still getting:

`
BUILD ERROR
Unknown version 67 of android
An unhandled exception occurred: Unknown version 67 of android
`

**Comment by tcoz** [comment]
For the record, I went through this today on a pretty important enterprise monorepo with nrwl, storybook, ng-packagr, and some other such suchery. I ran ng update, looked at what needed updating, followed it carefully (checking ng version etc), and that cleared it. BUT...now I had peer dep warnings. So I went through all those, and eventually cleared them all out. 

The joy of the JS/TS/Angular ecosystem. The upshot: update your versions. This is one of those Apple-like ones; no explanation just upgrade.

**Comment by Shaimae18** [comment]
@andrewryan1906  solution work for me, thank you.

**Comment by skorunka** [comment]
I got an `ERROR: Unknown version 80 of edge` when building publishable library (ng9). It just happens when I import another module in the library. Even the empty module. The module is defined inside the library scope. I don't understand the error text, how it is connected to a ng-packagr?

**Comment by jagomf** [comment]
This is happening now.
Angular ~7.2.0 project, so I guess I can't use angular compiler ^0.800 from @andrewryan1906 solution...

**Comment by twtavares** [comment]
@andrewryan1906, funcionou pra mim.
Muito obrigado!

**Comment by riveroreyes** [comment]
This anwser (from andrewryan1906 commented on Oct 1, 2019) worked for me, today 2020-05-17. Thanks
