### ISSUE TITLE
Any way to extend the Webpack config?

### ISSUE THREAD

**Issue by matheo** [ng-packagr/ng-packagr#1418]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

I'm using `@angular-devkit/build-ng-packagr:build v0.803.9` and I'm trying to build a library inside a NX monorepo, with components using PUG templates.

It requires some special loaders, and the current way is to run `ng add ng-cli-pug-loader` which hacks the devkit's node_module files. Even with this hack, my library is not compiling, so I'm looking for a cleaner method to extend the config, like `@nrwl/web` package does:
https://connect.nrwl.io/app/cookbook/4CjE7wgoOyYU3ri08GCAr7

Unfortunately that option is just for the web builder and I wonder if ng-packagr can implement it:
```
{
  "projects": {
    "my-app": {
      "architect": {
        "build": {
          "builder": "@nrwl/web:build",
          "options": {
            "webpackConfig": "apps/frontend/webpack.config.js"
          }
        }
      }
    }
  }
}
```

Thanks in advance!

**Comment by alan-agius4** [comment]
Hi, ng-packagr doesn’t use webpack to build and bundle the libraries.

We use rollup, but only at the last step to generate the FESM and UMD bundles.

**Comment by ashwingairola** [comment]
I am new to the concept of Angular libraries. I wish to create a component library that uses TailwindCSS. That would require me to add PostCSS as a dependency.
In a traditional app, I could override the webpack config and use @angular-builders, but since libraries use ng-packagr, I am not sure how to proceed. Can someone point me in the right direction?

**Comment by alan-agius4** [comment]
Adding custom postcss plugins is currently not supported, We'll be looking at this in the future.
