### ISSUE TITLE
data path "" should NOT have additional properties (name) 

### ISSUE THREAD

**Issue by raviji** [ng-packagr/ng-packagr#1426]
I got this error when i ran the build command

"ERROR: Configuration doesn't match the required schema.
Data path "" should NOT have additional properties (name)."

Package.json -- 
`{
    "author": "Ravi G",
    "name": "@html5ravi/as_input",
    "version": "1.0.1",
    "scripts": {
        "ng": "ng",
        "start": "ng serve",
        "build-ng": "ng build",
        "test": "ng test",
        "lint": "ng lint",
        "e2e": "ng e2e",
        "build": "ng-packagr -p ng-package.json"
    },
    "private": false,
    "dependencies": {
        "@angular/animations": "~8.0.0",
        "@angular/common": "~8.0.0",
        "@angular/compiler": "~8.0.0",
        "@angular/core": "~8.0.0",
        "@angular/forms": "~8.0.0",
        "@angular/platform-browser": "~8.0.0",
        "@angular/platform-browser-dynamic": "~8.0.0",
        "@angular/router": "~8.0.0",
        "@types/jquery": "^3.3.31",
        "jquery": "^3.4.1",
        "rxjs": "~6.4.0",
        "tslib": "^1.9.0",
        "zone.js": "~0.9.1"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "0.803.12",
        "@angular/cli": "~8.0.1",
        "@angular/compiler-cli": "~8.0.0",
        "@angular/language-service": "~8.0.0",
        "@types/jasmine": "~3.3.8",
        "@types/jasminewd2": "~2.0.3",
        "@types/node": "~8.9.4",
        "codelyzer": "^5.0.0",
        "jasmine-core": "~3.4.0",
        "jasmine-spec-reporter": "~4.2.1",
        "karma": "~4.1.0",
        "karma-chrome-launcher": "~2.2.0",
        "karma-coverage-istanbul-reporter": "~2.0.1",
        "karma-jasmine": "~2.0.1",
        "karma-jasmine-html-reporter": "^1.4.0",
        "ng-packagr": "^5.7.0",
        "protractor": "~5.4.0",
        "ts-node": "~7.0.0",
        "tslint": "~5.15.0",
        "typescript": "~3.4.3"
    }
}`

ng-package.json --

`{
    "$schema": "./node_modules/ng-packagr/package.schema.json",
    "name": "@html5ravi/as_input",
    "version": "1.0.0",
    "ngPackage": {
        "lib": {
            "entryFile": "public_api.ts"
        }
    }
}`

please help me out on this.

**Comment by alan-agius4** [comment]
In `ng-package.json`, `name` is not a valid property, kindly remove it.

**Comment by raviji** [comment]
@alan-agius4 I have removed `name` still getting error and this time other one
`ERROR: Configuration doesn't match the required schema.
Data path "" should NOT have additional properties (version).`

I have removed that too and getting error still as below

`ERROR: Configuration doesn't match the required schema.
Data path "" should NOT have additional properties (ngPackage).`

**Comment by mariohmol** [comment]
In my case was the  `"workingDirectory": "../.ng_build",`
