### ISSUE TITLE
Secondary entrypoint named "license" not working

### ISSUE THREAD

**Issue by vmcbaptista** [ng-packagr/ng-packagr#1451]
## Type of Issue

```
[x ] Bug Report
[ ] Feature Request
```

## Description

I'm using ng-packagr to create an npm package with several secondary entrypoints.

One of the entrypoints is called "license".

All the other secondary entry-points are correctly generated. Is "license" a forbidden word?

#### How To Reproduce

I created a sample repository to reproduce the problem:
https://github.com/vmcbaptista/ng-packgr-issue

If you execute npm run build:components, you will see that the generated package.json under dist/components/license stays like:

```json
{
  "ngPackage": {}
}
```

#### Expected Behaviour
Comparing with the working secondary entry points I expect that the package.json generated look like:
```json
{
  "main": "../bundles/components-license.umd.js",
  "module": "../fesm5/components-license.js",
  "es2015": "../fesm2015/components-license.js",
  "esm5": "../esm5/license/components-license.js",
  "esm2015": "../esm2015/license/components-license.js",
  "fesm5": "../fesm5/components-license.js",
  "fesm2015": "../fesm2015/components-license.js",
  "typings": "components-license.d.ts",
  "metadata": "components-license.metadata.json",
  "sideEffects": false,
  "name": "components/license"
}
```

#### Version Information

```
ng-packagr:            5.7.1
@angular/compiler:     8.2.14
rollup:                1.25.2
tsickle:               0.37.1
typescript:            3.5.3
```

**Comment by alan-agius4** [comment]
Hi @vmcbaptista, 

I took at look at your reproduction. But I can see that the license entry point was generated.

**Comment by vmcbaptista** [comment]
Hi @alan-agius4 
I updated the repo with the output I receive
If you check https://github.com/vmcbaptista/ng-packgr-issue/blob/master/dist/components/license/package.json

You will see that it is not filled with the entrypoints like the
https://github.com/vmcbaptista/ng-packgr-issue/blob/master/dist/components/abc/package.json

**Comment by alan-agius4** [comment]
Hi @vmcbaptista, I am still unable to replicate.

```
$ cat dist/components/license/package.json 
{
  "main": "../bundles/components-license.umd.js",
  "module": "../fesm5/components-license.js",
  "es2015": "../fesm2015/components-license.js",
  "esm5": "../esm5/license/components-license.js",
  "esm2015": "../esm2015/license/components-license.js",
  "fesm5": "../fesm5/components-license.js",
  "fesm2015": "../fesm2015/components-license.js",
  "typings": "components-license.d.ts",
  "metadata": "components-license.metadata.json",
  "sideEffects": false,
  "name": "components/license"
}
```

Can you provide the output of ng version?

**Comment by vmcbaptista** [comment]
```
$ ng version
Angular CLI: 8.3.19
Node: 10.15.3
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.19
@angular-devkit/build-angular      0.803.19
@angular-devkit/build-ng-packagr   0.803.19
@angular-devkit/build-optimizer    0.803.19
@angular-devkit/build-webpack      0.803.19
@angular-devkit/core               8.3.19
@angular-devkit/schematics         8.3.19
@angular/cli                       8.3.19
@ngtools/webpack                   8.3.19
@schematics/angular                8.3.19
@schematics/update                 0.803.19
ng-packagr                         5.7.1
rxjs                               6.4.0
typescript                         3.5.3
webpack                            4.39.2
```

**Comment by alan-agius4** [comment]
@vmcbaptista, managed to replicate it on Windows, but failed to identify where the problem is coming from.

**Comment by SchnWalter** [comment]
The windows FS is case-insensitive, the problem might be in here: https://github.com/ng-packagr/ng-packagr/blob/0c6b218c41af697823abb94e4051f61c063149d9/src/lib/ng-package/package.transform.ts#L220-L224

**Comment by SchnWalter** [comment]
@vmcbaptista, can you please give PR https://github.com/ng-packagr/ng-packagr/pull/1849 a try? A `license` entry point should now be properly included in the build on case-insensitive file systems.

```
git clone git@github.com:SchnWalter/ng-packagr.git
git checkout issue-1451-license-entry-point
yarn install
yarn test
```
