### ISSUE TITLE
Support for react components with scss imports

### ISSUE THREAD

**Issue by CarstenLeue** [ng-packagr/ng-packagr#1452]
## Type of Issue

```
[ ] Bug Report
[x ] Feature Request
```

## Description

ng-packagr supports to package react components, potentially alongside angular components, according to this page: https://github.com/ng-packagr/ng-packagr/blob/master/docs/jsx.md

It is common practice for react components though to import component level `scss` files directly from the `tsx` source of the component, e.g. like this:

```tsx
import { FC } from "react";
import * as React from 'react';
import './_test.component2.scss';

export const TestComponent2: FC = () => <div className={'test-component-2'}>TestComponent2</div>;
```

Currently it is not possible to package such a component with ng-packagr because of two reasons:
- the scss files are not copied over to the `dist` folder. This can easily be mitigated by a post-build step
- the compile fails with an error message like this:
```
Building Angular Package

------------------------------------------------------------------------------
Building entry point 'sample-react-lib1'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
Bundling to FESM2015
ERROR: Could not resolve './_test.component2.scss' from dist\esm2015\lib\components\test-2\test.component2.js
error Command failed with exit code 111.
```
Note that the `esm5` has been generated successfully at this point.

In addition I see a conceptual issue: during the generation of the `fesm` packages, all sources will be rolled up into a single file. This will also be true for the `scss` imports, and this will then break tree-shaking for the scss files. 
Note that tree shaking would work fine for `scss` files imported from non-rolled-up files.

**Request:**
Support the inclusion of react components that import `scss` files from the component sources.

Please note that the request is explicitly **NOT** to compile the scss and to include the resulting css somehow via a loader. The generates ESM JS files should contain the `scss` import statements, such that the consuming application can compile them.

**Comment by alan-agius4** [comment]
Thanks for this feature request.


However, seeing the little interest from the community around this we don't plan to address it at the moment.
