### ISSUE TITLE
Do not export the 'metadata' key for non-angular modules

### ISSUE THREAD

**Issue by CarstenLeue** [ng-packagr/ng-packagr#1455]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description
While ng-packagr is meant to be used to build angular libraries it is also a very good general purpose packaging tool, also applicable for modules that do not contain Angular dependencies.
We e.g. use it to package libraries with support or utility code that is then used by other Angular modules, but the utility library does not have an Angular dependency on its own.

It turns out that if Ivy is enabled when building the application, the Ivy compiler will cross-compile all dependencies that have a `metadata` field in their package json, probably assuming  that these are Angular libraries. However for libraries that have the `metadata` field (because they have been packaged with ng-packagr) but do not feature an Angular dependency, the cross-compile step is not required, it's an identity operation.
Still this step is very time consuming if many libraries are involved.

**Suggested Feature**: Only include the `metadata` field in the `package.json` if the library has an Angular dependency. This could e.g. be detected by analyzing the `peerDependencies` or by checking the generated `metadata.json` file for references to `@angular`.

A workaround is of course to remove the field in a cusom post-build step, but it would be very convenient to have it as part of the official build.

**Comment by alan-agius4** [comment]
Thanks for opening this issue, however ng-packagr goal is to build and package Angular libraries.
