### ISSUE TITLE
Add option to publish a library built with ivy

### ISSUE THREAD

**Issue by ocombe** [ng-packagr/ng-packagr#1467]
## Type of Issue

```
[x] Feature Request
```

## Description

I have a library that is only for ivy, it uses ivy APIs that are not available in previous versions of the framework.
When I tried to publish it, I get the message:
> info:    err >  ERROR: Trying to publish a package that has been compiled by Ivy. This is not allowed.
> Please delete and rebuild the package, without compiling with Ivy, before attempting to publish.

#### Expected Behaviour
I should be able to publish my library for ivy anyway. I understand that it should be opt-in only because we want to avoid errors, but there should be a better way to allow that than to force me to manually edit the package.json file every time I want to build/publish my lib.
Ideally there should be an option in `ng-package.json` to do that.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            5.7.1
@angular/compiler:     9.0.0-rc.5
rollup:                1.25.2
tsickle:               0.37.1
typescript:            3.6.4
```

cc @alan-agius4

**Comment by JoostK** [comment]
@ocombe I am very worried about this. Whether Ivy specific API is available or not is not dependent on how a library is bundled, so I don't see how this is necessary.

What particular code are you using that you think is a problem for ngcc to handle?

**Comment by ocombe** [comment]
I'm using stuff from `$localize`, but I tried to disable ivy and it seems to be able to build the lib and it works fine (even if the files are larger).
I guess I don't need ivy to make ivy code works (which sounds weird)?
I'll let you know if I notice something that's not working, I still need to add e2e tests.

**Comment by ocombe** [comment]
Looks like it works fine, sorry for the unnecessary issue

**Comment by dimitri-bret** [comment]
In Angular 9, Ivy is enabled by default, it is a little bit weird to "disable Ivy" in this version for building a lib. Angular 9 is mainly about Ivy.
How do you manage this contradiction for Angular 9 projects?
I think giving this option is a good compromise.
 For my case I am preparing for Angular 9 version, for private and controlled package it is a good idea. I could disable Ivy for compilation but building the project that relies on my Angular 9 Lib: will it be slower to build?

**Comment by Splaktar** [comment]
@dimitri-bret A goal for Angular version 10 to support publishing "Ivy" code to NPM. This is not currently supported in version 9. You can find out more here: https://next.angular.io/guide/ivy#ivy-and-libraries

**Comment by miguel-leon** [comment]
Is there an option to not include the `prepublishOnly` script added to the dist package.json?

My library is private and does not compile without Ivy. It's ok for me to publish it with Ivy, but I wish I didn't have to remove this script after every build.

**Comment by Splaktar** [comment]
@miguel-leon please open an enhancement request for that. It's unlikely to be addressed for `9.x`, but it may be something that could go into version 10.

**Comment by bschaeublin** [comment]
> Is there an option to not include the `prepublishOnly` script added to the dist package.json?
> 
> My library is private and does not compile without Ivy. It's ok for me to publish it with Ivy, but I wish I didn't have to remove this script after every build.

I needed this too (now), so here is my workaround.

- I configured `ng-package.json` to keep its scripts from `src/package.json` with following property set:

`"keepLifecycleScripts": true`

- i added a `prepare` script in my libs `src/package.json`, which looks like this:

 ```
  "scripts": {
    "build:remove:ivy-publishblock": "node ../../../scripts/removePrepublishScript.ts",
    "prepare": "npm run build:remove:ivy-publishblock"
  }
```
- my script which removes the 'scripts' section of the package.json looks like this:
```
const fs = require('fs');
const path = require('path');

// Define absolute paths for original pkg and temporary pkg.
const ORIG_PKG_PATH = path.resolve(__dirname, '../dist/@demo/demo-library/package.json');

// Obtain original `package.json` contents.
const pkgData = require(ORIG_PKG_PATH);

// Delete scripts
delete pkgData.scripts;

// Overwrite original `package.json` with new data (i.e. minus the specific data).
fs.writeFile(ORIG_PKG_PATH, JSON.stringify(pkgData, null, 2), function (err) {
	if (err) {
		throw err;
	}
});

```

**Comment by JohnnyDevNull** [comment]
Well this is pretty wiered why developers for private libraries don't have a force option for ivy libraries. This should be something that should definetly not wait for angular 10! This is a kind of thing where a framework should not make decisions for developers or otherwise giving them the option to force it because of they know what they are doing!

**Comment by flash-me** [comment]
> > Is there an option to not include the `prepublishOnly` script added to the dist package.json?
> > My library is private and does not compile without Ivy. It's ok for me to publish it with Ivy, but I wish I didn't have to remove this script after every build.
> 
> I needed this too (now), so here is my workaround.
> 
> * I configured `ng-package.json` to keep its scripts from `src/package.json` with following property set: `"keepLifecycleScripts": true`
> * i added a `prepare` script in my libs `src/package.json`, which looks like this:
> 
> ```json
>  "scripts": {
>    "build:remove:ivy-publishblock": "node ../../../scripts/removePrepublishScript.ts",
>    "prepare": "npm run build:remove:ivy-publishblock"
>  }
> ```
> 
> * my script which removes the 'scripts' section of the package.json looks like this:
> 
> ```js
> const fs = require('fs');
> const path = require('path');
> 
> // Define absolute path for 'package.json'.
> const ORIG_PKG_PATH = path.resolve(__dirname, '../dist/@demo/demo-library/package.json');
> 
> // Obtain original `package.json` contents.
> const pkgData = require(ORIG_PKG_PATH);
> 
> // Delete scripts
> delete pkgData.scripts;
> 
> // Overwrite `package.json` with new data (i.e. minus the specific data).
> fs.writeFile(ORIG_PKG_PATH, JSON.stringify(pkgData, null, 2), function (err) {
> 	if (err) {
> 		throw err;
> 	}
> });
> ```

Hi @bschaeublin 

`sed -i '/prepublishOnly/d' package.json` does the trick pretty fine.

cheers
flash :zap:

**Comment by michib** [comment]
`npm publish --ignore-scripts` ignores the prepublishOnly Script (also every other script, but my publishable package.json does not contain any other scripts)

**Comment by flash-me** [comment]
@michib!

Nice hint! Never thought of that, thx.

cheers
flash :zap:

**Comment by benjamincharity** [comment]
@ocombe IMO this should be re-opened. 🙏  I'm not sure what the benefit is for `ng-packagr` to enforce this limitation. The error makes it sound as if the infrastructure itself doesn't support Ivy code.

This is giving me flashbacks to the 'peer dependency vs bundled' discussions. Best practices do exist, but I'm not sure it should be this tools job to enforce them. This situation feels very similar. Sure, 90% of people should not be publishing public Ivy packages. But as I've seen through discussions here and in the Angular issues, there are many teams building and publishing internal packages. AFAIK for those packages only consumed by Ivy applications, there is no actual benefit for consuming VE code vs Ivy code.

---

Either way, much love and appreciation for _all_ those involved with this tool! ❤️

**Comment by alan-agius4** [comment]
At the moment, it is not recommended to publish Ivy code both internally and externally. Insofar there is an official support for Ivy published libraries we will not provide an option to publish ivy libraries. In case you want to publish Ivy libraries privately  you can remove the `prepublishOnly` property from the library's package.json before publishing. You are though venturing in unsupported theory, both from ng-packagr and Angular perceptive. 

@petebacondarwin wrote a good explanation here https://github.com/angular/angular/issues/37973#issuecomment-656024069 to why Ivy compiled libraries shouldn't be published.

**Comment by pburgmer** [comment]
@alan-agius4 thanks for sharing the linkt to Pete's comment. Very helpful.

**Comment by Splaktar** [comment]
> Insofar there is an official support for Ivy published libraries we will not provide an option to publish ivy libraries.

@alan-agius4 did you mean the following?

 Insofar as there is **not** official support for Ivy published libraries we will not provide an option to publish ivy libraries.

**Comment by alan-agius4** [comment]
@Splaktar, re-phrase
