### ISSUE TITLE
[Feature Request] Support for paths option when compiling libraries

### ISSUE THREAD

**Issue by fireflysemantics** [ng-packagr/ng-packagr#1469]
## Type of Issue

```
[ ] Bug Report
[X ] Feature Request
```

## Description
If we setup the typescript `paths` option for libraries the libraries get compiled without resolving the paths.  For example if we declared a path like this:

```
      "@app/*": ["projects/my-lib/src/lib/*"] 

```

And build.  The compiled fesm2015 will look like this:

```
import { Test } from '@app/test';

```
I have been using typescript transform paths for this in the past, but I was hoping Angular Library support would have it baked in.  

https://www.npmjs.com/package/typescript-transform-paths

**Comment by arvindnama** [comment]
did not notice the Request . so create one for the same .. 
but i ve a PR for this 
https://github.com/ng-packagr/ng-packagr/pull/1502

**Comment by alan-agius4** [comment]
Kindly see discussion in https://github.com/ng-packagr/ng-packagr/pull/1502
