### ISSUE TITLE
Support ngcc style parallel build

### ISSUE THREAD

**Issue by log2-hwan** [ng-packagr/ng-packagr#1476]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

I found that ngcc (Angular Compatibility Compiler) supports parallel build by using node's `cluster` module [PR link](https://github.com/angular/angular/pull/32427/files). In my understanding, ngcc and ng-packagr have similar build process (calculate inter-package dependency -> Sort packages by dependency -> Run build jobs by order). So supporting ngcc style parallel build can reduce build time dramatically. It may not as easy as what I wrote, so feel free to close this issue if you think this isn't worth of time to implement.

#### How To Reproduce

N/A

#### Expected Behaviour

ng-packagr can run build jobs in parallel.

#### Version Information

```
ng-packagr:            9.0.0-rc.3
@angular/compiler:     9.0.0-rc.6
rollup:                1.27.8
tsickle:               
typescript:            3.6.4
```

**Comment by alan-agius4** [comment]
Thanks for this request. However, this is not something that is in the current roadmap.
