### ISSUE TITLE
resolve custom modules from ts-path 

### ISSUE THREAD

**Issue by arvindnama** [ng-packagr/ng-packagr#1501]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

Current implementation does not resolve custom modules from ts-paths.

i.e.
ts-config.json 
```
 {
 "paths": {
      "@ts-path/api": ["./src/api/index"]
    }
}
```
angular.component.js  ( component in the library)

```
import { Component, Input } from '@angular/core';
import { getSampleApi } from '@ts-path/api';
@Component({
  selector: 'ng-component',
  template: '<h1>{{title}}</h1>',
  styleUrls: ['./angular.component.scss'],
})
export class AngularComponent {
  @Input() title = 'Angular';

  constructor(){
    console.log(getSampleApi());
  }

}
```

here `@ts-path` is a custom module alias , who paths is present in ts-config, 
current ng-packagr build does not resolve these modules based on ts-config path.

#### Expected Behaviour
To Resolve module alias from ts-path

NOTE: I will create a PR on the master branch with the above changes soon.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 9.0.0-rc3
@angular/*: 8.2.3
typescript: 3.5.3
rxjs: 6.5.3
node:12.13.1
npm 6.12.1
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by alan-agius4** [comment]
Kindly see discussion in https://github.com/ng-packagr/ng-packagr/pull/1502
