### ISSUE TITLE
Incorrect detection of `potentialDependencies` in `9.0.0-rc.7`

### ISSUE THREAD

**Issue by CarstenLeue** [ng-packagr/ng-packagr#1510]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I am seeing this error during compilation:

```
ERROR: Entry point @acoustic-content-sdk/ng-edit-api which is required by @acoustic-content-sdk/ng-edit doesn't exists.
```

This problem has not existed in `9.0.0-rc.4`. 

Cause: 

In the file `node_modules\ng-packagr\lib\ng-package\entry-point\analyse-sources.transform.js` the `analyseEntryPoint` method populates the `potentialDependencies` record. 

It uses `moduleName.startsWith(packageNode.data.primary.moduleId)` to tell if the module is such a dependency.

This leads to false positives if the package name is a prefix (and not just a namespace) e.g. for this case:

```json
{
  "name": "@acoustic-content-sdk/ng-edit",
  ...,
  "dependencies": {
    "@acoustic-content-sdk/api": "9.0.0",
    "@acoustic-content-sdk/component-api": "9.0.0",
    "@acoustic-content-sdk/component-edit": "9.0.0",
    "@acoustic-content-sdk/edit-api": "9.0.0",
    "@acoustic-content-sdk/ng-api": "9.0.0",
    "@acoustic-content-sdk/ng-edit-api": "9.0.0",
    "@acoustic-content-sdk/ng-utils": "9.0.0",
    "@acoustic-content-sdk/utils": "9.0.0"
  },
  ...
}
```

The module name found as a dependency is `@acoustic-content-sdk/ng-edit-api` while the module name is `@acoustic-content-sdk/ng-edit`, a prefix of the dependency. 

I think that the test is supposed to find secondary entry points, but in this case `@acoustic-content-sdk/ng-edit-api` is not a secondary entry point but an external dependency.

The check should probably be:

```ts
if ((moduleName === packageNode.data.primary.moduleId) || moduleName.startsWith(packageNode.data.primary.moduleId + '/'))
```

#### Version Information

```
ng-packagr:            9.0.0-rc.7
@angular/compiler:     9.0.0-rc.8
rollup:                1.29.0
tsickle:               0.38.0
typescript:            3.7.4
```

**Comment by alan-agius4** [comment]
good catch

**Comment by JoostK** [comment]
@CarstenLeue nice find, thanks for all the testing and reporting!

**Comment by CarstenLeue** [comment]
@JoostK @alan-agius4 ng-packagr is an awesome tool, I use it a lot, not just for Angular packages. Keep up with the good work!
