### ISSUE TITLE
annotateForClosureCompiler:true generates incorrect DI code

### ISSUE THREAD

**Issue by CarstenLeue** [ng-packagr/ng-packagr#1517]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

This is the ng-packagr version of https://github.com/angular/angular/issues/34832

Summary: 
Setting `annotateForClosureCompiler: true` generates incorrect code for DI which then breaks the ivy pre-compiler:

```js
SitesCellLayoutComponent.ctorParameters = () => [
    { type: undefined }
];
SitesCellLayoutComponent.decorators = [
    { type: Component, args: [{
                selector: 'app-sites-cell-layout-component',
                template: "<div\r\n  *ngIf=\"content$ | async as content\"\r\n  class=\"cell-content\"\r\n  [ngStyle]=\"styles$ | async\"\r\n  [wchEditable]=\"accessor$ | async\"\r\n  data-drop-target=\"true\"\r\n>\r\n  <wch-content\r\n    *ngFor=\"let contentItem of content; trackBy: trackCtx\"\r\n    [ctx]=\"contentItem\"\r\n  ></wch-content>\r\n\r\n  <div #dndPlaceholder class=\"dndPlaceholder\"></div>\r\n\r\n</div>\r\n\r\n",
                changeDetection: ChangeDetectionStrategy.OnPush,
                preserveWhitespaces: false,
                styles: [".cell-content{display:block;width:100%;min-height:1rem}wch-content{display:block}.dndPlaceholder{width:100%;height:2rem;background-color:#87cefa;border:1px solid #0000cd}"]
            }] }
];
/** @nocollapse */
SitesCellLayoutComponent.ctorParameters = () => [
    { type: undefined, decorators: [{ type: Optional }, { type: Inject, args: [WCH_TOKEN_LOGGER_SERVICE,] }] }
];
```

This shows generated code. The `ctorParameters ` appears twice.

#### How To Reproduce

Use this repo to reproduce: https://github.com/Carsten-Leue/ivy-module

```bash
yarn install
yarn build
```

The inspect the generated code in the `dist` folder.

#### Expected Behaviour

ng-packagr should generate valid code with `annotateForClosureCompiler` set to either true or false

#### Version Information

```
ng-packagr:            9.0.0-rc.7
@angular/compiler:     9.0.0-rc.9
rollup:                1.29.0
tsickle:               0.37.1
typescript:            3.6.4
```

**Comment by alan-agius4** [comment]
Note: this seems to be caused by the usage of custom decorators, when removing custom decorations it seems to be working fine.

Will need to investigate this a bit more in the coming days.

**Comment by alan-agius4** [comment]
Root cause seems to be that we are running the `downlevelConstructorParameters` even when `annotateForClosureCompiler` is enabled.

https://github.com/ng-packagr/ng-packagr/blob/9e05fb3c70c812d1ac9d72c36789bbff1c967a90/src/lib/ngc/compile-source-files.ts#L89
