### ISSUE TITLE
With inlineSourceMap enabled external .map files are still generated and source maps are not inlined

### ISSUE THREAD

**Issue by JonWallsten** [ng-packagr/ng-packagr#1537]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

When building our library with ng-packagr *.js.map files are created in the bundles/fesm5/fesm2015 folders even though I have specified `inlineSourceMap: true` in my tsconfig.json file.
This causes an issue with loading the source maps since our Webpack build expects inline sourcemaps when it bundles our application.

![image](https://user-images.githubusercontent.com/5993909/74144326-d2e0a180-4bfc-11ea-83bf-8eccd7bbda7f.png)

```
//# sourceMappingURL=oas-web-lib-angular.umd.js.map
```

This results in the following error in Chrome:
![image](https://user-images.githubusercontent.com/5993909/74137527-47f9aa00-4bf0-11ea-9940-83f9fa46ee08.png)

#### How To Reproduce

Run ng-packagr through the API:
```ts
import * as ngPackage from 'ng-packagr';
import yargs from 'yargs';

const argv = yargs.argv;

ngPackage
  .ngPackagr()
  .forProject('ng-package.json')
  .withTsConfig('./tsconfig.build.json')
  .withOptions({ watch: (argv.watch as boolean) })
  .build()
  .catch(error => {
      console.error(error);
      process.exit(1);
  });
 
```

tsconfig.build.json:
```
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "strictNullChecks": true,
    "noImplicitReturns": true,
    "inlineSourceMap": true,
    "inlineSources": true,
    "skipLibCheck": true,
    "importHelpers": true,
    "target": "es2015",
    "module": "es2015",
    "moduleResolution": "node",
    "typeRoots": [
      "node_modules/@types",
      "../../node_modules/@types",
      "./typings/",
      "../../typings/"
    ]
  },
  "files": [
    "src/index.ts",
    "./typings/global.d.ts",
    "../../typings/global.d.ts"
  ],
  "angularCompilerOptions": {
    "enableIvy": true,
    "skipTemplateCodegen": true,
    "strictMetadataEmit": true,
    "fullTemplateTypeCheck": true,
    "enableResourceInlining": true
  }
}
```

I have tried both with sourceMaps: false and true in combination with inlineSourceMap: true.

#### Expected Behaviour

Sourcemaps should be inlined and base64 encoded for easier consumption in Webpack.

#### Version Information

```
ng-packagr:            9.0.0
@angular/compiler:     9.0.0
rollup:                1.31.0
tsickle:
typescript:            3.7.5
rxjs                   6.5.4
typescript             3.7.5
webpack                4.41.5
Node:                  12.14.0
OS:                    win32 x64
```

**Comment by JonWallsten** [comment]
@alan-agius4: I'm really eager to get this fixed. As of now we have to debug using the compiled bundle file. It's not really a viable solution. Do you mind pointing me in the right direction for debugging this? Like which file's responsible for the compiling?

**Comment by alan-agius4** [comment]
Edit: I found it now. It's the rollup step. But the uglify part is involed later. It seems like it's easier for me to find a way to either make them inline again, or find a way for Webpack to consume the external file.
> Indeed it is the Rollup step

Edit2: It might make sense to have development/production mode even for the lib since it would be consumed during development for internal libraries.
> And what would be the differenced between development/production?

Edit3: It isn't working out of the box with source-map-loader. It finds and process the source-map. But it's not working unfortunately. To many moving parts involved. I will try to disabled uglify and use inline sourcemaps for the bundle instead.
> Not sure what's the problem here, as this works with Angular CLI at least for FESMs. The error in the devtools seems to be pointing to an incorrect path, `oas-web-lib-angular.js.map` instead of `oas-web-lib-angular.umd.js.map`

Also, I am curios to know what's the reason to use UMD bundle in the browser, especially seeing that you are using webpack.

Edit4: It doesn't work with inline sourcemaps either. I guess Webpack or AngularCompilerPlugin aren't able to consume the sourcemaps from the lib. Not sure who's responsibility it is.
Webpack will not load library sourcemaps by default. You'd need to use https://www.npmjs.com/package/source-map-loader

**Comment by JonWallsten** [comment]
> And what would be the differenced between development/production?

I guess minifying would not be needed for development. I know minifying usally messed with the source maps.

 > Not sure what's the problem here, as this works with Angular CLI at least for FESMs. The error in the devtools seems to be pointing to an incorrect path, `oas-web-lib-angular.js.map` instead of `oas-web-lib-angular.umd.js.map`

I think the error is the correct source of information here. It's clear to me now that Webpack is consuming this one: `web-lib-angular/dist/fesm5/oas-web-lib-angular.js`
So the error makes sense
```
DevTools failed to load SourceMap: Could not load content for http://localhost:4000/oas-web-lib-angular.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE 11:32:04.051
```

> Also, I am curios to know what's the reason to use UMD bundle in the browser, especially seeing that you are using webpack.

As stated above I was probably looking at the wrong files when I did the initial investigation.

> Webpack will not load library sourcemaps by default. You'd need to use https://www.npmjs.com/package/source-map-loader

We use EvalSourceMapDevToolPlugin for creating inlined sourcemaps for our other libraries. It works out of the box, hence my idea that it had to do with the external/inline thing. But when checking the bundle created by our App (that consumes the Angular library) the inline sourcemaps are just stripped away. The sourcemaps for all other libraries are working fine though. They are not lost.

So this is an example from the bundle of another library we create (TypeScript->ES5 with ts-loader)
![image](https://user-images.githubusercontent.com/5993909/80582314-c1927e80-8a0e-11ea-9b26-25f17a3f2228.png)

Looking at the image below you can see why chrome is looking for the sourcemaps in the root of the webserver, but as far as I know source-map-loader doesn't copy map files, it consumes them. So this wouldn't work anyway. The file will never be found unless I copy it manually in my Webpack config (probably the easiest way to solve this)

![image](https://user-images.githubusercontent.com/5993909/80582429-fb638500-8a0e-11ea-8374-c84cddb47107.png)
 
When I used inline sourcemaps in rollup the line that now says `//# sourceMappingURL=oas-web-lib-angular.js.map` was just removed in the bundle. Not sure why this line is kept but not he inlines sourcemap? Unfortunately I don't know if it's Webpack or AngularCompilerPlugin. So it's hard to debug.
