### ISSUE TITLE
There isn't a GitHub Pages site here (ng-packagr.github.io/ng-packagr)

### ISSUE THREAD

**Issue by splincode** [ng-packagr/ng-packagr#1539]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

![image](https://user-images.githubusercontent.com/12021443/74310650-b7050900-4d7e-11ea-9b3a-922d80f80db0.png)

**Comment by alan-agius4** [comment]
Links to this page have been removed.
