### ISSUE TITLE
Support es6 output in UMD bundle

### ISSUE THREAD

**Issue by fr0** [ng-packagr/ng-packagr#1541]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

I want to be able to use the `.umd.js` bundle for use with `systemjs`; however, I also want it to be compiled to es6+ (e.g. use real classes instead of `__extends`, use `async`/`await` instead of `__awaiter`+`yield`). Is this possible?

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            9.0.0
@angular/compiler:     9.0.0
rollup:                1.31.0
tsickle:               
typescript:            3.7.5
```

**Comment by alan-agius4** [comment]
Hi,

This is not possible, and this is outside of the scope of ng-packagr as we follow the APF spec where UMD bundles contain ES5 code.

Also, native async/await will not work with ZoneJs.

See: https://github.com/angular/angular/issues/31730
