### ISSUE TITLE
[proposal] support targeting `esnext`

### ISSUE THREAD

**Issue by JounQin** [ng-packagr/ng-packagr#1542]
## Type of Issue

- [ ] Bug Report
- [x] Feature Request

## Description

It is possible to use `babel` instead of `typescript` to compile `.ts` files, and then `@babel/polyfill` can be integrated.

We are using this pattern in [@alauda/custom-webpack](https://www.npmjs.com/package/@alauda/custom-webpack) at @alauda .

But for libraries, `ng-packagr` does not produce `esnext` bundles for now.

It would be awesome to support this feature.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            9.0.0
@angular/compiler:     9.0.0
rollup:                1.31.0
tsickle:               0.38.0
typescript:            3.7.5
node: v12.14.1
yarn: 1.22.0
```

**Comment by alan-agius4** [comment]
Thanks for this feature request. 

This request however is not in line with APF specs and thus is not in scope of ng-packagr.

**Comment by JounQin** [comment]
@alan-agius4 Thanks for your reply, so is there any place to post a proposal to add `esnext` support into APF spec?
