### ISSUE TITLE
Feature request: watch assets files and rebuild on changes

### ISSUE THREAD

**Issue by JayChase** [ng-packagr/ng-packagr#1545]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

Add an option to watch files listed in the new assets option and update rebuild a library when running `ng build --watch`.

To be able to add scss files to a library has made it easier to add Angular Material theme support for components in a library. If there was an option to watch them for changes and rebuild this would really improve the development experience (esp using Storybook for Angular).

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 9.0.0
@angular/*: 9.0.1
typescript: 3.7.5
rxjs: 6.5.4
node: 12.14.0
npm: 6.13.4
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by ivan-saorin** [comment]
I would really appreciate this feature,
