### ISSUE TITLE
ERROR in the target entry-point "my-library" has missing dependencies

### ISSUE THREAD

**Issue by miladamery** [ng-packagr/ng-packagr#1546]
## Type of Issue

```
[x] Bug Report
```

## Description
I have an angular library project which contains what ever is common for me( i build it with ng-packagr) and i reuse the library in other projects. recently i migrated to angular 9 and v 9.0.0 of ng-packagr. library project gets build perfectly with no problem but when i use it in other projects that depend on it in prod build i get following error:
```sh
ERROR in the target entry-point "my-library" has missing dependencies
- @angular/forms/src/directives/control_value_accessor
- @angular/core/src/type
```
#### Expected Behaviour
To use produced library without any error in production build

#### Version Information

```
ng-packagr: 9.0.0
@angular/*: 9.0.1
typescript: 3.7.5
rxjs: 6.5.4
node: 12.16.0
```

**Comment by JoostK** [comment]
This looks like a bug in your library, not ng-packagr, nor Angular 9.

The library appears to contain deep imports into the mentioned paths, which is not allowed when importing things from `@angular` packages. As such, please locate the imports into the mentioned paths and replace them with just `@angular/core` and `@angular/forms`.

**Comment by alan-agius4** [comment]
Thanks @JoostK for chiming in.

**Comment by miladamery** [comment]
@JoostK @alan-agius4                  
Thanks. The problem wasn't in my code. one of 3rd party libraries that i was using in my library project possessed such code. well took me a long time to find it and it is painful to see error in this way. i hope ng-packagr could tell me this error existed when i was building my library with it.
