### ISSUE TITLE
compilation error in HTML files when switching version 2.4.2 to 9.0.0

### ISSUE THREAD

**Issue by secabhi** [ng-packagr/ng-packagr#1547]
## Type of Issue

```
Bug Report
```

## Description
I have upgraded ng-packagr version from 2.4.2 to 9.0.0 .
All my HTML files throwing below error - 

```
WARNING: Invalid font values at 516:2. Ignoring.
WARNING: Invalid font values at 92:2. Ignoring.
WARNING: Invalid font values at 421:2. Ignoring.
ERROR: src/app/components/menu/menu.component.html(5,70): : Property 'data' does not exist on type 'CurrentOptionMenuHandler'.
src/app/components/menu/menu.component.html(5,70): : Property 'key' does not exist on type 'CurrentOptionMenuHandler'.
src/app/components/dynamic-form-field/dynamic-form-field.component.html(7,13): : Property 'type' does not exist on type 'FormBase<any>'.
src/app/components/dynamic-form-field/dynamic-form-field.component.html(8,13): : Property 'type' does not exist on type 'FormBase<any>'.
src/app/components/dynamic-form-field/dynamic-form-field.component.html(6,13): : Property 'type' does not exist on type 'FormBase<any>'.
src/app/components/dynamic-form-field/dynamic-form-field.component.html(6,13): : Property 'type' does not exist on type 'FormBase<any>'.
src/app/components/dynamic-form-field/dynamic-form-field.component.html(9,13): : Property 'type' does not exist on type 'FormBase<any>'.
src/app/components/dynamic-form-field/dynamic-form-field.component.html(10,13): : Property 'type' does not exist on type 'FormBase<any>'.
src/app/components/dynamic-form-field/dynamic-form-field.component.html(11,80): : Expected 0 arguments, but got 1.
src/app/components/dynamic-form-field/dynamic-form-field.component.html(12,13): : Expected 0 arguments, but got 1.
src/app/components/dynamic-form-field/dynamic-form-field.component.html(12,44): : Expected 0 arguments, but got 1.
src/app/components/dynamic-form-field/dynamic-form-field.component.html(16,25): : Property 'options' does not exist on type 'FormBase<any>'.
src/app/components/dynamic-form-field/dynamic-form-field.component.html(15,43): : Expected 0 arguments, but got 1.
src/app/components/dynamic-form-field/dynamic-form-field.component.html(21,13): : Expected 0 arguments, but got 1.
src/app/components/dynamic-form-field/dynamic-form-field.component.html(25,51): : Expected 0 arguments, but got 1.
```
#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 9.0.0
@angular/*: 8.0.1
typescript: 3.4.5
rxjs: 6.5.0
node: 10.16.2
npm: 6.9.0
```

#### ng-package.json 
```
{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "lib": {
    "entryFile": "public_api.ts",
    "umdModuleIds": {
      "@angular/flex-layout": "ng.flex-layout",
      "moment": "moment"
    },
    "flatModuleFile": "index",
    "cssUrl": "inline"
  },
  "whitelistedNonPeerDependencies": [
    "."
  ],
  "dest": "build"
}
```

**Comment by alan-agius4** [comment]
@secabhi, the error messages you are getting seems genuine. Does `CurrentOptionMenuHandler` have `data` and `key` properties?

**Comment by alan-agius4** [comment]
Note: ng-packagr version 9 is only compatible with Angular version 9.

**Comment by secabhi** [comment]
@alan-agius4 The error message was not coming when I was using ng-packgr - 2.4.2 with angular v8. Are you suggesting me to upgrade angular to v9 and then check issues?

**Comment by alan-agius4** [comment]
Ng-packagr version 2 was not compatible with Angular version 8, you probably are experiencing genuine errors that previously were unreported.

As a recommendation, I do suggest to update Angular and TypeScript to the supported versions as otherwise you might get undefined/broken behaviour.

**Comment by secabhi** [comment]
@alan-agius4 Still facing the same issue updated to angular 9.0.1. Is possible to somehow disable these checks?

**Comment by alan-agius4** [comment]
@secabhi, you can add provide a custom tsconfig and turn off `fullTemplateTypeCheck` https://github.com/ng-packagr/ng-packagr/blob/36830f40a71662667d15a402bac9868092abfed5/src/lib/ts/conf/tsconfig.ngc.json#L6

That being said, I would strongly suggest against this and instead opt to fix the implementation as otherwise you might get runtime issues.

**Comment by secabhi** [comment]
@alan-agius4 I got your point. I have tried disabling "fullTemplateTypeCheck" . It worked.
I have created a custom tsconfig file, but don't know where to add the path. Can you help me here?

**Comment by secabhi** [comment]
I have tried creating lib folder and put tsconfig.lib.json. But it didn't work. I am using one tsconfig.json as root and another as tsconfig.app.json inside my src folder which extends the root tsconfig. 
I have already tried
```
"fullTemplateTypeCheck": true,
```
in roo tsconfig.json. But it didn't work
