### ISSUE TITLE
Allow custom transformers

### ISSUE THREAD

**Issue by hmil** [ng-packagr/ng-packagr#1558]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

There are a number of awesome TypeScript libraries which leverage the power of typescript transformers.

Unfortunately, it is not possible to use any of those with ng-packagr at the moment because ng-packagr doesn't let users add custom transformers to the typescript build.

One nice way to expose this feature would be to recognize the `plugins` option in `tsconfig.json` as is currently done by [ttypescript](https://github.com/cevek/ttypescript).

---

Some people are so desperate for this feature, they have gone to [insane length](https://medium.com/joolsoftware/custom-typescript-transformers-with-angular-cli-7f4150797e05) in order to inject custom transformers in the build pipeline of angular.
However, the above hack is based on webpack and so it cannot work with ng-packagr. A better alternative would be to provide official support for transformers.

**Comment by alan-agius4** [comment]
Let's consider this in the future when https://github.com/angular/angular/issues/22434 is resolved.
