### ISSUE TITLE
components not work when create by service and compiled by ng-packgar

### ISSUE THREAD

**Issue by vthinkxie** [ng-packagr/ng-packagr#1576]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

There are two components, the parent component **P** and the child component **C**.

1. create **P** component by the service
2. import the **P** component in the **C** component
3. compiled by `ng-packagr`
4. run in **prod** mode.

All change detection inside **P** components doesn't work anymore.

#### How To Reproduce

I have created a reproduction repo: https://github.com/vthinkxie/ng-packagr-bug

1. ng build message
2. ng serve --prod
3. visite localhost:4200

Click the message, a message will popup

1. uncomment this line https://github.com/vthinkxie/ng-packagr-bug/blob/c5dced469ac24e3e5b2a3a046793e40e36628043/projects/message/src/lib/message.component.ts#L3
2. ng build message
3. ng serve --prod
4. visite localhost:4200

Click the message, no message will popup

#### Expected Behaviour

one message will popup

#### Version Information

```
ng-packagr:            9.0.3
@angular/compiler:     9.0.6
rollup:                1.32.1
tsickle:               
typescript:            3.7.5
```

the fesm2015 file generated by ng-packagr is different in two situations
it seems that the bug is caused by the missing of `directives: [NgForOf, MessageComponent]`
and the bug one has more imports than the normal one

-  https://github.com/vthinkxie/ng-packagr-bug/blob/master/message-bug.js
-  https://github.com/vthinkxie/ng-packagr-bug/blob/master/message-no-bug.js

**Comment by JoostK** [comment]
This is not an ng-packagr bug, but rather an issue with how the Angular compiler deals with cyclic references that ends up violating the `"sideEffects": false` flag. More info in angular/angular#35602, there's a workaround described [in this comment](https://github.com/angular/angular/issues/35602#issuecomment-591133414).

**Comment by vthinkxie** [comment]
Hi @JoostK 
thanks for your quick response!

**Comment by alan-agius4** [comment]
Thanks @JoostK, closing as per above.
