### ISSUE TITLE
Slow watch mode

### ISSUE THREAD

**Issue by rmannibucau** [ng-packagr/ng-packagr#1580]
## Type of Issue

```
[ ] Bug Report
[X] Feature Request
```

## Description

Using watch mode should enable to have fast update roud trip, however ngc phase stays slow whereas other phases are acceptable.

#### How To Reproduce

Build a project with some dependencies and angular 9.0.x.

#### Expected Behaviour

A simple update (even just forcing a file save) should refresh the umd files in really max around 1s, today it is ~4-5s on my computer.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 9.0.3
@angular/*: 9.0.7
typescript: 3.7.5
rxjs: 6.5.4
node: v12.14.1
npm: 6.13.4
// lib
@ngx-formly/material": "^5.5.13
```

If it helps: main slowness points are (from compile-source-files):

1. ngProgram.loadNgStructureAsync
2. ngProgram.getNgSemanticDiagnostics (and a few other get...Diagnostics): here program.getSourceFiles() is iterated and tests with a regex (without ivy) the files. By it self it is fast by since the number of file is often ~720 (even for small projects, it comes from deps), then the regex test and extraction become way slower than a plain endsWith/subtring impl (see https://github.com/angular/angular/issues/36148#issuecomment-601367380 for details). Guess some optimization is doable on ng-packgr side.
3. compile-ngc.transform does 2 compilations calling 2 which the "same" cost i spaid twice.

Side note: the rest of the compilation round trip is acceptable, it is really the ngc phase which is slow.

**Comment by alan-agius4** [comment]
Thanks @rmannibucau, thanks for this issue and the superb investigation 👍.
