### ISSUE TITLE
Extend Rollup Config to use Postcss

### ISSUE THREAD

**Issue by gquinteros93** [ng-packagr/ng-packagr#1590]
## Type of Issue

```
[ ] Bug Report
[ ] Feature Request
[x] Documentation
```

## Description

Hi, I would like to use [postcss](https://www.npmjs.com/package/postcss) through [rollup](https://rollupjs.org/) like is used here:
https://www.learnwithjason.dev/blog/learn-rollup-css/

I saw in the documentation that is possible to extend the rollup config:
https://github.com/ng-packagr/ng-packagr/blob/master/docs/DESIGN.md#rollup-config

However, I didn't find any documentation or example on how to do that.

#### How To Reproduce

No Documentation available.

#### Expected Behaviour

Have Documentation that explains how to extend the rollup config.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 4.2.0
@angular/*: 7.2.0
typescript: 3.2.2
rxjs: 6.3.2
node: >= 8.0.0
npm/yarn: >= 5
```

**Comment by gquinteros93** [comment]
Hi, I added this question on two different questions in Stackoverflow:

- https://stackoverflow.com/questions/60955837/ng-packagr-extend-rollup-config

- https://stackoverflow.com/questions/60937107/use-postcss-in-custom-angular-library

But I don't have any response or help yet.

**Comment by vasicvuk** [comment]
Missing of these options is killing Developer freedom :). We do not have any option to extend Library build pipeline which is very bad. As with Ivy loading dynamic modules is easy, there should be an option to extend the build process and include some custom things in the output UMD file.

**Comment by alan-agius4** [comment]
Rollup is an implementation detail which can be changed at anytime without warning. Also, rollup is only used to generate the FESMs and UMD bundles. ESM bundles are not processed by Rollup.

Adding custom postcss plugins is currently not supported, We'll be looking at this in the future.
