### ISSUE TITLE
Add PNPM support

### ISSUE THREAD

**Issue by knafteN** [ng-packagr/ng-packagr#1595]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

Please add support for https://github.com/pnpm/pnpm, which is another package manager like npm or yarn.

It seems that ng-packagr cannot resolve symlinks/junctions, which is what pnpm packages are made of in the node_modules folder. See https://pnpm.js.org/en/ in the "background" section

#### How To Reproduce

- `npm i -g pnpm`
- `git clone https://github.com/knafteN/ng-packagr-pnpm.git`
- `cd ng-packagr-pnpm`
- `pnpm i`
- `pnpm run pkg`

#### Expected Behaviour
The dist folder gets created. The package is exported.

#### Version Information

Running on windows machine.

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            9.1.0
@angular/compiler:     9.1.1
rollup:                2.2.0
tsickle:               0.38.0
typescript:            3.8.3

node: 10.13.0
pnpm: 4.12.5
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by literalpie** [comment]
I would love to see this. Although pnpm isn't intentionally supported by the angular team ([see here](https://github.com/angular/angular/issues/32087#issuecomment-523225437)), most things seem to work. The only things keeping my team from moving to pnpm is that ng-packagr fails to build the library

**Comment by alan-agius4** [comment]
Closing as this should have been resolved in version 13.
