### ISSUE TITLE
Support packaging of Web Components?

### ISSUE THREAD

**Issue by fireflysemantics** [ng-packagr/ng-packagr#1599]
## Type of Issue

```
[ ] Bug Report
[ X] Feature Request
```

## Description
https://stackoverflow.com/questions/61151396/distributing-web-components-as-a-library-with-the-angular-package-format

I wrote up the description in the above reference SO  Post.

_A feature: please describe your use case and motivation_

To be able to package web components.

**Comment by alan-agius4** [comment]
Closing as this is currently out of scope.
