### ISSUE TITLE
[Question] - Is there a way to include an external lib in the umd bundle?

### ISSUE THREAD

**Issue by albeserra** [ng-packagr/ng-packagr#1600]
## Type of Issue

```
[X ] Question
```

## Description

My question is: Is there a way to include an external library in thefinal js code umd bundle?
I need a simple js file to be imported in an index.html app. The ng-packagr works like a charm but when I use external libraries I cannot bundle them inside my js code. 
For example my imports are:

`import * as jwt from 'jsonwebtoken';
import { Class as MyClass } from '@my-package/example';
`

My ng-package.json file: 

```
  "$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
  "dest": "../../dist/libs/mylib",
  "lib": {
    "entryFile": "src/index.ts",
    "umdModuleIds": {    "jsonwebtoken": "jsonwebtoken", 
    }
  },
  "whitelistedNonPeerDependencies": ["."]
}
```

Sorry If I'm posting questions here but I cannot get a solution for this issue. I tried a lot of examples. Does anyone have any suggestions? Thank you!

**Comment by donmahallem** [comment]
Do angulars bundledDependencies the job? You add that besides the common (dev/peer)dependencies tag inside the libraries package.json

**Comment by albeserra** [comment]
> Do angulars bundledDependencies the job? You add that besides the common (dev/peer)dependencies tag inside the libraries package.json
I dont know, but I resolved building my library with @angular-devkit/build-webpack:webpack with architect and a webpack config file. This process runs inside nx :

`...
"architect": {
        "build": {
          "builder": "@angular-devkit/build-webpack:webpack",
          "options": {
            "webpackConfig": "libs/my-lib/webpack.config.js"
          },
          "configurations": {
            "production": {
            }
          }
        },

...`

**Comment by vasicvuk** [comment]
@albeserra 
Can you share your webpack config including lib in UMD bundle?

**Comment by albeserra** [comment]
> @albeserra
> Can you share your webpack config including lib in UMD bundle?

that's my lib configuration on nx angular.json file: 

`"MY-LIB": {
      "root": "libs/MY-LIB",
      "sourceRoot": "libs/MY-LIB/src",
      "projectType": "library",
      "schematics": {},
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-webpack:webpack",
          "options": {
            "webpackConfig": "libs/MY-LIB/webpack.config.js"
          },
          "configurations": {
            "production": {
            }
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": ["libs/MY-LIB/tsconfig.lib.json", "libs/MY-LIB/tsconfig.spec.json"],
            "exclude": ["**/node_modules/**", "!libs/MY-LIB/**"]
          }
        },
        "test": {
          "builder": "@nrwl/jest:jest",
          "options": {
            "jestConfig": "libs/MY-LIB/jest.config.js",
            "tsConfig": "libs/MY-LIB/tsconfig.spec.json",
            "passWithNoTests": true
          }
        }
      }
    },`

you should run this by doing a `npm run build <lib/app name>`

**Comment by vasicvuk** [comment]
@albeserra Thanks, but what is the content of libs/MY-LIB/webpack.config.js. I guess there is a definiton of including external lib?

**Comment by albeserra** [comment]
> @albeserra Thanks, but what is the content of libs/MY-LIB/webpack.config.js. I guess there is a definiton of including external lib?

That's the content of webpach.config.js. You should import your mylib.bundle.min.js on html and access to its methods by  using EntryPointForMyLib as entry point. 
I no longer need this configuration but I tried it some some weeks ago and it worked 

```
var path = require('path');

module.exports = {
  mode: "production",
  context: path.resolve(__dirname),
  entry: path.resolve(__dirname,'src/index.ts'),
  output: {
    path: path.resolve(__dirname, '../../dist/libs/MY-LIB'),
    filename: 'mylib.bundle.min.js',
    libraryTarget: 'var',
    library: 'EntryPointForMyLib'
  },
  module: {
    rules: [
      {
        test: /\.ts$/,
        include: path.resolve(__dirname, 'src'),
        exclude: [/node_modules/, /assets/],
        use: [{ loader: 'ts-loader', options: { transpileOnly: true } }],
      },
    ],
  },
  resolve: {
    extensions: ['.tsx', '.ts', '.js'],
    symlinks: false,
  },
};

```

**Comment by vasicvuk** [comment]
@albeserra  Thanks
