### ISSUE TITLE
Modify html files during build time.

### ISSUE THREAD

**Issue by gquinteros93** [ng-packagr/ng-packagr#1601]
## Type of Issue

```
[x ] Feature Request
```

## Description

Hi, I would like to know if it's possible to modify the HTML files during build time in a Custom Angular Library. 

In fact, I would like to execute [lodash.template()](https://lodash.com/docs/4.17.15#template) to replace some string in my HTML during build time of my Custom Angular Library. 

Is it possible to do that?

#### Expected Behaviour

Through lodash, I can set a function to replace a string by the result of executing a function like this:

**Before build**:

```
<div class=`<%= getNewClassName('classNameExample') %>`>
</div>
```

Then I can set the following configuration to run in build time for the HTML files:

```
     let classNames = {
        "classNameExample": "classNameResult"
     };

      // Function to lookup hashed class names
      var getNewClassName = function(nameClass) {
        return classNames[nameClass];
      }

      // Use lodash to template it, passing the class lookup function
      var compiled = _.template(html);
      var templated = compiled({
        getNewClassName: getNewClassName
      });
```

This is an example, but the classNames is a JSON that it would be generated before build so it would be dynamic and because of that, I cannot replace them manually before I build the library and that is why I want to modify the HTML files during the build time of the library. 

#### Version Information

```
ng-packagr: 4.2.0
@angular/*: 7.2.0
typescript: 3.2.2
rxjs: 6.3.2
node: >= 8.0.0
npm/yarn: >= 5
```

**Comment by mlc-mlapis** [comment]
@gquinteros93 You can probably think about some of your custom schematics to do it.

**Comment by gquinteros93** [comment]
Hi @mlc-mlapis , 

Mmm... I do not know if schematics is the solution that I need.

Let me explain my objective better.

I want to implement [CSS Modules](https://github.com/css-modules/css-modules) in my Custom Angular Library as I already did it in an Angular Project: https://github.com/gquinteros93/angular-css-modules

For the Angular Project, I was able to do that extending the project compilation (thanks to [@angular-builders/custom-webpack](https://github.com/just-jeb/angular-builders/tree/8.x.x/packages/custom-webpack)) using [postcss-modules](https://github.com/css-modules/postcss-modules), posthtml-css-modules (https://github.com/posthtml/posthtml-css-modules) and Lodash to handle the ngClass directive like is explained here: https://stackoverflow.com/questions/60512235/use-hashbase645-in-javascript-typescript-file

To extend the build of my Angular Library, I can modify the scss files using [postcss-modules](https://github.com/css-modules/postcss-modules) through [scss-bundle](https://github.com/reactway/scss-bundle) like is done here:

- https://stackoverflow.com/questions/60712566/nodejs-script-that-compiles-scss-files-fails-because-of-postcss-rule-for-undefin
- https://github.com/ng-packagr/ng-packagr/issues/839#issuecomment-386791207

But, I still need to modify the HTML files on build time without replacing the original HTML files, on resume, I only need to modify the HTML files that are going to build/deployed in the library (dist folder).

If (https://github.com/posthtml/posthtml-css-modules) is not an option, I can replace all the class names using [lodash.template()](https://lodash.com/docs/4.17.15#template)

Do you know if I can use [lodash.template()](https://lodash.com/docs/4.17.15#template) during build time?

Thanks in advance.

**Comment by gstvribs** [comment]
I'm facing the same issue, did you find any solution?

**Comment by alan-agius4** [comment]
Closing as this is out of scope.
