### ISSUE TITLE
ERROR: Unknown version 80 of android

### ISSUE THREAD

**Issue by Rofer11607** [ng-packagr/ng-packagr#1611]
[x ] Bug Report
[ ] Feature Request

## Description

_A bug: please describe the error that you encountered_

when running ng-packagr -p <pathToPackage.json> there is an error in the terminal which reads"ERROR: Unknown version 80 of android" 

#### How To Reproduce

run "npm run build:lib"

#### Expected Behaviour

should compile an installable component 

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
{
	"name": "merchlib",
	"version": "0.0.0",
	"scripts": {
		"ng": "ng",
		"start": "ng serve",
		"build": "ng build",
		"test": "ng test",
		"lint": "ng lint",
		"e2e": "ng e2e",
		"build:lib": "ng-packagr -p lib/package.json"
	},
	"private": true,
	"dependencies": {
		"@angular/animations": "~8.2.14",
		"@angular/common": "~8.2.14",
		"@angular/compiler": "~8.2.14",
		"@angular/core": "~8.2.14",
		"@angular/forms": "~8.2.14",
		"@angular/platform-browser": "~8.2.14",
		"@angular/platform-browser-dynamic": "~8.2.14",
		"@angular/router": "~8.2.14",
		"rxjs": "~6.4.0",
		"tslib": "^1.10.0",
		"zone.js": "~0.9.1"
	},
	"devDependencies": {
		"@angular-devkit/build-angular": "~0.801.3",
		"@angular-devkit/build-ng-packagr": "^0.801.3",
		"@angular/cli": "~8.3.24",
		"@angular/compiler-cli": "~8.2.14",
		"@angular/language-service": "~8.2.14",
		"@types/jasmine": "~3.3.8",
		"@types/jasminewd2": "~2.0.3",
		"@types/node": "~8.9.4",
		"codelyzer": "^5.0.0",
		"jasmine-core": "~3.4.0",
		"jasmine-spec-reporter": "~4.2.1",
		"karma": "~4.1.0",
		"karma-chrome-launcher": "~2.2.0",
		"karma-coverage-istanbul-reporter": "~2.0.1",
		"karma-jasmine": "~2.0.1",
		"karma-jasmine-html-reporter": "^1.4.0",
		"ng-packagr": "^9.1.1",
		"protractor": "~5.4.0",
		"ts-node": "~7.0.0",
		"tslint": "~5.15.0",
		"typescript": "~3.5.3"
	}
}


package.json for lib:

{
	"name": "merch",
	"version": "0.0.1",
	"author": "Raphael Castro <rafac@mosnterrg.com>",
	"license": "MIT",
	"ngPackage": {
		"$schema": "./node_modules/ng-packagr/ng-package.schema.json",
		"lib": {
			"entryFile": "public_api.ts"
		},
		"dest": "dist"
	}
}

**Comment by metodribic** [comment]
Probably related to #1411

**Comment by Rofer11607** [comment]
Thats what I thought, however the solutions posted in that thread do not fix the issue,
I do however have another project on my computer that doesn't throw the error, I guess its because I have an older version of angular or ng-packgr installed. here is the package.JSON for the older working one, please help

{
  "name": "testy",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "build:lib": "ng-packagr -p ./lib/package.json"
  },
  "private": false,
  "dependencies": {
    "@angular/animations": "~8.2.14",
    "@angular/cdk": "~8.2.3",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/material": "^8.2.3",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "rxjs": "~6.4.0",
    "testy-mctesterson": "file:lib/src/dist",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.24",
    "@angular/cli": "~8.3.24",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "ng-packagr": "^9.1.1",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  },
  "description": "This project was generated with [Angular CLI](https://github.com/angular/angular-cli) version 8.3.24.",
  "main": "public_api.ts",
  "directories": {
    "lib": "lib"
  },
  "author": "raphael castro",
  "license": "MIT"
}

**Comment by mgameover** [comment]
Hi everyone,
I am facing the same issue, but my angular version is 9.1.3. 

> ERROR: Unknown version 80 of android
> An unhandled exception occurred: Unknown version 80 of android

It looks like ng-packagr **v9.1.2** is causing that.
The workaround is to downgrade it by specifying version explicitly:
>    "ng-packagr": "9.1.1",

That solved the issue for me.
P.S. Don't forget to delete `package-lock.json` and clean up node_modules before downgrading

**Comment by alan-agius4** [comment]
Can you please try to remove your lock file, node_modules and try again?

@mgameover, what's your `@angular-devkit/build-angular` version?

**Comment by alan-agius4** [comment]
Closed via https://github.com/ng-packagr/ng-packagr/pull/1626

**Comment by mgameover** [comment]
Hey @alan-agius4, 
> what's your `@angular-devkit/build-angular` version?
    "@angular-devkit/build-angular": "~0.901.4"

I don't see this issue anymore. Thanks!
