### ISSUE TITLE
How to require assets in a library

### ISSUE THREAD

**Issue by mistic100** [ng-packagr/ng-packagr#1634]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

Many components of my library uses SVGs (icons, various illustrations, etc).

Until version 9 I simply required them in the component :
```
const imagePath = require('./assets/images/404.svg');
// used with [src] or a component that takes an url input
```
This worked by copying my assets folder inside dist/fesm5 before publishing. There where no error or warning while building the library and the application builded fine as well.

Now with Angular 9 and the latest version of ng-packr this no longer works. This error happens when building the library :
> ERROR: Could not resolve './assets/images/404.svg' from dist/esm2015/components/core/not-found/not-found.component.js

I understand that there is a [new official option for handling assets](https://github.com/ng-packagr/ng-packagr/blob/master/docs/copy-assets.md) but this seems to only cover assets exposed by a library and used by an application.

What about assets used by the library itself ?

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 9.1.1
@angular/*: 9.1.2
typescript: 3.8.3
rxjs: 6.5.5
node: 10.16.2
yarn: 1.22.0
```

**Comment by alan-agius4** [comment]
You should inline your assets in components css file and from the template use a class.

https://github.com/ng-packagr/ng-packagr/blob/master/docs/embed-assets-css.md

`requiring` an image is a webpack specific feature, and is not supported by the Angular CLI see https://github.com/angular/angular-cli/issues/17400#issuecomment-609744000

**Comment by mistic100** [comment]
Ok but what about situations where using CSS is not a solution ?

Imagine a component taking the **url** of an image as input. I need to have a way to make this url variable and not bloat my CSS with it.

The "require" _trick_ worked perfectly in Angular 8.

Taking the risk to sound like an ass, I saw **a lot** of requests to support external assets properly in Angular libraries, I don't understand how this not a priority. Using assets is not anectodical at all.

**Comment by mistic100** [comment]
Additionally to the case explained above I also have a library using SVG icons, these SVG **cannot** be inlined in the CSS because there have to be inserted in the DOM to be able to change their color.

**Comment by mistic100** [comment]
Current workarround is to `require('!file-loader!....)` when I need the assets to be loaded from external file (for usage in dynamic img) and `require('!raw-loader!....)` when I need the assets to be inlined elsewhere than in the CSS (for usage directly in the DOM).

I managed to build the libs, tomorrow I'll see if the apps can be builded.

**Comment by alan-agius4** [comment]
I doubt that the `require` approach works for all module formats, also this relies on the fact that downstream users all use Webpack and the library now needs to be aware of the application build system.

I think a better approach from an architectural point of view would be to;
1) Copy the assets in the dist folder
2) Create an assets service.

```ts
export const ICONS_BASE_URL = new InjectionToken<string>('SVG_ICONS_BASE_URL');

@Injectable({
  providedIn: 'root',
})
export class AssetService {
  constructor (
    @Inject(IconsBaseUrl) baseUrl: string,
  ) {
  }

  getUrl(img: string): string {
      return `${this.baseUrl || ''}${img}`;
  }
}
```
3) Use the service to retrieve the image path
```ts

@Component({
  selector: 'lib-root',
  template: `<img [src]=src>`,
})
export class LibComponent {
  src = this.assetService('foo.svg');

  constructor(private assetService: AssetService) {}
}
```

3. The consumers of your library will need to copy the assets themselves, such as the `assets` option of the Angular CLI.
4. Users will also be able to configure were to locate the images via the `ICONS_BASE_URL` toekn.

**Comment by mistic100** [comment]
That's awfully complicated IMHO. And the same thing can be done without any service : https://github.com/atularen/ngx-monaco-editor

And it works for external assets only, not when the raw content is needed.

----

The problem I have is there is not a single working and simple solution, which I expect from a tool specifically designed to build librairies.

I agree my "require" approach is not generalizable, but as the maintainer of a 100+ components library used by 30 enterprise applications I have to find a simple solution (the library and tooling must absorb most of the maintenance cost and require minimum configuration in each app).

Currently it's just a bunch of hacks.

**Comment by mistic100** [comment]
As I understand it the current situation is unsolvable because the format is just not designed for that. And it cannot be an option for the same reason the team always refused an option to disable UMD generation (totally useless in closed enterprise environnements).

**Comment by mistic100** [comment]
Well my require trick above does not work. The "require" is transformed into an import statement so when the app is building there is no "require" to resolve throught Webpack.

I guess I'am stuck to Angular 8...

**Comment by mistic100** [comment]
I made a custom preprocessor to transform my SVG into TS modules in order to be able to import them.

Other assets are handled in a similar way to ngx-monaco-editor.

**Comment by sbatezat** [comment]
> You should inline your assets in components css file and from the template use a class.
> 
> https://github.com/ng-packagr/ng-packagr/blob/master/docs/embed-assets-css.md
> 
> `requiring` an image is a webpack specific feature, and is not supported by the Angular CLI see [angular/angular-cli#17400 (comment)](https://github.com/angular/angular-cli/issues/17400#issuecomment-609744000)

I don't even understand why this has been setup on ng-packagr. It's a very bad idea to transform images to base64 from a performance point of view. Base64 is bigger than original picture, We should be able to use original files, without any config from the library's consumer.

**Comment by sbatezat** [comment]
> Well my require trick above does not work. The "require" is transformed into an import statement so when the app is building there is no "require" to resolve throught Webpack.
> 
> I guess I'am stuck to Angular 8...

Could you please elaborate more on the issue you've met wiith this trick? 
I've done some tests, and, indeed, require statement is transforme into an import one. However, when I launch my app using my lib, images are showing up without any problem.

Also, could you please add some details about the "similar way to ngx-monaco-editor."
Thanks!

**Comment by mistic100** [comment]
> > Well my require trick above does not work. The "require" is transformed into an import statement so when the app is building there is no "require" to resolve throught Webpack.
> > I guess I'am stuck to Angular 8...
> 
> @mistic100 Could you please elaborate more on the issue you've met wiith this trick?
> I've done some tests, and, indeed, require statement is transformed into an import one. However, when I launch my app using my lib, images are showing up without any problem.
> 
> Also, could you please add some details about the "similar way to ngx-monaco-editor."
> Thanks!

I don't remember but it didn't worked.

---

https://github.com/atularen/ngx-monaco-editor#installation
