### ISSUE TITLE
ng-packagr library not working properly from inside of Angular 5 project

### ISSUE THREAD

**Issue by sdharagit** [ng-packagr/ng-packagr#1661]
## What I'm doing is
I'm not publishing my lib in npm because it is not open source. So hosted the source code of ng-packagr library in github and pulling from there in package json of Angular 5 app and running a post-install script inside library.
## Error
ng-packagr library is working and building fine independently but when consuming from Angular 5 project, maybe the ngc and tsc not working properly and generating error like below.  Basically its unable to produce licensing folder inside esm2015 folder and the error is happening.
```
[ ] Bug Report
Building Angular Package
Building entry point '@lib/common-services'
Rendering Stylesheets
Rendering Templates
Compiling TypeScript sources through ngc
Bundling to FESM2015

BUILD ERROR
Could not resolve './licensing/licensing.service' from dist\esm2015\public_api.js
Error: Could not resolve './licensing/licensing.service' from dist\esm2015\public_api.js
    at error (D:\MyWorks\work\csp.root.ui\packages\ufe-nav-menu\node_modules\@lib\common-services\node_modules\rollup\dist\rollup.js:199:15)
    at D:\MyWorks\work\csp.root.ui\packages\ufe-nav-menu\node_modules\@lib\common-services\node_modules\rollup\dist\rollup.js:20784:25
    at async Promise.all (index 0)
    at async Promise.all (index 0)
```

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: "^3.0.6"
@angular/*: 5.2.11
typescript: 2.8.1
"@types/node": "^6.0.89",
"ts-node": "4.1.0",
```

## A quick help is very much appreciated :)

**Comment by alan-agius4** [comment]
Hi `ng-packagr` version 3 is no longer supported. Kindly update to `ng-packagr` version 9. 

If the problem persists, please file a new issue and provide a minimal reproduction.

Thanks.
