### ISSUE TITLE
A way to change .browserlistrc location

### ISSUE THREAD

**Issue by gstvribs** [ng-packagr/ng-packagr#1665]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

A way to change .browserlistrc location

#### Expected Behaviour

Hi guys, there is a way to change .browserlist file path? I use a Lerna monorepo structure and I want to use a single file that is used across many libraries at my project

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 9.1.5
@angular/*: 8.2.14
typescript: 3.5.3
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by alan-agius4** [comment]
Hi, if the browserslist configuration is either in the current directory or in a parent directory browserslist is able to resolve it.

See: https://github.com/browserslist/browserslist

**Comment by gstvribs** [comment]
Nice! Thank a lot @alan-agius4!
