### ISSUE TITLE
Angular 9 build error `Custom named exports`

### ISSUE THREAD

**Issue by hendryfudiko** [ng-packagr/ng-packagr#1671]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

```
ERROR: Custom named exports were specified for angular9-lib-commonjs/dist/my-commonjs-lib/fesm5/my-commonjs-lib.js but it does not appear to be a CommonJS module
An unhandled exception occurred: Custom named exports were specified for angular9-lib-commonjs/dist/my-commonjs-lib/fesm5/my-commonjs-lib.js but it does not appear to be a CommonJS module
```

## Description
This issue happened when we add 
[{ "module": "CommonJS", "importHelpers": false } in tsconfig.lib.json](https://github.com/hendryfudiko/angular9-lib-commonjs/blob/master/projects/my-commonjs-lib/tsconfig.lib.json#L6-L7).
That error occur when use `@rollup/plugin-commonjs: ^11.0.2` but with latest `@rollup/plugin-commonjs: ^13.0.0` this error not happened.

#### How To Reproduce
[Repo Link to reproduce](https://github.com/hendryfudiko/angular9-lib-commonjs)
- run `ng build my-commonjs-lib --prod`

#### Expected Behaviour
On _ng-packagr version 8_, this error not happened.
Can you upgrade `@rollup/plugin-commonjs` to version `^13.0.0` for _ng-packagr_ v9 branch?

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 9.1.5
@angular/compiler: 9.1.11
rollup: 2.7.5
typescript: 3.8.3
node: 10.17.0
yarn: 1.22.4
```

**Comment by alan-agius4** [comment]
Hi @hendryfudiko, That is because CommonJs module is not part of the Angular Package Format. https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview
