### ISSUE TITLE
Ability to reuse umdModuleId definitions in secondary entry points

### ISSUE THREAD

**Issue by karan-kang** [ng-packagr/ng-packagr#1674]
## Type of Issue

```
[ ] Bug Report
[X] Feature Request
```

## Description

We are building a large library that has several secondary  & tertiary entry points. At present, we have to repeat umdModuleIds in each secondary/tertiary point, which defeats the principle of DRY and is error prone.

It would be helpful if ng-packagr can pick the base list of umdModuleIds from primary endpoint (or ancestor chain).

#### Version Information

```
ng-packagr:            4.7.1
@angular/compiler:     7.2.15
rollup:                0.67.4
tsickle:               0.34.3
typescript:            3.2.4
```

**Comment by astectus** [comment]
As I understood you  try to have a `shared` entry point so you could  use it in multiple entry points ?

**Comment by SchnWalter** [comment]
I will look into this over the weekend.

We're building multiple (private) libraries with different names from the same code-base, and it's a pain to have them maintained. I'll make sure that the entry point details will have a public version of this information and I will have secondary entry points look into the primary entry point.

**Comment by SchnWalter** [comment]
Besides `lib.umdModuleIds`, what else should the entry points inherit from their parent?

1) `keepLifecycleScripts`?
2) `whitelistedNonPeerDependencies`?
2) properly resolved `lib.styleIncludePaths`?
3) `lib.cssUrl`?

P.S. With https://github.com/ng-packagr/ng-packagr/pull/1737, all this data will be available when it's needed, it will be trivial to make these changes.

**Comment by flash-me** [comment]
@SchnWalter Will this happen by default? If yes, isn't this a possible breaking change? Will we get the option the not inherit from the parent?

cheers
flash ⚡

**Comment by SchnWalter** [comment]
I don't see why this would be a breaking change, you can't really have 2 different globals with different code. But, will soon become irrelevant, UMD builds will be removed in the next release of the AFP (most probably sometime after the new linker will be merged - if it hasn't been merged already)

**Comment by flash-me** [comment]
Possible case would be e.g. if you provide secondary entry points exactly because of that. The primary entry point uses lets say public umdModuleIds and you have a secondary entry point for special environments with different umds.
In that case, it would be nice, if the secondary umdModuleIds are not overwritten with those of the parents.

UMD becoming deprecated is aprreciated. So why changing here sth anyway? :P
