### ISSUE TITLE
Peer dependency warning when installing v10

### ISSUE THREAD

**Issue by crfrolik** [ng-packagr/ng-packagr#1679]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

_A bug: please describe the error that you encountered_

_A feature: please describe your use case and motivation_

```
warning "ng-packagr > injection-js@2.3.0" has incorrect peer dependency "tslib@^1.9.3".
```

#### Expected Behaviour

No peer dependency warnings should occur when installing the latest version.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            10.0.0
@angular/compiler:     10.0.0
rollup:                2.18.0
tsickle:
typescript:            3.9.5
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by alan-agius4** [comment]
This seems to be a problem of injection-is, where tslib is being specified as a peerDependency and not a direct dependency.

We cannot meet this peer requirement because we are using TS 3.9 to build this package which requires tslib 2+.

**Comment by alan-agius4** [comment]
Fixed via https://github.com/mgechev/injection-js/pull/46
