### ISSUE TITLE
Provide a possibility to build secondary entry point only

### ISSUE THREAD

**Issue by klemenoslaj** [ng-packagr/ng-packagr#1680]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

This might be a very exotic request, but I bring it forth anyway in the hope that it might be useful for others as well.
Normally building secondary entries alone wouldn't make any sense, however, for monorepo environments, this might prove very useful in the CI.

Example structure:

```
@npmScope/library-a
@npmScope/library-a/entry-1
@npmScope/library-a/entry-2
@npmScope/library-a/entry-3

@npmScope/library-b
@npmScope/library-b/entry-1
@npmScope/library-b/entry-2
```

Now if `@npmScope/library-b/entry-2` would depend on `@npmScope/library-a/entry-1`, we could theoretically only build these two entries, without building the whole library.

Currently:

```
Built @npmScope/library-a
Built @npmScope/library-a/entry-1
Built @npmScope/library-a/entry-2
Built @npmScope/library-a/entry-3


Built @npmScope/library-b
Built @npmScope/library-b/entry-1
Built @npmScope/library-b/entry-2
```

After:

```
Built @npmScope/library-a/entry-1

Built @npmScope/library-b/entry-2
```

#### How To Reproduce

N/A

#### Expected Behaviour

N/A

#### Version Information

N/A

**Comment by alan-agius4** [comment]
Hi @klemenoslaj,

This request is very similar to https://github.com/ng-packagr/ng-packagr/issues/925. So let’s continue tracking this over there.

If I miss understood the issue please let me know.
