### ISSUE TITLE
internal third party code inside bundle without external

### ISSUE THREAD

**Issue by stepet80** [ng-packagr/ng-packagr#1690]
We are using Angular CLI with libraries which uses ng-packagr.
We have some external dependencies (rxjs, angular) and we want to have some internal dependencies (localForage, util).
The internal dependencies should be bundled into the final bundle (so it shouldn't use global.util or global.localforage).
The external dependencies are defined by using the umdModuleIds array (externals) in the ng-package.json file.

But it seems that the internal dependencies are not bundled in the final bundle eventhough it is not mentioned in the umdModuleIds array.

Is this a bug or do we need to define something extra?

**Comment by alan-agius4** [comment]
You can use the npm's `bundledDepedencies`. Though support for this feature is deprecated and likely to be removed in the next major version

See: https://github.com/ng-packagr/ng-packagr/issues/1432
