### ISSUE TITLE
Missing support for lazy-loading

### ISSUE THREAD

**Issue by adrianbarwicki** [ng-packagr/ng-packagr#1708]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description

`ng-packagr` does not build modules with lazy loading (with the `loadChildren`-syntax), resulting in the following error:
```
ERROR: /Users/user/ng-packagr/integration/samples/lazy-loading/src/lib/lazy.module.ts:14:1: Error encountered in metadata generated for exported symbol 'LazyModule': 
 /Users/user/ng-packagr/integration/samples/lazy-loading/src/lib/lazy.module.ts:7:23: Metadata collected contains an error that will be reported at runtime: Lambda not supported.
  {"__symbolic":"error","message":"Lambda not supported","line":6,"character":22}
```

#### How To Reproduce
Please see the integration sample here:
https://github.com/ng-packagr/ng-packagr/pull/1707

_Can you reproduce the error in the integration tests in ng-packagr?_
Yes, see the above PR.

#### Expected Behaviour
I expect the build to be successful, correctly implementing the lazy loading.

#### Version Information
See package.json in the PR https://github.com/ng-packagr/ng-packagr/pull/1707

**Comment by alan-agius4** [comment]
This is the expected behaviour.

See https://github.com/angular/angular-cli/issues/6373#issuecomment-533204545 for more context.
