### ISSUE TITLE
Cannot resolve type entity ɵngcc29.PsButtonModule to symbol

### ISSUE THREAD

**Issue by darkoandreev** [ng-packagr/ng-packagr#1713]
Hello guys,

I have a UI components library and I added secondary entrypoints to every component and in my demo project everything seems to be fine after production build. The problem is, when I try to install it in a separate project and I've got the following error for prod build:
`Cannot resolve type entity ɵngcc29.PsButtonModule to symbol`

The project and the library both are built using Angular 10.

Do you know why I get this error only for the button module and do you know what is causing it?

Thanks in advance!

**Comment by JoostK** [comment]
This sounds like it could be similar to angular/angular#38238. There's some more details in that ticket.

**Comment by EOussama** [comment]
Anything on this yet?

**Comment by JoostK** [comment]
Can you try setting `compilerOptions.preserveSymlinks: true` in tsconfig?

```json
{
  "compilerOptions": {
    // ...
    "preserveSymlinks": true,
    // ...
  }
}
```

**Comment by EOussama** [comment]
> Can you try setting `compilerOptions.preserveSymlinks: true` in tsconfig?
> 
> ```json
> {
>   "compilerOptions": {
>     // ...
>     "preserveSymlinks": true,
>     // ...
>   }
> }
> ```

That fixed my error but I was met with yet another runtime exception: 
```
ERROR Error: Uncaught (in promise): Error: inject() must be called from an injection context
Error: inject() must be called from an injection context
```

**Comment by JoostK** [comment]
@EOussama that indicates to me that you probably have multiple versions of `@angular/core` bundled.

**Comment by EOussama** [comment]
I followed that article step by step however, when I try to call a component I get some  path conflict errors

**Comment by alexandis** [comment]
> ```json
> "preserveSymlinks": true,
> ```

Didnt' help :(

**Comment by alan-agius4** [comment]
This is unlikely caused by ng-packagr. If the problem persists please file a new issue with a minimal reproduction.

**Comment by unanimity** [comment]
in my case 

```
/** @internal */   ---  DELETE 
@Component({
```
....
