### ISSUE TITLE
Please provide a more detailed Information Sheet/Readme about styleIncludePaths.

### ISSUE THREAD

**Issue by CreativeHouseDotOrg** [ng-packagr/ng-packagr#1728]
## Type of Issue

```
[ ] Bug Report
[ X ] Feature Request
```

## Description

I have opened a[ Thread on Stackoverflow](https://stackoverflow.com/questions/63448977/how-do-i-declare-include-an-imported-scss-folder-in-my-library-so-i-can-call-im) regarding this Issue.

Thank you

**Comment by alan-agius4** [comment]
Doesn't this suffice https://github.com/ng-packagr/ng-packagr/blob/master/docs/style-include-paths.md? It should point you to the right direction.

**Comment by CreativeHouseDotOrg** [comment]
Thank you
