### ISSUE TITLE
No ES5 format scripts in latest ng-packagr?

### ISSUE THREAD

**Issue by kumaresan-subramani** [ng-packagr/ng-packagr#1732]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I am upgrading my `ng-packagr` version from `1.5.x` to latest. t generate package like below structure which dont have `es5` scripts fles.

Generated package structure:

In below both are `es2015` no `es5` script files.

![image](https://user-images.githubusercontent.com/36756050/91014086-6b24fd80-e606-11ea-9200-9239ca498fe7.png)

#### How To Reproduce

1. download below sample
[packageGen.zip](https://github.com/ng-packagr/ng-packagr/files/5116275/packageGen.zip)

2. Give `npm i`

3. Then `npm run packagr`

**Note: Before that please delete `dist` folder which is already generated package. i have attached for reference**

#### Expected Behavior

Expected below mentioned scripts files too:

![image](https://user-images.githubusercontent.com/36756050/91014645-644aba80-e607-11ea-9f54-03f4691d55f3.png)

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 10.0.4
@angular/*: 9.1.2
typescript: 3.6.4
rxjs: 5.0.0 - 5.5.10
node: 10.15.1
npm/yarn: 6.4.1
```

**Comment by kumaresan-subramani** [comment]
My Generated package dot have below mentioned scripts

![image](https://user-images.githubusercontent.com/36756050/91015243-7711bf00-e608-11ea-8bc1-d460b1626198.png)

**Comment by kumaresan-subramani** [comment]
When i try to use generated package in my application it throws below error:
![image](https://user-images.githubusercontent.com/36756050/91016620-a88b8a00-e60a-11ea-8d98-a7242bc92641.png)

## Repo steps

1. download below sample
[sample.zip](https://github.com/ng-packagr/ng-packagr/files/5116382/sample.zip)

2. Give `npm i`

3. replace `@syncfusion/ej2-agular-buttons` package with above generated package

4.then `ng serve`

Issue will throws in terminal

**Comment by alan-agius4** [comment]
ESM5 and FESM5 format were deprecated and have been removed from APF version 10.
See: https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes|

From the `ng-packagr --version`, it looks you are using ng-packagr version 10 with Angular version 9 and TypeScript 3.6, this is not supported. ng-packagr version 10, is only compatible with TypeScript 3.9+ and Angular ^10.
