### ISSUE TITLE
[Question] Possible to keep publishConfig and repository in package.json?

### ISSUE THREAD

**Issue by maloneygassertiv** [ng-packagr/ng-packagr#1740]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

We are following the instructions at [this link](https://docs.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-npm-for-use-with-github-packages#publishing-a-package-using-publishconfig-in-the-packagejson-file) to publish our Angular package to Github Packages.  This involves setting values for `publishConfig` and `repository` in package.json.  Is there a way to keep these values from being erased?

**Comment by SchnWalter** [comment]
I just tested this and the `publishConfig` was removed from the build. You are probably adding that configuration to the `package.json` from the project root and not to the `package.json` that is located in the library source code root (where `ng-package.json` is also located)

**Comment by maloneygassertiv** [comment]
I'm adding that configuration to `package.json` in the library source code root (where `ng-package.json` is also located).  As you say, it is removed from the build.  Our current workaround is to add it back manually after building, but it would be nice to configure it not to be removed in the first place.

**Comment by SchnWalter** [comment]
Can you please provide the output of `npx ng-packagr --version`?

**Comment by maloneygassertiv** [comment]
That command gives an error:
```
$ npx ng-packagr --version
npx: installed 285 in 11.447s
Cannot find module '@angular/compiler-cli'
```
When I use `npm`, I get this:

```
$ npm ng-packagr --version
6.9.0
```

**Comment by SchnWalter** [comment]
You need to execute the command in the root of your project. otherwise npx will use a brand new installation of the package, which won't have the required peerDependencies.

And the 2nd one is equivalent to `npm --version`.

**Comment by maloneygassertiv** [comment]
```
$ npx ng-packagr --version
ng-packagr:            5.7.1
@angular/compiler:     8.2.14
rollup:                1.25.2
tsickle:               0.35.0
typescript:            3.5.3
```

**Comment by SchnWalter** [comment]
In theory, it should work:
* https://github.com/ng-packagr/ng-packagr/blob/v5.7.1/src/lib/ng-v5/discover-packages.ts#L43
* https://github.com/ng-packagr/ng-packagr/blob/v5.7.1/src/lib/ng-v5/entry-point/write-package.transform.ts#L92

But I wasn't able to reproduce the issue. If you provide a reproduction repository, I can take a look into it. Otherwise, I suggest that you update to a more recent version and use a freshly generated library as a template to apply the various changes that exist.

**Comment by maloneygassertiv** [comment]
Thank you @SchnWalter I'm happy with this answer.
