### ISSUE TITLE
Error "Cannot read property 'type' of null" when importing another NgModule with directive export

### ISSUE THREAD

**Issue by mvnrhd** [ng-packagr/ng-packagr#1741]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

ng-packagr throws the following error when importing an NgModule which exports a directive. 

**ERROR: Cannot read property 'type' of null**

#### How To Reproduce

Note that I'm using yarn for linking workspaces and both modules (ModuleA & ModuleB) are located inside separate packages inside the same yarn package root. Both are built via ng-packagr. Module A package has been built, Module B package build fails.

Module A:

```
@NgModule({
    imports: [
        // some imports
    ],
    declarations: [
        SampleDirective
    ],
    exports: [
        SampleDirective       // if commented out, it works
    ]
})
export class ModuleA {

    public static forRoot(): ModuleWithProviders<ModuleA> {
        return {
            ngModule: ModuleA,
            providers: [
                // some providers
            ]
        };
    }
}
```

Module B:

```
@NgModule({
    imports: [
        ModuleA
    ]
})
export class ModuleB {

    public static forRoot(): ModuleWithProviders<ModuleB> {
        return {
            ngModule: ModuleB,
            providers: [
                // some providers
            ]
        };
    }
}
```

#### Expected Behaviour

build doesn't fail and SampleDirective can be used inside ModuleB.

#### Notes

I've seen this similar issue https://github.com/angular/angular/issues/24143 but unfortunately it was closed. I wasn't sure if it's a bug inside angular or ng-packagr. IMO it seems to be related to symlinks. If I copy packageA/dist to package/b/node_modules/packageA manually, build **doesn't fail**.

#### Version Information

```
ng-packagr: 10.1.0
@angular/*: 10.0.9
typescript: 3.9.7
node: 12.14.1
yarn: 1.22.5
```

**Comment by matheo** [comment]
This is related to #1087 and indeed is about symlinks.
I'm using `lerna` and I had to add a `path` in the tsconfig to override the symlinks at node_modules and map directly the `dist` folders, so it worked
```
    "paths": {
      "@scope/*": ["packages/*/dist"]
    }
```
