### ISSUE TITLE
`Maximum call stack size exceeded` when using two or more nested generic interface in a class constructor

### ISSUE THREAD

**Issue by tharvik** [ng-packagr/ng-packagr#1742]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

When building an angular library with `--prod`, I encouter `ERROR: Maximum call stack size exceeded` when using two or more nested generic interface in a class constructor.

#### How To Reproduce

```sh
#!/bin/sh -eu

npx -p @angular/cli ng new my-workspace --create-application=false
cd my-workspace
npx ng generate library my-lib

cat > projects/my-lib/src/public-api.ts <<EOF
interface Type<T> {}

export class A {
  constructor(
    t: Type<Type<string>>
  ) {}
}
EOF

npx ng build --prod
```

#### Expected Behaviour

Not to crash.

#### Version Information

```
ng-packagr: 10.1.0
@angular/compiler: 10.1.0
rollup: 2.26.5
typescript: 4.0.2
rxjs: 6.6.3
node: 14.4.0
npm: 14.4.0
```

**Comment by alan-agius4** [comment]
Similar issue https://github.com/ng-packagr/ng-packagr/issues/1785

**Comment by alan-agius4** [comment]
Closinmg as this is not caused by ng-packagr.
