### ISSUE TITLE
Secondary Entry Points Multiple Subdirectories

### ISSUE THREAD

**Issue by daithyy** [ng-packagr/ng-packagr#1748]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

Hello everyone, I want to add secondary entry points to our library but am running into path related issues searching for `public_api.ts`. I want to clarify if using secondary entry points is applicable with this folder layout.

The library folder layout looks like this:

```
my_library
└── projects
    └── my-package
        ├── src
        |   ├── lib
        |   |   ├── modules
        |   |   |   ├── my-module-one
        |   |   |   |   ├── component
        |   |   |   |   |   └── ...
        |   |   |   |   ├── component
        |   |   |   |   |   └── ...
        |   |   |   |   ├── index.ts <--
        |   |   |   |   ├── package.json <-- want to add these
        |   |   |   |   ├── public-api.ts <--
        |   |   |   |   └── my-module-one.module.ts
        |   |   |   └── my-module-two
        |   |   |       ├── component
        |   |   |       |   └── ...
        |   |   |       ├── component
        |   |   |       |   └── ...
        |   |   |       ├── index.ts <--
        |   |   |       ├── package.json <-- to each module that contains components
        |   |   |       ├── public-api.ts <--
        |   |   |       └── my-module-two.module.ts
        |   |   ├── index.ts
        |   |   ├── package.json
        |   |   ├── public-api.ts
        |   |   ├── library.module.ts
        |   |   └── library.service.ts
        |   └── public-api.ts (exports everything)
        ├── ng-package.json (targets public-api above)
        └── tsconfig.lib.json

```

#### How To Reproduce

When building the first entry point will build with no issues (`@name/my-package`).
Then the next entry point is `@name/my-package/src/lib/modules/my-module-one` on which it fails with `Cannot find module './public_api.ts'`

#### Version Information

```
ng-packagr: 9.0.0
@angular/*: 9.1.9
typescript: ~3.8.3
rxjs: ~6.5.4
npm: 6.11.3
```

**Comment by SchnWalter** [comment]
You can find an example with multiple sub-packages in the Angular Package Format [integration sample](https://github.com/ng-packagr/ng-packagr/tree/v10.1.0/integration/samples/apf) ; there you have a package with 3 sub-packages:
```
@sample/apf
@sample/apf/secondary
@sample/apf/secondary/testing
@sample/apf/testing
```

You can build the integration samples by running `yarn build` and `yarn integration:samples`
```
$ grep -ri '"name": "' integration/samples/apf/dist
integration/samples/apf/dist/package.json:  "name": "@sample/apf",
integration/samples/apf/dist/secondary/package.json:  "name": "@sample/apf/secondary"
integration/samples/apf/dist/secondary/testing/package.json:  "name": "@sample/apf/secondary/testing"
integration/samples/apf/dist/testing/package.json:  "name": "@sample/apf/testing"
```

**Comment by daithyy** [comment]
Hello @SchnWalter , thanks for your response and for the integration sample, very helpful. I see there are 3 sub-packages for that package.

Let's say my `secondary` folder doesn't contain a package but holds a list of sub-packages, would the following work?
```
@sample/apf/secondary/testing
@sample/apf/secondary/toggle
@sample/apf/secondary/dropdown
@sample/apf/secondary/badge
```

In my case above in the question, these sub-packages are buried further down the directory, would this still work?
```
@sample/apf/.../.../secondary/testing
```

Can you skip folders or does it require a public_api.ts and package.json the whole way down the directory until the sub-package is reached?

**Comment by SchnWalter** [comment]
You can have empty directories without a problem, but this is not a document feature and it's tested to prevent regressions.

 But you can always provide a minimal sub-package (or even a root package) that just exports something:

* **ng-package.json**
    ```json
    {
      "$schema": "../../../node_modules/ng-packagr/ng-package.schema.json",
      "lib": {
        "entryFile": "public-api.ts"
      }
    }
    ```

* **public-api.ts**
    ```ts
    /**
     * @file This file is required for building this "empty" package.
     */
    export const EMPTY_PACKAGE: boolean = true;  // or you could export the package version.
    ```


Sub-packages are relative to the primary package; so, one can have an empty directory as parent for sub-packages and a structure like this example here will work just fine, but AFAIK it's NOT a documented feature:

```
/projects/@example/package/src/
├── core
│   ├── components
│   │   ├── badge
│   │   │   ├── ng-package.json
│   │   │   └── public-api.ts
│   │   ├── toggle
│   │   │   ├── testing
│   │   │   │   ├── ng-package.json
│   │   │   │   └── public-api.ts
│   │   │   ├── ng-package.json
│   │   │   └── public-api.ts
│   │   └── testing
│   │       └── integration
│   │           ├── ng-package.json
│   │           └── public-api.ts
│   ├── ng-package.json
│   └── public-api.ts
├── ng-package.json
├── package.json
└── public-api.ts
```

If the library maintainers would like to make this a documented feature, I can quickly extend the tests to watch for these sub-packages that contain "empty directories" in their name.

**Comment by SvenBudak** [comment]
@SchnWalter Thank you for this solution! This worked well but...
i have in this way a problem, with using Component A inside of Component B.

```
------------------------------------------------------------------------------
Building entry point '@devmonkeys/mark6/messenger'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
ERROR: projects/mark6-lib/image/src/index.ts:6:15 - error TS6059: File 'F:/Projects/mark6/projects/mark6-lib/image/src/public_api.ts' is not under 'rootDir' 'F:\Projects\mark6\projects\mark6-lib\messenger\src'. 'rootDir' is expected to contain all
 source files.

6 export * from './public_api';
                ~~~~~~~~~~~~~~
projects/mark6-lib/messenger/src/devmonkeys-mark6-messenger.ts:7:38 - error TS6059: File 'F:/Projects/mark6/projects/mark6-lib/image/src/index.ts' is not under 'rootDir' 'F:\Projects\mark6\projects\mark6-lib\messenger\src'. 'rootDir' is expected t
o contain all source files.

7 export {Mark6ImageModule as ɵa} from '../../image/src';
                                       ~~~~~~~~~~~~~~~~~

An unhandled exception occurred: projects/mark6-lib/image/src/index.ts:6:15 - error TS6059: File 'F:/Projects/mark6/projects/mark6-lib/image/src/public_api.ts' is not under 'rootDir' 'F:\Projects\mark6\projects\mark6-lib\messenger\src'. 'rootDir'
is expected to contain all source files.

6 export * from './public_api';
                ~~~~~~~~~~~~~~
projects/mark6-lib/messenger/src/devmonkeys-mark6-messenger.ts:7:38 - error TS6059: File 'F:/Projects/mark6/projects/mark6-lib/image/src/index.ts' is not under 'rootDir' 'F:\Projects\mark6\projects\mark6-lib\messenger\src'. 'rootDir' is expected t
o contain all source files.

7 export {Mark6ImageModule as ɵa} from '../../image/src';
                                       ~~~~~~~~~~~~~~~~~
```

This is how i import `Component A` (In my case it is `mark6.image`:
https://github.com/DevMonkeysDE/mark6/blob/master/projects/mark6-lib/messenger/src/messenger.module.ts#L5

Or is the problem maybe in any `public-api.ts` ?

**Comment by SchnWalter** [comment]
You can't use relative imports between sub-packages. You need to use the sub-package name, see:

https://github.com/ng-packagr/ng-packagr/blob/dad958107087d3afeb4a2f70d65cbd1dc08c8c63/integration/samples/secondary/feature-d/feature-d.ts#L1-L5

Also, for IDEs to not complain about missing imports, you'll need to define those subpackages as path aliases in the root `tsconfig.json`. This happens because IDEs ignore the `tsconfig.lib.json` file. You should define a `tsconf.json` and import it in your lib json, just like in a freshly generated repository + library.

**Comment by SvenBudak** [comment]
@SchnWalter Thanks for the quick answer! But I think I don't really understand.

So I have to create a tsconf.json in root? In root of the repository or in root of the lib?
Because I already have one in the repo root: https://github.com/DevMonkeysDE/mark6/blob/master/tsconfig.json

Or i have to add a `tsconfig.json` in `/projects/mark6-lib` ?

and have you a example `tsconfig.json` where i can see exactly how to add the paths? because you posted a `feature-d.ts` i am not sure how to add js code to a json file.

**Comment by SchnWalter** [comment]
@daithyy, did the suggestions here work for you? Could you please close the story if you are satisfied with the suggestions.

**Comment by daithyy** [comment]
Hello @SchnWalter , the suggestions here worked for us. We ultimately decided however to restructure the library in the future to make things cleaner. It's been moved outside the scope of our project currently. Thanks very much for the help here guys! 👍
