### ISSUE TITLE
Warning about auto detected solution-style tsConfig emitted during build process.

### ISSUE THREAD

**Issue by sir-ion** [ng-packagr/ng-packagr#1754]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description

I've got an angular workspace with a `projects` folder.
One of the projects it contains is an Angular library whose `build` target is configured as follows
```
{
  "projects": {
    "MY_PROJECT": {
      "projectType": "library",
      "root": "projects/MY_PROJECT",
      "sourceRoot": "projects/MY_PROJECT/src",
      "prefix": "lib",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-ng-packagr:build",
          "options": {
            "tsConfig": "projects/MY_PROJECT/tsconfig.lib.json",
            "project": "projects/MY_PROJECT/ng-package.json"
          },
          "configurations": {
            "production": {
              "tsConfig": "projects/MY_PROJECT/tsconfig.lib.prod.json"
            }
          }
        }
      }
    },
  ... other projects ...
  }
}
```
When I try to compile it with `ng build --project MY_PROJECT` the build succeeds but I get this warning many times:

```
Warning: The inferred tsconfig file "/<PATH_TO_MY_WORKSPACE>/tsconfig.json" appears to be "solution-style" since it contains no root files but does contain project references.
This is probably not wanted, since ngcc is unable to infer settings like "paths" mappings from such a file.
Perhaps you should have explicitly specified one of the referenced projects using the --tsconfig option. For example:

  ngcc ... --tsconfig "./projects/MY_PROJECT/tsconfig.lib.json"
  ngcc ... --tsconfig "./projects/MY_PROJECT/tsconfig.spec.json"
  ngcc ... --tsconfig "./projects/ANOTHER_PROJECT/tsconfig.app.json"
  ngcc ... --tsconfig "./projects/ANOTHER_PROJECT/tsconfig.spec.json"
  ngcc ... --tsconfig "./projects/ANOTHER_PROJECT/e2e/tsconfig.json"

Find out more about solution-style tsconfig at https://devblogs.microsoft.com/typescript/announcing-typescript-3-9/#solution-style-tsconfig.
If you did intend to use this file, then you can hide this warning by providing it explicitly:

  ngcc ... --tsconfig "tsconfig.json"
```

The error is pretty self-explanatory: when ngcc gets called it tries to use the `tsconfig.json` file in the root folder of my workspace, which is a solution-style tsConfig. Is there a way to tell ng-packagr that ngcc should use the same tsConfig set in the options of the build target, i.e. `projects/MY_PROJECT/tsconfig.lib.json` ?

I'm not an expert at all of angular-related tools, but having a quick look at the source code, shouldn't we be able to configure the value passed to ngcc at this line of [code ](https://github.com/ng-packagr/ng-packagr/blob/884dcaa7d97a26f35905f1e54f82a943ceb27534/src/lib/ngc/ngcc-processor.ts#L64)?

#### How To Reproduce

See above

#### Expected Behaviour

It should be possible to specify which tsConfig file ngcc should use.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            10.0.0
@angular/compiler:     10.0.11
rollup:                2.10.9
tsickle:               
typescript:            3.9.5

```

**Comment by alan-agius4** [comment]
Closing as solution style tsconfig is no longer used in an Angular CLI project.
