### ISSUE TITLE
Error when building library without sub entry points with tsconfig path mappings

### ISSUE THREAD

**Issue by victorsc** [ng-packagr/ng-packagr#1759]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I am trying to build a library that does not have sub entry points but has absolute imports between its components along with path mappings in tsconfig.

#### How To Reproduce

I created a [small library](https://github.com/victorsc/path-mapping-lib) for reproducing the error.

Please note:
1. in `projects/lib-path-mapping/src/lib/comp1/comp1.component.ts`

```javascript
import {Comp2Component} from 'lib-path-mapping/comp2';
```

2. in `projects/lib-path-mapping/tsconfig.lib.json`

```json
    "baseUrl": ".",
    "paths": {
      "lib-path-mapping/*": ["src/lib/*"]
    },
```

- run `ng build`

```
ERROR: Entry point lib-path-mapping/comp2 which is required by lib-path-mapping doesn't exists.
An unhandled exception occurred: Entry point lib-path-mapping/comp2 which is required by lib-path-mapping doesn't exists.
```

#### Expected Behaviour

I would expect that path mappings are considered before any sub entry checks done on the source files.

I suspect that the issue comes from https://github.com/ng-packagr/ng-packagr/blob/551a4d9a866a8c337189f807d755856b995ffc9b/src/lib/ng-package/entry-point/analyse-sources.transform.ts#L97

Is it possible to take into account path mappings before adding the `potentialDependency`?

from
```javascript
            if (moduleName === primaryModuleId || moduleName.startsWith(`${primaryModuleId}/`)) {
                potentialDependencies.add(moduleName);
            }
```

to 
```javascript
            let pathMapped = false;
            Object.keys(tsConfigOptions.paths).forEach(path => {
                if (minimatch(moduleName, path)) pathMapped = true;
            });
            if (moduleName === primaryModuleId || (!pathMapped && moduleName.startsWith(`${primaryModuleId}/`))) {
                potentialDependencies.add(moduleName);
            }
```

Thank you.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 10.1.0
@angular/compiler: 10.0.14
typescript: 3.9.7
rxjs: 6.6.3
node: 12.13.1
yarn: 1.21.1
```

**Comment by SchnWalter** [comment]
The whole idea of `ng-packagr` is to package libraries in the [Angular Package Format](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview) and from what I can tell, what you are trying to do isn't really compatible with APF. I would suggest that you stick to relative imports and sub-packages (sub entry points).

If what you are trying to do is work around the performance issue that you've mentioned in #1758, you should close this story and provide more information there, together with a reproduction repository.
