### ISSUE TITLE
ng-packagr v10 cannot resolve url() path references from deep scss folder structures

### ISSUE THREAD

**Issue by gkamperis** [ng-packagr/ng-packagr#1776]
## Type of Issue

```
[X ] Bug Report
[ ] Feature Request
```

## Description

ng-packagr v10+ cannot resolve paths in url('../../../some.svg') inside scss code when these are referenced from a nested folder structure.

while compiling there is a warning 
`npm run build`

`WARNING: postcss-url: a:\github\lib-ws\projects\my-lib\src\lib\test-component\scss\test-component.component.scss:2:3: Can't read file 'a:\github\lib-ws\projects\my-lib\src\assets\account_box-24px.svg', ignoring
`

#### How To Reproduce

Link to repro repo

https://github.com/gkamperis/ng-packagr-scss-depth-bug

Please note that 

https://github.com/gkamperis/ng-packagr-scss-depth-bug/blob/master/projects/my-lib/src/lib/test-component/scss/test-component.component.scss

resolves the SVG asset ok but 

https://github.com/gkamperis/ng-packagr-scss-depth-bug/blob/master/projects/my-lib/src/lib/test-component/scss/level1/_something.scss

referencing the same asset from a deeper folder cannot.

This results in the asset to not be in-lined as expected

#### Expected Behaviour

ng-packagr v9 with node-sass was correctly resolving these.

I'd expect the scenario to work correctly and all assets to be inlined

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            10.1.2
@angular/compiler:     10.2.0
rollup:                2.26.5
tsickle:
typescript:            4.0.3

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 10.2.0
Node: 14.0.0
OS: win32 x64

Angular: 10.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1002.0
@angular-devkit/build-angular   0.1002.0
@angular-devkit/core            10.2.0
@angular-devkit/schematics      10.2.0
@schematics/angular             10.2.0
@schematics/update              0.1002.0
ng-packagr                      10.1.2
rxjs                            6.6.3
typescript                      4.0.3

**Comment by alan-agius4** [comment]
This is expected as this is how SASS works. SASS implementations don't provide url rewriting, all linked assets must be relative to the output and not the location of the partial source file .scss.

In this case https://github.com/gkamperis/ng-packagr-scss-depth-bug/blob/896bb55a67ef93ad8f5a4e144d26a9742d42993b/projects/my-lib/src/lib/test-component/scss/level1/_something.scss#L2 should be changed to ` background-image: url("../../assets/account_box-24px.svg");`

using node-sass does yield the same problem.

**Comment by gkamperis** [comment]
Thanks for the reply @alan-agius4 .

I stumbled upon this while in an Nx workspace and I did not experience this issue with previous versions and node-sass.

I raised an issue with Nx for the same underlying problem. 

I suspect it is the way a lib is referenced straight by an app in the workspace vs the app linking to the disted artefacts that makes the difference here.

Although this does not look like an ng-packagr issue I will leave the issue open for now until I have some response on the Nx one.

**Comment by alan-agius4** [comment]
> I suspect it is the way a lib is referenced straight by an app in the workspace vs the app linking to the disted artefacts that makes the difference here.

Oh yeah, that is definitely the problem here. An application build uses a different tool chain and certain discrepancies such as the one mentioned above might exists when referring the the library file via path mappings instead of building. Hence, why we don’t recommend using the path mappings workflow.

**Comment by gkamperis** [comment]
@alan-agius4 node-sass with ng9 and nx9 was working fine. 

ng-packagr picks up node-sass if it exists. 

Is there any way to force ng10 to use node-sass?

**Comment by alan-agius4** [comment]
If you install node-sass, ng-packagr will use node-sass.

**Comment by gkamperis** [comment]
@alan-agius4 I know... I mentioned this in my comment :)

Is there a way to force ng10 to do the same?

**Comment by alan-agius4** [comment]
The above will force node-sass to be used in v10.
