### ISSUE TITLE
Mysterious "tsickle" dependency

### ISSUE THREAD

**Issue by NicBright** [ng-packagr/ng-packagr#1801]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I was wondering which package was using `tsickle` (because I pinpointed an error down to it). Usually, you can do so by running `npm ls tsickle` ... but it showed it was a top level dependency of our project ... the developer who set it up must have added it manually (or maybe ng cli does it, too?) ... regardless, the bug is that ng-packagr is using `tsickle` not only as a devDependency as it is specified in its package.json (https://github.com/ng-packagr/ng-packagr/blob/master/package.json#L100).

Compare e.g. with: https://github.com/ng-packagr/ng-packagr/blob/master/src/lib/ngc/create-emit-callback.ts#L69

#### Expected Behaviour

`tsickle` should be made an additional peerDependency or alternatively moved to live under regular `dependencies`.

#### Version Information

This can be seen directly in the master branch

**Comment by alan-agius4** [comment]
Tsickle converts TypeScript transpilled code into a form acceptable to the Closure Compiler. In most cases uses tsickle is not needed outside of Google.


I guess we should add this to be an optional peerDependency until support for tsickle is removed.
