### ISSUE TITLE
only gengerate metadata and typings

### ISSUE THREAD

**Issue by joebnb** [ng-packagr/ng-packagr#1806]
## Type of Issue

```
[ ] Bug Report
[o] Feature Request
```

## Description

could only gengerate metadata and typings with ng-packagr,i want use webpack to bundle process,

#### Expected Behaviour

```
"ngPackage": {
        "dest": "lib",
        "emitTypingsOnly":true, 
        "emitMetadataOnly":true,
        "lib": {
            "entryFile": "src/index.ts"
        }
    },
```

only out put typings and metaData

**Comment by alan-agius4** [comment]
This is not in scope of ng-packagr as this doesn't align with the goal of ng-packagr. The goal of ng-packagr is to generate a shippable library following the Angular package format.
