### ISSUE TITLE
Error: ./node_modules/ng-packagr/lib/utils/color.js

### ISSUE THREAD

**Issue by johanmaia** [ng-packagr/ng-packagr#1825]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description
 
ng-packagr 11.0.3 makes an error :

Error: ./node_modules/ng-packagr/lib/utils/color.js

Module not found: Error: Can't resolve 'tty' in 'D:\path-to\my-project\node_modules\ng-packagr\lib\utils'

#### How To Reproduce

when I run `ng serve` , I got this error 
`Error: ./node_modules/ng-packagr/lib/utils/color.js`
`Module not found: Error: Can't resolve 'tty' in 'D:\path-to\my-project\node_modules\ng-packagr\lib\utils'`

this is my package.json:

```
{
  "name": "myproject",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^11.0.0",
    "@angular/cdk": "^11.0.0",
    "@angular/compiler": "^11.0.0",
    "@angular/compiler-cli": "^11.0.0",
    "@angular/core": "^11.0.0",
    "@angular/flex-layout": "^11.0.0-beta.33",
    "@angular/forms": "^11.0.0",
    "@angular/material": "^11.0.0",
    "@angular/platform-browser": "^11.0.0",
    "@angular/platform-browser-dynamic": "^11.0.0",
    "@angular/router": "^11.0.0",
    "@material-ui/core": "^4.11.0",
    "@ngx-formly/core": "^5.10.6",
    "@ngx-formly/material": "^5.10.6",
    "change-case": "^3.1.0",
    "dashicons": "0.0.2",
    "initials": "^3.0.1",
    "rxjs": "^6.4.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.1100.5",
    "@angular-devkit/build-ng-packagr": "~0.901.1",
    "@angular/cli": "^11.0.0",
    "@angular/compiler-cli": "^11.0.0",
    "@angular/language-service": "^11.0.0",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.19.8",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~5.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "^4.0.1",
    "karma-jasmine-html-reporter": "^1.5.4",
    "ng-packagr": "~11.0.3",
    "protractor": "^7.0.0",
    "ts-node": "~7.0.0",
    "tslint": "^5.0.0 || ^6.0.0",
    "typescript": "~4.0.5"
  }
}
```

**Comment by JoostK** [comment]
It looks like something is importing from `ng-packagr` in a browser bundle, whereas ng-packagr is a NodeJS binary that requires builtin modules (`tty` is such a builtin module).

**Comment by johanmaia** [comment]
> 
> 
> It looks like something is importing from `ng-packagr` in a browser bundle, whereas ng-packagr is a NodeJS binary that requires builtin modules (`tty` is such a builtin module).

Should I change someting in my configuration ?

**Comment by JoostK** [comment]
I can't say at the moment, can you share a Github repo for me to use as reproduction?

**Comment by johanmaia** [comment]
Thanks a lot !!! 
I fix the problem.
When I was prepared a repository for you, I did not see the error that helps me.
The problem was I would like to display errors, warnings message using

`import {warn} from 'ng-packagr/lib/utils/log' 
...
warn('my warning message');
`
But as you said I 

#t looks like something is importing from ng-packagr in a browser bundle, whereas ng-packagr is a NodeJS binary that requires builtin modules (tty is such a builtin module).

I imagined I should find another way to write warning console message.

**Comment by flash-me** [comment]
> I imagined I should find another way to write warning console message.

How about [`console.warn`](https://developer.mozilla.org/en-US/docs/Web/API/Console/warn)?

cheers
flash ⚡
