### ISSUE TITLE
Include a JavaScript library in a packaged component

### ISSUE THREAD

**Issue by Detzito** [ng-packagr/ng-packagr#1836]
## Type of Issue

```
[ ] Bug Report
[X] Feature Request
```

## Description

I created a component that uses the JS library jointjs. For the inclusion, I added the JS file to the angular.json file, in the "scripts" section of the node @angular-devkit/build-angular:browser.

When I launch the application, everything works. But when I run ng-packagr and that I reference this package in another application, I get the error "joint is not defined". I think that my JS library is simply not included in the package. Is there a (simple) way to reference this library to be included ?=

**Comment by SchnWalter** [comment]
@Detzito, for bundling dependencies you should follow #1432 ("Feature Request: Keep Bundled Dependencies").

P.S. Please close this issue.
