### ISSUE TITLE
bug: Packages built on ng10 with `enableIvy` turned off have the wrong import path for `.d.ts`

### ISSUE THREAD

**Issue by damienwebdev** [ng-packagr/ng-packagr#1844]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description
When trying to build an Angular 10 library with `enableIvy: false` I get the wrong path in my output `.d.ts` files.

#### How To Reproduce
The relevant PR: https://github.com/graycoreio/daffodil/pull/1250

https://graycore.visualstudio.com/Daffodil/_build/results?buildId=5281&view=logs&j=c38f29ce-e04b-506f-1547-0eb337037d6d&t=800b40a4-52be-5cb3-e6a0-1e6ad58b2f80

The relevant `.d.ts` file:

```ts
import { InjectionToken } from '@angular/core';
import { DaffCategoryServiceInterface } from '../interfaces/category-service.interface';
export declare const DaffCategoryDriver: InjectionToken<DaffCategoryServiceInterface<import("../..").DaffCategoryRequest, import("../..").DaffCategory, import("../..").DaffCategoryRequest & {
    filters: import("../..").DaffCategoryFilter[];
    sort_options: import("../..").DaffCategorySortOption[];
    total_pages: number;
    total_products: number;
    product_ids: string[];
}, import("../../../../../dist/product").DaffProduct>>;
```

#### Expected Behaviour

I expected to be able to build my packages.

```
import { InjectionToken } from '@angular/core';

import { DaffCategoryServiceInterface } from '../interfaces/category-service.interface';

export const DaffCategoryDriver = new InjectionToken<DaffCategoryServiceInterface>('DaffCategoryDriver');
```

Note that `DaffCategoryServiceInterface` is generic with default types.

```ts
import { InjectionToken } from '@angular/core';
import { DaffCategoryServiceInterface } from '../interfaces/category-service.interface';
export declare const DaffCategoryDriver: InjectionToken<DaffCategoryServiceInterface<import("@daffodil/category").DaffCategoryRequest, import("@daffodil/category").DaffCategory, import("@daffodil/category").DaffCategoryRequest & {
    filters: import("@daffodil/category").DaffCategoryFilter[];
    sort_options: import("@daffodil/category").DaffCategorySortOption[];
    total_pages: number;
    total_products: number;
    product_ids: string[];
}, import("@daffodil/product").DaffProduct>>;
```

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            10.1.2
@angular/compiler:     10.2.4
rollup:                2.26.5
tsickle:               0.39.1
typescript:            3.9.7
```

**Comment by damienwebdev** [comment]
This is likely to a related issue from a while back: https://github.com/ng-packagr/ng-packagr/issues/1405#issuecomment-726112297

**Comment by damienwebdev** [comment]
Manually referencing:

```ts
import { DaffProduct } from '@daffodil/product';
```

In the relevant file fixes the problem, but it looks wrong because the import appears unused in the file.

**Comment by flash-me** [comment]
I think the relative path `import("../../../../../dist/product")` is the result of (wrong?) configuration 
of the baseUrl for the [library](https://github.com/graycoreio/daffodil/blob/develop/libs/category/tsconfig.json#L4).
Since the value is set to `../..`, the `/dist/*` directories are within the compile scope ("source root") of the library, so the imports are not considered as external libraries, which in turn results in referencing with a relative path.

cheers
flash ⚡

**Comment by alan-agius4** [comment]
Closed via https://github.com/ng-packagr/ng-packagr/pull/2051
