### ISSUE TITLE
Library dependencies are not resolved correctly with npm / yarn link

### ISSUE THREAD

**Issue by MickL** [ng-packagr/ng-packagr#1848]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description
After building a library and using `npm link` or `yarn link` to use it within another app, the library dependencies are still looking for the library node_modules instead of the app's node_modules.

#### How To Reproduce

Create a library and an app. Link the library into the app and start it:

```
ng new my-workspace --create-application=false
ng new my-app
cd my-workspace
ng generate library my-lib
ng build my-lib --prod
cd dist/my-lib
npm link
cd ../../../my-app
npm link my-lib
npm run start
```

Add an import into `my-app/src/app/app.module.ts`:

```
import { MyLibService } from 'my-lib';

// ...
  imports: [
    MyLibModule,
    BrowserModule,
    AppRoutingModule
  ],
// ...
```

Everything works as expected. Now remove node_modules from the library project and restart the app:

```
cd ../my-workspace
rm -rf node_modules
cd ../my-lib
npm run start
```

Results in:

> Error: ../my-workspace/dist/my-lib/__ivy_ngcc__/fesm2015/my-lib.js
Module not found: Error: Can't resolve '@angular/core' in '/Users/mick/Desktop/my-workspace/dist/my-lib/__ivy_ngcc__/fesm2015'

Why doesnt it look in `my-app/node_modules` ?

**Comment by JoostK** [comment]
Because of the `preserveSymlinks` configuration, which defaults to false. This means that symlinks are actually resolved, after which node module resolution occurs from within the directory where the linked library is declared. If symlink preservation is enabled, the symlink is not resolved and you stay in the realm of the application.

**Comment by MickL** [comment]
Thanks for the fast response. I tried `preserveSymlinks` to true in angular.json and tsconfig.json still the error is unchanged.

**Comment by MickL** [comment]
@JoostK Thank you so much for your fast reply! Life can be so easy sometimes but this took me hours and hours...

Adding `"preserveSymlinks": true,` into the app's `angular.json` (within architect -> build -> options) resolved the issue.
