### ISSUE TITLE
The library uses environment variables to package an error

### ISSUE THREAD

**Issue by fengzhihenxs** [ng-packagr/ng-packagr#1864]
Hello, I use environment variables in my angular library. When packaging this library, it says "File'C:/Test/src/environments/environment.ts' is not under'rootDir''C:\Test\projects\x -shared\src'.''C:\Test\projects\x-shared\src'.'rootDir' is expected to contain all source files.". I want to know why and how to use environment in angular library?

Thank you!

**Comment by SchnWalter** [comment]
The error message is pretty clear: you are trying to use a TypeScript file that is outside of the library root. Move it inside the library root directory and the build command will stop complaining.

--- 

P.S. I saw that you've first submitted this issue to the Angular repository. If you want to have more chances of getting help, when you submit issues to open source projects, please follow the provided issue template and give all the requested information. Most projects also have contributing guidelines which GitHub links to when you try to submit a new issue:

![image](https://user-images.githubusercontent.com/2186426/107339552-793bdd00-6ac5-11eb-863c-41cb415ca6d7.png)

Make sure that you always read those.
