### ISSUE TITLE
Inconsistent peer dependencies between ng-packagr and angular-cli

### ISSUE THREAD

**Issue by alexhobbs** [ng-packagr/ng-packagr#1866]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

Using the latest @angular/cli + ng-packagr results in the following peer dependency warnings. build-angular requires v7 of postcss, ng-packagr is after v8.

```console
npm WARN postcss-import@14.0.0 requires a peer of postcss@^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-modules-extract-imports@3.0.0 requires a peer of postcss@^8.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-modules-local-by-default@4.0.0 requires a peer of postcss@^8.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-modules-scope@3.0.0 requires a peer of postcss@^8.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-modules-values@4.0.0 requires a peer of postcss@^8.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-url@10.1.1 requires a peer of postcss@^8.0.0 but none is installed. You must install peer dependencies yourself.
```

#### How To Reproduce

Install latest @angular/cli and latest ng-packagr, warnings will show after npm install.

#### Expected Behaviour

I'd expect these to be in sync with one another (but please correct me if wrong). @angular/cli rolled back to a lower version of css-loader, so not sure if that needs to be done here also or if unrelated. https://github.com/angular/angular-cli/pull/19376 

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 11.2.0
@angular/*: 11.1.2
typescript: 4.1.3
rxjs: 6.6.3
node: 12.20.1
npm: 6.14.10
```

**Comment by SchnWalter** [comment]
There shouldn't be any problem, a newly generated workspace works just fine, and dependencies are deduplicated. You probably have an invalid `package-lock.json`. How did you update to `ng-packagr@11.2.0`?

Did you update using `ng update ng-packagr`? Or at least, did you follow the NPM best pactices for updating dependencies? In your case, the easiest fix would be to just delete the `node_modules` and `package-lock.json` and run `npm install`, this way, you'll have the latest version of everything.

P.S. A newly generated workspace without `ng-packagr` will have `@angular-devkit/build-angular@0.1101.4`, which requires both postcss v7 and postcss v8 and it works just fine.

**Comment by alan-agius4** [comment]
Closing as no further feedback provided.
