### ISSUE TITLE
Override tsconfig.lib.json

### ISSUE THREAD

**Issue by ArcosBinary** [ng-packagr/ng-packagr#1870]
## Type of Issue

```
[x] Question
```

## Description

I want to override the compiler options of the tsconf.lib.json. There is a documentation for this:
https://github.com/ng-packagr/ng-packagr/blob/HEAD/docs/override-tsconfig.md
But it's not working for me. I don't have an api. So I just created a tsconfig.lib.json on my root folder:
```json
{
    "extends": "./node_modules/ng-packagr/lib/ts/conf/tsconfig.ngc.json",
    "compilerOptions": {
        "resolveJsonModule": true,
        "esModuleInterop": true,
    }
}
```
But when running 'npm run packagr' the options are not applied. It only works when adding these options to the tsconfig.lib.json in the node_modules. But this is not an option in combination with a build pipeline.
Here is also an issue at stackoverflow for this problem:
https://stackoverflow.com/questions/62161673/specifying-resolvejsonmodule-true-when-running-ng-packagr

So the question is: How exactly can the config be overridden? Could someone provide an example?

**Comment by flash-me** [comment]
> But it's not working for me. I don't have an api. So I just created a tsconfig.lib.json on my root folder

*"I haven't done what the docs are telling me, so I just did something else."* **Seriously, what did you expect?**

The docs are **not** referring to **your** API. 
It's about the API of ng-packagr.

You can see how it's done by looking into the code itself. 
[See here](https://github.com/ng-packagr/ng-packagr/blob/master/src/lib/commands/build.command.ts#L23)

You also know, that by doing this, you take the responsibility of the results, right? Just wanted to mention here

cheers
flash ⚡

**Comment by ArcosBinary** [comment]
Yeah, I misread this part. 
The build commands helped me. Thanks 4 that.

`"packagr": "ng-packagr -p ng-package.json --config tsconfig.lib.json"`
did the trick.

**Comment by flash-me** [comment]
Great you got it working!
May you close the issue, if you don't have any questions left? 
cheers
flash ⚡
