### ISSUE TITLE
Uglified UMD bundle for PlatformBrowser broken

### ISSUE THREAD

**Issue by flash-me** [ng-packagr/ng-packagr#1882]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

The minimized UMD bundle of `@angular/platform-browser` cannot be used. If any ngModule imports the `BrowserModule` an error will be thrown on bootstrap: 
```
definition.ts:753 Uncaught Error: Type t does not have 'ɵmod' property.
    at getNgModuleDef (definition.ts:753)
    at recurse (ng_module_factory_registration.ts:49)
    at recurse (ng_module_factory_registration.ts:61)
    at registerNgModuleType (ng_module_factory_registration.ts:45)
    at new NgModuleFactory (ng_module_ref.ts:121)
    at compileNgModuleFactory__POST_R3__ (application_ref.ts:66)
    at PlatformRef.bootstrapModule (application_ref.ts:401)
    at first.mfe.ts:29
    at angular-mfe-first.umd.js:4
    at angular-mfe-first.umd.js:5
``` 

#### How To Reproduce

Just import it, e.g. 
```
<script src="node_modules/@angular/platform-browser/bundles/platform-browser.umd.min.js"></script>
``` 

#### Expected Behaviour

That angular can bootstrap

#### Version Information
![image](https://user-images.githubusercontent.com/5240450/108494001-51a7fa00-72a7-11eb-8670-bc2ebd54d991.png)

#### The issue

Somehow, the prototype of the global exports from `platform-Browser` will be minified. 

platform-browser.umd.js:
![image](https://user-images.githubusercontent.com/5240450/108493349-7ea7dd00-72a6-11eb-9573-e98cf1603a4b.png)

platform-browser.umd.**min**.js:
![image](https://user-images.githubusercontent.com/5240450/108493686-e52cfb00-72a6-11eb-884c-ce1ab8d44b2e.png)

Which leads to the injection error shown above. 
The other UMD bundles are fine so far.

_Please include all version numbers that might be relevant, e.g. third-party libraries_
**I think this is the case since Angular Version 9**, but since I'm the only human on earth that ~~uses~~ [used](https://github.com/angular/angular-cli/issues/20056#issuecomment-781899902) those UMD bundles,<br>it's not that high priority I guess. Just wanted to mention this here. Maybe the bug can reveal something interesting to prevent further issues in the future related to minification.

**Update**: Both the usual bundle and the ivy-compiled bundle have this issue

cheers
flash ⚡

**Comment by flash-me** [comment]
Just played a bit. 
![image](https://user-images.githubusercontent.com/5240450/108497283-828a2e00-72ab-11eb-9b87-0dae71fbfa42.png)


cheers
flash ⚡

**Comment by alan-agius4** [comment]
This seems like an Angular built pipeline and not ng-packagr. Ng-packagr, is not used to bundle the Angular framework.

That said the problem here appears to be that the class names are also minified.
