### ISSUE TITLE
Build lib project missing details about whey I get `i` instead of 'v'

### ISSUE THREAD

**Issue by ofirrifo** [ng-packagr/ng-packagr#1883]
## Type of Issue

```
[X] Feature Request
```

## Description
I'm using the angular cli to build library.
When I build the library I get nice indication about the build.

✔ Compiling TypeScript sources through NGC
✔ Bundling to FESM2015
✔ Bundling to UMD
✔ Minifying UMD bundle
ℹ Removing devDependencies section in package.json.
✔ Writing package metadata
ℹ Built  @rifo/my-lib

The issue is the last one that show me `i Built  @rifo/my-lib`
and I don't get any details what is the issue.

#### How To Reproduce
just execute the command to build lib

#### Expected Behaviour
To get more details about whey I get `i` instead of 'v'

#### Version Information

```
Angular CLI: 11.2.0
Node: 12.3.1
OS: darwin x64

Angular: 11.2.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.0
@angular-devkit/build-angular   0.1102.0
@angular-devkit/core            11.1.4
@angular-devkit/schematics      11.1.4
@schematics/angular             11.2.0
@schematics/update              0.1102.0
ng-packagr                      11.1.4
rxjs                            6.6.3
typescript                      4.0.5

```

**Comment by JoostK** [comment]
`i` indicates "Info" in this case, not "Issue" :-)

**Comment by ofirrifo** [comment]
@JoostK I understand but what is the info ?

**Comment by alan-agius4** [comment]
That the library was built, maybe we should change it to a very good sign
