### ISSUE TITLE
Rename whitelistedNonPeerDependencies

### ISSUE THREAD

**Issue by devsull** [ng-packagr/ng-packagr#1884]
## Type of Issue

```
[ x ] Feature Request
```

## Description

Consider renaming "white listed," to something less racially charged - like "allowed."

**Comment by SchnWalter** [comment]
Fell free to submit a PR, but make sure to include a deprecation phase for the existing settings.

Make sure to read [CONTRIBUTING.md](https://github.com/ng-packagr/ng-packagr/blob/master/CONTRIBUTING.md) and if you need help running the tests, I've added some information to `docs/DEVELOP.md` in this pull request: https://github.com/ng-packagr/ng-packagr/pull/1853

**Comment by devsull** [comment]
> Fell free to submit a PR, but make sure to include a deprecation phase for the existing settings.
> 
> Make sure to read [CONTRIBUTING.md](https://github.com/ng-packagr/ng-packagr/blob/master/CONTRIBUTING.md) and if you need help running the tests, I've added some information to `docs/DEVELOP.md` in this pull request: #1853
> 
> L.E. An example on how to rename something in the configuration can be found in this pull request: #1722

I was able to execute the tests however I got an error during their execution unrelated to my changes: 

```
$ integration/samples.sh
$ cross-env TS_NODE_PROJECT=integration/tsconfig.specs.json mocha --require ts-node/register "integration/samples/*/specs/**/*.ts"

TSError: ⨯ Unable to compile TypeScript:
integration/samples/core/specs/ts-api.ts:2:26 - error TS2307: Cannot find module '../dist/sample-core' or its corresponding type declarations.

2 import { Foo, Bar } from '../dist/sample-core';
                           ~~~~~~~~~~~~~~~~~~~~~
```
