### ISSUE TITLE
Support for package.json exports

### ISSUE THREAD

**Issue by k3nsei** [ng-packagr/ng-packagr#1890]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

I would like to have control over what is public in my package and what isn't.
[Package Exports](https://nodejs.org/api/packages.html#packages_exports) gives us ability to define those.
This should prevent library users of importing library internals. 

Example of usage is here
```json
{
  "exports": {
    "default": {
      "import": "./fesm2015/ngx-abcd.js",
      "require": "./bundles/ngx-abcd.umd.js"
    },
    "node": {
      "import": "./fesm2015/ngx-abcd.js",
      "require": "./bundles/ngx-abcd.umd.js"
    }
  }
}
```

**Comment by alan-agius4** [comment]
These will be added when they are part of the APF spec.

**Comment by costlydeveloper** [comment]
@alan-agius4 what is the "APF", where to look for that? 

does anyone know is there a way to manually add exports on package json? what package files from the bundle should be there to prevent the import from internal files such as nested d.ts.

**Comment by alan-agius4** [comment]
@costlydeveloper https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview

**Comment by alan-agius4** [comment]
Closing since this is not actionable until it's part of the APF spec.
