### ISSUE TITLE
Issue with AOT builds (Field 'browser' doesn't contain a valid alias configuration)

### ISSUE THREAD

**Issue by LukeArthurs** [ng-packagr/ng-packagr#1897]
## Type of Issue

```
[x ] Bug Report
[ ] Feature Request
```

## Description

Alright I'm not entirely sure where this issue is coming from, ng-packagr or @angular/compiler or something else but I've moving part of our monolith angular application into a angular library. Had enough issues with having to change dependencies and barrel file issues and what not but I've gotten to a successful stage that everything works in the not AOT build. 

So ng build/ng serve work just fine but ng build --prod is not. Ive done a lot of research myself the past two days and have come pretty far but theres something Im missing and I cant think of anything else anymore. Also been a good long while since I opened an issue on github so Ive exhausted my google searching capabilities.

#### How To Reproduce

Folder structure: (There are more subpackages but all follow the same structure, showing two as example)
```
|---shared-kernel
|----------feedback
|----------------internal
|                package.json
|                public-api.ts               
|----------filters
|----------------internal
|                package.json
|                public-api.ts         
|   ng-package.json
|   package.json
|   public-api.ts
|   tsconfig.lib.json
|   tslint.json
```

main ng-package.json
```
{
  "$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
  "dest": "../../dist/shared-kernel",
  "lib": {
    "entryFile": "public-api.ts"
  }
}
```
main package.json
```
{
  "name": "@portal/shared-kernel",
  "version": "0.0.26",
  "peerDependencies": {
    "@angular/common": "~11.2.2",
    "@angular/core": "~11.2.2",
    "@angular/cdk": "~11.2.2",
    "@angular/material": "~11.2.2"
  },
  "dependencies": {
    "tslib": "^2.0.0"
  }
}
```
subpackages (all the same setup)
```
---package.json
{
  "ngPackage": {
    "lib": {
      "entryFile": "public-api.ts",
      "cssUrl": "inline",
      "styleIncludePaths": ["../../../sass"]
    }
  }
}

---public-api.ts
export * from "./internal/filter/filter.component";
export * from "./internal/contracts/filter-type.enum";
export * from "./internal/filters-overview.component";
export * from "./internal/contracts/filter.dto";
export * from "./internal/contracts/filter-option.dto";
export * from "./internal/filters.module";
export * from "./internal/testing/filter-dto.fixture";

```
tsconfig.json
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "skipLibCheck": true,
    "esModuleInterop": true,
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "strictPropertyInitialization": false,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "module": "esnext",
    "lib": [
      "es2017",
      "es2018",
      "es2019",
      "dom"
    ],
    "paths": {
      "@portal/shared-kernel/*": [
        "projects/shared-kernel/*/public-api.ts"
      ]
    }
  },
  "angularCompilerOptions": {
    "annotateForClosureCompiler": true,
    "skipTemplateCodegen": true,
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true,
    "strictMetadataEmit": true,
    "enableResourceInlining": true
    "enableIvy": false
  }
}
```

The package/subpackages are properly built and pushed to a private npm repo and loaded into the application with the normal npm/node_modules flow

```
@portal/shared-kernel
@portal/shared-kernel/feedback
@portal/shared-kernel/filters
etc.....
```
Here's a screenshot of it post npm install
![image](https://user-images.githubusercontent.com/6594054/109398674-89b1db80-793e-11eb-8a04-1ca61795816a.png)
and the package.json
```
{
  "main": "../bundles/portal-shared-kernel-filters.umd.js",
  "module_ivy_ngcc": "../__ivy_ngcc__/fesm2015/portal-shared-kernel-filters.js",
  "module": "../fesm2015/portal-shared-kernel-filters.js",
  "es2015_ivy_ngcc": "../__ivy_ngcc__/fesm2015/portal-shared-kernel-filters.js",
  "es2015": "../fesm2015/portal-shared-kernel-filters.js",
  "esm2015": "../esm2015/filters/portal-shared-kernel-filters.js",
  "fesm2015_ivy_ngcc": "../__ivy_ngcc__/fesm2015/portal-shared-kernel-filters.js",
  "fesm2015": "../fesm2015/portal-shared-kernel-filters.js",
  "typings": "portal-shared-kernel-filters.d.ts",
  "metadata": "portal-shared-kernel-filters.metadata.json",
  "sideEffects": false,
  "name": "@portal/shared-kernel/filters",
  "__processed_by_ivy_ngcc__": {
    "es2015": "11.2.3",
    "fesm2015": "11.2.3",
    "module": "11.2.3",
    "typings": "11.2.3"
  }
}
```
And finally the error on AOT production build
![image](https://user-images.githubusercontent.com/6594054/109398785-312f0e00-793f-11eb-8ef9-a9cdbfb9a0dc.png)

All I've been able to tell is that the module resolution in webpack seems to be going to the wrong place despite all the paths being described in package.json. The error appears about a billion times for all the separate imports in all the files but all the same resolution.

#### Expected Behaviour

The expected behavior would be to build successfully just like the serve/build jit mode. The node_modules package output is pretty similar to @angular/material so I dont really know what I'm missing at this point.

The main application does use "@angular-builders/custom-webpack": "^11.1.0", if thats important at all. The custom webpack only does scss/css related actions so that shouldn't be an issue. 

#### Version Information

```
ng-packagr: ^11.2.4
@angular/*: ~11.2.2
typescript: 4.0.5
rxjs: ~6.6.0
node: 12.14.0
npm: 6.14.9
```

**Comment by JoostK** [comment]
Something seems off in the way you presented the `package.json` file and the folder structure:

```
|----shared-kernel
|----------feedback
|----------------internal
|                        package.json
|                        public-api.ts               
|----------filters
|----------------internal
|                        package.json
|                        public-api.ts         
|     ng-package.json
|     package.json
|     public-api.ts
|     tsconfig.lib.json
|     tslint.json
```

does not align with what you posted for the configuration of subpackages:

```
---package.json
{
  "ngPackage": {
    "lib": {
      "entryFile": "public-api.ts",
      "cssUrl": "inline",
      "styleIncludePaths": ["../../../sass"]
    }
  }
}

---public-api.ts
export * from "./internal/filter/filter.component";
export * from "./internal/contracts/filter-type.enum";
export * from "./internal/filters-overview.component";
export * from "./internal/contracts/filter.dto";
export * from "./internal/contracts/filter-option.dto";
export * from "./internal/filters.module";
export * from "./internal/testing/filter-dto.fixture";
```

Notice the `public-api.ts` file refers to `./internal`, but the folder structure suggests that `public-api.ts` is itself contained in `./internal`.

I am not entirely sure what is wrong, but that `internal` folder appears to be treated inconsistently.

**Comment by LukeArthurs** [comment]
Sorry the spacing is a little off but the internal folder contains all the code for the subpackages and the public-api.ts is always outside of it and exporting the correct contents

**Comment by LukeArthurs** [comment]
Well, after a very looooong debug session I finally figured out the issue. It was my own mistake and not that of the ng-packagr or anything else.

In the legacy code there was a modules.ts file which re-exported all the modules from the now external npm angular library.

When the library code was still within the application code then that didnt cause any issues, but coming from an npm package caused some sort of looping process which just destroyed my sanity.

I'm not sure if this is an Angular compiler issue or webpack itself but whoever it is does not give any clear warnings, Ill test it in a non angular application later on to see who is to blame and record the issue if I can find it to help any future developers.
