### ISSUE TITLE
ES5 deprecated but Angular >= 10 is still supported it

### ISSUE THREAD

**Issue by lalogrosz** [ng-packagr/ng-packagr#1900]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I saw the issue [https://github.com/ng-packagr/ng-packagr/issues/1732](https://github.com/ng-packagr/ng-packagr/issues/1732), but I have to migrate to Angular 10 and then to Angular 11, but my clients are still using IE11 and I need support to ES5 too. My libraries witch are migrated to Angular 10, now they have a dependency to ng-packagr@10. When I build my Angular 10, that libraries crash in IE11. Why yo deprecated this if Angular is still supported ES5?

**Comment by alan-agius4** [comment]
Angular CLI 10+ will downlevel the library from es2015 to es5 when the consuming application is configured via browserslist configuration to support IE11.

**Comment by lalogrosz** [comment]
I'm sorry, but when I have an Angular 10 project with browserlist configured with ie11, It loads from fesm2015 library folder even when I use IE11. I have errors with arrow functions for example. Any idea?

**Comment by alan-agius4** [comment]
fesm2015 will always be used, this will be downlevelled to ES5 when IE11 support is needed.

Without a reproduction, it’s hard to tell what’s the problem.

Is the error occurring during `ng serve`? What’s the target in the application’s tsconfig?

**Comment by lalogrosz** [comment]
I'm sorry, I was testing in an Angular 9 project with Angular 10 libraries. When I upgrade to Angular 10, these libraries were transpiled to ES5 too.
Thanks!
