### ISSUE TITLE
Add configuration option to opt-out "ivy library" warning

### ISSUE THREAD

**Issue by MarioSchymura** [ng-packagr/ng-packagr#1901]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

Add an configuration option to disable the warning regarding publishing of "ivy libraries".

During build a message is shown warning to not publish libraries using ivy to NPM repositories. A project using only ivy components and encapsulation these into libraries is absolutely viable and should therefore not be warned about this during every build.

Warning get created and shown in `init-tsconfig.transform.ts`

#### How To Reproduce

Just use `ng build`

#### Expected Behaviour

Hide the warning, if the respective newly created configuration option opts out showing the warning.

#### Version Information

```
ng-packagr: 11.2.4
```

**Comment by dimeloper** [comment]
Today morning me and my team spent almost 2 hours debugging an issue that turned out to be caused by enabling Ivy on an ng-packagr library - we're also using version `11.2.4`. I would suggest not only leaving the warning as it is, but probably throw an error instead.
