### ISSUE TITLE
Keep package.json in dist folder before build

### ISSUE THREAD

**Issue by gstvribs** [ng-packagr/ng-packagr#1902]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I need to print the version coming from package.json in my component but the package.json do not exists in my dist folder when the build occurs.

Is there any way fix this problem above?

#### How To Reproduce

So i have a `public_api.ts` file. that requires the version from package.json

```ts
export { ComponentModule } from './lib/component.module';

export const { version } = require('../package.json');
```

And in my html i use this version to print the version

```
<div [attr.data-version]="version">
```

But, when i build this component the ng-packagr throws this error:

```
------------------------------------------------------------------------------
Building entry point '@ng-mydesignsystem/component'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
Bundling to FESM2015
ERROR: Could not resolve '../package.json' from dist/esm2015/index.js
```
#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 9.1.5
@angular/compiler: 8.2.14
rollup: 2.7.5
typescript: 3.5.3
node: 10.23.0
npm: 6.14.8
```

**Comment by williamsousa** [comment]
@gstvribs I've the same issue that you report.

@alan-agius4 can you help us, please.

**Comment by alan-agius4** [comment]
Avoid using `require` In any of your code unless you creating something for Node.JS <=12.

You can use TypeScript `resolveJsonModule` instead.

**Comment by gstvribs** [comment]
Upgrading to the latest version: ng-packagr@11.2.4 solves the problem!

@alan-agius4

1) Upgrading to the latest version of ng-packagr i lost backwards compatibility if this library is used in Angular 8/9 applications?
2) I'm using `require` to bypass the error that `package.json is not under the rootDir`, do you know any workaround that i can made here?

The project is in a monorepo structure.
