### ISSUE TITLE
Relative source map source file paths break the debugging mappings

### ISSUE THREAD

**Issue by Egorikhin** [ng-packagr/ng-packagr#1903]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description
Hi,
Thanks for the great library.
After the https://github.com/ng-packagr/ng-packagr/issues/1622 was merged, our sourcemaps seems to be broken. We're using yarn workspaces + lerna monorepo setup and have separate libraries packaged with ng-packagr which are then bundled to the electron application by webpack.
Previously we had libraries sourcemaps generated with `sources` paths like this: `"ng://@scope/package1/model/something.ts","ng://@scope/package2/helpers/something2.ts`. We had configured our launch.json file to use sourceMapPathOverrides to resolve those "fake" paths to correct source folders like this
```
"sourceMapPathOverrides": {
   ng://@scope/package1/*": "${workspaceFolder}/Package1/lib/src/*",
   ng://@scope/package2/*": "${workspaceFolder}/Package2/lib/src/*",
}
```
And VSCode debugging worked correctly for a while.

After 1622 was merged, sourcemaps are generated with `sources` paths like this: `"../../src/model/something.ts","../../src/helpers/something2.ts"`. And during the runtime they're actually resolved to incorrect paths (`node_modules/@scope/src/model/something.ts`, which is missing `package1`). So there is no actual ability to distinguish different source roots anymore and no ability to configure correct sourceMapPathOverrides. 

#### Expected Behaviour
Either sourcemaps are generated as previously or some configuration mechanism added to be able to specify the behavior of sourcemap generation process.

Or maybe you have an experience with webpack and could advice how could I parse those sourcemaps to rewrite those paths?

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 10.1.2
@angular/*: 10.2.3
typescript: 4.0.5
rxjs: 6.6.3
node: 10.24.0
npm/yarn: yarn 1.22.5
```

P.S. I can create a PR with configuration parameter with like `relativeSourceRoot` name and default value of `true` and return the previous behavior when this flag is `false`. What do you think?

**Comment by alan-agius4** [comment]
Hi @Egorikhin,

Adding a custom protocol such as `ng://` is not something that we want to allow or do. This breaks https://webpack.js.org/loaders/source-map-loader/

You mentioned that you are using `Webpack`, is this a custom build configuration or is it via the Angular CLI? If it's custom are you enabling sourcemaps loading with https://webpack.js.org/loaders/source-map-loader.

**Comment by Egorikhin** [comment]
We have a custom webpack config ejected for angular CLI long ago. I've tried to use source-map-loader but I wasn't able to configure it in a way that will work for those relative paths. As there is only one option here - allow/disallow to process a file, I'm not quite sure how to configure it to fit my situation. Do you have any insights here?

**Comment by alan-agius4** [comment]
I am not sure what is your Webpack setup since you are not using the Angular CLI. But it's likely you have some misconfigurations in Webpack config, since this works in Angular CLI which uses Webpack under the hood.

There are a number of options that effect sourcemaps, but likely it's one of the below;
- context https://webpack.js.org/configuration/entry-context/#context
- symlinks https://webpack.js.org/configuration/resolve/#resolvesymlinks

At the point, there is nothing we can do there, as it does appear to be a misconfiguration of Webpack.
