### ISSUE TITLE
After upgrading to v11, component throws Can't resolve all parameters for <ChildrenComponent>

### ISSUE THREAD

**Issue by gstvribs** [ng-packagr/ng-packagr#1909]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I currently use ng-packagr in a monorepo project using Lerna and after upgrading ng-packagr to version `11.2.4`, an error message started to appear on a specific type of component.

`Can't resolve all parameters for ChildrenComponent (?, ?, ?, ?, ?, ?, ?, ?, ?, ?).`

Before that i was using the version `9.1.5` and it was working perfectly.

important information: this type of error only happens with components that depend on other components that also depend on other components, within the same monorepo.

Example:

```
// Works
componentA

// Works
componentA
    requires -> componentB

// DO NOT WORK
componentA
    requires -> componentB
                        requires -> componentC

```

Components that depend on themselves, or have only one dependency, the package works normally. 

#### Expected Behaviour

There are any reasons for that do not work? i want to upgrade de ng-packagr, because another bug was just fixed in v11 version and i needed this fix.

#### Version Information

```
ng-packagr:            11.2.4
@angular/compiler:     8.2.14
rollup:                2.40.0
typescript:            3.5.3
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by gstvribs** [comment]
@alan-agius4

**Comment by SchnWalter** [comment]
@gstvribs, this is probably related to this change in Angular and not with ng-packagr:

> https://v10.angular.io/guide/migration-undecorated-classes

Whenever you do an update, you should use update.angular.io:

> https://update.angular.io/?l=3&v=9.1-11.0

Did you use `ng update`? Or did you only make changes to `package.json`?

**Comment by alan-agius4** [comment]
@gstvribs, It appears that you are using Angular version 8 with ng-packagr versions 11. Please be aware that the major version so `ng-packagr` and `@angular/` need to be aligned. It is also unclear what you mean by a component requiring another component, are you referring to a component being injected through DI into another component or something else? 

If the problem persists after aligning Angular and ng-packagr version please file an issue with a minimal reproduction. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.
