### ISSUE TITLE
Keep the ng-update section in package.json

### ISSUE THREAD

**Issue by handijk** [ng-packagr/ng-packagr#1914]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

I want to keep the `ng-update` section in my package.json so the users of my library are able to update using `ng update`.

#### Expected Behaviour

Copy the `ng-update` section to the final library package.json.

**Comment by alan-agius4** [comment]
Hi @handijk,

I am not sure what you are experiencing here, but we don't delete `ng-update` properties from the `package.json`.

**Comment by handijk** [comment]
I think i was experiencing some mental meltdown, because indeed, the `ng-update` section is totally fine.
