### ISSUE TITLE
IVY support - Throw an error if IVY is enabled

### ISSUE THREAD

**Issue by dimeloper** [ng-packagr/ng-packagr#1923]
## Type of Issue

```
[ ] Bug Report
[ x] Feature Request
```

## Description

Today morning me and my team spent almost an hour debugging an issue on our main app that turned out to be caused by enabling Ivy on an `ng-packagr` library of ours - we're using version `11.2.4`. By disabling Ivy on our library the main app started working again.

Error details (thrown at the main app):
```
TypeError: record.factory is not a function
    at R3Injector.hydrate (core.umd.js:11886)
    at R3Injector.get (core.umd.js:11702)
    at core.umd.js:11740
    at Set.forEach (<anonymous>)
    at R3Injector._resolveInjectorDefTypes (core.umd.js:11740)
    at new NgModuleRef$1 (core.umd.js:25956)
    at NgModuleFactory.create (core.umd.js:26016)
    at core.umd.js:29828
```
Worth to mention that both library and main app were built with no issues, but during runtime the main app was not able to load.

#### Expected Behaviour

If IVY is not fully supported and these kind of errors are expected to occur, why not throwing an error in the first place in order to force `ng-packagr` users to disable Ivy on their libraries?

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 11.2.4
@angular/*: 11.2.6
typescript: 4.1.5
rxjs: 6.6.3
node: 14.8.0
npm/yarn: 1.22.0
```

**Comment by alan-agius4** [comment]
Generating Ivy libraries is supported.

@JoostK any idea what’s happening here?

**Comment by JoostK** [comment]
I suspect that the library was built either in a different workspace using a different Angular version, or built earlier and published somewhere and then used in a consuming Angular app with a newer version of Angular. That is problematic for Ivy built libraries, and exactly the reason why the warning is reported.

There are a couple of usage patterns where using fully Ivy compiled libraries is beneficial and I don't think it's a good idea to disallow Ivy by default, at least as we know it today using full compilation mode. We may want to reconsider once partial compilation mode is finalized (planned for v12); I could imagine that you'd have to explicitly opt-in to full compilation for libraries if you know what you're doing, but that you'd get partial compilation which avoids this category of issues.

As a sidenote: for upcoming APF versions I think it would be valuable to augment the `package.json` file with information about the Angular compiler used:

```json
{
  "angular": {
    "version": "12.0.0",
    "compilationMode": "partial",
  }
}
```

This information could then be used by tooling to better detect invalid configurations (although tooling would have to manually verify this; I don't think e.g. the CLI currently reads any `package.json` files itself)

**Comment by dimeloper** [comment]
Ok I see. The Angular version we're using at our web application (where the ng-packagr library is being used) is `11.2.7` so I guess there is no major mismatch there. The main problem is that due to the error logs that we got in the console we were basically unable to investigate the root cause of the problem and adjust our library.

The information about APF versions `12.x.x` sounds promising but still seems like IVY cannot be reliably supported on the current stable versions `11.x.x` ....

**Comment by JoostK** [comment]
> but still seems like IVY cannot be reliably supported on the current stable versions 11.x.x ....

@dimeloper The current requirement for Ivy built libraries is that they are used in an application using the exact same version; even the same patch version. Unfortunately there is no formal verification when building the application that all libraries align, resulting in the hard-to-debug error you experienced.

**Comment by alan-agius4** [comment]
Thanks for looking into this @JoostK.

It though that the library was consuming in the same monorepo, where the same Angular version is used, since publishing an Ivy library is not allowed and will fail with an error.
