### ISSUE TITLE
Question: Is there a way to consume generated angular 11 library in applications using angular 6?

### ISSUE THREAD

**Issue by alankin** [ng-packagr/ng-packagr#1924]
## Type of Issue

```
[ ] Bug Report
[ ] Feature Request
[x] Question
```

## Description
If this is not the right platform for questions, please let me know.

I am using `ng-packagr` with Angular CLI 11.0.1 to build/publish a library. I read in the documentation about major changes and found that as of version 10, the generation of the es5 and esm5 package was removed.
I need to have a library of commons working in two apps, one with angular 11 and one with angular 6, so could you please give me some guidance (links, tips) to see what would be the best way to proceed?

Currently like es5/esm5 is not included, I'm having the following error in angular 6 application:

` TypeError: Class constructor BaseCommand cannot be invoked without 'new'`

This is an abstract class that is part of my common library built with Angular 11.

Thank you very much in advance.

**Comment by alan-agius4** [comment]
Hi,

No, libraries are not backwards compatible. They are only forward compatible for up to 2 major versions.

If you want to use a library with Angular 6, you need to compile the library with Angular 6 or before.

NB: anything before Angular 9 is no longer supported by the Angular team.
