### ISSUE TITLE
Getting List of All Dependencies and Transient Dependencies

### ISSUE THREAD

**Issue by CodeSwimBikeRunner** [ng-packagr/ng-packagr#1936]
## Type of Issue
Unsure if my request exists.
```
[ x] Feature Request
```

## Description
Let's say I have half a dozen libraries through an angular workspace.

- monorepo
    - projects
        - services
             - error-handler
             - user-client
             - whatever
         - deployments
             - www-site
             - portal
             - vendor-management
         - components
             - data-panel
             - crud-table
             - header    
    - angular.json
    - package.json
   
   
Any service can depend on any service, many components could require many service dependencies, many deployments could depend on multiple components, and not all deployments could use every component, etc.

In an angular project if I have the `user-client` service built, with `ng build user-client`. It builds the output in the dist folder, and every consumer of the `user-client` dependency is happy. What I mean by happy is the angular-language-service can recognize the import for `@services/user-client`. Building of the deployments are happy, etc.

So my request is, is it possible to get every dependency, and every transitive depency recursively from ng-packagr. What I can gather, is that this project does the heavy lifting of building that information.

I need this in order to know things like code coverage, and ensuring that if i were to deploy www-site, that all depencies have also ran ng test for them, and get this type of output.

I also want this list to determine that if someone were to make a change to user-client. I can get a list of all deployments that use user-client, and redeploy those.

I'm not going to publish these, create artifacts or anything of that nature. I just need this list.

**Comment by alan-agius4** [comment]
Hi @CodeSwimBikeRunner, 

This not in scope of ng-packagr.

 What you want is a a tool that generates a full dependency graph something like https://nx.dev/latest/angular/structure/dependency-graph

**Comment by CodeSwimBikeRunner** [comment]
I'm sorry, let me describe my issue. package a depends on package b, however package b might not be built yet, or the package has changes. How do I.
- get package b to build when i build package a.
- watch for changes on package b
- if I'm running a deployment, how would I do something similar?
- how do I get package b tests to run when I run package a tests?

Is there something with angular schematics/builder/architect whatever its all called I am missing?
