### ISSUE TITLE
Style imports are ignored, only the file specified in angular.json is included

### ISSUE THREAD

**Issue by CSchulz** [ng-packagr/ng-packagr#1941]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description
All imports in a less file are ignored with the newest version of ng-packagr 11.2.3.
It works fine with ng-packagr 11.0.3

#### How To Reproduce
Create a file like this:

styles.less
```
// cms less
@import "const/variables.less";
```

const/variables.less
```
// @name variables
// @description global less variables for dpui
@roundDigits:                       3;

// global paths
@dir_designSources:                 '../';
```

angular.json:
`"styles": ["projects/styles/styles.less"],`

Build the project, you can see the dist folder is missing the const/variables.less file.

#### Expected Behaviour
All files should be included like before in ng-packagr 11.0.3

#### Version Information

```
ng-packagr: 11.2.3
typescript: 4.0.5
@angular/cli: 11.0.7
```

**Comment by alan-agius4** [comment]
ng-paxkagr doesn’t use `angular.json`

Can you example you are trying to do?

**Comment by alan-agius4** [comment]
Closing as the author didn't get back to us.
