### ISSUE TITLE
Cannot find copied javascript or png files

### ISSUE THREAD

**Issue by Elikill58** [ng-packagr/ng-packagr#1948]
## Type of Issue

```
[x] Bug Report
```

## Description

I have a folder with multiple JS and TXT file.
The objective is to include it in the dist folder, and also make them include in application.

For example, I have `js/worker.js`.

When I build, I want that there is `/lib/js/worker.js`.

When I include my library, I want that it can be accessed with `/js/worker.js` or something like that.

Currently, I success to copy it, thanks to assets. But I failed to find it when I run application which use library.

#### How To Reproduce

Copy assets in builded librairy, and try to find them in `http://localhost:4200/here`.

#### Version Information

```
Angular CLI: 11.0.7
Node: 14.15.1
OS: win32 x64
Angular: 11.0.9

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.7
@angular-devkit/build-angular   0.1100.7
@angular-devkit/core            11.0.7
@angular-devkit/schematics      11.0.7
@angular/cdk                    11.2.9
@angular/cli                    11.0.7
@angular/material               11.2.9
@schematics/angular             11.0.7
@schematics/update              0.1100.7
ng-packagr                      11.2.4
rxjs                            6.6.7
typescript                      4.0.7
```

**Comment by patelhr** [comment]
I also have same issue in my project. 
I do have images in lib/src/assets /a.jpg . Also in production its copied in dist/src/assets/a.jpg folder.
In lib component I am adding image like this `<img src="assets/a.jpg"/> or <img src="./src/assets/a.jpg"/>` but when I import this lib in other project outside angular workspace its giving me not found error.

lib/ng-packger.json
`{
  "$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
  "dest": "../../dist/form-renderer",
  "whitelistedNonPeerDependencies": ["@ionic/angular", "@ionic/core"],
  "lib": {
    "entryFile": "src/public-api.ts",
    "umdModuleIds": {
      "@ionic/angular": "@ionic/angular"
    }
  },
  "assets": ["./src/assets"]
}`

lib/someComponent.html
` <img src="./src/assets/a.jpg" />`

other HostProject lib loading like this
`<lib-example></lib-example>`

Note: Assets are getting copied in lib package so ng packager is working fine but why image is not loading that's strange . Tried different path also but its not working,

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `ng-packagr`.

If you are wondering why we don't resolve support issues via the issue tracker.

**Comment by Elikill58** [comment]
Hi,
Sorry, I finally find something to fix it @patelhr :
In `angular.json` you can add the `assets` section such as this :

```
{
  "projects": {
    "my-app": {
      "architect": {
        "build": {
          "options": {
            "assets": [
              "dist/my-lib/lib/js"
            ]
          }
        }
      }
    }
  }
}
```

It works for me !
