### ISSUE TITLE
Incorrect relative import path generated in a yarn monorepo

### ISSUE THREAD

**Issue by bdedov** [ng-packagr/ng-packagr#1949]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

We have a monorepo based on yarn workspaces comprising several subpackages. One of them contains shared services that can be used by the other subpackages. Every subpackage has its own `dist` folder and this cannot be changed due to various reasons. The issue occurs when:

- One of the other subpackages has a service using a service from the shared package as a dependency AND
- The consuming service is decorated with `@Injectable({ providedIn: "root" })`

The issue is reproducible only with the `providedIn: "root"` option set, otherwise `ngc` doesn't generate the `SomeService.ngInjectableDef = i0.ɵɵdefineInjectable(...)` part and the relevant imports causing the build error.

The shared service class is imported via a relative path in the generated code:

```typescript
import * as i1 from "../client/hello.service";
```

Building fails with the error:
```
------------------------------------------------------------------------------
Building entry point 'components'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
Bundling to FESM2015
ERROR: Could not resolve '../client/hello.service' from dist/esm2015/greetings.service.js
error Command failed with exit code 111.
```
#### How To Reproduce

A minimal reproduction is available in a git [repository](https://github.com/bdedov/ng-packagr-yarn-monorepo):

1. `git clone https://github.com/bdedov/ng-packagr-yarn-monorepo.git`
2. Install dependencies by running `$ yarn`
3. Build packages by running `$ yarn build`

#### Expected Behaviour

Import path is generated correctly and build runs through.

#### Version Information

```
node_modules/.bin/ng-packagr --version
ng-packagr:            5.7.1
@angular/compiler:     8.2.13
rollup:                1.25.2
tsickle:               
typescript:            3.5.3
```

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent version.
