### ISSUE TITLE
bug: `importHelpers: true` appears to be ignored

### ISSUE THREAD

**Issue by thefliik** [ng-packagr/ng-packagr#1957]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

Very sorry if this is user error, but it does not appear that `ng-packagr` is utilizing `tslib` when `importHelpers: true` exists in a `tsconfig.lib.json` file. 

#### How To Reproduce

Take my open source [`@service-work/is-loading` repo](https://gitlab.com/service-work/is-loading) as an example. The `is-loading` package lists `tslib` as a dependency in the [`package.json` file](https://gitlab.com/service-work/is-loading/-/blob/master/projects/is-loading/package.json) and [`tsconfig.lib.json` file](https://gitlab.com/service-work/is-loading/-/blob/master/projects/is-loading/tsconfig.lib.json) specifies `importHelpers: true` yet when building the library (using angular-cli) the import helpers are inlined into the build file and the `tslib` package is not used. You can look at the [published package contents here](https://www.runpkg.com/?@service-work/is-loading@5.1.2/bundles/service-work-is-loading.umd.js), and see inline definitions for `__assign`, `__extends`, etc.

I'm very sorry if I'm missing something obvious.

To repoduce:

1. Clone the `@service-work/is-loading` repo `git clone git@gitlab.com:service-work/is-loading.git`
2. Open it locally (a devcontainer is provided for easy setup in vscode)
3. Install the dependencies using `yarn install`
4. Run `yarn build`
5. Inspect the umd build output and see that `tslib` is not used.

_Note: this repo is using yarn workspaces_

#### Expected Behaviour

The typescript import helper functions are not inlined and instead are imported from `tslib`.

#### Version Information

The `@service-work/is-loading` library has the following version information:

```
ng-packagr:            10.1.2
@angular/compiler:     10.2.3
rollup:                2.33.1
typescript:            4.0.5
rxjs: 6.6.3
node: v12.20.0
yarn: 1.22.5
```

This being said, I first noticed this issue in a non-open-source repo with the following version information:

```
ng-packagr:            11.2.4
@angular/compiler:     11.2.11
rollup:                2.45.2
typescript:            4.0.7
rxjs                            6.6.3
node: v12.20.0
yarn: 1.22.5
```

**Comment by alan-agius4** [comment]
This is expected, tslib is always embedded in UMD bundles. 

The version of tslib is coupled with the version of typescript used to bundle a library, therefore in some cases you might need to include multiple tslib versions in your application.
