### ISSUE TITLE
Feature: Support dynamic imports

### ISSUE THREAD

**Issue by admosity** [ng-packagr/ng-packagr#1960]
## Type of Issue

```
[ ] Bug Report
[X] Feature Request
```

## Description

This builds on a lot of findings in #1285 and angular/angular-cli#6373. Many techniques were used from: https://github.com/vmcbaptista/ng-packagr-lazy-load/blob/master/projects/auth/src/lib/auth-routing.module.ts as well (thank you @vmcbaptista)

I had a need to support dynamic imports as we are creating widgets that are dynamically loaded based on configuration.

The [patch-package](https://github.com/ds300/patch-package) package was used to patch `ng-packagr@11.2.4` for the library project I'm working on (patch at the end of this issue). That patch detects when the the FESM build fails and updates the bundle configuration to write out to the directory instead. Following this, the UMD build is disabled when code splitting is detected.

Running the build against a project built in this way produces the following output on serve: 
![image](https://user-images.githubusercontent.com/4655972/116167836-25599100-a6cf-11eb-9792-03e02a47235c.png)

Dynamic imports as seen from ng serve:
![image](https://user-images.githubusercontent.com/4655972/116169675-40c69b00-a6d3-11eb-98e1-240ccfcbe2d7.png)

The correct file structure and references are created on a ng-packagr build:
![image](https://user-images.githubusercontent.com/4655972/116167933-5afe7a00-a6cf-11eb-8998-da75b6fce1d4.png)

Output from ng-packagr build with this patch:
![image](https://user-images.githubusercontent.com/4655972/116170392-bbdc8100-a6d4-11eb-85f6-27939174085b.png)

On a production build using the library built this way, the dynamic loading works and is bundled correctly:
![image](https://user-images.githubusercontent.com/4655972/116168994-b2054e80-a6d1-11eb-9e5a-e776eda69c7e.png)

IVY has no issues compiling:
![image](https://user-images.githubusercontent.com/4655972/116169788-81261900-a6d3-11eb-9ca7-49e5d1b43488.png)
![image](https://user-images.githubusercontent.com/4655972/116169859-a0bd4180-a6d3-11eb-8f28-0eba2ce7c482.png)

Other things of note, it looks like angular-cli is not looking to support other formats other than FESM anytime soon, so this seems to be a safe approach: 

angular/angular-cli/issues/10754
angular/angular-cli/pull/13650

Maybe this could be reused for ng-packagr/pull/1707 setting up the test.

#### How To Reproduce

Try to use a dynamic import and build produces this error (same as seen in #1285):
```
ERROR: When building multiple chunks, the "output.dir" option must be used, not "output.file". To inline dynamic imports, set the "inlineDynamicImports" option.
An unhandled exception occurred: When building multiple chunks, the "output.dir" option must be used, not "output.file". To inline dynamic imports, set the "inlineDynamicImports" option.
See "/private/var/folders/l0/_s3rrmmd5t1d4bwbpfl_ssqc0000gn/T/ng-VkjGy8/angular-errors.log" for further details.
```

#### Notes on how the files have to be organized

Dynamically loaded modules have to have all their angular symbols exported (all components, modules):
![image](https://user-images.githubusercontent.com/4655972/116170018-f1cd3580-a6d3-11eb-8027-ca65c92528f6.png)

`loadChildren` references can't use lambdas as this would be flagged by ng-packagr. This form of import provided by @vmcbaptista is used:
![image](https://user-images.githubusercontent.com/4655972/116170131-348f0d80-a6d4-11eb-9b38-631c1e8ab60f.png)

Needed to provide the `// @dynamic` flag on the module or this error appears:
![image](https://user-images.githubusercontent.com/4655972/116170256-78821280-a6d4-11eb-9055-c082d0792234.png)
![image](https://user-images.githubusercontent.com/4655972/116170331-918ac380-a6d4-11eb-9f60-b7798a7469f1.png)

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            11.2.4
@angular/compiler:     11.0.9
rollup:                2.45.2
typescript:            4.0.7
```

```
Angular CLI: 11.0.7
Node: 14.15.3
OS: darwin x64

Angular: 11.0.9
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, router, service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.7
@angular-devkit/build-angular   0.1100.7
@angular-devkit/core            11.0.7
@angular-devkit/schematics      11.0.7
@angular/cdk                    11.1.2
@angular/cli                    11.0.7
@angular/localize               11.2.11
@schematics/angular             11.0.7
@schematics/update              0.1100.7
ng-packagr                      11.2.4
rxjs                            6.5.5
typescript                      4.0.7
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/ng-packagr/lib/flatten/rollup.js b/node_modules/ng-packagr/lib/flatten/rollup.js
index 3b9d50d..a81efb1 100644
--- a/node_modules/ng-packagr/lib/flatten/rollup.js
+++ b/node_modules/ng-packagr/lib/flatten/rollup.js
@@ -9,6 +9,7 @@ const rollupJson = require("@rollup/plugin-json");
 const log = require("../utils/log");
 const external_module_id_strategy_1 = require("./external-module-id-strategy");
 const umd_module_id_strategy_1 = require("./umd-module-id-strategy");
+const path = require('path');
 /** Runs rollup over the given entry file, writes a bundle file. */
 async function rollupBundleFile(opts) {
     log.debug(`rollup (v${rollup.VERSION}) ${opts.entry} to ${opts.dest} (${opts.format})`);
@@ -47,16 +48,31 @@ async function rollupBundleFile(opts) {
         // see: https://github.com/angular/angular/pull/32069
         treeshake: false,
     });
-    // Output the bundle to disk
-    await bundle.write({
-        name: opts.moduleName,
-        format: opts.format,
-        amd: opts.amd,
-        file: opts.dest,
-        banner: '',
-        globals: moduleId => umd_module_id_strategy_1.umdModuleIdStrategy(moduleId, opts.umdModuleIds || {}),
-        sourcemap: true,
-    });
+    try {
+        // Output the bundle to disk
+        await bundle.write({
+            name: opts.moduleName,
+            format: opts.format,
+            amd: opts.amd,
+            file: opts.dest,
+            banner: '',
+            globals: moduleId => umd_module_id_strategy_1.umdModuleIdStrategy(moduleId, opts.umdModuleIds || {}),
+            sourcemap: true,
+      });
+    } catch (error) {
+        log.info(`Dynamic imports detected in ${opts.moduleName}`);
+
+        // Output the bundle to disk
+        await bundle.write({
+            name: opts.moduleName,
+            format: opts.format,
+            amd: opts.amd,
+            dir: path.dirname(opts.dest),
+            banner: '',
+            globals: moduleId => umd_module_id_strategy_1.umdModuleIdStrategy(moduleId, opts.umdModuleIds || {}),
+            sourcemap: true,
+      });
+    }
     return bundle.cache;
 }
 exports.rollupBundleFile = rollupBundleFile;
diff --git a/node_modules/ng-packagr/lib/ng-package/entry-point/write-bundles.transform.js b/node_modules/ng-packagr/lib/ng-package/entry-point/write-bundles.transform.js
index ecb19da..cc07221 100644
--- a/node_modules/ng-packagr/lib/ng-package/entry-point/write-bundles.transform.js
+++ b/node_modules/ng-packagr/lib/ng-package/entry-point/write-bundles.transform.js
@@ -38,6 +38,7 @@ exports.writeBundlesTransform = transform_1.transformFromPromise(async (graph) =
     });
     try {
         spinner.start('Bundling to FESM2015');
+
         cache.rollupFESMCache = await rollup_1.rollupBundleFile({
             ...opts,
             moduleName: ngEntryPoint.moduleId,
@@ -46,19 +47,23 @@ exports.writeBundlesTransform = transform_1.transformFromPromise(async (graph) =
             cache: cache.rollupFESMCache,
         });
         spinner.succeed();
-        spinner.start('Bundling to UMD');
-        cache.rollupUMDCache = await rollup_1.rollupBundleFile({
-            ...opts,
-            moduleName: ngEntryPoint.umdId,
-            entry: esm2015,
-            format: 'umd',
-            dest: umd,
-            cache: cache.rollupUMDCache,
-            transform: downlevel_plugin_1.downlevelCodeWithTsc,
-        });
-        spinner.succeed();
-        spinner.start('Minifying UMD bundle');
-        await uglify_1.minifyJsFile(umd, umdMinified);
+        try {
+            spinner.start('Bundling to UMD');
+            cache.rollupUMDCache = await rollup_1.rollupBundleFile({
+                ...opts,
+                moduleName: ngEntryPoint.umdId,
+                entry: esm2015,
+                format: 'umd',
+                dest: umd,
+                cache: cache.rollupUMDCache,
+                transform: downlevel_plugin_1.downlevelCodeWithTsc,
+            });
+            spinner.succeed();
+            spinner.start('Minifying UMD bundle');
+            await uglify_1.minifyJsFile(umd, umdMinified);
+        } catch (error) {
+          spinner.info('Skipping UMD build for code splitting build.');
+        }
         spinner.succeed();
     }
     catch (error) {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by alan-agius4** [comment]
Hi, 

Thanks for this request.

Libraries shouldn't contain any lazy-loaded module or routing. These are the responsibility of the application.

See: https://github.com/angular/angular/issues/31893#issuecomment-516615243 and https://github.com/angular/angular-cli/issues/6373

**Comment by alan-agius4** [comment]
Hi, 

Thanks for this request.

Libraries shouldn't contain any lazy-loaded module or routing. These are the responsibility of the application.

See: https://github.com/angular/angular/issues/31893#issuecomment-516615243 and https://github.com/angular/angular-cli/issues/6373

**Comment by alan-agius4** [comment]
Hi, 

Thanks for this request.

Libraries shouldn't contain any lazy-loaded module or routing. These are the responsibility of the application.

See: https://github.com/angular/angular/issues/31893#issuecomment-516615243 and https://github.com/angular/angular-cli/issues/6373
