### ISSUE TITLE
v12.0.0-rc.2 fails silently on step "Compiling TypeScript sources through NGC"

### ISSUE THREAD

**Issue by e-oz** [ng-packagr/ng-packagr#1975]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

While 12.0.0-rc.1 runs fine, 12.0.0-rc.2 fails (node crashes, I suppose - process disappears from Task Manager).

#### How To Reproduce

I know that such a description will not let you find and fix the issue, so please let me know how can I  turn on some "verbose mode" or logging to give you more details.

#### Version Information

```
ng-packagr: 12.0.0-rc.2
@angular/*: 12.0.0-rc.2
typescript: 4.2.4
rxjs: 7.0.0
node: 14.6.1
npm/yarn: yarn 1.22.10, same result with npm 7.11.2
Windows 10 x64
```

**Comment by alan-agius4** [comment]
Closed via https://github.com/ng-packagr/ng-packagr/pull/1976

Please try RC3

**Comment by e-oz** [comment]
Works great! Thank you.
