### ISSUE TITLE
[SECURITY AUDIT FAILURE] - PostCss

### ISSUE THREAD

**Issue by pl4yradam** [ng-packagr/ng-packagr#1977]
## Type of Issue

```
[ X ] Bug Report
[ ] Feature Request
```

## Description
Manual Review 
Some vulnerabilities require your attention to resolve  
Visit https://go.npm.me/audit-guide for additional guidance        
Moderate: Regular Expression Denial of Service                         
Package: Postcss 
Patched: in >=8.2.10     
Dependency of:  @angular-devkit/build-angular [dev]     
Path @angular-devkit/build-angular: > resolve-url-loader > postcss 
More info:  https://npmjs.com/advisories/1693

**Comment by alan-agius4** [comment]
Duplicate of https://github.com/angular/angular-cli/issues/20747
