### ISSUE TITLE
Update postcss to 8.2.10 or higher

### ISSUE THREAD

**Issue by rabraghib** [ng-packagr/ng-packagr#1980]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

Update `postcss` for vulnerabilities purposes https://npmjs.com/advisories/1693

**Comment by SchnWalter** [comment]
Dupe of #1977 and others, please run a quick search before posting something.

**Comment by rabraghib** [comment]
Its closed & I only search in open issues
already saw the one from angular cli but is ng-packagr a sub project of it ??

**Comment by rabraghib** [comment]
@SchnWalter ??

**Comment by SchnWalter** [comment]
It's a breaking change, so you need to update to Angular 12, which was release a few days ago.

**Comment by rabraghib** [comment]
I am using v12 of angular & It steal not updated

**Comment by rabraghib** [comment]
@SchnWalter maybe this is related https://github.com/angular/angular-cli/issues/20795

**Comment by alan-agius4** [comment]
Closing as postcss released a security fix in
