### ISSUE TITLE
CSS processing errors are silent, hidden the issue from the user

### ISSUE THREAD

**Issue by shlomiassaf** [ng-packagr/ng-packagr#1983]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description

When processing CSS, SCSS etc, if there is an error, it is not displayed to the user.

https://github.com/ng-packagr/ng-packagr/blob/c2efc42591ea8f2581cb7c8d3ea16a6b9cfa526e/src/lib/styles/stylesheet-processor.ts#L71

For example, I had an invalid `browser-list` configuration.
The real error was `Unknown version 88 of edge`

However, in the console I got:

```
✖ Compiling TypeScript sources through NGC
ERROR: my-component.component.ts:59:16 - error NG2008: Could not find stylesheet file 'my-component.component.scss'.

59   styleUrls: [ 'my-component.component.scss' ],
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

my-component.component.ts:59:16 - error NG2008: Could not find stylesheet file 'my-component.component.scss'.

59   styleUrls: [ 'my-component.component.scss' ],
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

The does not provide proper information, and is misleading since the SCSS file is there... which is confusing.

#### Expected Behaviour

Proper error shown

#### Version Information

```
ng-packagr:            12.0.0
@angular/compiler:     12.0.0
rollup:                2.48.0
typescript:            4.2.4
```

**Comment by Bartoszkolodziejczak** [comment]
I have similar issue. Temporary workaround is downgrade ng-packagr

**Comment by mmuenker** [comment]
I have the same issue. But a downgrade to 11.2.4 does not resolve the issue. It is required to downgrade to 11.1.4

@angular/compiler: 12.0.1
typescript: 4.2.4

**Comment by shlomiassaf** [comment]
It's a bug in the new **ivy** compiler webpack plugin.

That plugin is used when ivy is enabled in V11, but in V12 it's no longer there so its how it behaves.

**Comment by DenysVuika** [comment]
This is a blocker for our large project upgrade so far. Hundreds of `Could not find stylesheet file` errors and nothing compiles. Downgrading does not help. Any ETA on when this problem is going to be fixed?
