### ISSUE TITLE
Karma tests fail when library entry points have dependencies between them

### ISSUE THREAD

**Issue by andreirogobete** [ng-packagr/ng-packagr#1989]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I have created an Angular library which contains 2 entry points, as follows:

- my-lib/common
- my-lib

"my-lib/common" exports an interface called "Model" that is used by a component inside the original entry point (my-lib).

I am able to fully build the library by running `ng build my-lib --prod` as expected.

However, I get an error stating that the "Model" class cannot be found when running karma tests via `ng test my-lib`.

I'm not sure at this point whether this is a karma bug or not but it looks like the compilation is problematic

#### How To Reproduce

I've created a repository where the issue can be reproduced: <https://github.com/andreirogobete/bug-ng-packagr.git>

To reproduce:

- run `npm install`
- run `ng test my-lib` and notice the console error

The issue is located in `projects/my-lib/src/lib/my-lib.component.ts` because the import at line 2 cannot be resolved:

```JavaScript
import { IModel } from 'my-lib/common'
```

#### Expected Behaviour

Karma tests should run and pass without import errors

#### Version Information

```
$ node_modules/.bin/ng-packagr --version

ng-packagr:            11.2.4
@angular/compiler:     11.2.14
rollup:                2.38.4
typescript:            4.1.5
rxjs:                  6.6.7
```

**Comment by alan-agius4** [comment]
It looks like you are not adding the secondary entry-point in your path mappings
https://github.com/andreirogobete/bug-ng-packagr/blob/cf807bc1600d9976810e8a95426b664b90414483/tsconfig.json#L15-L18

```
"my-lib/common": [
  "dist/my-lib/my-lib/common",
  "dist/my-lib/common",
  "projects/my-lib/common/public-api.ts"
 ]
```

**Comment by andreirogobete** [comment]
Thanks, that worked fine :)
