### ISSUE TITLE
StylePreproccessor error with /deep/ in css

### ISSUE THREAD

**Issue by fnnzzz** [ng-packagr/ng-packagr#1990]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

_I'm getting an error on some css with a error message `Unclosed comment in stylesheet file`_
_CSS looks like this_

<img width="346" alt="image" src="https://user-images.githubusercontent.com/3502507/119648524-3ca0b100-be2a-11eb-9864-d27af9e28e22.png">

_I suspect the preprocessor is treating /deep/ as an unclosed comment. (if you delete it, then everything works correctly)_

#### How To Reproduce

- _add to css /deep/_ and run build

#### Version Information

```
ng-packagr: 12.0.2
"@angular/animations": "12.0.1",
"@angular/cdk": "^12.0.1",
"@angular/common": "12.0.1",
"@angular/compiler": "12.0.1",
"@angular/core": "12.0.1",
"@angular/elements": "12.0.1",
"@angular/fire": "^6.1.5",
"@angular/forms": "12.0.1",
"@angular/material": "^12.0.1",
"@angular/material-moment-adapter": "^12.0.1",
"@angular/platform-browser": "12.0.1",
"@angular/platform-browser-dynamic": "12.0.1",
"@angular/platform-server": "^12.0.1",
"@angular/router": "12.0.1",
typescript: 4.2.4
rxjs: 7.0.1
node: 14.16.1
yarn: 1.22.5
```

**Comment by fnnzzz** [comment]
After changed `/deep` to `::ng-deep` a build passed.


https://angular.io/guide/component-styles
>The /deep/ combinator also has the aliases >>>, and ::ng-deep.

**Comment by fnnzzz** [comment]
**UPD:**
https://github.com/angular/angular/pull/42214
I noticed that the angular team is preparing a migration for `/deep/`, so maybe it's just a matter of time

**Comment by SchnWalter** [comment]
Actually, both versions are deprecated: https://angular.io/guide/deprecations#deep-component-style-selector and should be avoided.

**Comment by alan-agius4** [comment]
Closing since `/deep/` is no longer supported by the underlying tooling.

Please use `::ng-deep` instead.
