### ISSUE TITLE
bug: SASS being compiled as CSS

### ISSUE THREAD

**Issue by matheo** [ng-packagr/ng-packagr#1993]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

After upgrading [this](https://github.com/matheo/angular/tree/12.0.x) NX monorepo and NG to `v12`,
and updating the SASS styles to the new modules
the compilation of the `datepicker` library is broken with a weird issue:

![image](https://user-images.githubusercontent.com/260185/119929414-115db500-bf43-11eb-8840-778e91ad87f2.png)

#### How To Reproduce

1. Clone and yarn install the `12.0.x` branch: https://github.com/matheo/angular/tree/12.0.x
2. Execute `yarn build datepicker`

#### Expected Behaviour

Successful compilation of the `datepicker` library because the SASS code seems valid.

#### Version Information

```
ng-packagr:            12.0.2
@angular/compiler:     12.0.2
rollup:                2.50.2
typescript:            4.2.4
rxjs: 6.6.7
node: 12.18.3
yarn: 1.22.5
```

**Comment by alan-agius4** [comment]
Hi @matheo,

While I wasn’t looked into the repo yet because of I didn’t have time yet.

Typically these errors occur when SCSS generates invalid CSS.

That said, I’ll take a look at the reproduction in the coming days.

**Comment by alan-agius4** [comment]
It looks like you are using `node-sass` which doesn't support Sass module system and its support is deprecated.

Remove `node-sass` from `devDependencies`.

**Comment by matheo** [comment]
Ouch! I forgot that detail. TYVM @alan-agius4!
