### ISSUE TITLE
Generated code for built library is faulty

### ISSUE THREAD

**Issue by redvp** [ng-packagr/ng-packagr#2000]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

Building a library with Ivy either disabled or enabled results in wrong generated code.

```
function _interopNamespace(e) {
        if (e && e.__esModule) return e;
        var n = Object.create(null);
        if (e) {
            Object.keys(e).forEach(function (k) {
                if (k !== 'default') {
                    var d = Object.getOwnPropertyDescriptor(e, k);
                    Object.defineProperty(n, k, d.get ? d : {
                        enumerable: true,
                        get: function () {
                            return e[k];
                        }
                    });
                }
            });
        }
        n['default'] = e; // <----- set default property
        return Object.freeze(n);
}

var i0__namespace = /*#__PURE__*/_interopNamespace(i0);
    
// namespace called without default property
ModuleaService.ɵprov = i0__namespace.ɵɵdefineInjectable(...);
```

#### How To Reproduce

Minimal reproduction is available [here](https://github.com/redvp/ngplugins) projects/ngpluginsrepro is an app that loads the generated modules from the projects/plugins workspace. Generated modules are included into the app's assets.
You will find 2 working examples in the app's assets, modulea.umd.js and moduleb.umd.js. However, I cannot build the modules anymore. (Reverting to [this commit](ec1b97241453f265b934e6ae68306c93298d8318) and reinstalling node_modules doesn't help).

#### Expected Behaviour

I cannot explain the inconsistency, but I used to be able to build the libraries. The ngpluginsrepro app would then load these modules at runtime and compile them as Angular modules (also includes lazy-loading and routing to these modules).

#### Version Information

```
ng-packagr: 10.1.2
@angular/*: 10.1.6
typescript: 4.0.7
rxjs: 6.6.7
node: 12.18.3
npm/yarn: 6.14.6 / 1.22.10
```

**Comment by alan-agius4** [comment]
Can you check if the problem still persists in version 12?

Note: UMD bundles are deprecated and will be removed in the future.

**Comment by redvp** [comment]
This problem still persists in version 12.

```
ng-packagr:            12.0.4
@angular/compiler:     12.0.3
rollup:                2.51.1
typescript:            4.2.4
```

**Comment by JoostK** [comment]
So what's wrong here exactly?

**Comment by redvp** [comment]
UMD bundles generated from the projects/plugins workspace (and inserted as assets into the projects/ngpluginsrepro app) are no longer loaded by systemjs.

![image](https://user-images.githubusercontent.com/46999554/121348909-367dfa80-c929-11eb-9c81-9dc0b6ff8f95.png)

Using ``` systemjs: 0.21.6 ```

I suspected it was a problem with ng-packagr (initial description) but to be perfectly honest I'm not sure... Any pointers are greatly appreciated.

**Comment by ratatoeskr666** [comment]
Shouldn't this be disabled when setting 
`"esModuleInterop": false` in compilerOptions in tsconfig.json? 

I'm using Angular 10.2.4 and I'm also unable to import my *.umd.js file via SystemJS because of this error.
Setting esModuleInterop to false doesn't make any difference. 
At this point, i have to replace this line in the built umd file:
` var i0__namespace = /*#__PURE__*/_interopNamespace(i0);`
with this:
` var i0__namespace = i0;`

**Comment by redvp** [comment]
Thank you @ratatoeskr666 for making me get back into this. 

After some more testing, some clarification is needed.

Using Angular 9, UMD modules are built and loaded by SystemJS without any issues (whether Ivy is enabled or not when building).
Whereas using Angular 10 and up, there are different results.

- **Disabling Ivy and using the interopNamespace** leads to `Cannot read property 'ɵɵdefineInjectable' of undefined` above.
- **Enabling Ivy and using the interopNamespace** also leads to `Cannot read property 'ɵɵdefineInjectable' of undefined` above.
- **Disabling Ivy and removing the interopNamespace** leads to Angular compiler error `Cannot read property 'declarations' of null` 
![image](https://user-images.githubusercontent.com/46999554/123847531-fbaf2700-d916-11eb-8eeb-1c813d006f4b.png)

- **Enabling Ivy and removing the interopNamespace** does work as intended as @ratatoeskr666 mentioned.

I can confirm that `"esModuleInterop": false` does not help.

Added branches with ng9 and ng10 configs on my [repo](https://github.com/redvp/ngplugins).
