### ISSUE TITLE
Make downleveling of code from ES2015 to ES5 optional when generating UMD bundles

### ISSUE THREAD

**Issue by ajaykrishnan33** [ng-packagr/ng-packagr#2004]
## Type of Issue

```
[ ] Bug Report
[X] Feature Request
```

## Description

I want to use ES2015 UMD bundles along with the ES2015 version of Angular. These libraries are loaded at runtime using SystemJS in the browser.

Currently, the generated UMD bundles are automatically transpiled to ES5. This results in errors in libraries which have classes that are extending ES2015 classes coming from other libraries that are loaded at runtime.

**Feature request**: Add a configuration parameter to make it optional to transpile from ES2015 to ES5.

**Some details regarding my specific usecase:**
I am using [single-spa](https://single-spa.js.org/) with multiple Angular applications and am trying to share the same angular libraries between all of the applications.

Am using Angular 11 with Ivy, and wanted to use the ES2015 version of the library. Currently, when using the UMD version of the `single-spa-angular` library (generated with ng-packagr) with this, it throws an error, since an ES5 class in that library is trying to extend an ES2015 class from Angular.

The exact details of the error have been captured here: https://github.com/single-spa/single-spa-angular/issues/370

Additional investigation here: https://github.com/single-spa/single-spa-angular/issues/370#issuecomment-859545789

#### Expected Behaviour

The source code in ng-packagr relevant to this is: 

1. https://github.com/ng-packagr/ng-packagr/blob/6e22549aa32ffe43ca8a12e120fcdc4c0e89e63d/src/lib/ng-package/entry-point/write-bundles.transform.ts#L65

![image](https://user-images.githubusercontent.com/8767512/121707299-0a62a500-caf4-11eb-8d64-2cdf17332980.png)

2. https://github.com/ng-packagr/ng-packagr/blob/6e22549aa32ffe43ca8a12e120fcdc4c0e89e63d/src/lib/flatten/downlevel-plugin.ts#L25

![image](https://user-images.githubusercontent.com/8767512/121707345-164e6700-caf4-11eb-94ab-b82a3acfb35c.png)

This seems to be explicitly transpiling the ES2015 UMD bundle to ES5. This could be made optional.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 11.2.4
@angular/compiler: 11.2.3
typescript: 4.0.5
rollup: 2.40.0
node: v12.22.1
npm: 7.16.0
```

**Comment by JoostK** [comment]
This is very unlikely to change. Angular tooling (ngcc in particular) relies on UMD being ES5. As you mentioned in https://github.com/single-spa/single-spa-angular/issues/370#issuecomment-859545789 there have indeed been hints at the removal of UMD bundles from the Angular Package Format entirely, but there's no concrete planning for when this may happen.

Have you considered going the opposite route, where ES2015 code is downleveled to ES5?

**Comment by ajaykrishnan33** [comment]
Thanks for your reply @JoostK ! 

In my usecase, I wouldn't be needing to have the single-spa-angular library UMD bundle again being passed through ngcc, since I will be loading the module dynamically into the browser at runtime. I realise that this will not be the standard usecase, but would it be possible to maintain the default behaviour the same as it is right now, but just provide some flag or config option to override for people like me with a similar usecase? I am happy to work on a PR for this if that works for the maintainers.

I did consider downlevelling all code to ES5, but I believe that it will significantly increase my bundle size since I have multiple large angular applications in production. Also, I am running the code exclusively in an ES2015 execution environment so it feels like I am potentially leaving some performance improvements on the table by moving to ES5. (Note: I might be dead wrong about this, please feel free to correct me!)

Is there any other alternative way that I could achieve this with ES2015 itself? Would be a great help!

**Fundamental doubt:** Even if there is no problem with Angular tooling itself, is it a bad idea to stick with this approach (of ES2015 UMD bundles)? Would I run into some unexpected issues?

Thanks in advance!

**Comment by alan-agius4** [comment]
Drive by comment, my-packagr follows the APF specs which implies that UMDs should be in ES5 format.

Including an option that allows UMDs to contain ES2015, is not on the table for 2 main reasons. Firstly because this goes against the spec and secondary because UMD format will likely be dropped in the near future.

**Comment by ajaykrishnan33** [comment]
@alan-agius4 Thanks for your reply. Is there any clean way that I can do something like this just for my own project? Ideally without having to fork the repo entirely?

**Comment by alan-agius4** [comment]
@ajaykrishnan33, not without a custom build pipeline. That said, I would strongly suggest to move away from UMD bundles.

Closing since changed UMDs to contain ES2015 is not part of the APF spec.
