### ISSUE TITLE
Building library in the node_modules folder

### ISSUE THREAD

**Issue by kryshac** [ng-packagr/ng-packagr#2005]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

the same issue that was created here #1635 

#### How To Reproduce
```bash
ng new example-workspace --createApplication=false
...
cd example-workspace
ng g lib example-lib
...
ng g app example-app
...
ng build example-app
⠋ Generating browser application bundles (phase: setup)...Compiling @angular/core : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
✔ Browser application bundle generation complete.
✔ Copying assets complete.
✔ Index html generation complete.

Initial Chunk Files               | Names         |      Size
main.0269233762bca8b97745.js      | main          |  65.65 kB
polyfills.71710c1bb70c21ce05f9.js | polyfills     |  35.96 kB
runtime.5e9671802f9984a7370d.js   | runtime       |   1.02 kB
styles.31d6cfe0d16ae931b73c.css   | styles        |   0 bytes

                                  | Initial Total | 102.63 kB

Build at: 2021-06-13T22:31:06.741Z - Hash: 274b099bb8150898c634 - Time: 17160ms

ng build example-lib
Building Angular Package

------------------------------------------------------------------------------
Building entry point 'example-lib'
------------------------------------------------------------------------------
✔ Compiling TypeScript sources through NGC
✖ Bundling to FESM2015
ERROR: Could not resolve './lib/example-lib.service' from dist/example-lib/esm2015/public-api.js
An unhandled exception occurred: Could not resolve './lib/example-lib.service' from dist/example-lib/esm2015/public-api.js
See "/tmp/ng-FJJ26J/angular-errors.log" for further details.

cat /tmp/ng-FJJ26J/angular-errors.log
[error] Error: Could not resolve './lib/example-lib.service' from dist/example-lib/esm2015/public-api.js
    at error (/home/user/work/angular/node_modules/example-workspace/node_modules/rollup/dist/shared/rollup.js:7917:30)
    at ModuleLoader.handleResolveId (/home/user/work/angular/node_modules/example-workspace/node_modules/rollup/dist/shared/rollup.js:19602:24)
    at /home/user/work/angular/node_modules/example-workspace/node_modules/rollup/dist/shared/rollup.js:19551:22
    at async Promise.all (index 0)
    at async ModuleLoader.fetchStaticDependencies (/home/user/work/angular/node_modules/example-workspace/node_modules/rollup/dist/shared/rollup.js:19549:34)
    at async Promise.all (index 0)
    at async ModuleLoader.fetchModule (/home/user/work/angular/node_modules/example-workspace/node_modules/rollup/dist/shared/rollup.js:19525:9)
    at async Promise.all (index 0)
    at async ModuleLoader.fetchStaticDependencies (/home/user/work/angular/node_modules/example-workspace/node_modules/rollup/dist/shared/rollup.js:19549:34)
    at async Promise.all (index 0)
```

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            12.0.5
@angular/compiler:     12.0.4
rollup:                2.51.2
typescript:            4.2.4
```

**Comment by alan-agius4** [comment]
In general, I suggest that you don't name a directory `node_modules`. `node_modules` is a special directory which should be used by package managers. Several tools handles `node_modules` in a special way because it is expected to be managed by package managers.

**Comment by kryshac** [comment]
the problem is when i install a package directly from git and i want to build package with the postinstall script

**Comment by alan-agius4** [comment]
> the problem is when i install a package directly from git and i want to build package with the postinstall script

Not following what this has to do with the directory naming.

**Comment by kryshac** [comment]
> > the problem is when i install a package directly from git and i want to build package with the postinstall script
> 
> Not following what this has to do with the directory naming.




```
my-project
└── node_modules
    └── my-workspace -> from github repo
```

```
     package.json
     {
        "scripts": {
           "postinstall": "ng build my-lib"
        }
     }
```

**Comment by alan-agius4** [comment]
I don’t see the reason why node_modules is needed for the above to work.

**Comment by kryshac** [comment]
this is package.json from root project:
```
{
  "name": "project",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~10.1.2",
    "@angular/common": "~10.1.2",
    "@angular/compiler": "~10.1.2",
    "@angular/core": "~10.1.2",
    "@angular/forms": "~10.1.2",
    "@angular/platform-browser": "~10.1.2",
    "@angular/platform-browser-dynamic": "~10.1.2",
    "@angular/router": "~10.1.2",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2",
    "@libs/core": "git+ssh://git@github.com/company/libs.git"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1001.7",
    "@angular/cli": "~10.1.2",
    "@angular/compiler-cli": "~10.1.2",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "ng-packagr": "^10.1.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2"
  }
}

```

and this is package.json from https://github.com/example/libs.git
```
{
  "name": "libs",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "postinstall": "ng build example-lib"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~10.1.2",
    "@angular/common": "~10.1.2",
    "@angular/compiler": "~10.1.2",
    "@angular/core": "~10.1.2",
    "@angular/forms": "~10.1.2",
    "@angular/platform-browser": "~10.1.2",
    "@angular/platform-browser-dynamic": "~10.1.2",
    "@angular/router": "~10.1.2",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1001.7",
    "@angular/cli": "~10.1.2",
    "@angular/compiler-cli": "~10.1.2",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "ng-packagr": "^10.1.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2"
  }
}
```

and when I run the `npm install` command in the root folder I get this error:
```
------------------------------------------------------------------------------
Building entry point 'example-lib'
------------------------------------------------------------------------------
✔ Compiling TypeScript sources through NGC
✖ Bundling to FESM2015
ERROR: Could not resolve './lib/example-lib.service' from dist/example-lib/esm2015/public-api.js
An unhandled exception occurred: Could not resolve './lib/example-lib.service' from dist/example-lib/esm2015/public-api.js
See "/tmp/ng-FJJ26J/angular-errors.log" for further details.
```

**Comment by SchnWalter** [comment]
@kryshac, you should not generate or clone angular workspaces inside the `node_modules` of another project, if you are trying to have a separate project use your library during development in a project outside the workspace, you can use `npm link`, or just run `npm install --no-save BUILD_PATH` with a relative path to the build directory of your library. -- just make sure that your `architect.build.options` of the project consuming these generated symbolic links contain: `"preserveSymlinks": true`

P.S. you are indeed right, if you generate or clone an Angular library inside the `node_modules` of an existing project, it will fail with the error you've provided, but yeah there are many reasons you should not do this. Also, if the symbolic links don'twork for you, you should go to one of the many questions websites (like S.O.), this if for bugs and feature requests.

**Comment by kryshac** [comment]
> @kryshac, you should not generate or clone angular workspaces inside the `node_modules` of another project, if you are trying to have a project outside of the workspace consume your library during development, you can use `npm link` to the build output (where the generated `package.json` lives). Or you could just run `npm install --no-save BUILD_PATH` with a relative path to the the same output directory, but it will work only if you set the `architect.build.options.preserveSymlinks` to true, this is needed for to fix `node_module` resolution inside the project that consumes your library via a symbolic link.
> 
> P.S. you are indeed right, if you generate or clone an Angular library inside the `node_modules` of an existing project, it will fail with the error you've provided, but yeah there are many reasons you should not do this. Also, if the symbolic links don'twork for you, you should go to one of the many questions websites (like S.O.), this if for bugs and feature requests.

I know symbolic connections, but it's complicated when several people work on the same project to do this. our problem now is that we can't publish lib on npm the only solution is to push the dist on git

**Comment by SchnWalter** [comment]
Well that's not an `ng-packagr` issue, that is your issue, and it's "links", not "connections".

Please close this issue, there's nothing more we the `ng-packagr` community can help you with, since module resolution is not something to mess with.

P.S. I home you do realize that your are using your workspace `package.json`.

**Comment by kryshac** [comment]
Somewhere anyway there is a problem with how to read the data because if I build an application there is no problem, but we can close the issue

**Comment by dnedelko** [comment]
@kryshac how did you solve that issue? I have the same

**Comment by kryshac** [comment]
@dnedelko unfortunately not, I put the dist folder on my git
