### ISSUE TITLE
Sourcemaps are broken in case of using templateUrl

### ISSUE THREAD

**Issue by Norby125** [ng-packagr/ng-packagr#2017]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description

I'm a bit unsure if this is really a bug with ng-packagr, but any help would be really appreciated. Whenever I try to use templateUrl in an angular library that is being built by ng-packagr, I loose my sourcemaps in devtools.

#### How To Reproduce

_A bug: I created a github repo which you can find here: https://github.com/Norby125/LibExportTest2
Repro steps: clone repo, npm install, build my-lib, use npm link on the outcome of the build, start the application

#### Expected Behaviour

Regardless I'm using templateUrl or template, source maps should not be broken.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 12.1.0
@angular/*: 12.1.0
typescript: 4.3.2
rxjs: 6.6.0
node: 14.17.0
npm/yarn: 6.14.13
```

**Comment by alan-agius4** [comment]
Duplicate of https://github.com/angular/angular-cli/issues/21271

**Comment by Norby125** [comment]
@alan-agius4 Thanks for taking time. Yep, definitely it is an issue with angular CLI. Sourcemaps are back when I use compilationMode "full". Closing the issue.
