### ISSUE TITLE
Copy assets feature for sub-packages

### ISSUE THREAD

**Issue by SuperITMan** [ng-packagr/ng-packagr#2030]
## Type of Issue

```
[ ] Bug Report
[X] Feature Request
```

## Description

In ng-packagr 12, we are able to configure assets to copy in "ng-package.json" at the root of the project.

It could be interesting to have the same behavior for subpackages ([Secondary Entry Points](https://github.com/ng-packagr/ng-packagr/blob/master/docs/secondary-entrypoints.md)). 

Currently, I have the following configuration in my project:

"./ng-package.json":
```json
{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "assets": ["./assets", "./testing/**/*.md"],
}
```

#### Expected Behaviour

Providing support for assets in subpackages would allow to have the following configs:

"./ng-package.json":
```json
{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "assets": ["./assets"],
}
```

"./testing/ng-package.json":
```json
{
  "$schema": "../node_modules/ng-packagr/ng-package.schema.json",
  "assets": ["./src/*.md"],
}
```

I didn't have a look on a possible implement yet. If it seems a good idea for you, I can create a PR in the next days.

Thanks in advance for your feedback 👍

**Comment by alan-agius4** [comment]
Thanks for this request.

However, there hasn't been much interest in this from the community since this issue has been opened. 

Hence, unless things change I don't think that this warrants to be included as part of the public API. 

Thanks again.
