### ISSUE TITLE
docs: alternative to package.json doesn't work

### ISSUE THREAD

**Issue by snebjorn** [ng-packagr/ng-packagr#2032]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

The docs suggests to use ng-package instead of package.json to fix linting errors.
https://github.com/ng-packagr/ng-packagr/blob/master/docs/secondary-entrypoints.md#alternative-to-packagejson

While this fixes the linting issue. It breaks the build.

#### How To Reproduce

1. Make a library with a secondary entrypoint
2. use ng-package.json instead of package.json
3. add a peerDependencies property to it

```
// ng-package.json
{
  "$schema": "../../../node_modules/ng-packagr/ng-package.schema.json",
  "lib": {
    "entryFile": "src/public-api.ts"
  },
  "peerDependencies": {
    "@angular/core": "latest",
  }
}
```
4. build your library `ng build`
5. observe this error
> ❯ ng build
Building Angular Package
Configuration doesn't match the required schema.
Data path "" must NOT have additional properties (peerDependencies).

#### Expected Behaviour

It should build.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            12.1.2
@angular/compiler:     12.1.2
@angular/cli:          12.1.2
rollup:                2.53.1
typescript:            4.3.5
node:                  14.15.1
npm:                   7.20.0
```

**Comment by SchnWalter** [comment]
Dependencies can only be defined in the `package.json` of the primary entry point, package managers don't care about your secondary entry points.

**Comment by alan-agius4** [comment]
Closing as per above.

**Comment by snebjorn** [comment]
I see. I'm assuming the solution is to use the peerDependenciesMeta then.

```json
{
  "peerDependencies": {
    "@angular/core": "latest"
  },
  "peerDependenciesMeta": {
    "@angular/core": {
      "optional": true
    }
  }
}
```

**Comment by alan-agius4** [comment]
I doubt that `@angular/core` is optional. Which lint rules are using?

**Comment by snebjorn** [comment]
I used `@angular/core` as an example it's not my actual dependency :)

**Comment by alan-agius4** [comment]
If indeed the package is optional you can indeed use peerDependenciesMeta.

**Comment by snebjorn** [comment]
I have the following setup

```
root
├── projects/
│   ├── my-lib/
│   │   ├── sub-lib/
│   │   │   ├── lib/
│   │   │   ├── ng-package.json // secondary entry - requires @scope/other
│   │   ├── src/
│   │   │   ├── lib/
│   │   │   ├── ng-package.json
│   │   │   ├── package.json // main entry - requires @angular/
```

```jsonc
// main package.json
{
  "peerDependencies": {
    "@angular/common": "latest",
    "@angular/core": "latest",
    "@scope/other": "latest",
  },
  "peerDependenciesMeta": {
    "@scope/other": {
      "optional": true
    }
  }
}
```
