### ISSUE TITLE
npm i ng-packagr@12.2.0 -D failed 

### ISSUE THREAD

**Issue by jucasoft** [ng-packagr/ng-packagr#2039]
## Type of Issue

```
[ X] Bug Report
[ ] Feature Request
```

## Description

bug: npm i ng-packagr@12.2.0 -D command failed 

#### How To Reproduce

bug: 
new angular-12 project
```
ng new ng12
```
ng-packagr installation
```
$ npm i ng-packagr@12.2.0 -D
npm ERR! code 1
npm ERR! path /....../VCS/ng12/node_modules/esbuild
npm ERR! command failed
npm ERR! command sh -c node install.js

npm ERR! A complete log of this run can be found in:
npm ERR!     ....../.npm/_logs/2021-08-04T10_14_18_343Z-debug.log
```
if the older version is installed, it works
```
npm i ng-packagr@12.1.2 -D
```

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 12.2.0
@angular/*: 12.1.0
typescript: ~4.3.2
rxjs: ~6.6.0
node: v16.6.1
npm/yarn: 7.20.3npde 
```

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with ng-packagr.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.

**Comment by jucasoft** [comment]
why if i install the previous version i have no errors?
npm i ng-packagr@12.1.2 -D

I'm using
node: v16.6.1
npm / yarn: 7.20.3

do i have to use different versions?
