### ISSUE TITLE
Note that you need plugins to import files that are not JavaScript

### ISSUE THREAD

**Issue by SmallShrimp** [ng-packagr/ng-packagr#2044]
## Type of Issue

```
[ ] Bug Report
[ ] Feature Request
[x] Seeking guidance
```

## Description
look my codes:
 ``` ts

export const getMetronicStyle = (type: number): Observable<string> => {
	let metronicJs: Promise<{ default: string }>;

	switch (type) {
		case 1:
			metronicJs = import(
				`../../../dist/metronic1/styles`
			);
			break;
		default:
			return;
	}

	return from(metronicJs).pipe(map(m => m.default));
};
```
when run build i get an error:

 ```
 Bundling to FESM2015
An unhandled exception occurred: Unexpected token (Note that you need plugins to import files that are not JavaScript)
```

this is  `styles` file codes:
```
import css from './css/style.bundle.min.css';

export default css;
```

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 12.0.0
@angular/*: 12.0.0
typescript: 4.2.3
rxjs: 6.6.0
node: 12.16.2
npm/yarn: x.y.z
```
**I don't know how to solve it**

**Comment by SmallShrimp** [comment]
I actually don't care about 'import(
`../../../dist/metronic1/styles`
);' , I don't know if I can skip it

**Comment by alan-agius4** [comment]
Non JS modules imports are not supported. Not really sure, what the usecase is here of trying to load an external stylesheet in a library.

**Comment by SmallShrimp** [comment]
I want to publish as an NPM package, and I want to load the stylesheet dynamically in the main project.Is it possible to ignore the `import` here at build time?

**Comment by alan-agius4** [comment]
> I want to publish as an NPM package, and I want to load the stylesheet dynamically in the main project.Is it possible to ignore the `import` here at build time?

No it is not possible to ignore that import. This is not something which is in scope of ng-packagr. 

In general styling and theming should be handled at an application level,
