### ISSUE TITLE
Issues with a 3rd party library typings

### ISSUE THREAD

**Issue by f4irline** [ng-packagr/ng-packagr#2049]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description

I've an Angular library project which uses a `hammerjs` within it's implementations as well as the `@types/hammerjs` type definitions. The library built fine with ng-packagr and Angular 11, but since updating to v12 I'm getting errors with missing type definitions of `hammerjs` in the consuming application.

This is the error I'm getting in the consuming application:

![image](https://user-images.githubusercontent.com/31544493/129918467-b2aa84e7-b8d8-414a-b67b-4b0465906f15.png)

#### How To Reproduce

Repository with a library implementation to reproduce the issue: https://github.com/f4irline/ng-packagr-hammerjs-issue/tree/master/projects/test-lib/src

Just run `yarn build` and `yarn package` in the project and then install the `.tgz` in a project. Steps I took: 
1. Create a new Angular library project
2. Install `hammerjs` and `@types/hammerjs`
3. Add a module and component:
```
// projects/test-lib/src/lib/hammer-test/hammer-test.component.html
<div class="hammer-test" (pan)="panEvent($any($event))"></div> 

// projects/test-lib/src/lib/hammer-test/hammer-test.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'lib-hammer-test',
  templateUrl: './hammer-test.component.html',
  styleUrls: ['./hammer-test.component.scss']
})
export class HammerTestComponent implements OnInit {

    constructor() { }

    ngOnInit(): void {
    }

    panEvent(e: HammerInput) {
        console.log(e);
    }
}

// projects/test-lib/src/lib/hammer-test/hammer-test.module.ts
import { Injectable, NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HammerTestComponent } from './hammer-test.component';
import { HammerGestureConfig, HammerModule } from '@angular/platform-browser';

// custom configuration Hammerjs
@Injectable()
export class HammerConfig extends HammerGestureConfig {
  overrides = <any> {
      // I will only use the swap gesture so 
      // I will deactivate the others to avoid overlaps
      'pinch': { enable: false },
      'rotate': { enable: false }
  }
}

@NgModule({
  declarations: [
    HammerTestComponent
  ],
  imports: [
    CommonModule,
    HammerModule,
  ],
  exports: [
      HammerTestComponent,
  ]
})
export class HammerTestModule { }
```
4. Add subentry files:

```
// projects/test-lib/src/lib/hammer-test/index.ts
export * from './public-api';

// projects/test-lib/src/lib/hammer-test/package.json
{
    "ngPackage": {
        "lib": {
            "entryFile": "public-api.ts"
        }
    }
}

// projects/test-lib/src/lib/hammer-test/public-api.ts
export * from './hammer-test.component';
export * from './hammer-test.module';

// projects/test-lib/src/lib/public-api.ts
/*
 * Public API Surface of test-lib
 */

export * from './lib/hammer-test';
```

5. Build the package and install the package to a new project
6. Install `hammerjs` to a new project (but not the `@types/hammerjs` package)
7. Import the `HammerModule` in for example `app.module.ts`
8. Start the project

#### Expected Behaviour

Should be able to use 3rd party libraries with type definitions in a library without expecting that the type definitions are installed in the consumer app.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 12.2.0
@angular/*: 12.1.5
typescript: 4.3.5
node: 12.16.3
npm/yarn: 6.14.4/1.22.4
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by f4irline** [comment]
Getting the same errors even after updating to latest Angular (12.2.1). Pushed the update to reproduction repo

**Comment by SchnWalter** [comment]
> 6. Install hammerjs to a new project (but not the @types/hammerjs package)

How do you expect TypeScript to read the types if you don't install them in the consuming application? That's your problem here.

**Comment by f4irline** [comment]
> > 1. Install hammerjs to a new project (but not the @types/hammerjs package)
> 
> How do you expect TypeScript to read the types if you don't install them in the consuming application? That's your problem here.

My bad. I assumed this started happening after updating from Angular 11 (and ng-packagr) to 12. This worked before with `skipLibCheck: true` configuration, and my new project (where I tried to use the library after the update) didn't have the option set to `true` initially.

Apologies for the inconvenience!
