### ISSUE TITLE
Resolving UMD Module Identifiers not working with domain packages

### ISSUE THREAD

**Issue by MurhafSousli** [ng-packagr/ng-packagr#2052]
_Sorry for removing the template issue, but it is pretty straight forward!_

## Description

I am trying to get rid of the warning `⠋ Bundling to UMDWARNING: No name was provided for external module '@fortawesome/angular-fontawesome' in output.globals – guessing 'i1'`

I tried as mentioned here https://github.com/ng-packagr/ng-packagr/blob/master/docs/dependencies.md#resolving-umd-module-identifiers 
```
{
  "lib": {
    "entryFile": "src/public-api.ts",
    "umdModuleIds": {
      "@fortawesome/angular-fontawesome": "@fortawesome/angular-fontawesome"
    }
  }
}
```
I also tried 

```
"umdModuleIds": {
   "@fortawesome/angular-fontawesome": "fortawesome.angular-fontawesome"
}
```

The warning is still appearing, any ideas?

**Comment by alan-agius4** [comment]
The UMD ID for `@fortawesome/angular-fontawesome` is `fontawesomeSvgCore` (https://unpkg.com/browse/@fortawesome/angular-fontawesome@0.9.0/bundles/angular-fontawesome.umd.js), can you please try?

**Comment by MurhafSousli** [comment]
I just tried it now, it didn't work!

**Comment by MurhafSousli** [comment]
I also tried `fortawesome['angular-fontawesome']` and `fortawesome.angular-fontawesome` but didn't work

**Comment by alan-agius4** [comment]
Can you setup a minimal repro please?

**Comment by alan-agius4** [comment]
Closing since no reproduction was provided.
