### ISSUE TITLE
ng packagr generated lib cannot be parsed by ngcc correctly

### ISSUE THREAD

**Issue by mogudy** [ng-packagr/ng-packagr#2053]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description

_A bug: 

original application works fine, when extract module into standalone lib using ng-packagr, it produces: "module not found error"

#### How To Reproduce

I created a new workspace includes a lib project:
@nbxx/nbweb-input contains several input components, e.g. a wrapper for signature_pad, etc.

folder structure is:
workspace
|
--projects
    |
    -- nbxx
         |
         -- nbweb-input

workspace and lib were generated by ng command

nbweb-input has no primary component, so i set public_api as "export default {};"
all dependencies are put in the package.json under lib folder;

lib compiles fine
```
------------------------------------------------------------------------------
Built Angular Package
 - from: F:\projects\nbms\nbweb-platform\nbweb-platform-admin\projects\nbxx\nbweb-input
 - to:   F:\projects\nbms\nbweb-platform\nbweb-platform-admin\dist\nbxx\nbweb-input
------------------------------------------------------------------------------
```
then I use `npm link` to set lib link, and generate a pure new project using ng new.

**the problem is:**
if I set enableIvy to false, then after ngcc compiled, I got error: `Module not found: Error: Can't resolve '@nbxx/nbweb-input/nb-input' in 'F:\projects\nongshang\stone-web\src\app'`
and when I navigated to the Module definition, I found empty definition;
```
export declare class NbCheckboxModule {
}
```
In my mind, a working lib should look like the following:
```
import { ModuleWithProviders } from '@angular/core';
import * as ɵngcc0 from '@angular/core';
import * as ɵngcc1 from './acl.directive';
import * as ɵngcc2 from './acl-if.directive';
import * as ɵngcc3 from '@angular/common';
export declare class DelonACLModule {
    static forRoot(): ModuleWithProviders<DelonACLModule>;
    static ɵfac: ɵngcc0.ɵɵFactoryDef<DelonACLModule, never>;
    static ɵmod: ɵngcc0.ɵɵNgModuleDefWithMeta<DelonACLModule, [typeof ɵngcc1.ACLDirective, typeof ɵngcc2.ACLIfDirective], [typeof ɵngcc3.CommonModule], [typeof ɵngcc1.ACLDirective, typeof ɵngcc2.ACLIfDirective]>;
    static ɵinj: ɵngcc0.ɵɵInjectorDef<DelonACLModule>;
}
```

so I change enableIvy to true, and change compilationMode to partial.
now I see something like:
```
export declare class NbCheckboxModule {
    static ɵfac: i0.ɵɵFactoryDef<NbCheckboxModule, never>;
    static ɵmod: i0.ɵɵNgModuleDefWithMeta<NbCheckboxModule, [typeof i1.NbCheckboxComponent], [typeof i2.CommonModule, typeof i3.FormsModule, typeof i3.ReactiveFormsModule, typeof i4.NzCheckboxModule], [typeof i1.NbCheckboxComponent]>;
    static ɵinj: i0.ɵɵInjectorDef<NbCheckboxModule>;
}
```

however, app still cannot import module......

#### Expected Behaviour

if lib compiles fine, ngcc should works fine, app should import lib correctly.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            11.2.4
@angular/compiler:     11.2.14
@angular/cli:    11.2.14
@angular-devkit/build-angular:  0.1102.13
rollup:                2.38.4
typescript:            4.1.6
rxjs: 6.6.0
node: 16.4.1
npm: 6.14.5
yarn: 1.22.10

// below are 3rd party libs
"expr-eval": "^2.0.2",
"ng-zorro-antd": "^11.4.2",
"rxjs": "~6.6.0",
"signature_pad": "^3.0.0-beta.4",
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

my lib workspace:
[nbweb-platform-admin.zip](https://github.com/ng-packagr/ng-packagr/files/7027148/nbweb-platform-admin.zip)

my demo app: 
[stone-web.zip](https://github.com/ng-packagr/ng-packagr/files/7027142/stone-web.zip)

**Comment by JoostK** [comment]
The module not found error is independent from ngcc, and from your description and provided zips I don't see where the app actually has a dependency on the `@nbxx/nbweb-input` package. Just using `npm link` registers the link, but that still requires using that link somewhere.

---

> if I set enableIvy to false, then after ngcc compiled, I got error: Module not found: Error: Can't resolve '@nbxx/nbweb-input/nb-input' in 'F:\projects\nongshang\stone-web\src\app'
and when I navigated to the Module definition, I found empty definition;
> 
> ```
> export declare class NbCheckboxModule {
> }
> ```

`enableIvy: false` means that Ivy isn't used, so ngcc isn't needed (and should not actually run by the CLI) and the empty module looks as expected.

---

> so I change enableIvy to true, and change compilationMode to partial.
> now I see something like:
>
> ```
> export declare class NbCheckboxModule {
>     static ɵfac: i0.ɵɵFactoryDef<NbCheckboxModule, never>;
>     static ɵmod: i0.ɵɵNgModuleDefWithMeta<NbCheckboxModule, [typeof i1.NbCheckboxComponent], [typeof i2.CommonModule, typeof i3.FormsModule, typeof i3.ReactiveFormsModule, typeof i4.NzCheckboxModule], [typeof i1.NbCheckboxComponent]>;
>     static ɵinj: i0.ɵɵInjectorDef<NbCheckboxModule>;
> }
> ```

Please keep in mind that partial compilation was experimental in Angular 11 and should not be used to distribute packages.

**Comment by mogudy** [comment]
thanks for your reply.

the app refs @nbxx/nbweb-input in app.module.ts & app.component.html. I'sorry that i didnot clean the code well.

The problem here is regardless of the enableivy flag, the app cannot run successful.

Sometimes it warns me `Module not found`
Sometimes it warns me some weird messages, such as 
```
1. If 'router-outlet' is an Angular component, then verify that it is part of this module.
2. If 'router-outlet' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
```

The only thing I do, compare with the original ng generated app, is I add the <nb-input></nb-input> lib ref in the app.component.html.

I re-upload a cleaner app, please have a look if not too much trouble for you.
[stone-web.zip](https://github.com/ng-packagr/ng-packagr/files/7027348/stone-web.zip)

**Comment by JoostK** [comment]
As mentioned, there is no dependency on the `@nbxx/nbweb-input` package from your app. Just using the `@nbxx/nbweb-input` module name is not sufficient, you'd have to specify somehow what that module is. This is typically done by adding a dependency to `package.json` which ends up installing the dependency into the `node_modules` directory. That location is searched for automatically, so the package can be found then.

Please read [the docs on NPM link](https://docs.npmjs.com/cli/v7/commands/npm-link), as it explains that there are two steps involved in linking a package. In your case, you've only registered the link but are not consuming it yet.

**Comment by mogudy** [comment]
Thank you for your patience.

I think I did not explain clearly, so I recorded a video, uninstall the global link, local link, rebuild lib, and then link global, link local, npm i local, run local, to show what happened.

below is my operation abstract just incase you don't want to watch it.

1. delete the whole dist folder in lib workspace
2. remove global links
```
npm uninstall -g @nbxx/nbweb-input
```
3. rebuild lib
```
ng build @nbxx/nbweb-input --configuration production
```
4. create global link
```
cd dist/nbxx/nbweb-input
npm link
```
5. switch to app workspace
6. link local
```
npm link @nbxx/nbweb-input
```
7. make sure it has dependency in package.json
8. npm install to make sure all dependencies are resolved
```
npm i
```
9. launch in dev mode
```
ng serve
```

and finally, you can see it warns me about ngxx 
```
Error: ../../nbms/nbweb-platform/nbweb-platform-admin/dist/nbxx/nbweb-input/nb-input/src/nb-input.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolv
ed to an NgModule class.

This likely means that the dependency (@nbxx/nbweb-input/nb-input) which declares NbinputModule has not been processed correctly by ngcc.
```

and nb-input.module.d.ts has the following content:
```
export declare class NbinputModule {
}
```

B.T.W. this try, enableIvy is disabled

So I gave a second try with enableIvy in true and compilationMode in partial ( not recorded ):
this time it showed: 
```
Error: src/app/app.component.html:1:11 - error NG8002: Can't bind to 'ngModel' since it isn't a known property of 'nb-input'.
1. If 'nb-input' is an Angular component and it has 'ngModel' input, then verify that it is part of this module.
2. If 'nb-input' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

1 <nb-input [(ngModel)]="stone"></nb-input>
            ~~~~~~~~~~~~~~~~~~~

  src/app/app.component.ts:5:16
    5   templateUrl: './app.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.

```

originally, my ng-packagr.json set entry file to public_api as doc said, later I saw an issue said it may cause blank index.d.ts
then I changed the entry to index.ts, but still no help.

I have tried all I can, searched for all sites I know, but still no idea what the cause is.....

Really appreaciate if you can help me find out what's the cause.


[bandicam 2021-08-23 01-39-50-353.zip](https://github.com/ng-packagr/ng-packagr/files/7027839/bandicam.2021-08-23.01-39-50-353.zip)

**Comment by mogudy** [comment]
Finally I found the solution. thank you.

just set pathMap in ts.config in workspace root, fill in all peerDependencies
