### ISSUE TITLE
customize the secondary entrypoint building order

### ISSUE THREAD

**Issue by mogudy** [ng-packagr/ng-packagr#2062]
## Type of Issue

```
[ ] Bug Report
[X] Feature Request
```

## Description

I built up a lib with several modules as secondary entrypoints.
Sometimes one module depends on each other.
Normally it compiles fine, but it may produce module not found error.

 It would be great if I can have a build order file to tell ng-packagr, it should build modules in such a order;

#### Expected Behaviour

maybe a json or txt file has entrypoint name each a line, ng-packagr reads if exist and build follow the order.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            11.2.4
@angular/compiler:     11.2.14
rollup:                2.38.4
typescript:            4.1.6
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by alan-agius4** [comment]
ng-packagr builds the secondary entry-points in topological order and therefore it should always built in the right order.

if you are experiencing issues with this please file a new issue with a reproduction.
 
Specifying the build order is definitely something that we shouldn’t allow.
