### ISSUE TITLE
Alternative to bundledDependencies

### ISSUE THREAD

**Issue by sporritt** [ng-packagr/ng-packagr#2064]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

This is a duplicate of #1739, which is now locked.  

I build a bunch of libraries that are commercially licensed, one of which is the Angular integration for jsPlumb. Other developers purchase a license to this code and build apps with it.

Now I'd like to build a component using that library, and I want to package that component up such that everything from the library it needs is contained therein, and there is no need to import the Angular integration as a peer dependency. Without the ability to do this I am required to rely on users installing the Angular integration library, which is a) a pain for them and b) not allowed, unless they have a development license, in which case they're not interested in this component anyway.

I've read through a bunch of other issues and I know I'm not the only person who has this issue.  The impression I get is that the main driver for removing this functionality was that it serves as a bit of a footgun (in particular that people might bundle angular, which I am not intending to do), not that it was difficult to maintain.  

Would you reconsider supporting this?

#### How To Reproduce

Declare `bundledDependencies` in package.json.  They are ignored.

#### Expected Behaviour

I would like the bundled dependencies to be included in the build. Or some other mechanism.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            10.1.2
@angular/compiler:     10.0.14
rollup:                2.10.9
tsickle:               
typescript:            3.9.10
npm: 6.14.13
```

**Comment by alan-agius4** [comment]
`bundledDependencies` can still be used, although the end result would be that the code will not be embedded in the UMD bundle. The good news is that UMDs bundles have been removed in the upcoming version (13), so there is no longer a discrepancy here.

**Comment by sporritt** [comment]
Um, thanks for the reply. I don't quite know how to respond to this. Have you ever seen Spinal Tap, the scene where the amps go to 11?

**Comment by alan-agius4** [comment]
No, and not sure what’s the point you are trying to make.

**Comment by sporritt** [comment]
@alan-agius4 Do you think, in the case I've outlined above, that you'd expect the imported libraries to be in the `fesm2015` output?  Imagine this module:

```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { AppComponent } from './app.component';

import { EmbeddedComponentModule } from "@foo/embedded-component"

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule, EmbeddedComponentModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

Some things I have read tend to suggest that `EmbeddedComponentModule` should be inlined in the fesm output - the package format spec for instance:

[https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview#](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview#)

>FESM is a file format created by flattening all ES Modules accessible from an entry point into a single ES Module. It’s formed by following all imports from a package and copying that code into a single file while preserving all public ES exports and removing all private imports

**Comment by alan-agius4** [comment]
In the statement you pasted, it is assumed that private imports are relative paths within that a module, while non relative paths are considered as externals.

For FESMs, `bundledDependencies` never caused the any of the code to be embedded into the FESM, but rather relied on NPM's [bundledDependencies](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#bundleddependencies) strategy and on the application bundler to resolve the dependency.

**Comment by sporritt** [comment]
So I've misinterpreted this line:

>It’s formed by following all imports from a package and copying that code into a single file

Because to me that sounds like, well, it follows _all imports_ from a package and copies that code into a single file. Perhaps "from a package" is the term I am interpreting differently.

Anyway just to be clear, there is no way now of bundling imports via ng-packagr, and there never will be. Correct?

**Comment by alan-agius4** [comment]
At the moment no, this is not something that it is possible to do without an additional transformation after ng-packagr is executed.

I cannot say that it will never be added, but at the moment this is not something that we’d want to add as part of our API, especially consider you can use NPMs bundledDepenencies.

**Comment by alan-agius4** [comment]
I think you are confusing a library bundle and an optimized application bundle where the latter unused/unexported symbols are tree-shake and dead code is removed.

A library bundle, is just a merging of smaller ESM modules into a single flat module, there is no dead-code elimination nor tree-shaking involved.

**Comment by sporritt** [comment]
No, I'm not confusing the two. I've detailed the use case clearly on here.

**Comment by alan-agius4** [comment]
You mentioned tree-shaking which is more of an application concept.

If in your library you have the following import and `@foo/embedded-component` get embed.
```ts
import { EmbeddedComponentModule } from "@foo/embedded-component"
```

All symbols which `@foo/embedded-component` exports (Even those unused) will be merged into the FESM file, because there is no tree-shaking at a library level.

**Comment by sporritt** [comment]
Wait so you're saying now that the FESM file won't have this import statement in it:

```
import { EmbeddedComponentModule } from "@foo/embedded-component"
```

?  

and that instead `EmbeddedComponentModule` will be in the FESM js file?

**Comment by alan-agius4** [comment]
Sorry for the confusion, I updated the above comment, I meant if bundle dependencies emceed non relative imports.

**Comment by sporritt** [comment]
...yes I am quite confused now.  What is `my-lib-fesm.js` ? Is it file that gets built and put in `fesm2015` ?  Why does it both import something from `"@foo/embedded-component" and also have source code that exports the same thing?

```
import { EmbeddedComponentModule } from "@foo/embedded-component"  <---------
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

/// contents of @foo/embedded-component
export const fooBar = ''; 

@NgModule({});
export class EmbeddedComponentModule {  <---------------
}
```

**Comment by alan-agius4** [comment]
PTAL a revised version of https://github.com/ng-packagr/ng-packagr/issues/2064#issuecomment-911344080

**Comment by sporritt** [comment]
Ok, so if this were the case then I would of course be delighted, since it's what I would like - it shows the embedded component's source getting included and therefore no need for `peerDependencies`.  

But it doesn't work like this, at least not in version 10.1.2.  This method, in `lib/flatten/rollup.js` is called twice during the component build, the first time to build the FESM bundle and the second time to build the UMD:

```
function rollupBundleFile(opts) {
    return __awaiter(this, void 0, void 0, function* () {
        log.debug(`rollup (v${rollup.VERSION}) ${opts.entry} to ${opts.dest} (${opts.format})`);
        const externalModuleIdStrategy = new external_module_id_strategy_1.ExternalModuleIdStrategy(opts.format, opts.dependencyList);
        // Create the bundle
        const bundle = yield rollup.rollup({
            context: 'this',
          external: moduleId => externalModuleIdStrategy.isExternalDependency(moduleId),
       ....extra rollup things....
        });
// Output the bundle to disk
        yield bundle.write({
            name: opts.moduleName,
            format: opts.format,
            amd: opts.amd,
            file: opts.dest,
            banner: '',
            globals: moduleId => umd_module_id_strategy_1.umdModuleIdStrategy(moduleId, opts.umdModuleIds || {}),
            sourcemap: true,
        });
        return bundle.cache;
    });
}
```

The incoming `opts.dependencyList` variable is populated with a list of dependencies and also contains the `bundledDependencies` list.  In order to determine which modules are external, this method uses `externalModuleIdStrategy.isExternalDependency(moduleId)`.  That method, and a helper it uses, look like this:

```
isExternalDependency(moduleId) {
        // more information about why we don't check for 'node_modules' path
        // https://github.com/rollup/rollup-plugin-node-resolve/issues/110#issuecomment-350353632
        if (path.isAbsolute(moduleId) || moduleId.startsWith('.') || moduleId.startsWith('/')) {
            // if it's either 'absolute', marked to embed, starts with a '.' or '/' or is the umd bundle and is tslib
            return false;
        }
        const externals = this.getNonBundledDependencies();
        if (Array.isArray(externals)
            ? !externals.some(x => x === moduleId || moduleId.startsWith(`${x}/`))
            : !externals.test(moduleId)) {
            return false;
        }
        return true;
    }
    /**
     * Returns a array of strings or a RegExp of non-bundled dependencies.
     */
    getNonBundledDependencies() {
        const { bundledDependencies = [], dependencies = [] } = this.dependencyList;
        // return catch all for when there are no 'bundledDependencies' is very important for secondary entry
        // as if this is not the case everything will be bundled in the secondary entry point
        // since no dependencies are defined.
      if (this.moduleFormat !== 'umd') {
       return /./; // catch all as external
       }
        // tslib should always be embedded for umd modules
        if (bundledDependencies.length === 0) {
            return /^((?!tslib).)*$/;
        }
        // filter out dependencies that are meant to be external
        return dependencies.filter(x => bundledDependencies.indexOf(x) < 0);
    }
```

So if `this.moduleFormat` is anything other than `"umd"` every module is considered external ( I actually thought you were saying that earlier in this issue but it seems now you are suggesting otherwise).

**Comment by sporritt** [comment]
it completely chokes at runtime though, predictably.

anyway i can see by the current codebase:

https://github.com/ng-packagr/ng-packagr/blob/master/src/lib/flatten/rollup.ts#L76

that this line of enquiry is going to go nowhere.  thanks for your time.
