### ISSUE TITLE
Library: Dynamic compile-time constants from environment 

### ISSUE THREAD

**Issue by alan-agius4** [ng-packagr/ng-packagr#2070]
# 🚀 Feature request

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

I have the requirement that I need to inject dynamically generated constants into the library during compile time. For example, I want to generate a unique version string (i.e., version string 1.0.0-dev.12345, build number 12345, git commit hash or commit/build date, etc.) from the CI/CD environment for each build and compile that string into the compiled library so it is available at runtime.

### Describe the solution you'd like

I want to create a metadata class that exposes the information at runtime of the library so that the library can provide information about it self to consumers of the library. The information should be injected at compile time by the CI/CD environment via Environment variables or command line options. In addition, the process should be in such a way, that it does not interrupt the developer workflow if these values are not present or undefined in the local developers work space in a dev environment.

Ideally, we could use the `environment.ts` and `environment.prod.ts` for this, where the `environment.ts` contains some default values such as `"version": '0.0.0'` and the `environment.prod.ts` receives that actual version during compile time from the CI/CD environment via some thing like `ng build my-lib --configuration production -D version=1.0.0-dev.12345 -D build-number=12345`. Note, that this line might not appear literally in a `package.json` but could be invoked from `npm run` via something like `npm run build:prod -- -D version=1.0.0-dev.12345 -D build-number=12345` assuming that the `build:prod` script resolves to `ng build my-lib --configuration production`.

### Describe alternatives you've considered

For plain Angular applications we are using the [custom-webpack][1] plugin, to modify the build process and inject values via Webpack's [DefinePlugin][2] or copy files via the [copy-webpack-plugin][3]. I just learned that when we are building libraries the Angular CLI uses [ng-packagr][4] and I do not see an equally straitforward way to inject custom build steps where I can integrate such steps.

It it possible at the moment and I just missed it? If not, are there known workarounds? If its not possible, could you add support for it? 

# PS

It seems what I am asking for is common in most programming languages. C/C++ has had pre-processor defines since forever and this is well integrated into higher level build tools like CMake, Autotools or Meson. In other environments like with MS dotnet we can [declare build-time properties][5] with the `-p` option. Its also possible in Java (`-D` option). Docker has `--build-arg` for this.

[1]: https://www.npmjs.com/package/@angular-builders/custom-webpack
[2]: https://webpack.js.org/plugins/define-plugin/
[3]: https://www.npmjs.com/package/copy-webpack-plugin/
[4]: https://github.com/ng-packagr/ng-packagr
[5]: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build#msbuild

**Comment by alan-agius4** [comment]
In general, the library build version is set in the package.json manifest.

What is the use-case of needed this to be available during runtime?

**Comment by s-geiger-si** [comment]
Well, we do not want to commit the library version inside the `package.json` into the git repository and we also do not want to modify a committed `package.json` in-place in the source directory. What we want is to compute it dynamically by the CI/CD pipeline. We usually render a new `package.json` into the `dist/` folder and inject the dynamically determined version number into it. But this only affects the `package.json` we also want to embed the version string directly into the bundled `.js` file during a compile step.

This would enable us to build something like a `version` or `about` view/route which informs us about the exact version of each of our (own) libraries that are being used in an app.

**Comment by s-geiger-si** [comment]
@alan-agius4 I am wondering if you could common on your perspective of this issue? Was there a particular reason not add this feature so far or has this just never been requested? Do you think it makes sense to add such a feature? Do you think it is easy to add this or will it require extensive work? Do you see any show-stoppers for this?

**Comment by alan-agius4** [comment]
> Was there a particular reason not add this feature so far or has this just never been requested?

There was never a competent enough feature to why a library should have static compile time configuration. This is a very atypically use-case as typically library configuration is passed via DI. 

> Do you think it makes sense to add such a feature

I personally, don't see many use-cases were such feature would be beneficial. 

> Do you think it is easy to add this or will it require extensive work?

Adding this feature is not complex. The bulk of works comes afterwards as this feature needs to be maintained and supported for many years to come.

**Comment by alan-agius4** [comment]
Thanks for this feature request, however it seems that there is not much interest in such feature from the community. Hence, I am going to close this.

Let’s revisit in the future if things change.
