### ISSUE TITLE
[Feature Request] Option to compile in the tslib dependency?

### ISSUE THREAD

**Issue by fireflysemantics** [ng-packagr/ng-packagr#2109]
## Type of Issue

```
[ ] Bug Report
[X ] Feature Request
```

## Description

_A feature: please describe your use case and motivation_

Right now the `tslib` is added as a direct dependency to Angular Package Format projects.

This means that all consumers of the project have to use a `tslib` compatible dependency.

It would be great if the required `tslib` lines of code were compiled in directly into the package (Perhaps as an option) so that consumers of the library don't have to worry about `tslib` version compatibility.

**Comment by alan-agius4** [comment]
In general it's not recommended to disable `importHelpers` as this would cause an increase in bundle size. Also, `tslib` is a direct dependency of the library and therefore it's not of concern for library consumers.

**Comment by alan-agius4** [comment]
Closing as this is currently in the roadmap
