### ISSUE TITLE
ng-packagr do not create bundles in watch mode

### ISSUE THREAD

**Issue by eboukamza** [ng-packagr/ng-packagr#2112]
## Type of Issue

```
[x ] Bug Report
```

## Description

`ng-packagr --watch` do not creates `/bundles` output

#### How To Reproduce
1. run ng-packagr normally: `ng-packagr`
you can see `/bundles` directory created inside /dist 
2. run ng-packagr in watch mode: `ng-packagr --watch`
`/bundles` directory is missing

#### Expected Behaviour

I think the output must be the same when build with --watch option

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 12.2.1
@angular/compiler: 12.2.4
rollup: 2.56.3
typescript: 4.3.5
```

**Comment by alan-agius4** [comment]
This is working as expected as it’s one of the breaking changes in v12. UMDs are not longer generated during watch mode.

In v13, UMDs have been removed completely.
