### ISSUE TITLE
Error css order after css minifier

### ISSUE THREAD

**Issue by yinshuxun** [ng-packagr/ng-packagr#2140]
## Type of Issue

```
[x ] Bug Report
[ ] Feature Request
```
## Description

Error css order after css minifier

#### How To Reproduce
in my scss file:
```
.aui-table {
  border-width: 1px;
  border-bottom: 0;
  border-style: solid;
  border-color: red;
}
```

after build:lib action ,in library 
```
styles: [".aui-table{border:1px solid red;border-bottom:0}"]
```

#### Expected Behaviour

after build:lib action ,in library 
```
styles: [".aui-table{border-bottom:0;border:1px solid red;}"]
```
#### Version Information

```
ng-packagr:            11.2.4
@angular/compiler:     11.2.4
rollup:                2.59.0
typescript:            4.1.5
```

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent ng-packagr version.
