### ISSUE TITLE
Building with @angular/material v13 @use statements are failing

### ISSUE THREAD

**Issue by michaelfaith** [ng-packagr/ng-packagr#2142]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description
After updating to v13 this morning, which removed all of the tildes from material's `@use` statements, our library isn't building, saying it can't find the stylesheet.  If I add the tildes back, it builds fine.  Using without the tilde is working ok in the context of an application, but ng-packagr seems to still need them.  This causes a really ugly catch 22, since our styles can't have tildes to work with applications, but need them to work with the library build.
 
#### Error

```
------------------------------------------------------------------------------
Building entry point '@fabric/components/breadcrumbs'
------------------------------------------------------------------------------
× Compiling with Angular sources in Ivy partial compilation mode.
Can't find stylesheet to import.
  ╷
7 │ @use '@angular/material' as mat;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  breadcrumbs\breadcrumbs.component.scss 7:1  root stylesheet
error Command failed with exit code 1.

```

#### Version Information

```
ng-packagr: 13.0.0
@angular/*: 13.0.0
typescript: 4.4.4
rxjs: 7.4.0
node: 14.17.0
yarn: 1.22.15
```

**Comment by alan-agius4** [comment]
@michaelfaith, thanks for reporting this.

**Comment by michaelfaith** [comment]
@alan-agius4 Thanks for the quick turnaround!

**Comment by michaelfaith** [comment]
@alan-agius4 unfortunately this doesn't seem to have fixed the issue for us.  I wonder if it has to do with it being in yarn workspaces?  Our node_modules are hoisted to the root of the mono-repo.  The change appeared to only add the local node_modules, if I'm reading the PR correctly?

**Comment by alan-agius4** [comment]
Yeah, you are right. Let me do that.

**Comment by alan-agius4** [comment]
https://github.com/ng-packagr/ng-packagr/pull/2145

**Comment by michaelfaith** [comment]
Awesome.  Thanks for jumping on this so quick.

**Comment by michaelfaith** [comment]
Just wanted to confirm, your updates resolved our issue, and our builds are green.  Thanks again!
