### ISSUE TITLE
v13: Sass assets packaged into the library aren't available in consuming apps

### ISSUE THREAD

**Issue by michaelfaith** [ng-packagr/ng-packagr#2149]
v13: Sass assets packaged into the library aren't available in consuming apps
```
[ x ] Bug Report
[ ] Feature Request
```

## Description

Prior to v13, we've always copied our ./styles folder via the assets config, as well as our _index.scss, and consuming apps have never had an issue importing (or `@use`ing) them.  After the 13 update, we're getting a `sass-loader` error that the consuming app can't find the stylesheet.  

```
./src/app/getting-started-guide/getting-started-guide.component.scss - Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
6 │ @use '@fabric/components' as fab;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\app\getting-started-guide\getting-started-guide.component.scss 6:1  root stylesheet



× Failed to compile.
```

Inspecting the material `package.json` from `node_modules`, I noticed their sass files are explicitly exported, and those imports work in the app.  If I manually edit our package.json from the downloaded package to include: 
`"sass": "./_index.scss",` in the `exports` `"."` object, and 
```json
    "./styles/dark-theme": {
      "sass": "./styles/_dark-theme.scss"
    },
    "./styles/light-theme": {
      "sass": "./styles/_light-theme.scss"
    },
```
The app is able to load them.  So my question is twofold.  
1) why did this suddenly stop working? i.e. was this an intentional change?
2) is there some configuration change I can make to restore the behavior we had before where all scss files copied via assets were available to consuming apps?  Or will I need to create my own `postbuild` script to add those entries to the generated `package.json`?

#### Version Information

```
ng-packagr: 13.0.3
@angular/core: 13.0.0
@angular/cli: 13.0.1
typescript: 4.4.4
rxjs: 7.4.0
node: 14.17.0
yarn: 1.22.15
```

**Comment by michaelfaith** [comment]
Thinking about this more, I wonder if this issue doesn't belong on the app compiler side.  `ng-packagr` is putting the assets in the right place, and they're making it into the consuming apps `node_modules` correctly still.  I guess it would be an issue here, if there indeed was a need to emit those export entries in the generated `package.json` as part of the new Angular package format.

**Comment by alan-agius4** [comment]
This is expected and is one of the changes in APF 13. This is cause by the the addition of package [exports](https://angular.io/guide/angular-package-format#exports) in the primary entry-point package.json.

You need to include to add these assets manually in the `package.json` of the primary entry-point. There is no need for a postbuild step, just add them in the source `package.json` as ng-packagr will merge the handwritten "exports" with the auto-generated ones.

More information https://angular.io/guide/creating-libraries#managing-assets-in-a-library.

**Comment by michaelfaith** [comment]
@alan-agius4 brilliant. That worked like a charm.  I assumed the exports was generated completely each time, but merging worked great.  And no knowing how this works, I actually like the change, since it allows to have private sass styles, and forces us to formalize our public api.  Thanks for all your help with these issues.  Really appreciate it.

Once I have a chance to come up for air and make it through our updates, I could contribute an update to the documentation here to callout the impacts to sass/styles specifically, if you think it's appropriate.
