### ISSUE TITLE
Angular 13 - Option to remove prepublishOnly script

### ISSUE THREAD

**Issue by mikerentmeister** [ng-packagr/ng-packagr#2155]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

Now that Angular 13 has been released, and ViewEngine is deprecated, can we please revisit the [request to remove the prepublishOnly script](https://github.com/ng-packagr/ng-packagr/issues/1467#issue-533620341)? I'm publishing a private repo to npm that will only be consumed by Ivy applications. I know that there are workarounds to remove or ignore the script, but it would be nice to not have to do this anymore

#### Expected Behaviour

Add a flag or something to opt out of the prepublishOnly script

**Comment by alan-agius4** [comment]
What are the reasons why you want to publish Ivy full compiled code am instead of partial?

It’s not recommended to publish Ivy code which is not partial as this requires your consumers to use the **exact same version** of Angular was the library was built with.

**Comment by mikerentmeister** [comment]
It's a private repo, so I can guarantee all of the above. When doing partial compiles I get a whole bunch of build errors about cyclical dependencies, and how it can't do more than 1 cycle.

**Comment by JoostK** [comment]
Ivy libraries are only meant to be published to any registry using partial compilation output. The full compilation output is not stable across Angular versions, and there is nothing in place to detect any incompatibilities either at compile time nor runtime. I don't feel comfortable offering this footgun as a configuration option.

In partial compilations (still using the Ivy compiler!), the compiler reports errors if the compilation of a component template ends up needing to create a cyclic import for a component/directive/pipe that is used. Application builds have a fallback strategy available for this scenario, but it breaks tree-shaking _and_ introduces side-effectful code, which introduces issues like angular/angular#38362. This is why we are not allowing such situations in partial compilations for published libraries.

**Comment by mikerentmeister** [comment]
> In partial compilations (still using the Ivy compiler!), the compiler reports errors if the compilation of a component template ends up needing to create a cyclic import for a component/directive/pipe that is used. Application builds have a fallback strategy available for this scenario, but it breaks tree-shaking _and_ introduces side-effectful code, which introduces issues like [angular/angular#38362](https://github.com/angular/angular/issues/38362). This is why we are not allowing such situations in partial compilations for published libraries.

So if I understand correctly, the problem is that my library being built in "partial" mode is actually showing something that I should have fixed a long time ago? (the cyclical dependencies).

Apart from the [building libraries section](https://angular.io/guide/creating-libraries#refactoring-parts-of-an-application-into-a-library) on angular.io, are there any other official resources of how to go about resolving these cyclical dependency issues? Is the major problem mainly components used in other components? It's proving quite the undertaking for my team.

**Comment by JoostK** [comment]
> So if I understand correctly, the problem is that my library being built in "partial" mode is actually showing something that I should have fixed a long time ago? (the cyclical dependencies).

The constraint around cyclic dependencies is new to Ivy, please see https://github.com/angular/angular/issues/43227#issuecomment-904173738 for background information.

> Apart from the building libraries section on angular.io, are there any other official resources of how to go about resolving these cyclical dependency issues? Is the major problem mainly components used in other components? It's proving quite the undertaking for my team.

There are some hints to avoid the cycles in [the NG3003 error documentation page](https://angular.io/errors/NG3003).

**Comment by alan-agius4** [comment]
Thanks @JoostK for chiming in. Closing as per above.
