### ISSUE TITLE
SCSS Preprocessor to support additionalData property

### ISSUE THREAD

**Issue by rsouthgate** [ng-packagr/ng-packagr#2163]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

Migrating a library from a webpack bundle to ng-packagr. One step currently is to make use of the sass-loader additionalData property (https://webpack.js.org/loaders/sass-loader/#additionaldata) to prepend a bunch of sass variable values into the scss at build.

It would be useful if the ng-packagr scss preprocessor could support the same property.

#### Version Information

```
ng-packagr:            11.2.4
@angular/compiler:     11.2.12
rollup:                2.47.0
typescript:            4.0.5
```

**Comment by alan-agius4** [comment]
Hi, 

This is not in our roadmap to add support for. 

`additionalData` is a Webpack specific feature, which are is not supported by the standard sass pre-processor nor when using Angular CLI to build an application.
