### ISSUE TITLE
Readme examples use package.json config even though it's deprecated

### ISSUE THREAD

**Issue by benelliott** [ng-packagr/ng-packagr#2176]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

The Readme for this repo doesn't explain that config via `package.json` (as opposed to `ng-package.json`) is deprecated and uses the former in its examples.

**Comment by f4irline** [comment]
Question about deprecating `package.json`: If we're supposed to use `ng-package.json`, how can we define dependencies specific for only some sub-package? Since `ng-package.json` doesn't support defining `peerDependencies`

**Comment by JoostK** [comment]
> Question about deprecating `package.json`: If we're supposed to use `ng-package.json`, how can we define dependencies specific for only some sub-package? Since `ng-package.json` doesn't support defining `peerDependencies`

There is no such thing as declaring dependencies in sub-packages. The `package.json` files within secondary entry-points only exist today for module resolution reasons, they are not at all used by package managers such as NPM so there is no value in declaring any dependencies there.

**Comment by f4irline** [comment]
> > Question about deprecating `package.json`: If we're supposed to use `ng-package.json`, how can we define dependencies specific for only some sub-package? Since `ng-package.json` doesn't support defining `peerDependencies`
> 
> There is no such thing as declaring dependencies in sub-packages. The `package.json` files within secondary entry-points only exist today for module resolution reasons, they are not at all used by package managers such as NPM so there is no value in declaring any dependencies there.

Ah, alright. My knowledge was based on [this](https://medium.com/tunaiku-tech/creating-secondary-entry-points-for-your-angular-library-1d5c0e95600a) article, but I guess I should've tested this myself!

**Comment by JoostK** [comment]
Hmm, yeah that article isn't quite accurate :(

In the future it is likely that the nested `package.json` files  will disappear, as we'd be able to leverage package exports. Those have already been adopted in the APF 13 format ([see `@angular/core` as an example](https://unpkg.com/browse/@angular/core@13.1.2/package.json)) but the nested `package.json` files are still present today as export fields are not universally supported by tooling yet.
