### ISSUE TITLE
ng-packagr v12 has esbuild v0.12.29 which causes CI builds to hang on postinstall

### ISSUE THREAD

**Issue by duncan-luno** [ng-packagr/ng-packagr#2182]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

Since `ng-packagr` v12.2.5 uses `esbuild` v0.12.29, these cause CI builds to hang on the `postinstall` step. This is fixed in `esbuild` v0.13 as per https://github.com/evanw/esbuild/pull/1621. We can't currently upgrade to `ng-packagr` v13 this year

#### How To Reproduce

This error is intermittent. Running a CI build where `ng-packagr` is installed can cause it to hang forever on the `esbuild` `postinstall` step.

#### Expected Behaviour

Should not hang on `esbuild` `postinstall` step.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 12.2.5
@angular/*: 12.2.13
typescript: 4.3.5
rxjs: 6.6.7
node: 14.18.1
npm/yarn: 6.14.15
```

I appreciate any help and understand if we may need to just push through until we can update to v13.

**Comment by JoostK** [comment]
I can confirm this is a problem; we avoided the issue using Yarn's resolutions feature to pull in esbuild 0.13 and that appears to work fine.

**Comment by dunxen** [comment]
> I can confirm this is a problem; we avoided the issue using Yarn's resolutions feature to pull in esbuild 0.13 and that appears to work fine.

Ah, unfortunately we're using npm. Hoping to switch to yarn in the new year but we'll have upgraded by then anyway :) 

Thanks for the tip, though!

**Comment by alan-agius4** [comment]
Closed via https://github.com/ng-packagr/ng-packagr/pull/2189/
