### ISSUE TITLE
Migration path for UMD packages excluded

### ISSUE THREAD

**Issue by vasicvuk** [ng-packagr/ng-packagr#2190]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description

I am trying to upgrade my environment from Angular 11  to Angular 13. I have used UMD modules loaded over SystemJS. 

I tried loading the `FESM` module instead, but the maximum I could get is this error.
```
Cannot use import statement outside a module
```

How can I upgrade to using FESM modules instead of UMD that no longer exists?

**Comment by alan-agius4** [comment]
Hi @vasicvuk, 

There are a couple of things that you can do. 

- Transform the ESM bundles UMD using Babel or Rollup.
- Use systemjs-babel https://github.com/systemjs/systemjs#systemjs-babel
