### ISSUE TITLE
SCSS paths aliases (tilda) with monorepos.

### ISSUE THREAD

**Issue by RuBAN-GT** [ng-packagr/ng-packagr#2194]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

Hello everyone, I have a yarn v2 monorepo with enabled hoisting mechanism, it means that yarn tries to keep common dependencies in the root node_modules folder and different angular libraries located in sub-folders. 
One of them has component scss file where I'm trying to import styles using 

```
@import '~flatpickr/dist/flatpickr.css';
```

It's pretty simple thing, but it doesn't work when flatpickr package when is located outside libraries node_modules (in root). 

```
ERROR: ENOENT: no such file or directory, open '/Users/dkruban/Documents/Project/libs/custom-lib/src/lib/modules/generic-components/components/date-range/flatpickr.css'
An unhandled exception occurred: ENOENT: no such file or directory, open ''/Users/dkruban/Documents/Project/libs/custom-lib/src/lib/modules/generic-components/components/date-range/flatpickr.css'
See "/private/var/folders/cc/rbs633t52r9gsq5pqphkbdyc0000gp/T/ng-Aq8sYX/angular-errors.log" for further details.
```

The only way for that is to use relevant path like `../../../../../../../../node_modules/flatpickr/dist/flatpickr.css`.

#### How To Reproduce

Try to use hierarchy of node_modules and any hoisting framework which can move all dependencies to the project root node_modules.

#### Expected Behaviour

With any monorepo environment scss can recognize paths aliases and load appropriate styles from root node_modules.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:             11.2.4
@angular/compiler: 11.2.14
rollup:                       2.51.1
typescript:               4.1.6
node:                        14.16.1
yarn:                         2.4.2
```

**Comment by avmaxim** [comment]
I have the same exact issue when working with yarn workspaces. I'd appreciate any action on it

**Comment by alan-agius4** [comment]
This should no longer be an issue in version 13.

**Comment by RuBAN-GT** [comment]
> This should no longer be an issue in version 13. Can you please update and report back?

As I understand it requires Angular 13 for my project. Do you have any other ways to solve it without affection of Angular dependencies? I'm afraid for now to fetch its breaking changes (specially with removed view engine).

**Comment by alan-agius4** [comment]
You can try to add the path to your root node modules via the `styleIncludePaths` https://github.com/ng-packagr/ng-packagr/blob/master/docs/style-include-paths.md but if that doesn’t work you will need to update to ng-packagr and Angular version 13.

**Comment by alan-agius4** [comment]
Closing as this should no longer be an issue in the latest version.
