### ISSUE TITLE
SHA-512 checksums vary depending on the folder path (version 10.1.2)

### ISSUE THREAD

**Issue by javier-lopez-1s** [ng-packagr/ng-packagr#2195]
## Type of Issue

```
[x] Bug Report
```

## Description

If you create 2 folders (folder1 and folder2), copy the same code on both and execute ng-packagr, then you get different SHA-512 checksums in each folder. This was already fixed for the issue [#19335](https://github.com/angular/angular-cli/issues/19335) with the pull request #1786, but it looks like it was only included in version 11. The pull request only changed 1 line of code, could the same fix be applied to version 10 as well?

#### How To Reproduce

Create two folders: **folder1** and **folder2**.

For each folder, run the following commands:

`ng new my-app --skipGit=true`

> No routing
> CSS

`ng generate library my-lib`

`ng build my-lib --prod`

#### Version Information

```
Angular CLI: 10.2.1
Node: 16.13.1
OS: win32 x64

Angular: 10.2.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1002.1
@angular-devkit/build-angular   0.1002.1
@angular-devkit/core            10.2.1
@angular-devkit/schematics      10.2.1
@angular/cli                    10.2.1
@schematics/angular             10.2.1
@schematics/update              0.1002.1
ng-packagr                      10.1.2
rxjs                            6.6.7
typescript                      4.0.8
```

**Comment by alan-agius4** [comment]
Versions 12, 11 and 10 are currently in LTS and only security fixes are applied. Please update to a more recent version to benefit from bug fixes and new features.
