### ISSUE TITLE
styleIncludePaths not working as expected

### ISSUE THREAD

**Issue by Tim-arts** [ng-packagr/ng-packagr#2200]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

In my Angular library I'm trying to use **styleIncludePaths** to shorten my imports while being inside my **components** folder and calling definitions located in my **scss* folder down below. This is my current architecture:

![image](https://user-images.githubusercontent.com/10064887/146451296-323881c9-b5dd-4288-bd7d-faab8897ab58.png)

// ng-package.json
```
{
  "$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
  "dest": "../../dist/core",
  "lib": {
    "entryFile": "src/public-api.ts",
    "styleIncludePaths": [
      "src/lib/scss"
    ]
  }
}

```
Which should produce this result:

// action-bar.scss
```
@use 'sass:map';

@use 'abstracts/variables' as variables;
@use 'abstracts/colors' as colors;
@use 'abstracts/mixins' as mixins;

@use 'components/common/cdkdraghandle';
...
```

But my IDE actually warns me that it cannot resolve the imports, AKA it doesn't work

![image](https://user-images.githubusercontent.com/10064887/146451768-16535044-b211-4c0f-a90b-dc5aa423ae21.png)

I have to write long imports to make it work, i.e: **@use '../../scss/abstracts/variables' as variables;**

I've taken a look about the [documentation ](https://github.com/ng-packagr/ng-packagr/blob/master/docs/style-include-paths.md)and it's far from being complicated, but doesn't seem to work in my case. Am I doing something wrong or is it a bug coming from the lib?

Thank you in advance for your insights

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 12.2.2
@angular/*: 12.2.10
typescript: 4.3.5
node: 16.10.0
npm/yarn: 8.1.3
@angular-devkit/build-angular: 12.2.14
```

**Comment by alan-agius4** [comment]
This is expected since `styleIncludePaths` only effect ng-packagr and not the IDE.

**Comment by Tim-arts** [comment]
Hello @alan-agius4, I meant like it was not working either while compiling the project. I guess the IDE is seeing something that might be not well set up somewhere

I have this architecture:
![image](https://user-images.githubusercontent.com/10064887/148853836-0374b325-5a2a-46b1-9fc4-4a832ab6b2e6.png)

// package.json
```
"exports": "./lib/scss/_index.scss"
```

// ng-package.json
```
{
  "$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
  "dest": "../../dist/core",
  "lib": {
    "entryFile": "src/public-api.ts",
    "styleIncludePaths": [
      "./src/lib/scss"
    ]
  },
  "assets": [
    "./src/lib/scss"
  ]
}

```

I'd like to call my library this way:
```
@import '~@ngx-chrono-ui-kit/core';
```
But every time I have this error, so it leads me to think there might be something wrong somewhere. Do you see anything that could help me?
![image](https://user-images.githubusercontent.com/10064887/148854010-9871acee-fbda-4664-83f5-fcf5a35a45b9.png)
