### ISSUE TITLE
Multiple sass import results bigger bundle size

### ISSUE THREAD

**Issue by saket-r** [ng-packagr/ng-packagr#2216]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description
When a library's component uses sass imports from third-party libraries.  Imagine a scenario where due to some dependency constraints of sass files or just because we want to club all the imports in a single file, we end up with importing multiple sass modules then, after compilation the compiled CSS ends up inside the compiled library (component style specifically).

This is not efficient because only the relevant part of CSS should end up inside the component.

for example 

In shared  demo application I am using only a single variable inside component but the compiled version would contain a lot of CSS which is not relevant to the component, which eventually increases the bundle size. 

#### How To Reproduce

PFA for the demo app [demo-app.zip](https://github.com/ng-packagr/ng-packagr/files/7830268/demo-app.zip)

build the library using `yarn run build:bar`

Observation: bundle size is too big because all the sass imports end up inside compiled component' style refer `dist/libs/bar/fesm2015/com.home-bar.js`

Note : I verified the similar behavior with version 10 as well. 

#### Expected Behavior

The compiled component style should only have relevant CSS. 

#### Version Information

PFA for demo-app in description

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: `12.2.5`
@angular/*: `^12.1.0`
typescript: `~4.3.5`
rxjs: `~6.6.0`
node: `v12.22.3`
npm/yarn: `yarn v1.22.5`
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_
"bootstrap": "^5.1.3",

**Comment by JoostK** [comment]
This is not a bug; there is simply no pruning of unused CSS rules (for any definition of _unused_, which is non-trivial).

**Comment by alan-agius4** [comment]
This is working as expected. Typically you want to avoid importing stylesheets that are meant to be used globally in components.
