### ISSUE TITLE
What is the Replacement for umdMoudleIds as it has been removed in V13.How can we do modularization.

### ISSUE THREAD

**Issue by JijiyaT** [ng-packagr/ng-packagr#2232]
![image](https://user-images.githubusercontent.com/98387144/150949221-61e43b8b-0365-47cd-b8d4-b30c575c3564.png)

**Comment by alan-agius4** [comment]
UMDs are no longer generated in v13.

No sure what you mean by modularization in this context.

**Comment by JijiyaT** [comment]
Thanks I get it.

But if unde are not generated will it not create any problem?
