### ISSUE TITLE
Cannot build library including math.div in SCSS

### ISSUE THREAD

**Issue by dimeloper** [ng-packagr/ng-packagr#2234]
## Type of Issue

```
[ x] Bug Report
[ ] Feature Request
```

## Description

I recently started trying to build a library of mine with `ng-packagr`. The problem is that my project heavily depends on divisions within my scss files, which as per latest sass recommendation I do with `math.div` instead of `/`.

Once I try to build my library I get the following error:
`Invalid CSS after " @return math": expected expression (e.g. 1px, bold), was "math.div`

I suspect this is related to having a sass peer dependency older than `1.33.0`.

#### How To Reproduce

Add a `math.div` in your library SCSS

#### Expected Behaviour

Library builds normally.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 13.2.0
@angular/*: 13.1.2
typescript: 4.5.4
rxjs: 7.5.2
node: 14.18.0
npm: 6.14.15
```

**Comment by SchnWalter** [comment]
The SCSS math.div function works just fine. By the looks of it, you most probably have a problem in your code. You should use a search engine to lookup that error, if not, you can always join a comunity and ask for help, this issue queue is for actually issues, not support.

> https://github.com/angular/angular/blob/13.2.0/CONTRIBUTING.md#question

**Comment by dimeloper** [comment]
Hey @SchnWalter I'm pretty sure I don't have a problem in my code since once I remove the `ng-packagr` dependency and I try a regular Angular build everything is fine.

**Comment by alan-agius4** [comment]
can you please run `npm ls sass`?

**Comment by dimeloper** [comment]
sure it is 
```
npm ls sass
ng-carrera@12.2.2 /Users/<username>/git-repos/ng-carrera
└─┬ @angular-devkit/build-angular@13.1.4
  └── sass@1.44.0
```

**Comment by alan-agius4** [comment]
`@angular-devkit/build-ng-packagr:build` is no longer supported.  Please use the `ng-packagr` builder in `@angular-devkit/build-angular`.

**Comment by dimeloper** [comment]
@alan-agius4 thanks for the hint, I updated the builder as you indicated, however I still get the error that I mentioned above:

`Error: Invalid CSS after "  @return math": expected expression (e.g. 1px, bold), was ".div($pixel, 16) * "
    at options.error (/Users/<username>/git-repos/my-library/node_modules/node-sass/lib/index.js:290:33) {
  status: 1,
  file: '/Users/<username>/git-repos/my-library/projects/my-library/abstracts/lib/_utilities.scss',
  line: 29,
  column: 15,
  formatted: 'Error: Invalid CSS after "  @return math": expected expression (e.g. 1px, bold), was ".div($pixel, 16) * "\n' +
    '        on line 29 of projects/my-library/abstracts/lib/_utilities.scss\n' +
    '        from line 1 of projects/my-library/abstracts/app-shell/_web-theme.scss\n' +
    '>>   @return math.div($pixel, 16) * 1rem;\n' +
    '\n' +
    '   --------------^\n'
}
`

**Comment by alan-agius4** [comment]
Form the error It’s seems that you opted to use node-sass.

Soemthing isn’t quite right, as node-sass I cannot be used in ng-packagr v13+.

Can you run `ng v` in `/Users/<username>/git-repos/my-library`?

**Comment by dimeloper** [comment]
sure, here is the output:

```
Angular CLI: 13.1.4
Node: 14.18.3
Package Manager: yarn 1.22.17
OS: darwin x64

Angular: 13.1.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1301.4
@angular-devkit/build-angular      13.1.4
@angular-devkit/build-ng-packagr   0.1002.0
@angular-devkit/core               13.1.4
@angular-devkit/schematics         13.1.4
@angular/cli                       13.1.4
@schematics/angular                13.1.4
ng-packagr                         13.2.0
rxjs                               7.5.2
typescript                         4.5.4
```

funnily enough, if I replace the `math.div`s in my scss files with `/` the build goes through..

**Comment by alan-agius4** [comment]
To be honest I cannot understand how node-sass is throwing the mentioned error. This is because in v13 node-sass cannot even be used as it was removed in favour of dart sass.

Since you are using yarn can you run the following in the library workspace (`/Users/<username>/git-repos/my-library`)

```
yarn why sass && yarn why node-sass
```

**Comment by dimeloper** [comment]
@alan-agius4 the output of the command is the following:

```
=> Found "sass@1.44.0"
info Reasons this module exists
   - "@angular-devkit#build-angular" depends on it
   - Hoisted from "@angular-devkit#build-angular#sass"
info Disk size without dependencies: "4.06MB"
info Disk size with unique dependencies: "5.02MB"
info Disk size with transitive dependencies: "9.07MB"
info Number of shared dependencies: 38
=> Found "ng-packagr#sass@1.33.0"
info This module exists because "ng-packagr" depends on it.
info Disk size without dependencies: "3.95MB"
info Disk size with unique dependencies: "4.26MB"
info Disk size with transitive dependencies: "8.31MB"
info Number of shared dependencies: 37
✨  Done in 0.96s.
yarn why v1.22.17
[1/4] 🤔  Why do we have the module "node-sass"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
error We couldn't find a match!
✨  Done in 0.92s.
```

however I saw that - since I have a custom styles builder - the package command corresponds me to a file where I use the following imports:
```

**Comment by alan-agius4** [comment]
`=> Found "ng-packagr#sass@1.33.0"` indicates that you lock file in un-maintained. 

Can you run the below to re-generate a fresh lock file? 

```
rm -rf node_modules yarn.lock
yarn
```

I am not sure what in happening in your project to be honest, `yarn` is reporting that you don't have `node-sass` installed. But the error clearly indicates that is being thrown by `node-sass`.

```
Error: Invalid CSS after "  @return math": expected expression (e.g. 1px, bold), was ".div($pixel, 16) * "
    at options.error (/Users/<username>/git-repos/my-library/node_modules/node-sass/lib/index.js:290:33) {
  status: 1,
```

Regarding to your custom styles builder, I am not sure what your builder is doing, how is it integrated in the build pipeline etc...

**Comment by dimeloper** [comment]
@alan-agius4 after I clean the dependencies and the `yarn.lock` file the error was gone, thank you for your help.
