### ISSUE TITLE
Ability to change package format to CommonJS

### ISSUE THREAD

**Issue by sir-captainmorgan21** [ng-packagr/ng-packagr#2242]
## Type of Issue

```
Not sure if this is a bug or not seeing a feature I can take advantage of
```

## Description
We have an angular library. We built and published a version of the library that resulted in a CommonJS module months ago. Now if I build that library with up to versions of angular and ng-packagr, it builds it as an esModule, even though we have the following tsconfig set up.

```
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "outDir": "../../out-tsc/lib",
    "target": "ES2019",
    "module": "CommonJS",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "sourceMap": false,
    "declaration": true,
    "removeComments": true,
    "noImplicitAny": true,
    "skipLibCheck": true,
    "strictPropertyInitialization": true,
    "strictNullChecks": true,
    "typeRoots": [
      "./node_modules/types"
    ],
    "types": [
      "jasmine",
      "node",
      "webdriverio/async"
    ],
    "lib": [
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "compilationMode": "partial",
    "skipTemplateCodegen": true,
    "strictMetadataEmit": true,
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true,
    "enableResourceInlining": true
  },
  "exclude": [
    "node_modules",
    "typescript"
  ]
}

```

#### How To Reproduce
Create a new angular project for publishing and update the tsconfig's module to CommonJS

#### Expected Behaviour
We'd expect it to still build a CommonJS module, but we aren't sure if this changed intentionally because of Ivy

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            13.1.3
@angular/compiler:     13.1.3
rollup:                2.64.0
typescript:            4.5.4
node: 16.12.0
npm/yarn: 8.1.0
```

**Comment by alan-agius4** [comment]
This is expected and is conformance with the [Angular package format](https://angular.io/guide/angular-package-format). 

Also, the Ivy linker only supports ESM modules by design.

**Comment by sir-captainmorgan21** [comment]
Anyone here, I created a angular builder forked off of https://github.com/pmachaux/ng-cli-tsc-builder. I updated that builder to copy over the package.json and README.md after running tsc. That package is available here: https://www.npmjs.com/package/@cptnmorgan/ng-cli-tsc-builder

**Comment by sir-captainmorgan21** [comment]
Also, if you are using nrwl, @nrwl/js executor works too
