### ISSUE TITLE
Renaming node_modules breaks package build

### ISSUE THREAD

**Issue by Hobart2967** [ng-packagr/ng-packagr#2248]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

When renaming node_modules to a name with a suffix, the build crashes instantly
```
[error] Error: Configuration doesn't match the required schema.
Data path "" should NOT have additional properties (LinkTarget).
    at ./node_modules/ng-packagr/lib/ng-package/discover-packages.js:71:23
    at Generator.next (<anonymous>)
    at fulfilled (./node_modules/ng-packagr/lib/ng-package/discover-packages.js:5:58)
```
#### How To Reproduce

1. Install Repo packages
2. Rename node_modules to node_modules_old because you want to re-install
3. Run build.

_Can you reproduce the error in the integration tests in ng-packagr?_ yes

#### Expected Behaviour

Old node_modules directory is ignored.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 9.1.5
@angular/*: does not matter
typescript: does not matter
rxjs: does not matter
node: 14.18.7
npm/yarn: does not matter
```

**Comment by alan-agius4** [comment]
Version 9 is no longer under support but from the looks of it, it appears that have an an invalid `LinkTarget` property in the configuration.

Please update to a more recent version.
