### ISSUE TITLE
Can't import custom type definitions

### ISSUE THREAD

**Issue by EoinGriffin-AI** [ng-packagr/ng-packagr#2250]
## Type of Issue

```
[X] Bug Report
[X] Feature Request

(not sure if this is a bug, or a missing feature... or if I'm just doing it wrong)
```

## Description

I have been using a JS library (d3-context-menu) successfully with ng-packagr up until now. Since upgrading to Typescript 4.4.2 I can't use the `require` syntax anymore for that version, so I'm forced to created a type definition file.
However, I cannot get my project to use this type definition at all.
It will work with another project that doesn't use ng-packagr, so there must be something I'm missing to get that type definition to work.

Help?
See here for a more detailed description of the problem, with screenshots: https://stackoverflow.com/questions/71178933/how-to-get-ng-packagr-to-recognize-a-typescript-type-definition

#### How To Reproduce

Import a JS library such as `d3-context-menu` and create a type definition for it.
Attempt to compile the project.

#### Expected Behaviour

Type definition should be recognized and allow the library to be used as it could be before, with the `require` syntax.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 12.1.2
@angular/*: 13
typescript: 4.4.2
```

**Comment by alan-agius4** [comment]
Hi @EoinGriffin-AI, 

I am unable to replicate the reported issue. Can you setup a minimal repro please? A good way to make a minimal repro is to create a new app via `ng new repro-app --no-create-application` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.
