### ISSUE TITLE
cant build due to "Optional chaining cannot appear in left-hand side"

### ISSUE THREAD

**Issue by ohabash** [ng-packagr/ng-packagr#2259]
## Type of Issue

```
[ x] Bug Report
```

## Description

After running `ng build my-publishable-module` I get an error durring build

> ✔ Compiling with Angular sources in Ivy partial compilation mode.
✖ Generating FESM2020
Optional chaining cannot appear in left-hand side (Note that you need plugins to import files that are not JavaScript)
Error: Optional chaining cannot appear in left-hand side (Note that you need plugins to import files that are not JavaScript)
    at error (/Users/omar/Sites/met-libs-nx/node_modules/ng-packagr/node_modules/rollup/dist/shared/rollup.js:159:30)
![Screen Shot 2022-02-28 at 5 58 56 PM](https://user-images.githubusercontent.com/15847500/156079049-6566d6b4-8480-4320-a04c-126676969c0d.png)

It looks like `@rollup@2.68.0`  (`/ng-packagr/node_modules/rollup/`) throws this error. 

There is a lot of chatter about this bug on rollup. but i have not found a solution. https://github.com/rollup/rollup/pull/3582

I tried all the suggestions with rollup and updating it within my project but no luck.

#### Version Information

```

Angular CLI: 13.1.3
Node: 14.16.0
Package Manager: npm 6.14.11
OS: darwin x64

Angular: 13.1.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.3
@angular-devkit/build-angular   13.1.3
@angular-devkit/core            13.2.5
@angular-devkit/schematics      13.2.5
@angular/cli                    13.1.3
@angular/fire                   7.2.1
@schematics/angular             13.2.5
ng-packagr                      13.1.3
rxjs                            6.6.7
typescript                      4.5.4
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by ohabash** [comment]
Just adding context. I asked the rollup community about the same problem and they mentioned an `Error.loc` or `Error.frame` file with more error context? I wonder if there are steps I can take to capture that output? 

I am working on a reproduction of the issue.

A direct solution would be nice however I am more than happy to read any debugging advice also. This error has be exhausting. Thank you!

https://github.com/rollup/rollup/issues/4420

**Comment by alan-agius4** [comment]
Printing the `fileInfo` on error https://github.com/rollup/rollup/blob/51cab92373bcf8c844a8de2a6765869f7eb05a5d/src/Module.ts#L836 should give should be enough to determine which file is causing the problem.

**Comment by alan-agius4** [comment]
I believe the problem is the below and since you are using casting you are also bypassing Typescript error reporting 

```
(this.schema?.fields as Field[])[e.previousContainer.data.index] = e.container.data.item;
    (this.schema?.fields as Field[])[e.container.data.index] = e.previousContainer.data.item;
    ```
