### ISSUE TITLE
ng build library crashes on Generating FESM2020

### ISSUE THREAD

**Issue by jacobdab** [ng-packagr/ng-packagr#2263]
## Type of Issue

```
[X ] Bug Report
[ ] Feature Request
```

## Description
I updated library from old angular 10 to angular 13. Additional package(storybook) that uses angular 13 to show what's there works fine, but when I try to build package using `ng build --prod` it crashes on `Generating FESM2020`. There is error:
`Optional chaining cannot appear in left-hand side (Note that you need plugins to import files that are not JavaScript)` ,but I checked all files and didn't notice any left-hand side optional chaining.

#### Expected Behaviour

Build without issues

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: "^13.0.0",
@angular/animations: "~13.2.0",
@angular/common: "~13.2.0",
@angular/compiler: "~13.2.0",
@angular/core: "~13.2.0",
@angular/forms: "~13.2.0",
@angular/platform-browser: "~13.2.0",
@angular/platform-browser-dynamic: "~13.2.0",
@angular/router: "~13.2.0",
typescript: "~4.5.2",
rxjs: "~7.5.0",
node: "v14.17.6",
npm/yarn: "6.14.15",
@storybook/angular: "^6.4.19",
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by alan-agius4** [comment]
This is likely an issue with your code. There is some information here https://github.com/ng-packagr/ng-packagr/issues/2259 on tracking this issue.

Unfortunately without a reproduction there isn’t anything we can do here.
