### ISSUE TITLE
Warnings for unused imports when packaging libraries

### ISSUE THREAD

**Issue by parky128** [ng-packagr/ng-packagr#2269]
I am working on an Nx powered monorepo, building a bunch of libs written in angular and packaged with ng-packagr.

When building the sources I am seeing a bunch of warnings like this:

WARNING: "DomSanitizer" is imported from external module "@angular/platform-browser" but never used in "xxx.js".

Example file:

**Typescript source:**

    import { Injectable } from '@angular/core';
    import { DomSanitizer } from '@angular/platform-browser';
    
    @Injectable()
    export class SomeService {
    
        constructor( public sanitizer:DomSanitizer) {
        }
    }

**Generated JS:**

    import { Injectable } from '@angular/core';
    import { DomSanitizer } from '@angular/platform-browser'; // warning about this not being used
    import * as i0 from "@angular/core";
    import * as i1 from "@angular/platform-browser";
    
    export class SomeService {
        constructor(sanitizer) {
            this.sanitizer = sanitizer;
        }
    }
    SomeService.ɵfac = i0.ɵɵngDeclareFactory({ minVersion: "12.0.0", version: "12.2.16", ngImport: i0, type: SomeService, deps: [{ token: i1.DomSanitizer }], target: i0.ɵɵFactoryTarget.Injectable });
    SomeService.ɵprov = i0.ɵɵngDeclareInjectable({ minVersion: "12.0.0", version: "12.2.16", ngImport: i0, type: SomeService });
    i0.ɵɵngDeclareClassMetadata({ minVersion: "12.0.0", version: "12.2.16", ngImport: i0, type: SomeService, decorators: [{
                type: Injectable
            }], ctorParameters: function () { return [ { type: i1.DomSanitizer }]; } });

indeed I can see the `DomSanitizer` import is not being used, but the tokenized `i1`.DomSanitizer is

Tsconfigs as follows..

tsconfig.lib.prod.json

    {
      "extends": "./tsconfig.lib.json",
      "compilerOptions": {
        "declarationMap": false
      },
      "angularCompilerOptions": {
        "compilationMode": "partial"
      }
    }

tsconfig.lib.json

    {
      "extends": "./tsconfig.json",
      "compilerOptions": {
        "outDir": "../../dist/out-tsc",
        "target": "es2015",
        "declaration": true,
        "declarationMap": true,
        "inlineSources": true,
        "types": [],
        "lib": ["dom", "es2018"]
      },
      "exclude": ["src/test-setup.ts", "**/*.spec.ts"],
      "include": ["**/*.ts"]
    }

How do I get rid of these warnings? Is there something misconfigured with how the libs are building and causing these duplicate\redundant imports?

Thanks

**Comment by alan-agius4** [comment]
Which version of ng-packagr are you using?

**Comment by parky128** [comment]
@alan-agius4 using 12.2.6

**Comment by alan-agius4** [comment]
These warnings as not actionable and therefore in version 13 we no longer emit them.

Please update to version 13.

**Comment by parky128** [comment]
OK, we are currently going through an effort of consolidating our code base split across many repo's (angular 9 apps) into an Nx monorepo, and are currently using v12 libs as that was latest version at time of us starting our migration work.

We will update to newer versions once we have moved all our code into the single repo, but for now we have to stick on 12. Is there anything that can configured ourside to stop these warning being emitted, or do we just have to live with them for now?

**Comment by alan-agius4** [comment]
There is no way to suppress these warnings in v12

**Comment by parky128** [comment]
ok thanks
