### ISSUE TITLE
Add support for __filename and __dirname

### ISSUE THREAD

**Issue by PashaTurok** [ng-packagr/ng-packagr#2313]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```
## Description
When we work with TS/JS we often need access to `__filename` and `__dirname`. When we develop angular application in order to get them we can use `"@angular-builders/custom-webpack:browser"` builder with custom custom webpack config:

```
export default (config: webpack.Configuration, options: CustomWebpackBrowserSchema, targetOptions: TargetOptions) => {
  config.node = {
    __filename: true,
    __dirname: true
  };
  return config;
}
```
However, this solution can't be used for angular libraries because they are not built with webpack.

As I know angular libraries are built with ng-packagr that uses rollup. Rollup can be configured to use these variables. So, it would be very nice to support these variables in ng-packagr so they can be used in angular libraries. Please note, that I mean relative paths to library root.

**Comment by alan-agius4** [comment]
Can you please elaborate to why you need to use `__filename` and `__dirname`? 

Using Node.JS specific APIs is not considered as a good practice especially in an Angular application / libraries where their primary channel is a browser.

**Comment by PashaTurok** [comment]
@alan-agius4 We use them for your enterprise framework. 

Yes, Angular is used first of all for browsers, but it doesn't mean that these variables are not used in browser applications. Please, the the following SO questions: [this](https://stackoverflow.com/questions/43527016/dirname-is-not-working-in-node-js-with-webpack-bundling) - 10K views, and [this](https://stackoverflow.com/questions/36090842/webpack-can-not-use-dirname) - 12K views.

**Comment by alan-agius4** [comment]
> Yes, Angular is used first of all for browsers, but it doesn't mean that these variables are not used in browser applications.

In general, using these variables outside of server context is an indicative of a code smell.

@PashaTurok, can you please provide a real world use-case where you need to use `__filename` and `__dirname`?

**Comment by PashaTurok** [comment]
> > Yes, Angular is used first of all for browsers, but it doesn't mean that these variables are not used in browser applications.
> 
> In general, using these variables outside of server context is an indicative of a code smell.
> 
> @PashaTurok, can you please provide a real world use-case where you need to use `__filename` and `__dirname`?

I have provided links that prove that these variables are used by many people. Their support was SPECIALLY added to webpack but you say this is a code smell. I'm afraid I can't agree with you.

You are asking a real case. For example, they can be used for logging:

```    
 logger: Logger = LoggerFactory.getLogger(__filename);
```

**Comment by alan-agius4** [comment]
> Their support was SPECIALLY added to webpack but you say this is a code smell

In general, Webpack specific functionalities are not supported. Ex: esbuild which will be available as an opt-in experimental builder in Angular CLI version 14 doesn't support these https://github.com/evanw/esbuild/issues/859.

The fact that the Angular CLI uses Webpack and ng-packagr uses Rollup is an implementation detail. From the example above, I am not sure why you need to provide the filename to a logger as typically this is available in the stacktrace.  Typically in such cases, `getLogger` method would be provided with an application/library name, feature name or class name. 

Also,  `__filename` and `__dirname` are not available in ESM modules even on the server, so using these APIs isn't correct IMHO.

**Comment by alan-agius4** [comment]
Closing as per above explanation.

**Comment by PashaTurok** [comment]
If someone understands what I mean, please, reopen this feature. __filename and __dirname are powerful feature that let to automate many things to avoid using `an application/library name, feature name or class name`.
