### ISSUE TITLE
Feature/Question: ng-package.json and preprocessor paths compatibility with IDEs

### ISSUE THREAD

**Issue by GitPaulo** [ng-packagr/ng-packagr#2315]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description
I may be ignorant about if this is the right thing to request, however, here it goes:

**Feature:**  IDE support for the `styleIncludePaths` specified in `ng-package.json` like so:

```json
// ng-package.json
{
  "$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
  "dest": "../../dist/core",
  "lib": {
    "entryFile": "src/public-api.ts",
    "styleIncludePaths": [
      "path/to/my/styles/"
    ]
  }
}
```

```less
// some less file in the project where 'something.less is in path/to/my/styles/'
@import (reference) 'something.less'
```
Despite this setup working fine for builds, the IDE wouldn't know if that path is valid during development since ng-packagr is the one handling them during the build phase. What are your recommendations to deal with these errors? 

Are there any IDE ng-packagr plugins that can solve this issue?

Thanks.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 13.3.1
@angular/*: 13.2.4
typescript: 4.5.2
rxjs: doesnt matter
node: 14.19.1
npm/yarn: using npm from that node verison
```

**Comment by alan-agius4** [comment]
Unfortunately, not that I am aware of. Note, that this issue does't only effect ng-packagr.

See: https://github.com/mrmlnc/vscode-scss/issues/41
