### ISSUE TITLE
Autoprefixer warnings from dependencies

### ISSUE THREAD

**Issue by Martinspire** [ng-packagr/ng-packagr#2316]
Right now I have 2 dependencies in my project, a leafletjs css and tailwind forms plugin which both have a line in their (S)CSS:
`color-adjust: exact;`

When processed by autoprefixer, I get this warning about it:
`./apps/<my project with tailwind imports>/src/styles.scss.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[6].rules[0].oneOf[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[6].rules[0].oneOf[0].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[6].rules[1].use[0]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[6].rules[1].use[1]!./apps/<my project>/src/styles.scss - Warning: Module Warning (from ./node_modules/postcss-loader/dist/cjs.js):`
`Warning`

`(1:1) autoprefixer: Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.`

Now I can understand why one would want to fix this, but as I said, I'm using dependencies so these are outside of my project files inside the node modules. Tailwind is imported into the styles.scss, but the error is actually from a dependency in the tailwind configuration.

And for leafletjs the import is in my angular.json (which then gets put into the front of the error message).

I wouldn't be as bothered with this issue if it didn't display it every time I build the app and into the browsers console as well. It doesn't look like something that should be done like this. Especially seeing that its a dependency that I'd rather not override.

Right now I can either create a copy from the files and make a duplicate plugin or css file where I manually fix it. Or modify the source files themselves and retry every time it gets updated. Or try to find a different dependency. Or try with a custom builder or whatever.

So my point is this: 

Every time any dependency breaks an autoprefixer rule, I'm going to get a warning again. To me that doesn't seem fair. Dependencies shouldn't generate warnings like these and it should be easier to ignore the messages (unless I'm missing something here). That also goes for displaying these warnings in your browser console when running the app. I don't really see the benefit of doing that when its already on the console you run the application from. When compilation is broken, files are missed or major issues happen with CSS I can see why you would want to alert the browser, but for these deprecation messages on dependencies that aren't even mine, it seems weird to push them out like this. The more messages you get this way, the easier people start to ignore their consoles and terminals. Not to mention that this line in particular is still going to work on browsers and its more that autoprefixer decided that there is enough support to require the `print` prefix.

**Comment by alan-agius4** [comment]
The warning above doesn't seem to be coming from ng-packagr compilation, but rather from the application compilation. Ng-packagr doesn't use webpack and doesn't support tailwindcss. 

My recommendation however would be to file an issue with the libraries that are using `color-adjust` and request this to be changed. This seems to be the long term better solution.
