### ISSUE TITLE
Package path ./assets/fonts/font.ttf is not exported from package .../project-name/node_modules/@namespace/roject-name

### ISSUE THREAD

**Issue by sergsar** [ng-packagr/ng-packagr#2331]
## Type of Issue

```
[ ] Bug Report
```

## Description

I'm running an application with my compiled library and have an error: 
`Package path ./assets/fonts/font.ttf is not exported from package .../project-name/node_modules/@namespace/project-name
`

Assets export from library ng-package.json:
```
	"$schema": "...",
	"dest": "...",
	"assets": [
		"./templates/**/*.template",
		"./application/styles/**/*.scss",
		"./assets/**/*.*",
		"ngcc.config.js"
	],
	"lib": {...}
```

Export from library package.json:

```
	"exports": {
		"./assets": "./assets/**/*.*"
	},
```

#### How To Reproduce
Compile any library with any fonts in assets and try to use the library in new project.
The library must use fonts from assets in its styles.css

#### Expected Behaviour

Could use fonts from library assets in the library css files

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 13.3.1
@angular/*: 13.2.0
typescript: 4.6.3
rxjs: 7.0.0
node: 16.13.0
npm: 8.1.0
```

**Comment by JoostK** [comment]
Did you follow https://angular.io/guide/creating-libraries#managing-assets-in-a-library? Also see #2149

**Comment by sergsar** [comment]
Yea, I followed. In my library css file I use fonts from assets like this:

```
@font-face {
	font-family: 'Open Sans';
	font-style: normal;
	font-weight: 400;
	src: url('~@namespace/my-project/assets/fonts/opensans.woff') format('woff');
}
```

**Comment by sergsar** [comment]
Fixed I have Changed
```
"exports": {
		"./assets": "./assets/**/*.*"
},
```
to

```
"exports": {
		"./assets/": "./assets/"
},
```
