### ISSUE TITLE
"Preferred way" of providing service in a module causes circular dependency warning

### ISSUE THREAD

**Issue by ArtemFrontendACTUM** [ng-packagr/ng-packagr#2335]
## Type of Issue

```
[✅] Bug Report
[ ] Feature Request
```

## Description
"Preferred way" of providing service in a module causes circular dependency warning

#### How To Reproduce
1. Use the code from official docs:  https://angular.io/guide/providers#providedin-and-ngmodules
2. Try to build the lib with `ng-packagr`

#### Version Information

```
node: v14.17.0
yarn: 1.22.18
ng-packagr: 12.0.0
@angular/compiler: 12.2.16
rollup: 2.71.1
typescript: 4.3.5
```

**Comment by uamanager** [comment]
Hey, it seems like you misunderstood documentation. It shows two methods of providing service inside module. You can choose one, but don't use both.

**Comment by f1ames0ff** [comment]
@uamanager OMG, yes, you're right. Sorry for inconvenience and thanks for pointing out.
