### ISSUE TITLE
Do library SCSS files have to be named _index.scss or index.scss?

### ISSUE THREAD

**Issue by fireflysemantics** [ng-packagr/ng-packagr#2337]
I packaged a library with a theme file.  I can import the theme file with `@use` if I name the theme file `_index.scss` or `index.scss`.  But if I call it `big.component.theme.scss` and use 

```
@use "@fireflysemantics/big-packaged-component-example/big.component.theme" as theme;
```

To try to import it I get errors.  I've written all this up on Stackoverflow here.

https://stackoverflow.com/questions/72334505/how-to-import-angular-13-library-packaged-sass

Do we have to name theme files `_index.scss` or `index.scss`?

**Comment by alan-agius4** [comment]
Closing as it's answered on Stackoverflow.
