### ISSUE TITLE
Confusing documentation

### ISSUE THREAD

**Issue by avocadosarelife** [ng-packagr/ng-packagr#2353]
## Type of Issue

```
[ ] Bug Report
[x?] Feature Request
```

## Description

Hello, 
I need some help understanding the documentation to copy the assets in an angular library: 
https://github.com/ng-packagr/ng-packagr/blob/main/docs/copy-assets.md

> You can copy these assets by using the assets option.

In which file should this be? `ng-package.json` or `package.json` ?

Then there is an example in `package.json`  which does not include neither an assets array nor a ngPackage object:

```
{
  "name": "your-library",
  "version": "1.2.3",
  "exports": {
    ".": {
      "sass": "./_index.scss"
    },
    "./styles/dark-theme": {
      "sass": "./styles/_dark-theme.scss"
    },
    "./styles/light-theme": {
      "sass": "./styles/_light-theme.scss"
    }
  },
  "peerDependencies": {
    ...
  },
  "dependencies": {
    ...
  }
}
```
 
Could you please clarify this? That would be greatly appreciated, as there isn't that much information available in the documentation I have found until now. 

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 11.0.0
@angular/*: 11.1.0
```

Thank you for the awesome library! : )

**Comment by alan-agius4** [comment]
The config mentioned above is for package `exports` which is need to **export styles**. This config is used by the consumers of the library and not by ng-packagr. This option doesn't configure how assets are copied but it's just a way for the library author to define their public API. 

On the other-hand, the `assets` configuration which is needed to configure your build to copy the assets needs to be set in `ng-package.json` configuration file,

You can read more about this here
- https://angular.io/guide/angular-package-format#packagejson
- https://angular.io/guide/creating-libraries#managing-assets-in-a-library

Package exports documentation
- https://nodejs.org/api/packages.html#package-entry-points
