### ISSUE TITLE
[Bug] ng-packagr does not emit declaration files

### ISSUE THREAD

**Issue by arturovt** [ng-packagr/ng-packagr#2369]
## Type of Issue

```
[x] Bug Report
```

## Description

`ng-packagr` does not emit declaration file for all of the compilation targets.

This happens with `ng-packagr@14`. So this seems to be a regression.

#### How To Reproduce

Steps:

```sh
$ git clone git@github.com:single-spa/single-spa-angular
$ cd single-spa-angular
$ yarn --frozen-lockfile
$ yarn ng-packagr -p libs/single-spa-angular/ng-package.json
```

The output folder is `lib`. Go to `lib/src/public_api.d.ts` and see that `single-spa-angular.d.ts` does not exist. You'll see the following code:

```ts
// lib/src/public_api.d.ts
export { enableProdMode } from './prod-mode';
export { singleSpaAngular } from './single-spa-angular'; // Cannot find module './single-spa-angular' or its corresponding type declarations.
export { getSingleSpaExtraProviders } from './extra-providers';
```

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            14.0.2
@angular/compiler:     14.0.2
rollup:                2.75.7
typescript:            4.7.4
```

**Comment by arturovt** [comment]
Hey @alan-agius4 . I've tried your changes locally and it doesn't seem to fix the issue. I've built `ng-packagr` locally and installed it into a workspace, this is the `cache-compiler-host` file:

![image](https://user-images.githubusercontent.com/7337691/177190003-9448f41b-3027-41d4-995f-a6f94b30450c.png)

The declaration file still does not exist:

![image](https://user-images.githubusercontent.com/7337691/177190069-1ef2ae0d-f589-4b18-aef2-8ab1b0f12b84.png)

**Comment by alan-agius4** [comment]
I am no longer able to replicate this.

```
$ cat lib/src/single-spa-angular.d.ts
import { LifeCycles } from 'single-spa';
import { SingleSpaAngularOptions } from './types';
export declare function singleSpaAngular<T>(userOptions: SingleSpaAngularOptions<T>): LifeCycles<T>;
 
```
