### ISSUE TITLE
Do not know how to serialize a BigInt

### ISSUE THREAD

**Issue by TomMettam** [ng-packagr/ng-packagr#2375]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description

When building an angular library, I get the error "Do not know how to serialize a BigInt"

My project does use BigInts, but doesn't attempt to serialize them at any point

```
------------------------------------------------------------------------------
Building entry point '@genius/frontend'
------------------------------------------------------------------------------
✔ Compiling with Angular sources in Ivy full compilation mode.
✖ Generating FESM2020
Do not know how to serialize a BigInt
```

#### How To Reproduce

It's unclear exactly what is being serialized here so I don't know how to reproduce the error

#### Expected Behaviour

Project should build

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            14.0.3
@angular/compiler:     14.0.5
rollup:                2.75.7
typescript:            4.7.4
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by alan-agius4** [comment]
Hi @TomMettam,

I am unable to replicate. Can you please provide a minimal reproduction?

**Comment by alan-agius4** [comment]
I suspected that it might be rollup, but without a reproduction it is hard to tell what is happened.

**Comment by TomMettam** [comment]
Hello.

Creating a minimal reproduction isn't feasible for me because my project is huge, and the error reported from ng-packagr isn't in any way helpful in knowing what might be triggering the errror. So I added some code to diagnose the issue.  

The exception is thrown in `rollup.js` with the following line:

`await (0, cache_1.saveCacheEntry)(cacheDirectory, opts.cacheKey, JSON.stringify(bundle.cache));`

I added some code to scan the object for bigints, and it spat out the following:


```
modules[3].ast.body[7].declaration.body.body[0].value.body.body[0].alternate.alternate.alternate.alternate.alternate.alternate.alternate.consequent.body[0].alternate.consequent.body[0].alternate.alternate.alternate.body[1].test.right.argument.value
bigint found at modules[3].ast.body[7].declaration.body.body[0].value.body.body[0].alternate.alternate.alternate.alternate.alternate.alternate.alternate.consequent.body[0].alternate.alternate.body[0].alternate.alternate.alternate.body[1].test.right.value
bigint found at modules[3].ast.body[7].declaration.body.body[0].value.body.body[0].alternate.alternate.alternate.alternate.alternate.alternate.alternate.alternate.consequent.body[0].consequent.body[0].test.right.argument.value
bigint found at modules[3].ast.body[7].declaration.body.body[0].value.body.body[0].alternate.alternate.alternate.alternate.alternate.alternate.alternate.alternate.consequent.body[0].alternate.test.right.value
bigint found at modules[4].ast.body[5].declaration.body.body[13].value.body.body[5].consequent.body[0].argument.left.value
bigint found at modules[4].ast.body[5].declaration.body.body[18].value.body.body[3].body.body[1].expression.right.right.value
```

I don't really know what any of these properties mean, but can you tell me, based on this, where the troublesome bigint may be sitting?

**Comment by alan-agius4** [comment]
Thanks for the above, so it appears to be this line https://github.com/ng-packagr/ng-packagr/blob/9b93a18d8673b6b788e35916518f241e981c302b/src/lib/flatten/rollup.ts#L83 that is causing the problem.

**Comment by TomMettam** [comment]
Well, I'm not sure if that is the "cause", it's the contents of bundle.cache which are the issue - there's a bigint in there which JSON.stringify can't serialize

**Comment by rehdie** [comment]
I've patched the script ng-packagr/src/lib/flatten/rollup.ts to find out, where the BigInt is located:
```
try {
	await (0, cache_1.saveCacheEntry)(cacheDirectory, opts.cacheKey, JSON.stringify(bundle.cache));
} catch(error) {
	console.log("Try to find a BigInt in the bundle cache....");
	const results = [];
	findBigintInCache("", bundle.cache, results);
	console.log("Results: ", results);
	throw error;
}


function findBigintInCache(path, cachedObject, results) {
	
	//console.log("Try to find a BigInt in the bundle cache: ", path);

	if (cachedObject === null || cachedObject === undefined) {
		return;
	}

	switch(typeof cachedObject) {
		case "bigint":
			results.push(`${path} is a bigint: ` + cachedObject);
			break;

		case "number":
		case "boolean":
		case "string":
		case "symbol":
		case "undefined":
			break;

		case "object": 
			if (cachedObject instanceof Date) {
				return;
			}
			if (Array.isArray(cachedObject)) {
				for (let i=0; i < cachedObject.length; i++) {
					findBigintInCache(`${path}[${i}]`,cachedObject[i], results);
				}	
			} else {
				const keys = Object.getOwnPropertyNames(cachedObject);
				for (const key of keys) {
					const value = cachedObject[key];
					findBigintInCache(`${path}.${key}`, value, results);
				}
			}
			break;
	}
}
```
And this was the result:
```
Results:  [
  '.modules[193].ast.body[3].declaration.body.body[3].value.body.body[7].declarations[0].init.value is a bigint: 97',
  '.modules[193].ast.body[3].declaration.body.body[3].value.body.body[10].argument.right.value is a bigint: 1'
]
```

BigInt literals like 1n or 97n produce this kind or error. Replace them with BigInt(1) (resp. BigInt(97)) and the problem is gone.

Hope that helps.....

**Comment by ssams** [comment]
just stumbled across this, with the confusing behavior that it didn't compile locally but working without issues in the CI build ... as ng-packagr automatically disables the cache in CI environments, the error may be hidden / not reproducible in some environments.

https://github.com/ng-packagr/ng-packagr/blob/2c618aeac51b3c4a2a1dd75b42653e4dd7bc1ff3/src/lib/ng-package/options.di.ts#L23-L24

the issue is also triggered by BigInt literal in my code (same error message as in the original description), I can confirm replacing `1n` with `BigInt(1)` as suggested by @rehdie as workaround. Alternatively disabling the Angular cache (and therefore also ng-packagr cache apparently) worked, could be also another reason why it sometimes may not be reproducible.

**Comment by MPalix86** [comment]
"The same error occurs! Wrapping bigint literals with BigInt() works!"

**Comment by S4elkyn4eGGG** [comment]
Jusr replace
const n: bigint = 9007199254740991n;
with
const n: bigint = BigInt('9007199254740991n');

**Comment by S4elkyn4eGGG** [comment]
Just replace
const a: bigint = 1_099_511_628_211n;
with
const a: bigint = BigInt('1099511628211');
