### ISSUE TITLE
Linking a re-exported secondary entry point fails when building a library

### ISSUE THREAD

**Issue by JesseDeBruijne** [ng-packagr/ng-packagr#2378]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

When I link a library with a secondary entry point which is re-used in the main entry point, building the library fails.

#### How To Reproduce

I have a library with multiple entry points.

```
- projects
| - my-lib
| - - shared
| - - - public-api.ts <-- export * from "./shared.module.ts";
| - - - ng-package.json
| - - - shared.module.ts
| - - src
| - - - public-api.ts <--- export * from "@scope/my-lib/shared";
| - - ng-package.json
| - - package.json <-- name: "@scope/my-lib"
```

projects/my-lib/ng-package.json
```
{
  "$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
  "dest": "../../dist/my-lib",
  "lib": {
    "entryFile": "src/public-api.ts"
  }
}
```

projects/my-lib/shared/ng-package.json
```
{
  "$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
  "lib": {
    "entryFile": "./public-api.ts"
  }
}
```

The idea is that you can import the `SharedModule` from both `my-lib` and `my-lib/shared`. The `SharedModule` is then used for other secondary entry points in `my-lib`.

When I do:
```
import { SharedModule } from "@scope/my-lib";
```
and then run
```
npm link @scope/my-lib
ng build example-lib
```
in another library, this breaks **only when linked**, with the following error:
```
../my-lib/dist/my-lib/public-api.d.ts - error TS2307: Cannot find module '@scope/my-lib/shared' or its corresponding type declarations.
```

It also broke when I ran `ng build` to build the _application_ the example-library is in, but that was remedied by adding: `preserveSymLinks: true` in the `angular.json` for that project. However, I cannot add this to the build of the library because it is not allowed.

When `@scope/my-lib` is published and then imported, running `ng build example-lib` succeeds as expected.

#### Expected Behaviour

I expect that running `ng build example-lib` in this scenario succeeds also with a linked version of `@scope/my-lib`.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 14.0.5
@angular/*: 14.0.5
typescript: 4.6.4
rxjs: 7.5.5
node: 16.13.1
npm: 8.12.1
```

**Comment by Ravi-Bossema** [comment]
I'm running into this too

**Comment by TiagoPT** [comment]
I have the same issue as well.

**Comment by alan-agius4** [comment]
This looks like a misconfiguration of TypeScript path mappings. Make sure you have configured path mappings for both the main and secondary entry-points in your `tsconfig.json`.

**Comment by JesseDeBruijne** [comment]
> This looks like a misconfiguration of TypeScript path mappings. Make sure you have configured path mappings for both the main and secondary entry-points in your `tsconfig.json`.

In my `tsconfig.lib.json`, I have the following:

```
"paths": {
  "@scope/*": [
    "node_modules/@scope/*"
  ]
}
```

And it's still throwing the same error. This path mapping looks sufficient to me, is it not?

**Comment by JesseDeBruijne** [comment]
> @JesseDeBruijne, could you try to enable `preserveSymLinks: true` in the libraries tsconfig? Also, you could enable ["traceResolution" ](https://www.typescriptlang.org/tsconfig#traceResolution) to see the resolution algorithm that TypeScript is following as if you'd need additional path mappings.
> 
> I you can share a self contained runnable reproduction I can take a look.

Looks like adding `preserveSymLinks: true` to the `tsconfig.lib.json` works. Not sure why but I thought this was an option only in `angular.json`. Then again, this ticket is over a year old.

Thanks for the reply @alan-agius4 👍
