### ISSUE TITLE
Entry point doesn't exist when path is equal to package.json name

### ISSUE THREAD

**Issue by Noeldeveloper** [ng-packagr/ng-packagr#2386]
## Type of Issue

```
[ ] Bug Report
```

## Description

When trying to build a library, it fails giving that error:
Entry point @tools/mylibrary/package1 which is required by @tools/mylibrary doesn't exists.

#### How To Reproduce

Type @tools/mylibrary as name in package.json inside projects folder.

Create a path in tsconfig.json like that:

    "paths": {
      "@tools/mylibrary": ["projects/main/public-api"],
      "@tools/mylibrary/package1": ["projects/main/package1/public-api"],
      "@tools/mylibrary/package2": ["projects/main/package2/public-api"]
    }

You could reproduce it in stackblitz launching npm i, and npm run build.
https://stackblitz.com/edit/ng14-library?file=testproject/package.json

Stackblitz code uploaded to: https://github.com/Noeldeveloper/ng14-library

#### Expected Behaviour

Correct build.

#### Version Information

```
ng-packagr: 14.0.4
@angular/*: 14.0.6
typescript: 4.7.4
rxjs: 7.5.6
node: 16.14.2
npm: 7.17.0
```

**Comment by Noeldeveloper** [comment]
> That's because they don't exist in your repo, you should check the release notes for breaking changes:
> 
> > package.json is not longer a valid method to configure ng-packagr. Use ng-package.json instead.
> 
> https://github.com/ng-packagr/ng-packagr/releases/tag/v14.0.0

I'm using ng-package.json to set main library entryFile. 
I've tried to use ng-package.json inside each package instead of package.json, and i get that error.
Configuration doesn't match the required schema.
Data path "" must NOT have additional properties (ngPackage).

I think problem is related with library name. It forces me to avoid using an alias of tsconfig.json paths field as library name.

You could launch ng build and see that problem here:
https://stackblitz.com/edit/ng14-library?file=testproject%2Fprojects%2Fmain%2Fpackage.json

**Comment by alan-agius4** [comment]
> Configuration doesn't match the required schema.
Data path "" must NOT have additional properties (ngPackage).

The error indicates that you are providing the values in and `ngPackage` which is not correct. 

```diff
{
-  "ngPackage": {
    "lib": {
      "entryFile": "./public-api.ts"
    }
-  }
}
```

**Comment by Noeldeveloper** [comment]
> > Configuration doesn't match the required schema.
> > Data path "" must NOT have additional properties (ngPackage).
> 
> The error indicates that you are providing the values in and `ngPackage` which is not correct.
> 
> ```diff
> {
> -  "ngPackage": {
>     "lib": {
>       "entryFile": "./public-api.ts"
>     }
> -  }
> }
> ```

I was done that change but still getting error. It's curious for me, if i set package.json name: "something" it builds correctly. But if i use "@tools/mylibrary", this is same as  alias of my base entry point, it fails.

https://stackblitz.com/edit/ng14-library?file=testproject/projects/main/package.json

**Comment by alan-agius4** [comment]
@Noeldeveloper, In the above repro you are still using `package.json` in the secondary entry-points. As previously mentioned this is no longer supported. Please use `ng-package.json`.

**Comment by Noeldeveloper** [comment]
> @Noeldeveloper, in the above repro you are still using `package.json` in the secondary entry-points. As previously mentioned this is no longer supported. Please use `ng-package.json`.

Solved! sorry for misunderstanding and thank you so much!
