### ISSUE TITLE
EISDIR: illegal operation on a directory, link. Angular 14.1.0

### ISSUE THREAD

**Issue by alan-agius4** [ng-packagr/ng-packagr#2388]
### Which @angular/* package(s) are the source of the bug?

upgrade

### Is this a regression?

No

### Description

Hi,

I have an angular library that I use in my project, I've just upgraded it to the latest version of angular, but when I try to build it I get the error below.

Please note: "X:\Project" is a sample.

EISDIR: illegal operation on a directory, link 'X:\Project.angular\cache\14.1.0\ng-packagr\tmp\09275629' -> 'X:\Project.angular\cache\14.1.0\ng-packagr\content-v2\sha512\2e\ca\d92807e329207635dd2b2744c9a2df00346a5ea7cf149ec7b3eae929c62f22e6e1cbe4765ac46d8b36d37b16fb5156b0e5854d0cc7e508af1a179e47313e'

### Please provide the exception or error you saw

```true
EISDIR: illegal operation on a directory, link 'X:\Project.angular\cache\14.1.0\ng-packagr\tmp\09275629' -> 'X:\Project.angular\cache\14.1.0\ng-packagr\content-v2\sha512\2e\ca\d92807e329207635dd2b2744c9a2df00346a5ea7cf149ec7b3eae929c62f22e6e1cbe4765ac46d8b36d37b16fb5156b0e5854d0cc7e508af1a179e47313e'
```

**Comment by alan-agius4** [comment]
Can you please provide the output of `ng v` @KennethUdoh?

**Comment by KennethUdoh** [comment]
Hi,

Please see below:


[image: image.png]

**Comment by KennethUdoh** [comment]
Hi,

Please see attached file.

Kenneth Udoh

**Comment by alan-agius4** [comment]
@KennethUdoh, 

Please copy and paste the output in the issue. Thanks.

**Comment by KennethUdoh** [comment]
![Version](https://user-images.githubusercontent.com/25224132/180746349-25761af1-cec0-483a-a014-a73f52dfb786.png)

**Comment by alan-agius4** [comment]
Please refrain from using images as they are not showing. Please copy and paste the output from your terminal. Thanks.

**Comment by KennethUdoh** [comment]
Ok, sorry about that.

**Comment by KennethUdoh** [comment]
@alan-agius4, 

Please let me know when there is a resolution to this issue.

Thanks

**Comment by Classic-Repo** [comment]
@alan-agius4 is there any update on this open issue?

**Comment by alan-agius4** [comment]
I am unable to reproduce this. Does the issue persists if you delete the cache directory?

**Comment by Classic-Repo** [comment]
@alan-agius4 

You mean in the .angular directory? Yes, I deleted the entire .angular folder, then deleted the package.lock.json file and also deleted ngmodules folder and I did npm install.

The problem happens when I try to build the library, and please note that it's a library.

It happened when I did an upgrade of the library to the latest version of angular.

**Comment by alan-agius4** [comment]
Can you setup a minimal repro please?

A good way to make a minimal repro is to create a new app via `ng new repro-app --no-create-application` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by Classic-Repo** [comment]
@alan-agius4 

I will do that, please give me a some time.

**Comment by Classic-Repo** [comment]
@alan-agius4 ,

I have created the repro library as you told me and it works, but my project is not stored on the local drive and this is the problem because when I copied it from it's current location to the local drive, it builds as normal and I need to have the project stored externally. Can this be rectified please?

**Comment by alan-agius4** [comment]
Do you have a stack trace or log file by any chance?

**Comment by Classic-Repo** [comment]
@alan-agius4 ,

Sorry I don't, the problem happens when I build the library. Can I push the one I have just created? Then you can try and build it on an external hard drive and you will see the error, or you can create a new library, then try to build it on an external hard drive.

**Comment by alan-agius4** [comment]
This seems to be caused by this https://github.com/npm/cacache/blob/71d4389ff8a35330c3fedce97761094e243d4faf/lib/util/move-file.js#L22. As a workaround you can disable caching. See: https://angular.io/cli/cache

Unfortunately this is not actionable from our end.
