### ISSUE TITLE
Compilation fails silently, the target is simply missing from destination directory

### ISSUE THREAD

**Issue by csisy** [ng-packagr/ng-packagr#2405]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

There is a special compilation issue that does not emit any error and it says the library is built successfully. However, the `dist` folder does not contain the component, nor the type definition file, nothing. (Not a workspace issue, after fixing the problem, the component is built successfully).

#### How To Reproduce

Given a component class that defines a function that tries to get its parameter type from a member variable:

```typescript
class MyComponent {
  protected myVariable: /*...*/;

  myFunc(param: typeof this.myVariable): void { /* ... */ }
}
```

For some reason this causes an "invisible error", however I don't see why it sould not [work](https://typescript-neenyn.stackblitz.io).

#### Expected Behaviour

If there is any error, the compilation must not succeed and the error message must be written to the console.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            14.1.0
@angular/compiler:     14.1.0
rollup:                2.77.2
typescript:            4.6.4
```

**Comment by alan-agius4** [comment]
Hi @csisy, I am unable to replicate the problem with the steps provided.

**Comment by csisy** [comment]
> Hi @csisy, I am unable to replicate the problem with the steps provided.

I will try to create a pack and upload it somewhere. Thank you!

**Comment by csisy** [comment]
Sorry for the delay, [here is the repo](https://github.com/csisy/compile-error-repro) with a freshly created angular library.

1. Run `npm run build` to compile the library
2. Examine the `dist/my-lib/lib` directory: only the `ok.d.ts` file is there, the `not-ok.d.ts` is missing
3. Open the `projects/my-lib/src/lib/not-ok.ts`
4. Change the "not working" `foo` to the working one
5. Compile the project again
6. Check the dist folder again (the `not-ok.d.ts` file is there)

Output of `ng version`

```
Angular CLI: 14.2.1
Node: 14.17.5
Package Manager: npm 7.24.2
OS: win32 x64

Angular: 14.2.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.1
@angular-devkit/build-angular   14.2.1
@angular-devkit/core            14.2.1
@angular-devkit/schematics      14.2.1
@angular/cli                    14.2.1
@schematics/angular             14.2.1
ng-packagr                      14.2.0
rxjs                            7.5.6
typescript                      4.7.4
```
