### ISSUE TITLE
After upgrading vom Angular v13 to v14 (ng-packagr 13.1.3 to 14.2.0) I get error "EINVAL: invalid argument, link..."

### ISSUE THREAD

**Issue by sekoch29** [ng-packagr/ng-packagr#2416]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description

Upgrading angular v13 library to v14. After I have upgraded everything (with guide on update.angular.io), I try to run "ng build library" and receive the following error:

```
ng build components --configuration production

Building Angular Package

------------------------------------------------------------------------------
Building entry point 'components/src/lib/badge'
------------------------------------------------------------------------------
✖ Compiling with Angular sources in Ivy partial compilation mode.
EINVAL: invalid argument, link 'V:\DevOps\Common.Angular.Components\.angular\cache\14.2.1\ng-packagr\tmp\43b2fa7b' -> 'V:\DevOps\Common.Angular.Components\.angular\cache\14.2.1\ng-packagr\content-v2\sha512\de\7a\1df533f2e02b5c1aca230edef2b20ad0acd131a4948ef9738b3e73c05138ce5a661286772c1b97fef634177778c3c315df1ba6333248da5664ac65b90271'
```

If I copy the angular folder to another destination it works. Other developers in my team can clone the repository and can build it without any problems. It seems that the path is now broken and something is cached. But I don't know how to clear this kind of cache. I already tried to delete package-lock.json, node_modules and .angular folder, also used "npm cache verify" etc. but nothing helps...

When I build it in another folder the .angular folder looks also different:

Folder - for example: C\temp\components:
![image](https://user-images.githubusercontent.com/45341528/187675077-8cdf0378-1b6f-43b6-b1a3-f14b5af6fbe1.png)

The origin folder - here: V:\DevOps\Common.Angular.Components
![image](https://user-images.githubusercontent.com/45341528/187675139-8b0a35f1-4785-4325-b6df-62b8b1aef777.png)

#### How To Reproduce

Good question... I have updated ng-packagr first to 14.3.0 and downgraded it to 14.2.0. Maybe that's an issue?

#### Expected Behaviour

That it does not break my angular builds on my developer machine :-D. I think it's maybe an other issue (npm?).

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            14.2.0
@angular/compiler:     14.2.0
rollup:                2.79.0
typescript:            4.7.4 
rxjs: 7.5.6
node: x.y.z
```

package.json depedencies:
```
"dependencies": {
    "@angular/animations": "^14.2.0",
    "@angular/cdk": "^14.2.0",
    "@angular/common": "^14.2.0",
    "@angular/compiler": "^14.2.0",
    "@angular/core": "^14.2.0",
    "@angular/flex-layout": "^14.0.0-beta.40",
    "@angular/forms": "^14.2.0",
    "@angular/material": "^14.2.0",
    "@angular/platform-browser": "^14.2.0",
    "@angular/platform-browser-dynamic": "^14.2.0",
    "@angular/router": "^14.2.0",
    "@internal/common": "^14.0.0-beta.0",
    "rxjs": "^7.5.6",
    "tslib": "^2.3.1",
    "zone.js": "^0.11.5"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^14.2.1",
    "@angular/cli": "^14.2.1",
    "@angular/compiler-cli": "^14.2.0",
    "@types/jasmine": "~4.0.0",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.2",
    "jasmine-core": "~4.3.0",
    "jasmine-spec-reporter": "^5.0.2",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "ng-packagr": "^14.2.0",
    "ng-samurai": "^3.0.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "typescript": "~4.7.2"
  }
```

**Comment by alan-agius4** [comment]
Likely you cache has been poised when you downgraded ng-packagr.

You can run `ng cache clean` to clean the cache.

**Comment by sekoch29** [comment]
Thanks alan-agius4 for the fast response. But it has no effect:

```
(base) PS V:\DevOps\Common.Angular.Components> ng cache clean
(base) PS V:\DevOps\Common.Angular.Components> ng build components
Building Angular Package

------------------------------------------------------------------------------
Building entry point 'components/src/lib/badge'
------------------------------------------------------------------------------
✖ Compiling with Angular sources in Ivy partial compilation mode.
EINVAL: invalid argument, link 'V:\DevOps\Common.Angular.Components\.angular\cache\14.2.1\ng-packagr\tmp\2e43d060' -> 'V:\DevOps\Common.Angular.Components\.angular\cache\14.2.1\ng-packagr\content-v2\sha512\de\7a\1df533f2e02b5c1aca230edef2b20ad0acd131a4948ef9738b3e73c05138ce5a661286772c1b97fef634177778c3c315df1ba6333248da5664ac65b90271'
```

I have also tried this combination, but does also not have any effects:
- remove folders: .angular and node_modules 
- remove package-lock.json
- ng cache clean & npm cache verify
- npm i

I have no idea and I don't know any buzzwords to google anymore.

**Comment by sekoch29** [comment]
I have another library project where I upgraded directly to 14.2.0 instead to 14.3.0 and downgrade to 14.2.0 and I have the same issue

**Comment by alan-agius4** [comment]
Are you using docker by any chance?

**Comment by sekoch29** [comment]
Nope. Windows...

**Comment by sekoch29** [comment]
If I disable the cache via "ng cache disable" it works. But why does ng cache clean not work...

**Comment by alan-agius4** [comment]
The error indicated that a link from `V:\DevOps\Common.Angular.Components\.angular\cache\14.2.1\ng-packagr\tmp\2e43d060` to `V:\DevOps\Common.Angular.Components\.angular\cache\14.2.1\ng-packagr\content-v2\sha512\de\7a\1df533f2e02b5c1aca230edef2b20ad0acd131a4948ef9738b3e73c05138ce5a661286772c1b97fef634177778c3c315df1ba6333248da5664ac65b90271` cannot be created. 

The link is being created by https://github.com/npm/cacache. 

Can you please provide the output of `ng v`?

**Comment by sekoch29** [comment]
Output of ng v

```
Angular CLI: 14.2.1
Node: 16.17.0
Package Manager: npm 8.6.0
OS: win32 x64

Angular: 14.2.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------       
@angular-devkit/architect       0.1402.1
@angular-devkit/build-angular   14.2.1
@angular-devkit/core            14.2.1
@angular-devkit/schematics      14.2.1
@angular/cli                    14.2.1
@angular/flex-layout            14.0.0-beta.40
@schematics/angular             14.2.1
ng-packagr                      14.2.0
rxjs                            7.5.6
typescript                      4.7.4
```

Folder content is also empty:
![image](https://user-images.githubusercontent.com/45341528/187718990-c989e982-6ee0-4afd-8a41-1cab72f13480.png)

I uninstall angular/cli and installed it again etc., but it doesn't help.

Now I have checked another thing: My repository is on V: which is mapped to an UNC Path (\\...). 

I just set the ng cache folder to "ng config cli.cache.path "C:/temp/.cache/ng" and it works. If I map it back to "./cache/ng", it does not work. 

Now I am confused that angular v13 projects work. 

![image](https://user-images.githubusercontent.com/45341528/187720704-2d0abba3-a752-453f-986c-d5b41852d376.png)

**Comment by 1010010010** [comment]
Should there be a released version 14.3.0 at all?
https://www.npmjs.com/package/ng-packagr states the latest version is 14.2.0 but when i updated our app today to angular 14 i got offered ng-packagr: "^14.3.0". That version has already a peer-dependency to @angular/compiler-cli 15.0.0-next, if i saw this correct.

**Comment by alan-agius4** [comment]
`^14.3.0` was released in a broken state and deprecated from a the NPM registry afterwards.

Who is suggesting that version?

**Comment by 1010010010** [comment]
Thanks for your fast response!
I updated yesterday afternoon with `ng update @angular/cli@14 @angular/core@14`.
I used --force because of another conflict.
Later i deleted my package-lock.json and tried `npm install` again without force to see if evertyhing still works fine and i got the peer-dep conflict for version 15.0.0-next of @angular/compiler-cli.
I had `ng-packagr ^14.3.0` in my package.json after updating.
Manually downgrading from `^14.3.0` to `14.2.0` worked.

Know i understood the problem, i guess. Thank you for your help!

**Comment by sekoch29** [comment]
Yes, I can confirm that. It automatically updates to 14.3.0 when you update with "ng update @angular/cli@14 @angular/core@14" , but that has a peer dep conflict wiht 15.0.0-next...

**Comment by alan-agius4** [comment]
That’s looks like a separate bug in the Angular CLI. 

Will investigate this later today.

**Comment by alan-agius4** [comment]
Closing as this is not actionable from our end.
