### ISSUE TITLE
Define peerDependencies for secondary entry points

### ISSUE THREAD

**Issue by ChiaraDipi** [ng-packagr/ng-packagr#2420]
## Type of Issue

```
[ ] Bug Report
[X] Feature Request
```

## Description

How can I indicate peerDependencies needed only by a secondary entry point of my Angular library, so that they are not installed when I install the library, and are requested only if I use the module from secondary entry point?

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 14.2.0
@angular/compiler: 14.2.0
rollup: 2.78.1
typescript: 4.7.4
rxjs: 6.6.7
node: 16.16.0
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by JoostK** [comment]
Package managers don't know about a "secondary entrypoint" concept; they only consider the root `package.json`  file. It is therefore not possible to indicate that a certain secondary entrypoint needs some peer dependency, but you can specify a peer dependendency as optionals using [`peerDependenciesMeta`](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta) in the root `package.json` file.

**Comment by alan-agius4** [comment]
Closing as per above.
