### ISSUE TITLE
Custom global properties cause compilation to fail

### ISSUE THREAD

**Issue by JanneSaukkio** [ng-packagr/ng-packagr#2421]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

Compilation of a library fails if it's trying to access custom properties on the global `window` object.

```
Property 'customProperty' does not exist on type 'Window & typeof globalThis'.
```

This is not a regression, because same error occurs with `ng-packagr` 11 and 13 (haven't tested with version 12).

#### How To Reproduce

Example library saves some information to `window.customProperty` variable. 

```typescript
// src/lib.ts
export function setCustomProperty(value: CustomProperty) {
    window.customProperty = value;
}
```

The global `Window` interface is extended with `customProperty` object.

```typescript
// src/typings/window.d.ts
declare global {
    interface Window {
        customProperty?: CustomProperty;
    }
}
```

This causes no errors with TypeScript type checking or compilation. Compiling this code with `ng-packagr` however fails because compiler doesn't understand `customProperty` object on the `window` object.

Full repository with instructions for the reproduction: https://github.com/JanneSaukkio/ng-packagr-global-typing-error

#### Expected Behaviour

Angular libraries should be able to access custom variables in the global `window` object.

#### Version Information

```
ng-packagr: 14.2.0
@angular/compiler: 14.2.0
rollup: 2.79.0
typescript: 4.7.4
node: 16.17.0
```

**Comment by alan-agius4** [comment]
This is expected. See: https://github.com/ng-packagr/ng-packagr/issues/2257
