### ISSUE TITLE
Grammatical correction in error message

### ISSUE THREAD

**Issue by drullo** [ng-packagr/ng-packagr#2428]
## Type of Issue

```
[ ] Bug Report
[ ] Feature Request
[x] Other
```

## Description

In `src\lib\ng-package\entry-point\analyse-sources.transform.ts`,  change the wording of the error thrown on line 168 to use the word "exist" instead of "exists".

The current wording is:

_Entry point `${moduleName}` which is required by `${moduleId}` doesn't exists._

#### How To Reproduce

Reference an invalid entry point

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 14.2.0
@angular/*: 14.2.0
typescript: 4.7.4
rxjs: 7.5.6
node: 16.4.2
npm: 8.10.0
```

**Comment by alan-agius4** [comment]
@drullo, want to do a PR?

**Comment by drullo** [comment]
@alan-agius4, I attempted to, but I got an Access Denied error when trying to push my change.  Perhaps I'm doing it wrong?  I have never done a PR before.

**Comment by alan-agius4** [comment]
Here a guide on how to open a PR https://opensource.com/article/19/7/create-pull-request-github

**Comment by alan-agius4** [comment]
Closed via https://github.com/ng-packagr/ng-packagr/pull/2429
