### ISSUE TITLE
Dependencies in a spec file are resolved in dist package.json peerDependencies

### ISSUE THREAD

**Issue by edbzn** [ng-packagr/ng-packagr#2433]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

We have a library with multiple sub-entry points, in one of these sub-entry points there's the following import declared **in a spec file**: 

```ts
import { CommonModule } from '@angular/common';
```

The problem is that when we build the library using ng-packagr, this dependency is added in the peerDependencies of the distribution package.json even if it's only used in a test file. Here is the produced dist package.json:

```jsonc
"peerDependencies": {
  "@angular/core": ">=12.0.0",
  "@angular/platform-browser": ">=12.0.0",
  "@rx-angular/cdk": ">=1.0.0-beta.2",
  "rxjs": ">=6.5.5",
  "@angular/common": "12.2.16" // <- resolved from the spec file import
}
```

Here is the [spec file in question](https://github.com/rx-angular/rx-angular/blob/9ebbe9ac76bcf569f41561a9dc021d2f14fc1777/libs/template/for/src/lib/tests/for.directive.observable.spec.ts#L1), if I remove the reference to the `CommonModule` in the spec file and I rebuild, peerDependencies are not populated with this superfluous dep.

It seems like ng-packagr is not excluding spec files as it is defined in the `tsconfig.lib.json`:

```json
"exclude": ["src/test-setup.ts", "**/*.spec.ts", "**/*.test.ts"]
```

This issue is producing a warning for our users:

```
template has incorrect peerDependecy for @angular/common = 12.2.16
```

#### How To Reproduce

1. clone https://github.com/rx-angular/rx-angular
2. yarn install
3. run `nx build template`
4. see that dist/libs/template/package.json is populated with `@angular/common`
5. removing the `CommonModule` declaration in [the spec file](https://github.com/rx-angular/rx-angular/blob/9ebbe9ac76bcf569f41561a9dc021d2f14fc1777/libs/template/for/src/lib/tests/for.directive.observable.spec.ts#L1) also removes it from the dist package.json

#### Expected Behaviour

Modules imported in spec files should not be taken into account when populating distribution peer dependencies.

#### Version Information

```
ng-packagr:            12.2.7
@angular/compiler:     12.2.16
rollup:                2.55.1
typescript:            4.3.5
```

**Comment by JoostK** [comment]
ng-packagr doesn't automatically populate `peerDependencies`, and the lib in question is using `@nrwl/angular:package`, _not_ ng-packagr.

**Comment by edbzn** [comment]
`@nrwl/angular:package` underlyingly uses ng-packagr, but you say that it is related to the Nx builder, not ng-packagr?

**Comment by edbzn** [comment]
You are right it seems to come from the Nx executor that updates dependencies in dist package.json, sorry for the noise.
