### ISSUE TITLE
Peer dependency warning for `@angular/compiler-cli@^15.0.0-next`

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [ng-packagr/ng-packagr#2434]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

After installing `ng-packagr` version `14.3.0` I get the following error in the console:
```
peer dep missing: @angular/compiler-cli@^15.0.0-next, required by ng-packagr@14.3.0
```

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            14.3.0
@angular/compiler:     14.2.1
rollup:                2.79.0
typescript:            4.7.4
rxjs: 7.5.6
node: 14.17.6
npm/yarn: 6.14.15
```

**Comment by JoostK** [comment]
Version 14.3.0 has been marked as deprecated on NPM and should not be used; it was published by accident.

**Comment by Blackbaud-SteveBrush** [comment]
Ah, thanks.

**Comment by Blackbaud-SteveBrush** [comment]
I installed with the `^` and got that version. Hopefully we can get a version higher that works. 👍

**Comment by alan-agius4** [comment]
This seems to he a bug in https://github.com/sindresorhus/latest-version which doesn’t properly for deprecated packages.

Therefore I recommend opening an issue in their repository.
