### ISSUE TITLE
Type-only imports should not trigger circular dependency errors

### ISSUE THREAD

**Issue by rabbitkiller-dev** [ng-packagr/ng-packagr#2453]
## Type of Issue

```
[ ] Bug Report
[*] Feature Request
```

#### How To Reproduce

https://github.com/rabbitkiller-dev/preview14.2.5

```shell
npm install
ng build fa
```
![image](https://user-images.githubusercontent.com/28952169/195051815-0f9b504b-35b3-4b60-87cf-353adc70da8e.png)

![image](https://user-images.githubusercontent.com/28952169/195052009-91abbe28-a342-4b1c-b3aa-867e6af40a32.png)

#### Version Information

```
λ node_modules\.bin\ng-packagr.cmd --version
ng-packagr:            14.2.1
@angular/compiler:     14.2.5
rollup:                2.79.1
typescript:            4.7.4

```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by JoostK** [comment]
I'd argue that type-only circular imports should only be allowed within a single compilation unit; _not_ across compilation units. Having such cycles introduces a true build cycle, resulting in an inability to determine build order for example.

**Comment by alan-agius4** [comment]
Closing as @JoostK explained that is still a build cycle.
