### ISSUE TITLE
embed assets of library in the package

### ISSUE THREAD

**Issue by rashedbayani** [ng-packagr/ng-packagr#2457]
## Type of Issue

```
[ ] Bug Report
```

## Description

_after updating angular and angular-devkit version to 14.2.5 and ng-packagr to version 14.2.1, assets of my project don't get included in the build

#### Expected Behaviour

based on the official documents, I expect the builder to keep the assets, including my style files. And it actually worked before updating the angular version to 14.
briefly, everything worked fine when angular and devkit version was 13.3.9.

#### Version Information

```
ng-packagr: 14.2.1
@angular/*: 14.2.5
typescript: 4.6.4
node: 16.16.0
npm/yarn: 8.11.0
```

**Comment by alan-agius4** [comment]
@rashedbayani, please share a  minimal reproduction. Thanks

**Comment by alan-agius4** [comment]
Closing as no reproduction was provided.
