### ISSUE TITLE
built dist folder contains a ton of node_modules folders full of README.md files

### ISSUE THREAD

**Issue by ghiscoding** [ng-packagr/ng-packagr#2459]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I seem to have the same problem as described in issue #2418, so the fix doesn't seem to work on my side. However in my case, I have 2x `node_modules` in my project because I separated Cypress into its own folder with its own `node_modules`. I did not have that problem in previous version 13.x of ng-packagr, so that seems like a regression

```sh
root
 node_modules
 src
 test
   cypress
     node_modules
```

![image](https://user-images.githubusercontent.com/643976/196330552-6e010d44-728f-4df4-8500-b270491c0b63.png)

#### How To Reproduce

my project is open sourced and can be clone from here
https://github.com/ghiscoding/Angular-Slickgrid

running `npm run packagr` should reproduce the issue

#### Expected Behaviour

in my case the `test/` folder should not be included, I also thought that my `.npmignore` would be excluding that folder when publishing but it turns out that since it's not part of the `dist/` folder, then it will completely skip the `.npmignore` (as explained in this [SO](https://stackoverflow.com/a/39334732/1212166)) and so my unwanted `test/` folder is being publishing as can be seen in this unpkg link: https://unpkg.com/browse/angular-slickgrid@5.0.0/

What I could do in the meantime is to copy my root `.npmignore` inside the `dist/` folder after it's packaged, but it's quite inconvenient but still is the only temporary solution that works and I'll go with that for now until the issue is fixed (hopefully)

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: ^14.2.1
@angular/*: ^14.1.2
typescript: ~4.7.4
rxjs: ^7.5.6
node: 16.18.0
npm/yarn: 8.10.0
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by alan-agius4** [comment]
Hi @ghiscoding,

I am unable to replicate this. 

```
npm run packagr

> angular-slickgrid@5.0.2 packagr
> ng-packagr -p ng-package.json

Building Angular Package

------------------------------------------------------------------------------
Building entry point 'angular-slickgrid'
------------------------------------------------------------------------------
✔ Compiling with Angular sources in Ivy partial compilation mode.
✔ Writing FESM bundles
✔ Copying assets
ℹ Removing scripts section in package.json as it's considered a potential security vulnerability.
ℹ Removing devDependencies section in package.json.
✔ Writing package manifest
✔ Built angular-slickgrid

------------------------------------------------------------------------------
Built Angular Package
 - from: /*****/cli-reproductions/Angular-Slickgrid
 - to:   /*****/cli-reproductions/Angular-Slickgrid/dist
------------------------------------------------------------------------------

Build at: 2022-10-21T11:14:30.643Z - Time: 7274ms

 alanagius@alanagius-linux  ~/cli-reproductions/Angular-Slickgrid   master  tree dist 
dist
├── app
│   └── modules
│       └── angular-slickgrid
│           ├── components
│           │   └── angular-slickgrid.component.d.ts
│           ├── constants.d.ts
│           ├── extensions
│           │   ├── index.d.ts
│           │   └── slickRowDetailView.d.ts
│           ├── global-grid-options.d.ts
│           ├── index.d.ts
│           ├── models
│           │   ├── angularComponentOutput.interface.d.ts
│           │   ├── angularGridInstance.interface.d.ts
│           │   ├── externalTestingDependencies.interface.d.ts
│           │   ├── gridOption.interface.d.ts
│           │   ├── index.d.ts
│           │   ├── rowDetailView.interface.d.ts
│           │   └── slickGrid.interface.d.ts
│           ├── modules
│           │   └── angular-slickgrid.module.d.ts
│           ├── services
│           │   ├── angularUtil.service.d.ts
│           │   ├── container.service.d.ts
│           │   ├── index.d.ts
│           │   ├── translater.service.d.ts
│           │   └── utilities.d.ts
│           └── slickgrid-config.d.ts
├── docs
│   └── assets
│       └── lib
│           └── multiple-select
│               └── README.md
├── esm2020
│   ├── angular-slickgrid.mjs
│   ├── app
│   │   └── modules
│   │       └── angular-slickgrid
│   │           ├── components
│   │           │   └── angular-slickgrid.component.mjs
│   │           ├── constants.mjs
│   │           ├── extensions
│   │           │   ├── index.mjs
│   │           │   └── slickRowDetailView.mjs
│   │           ├── global-grid-options.mjs
│   │           ├── index.mjs
│   │           ├── models
│   │           │   ├── angularComponentOutput.interface.mjs
│   │           │   ├── angularGridInstance.interface.mjs
│   │           │   ├── externalTestingDependencies.interface.mjs
│   │           │   ├── gridOption.interface.mjs
│   │           │   ├── index.mjs
│   │           │   ├── rowDetailView.interface.mjs
│   │           │   └── slickGrid.interface.mjs
│   │           ├── modules
│   │           │   └── angular-slickgrid.module.mjs
│   │           ├── services
│   │           │   ├── angularUtil.service.mjs
│   │           │   ├── container.service.mjs
│   │           │   ├── index.mjs
│   │           │   ├── translater.service.mjs
│   │           │   └── utilities.mjs
│   │           └── slickgrid-config.mjs
│   └── public_api.mjs
├── fesm2015
│   ├── angular-slickgrid.mjs
│   └── angular-slickgrid.mjs.map
├── fesm2020
│   ├── angular-slickgrid.mjs
│   └── angular-slickgrid.mjs.map
├── index.d.ts
├── LICENSE
├── package.json
├── public_api.d.ts
└── README.md

23 directories, 52 files
```

**Comment by ghiscoding** [comment]
@alan-agius4 yes that's because I patched it by copying the `.npmignore` into the built package, if you rollback this [commit](https://github.com/ghiscoding/Angular-Slickgrid/commit/50e5a4f8f03fa56a5dcd4bd4ed8e71000be74d9c) on your local, you should see it happening. I would like to go back to before without needing to copy the `.npmignore`

**Comment by alan-agius4** [comment]
In the comment above I am showing the output by ng-packagr which does not include the mentioned problematic files. 

The npmignore doesn’t affect this, as it is only used when executing `npm pack` / `npm publish`.

**Comment by ghiscoding** [comment]
I'm not exactly sure what you mean, what I see is that this behavior did not happen in previous ng-packagr version which is that it adds all `node_modules/**/README.md` in my `dist/` build folder (which is nearly the same as issue #2418, again it wasn't doing that in previous version. 

in the past I never had to deal with the npmignore, but at this point that is the only I found to bypass the issue I'm having will all these readme files showing up, the npmignore just help me bypass the issue with ng-packagr that I didn't have before.

**Comment by alan-agius4** [comment]
The above issue mentioned issues was solved in version 14.2.1 and using the reproduction provided I am unable to reproduce the issue you are experiencing.

Can you run `yarn why ng-packagr` ?

**Comment by ghiscoding** [comment]
The output of that command is 

```sh
=> Found "ng-packagr@14.2.1"
info Has been hoisted to "ng-packagr"
info This module exists because it's specified in "devDependencies".
info Disk size without dependencies: "26.06MB"
info Disk size with unique dependencies: "66.79MB"
info Disk size with transitive dependencies: "101.94MB"
info Number of shared dependencies: 169
Done in 1.83s.
```

If I remove the npmignore copy that I mentioned in my previous comment

```diff
- "postbuild": "npm-run-all copy:i18n copy:npmignore",
+ "postbuild": "npm-run-all copy:i18n",
```

and run the build again, all readme files are again coming all back, so I know that latest version of ng-packagr was supposed to fix this but, it doesn't like it is fixed on my side.

**Note** there might be one think I forgot to mention, I have 2 folders with `node_modules`, I moved Cypress E2E install into it's own folder and you probably did not installed it when you first tried to replicate and it might be the reason you don't see it on your side, so there's 2 installs to run
```sh
# from project root
yarn install

# for Cypress install
c:\source\angular-slickgrid> cd test/cypress
c:\source\angular-slickgrid\test\cypress> yarn install
```

![image](https://user-images.githubusercontent.com/643976/197365429-c2efd5f8-1abc-4940-b44a-72b4f633ee1f.png)

![image](https://user-images.githubusercontent.com/643976/197365449-cbc24e0c-36a8-4ab3-be70-68a9994ad2f1.png)

**Comment by alan-agius4** [comment]
> Note there might be one think I forgot to mention, I have 2 folders with node_modules, I moved Cypress E2E install into it's own folder and you probably did not installed it when you first tried to replicate and it might be the reason you don't see it on your side, so there's 2 installs to run

Indeed that causes the problem.

**Comment by ghiscoding** [comment]
Thanks for the quick fix, it works
