### ISSUE TITLE
cannot use libs within its own lib

### ISSUE THREAD

**Issue by kenatwex** [ng-packagr/ng-packagr#2466]
## Type of Issue

```
[X ] Bug Report
[ ] Feature Request
```

## Description
simple?
fundamental?

cannot use libs within its own library

I cannot even log a message for a config library how terrible
very frustrating angular has come so far
and falls so short

a workaround would make my day

#### How To Reproduce

try and use a lib within a composite lib

```

- @mycorp/my-core
    - projects/common
    - projects/logger
    - projects/config

```

config uses logger to emit log messages of bad config

but cannot build

I have listed logger as peer dependency inside config package.json

there use to be a 
```
    "umdModuleIds": {
      "@mycorp/logger": "@mycorp/logger"
    }
```
and this permitted inner libs to be shared amongst themselves from ng-package.json 
but this is now banned

```
npm run build-lib:config

> yeti-ui-core@0.0.0 build-lib:config
> ng build @mycorp/config && cd dist/mycorp/config && npm pack

Building Angular Package

------------------------------------------------------------------------------
Building entry point '@wexinc/config'
------------------------------------------------------------------------------
✖ Compiling with Angular sources in Ivy partial compilation mode.
projects/mycorp/config/src/lib/app.config.ts:1:60 - error TS2307: Cannot find module '@mycorp/logger' or its corresponding type declarations.

1 import {EEnvironment, IConfiguration, ILoggingConfig} from '@mycorp/logger'
```

#### Expected Behaviour

angular library framework should be able to use libs within its own lib

I shouldnt be here
this should be implemented
fundamental

#### Version Information

```
nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.17.0
   OS   : darwin arm64
   yarn : 1.22.18
   
   nx : 15.0.3
   @nrwl/angular : 15.0.3
   @nrwl/cypress : 15.0.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.3
   @nrwl/js : 15.0.3
   @nrwl/linter : 15.0.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.0.3
   @nrwl/nx-cloud : 15.0.0
   @nrwl/nx-plugin : 15.0.3
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.0.3
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.3
   @nrwl/web : 15.0.3
   @nrwl/webpack : 15.0.3
   @nrwl/workspace : 15.0.3
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @fortawesome/angular-fontawesome: 0.10.2
   	 @ngneat/transloco: 4.1.1
   	 @ngrx/component: 14.3.2
   	 @ngrx/component-store: 14.3.2
   	 @ngrx/effects: 14.3.2
   	 @ngrx/entity: 14.3.2
   	 @ngrx/router-store: 14.3.2
   	 @ngrx/store: 14.3.2
   	 @ngrx/store-devtools: 14.3.2
   	 apollo-angular: 4.1.0
   	 @buildmotion/angular: 13.0.1
   	 @ngrx/schematics: 14.3.2
   	 @ngrx/store-devtools: 14.3.2
   	 @storybook/angular: 6.5.13
```

**Comment by alan-agius4** [comment]
Hi @kenatwex, this looks like a misconfiguration from your end.

From the error is appears that `@myocrp/logger` is either not built or the TypeScript path mappings are configured incorrectly. 

That said, it looks like you misunderstand what peer dependencies and `umdModuleIds` are for used for.

Peer dependencies are a type of dependency that is only used by your consumers when you publish the library on NPM. Having a peer dependency means that your package needs a dependency that the consumers needs to install additional to your library.
 
umdModuleIds was used for, this was used to provide the IDs of the dependencies need to generate a valid UMD bundle. This is no longer required as UMDs are no longer generated.

Unfortunately, without a minimal reproduction we are unable to assist further.

**Comment by kenatwex** [comment]
That was just a typo

**Comment by kenatwex** [comment]
I asked for the solution and alternative to umdModuleIds

do we really need a repo for that?

**Comment by alan-agius4** [comment]
> I asked for the solution and alternative to umdModuleIds

There is no alternative and no need for one as UMD bundles are no longer generated.

> peer dependencies is the solution

Peer dependencies are only used/needed by your consumers (IE: when your package is published on NPM).

> I have them setup and still getting compile error

Likely this is an issue of misconfiguration which without a reproduction we are unable to provide additional information.

**Comment by kenatwex** [comment]
Okay thanks for your response

**Comment by kenatwex** [comment]
Okay thanks for your response
Just needed to firm up on THE solution and thats okay
