### ISSUE TITLE
Publish React component / web component from an Angular library

### ISSUE THREAD

**Issue by abf7d** [ng-packagr/ng-packagr#2491]
## Type of Issue

```
[X ] Bug Report
[ ] Feature Request
```

## Description

I am looking to set up ng-packagr so it will publish an angular library with a webcomponent / react component defined in it.

I have created an angular workspace with an app and a few libraries in the projects folder. I followed a few tutorials that step you through creating a react component inside an angular library. For example you install react and react-dom into the workspace, you add "jsx": "react-jsx" to your tsconfig, you wrap your react component in a web component, you import your web component into your project app, you add CUSTOM_ELEMENTS_SCHEMA to the app.module.ts, and you use the webcomponent markup inside of the template of the component of your choosing. (I also added the line "include": ["./src/**/*.ts", "./src/**/*.js", "./src/**/*.tsx", "./src/**/*.jsx"], to the tsconfig.)

I am now trying to set up building the library. I added an index.ts file to the library as the entry point and export my web component from it:

```
export * as any from './lib/my-web-component.jsx';
```
I'm getting non-descriptive errors when I build that say
```
✖ Generating FESM2020
Could not resolve "./lib/my-web-component.jsx" from "dist/my-lib/esm2020/index.mjs"
```

I realize there is tooling that a createReact app uses to bundle the components. Is it possible to publish react components from an angular library? Does anyone have any insight into what this error is from, how to solve it, or how to get a more descriptive message?

I have tried using other monorepo solutions such as NX to address this problem, but nothing has worked so far. 

#### How To Reproduce
 
Create an angular applicaiton with a library.
Install react and react-dom into the workspace
Add "jsx": "react-jsx" to your tsconfig, 
Wrap a react component in a web component
Import your web component into your project app 
Add CUSTOM_ELEMENTS_SCHEMA to the app.module.ts
Use the webcomponent markup inside of the template of the component of your choosing. (I also added the line "include": ["./src/**/*.ts", "./src/**/*.js", "./src/**/*.tsx", "./src/**/*.jsx"], to the tsconfig.)
Run ng build my-libarary

#### Expected Behaviour

I am hoping to publish a react component through an angular library.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            15.0.1
@angular/compiler:     15.0.2
rollup:                3.5.1
typescript:            4.8.4
```

**Comment by alan-agius4** [comment]
Hi, 

ng-packagr is designed to be used to bundle Angular components. 

JSX is not something that we support nor plan to support in the near future.
