### ISSUE TITLE
rollup-plugin-sourcemaps doesn't support rollup 3.x

### ISSUE THREAD

**Issue by XhmikosR** [ng-packagr/ng-packagr#2495]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description

```
C:\Users\xmr\Desktop\keycloak-angular>npm ls rollup
keycloak-angular@13.0.0 C:\Users\xmr\Desktop\keycloak-angular
`-- ng-packagr@15.0.1
  +-- @rollup/plugin-json@5.0.2
  | +-- @rollup/pluginutils@5.0.2
  | | `-- rollup@3.5.1 deduped
  | `-- rollup@3.5.1 deduped
  +-- @rollup/plugin-node-resolve@15.0.1
  | `-- rollup@3.5.1 deduped
  +-- rollup-plugin-sourcemaps@0.6.3
  | +-- @rollup/pluginutils@3.1.0
  | | `-- rollup@3.5.1 deduped invalid: "^1.20.0||^2.0.0" from node_modules/rollup-plugin-sourcemaps/node_modules/@rollup/pluginutils
  | `-- rollup@3.5.1 deduped
  `-- rollup@3.5.1
```

#### How To Reproduce

```sh
git clone https://github.com/mauriciovigolo/keycloak-angular.git
cd keycloak-angular
rm ./package-lock.json
npm i
```

#### Expected Behaviour

There shouldn't be any invalid packages.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 15.0.1
@angular/*: 15.0.2
typescript: 4.8.4
rxjs: 7.6.0
node: 18.12.1
npm: 8.19.2
```

---

`rollup-plugin-sourcemaps` seems to be outdated. An intermediate solution would be to downgrade rollup to 2.x or see if `rollup-plugin-sourcemaps` can be updated, or find a replacement package.

Unsure if it's a bug in npm. Adding `rollup@2` as a devDependency seems to work around the issue, but then `rollup` is duplicated.

**Comment by alan-agius4** [comment]
This seems to be a problem with `rollup-plugin-sourcemaps ` which I have a fix for https://github.com/maxdavidson/rollup-plugin-sourcemaps/pull/125.

As an interim solution you can use `--legacy-peer-deps` NPM option.

**Comment by alan-agius4** [comment]
You can provide the option through an npmrc file that can be committed in the repo.

**Comment by XhmikosR** [comment]
I actually tried it with an .npmrc and `npm ci` still fails for me. Not a big deal, I'll just include `rollup@2` for the time being.
