### ISSUE TITLE
Support Relative Dynamic Imports

### ISSUE THREAD

**Issue by Carlosamouco** [ng-packagr/ng-packagr#2508]
## Type of Issue

```
[ ] Bug Report
[X] Feature Request
```

## Description

Currently when creating a dynamic import inside a library an error is thrown by rollup:
`Invalid value for option "output.file" - when building multiple chunks, the "output.dir" option must be used, not "output.file". To inline dynamic imports, set the "inlineDynamicImports" option.`
This prevents creating more optimized libraries.
I think that the reason behind this limitation was because of the view engine. Since that is gone, is there anything still holding us back?

#### Expected Behaviour

Additional chunks are created and no error is given.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 15.0.1
@angular/*: 15.0.1
typescript: 4.8.4
rxjs: 7.5.7
node: 18.12.0
npm: 9.2.0
```

**Comment by alan-agius4** [comment]
What is your use-case of needed support for dynamic imports?

**Comment by Carlosamouco** [comment]
I have an additional question, when will the unflattened modules be the default export of the libraries? I tested converting all my libraries to have the default pointing to the "ESM2020" module path and got less 3MB of initial bundle size (unzipped).

**Comment by alan-agius4** [comment]
>  I tested converting all my libraries to have the default export pointing to the "ESM2020" module path and got less 3MB of initial bundle size (unzipped).

This typically indicates that the you are not splitting unrelated features into secondary entry-points. Which causes the unrelated code to be bundled in the same FESM.
