### ISSUE TITLE
Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by chengzhuotc** [ng-packagr/ng-packagr#2522]
## Type of Issue

```
[ ] Bug Report
[ ] Feature Request
```

## Description
Cannot read property 'type' of undefined  angular5 ng-zorro-antd 0.6.15
![60$Y07SWIYB8Y}PA}LXMA K](https://user-images.githubusercontent.com/9107399/211139338-8d397007-ca77-4280-8fb6-372a2a3ef7b0.png)

#### How To Reproduce

_A bug: please include instructions how to reproduce. Issues without reproduction are likely to receive no feedback._

_Can you reproduce the error in the integration tests in ng-packagr?_
_If possible, take a look at the [`integration/samples`](./integration/samples) and try to break one of these builds!_

_Is the error you faced in an application importing the library_
_Try to break the Angular CLI app in [`integration/consumers/ng-cli`](./integration/consumers/ng-cli)!_

#### Expected Behaviour

_A bug: please describe what behaviour or result you expected_

_A feature: do you have a first draft or an idea how to implement?_

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
"ng-packagr": "^1.6.0",

    "@3tmall/ng-zorro-antd": "^0.6.15-7",
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
"typescript": "^2.4.2"
"rxjs": "^5.5.6",
node: 10.9.0
npm/yarn: 6.2.0
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by JoostK** [comment]
Angular 5 was released over five years ago and is no longer supported. Please update to a recent version of Angular.
