### ISSUE TITLE
Disabling automatic CSS asset embedding doesn't work (cssUrl to none)

### ISSUE THREAD

**Issue by AmadejBukorovic** [ng-packagr/ng-packagr#2523]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description

Previous versions of ng-packgr provided the ability to control embedding CSS assets (images, fonts), referenced in libraries as a relative path to the asset file, as described in https://github.com/ng-packagr/ng-packagr/blob/main/docs/embed-assets-css.md. You could opt-out of this behavior by changing setting value of the `cssUrl` to `none`.

It seems that with version 14+, this is broken and setting the `cssUrl` value to `none` has no affect. Referenced assets get embedded into the outputted CSS of the library component regardless of the value of that setting. I can confirm this was still working in v12, but I'm unsure of how it behaved in v13.

I'm under the impression this should still work (=be able to prevent any kind of assets being embedded), but I may be wrong and it's just a matter of updating the official documentation and the configuration schematics?

#### How To Reproduce

I've set up as simple project with 1 application and 1 library. The library contains a component, located in the filename `my-components.component.ts`, which references the `coffee-icon.svg` via a relative path. 

1. check out https://github.com/AmadejBukorovic/ngpackgr-14-embedded-assets-bug
2. `npm install`
3. `npm run start` 
4. open the app in the browser, observe a coffee mug icon being drawn out (embedded background image)

#### Expected Behaviour

Given that I've set the `cssUrl` value in the library's `ng-packgr.json` to `none`, I'd expect the image not to be embedded into the outputted CSS, but it does? In v12, the URL would be unchanged and the image isn't embedded into the CSS output.

The behavior is reproducible on ng-packgr v14 (main branch), as well as ng-packgr v15 (v15 branch).

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 14.2.2
@angular/*: 14.2.12
typescript: 4.7.2
rxjs: 7.5.0
node: 14.21.2
npm: 6.14.17
```

**Comment by alan-agius4** [comment]
This looks like a cache issue where changing the setting does not invalidate the cache. As a workaround you can delete the cache directory when changing the setting.
