### ISSUE TITLE
Memory leak during build after upgrade to 15.1.0

### ISSUE THREAD

**Issue by SebastianPodgajny** [ng-packagr/ng-packagr#2530]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

Looks like ng-packagr 15.1.0 has a memory leak
With ng-packagr 15.0.3 during our user-interface build ng-packagr has a memory usage ~1GB
![image](https://user-images.githubusercontent.com/21180501/211863296-9d371237-2221-4ffc-b8ad-6be6a219ab60.png)
with ng-packagr 15.1.0 memory usage goes to ~12GB and build never completes 
![image](https://user-images.githubusercontent.com/21180501/211864205-6bd57a2f-f39f-46b0-9dc8-0539ffe06793.png)
Also CPU usage is a lot higher

I can use ng-packagr 15.0.3 with Angular 15.1 without any issues

#### How To Reproduce

I can't find a reproduce also I can't record CPU profile because my system almost freezes with such a high ram usage and I can't do much

#### Expected Behaviour

Build should complete and memory usage should go back to normal

#### Version Information

```
Angular CLI: 15.1.0
Node: 16.16.0
Package Manager: yarn 1.21.1
OS: darwin x64

Angular: 15.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.0
@angular-devkit/build-angular   15.1.0
@angular-devkit/build-webpack   0.1501.0
@angular-devkit/core            15.1.0
@angular-devkit/schematics      15.1.0
@angular/benchpress             0.3.0
@angular/cdk                    15.0.4
@ngtools/webpack                15.1.0
@schematics/angular             15.1.0
ng-packagr                      15.1.0
rxjs                            7.5.7
typescript                      4.9.4
webpack                         5.75.0

ng-packagr:            15.1.0
@angular/compiler:     15.1.0
rollup:                3.9.1
typescript:            4.9.4
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by alan-agius4** [comment]
- Does this happen in non-watch mode?
- How many entry-points do you have?
- Do you have component stylesheets?

Are you able to share the project privately?

**Comment by ruizmarc** [comment]
Yes, it happens in non watch.

In my case I have about 25 entry points, it is a quite big project.

Yes, I have component stylesheets for almost every component. 

I can share the project under confidentiality conditions if needed.

**Comment by alan-agius4** [comment]
I have some ideas on what is causing the increase in memory usage. 

I will continue looking into this tomorrow.

**Comment by alan-agius4** [comment]
@SebastianPodgajny, can you check if setting `NG_BUILD_MAX_WORKERS` improves things for you?

**Comment by alan-agius4** [comment]
@SebastianPodgajny can you also try to replace the contents of `node_modules/ng-packagr/lib/ng-package/package.transform.js` with https://www.unpkg.com/browse/ng-packagr@15.0.0/lib/ng-package/package.transform.js

**Comment by SebastianPodgajny** [comment]
After replacing `node_modules/ng-packagr/lib/styles/stylesheet-processor.js` with
https://www.unpkg.com/browse/ng-packagr@15.0.0/lib/styles/stylesheet-processor.js (also I've added noop destroy function) build passes

**Comment by alan-agius4** [comment]
> After replacing `node_modules/ng-packagr/lib/styles/stylesheet-processor.js` with
> https://www.unpkg.com/browse/ng-packagr@15.0.0/lib/styles/stylesheet-processor.js (also I've added noop destroy method) build passes

So to confirm replacing the file does fix the issue and causes the build to succeed?

**Comment by SebastianPodgajny** [comment]
File replacement + noop destroy without it build fails because `_b.destroy() is undefined`

**Comment by alan-agius4** [comment]
Hi @SebastianPodgajny, thanks for the help to track this down. I belive I found the root cause. Can you try to replace `[stylesheet-processor.js](https://gist.github.com/alan-agius4/02af085774f163fc959dfbb5d36d82c5)` with https://gist.github.com/alan-agius4/02af085774f163fc959dfbb5d36d82c5

**Comment by SebastianPodgajny** [comment]
With this changes memory consuption is just a little bit higher than before and everything compiles successfully 
![image](https://user-images.githubusercontent.com/21180501/212018761-05b5d02f-f3b4-4af3-8f20-9553db466a3c.png)

Thats the diff of my ng-packagr generated using patch-package after applying your changes
```diff
diff --git a/node_modules/ng-packagr/lib/styles/stylesheet-processor.js b/node_modules/ng-packagr/lib/styles/stylesheet-processor.js
index 27e4ffc..a2806c0 100644
--- a/node_modules/ng-packagr/lib/styles/stylesheet-processor.js
+++ b/node_modules/ng-packagr/lib/styles/stylesheet-processor.js
@@ -5,10 +5,10 @@ var __importDefault = (this && this.__importDefault) || function (mod) {
 Object.defineProperty(exports, "__esModule", { value: true });
 exports.StylesheetProcessor = exports.CssUrl = void 0;
 const browserslist_1 = __importDefault(require("browserslist"));
+const fs_1 = require("fs");
 const path_1 = require("path");
 const piscina_1 = __importDefault(require("piscina"));
 const color_1 = require("../utils/color");
-const fs_1 = require("../utils/fs");
 const maxWorkersVariable = process.env['NG_BUILD_MAX_WORKERS'];
 const maxThreads = typeof maxWorkersVariable === 'string' && maxWorkersVariable !== '' ? +maxWorkersVariable : 4;
 var CssUrl;
@@ -37,7 +37,7 @@ class StylesheetProcessor {
         ];
     }
     async process({ filePath, content }) {
-        await this.getOrCreateRenderWorker();
+        this.createRenderWorker();
         return this.renderWorker.run({ content, filePath });
     }
     /** Destory workers in pool. */
@@ -45,7 +45,7 @@ class StylesheetProcessor {
         var _a;
         void ((_a = this.renderWorker) === null || _a === void 0 ? void 0 : _a.destroy());
     }
-    async getOrCreateRenderWorker() {
+    createRenderWorker() {
         if (this.renderWorker) {
             return;
         }
@@ -54,7 +54,7 @@ class StylesheetProcessor {
         let currentDir = this.basePath;
         while (currentDir !== prevDir) {
             const p = (0, path_1.join)(currentDir, 'node_modules');
-            if (await (0, fs_1.exists)(p)) {
+            if ((0, fs_1.existsSync)(p)) {
                 styleIncludePaths.push(p);
             }
             prevDir = currentDir;
@@ -69,13 +69,13 @@ class StylesheetProcessor {
                 FORCE_COLOR: '' + color_1.colors.enabled,
             },
             workerData: {
-                tailwindConfigPath: await getTailwindConfigPath(this.projectBasePath),
+                tailwindConfigPath: getTailwindConfigPath(this.projectBasePath),
                 projectBasePath: this.projectBasePath,
                 browserslistData,
                 targets: transformSupportedBrowsersToTargets(browserslistData),
                 cacheDirectory: this.cacheDirectory,
                 cssUrl: this.cssUrl,
-                styleIncludePaths: styleIncludePaths,
+                styleIncludePaths,
             },
         });
     }
@@ -105,7 +105,7 @@ function transformSupportedBrowsersToTargets(supportedBrowsers) {
     }
     return transformed.length ? transformed : undefined;
 }
-async function getTailwindConfigPath(projectRoot) {
+function getTailwindConfigPath(projectRoot) {
     // A configuration file can exist in the project or workspace root
     // The list of valid config files can be found:
     // https://github.com/tailwindlabs/tailwindcss/blob/8845d112fb62d79815b50b3bae80c317450b8b92/src/util/resolveConfigPath.js#L46-L52
@@ -113,7 +113,7 @@ async function getTailwindConfigPath(projectRoot) {
     for (const configFile of tailwindConfigFiles) {
         // Irrespective of the name project level configuration should always take precedence.
         const fullPath = (0, path_1.join)(projectRoot, configFile);
-        if (await (0, fs_1.exists)(fullPath)) {
+        if ((0, fs_1.existsSync)(fullPath)) {
             return fullPath;
         }
     }
```

**Comment by alan-agius4** [comment]
The slight increase in memory is expected due to the usage of workers. Do you any see any difference in compilation duration with from 15.0.0?

Nb: By sure to disable the cache `ng cache disable`

**Comment by alan-agius4** [comment]
Great so 15.1.0 is faster :)
