### ISSUE TITLE
How to generate a lib to use with webpack in a non-angular webapp?

### ISSUE THREAD

**Issue by AlonsoK28** [ng-packagr/ng-packagr#2535]
## Type of Issue

```
[ ] Bug Report
[ ] Feature Request
[*] Question
```

## Description

According with your README  file
```
🎒 npm package can be consumed by 
[Angular CLI] (https://github.com/angular/angular-cli), 
[Webpack] (https://github.com/webpack/webpack), or ESM Bundlers
```

Using `ng-packagr` I can create an Angular Material app an consume it on other already existing web application **outside** Angular using just **webpack 5** ?

Example steps to follow for this purpose
1. create angular lib using `ng-packagr`
2. publish to `npm`
3. install on my already existing web app using `webpack 5` (**no angular** web app)
4. import and use in proyect

You think that this is possible ?

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `ng-packagr`.
