### ISSUE TITLE
Upgrade to v14 breaks bazel build with architect; assets not in bundle

### ISSUE THREAD

**Issue by nattySP** [ng-packagr/ng-packagr#2551]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

After upgrading to angular/ng-packagr v14, building our library in our bazel WORKSPACE with the architect bazel rule (e.g. load("@npm//@angular-devkit/architect-cli:index.bzl", "architect") results in the assets not getting copied, or at least not getting copied to the right place.  Running with `ng build` still works.

#### How To Reproduce
Here is our ng-package.js:

```
const {resolve} = require('path');
// In the BUILD target ["$(@D)"] is ensured to be the last.
const [outputPath] = process.argv.slice(-1);

module.exports = {
  dest: resolve(outputPath),
  lib: {
    entryFile: 'src/public-api.ts',
  },
  assets: [
    'src/assets/icons/**/*',
    'src/assets/fonts/*',
    'src/assets/images/**/*',
    'src/styles/*.scss',
    'src/styles/*.css',
  ],
};
```

Running `ng build foo` for our library produces expected results, with the following directory in the built bundle, assuring me that the assets have been copied over:
src
 |_assets
 |_styles

Running `bazel build foo` results in no src directory present in the bundle, where the following BUILD.bzl configures the build target: 
```
load("@build_bazel_rules_nodejs//:index.bzl", "pkg_npm")
load("@npm//@angular-devkit/architect-cli:index.bzl", "architect")

_package_segments = len(package_name().split("/"))

architect(
    name = "foo",
    args = [
        "foo:build",
        "--",
        # ng-packagr.js file reads this argument and inserts
        # it into the configuration object.
        # ../.. segments to re-relative paths from the chdir back to workspace
        "/".join([".."] * _package_segments + ["$(@D)"]),
    ],
    chdir = package_name(),
    data = glob(
        include = ["src/**/*"],
        exclude = [
            "src/**/*.spec.ts",
        ],
    ) + [
        "ng-package.js",
        "package.json",
        "tsconfig.lib.json",
        "tsconfig.lib.prod.json",
    ],
    output_dir = True,
)

pkg_npm(
    name = "foo-lib",
    package_name = "foo",
    package_path = "frontend",
    deps = [":foo"],
    stamp = "@rules_nodejs//nodejs/stamp:never",
)
```

#### Expected Behaviour

I expect the built bundle to look the same whether its built with `ng build` or `bazel build <architect rule>` given the same ng-package.js/json.  Reverting to ng-packagr@13.3.1 resolves the issue for now but we can't upgrade ng-packagr until the bazel issue is fixed.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 14.2.2
@angular/*: 14.2.12
typescript: 4.6.4
rxjs: 6.6.7
node: 16.19.0
yarn: 1.22.19
```
Bazel:
build_bazel_rules_nodejs 5.8.0 (which uses node 16.19.0)
rules_nodejs 5.8.0

**Comment by alan-agius4** [comment]
Hi @nattySP, 

Can you please create a minimal reproduction then you can push this repository to github and link it here?

**Comment by alan-agius4** [comment]
Closing as no reproduction was provided.
