### ISSUE TITLE
Angular 15 library with dependencies are not bundled when build or publish

### ISSUE THREAD

**Issue by stefan0s** [ng-packagr/ng-packagr#2553]
## Type of Issue
I have an angular library project and have add in package.json as dependency an external library that i want to get bundled with my library (ex. angular-oauth2-oidc). 

When i import that library to my project i am getting error: Cannot find module 'angular-oauth2-oidc' or its corresponding type declarations.

I have also set in ng-package.json the 
"allowedNonPeerDependencies": ["angular-oauth2-oidc"] and 
"umdModuleIds": { "angular-oauth2-oidc": "angular-oauth2-oidc" }

I don't want to add that external library as a peer dependency because i need to be agnostic to someone that want to use it.

```
[X] Bug Report
[ ] Feature Request
```

## Description

 When importing my library i receive Cannot find module 'angular-oauth2-oidc' or its corresponding type declarations.

#### How To Reproduce

Create a angular-tour-of-heroes demo project
Create a new library
Add an external library to the new library as Dependency and yarn install within the library path
Add the library module to the project

#### Expected Behaviour

The library should be installed and use any external libraries installed as dependencies.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 12.2.7
@angular/*: 12.2.18
typescript: 4.3.5
rxjs: 6.6.7
node: 18.13.0
npm/yarn: 1.21.1
angular-oauth2-oidc: 13.0.1
```

**Comment by alan-agius4** [comment]
This is an intended changed and is highlighted in the changelog. 


> BREAKING CHANGES
Bundling of dependencies has been removed without replacement. In many cases this was used incorrectly which drastically increase in size. This was also mainly used for UMD bundles which will be removed in future.

**Comment by stefan0s** [comment]
Thank you for your feedback. So if we use peerDependencies and within library package.json add
"peerDependenciesMeta": {
    "angular-auth-oidc-client": {
      "autoinstall": true
    },
  }

will that work as expected? Is this a proposed approach?

**Comment by alan-agius4** [comment]
The `autoinstall` option was a proposal which was never implemented. See:  https://github.com/npm/rfcs/blob/main/implemented/0025-install-peer-deps.md#unresolved-questions-and-bikeshedding

Typically users installing `peerDependencies` manually results in a better DX and also ensures compatibility with other packages managers.
