### ISSUE TITLE
[Bug] Leaving a slash at the end of "dest" config property leads to infinite watch loop

### ISSUE THREAD

**Issue by bundyo** [ng-packagr/ng-packagr#2558]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

If the "dest" config property ends with a slash, running `ng build --watch` compiles normally, but after the first refresh goes into an infinite compilation loop. This is broken with version 14.0.0, 13.3.1 is fine. Specifically this line in `ng-package/package.ts` is the culprit:

```diff
- return this.absolutePathFromPrimary('dest');
+ return path.join(this.basePath, this.primary.$get('dest'));
```

since the path.resolve removes the trailing slash and path.join apparently not. 

I'm using an `angular.json` to build my project, as I have a test app there too. Seems `paths` module config in tsconfig is worsening things too.

#### How To Reproduce

I had to reproduce it in a custom project (based on your Ivy sample), since I'm using angular.json. The repo is [here](https://github.com/bundyo/ng-packagr-test). Run `npm i`, then `ng build --watch`. Change something in `src/angular.component.ts` and you will see an additional change detection out of nowhere in the secondary library. Even worse - go into `secondary/src/secondary.module.ts` and change the import from `@sample/ivy`  to `@lib` (there's an additional path for this, defined in tsconfig.ngc.json) and the compilation goes in a wild infinite loop.

To fix the problem - stop the build and change `"dest": "./dist/"` to `"dest": "./dist"` in `ng-package.json` and start the watch again - everything is back to normal, including the `@lib` path.

#### Expected Behaviour

To not have an infinite compilation loop or false change detections. 

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 14.0.0+
@angular/*: 14.2.12
typescript: 4.8.4
rxjs: 6.6.7
node: 18.13.0
npm: 8.19.3
```

Can I ask you to please backport this change to 14.x too, after fixing it? :slightly_smiling_face:

**Comment by alan-agius4** [comment]
Thanks for this bug report.

Unfortunately, we cannot backport the fix since version 14 is LTS and only security fixes are backported.

**Comment by bundyo** [comment]
Okay, at least there's a workaround. :)
