### ISSUE TITLE
[BUG] Cannot build library with external SCSS exports

### ISSUE THREAD

**Issue by roman-supy-io** [ng-packagr/ng-packagr#2559]
## Type of Issue

```
[x ] Bug Report
[ ] Feature Request
```

## Description

In our project, we are using `@infragistics` components. 
All is working well with the app builds only, but not the buildable libraries.
The issue is that `@infragistics` have SCSS `exports` property within `package.json` that points to the actual file, here's excerpt from `package.json` of that library:
```
"exports": {
    "./themes": {
      "sass": "./lib/core/styles/themes/_index.scss"
    }
}
```
and the library path in `node_modules` is `@infragistics/igniteui-angular`.

#### How To Reproduce

Create an angular workspace and a buildable library with `ng-packagr` executor.

Add a SCSS file and reference any package's SCSS that is being `export`ed from `package.json` by alias.

Try to build a library.

We use `@infragistics`, it's a paid package from private registry.

When the SCSS file is imported directly, like `@infragistics/igniteui-angular/lib/core/styles/themes`, everything works as expected.
However if the import points to the alias defined in `package.json` which is `@infragistics/igniteui-angular/themes` the following build error appears:
```
      Can't find stylesheet to import.
     ╷
   1 │ @use '@infragistics/igniteui-angular/theming';
     │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     ╵
     libs/components/src/lib/icon/components/icon/icon.component.scss 1:1  root stylesheet
   Pass --verbose to see the stacktrace.
```

Note: `ng-package.json` already contains the needed option:
```
"styleIncludePaths": ["../styles/src/lib", "../components/src/lib", "../../node_modules"]
```

#### Expected Behaviour

The `ng-packagr` should follow the same build rules as Angular does, _by being able to read not only files directly but also by alias_.

#### Version Information

```
ng-packagr: 15.1.0
@angular/compiler: 15.1.0
rollup: 3.14.0
typescript: 4.8.4
rxjs: 7.8.0
node: 18.12.1
npm: 8.19.2
@infragistics/igniteui-angular: 15.0.7
```

**Comment by lkuendig** [comment]
Is there any intention to fix this? It's already broken for more than a month and no one assigned the ticket. Cannot build without the fix :(

**Comment by alan-agius4** [comment]
For the time being you can use the workaround mentioned in https://github.com/angular/angular-cli/issues/23552#issuecomment-1183108111

**Comment by nattySP** [comment]
+1 This is also affecting me.

**Comment by matze1234** [comment]
+1 This is also affecting me.

**Comment by Parth7030** [comment]
+1

**Comment by tinesoft** [comment]
Hi all,

I was having the similar issue, I managed to workaround by using a **relative path**(`libs/path/to/lib`) and not the **import path** (`@myorg/lib`) 

## Setup:

My setup: two Angular libraries `ui-styles` 	and  `ui-theme`, the later importing styles from the first one:

the **imported library** :
- libs/ui-styles/scss/file.scss
- libs/ui-styles/ng-package.json

the **importing library** :
- libs/ui-theme/scss/theme.scss
- libs/ui-theme/ng-package.json


## Solution 

1. importing styles from `ui-styles` in `ui-theme` as such:
```scss
@import 'libs/libs/ui-styles/scss/file';
```

2. adding the following lines in the `ng-package.json` of the **importing library**  `ui-theme` :
```json
{
	"$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
	"dest": "../../dist/libs/ui-theme",
	"lib": {
		"entryFile": "src/index.ts",
		"styleIncludePaths": [
			"../.."
		]
	}
}

```

Hope it helps

**Comment by aalbericio** [comment]
I'm hitting this issue again after upgrading to ng-packagr 19.0.1:

`Can't find stylesheet to import`

Reverting back to 18.2.1 works 100%. 

What can be wrong? 

Thanks!

**Comment by alan-agius4** [comment]
@aalbericio, without a reproduction it's hard to tell. Kindly file a new issue with a minimal reproduction. 

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by aalbericio** [comment]
@alan-agius4 I know. 

I was trying to create a repo to share but, believe or not, in this new (and simplified) repo, it works perfectly.

There must be something else I'm missing...

As soon as I have a repo that reproduces the error, I will file a new issue, as you mentioned.

Thanks

**Comment by alan-agius4** [comment]
The current behavior is expected and occurs because the library’s `package.json` includes an `exports` field. However, the specific file you are trying to access is not listed within the exports, making the library unresolved.  

To link to an unbuilt library, you must manually add an export entry for the `package.json` file:  

```json
"exports": {
  "./styles/*": {
    "sass": "./styles/*.scss"
  },
  "./package.json": {
    "default": "./package.json"
  }
}
```  

Alternatively, a more appropriate solution is to `npm link` to the built version of the library.

**Comment by aalbericio** [comment]
Hello @alan-agius4 

I got it working (both in local and CI environments) but I'm getting a warning in my Gitlab environment:

`WARNING: Found a conflicting export condition for "./package.json". The "default" condition would be overridden by ng-packagr. Please unset it.`

Anyway, the compilation is working and I think you don't need to reopen this issue.

Thank you, again.

**Comment by alan-agius4** [comment]
Glad to hear that you fixed the issue, the warning is because you are setting an export condition which will be overridden by the build system.
