### ISSUE TITLE
Built dist folder contains ton of README.md files

### ISSUE THREAD

**Issue by cami-dev** [ng-packagr/ng-packagr#2564]
## Type of Issue

```
[ x] Bug Report
[ ] Feature Request
```

## Description

I seem to have the same problem described in issue https://github.com/ng-packagr/ng-packagr/issues/2418 and https://github.com/ng-packagr/ng-packagr/issues/2459 but directly in the /dist folder of our Angular lib probject.  We did not have thist problem in previous version 13.x of ng-packagr, so that seems like a regression

![image](https://user-images.githubusercontent.com/13835159/218782472-7f286337-25df-49f8-9b5e-c9c607a43cc9.png)

#### How To Reproduce

By setting a custom destination in the  ng-package.json like this and having deleteDestPath: false

```
{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "dest": "dist/app/appname",
  "deleteDestPath": false,
  "lib": {
    "entryFile": "./src/public-api.ts"
  },
}

```
The README.md is in the root-folder of the project to start with.

#### Expected Behaviour

The folders and README.md should not be duplicated.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 15.1.2
@angular/*: 15.0.4
typescript: 4.8.4
rxjs: 7.5.5
node: 16.19.0
npm/yarn: 8.19.3
```

**Comment by cami-dev** [comment]
Works like a charm <3

**Comment by alan-agius4** [comment]
Glad to hear that @cami-dev
