### ISSUE TITLE
Cannot build on exFat file system

### ISSUE THREAD

**Issue by vasicvuk** [ng-packagr/ng-packagr#2588]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description

When I do ng build on the library i get the following error:

```
EISDIR: illegal operation on a directory, link 'D:\Projects\some-project\.angular\cache\15.2.4\ng-packagr\tmp\370d1ae0' -> 'D:\Projects\some-project\.angular\cache\15.2.4\ng-packagr\content-v2\sha512\8d\53\ad58764bc240411378ae1c47c0c20525da378a3b143795a11bc3fdbf6c9cde6fb2de6c3947d673d5872b9ce205d6274114b3b4dfd27609a636df7fd0b600'

```

#### How To Reproduce

- Format a hard drive to exFAT
- Download project with library
- Run ng build library

#### Expected Behaviour

As ng serve and other commands are working regulary, I would expect for ng build to also work.

**Comment by alan-agius4** [comment]
Same cause as https://github.com/ng-packagr/ng-packagr/issues/2416

**Comment by vasicvuk** [comment]
Anyway the workaround is to disable cache:

```
ng config cli.cache.environment all
```

@alan-agius4  Is this opened on Angular CLI then?

**Comment by alan-agius4** [comment]
No, as mentioned in the linked issue above, the problem is from an upstream package called cacache.
