### ISSUE TITLE
Allow for force setting package.json export fields

### ISSUE THREAD

**Issue by alirezamirian** [ng-packagr/ng-packagr#2609]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request (I guess!)
```

## Description

I need to set `exports` in package.json, to export my css files. It works fine as suggested here: https://github.com/ng-packagr/ng-packagr/blob/main/docs/copy-assets.md#exporting-styles

The issue is that by setting `exports`, field, my storybook which uses webpack5 fails to build, as it expects the entry point to be also resolvable by `exports`, when `exports` exists. If I add `default` and `types`, to make it happy, then ng-packagr is unhappy with it and throws the error: 

> Found a conflicting export condition for ".". The "default" condition would be overridden by ng-packagr. Please unset it.

Does it make sense to make this a warning, or at least provide an option to suppress it?

**Comment by alan-agius4** [comment]
I am not following why you need to modify the `default` and `types` conditions. I don’t see any reason why you’d need to do that.

What is the value that you are setting?

**Comment by alirezamirian** [comment]
The reason I need to set `default` and `types`, is that I have code in my monorepo that imports from my package. That code (storybook stories, basically), uses webpack5 to build. When `exports` is set in package.json, webpack (and probably any other build tool that supports `exports`) expects `exports` to be the only source of truth for module resolution. i.e., `module`, `main`, `typings`, etc. in package.json are rendered moot. 
The point is, I know these fields will be overwritten in the generated package.json, and it's fine because they are guaranteed to be pointing to the right thing, based on the build output. I think throwing an exception seems a little too dramatic, and a warning could suffice.

**Comment by alan-agius4** [comment]
> The reason I need to set default and types, is that I have code in my monorepo that imports from my package. That code (storybook stories, basically), uses webpack5 to build. 

Looks like the problem here is that storybook is consuming the uncompiled library.

**Comment by alirezamirian** [comment]
Yes. I have a shared storybook for multiple packages, and even if I import by the relative path (and not the package name), there is a package.json in that directory which will be used by webpack, to find the exports. I can find a way to avoid such imports, but it would be nice to keep importing by the package name and let it be linked or not linked to the source, based on the dependency version constraints.
Anyway, regardless of the specifics of this case, I think it would make sense to either just log an error/warning without throwing, or provide a way to suppress it. The check for existing `exports` conditions that would be overwritten is nice, but existing conditions wouldn't cause any issues for the rest of the build logic.

**Comment by alan-agius4** [comment]
Released in [16.0.1](https://github.com/ng-packagr/ng-packagr/releases/tag/16.0.1)
