### ISSUE TITLE
Version 16 does not work for me

### ISSUE THREAD

**Issue by henryruhs** [ng-packagr/ng-packagr#2611]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

```
ERROR TypeError: this.injector is undefined
```

#### How To Reproduce

1. "npm run build" in https://github.com/henryruhs/ngx-crud to create build directory
2. link ngx-crud dependency in https://github.com/henryruhs/ngx-crud-playground via npm link
3. run npm start

The playground works with ngx-crud 13.0.1 which is build with ng-packagr 15.x.x

#### Expected Behaviour

Well, the injector from CrudService should work.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            16.0.0
@angular/compiler:     16.0.0
rollup:                3.21.1
typescript:            5.0.4
```

**Comment by alan-agius4** [comment]
This is expected as it's related to the ECMA2022 changes which by default class fields behave different.

You can read more about this here;
- https://www.typescriptlang.org/tsconfig#useDefineForClassFields
- https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#the-usedefineforclassfields-flag-and-the-declare-property-modifier

There are a couple of things you can do;
- Refactor the code.
- In the tsconfig provided to ng-packagr, set `useDefineForClassFields` to `false`.

**Comment by henryruhs** [comment]
I refactored the code via https://github.com/henryruhs/ngx-crud/commit/8e933f37951293a23c85e13167cd68fc3fcec0a5 and it works now. The quick win to set `useDefineForClassFields` to `false` was not successful.

Thanks for pointing out that issue.

**Comment by Michsior14** [comment]
For the future readers, `useDefineForClassFields: false` won't help with pre-intialized class fields in ES2022 and TS 5.0.4 (works fine with TS 4.9.5): https://github.com/microsoft/TypeScript/issues/52331

It's also a bit unfortunate because there are no errors during compilation, but only in runtime.

**Comment by henryruhs** [comment]
I cannot confirm this @Michsior14 as it still works for me using `5.0.4`.

**Comment by alan-agius4** [comment]
@Michsior14, Unfortunately that is a TypeScript bug which we cannot action. As a workaround you could downgrade TypeScript or refactor the class to not require `useDefineForClassFields`.

**Comment by Michsior14** [comment]
> useDefineForClassFields

Yup, I am aware, just wanted to post this so others don't need to debug and just stay on 4.9.5 until it's resolved (`useDefineForClassFields` refactor is not easy due to https://github.com/microsoft/TypeScript/issues/53286).
