### ISSUE TITLE
Global Library Styles

### ISSUE THREAD

**Issue by Aurrix** [ng-packagr/ng-packagr#2620]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

Utilizing global styles in the Angular library packaged by ng-packgr at the moment is impossible or at least missing documentation.
It would be nice to have global styles as in normal angular applications so that developers won't need to import, e.g. bootstrap into each component separately.

#### Expected Behaviour

When specifying `styleIncludePaths` in ng-package.json, there should be an option that resolves and inlines css for each component globally.

#### Version Information

```
ng-packagr: 15.2.2
@angular/*: 15.2.7
typescript: 4.9.4
```

**Comment by Aurrix** [comment]
Just as a note, I have tried following:
* Create styles.scss in library root: `libs/components/src/styles.scss`
* Include styles in ng-package.json
```json
  "lib": {
    "styleIncludePaths": [
      "src/styles.scss"
    ],
```

The above does not work, but importing e.g. bootstrap directly into components styles does work.

**Comment by alan-agius4** [comment]
In this case you can provide a `styles.scss` as an asset. See: https://angular.io/guide/creating-libraries#managing-assets-in-a-library
