### ISSUE TITLE
ngpackagr with vite and esbuild?

### ISSUE THREAD

**Issue by jon9090** [ng-packagr/ng-packagr#2621]
Is ngpackagr compatible with esbuild and vite? If not, are there any plans to add support for them in the future?

**Comment by alan-agius4** [comment]
Yes, the generated bundles are compatible with vite and esbuild

**Comment by jon9090** [comment]
@alan-agius4  oh sorry, I mean, does ngpackagr build with esbuild or tsc? if tsc do you have plan to use esbuild?
