### ISSUE TITLE
TypeScript compilation issue, only during import

### ISSUE THREAD

**Issue by R-Bower** [ng-packagr/ng-packagr#2633]
## Type of Issue

Not sure if this is a bug or working as intended.

## Description

When packaging my component library using Angular 16, the emitted types are incompatible with applications using Angular 15.  Custom Input properties throw errors when used with property binding (`[ ]`) syntax. 

#### How To Reproduce

1. Create a component library using Angular 16 and the latest version of ng-packagr. 
2. Export at least one component with a custom `@Input` decorator.
3. Build and export.
4. Source the component library in an Angular 15 application.
5. Attempt property binding syntax on the exported component.

Is this behavior expected?

**Comment by JoostK** [comment]
Yes, this is expected. Libraries created with Angular 16 cannot be used in 15 or older. This has always been the case, as the compiler only provides backwards compatibility for libraries, not forwards compatibility.
