### ISSUE TITLE
Cannot use advanced asset copy syntax

### ISSUE THREAD

**Issue by kellyprankin** [ng-packagr/ng-packagr#2655]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

My ng-package.json looks like this:

```
{
  "$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
  "dest": "../../dist/rcp-lib-common",
  "lib": {
    "entryFile": "src/public-api.ts"
  },
 "assets": [
    { "input": "../assets", "glob": "**/*", "output": "assets" }
 ]
}
```

I get the following schema error when building:

```
Building Angular Package
Configuration doesn't match the required schema.
Data path "/assets/0" must be string.
```

#### How To Reproduce

Simply try to use the following syntax in the assets array in ng-package.json:
 { "input": "../assets", "glob": "**/*", "output": "assets" }

#### Expected Behaviour

Should copy the assets to the correct folder

I see that the code was added in [this commit.](https://github.com/ng-packagr/ng-packagr/commit/6776e17ac41458f4d196f8ea001ab649e5274952)

 It seems like it should work and there's something wrong w/ how the ng-package-schema.json is being generated.
Just by looking at ng-package-schema.d.ts in my node_modules/ng-packagr I see that assets is defined as string[] and doesn't provide an option for an alternative type, which doesn't make sense since this block was modified to support it in the last commit to the file src/ng-package.schema.json:

```
 "assets": {
      "type": "array",
      "description": "A list of files which are simply copied into the package.",
      "items": {
        **"$ref": "#/definitions/assetPattern"**
      },
      "default": []
    },
```

which points at:

```
 "assetPattern": {
      "oneOf": [
        {
          "type": "object",
          "properties": {
            "glob": {
              "type": "string",
              "description": "The pattern to match."
            },
            "input": {
              "type": "string",
              "description": "The input directory path in which to apply 'glob'. Defaults to the project root."
            },
            "ignore": {
              "description": "An array of globs to ignore.",
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "output": {
              "type": "string",
              "description": "Absolute path within the output."
            },
            "followSymlinks": {
              "type": "boolean",
              "default": false,
              "description": "Allow glob patterns to follow symlink directories. This allows subdirectories of the symlink to be searched."
            }
          },
          "additionalProperties": false,
          "required": ["glob", "input", "output"]
        },
        {
          "type": "string"
        }
      ]
    }
```

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            13.3.1
@angular/compiler:     13.4.0
rollup:                2.79.1
typescript:            4.6.4
```

**Comment by kellyprankin** [comment]
I figured out my problem. This feature was added in a higher version of ng-packagr. The reason I was confused is because I found multiple sources stating this was supported before the version that I am currently using.

**Comment by kellyprankin** [comment]
I figured out my problem. This feature was added in a higher version of ng-packagr. The reason I was confused is because I found multiple sources stating this was supported before the version that I am currently using.

**Comment by alan-agius4** [comment]
Glad to hear you figured it out
