### ISSUE TITLE
[BUG] Build breaks with secondary entrypoints, when importing from one entrypoint to another (even when using absolute paths)

### ISSUE THREAD

**Issue by OE-mkaipiainen** [ng-packagr/ng-packagr#2657]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description

When having two secondary entrypoints (feature1 and feature2), and importing anything from feature1 into feature2 (or vice-versa), build breaks even when using absolute paths. 

In my root tsconfig.json, I have configured the paths as follows:

`
 "paths": {
      "test-lib": [
        "dist/test-lib"
      ],
      "@test-lib/*": [
        "projects/test-lib/*",
        "projects/test-lib"
      ],
    },
`

Then, inside secondary entrypoint feature1 I have

- ng-package.json // Nothing here except entrypoint
- public-api.ts // export * from './feature1.component.ts`
- index.ts // export * from './public-api.ts'
- feature1.component.ts // standalone component called Feature1Component

And inside secondary entrypoint feature2.component.ts I have

-- public-api.ts // export * from './feature2.component.ts'
-- feature2.component.ts // Standalone component called Feature2Component, that imports Feature2Component

The import string inside feature2.component.ts is an absolute path using the paths defined inside the root tsconfig, which looks like 

`import {Feature1Component} from "@test-lib/feature-1";`

When building this, the following error is thrown:

> projects/test-lib/feature-2/feature2.component.ts:2:33 - error TS6059: File '../projects/test-lib/feature-1/index.ts' is not under 'rootDir' '../projects/test-lib/feature-2'. 'rootDir' is expected to contain all source files.

#### How To Reproduce

Check out test repo, run `npm install` and `ng build`

https://github.com/Poltto/ng-packagr-bug

----

Alternatively create a simple library with the main entrypoint being just a public-api.ts file with the contents

`export default void 0;`

And then create two secondary entrypoints, one of which imports the other using absolute paths defined in root tsconfig.json. 

Then try to build.

#### Expected Behaviour

I'm expecting the build to succeed 

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
"@angular/animations": "^16.1.0",
"@angular/common": "^16.1.0",
"@angular/compiler": "^16.1.0",
"@angular/core": "^16.1.0",
"@angular/forms": "^16.1.0",
"@angular/platform-browser": "^16.1.0",
"@angular/platform-browser-dynamic": "^16.1.0",
"@angular/router": "^16.1.0",
"rxjs": "~7.8.0",
"tslib": "^2.3.0",
"zone.js": "~0.13.0"
"@angular-devkit/build-angular": "^16.1.5",
"@angular/cli": "~16.1.0",
"@angular/compiler-cli": "^16.1.0",
"@types/jasmine": "~4.3.0",
"jasmine-core": "~4.6.0",
"karma": "~6.4.0",
"karma-chrome-launcher": "~3.2.0",
"karma-coverage": "~2.2.0",
"karma-jasmine": "~5.1.0",
"karma-jasmine-html-reporter": "~2.1.0",
"ng-packagr": "^16.1.0",
"typescript": "~5.1.3"
```

**Comment by alan-agius4** [comment]
The problem here is that your library is not named `@test-lib`, but rather `test-lib`

https://github.com/Poltto/ng-packagr-bug/blob/713e394b0263755ad7d3dab9ace15049ae65b5c4/projects/test-lib/package.json#L2

Thus the correct import will is
```
import {Feature1Component} from "test-lib/feature-1";
```
