### ISSUE TITLE
Weird caching issue during build watch

### ISSUE THREAD

**Issue by sream** [ng-packagr/ng-packagr#2658]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

The first idea with this issue that I've stumbled upon was that the icon was not updating so the initial idea was that the conversion doesn't work but seems like the issue is much more complex. Data URI ist not being updated on code change but also once you revert the parameters it magically pulls the state before that. The only solution that worked was to delete the library build and .angular cache.

#### How To Reproduce

A simple way to reproduce is to download a Material Symbol for example the [Check](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Acheck%3AFILL%400%3Bwght%40600%3BGRAD%400%3Bopsz%4048) icon. It needs to be with a higher weight to see the difference. Maybe even a fill color change works. What can be done for example is to change the background size back and forth.

#### Version Information

```
ng-packagr: 16.0.1
@angular/*: 16.0.2
typescript: 4.9.5
rxjs: 6.6.7
node: 18.16
npm: 9.5.1
```

**Comment by alan-agius4** [comment]
Can you please provide a runnable reproduction? Thanks.

**Comment by sream** [comment]
Cannot reproduce it anymore. Maybe it was an issue with Node since that's the only thing that I've updated on the project after the reported issue.
