### ISSUE TITLE
Build Lib and skip resolve node_module Lib

### ISSUE THREAD

**Issue by gonglixin980926** [ng-packagr/ng-packagr#2680]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description

I have a angular lib and it is named 'ngx-qwe'.
 The 'ngx-qwe' quote a npm package 'ngx-asd'. 
The 'ngx-asd' package has build error when i build 'ngx-qwe' I use 'ng build ngx-qwe --configuration production' to build 'ngx-qwe'

I want to skip resolve 'ngx-asd', how should I do?

<img width="1619" alt="image" src="https://github.com/ng-packagr/ng-packagr/assets/40887236/eee29986-9c79-45f4-a9c6-1307be6b948c">

`"@angular-builders/custom-webpack": "^9.2.0",
 "@angular/animations": "~9.1.4",
  "@angular/common": "~9.1.4",
   "@angular/compiler": "~9.1.4", 
   "@angular/core": "~9.1.4", 
   "@angular/elements": "~9.1.4", 
   "ng-packagr": "^9.0.0",
`

_A bug: please describe the error that you encountered_

_A feature: please describe your use case and motivation_

#### How To Reproduce

_A bug: please include instructions how to reproduce. Issues without reproduction are likely to receive no feedback._

_Can you reproduce the error in the integration tests in ng-packagr?_
_If possible, take a look at the [`integration/samples`](./integration/samples) and try to break one of these builds!_

_Is the error you faced in an application importing the library_
_Try to break the Angular CLI app in [`integration/consumers/ng-cli`](./integration/consumers/ng-cli)!_

#### Expected Behaviour

_A bug: please describe what behaviour or result you expected_

_A feature: do you have a first draft or an idea how to implement?_

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            9.1.5
@angular/compiler:     9.1.13
rollup:                2.7.5
tsickle:               
typescript:            3.8.3
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by alan-agius4** [comment]
ng-packagr version 9 is no longer supported. Please update to a more recent version. If the problem persists than please open a new issue with a minimal reproduction.

**Comment by gonglixin980926** [comment]
> ng-packagr version 9 is no longer supported. Please update to a more recent version. If the problem persists than please open a new issue with a minimal reproduction.

But my company use
`    "@angular/common": "~9.1.4",
    "@angular/compiler": "~9.1.4",
    "@angular/core": "~9.1.4",
    @angular/compiler:     9.1.1` 
If I use recent version to build lib package, can the package use in angular v9？

**Comment by JoostK** [comment]
No, a library can only be used in the Angular version it is built with, plus at least two later major version. So building a library using Angular 14 allows it to be used in Angular 14, 15 and 16 (and possibly later versions, but not earlier).

**Comment by gonglixin980926** [comment]
> 


> No, a library can only be used in the Angular version it is built with, plus at least two later major version. So building a library using Angular 14 allows it to be used in Angular 14, 15 and 16 (and possibly later versions, but not earlier).

all right, I only can find the problom or hack ng-packgr，thank you
