### ISSUE TITLE
"TaskCategoryCodes" is not exported by "dist/valueSets/esm2020/lib/sets/tak/TaskCategoryCodes.mjs", imported by "dist/valueSets/esm2020/public-api.mjs".

### ISSUE THREAD

**Issue by stefanbernhardweb** [ng-packagr/ng-packagr#2684]
✖ Generating FESM2020
"TaskCategoryCodes" is not exported by "dist/valueSets/esm2020/lib/sets/tak/TaskCategoryCodes.mjs"imported by "dist/valueSets/esm2020/public-api.mjs"
```
[x ] Bug Report
[ ] Feature Request
```
When I want to build my own library and I don't use the * to import all exported consts and types into the public-api.ts I always get the error above. 

#### How To Reproduce
Build a new library and remove all automatically created files in the lib folder. After that create a own file that has follow content:
```
export declare const TaskCategoryCodes: {
  readonly Completed: "completed";
  readonly EnteredInError: "entered-in-error";
  readonly InProgress: "in-progress";
  readonly Stopped: "stopped";
};

export declare type TaskCategoryCodesType=
  (typeof TaskCategoryCodes)[keyof typeof TaskCategoryCodes];
```

Than import this file into the public-api.ts and into the components or services you want to use this codes in your angular project. Now execute the build-statement, to build the library-files.

#### Expected Behaviour
Build process works.

#### Version Information

```
ng-packagr:            15.2.2
@angular/compiler:     15.1.0
rollup:                3.28.1
typescript:            4.8.4
```

**Comment by stefanbernhardweb** [comment]
I've found out that the error only occurs if I export the constant TaskCategoryCodes. If I only export the TaskCategoryCodesType the build works fine. The thing is, that I need this constant in my angular project.

**Comment by alan-agius4** [comment]
You need to replace `export declare` with just `export` since you are not writing a Type definition file. Also, you might want to consider using a enum

```ts
export enum TaskCategoryCodes {
  Completed = "completed",
  EnteredInError = "entered-in-error",
  InProgress = "in-progress",
  Stopped = "stopped",
}
```

**Comment by stefanbernhardweb** [comment]
I understand. That was my mistake. Thank you.
