### ISSUE TITLE
Increased memory usage in 16.2.0

### ISSUE THREAD

**Issue by LeonEck** [ng-packagr/ng-packagr#2688]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

In our library build, we noticed a significant increase in memory usage during the build going from around 800MB in v16.1.0 to about 4GB in v16.2.0.
We were able to pinpoint the change to commit https://github.com/ng-packagr/ng-packagr/commit/b2bfec81d15c62ea7995c438e16f92c9cf43658a where piscina was updated. We further dug into piscina and were able to isolate it to this commit that was added between piscina 4.0.0 and 4.1.0: https://github.com/piscinajs/piscina/commit/8e6d16e1dc23f8bb39772ed954f6689852ad435f

The commit adds a new lifecycle hook on the "exit" of a worker. That code path causes an increase in memory consumption. We added logging to it and saw that for each entry point of our library, multiple workers exit with code "1".

We are unsure if this is an issue with piscina, if ng-packagr is using it incorrectly (which is now surfaced with the piscina change), or if some process within the worker shouldn't have exited with "1". Since we are unsure where the issue is originating from (or if it actually is an issue or working as designed), we wanted to start reporting this here.

As a workaround in order to not have to use larger CI runners, we currently override the piscina dependency in our package.json like this:
```
"overrides": {
  "piscina": "4.0.0"
}
```

When using ng-packagr 16.2 in combination with @angular-devkit/build-angular 16.2 the issue is not present since @angular-devkit/build-angular pins piscina to exactly 4.0.0. Therefore npm only installs 4.0.0 since it satisfies the "^" version range specified in ng-packagr. @angular-devkit/build-angular in its latest 17 next versions already updated to piscina 4.1.0. Therefore running all angular dependencies on their latest next versions will install 4.1.0 and trigger the issue.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 17.0.0-next.1
@angular/*: 17.0.0-next.3
typescript: 5.1.6
rxjs: 7.8.1
node: 18.16.0
npm: 9.6.6
piscina: 4.1.0
```

**Comment by alan-agius4** [comment]
This appears to be a piscina bug https://github.com/piscinajs/piscina/issues/427
