### ISSUE TITLE
Unable to build with secondary module importing shared module

### ISSUE THREAD

**Issue by darinw** [ng-packagr/ng-packagr#2690]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I have a  `shared` module and a `component` module. When i import the shared module into the component the build will fail on the `component` module with the following error.

```
File 'C:/Users/Darin/.../projects/my-lib/src/shared/public-api.ts' is not under 'rootDir' 'C:\Users\Darin\...\projects\my-lib\src\component'. 'rootDir' is expected to contain all source files.
```

i have followed:
https://github.com/ng-packagr/ng-packagr/blob/main/docs/secondary-entrypoints.md
https://github.com/ng-packagr/ng-packagr/tree/main/integration/samples/secondary

#### How To Reproduce

Repo:  https://github.com/darinw/root-dir-entry-point
Pull, Install & `ng build`

#### Expected Behaviour

It should act the same as:
https://github.com/ng-packagr/ng-packagr/blob/main/docs/secondary-entrypoints.md
https://github.com/ng-packagr/ng-packagr/tree/main/integration/samples/secondary

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 16.2.3
@angular/compliner: 16.2.4
typescript: 5.0.4

In package
@angular/*: 16.0.0
typescript: 5.0.2
rxjs: 7.8.0
node: 16.15.0 / 18.12.1 / 20.6.1
```

**Comment by JoostK** [comment]
You are using a relative import into `shared`:

```ts
import { getVersion } from '../shared/public-api';
```

but it needs to use the absolute module specifier of the entry-point module:

```ts
import { getVersion } from 'my-lib/shared';
```

**Comment by darinw** [comment]
Thanks @JoostK! I appreciate it! I think i went in circles with various errors! That was what i needed


To anyone looking at this in the future, i have pushed the barebones example here: https://github.com/darinw/root-dir-entry-point
