### ISSUE TITLE
Watcher does not trigger recompile on linked peerdependency changes

### ISSUE THREAD

**Issue by qualmon** [ng-packagr/ng-packagr#2695]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I'm building an Angular library with `ng build my-lib --watch` but it does not watch things properly.
The Angular library `my-lib` is dependent on a peerdependency `my-dep` which is linked with `npm link my-dep`. But ng-packagr does not properly watch changes in `my-dep`.

#### How To Reproduce

1) `npm link your-dep`
2) `ng build your-lib --watch`
3) Make changes to `your-dep`
4) No recompile is triggered.

#### Expected Behaviour

I expect `my-lib` to recompile when I make changes in `my-dep`.

#### Version Information

```
ng-packagr:            15.2.2
@angular/compiler:     15.2.9
rollup:                3.25.3
typescript:            4.9.5
node:                  16.19.1
npm:                   8.19.3
```

**Comment by alan-agius4** [comment]
This is currently working as expended as node modules are not watched.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. Luckily, it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.
