### ISSUE TITLE
Making code shared between secondary entry points private(for internal use)

### ISSUE THREAD

**Issue by bwroblewski** [ng-packagr/ng-packagr#2719]
## Type of Issue

```
[ ] Feature Request
```

## Description

I want to share code between secondary entry points of my component library. I also want the code to be only accessible from within these entry points. 

One way to do that would be to create external folder and place the code there. The problem is that ng-packagr does not allow for imports outside of given secondary entrypoint. There is an error in console that says `'rootDir' is expected to contain all source files`.

The other way would be to create secondary point for this shared code as well. But then it becomes accessible to anybody.

## Describe the solution you'd like

The best solution would be enable one to create secondary entry points that are only accessible from within library across all its secondary entry points.

**Comment by alan-agius4** [comment]
In this case, you can create a shared entry-point and mark the APIs are private through TSDOC or other conventions.

**Comment by wszydlak** [comment]
From ng-packagr view, is it really that hard to implement to have such private API? Angular for example have same format for libraries, but they can have private field (eg. platform-browser, where testing or animations are secondary entry points):

![image](https://github.com/ng-packagr/ng-packagr/assets/6583977/eafe2e41-0616-40b6-9c6f-2f0d8d26a063)

Having such a functionality will be better cause tsdoc or some conventions are just conventions that will not block private imports while having it private from "exports" point of view will not allow developers to import

If it is considered by ng-packagr as wrong practise, please explain why.
If not then maybe you can check if it will be possible to implement such a solution?

**Comment by ptu14** [comment]
Having such functionality would be nice.

If it is considered by ng-packagr as wrong practice, please explain why.
If not, then maybe you can check if it will be possible to implement such a solution?"

I hope this accurately conveys your request for the feature.

**Comment by alan-agius4** [comment]
With ng-packagr you can achieve the same thing that is implemented in the above displayed screenshot.  Just create a private export file that is referenced in the `index.ts`. This is the same pattern that is used in the `@angular/` packages.
