### ISSUE TITLE
Support for top-level await

### ISSUE THREAD

**Issue by jrdioko** [ng-packagr/ng-packagr#2746]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

When trying to use top-level await in our Angular library using ng-packagr, I get:

```
Error: The top-level-await experiment is not enabled (set experiments.topLevelAwait: true to enabled it)
```

It sounds like top-level await is supported in the browser-esbuild builder as well as in Rollup (which ng-packagr uses?). Should top-level await be working for libraries build with ng-packagr?

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            15.2.2
@angular/compiler:     15.2.10
rollup:                3.20.2
typescript:            4.9.5
```

**Comment by alan-agius4** [comment]
Top level await is intentionally not supported. See: https://github.com/angular/angular-cli/issues/26507
