### ISSUE TITLE
17.1 Release Schematic Breakage

### ISSUE THREAD

**Issue by scottwalter-nice** [ng-packagr/ng-packagr#2767]
## Type of Issue

```
[x ] Bug Report
[ ] Feature Request
```

## Description

We have a secondary endpoint with the following:

```
{
  "allowedNonPeerDependencies" : [
    "tagify"
  ],
  "dest" : "../../../dist/cxone-components/tagify",
  "lib" : {
    "entryFile" : "public_api.ts"
  }
}
```

Since upgrading to 17.1 the following error is thrown:
```
Building Angular Package
An error has occurred while validating config at /Volumes/T16-Skyhopper/cxone/libs/cxone-angular-core-ui/projects/cxone-components/tagify
Configuration doesn't match the required schema.
Data path "" must NOT have additional properties (allowedNonPeerDependencies).
```

I noticed there is a new schema for secondary endpoints now.   Does this mean before 17.1 allowedNonPeerDependencies and dest never actually did anything before and the new  schema validates the unneeded properties are no needed included?

#### Version Information
```
ng-packagr:            17.1.0
@angular/compiler:     17.1.0
typescript:            5.2.2
```

**Comment by alan-agius4** [comment]
Correct, those properties never had any effect in secondary entry points

**Comment by krishna217** [comment]
@alan-agius4 but `dest` property is used to set the library build output. Now it just defaults to `dist` folder in library root folder.

**Comment by alan-agius4** [comment]
The dest option can still be used in the configuration of the primary entry point
