### ISSUE TITLE
Build inline SVG

### ISSUE THREAD

**Issue by omishyn-dm** [ng-packagr/ng-packagr#2770]
## Type of Issue

```
[ ] Bug Report
[ ] Feature Request
```

## Description

_A bug: after upgrade version from 17.0.3 to 17.1.0

_A feature: build did't make inline svg image

#### How To Reproduce

_A bug: please clone https://github.com/omishyn-dm/ng-packagr-17-1-0-inline-svg

npm i

npm run build

#### Expected Behaviour

_A bug: after build by path build/esm2022/components/no-data/no-data.component.mjs

you can find ... .icon[_ngcontent-%COMP%]{mask:center/contain no-repeat url(../../../assets/svg/no-data.svg)
but for prev version you can find ... .icon[_ngcontent-%COMP%]{-webkit-mask:center/contain no-repeat url("data:image/svg+xml

_A feature: do you have a first draft or an idea how to implement? No

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            17.1.0
@angular/compiler:     17.1.0
typescript:            5.2.2


_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by alan-agius4** [comment]
This should have been fixed in 17.1.1, can you please verify?
