### ISSUE TITLE
Can't import default export inside library component

### ISSUE THREAD

**Issue by krechtern** [ng-packagr/ng-packagr#2780]
## Type of Issue

```
[ x ] Bug Report
[ ] Feature Request
```

## Description

Hey, I have some trouble to import a default export inside a library component. To be specific I'm talking about `air-datepicker` and the import of one of the locale files like `import localeEn from 'air-datepicker/locale/en';`.

I have a mono repo with a root application and multiple libraries. I have already added `allowSyntheticDefaultImports: true` to the root `tsconfig.json`. The above mentioned import does work as expected inside the root application and gives me the locale object. But if I try the same import inside one of my library components it returns an object like this:

```
{default: {…}, __esModule: true}
```

I have no idea why it is not working within the library. It even works in storybook, when I add a `.stories.ts` file for my library component. So it seems like `ng-packagr` is doing something different here? It is basically the same problem as described here: [Angular Library Issue](https://github.com/angular/angular/issues/52805).

My root `tsconfig.json` looks like this:

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "skipLibCheck": true,
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitOverride": true,
    "noPropertyAccessFromIndexSignature": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "importHelpers": true,
    "target": "ES2022",
    "module": "ES2022",
    "useDefineForClassFields": false,
    "lib": ["ES2022", "dom", "esnext.asynciterable"],
    "allowSyntheticDefaultImports": true,
    "paths": {
      "wuh-design": ["dist/wuh-design"]
    },
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }
}
```

`tsconfig.lib.json`
```
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "outDir": "../../out-tsc/lib",
    "declaration": true,
    "declarationMap": true,
    "inlineSources": true,
  },
  "exclude": ["**/*.spec.ts"]
}

```

#### Expected Behaviour

I would expect the import to work exactly like in the root application.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            16.2.3
@angular/compiler:     16.2.12
rollup:                3.29.4
typescript:            5.1.6
node:                  18.17.1
npm:                   9.6.7
air-datepicker:        3.4.0
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by alan-agius4** [comment]
`ng-packagr` does not process dependent libraries these remain as external. In this case the `air-datepicker/locale/en` is a CJS dependency where default export behaviours differently and is in fact error prone. The problem you are encountering is described here: https://esbuild.github.io/content-types/#default-interop
