### ISSUE TITLE
secondary entry point peer deps

### ISSUE THREAD

**Issue by LPCmedia** [ng-packagr/ng-packagr#2785]
## Type of Issue

```
[X] Bug Report
[X] Feature Request
```

## Description

We are trying to figure out how to ship part of a library that requires a peerDep. When specifying peer deps in a secondary entry point, they are removed from the package.json that is output by the build. 

#### How To Reproduce

Create a library. 
Create a secondary entry point which depends on an external lib. In our case: monaco-editor. 
Add package.json to the entry point:

```
{
    "name": "@foo/ngx-components/editor",
    "version": "1.0.0",
    "peerDependencies": {
        "angular/core": "^12.0.0",
        "monaco-editor": "0.45.0"
    },
    "ngPackage": {
        "lib": {
            "entryFile": "src/index.ts"
        }
    }
}
```

#### Expected Behaviour

We build the lib and the peer deps are in the entry point's package json. 

instead we get: 

```
{
  "module": "../fesm2022/foo-ngx-components-editor.mjs"
}
```

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            17.1.2
@angular/compiler:     17.1.1
typescript:            5.3.3
node: v18.16.0
npm/yarn: 1.22.4
```

**Comment by JoostK** [comment]
Please see https://github.com/ng-packagr/ng-packagr/issues/1211#issuecomment-462251094.

**Comment by LPCmedia** [comment]
Thank you for quick response and clarification.
