### ISSUE TITLE
Documentation about postcss configuration

### ISSUE THREAD

**Issue by rikotsev** [ng-packagr/ng-packagr#2786]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description
I am trying to introduce a library that contains postcss/tailwind compilation. The current doc seems insufficient and vague.
The postcss and tailwind website provide completely different configurations.

#### Expected Behaviour
Provide some detailed documentation about the postcss configuration in order to compile the output styles

#### Version Information
ng-packagr:            17.1.2
@angular/compiler:     17.1.2
typescript:            5.3.3

**Comment by alan-agius4** [comment]
Can you elloborate on further information you'd like? The options and configuration are specific and vary based on the plugin you choice to use. However the format is always the same. 

The configuration allows two forms of config. 

```
{
  "plugins": ["plugin-name-1", ["plugin-name-2", { ... specific options for this plugin}]]
}
```
```
{
  "plugins": {
    "plugin-name-1": { ...specific options for this plugin},
    "plugin-name-2": { ...specific options for this plugin},
  }
}
```

Example if you'd want to choose https://github.com/csstools/postcss-short it would be 

```
{
  "plugins": {
    "postcss-short": { prefix: 'x' },
  }
}
```

**Comment by rikotsev** [comment]
Would this be considered a correct configuration:

```json
{
 "plugins": {
  "tailwindcss/nesting": "postcss-nesting"
  }
}
```

**Comment by alan-agius4** [comment]
Currently not, but it will be when https://github.com/ng-packagr/ng-packagr/pull/2789 is merged.
