### ISSUE TITLE
Cannot use import() to include external scripts in the library

### ISSUE THREAD

**Issue by MurhafSousli** [ng-packagr/ng-packagr#2787]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

When building the library, I get the following error

`Could not resolve "../scroll-timeline.js" from "dist/ngx-scrollbar/esm2022/lib/utils/scrollbar-manager.mjs"`

where the polyfill script is located inside library src directory

#### How To Reproduce

Reproduction repo https://github.com/MurhafSousli/ng-lib-dynamic-import-repro

1. `npm i` 
2. `ng-build`

***

Just import any JS file using the dynamic import `import()`

```ts
@Injectable({ providedIn: 'root' })
export class ScrollbarManager {
  constructor() {
      this.initPolyfill();
  }

  async initPolyfill(): Promise<void> {
    try {
      // Dynamically import the external script
      await import('../scroll-timeline.js');
    } catch (error) {
      console.error('Error loading ScrollTimeline script:', error);
    }
  }
}
```

#### Expected Behaviour

I would like to ship the polyfill with my library

#### Version Information

```
ng-packagr:            17.1.2
@angular/compiler:     17.1.2
typescript:            5.2.2
```

**Comment by MurhafSousli** [comment]
Just add a dynamic import in the library, any `import('./script.js')` function will throw the same error.

**Comment by MurhafSousli** [comment]
@JoostK Here is a minimal reproduction https://github.com/MurhafSousli/ng-lib-dynamic-import-repro, just run `ng build`

**Comment by JoostK** [comment]
The `scroll-timeline.js` is not an ES module. If you enable `"allowJs": true` in `tsconfig.json` there will by a TypeScript error:

> projects/test-library/src/lib/test-library.component.ts:23:20 - error TS2306: File 'C:/Downloads/ng-lib-dynamic-import-repro-main/projects/test-library/src/lib/scroll-timeline.js' is not a module.

Even if the file were to be copied you wouldn't be able to actually load it.
