### ISSUE TITLE
Improve Postcss Documentation

### ISSUE THREAD

**Issue by Astarosa** [ng-packagr/ng-packagr#2822]
## Type of Issue

**Doc change Request**

## Description

The Postcss is unclear concerning the tailwind css build in docs/postcss-config.md.

### Use case

I installed tailwind with postcss in a angular lib. As mentionned in the postcss-config doc i declared a postcss.config.json adding tailwind plugin. 

I declared the styles.css file in the src folder neer public-api.ts and imported it in.

![image](https://github.com/ng-packagr/ng-packagr/assets/47830787/418e31f2-afe0-43c1-bacc-82d41a9c1624)

I did not configure any additionnal assets management in ng-package.json or at the entrypoint package.json (should we ?)
based on the documentation that says it should resolve automatically the postcss config.

What is the expected output ? Standard should be a compiled styles.css but in my case it generate nothing.

![image](https://github.com/ng-packagr/ng-packagr/assets/47830787/7d9dbdf0-4dbf-4063-8af0-2b1f834f411e)

![image](https://github.com/ng-packagr/ng-packagr/assets/47830787/79201cb3-729b-4904-8202-1e9c10be49c7)

**Comment by alan-agius4** [comment]
From the looks of it you are trying to import the css in an incorrect way. Is this a component stylesheet?

**Comment by Astarosa** [comment]
It's a global tailwind stylesheet with :

@tailwind base;
@tailwind components;
@tailwind utilities;

**Comment by alan-agius4** [comment]
Using a CSS file as an ECMA module isn't supported. Additionally, it's advised against libraries having imports with side effects. Global stylesheets from a library should be included in the consumer app's style files.
