### ISSUE TITLE
Sub-package is being bundled even if nothing is imported from it.

### ISSUE THREAD

**Issue by MurhafSousli** [ng-packagr/ng-packagr#2860]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description

I have a package that has sub-packages in it.

`ngx-sharebuttons` is the main package that exports a directive.

`ngx-sharebuttons/icons` is a sub-package that exports a function, this function has a dependency of another package from **FontAwesome**.

The user has the option to use the icons package to load the default icons, but it is optional.

The problem is that when user install the package and then use only the directive from the main package (without importing anything from the sub-package). it throws an error caused by the sub-package on `ng serve`

```
[ERROR] Could not resolve "@fortawesome/angular-fontawesome"

    node_modules/ngx-sharebuttons/fesm2022/ngx-sharebuttons-icons.mjs:2:30:
      2 │ import { FaIconLibrary } from '@fortawesome/angular-fontawesome';
        ╵                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@fortawesome/angular-fontawesome" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.

✘ [ERROR] Could not resolve "@fortawesome/free-brands-svg-icons"

    node_modules/ngx-sharebuttons/fesm2022/ngx-sharebuttons-icons.mjs:3:181:
      3 │ ... faMix, faXing, faLine } from '@fortawesome/free-brands-svg-icons';
        ╵                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@fortawesome/free-brands-svg-icons" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.

✘ [ERROR] Could not resolve "@fortawesome/free-solid-svg-icons"

    node_modules/ngx-sharebuttons/fesm2022/ngx-sharebuttons-icons.mjs:4:97:
      4 │ ...k, faEllipsisH, faMinus } from '@fortawesome/free-solid-svg-icons';
        ╵                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@fortawesome/free-solid-svg-icons" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.

Error: Build failed with 3 errors:
node_modules/ngx-sharebuttons/fesm2022/ngx-sharebuttons-icons.mjs:2:30: ERROR: Could not resolve "@fortawesome/angular-fontawesome"
node_modules/ngx-sharebuttons/fesm2022/ngx-sharebuttons-icons.mjs:3:181: ERROR: Could not resolve "@fortawesome/free-brands-svg-icons"
node_modules/ngx-sharebuttons/fesm2022/ngx-sharebuttons-icons.mjs:4:97: ERROR: Could not resolve "@fortawesome/free-solid-svg-icons"
    at failureErrorWithLog (/home/projects/ngx-sharebuttons-mmsqmz/node_modules/vite/node_modules/esbuild/lib/main.js:1641:15)
    at eval (/home/projects/ngx-sharebuttons-mmsqmz/node_modules/vite/node_modules/esbuild/lib/main.js:1049:25)
    at eval (/home/projects/ngx-sharebuttons-mmsqmz/node_modules/vite/node_modules/esbuild/lib/main.js:1517:9) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}
```

#### How To Reproduce

Here is a [reproduction stackblitz](https://stackblitz.com/edit/ngx-sharebuttons-mmsqmz?file=package.json,src%2Fmain.ts)

This is the `package.json`

https://github.com/MurhafSousli/ngx-sharebuttons/blob/30c35371ea1b6d7e0ad67844ab9d62f0963ab396/projects/ngx-sharebuttons/package.json#L1-L13

The main package: https://github.com/MurhafSousli/ngx-sharebuttons/tree/master/projects/ngx-sharebuttons

The sub-package causing the issue: https://github.com/MurhafSousli/ngx-sharebuttons/tree/master/projects/ngx-sharebuttons/icons

#### Expected Behaviour

`ngx-sharebuttons/icons` should not be added to the bundle when nothing is imported in the app from its path.

And it should not throw an error on `ng serve`.

#### Version Information

```
ng-packagr:            18.0.0
@angular/compiler:     18.0.1
@angular/cdk:     18.0.1
typescript:            5.4.3
```

**Comment by JoostK** [comment]
The comment in https://github.com/MurhafSousli/ngx-sharebuttons/issues/673#issuecomment-2151378891 explains why: there is an import into this entry point and that does result in pulling in all its imports as well.

This is working as expected; while there is tree-shaking of unused symbols, the reachable module graph is still traversed during a build.
