### ISSUE TITLE
How to config less option?

### ISSUE THREAD

**Issue by iblislin** [ng-packagr/ng-packagr#2865]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

The PR #2678 removed the `math: 'always'` option from less, but I really need it. How to configure it? Seem that the `ng-package.json` don't support something like `lessOptions` in `angular.json`.

**Comment by alan-agius4** [comment]
Similar to the Angular CLI, ng-packagr does not provide an option to override this behaviour.
