### ISSUE TITLE
Allow devDependencies

### ISSUE THREAD

**Issue by jdegand** [ng-packagr/ng-packagr#2871]
## Type of Issue

```
[ ] Bug Report
[X] Feature Request
```

## Description

This [PR](https://github.com/angular/angular-cli/pull/15815) allows `ng-add` to use `devDependencies`.  `postBuild.js`  removes all `devDependencies` on line 12:  `delete packageJson['devDependencies'];`.  This package imposes limitations that would not apply if you didn't use it.  Is this an oversight or can nothing be done?

#### How To Reproduce

N/A

#### Expected Behaviour

Currently, `ng-packagr` strips all devDependencies.  I'd like to see a flag to allow `devDependencies` to be set. This will reduce bundle size and duplicate installs.

#### Version Information

N/A

**Comment by alan-agius4** [comment]
The mentioned pull request does not permit the use of dev dependencies directly. Instead, it allows the library to be configured to be saved as a dev dependency.

When installing a library, its dev dependencies are not installed.

For more information on NPM dependencies, you can refer to [this guide](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#dependencies).
