### ISSUE TITLE
How to share code between entrypoints - "private" entrypoints?

### ISSUE THREAD

**Issue by json-derulo** [ng-packagr/ng-packagr#2877]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

I have a library with multiple entrypoints and want to share code between them. However I don't want the shared code to be exposed to the consumers of the library. Example:

```
@mylib
|----- src
|      |----- Entrypoint-1
|      |----- Entrypoint-2
|      |----- Utils (not exposed)
```

I tried to implement this with TSConfig paths, however I can't get rid of the `File xxx is not unter 'rootDir'` error.

#### Proposed solution

I am not sure if this is technically possible, but my idea is to add a new `isPrivate` flag to the entrypoint configuration in `ng-package.json`. If set to true, the consumers will not be able to import this entrypoint. However inside the library, imports from this entrypoints are possible.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            18.0.0
@angular/compiler:     18.0.5
typescript:            5.4.5
```

**Comment by alan-agius4** [comment]
This is not possible.  However, while it's not possible to make it completely inaccessible, you can indicate that the entry point is for internal use only by naming it appropriately.
