### ISSUE TITLE
Angular 17+ new build system

### ISSUE THREAD

**Issue by dustydang-tyler** [ng-packagr/ng-packagr#2886]
I am currently upgrading from Angular 16 to Angular 18. I read on the changes that there is a new build system being implemented for the newer version.

However, most of my packages are using "ng-packagr" to build, my question is "will the new Angular build system have any impacts and or future updates to ng-packagr? Can I still be able to use ng-packagr?"

I did build my project after the upgrade; it seem like everything is build fine. But I just want to make sure.

**Comment by alan-agius4** [comment]
The new Angular build system only affects how applications are build.

no-packagr is still required and is still the preferred solution to build libraries.
