### ISSUE TITLE
Missing 18.2 GitHub Release

### ISSUE THREAD

**Issue by davidlj95** [ng-packagr/ng-packagr#2901]
## Type of Issue

```
[ ] Bug Report
[ ] Feature Request
[x] Another thingie
```

## Description

Version 18.2.0 has been released but it's not in the [releases page](https://github.com/ng-packagr/ng-packagr/releases)

I'm used to find all releases in there

#### How To Reproduce

N/A

#### Expected Behaviour

N/A

#### Version Information

N/A

**Comment by alan-agius4** [comment]
Added
