### ISSUE TITLE
Why don't move that project  to the Angular organization?

### ISSUE THREAD

**Issue by splincode** [ng-packagr/ng-packagr#2910]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

@alan-agius4 Hello, why don't you move this project to the Google repository? 

https://github.com/angular/ng-packagr

Perhaps this project would attract even more people to contribute

**Comment by alan-agius4** [comment]
We’ve talked about this a few times already. We do intend to eventually rewrite ng-packagr at some point in the future.

One challenge with moving it to the Angular organization is that not all contributors have signed the Google CLA. As for contributions, I’m not sure moving it will attract more contributors; for instance, we don't see many third-party contributors in the CLI repo.
