### ISSUE TITLE
Embebed Assets on 18.2.1

### ISSUE THREAD

**Issue by gothaussencl** [ng-packagr/ng-packagr#2918]
## Type of Issue

```
[ x] Bug Report
[ ] Feature Request
```

## Description

I have a library where we are exporting TTF (fonts) and SVG files, but it is not finding the relative path of these... so it is throwing the following errors:

<img width="632" alt="image" src="https://github.com/user-attachments/assets/74600133-673b-4f2a-b38c-b2a7ef9c9b9c">
<img width="301" alt="image" src="https://github.com/user-attachments/assets/25216064-eca3-4a4c-bf02-458d7317ff65">
<img width="763" alt="image" src="https://github.com/user-attachments/assets/719a7cb0-ade8-41d2-9aee-851d3410c6f1">

#### How To Reproduce

1.- clone repo: https://github.com/gothaussencl/ng-packagr-error
2.- run command npm install
3.- run command ng build

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 18.2.1
@angular/*: 18.2.4
typescript: 5.4.5
node: 22.8.0
npm/yarn: 10.8.2
```

**Comment by alan-agius4** [comment]
Hi, kindly provide a runnable reproduction thanks.

**Comment by gothaussencl** [comment]
I'm not so sure that I can share the executables, because the code belongs to a banking company, so I don't know how I can indicate how the error is reproduced.

I can only say that in version 16 of Angular we have no problem, but in 17 and 18 we do.

In case it is necessary to find a way to reproduce the error, please close the ticket and we will look for another way to "correct" it.

thanks and sorry

**Comment by alan-agius4** [comment]
A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by GusLAN** [comment]
I have the same problem when I use the 'intl-tel-input' library, and I can't access that file in the node_modules...

**Comment by NavneetVaid** [comment]
> Same problem here!

Did you find a solution ?

**Comment by NavneetVaid** [comment]
hi @alan-agius4 are we having any ETA on this ?

**Comment by NavneetVaid** [comment]
> I have the same problem when I use the 'intl-tel-input' library, and I can't access that file in the node_modules... The error is:
> 
> ✖ Compiling with Angular sources in Ivy partial compilation mode. Build failed with 4 errors: :15:27: ERROR: [plugin: angular-css-resource] Could not resolve "../img/flags.webp" :16:27: ERROR: [plugin: angular-css-resource] Could not resolve "../img/[flags@2x.webp](mailto:flags@2x.webp)" :17:27: ERROR: [plugin: angular-css-resource] Could not resolve "../img/globe.webp" :18:27: ERROR: [plugin: angular-css-resource] Could not resolve "../img/[globe@2x.webp](mailto:globe@2x.webp)"

Hey you got a solution ?
