### ISSUE TITLE
Any suggestions on how to use yarn berry for releasing?

### ISSUE THREAD

**Issue by aqeelat** [ng-packagr/ng-packagr#2938]
## Description

We're trying to create a release pipeline for our packaged libraries.
Currently, our process is
1. manually create a yarn sub package in the library folder (`touch yarn.lock && yarn`)
2. add yarn.lock to the assets array
3. Then in CI:
    * build
    * cd into dist
    * copy the .yarnrc.yml file into it (because it will have secrets populated during CI)
    * run `yarn npm publish`

I tried adding `"workspaces": ["projects/*"],` to package.json and then using the package.json below.
However, running `yarn workspace @org/package pack --dry-run` results in:
1. package.json that does not point to the dist folder
2. another package.json that's inside the dist folder
Which means that we will have to do `import * from '@org/package/dist'`

projects/user/package.json
```json
{
  "name": "@org/user",
  "version": "1.2.7",
  "files": ["dist/**/*"],
  "peerDependencies": {
    "@angular/common": "^16.2.12",
    "@angular/core": "^16.2.12",
    "@angular/router": "^16.2.12",
    "rxjs": "^7.8.1"
  },
  "dependencies": {
    "tslib": "^2.3.0"
  },
}
```
```
$ yarn workspace @org/user pack --dry-run
➤ YN0000: README.md
➤ YN0000: dist/README.md
➤ YN0000: dist/esm2022/org-user.mjs
➤ YN0000: dist/esm2022/lib/index.mjs
➤ YN0000: dist/esm2022/lib/user.const.mjs
➤ YN0000: dist/esm2022/lib/user.guard.mjs
➤ YN0000: dist/esm2022/lib/user.inteceptor.mjs
➤ YN0000: dist/esm2022/lib/user.model.mjs
➤ YN0000: dist/esm2022/lib/user.options.mjs
➤ YN0000: dist/esm2022/lib/user.service.mjs
➤ YN0000: dist/esm2022/public-api.mjs
➤ YN0000: dist/fesm2022/org-user.mjs
➤ YN0000: dist/fesm2022/org-user.mjs.map
➤ YN0000: dist/index.d.ts
➤ YN0000: dist/lib/index.d.ts
➤ YN0000: dist/lib/user.const.d.ts
➤ YN0000: dist/lib/user.guard.d.ts
➤ YN0000: dist/lib/user.inteceptor.d.ts
➤ YN0000: dist/lib/user.model.d.ts
➤ YN0000: dist/lib/user.options.d.ts
➤ YN0000: dist/lib/user.service.d.ts
➤ YN0000: dist/package.json
➤ YN0000: dist/public-api.d.ts
➤ YN0000: package.json
```

I think the issue is with yarn trying to pack the entire workspace. Not sure if this is something ng-packagr can help with, but I would like to know how other users are solving this problem.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            16.2.3
@angular/compiler:     16.2.12
rollup:                3.29.4
typescript:            4.9.5
yarn 4.2.2
```

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/)
