### ISSUE TITLE
Need to add Angular compatibility table

### ISSUE THREAD

**Issue by irfanullahjan** [ng-packagr/ng-packagr#2957]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

There is a need to add a docs page / section with a table that specifies which version of `ng-packagr` is compatible with which version(s) of Angular. This is because, Angular has a peer dependency on a range of Typescript versions, but `ng-packagr` too has such a peer dependency. If an app sticks to older Angular versions e.g. 17, they are not compatible with latest `ng-packagr` versions and Typescript compilation fails.

It is suggested to add a table that lists down compatible `ng-packagr` versions against each major Angular compiler version.

**Comment by alan-agius4** [comment]
ng-packagr versions are match the extract versions of what Angular support.

Example ng-package follow the same version strategy of Angular.

Version 19.0 support Angular 19.0 and its typescript versions, version 19.1 supports Angular 19.0 and 19.1 and its typescript version and so on.

The generated libraries are compatible with the Angular version used to compile the library and 2 future major.

See: https://angular.dev/tools/libraries/creating-libraries
