### ISSUE TITLE
/// <reference types="grecaptcha" /> is not being appended in d.ts files

### ISSUE THREAD

**Issue by LakhveerChahal** [ng-packagr/ng-packagr#2961]
## Type of Issue

```
[Y] Bug Report
[ ] Feature Request
```

## Description

`/// <reference types="grecaptcha" />` is not being appended in d.ts files which have reference to types belonging to grecaptcha (or any other library for that matter).

If we use the npm packed tgz of it in another angular application, then it throws error like:
error TS2503: Cannot find namespace 'ReCaptchaV2'. because of the missing reference/link to the source types i.e. grecaptcha.

#### How To Reproduce

1. Create a new angular v19 based library (for e.g. my-lib).
2. perform npm i @types/grecaptcha for both package.json (root & project).
3. Add "grecaptcha" in the types property of tsconfig.lib.json.
4. Add "@types/grecaptcha" in allowedNonPeerDependencies property of ng-package.json
5. Now consume any type of grecaptcha in any file of library. For e.g. ReCaptchaV2.Theme can be consumed.
6. Perform ng build my-lib and observe that /// <reference types="grecaptcha" /> is not appended in the correspondong d.ts file where type was consumed.
7. npm pack it and consume it in another angular application and do ng serve & you will get the above mentioned error.

_Can you reproduce the error in the integration tests in ng-packagr?_
Not checked

_Is the error you faced in an application importing the library_
Yes.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 19.0.1
@angular/*: 19.0.0
typescript: 5.6.0
rxjs: 6.5.3
node: 20.13.1
yarn: 1.22.22
```

**Comment by alan-agius4** [comment]
This is one of the changes in TypeScript 5.5. See: https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/#simplified-reference-directive-declaration-emit
