### ISSUE TITLE
Generate cli files

### ISSUE THREAD

**Issue by ocombe** [ng-packagr/ng-packagr#298]
## Type of Issue

```
[x] Feature Request
```

## Description

My library exports a standard angular library, but it also has a cli tool that can be used to transform some data to be consumed by my library.
Is there a way to use ng-packagr to generate this "bin" file as well?

**Comment by dherges** [comment]
Hi @ocombe,

at the moment: no. ng-packagr generates the [FESM's, UMD's, AoT metadata, and Type Definitions](https://github.com/dherges/ng-packagr/blob/master/src/lib/model/ng-artifacts.ts#L4-L17) and writes them to the distribution-ready `package.json`.

You can, however, add the `bin` property to your source `package.json` as it will be copied to the resulting JSON. I guess you need an additional JavaScript file in `dist` for the cli tool, right? There's no way for ng-packagr to compile that "extra" `*.ts` source file

**Comment by ocombe** [comment]
Ok, it could be a nice addition.
For now I've added a new script to compile my cli part with tsc, it seems to work fine. The only downside is that it adds .js files for the shared parts of my lib
