### ISSUE TITLE
[v1] tsickle crashes during build: `TypeError: node.getFullStart is not a function`

### ISSUE THREAD

**Issue by amcdnl** [ng-packagr/ng-packagr#311]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description
Trying to setup ng-packagr on `ngx-datatable`, when i run the build I get the following errors.
```
> ng-packagr -p ng-package.json

Building Angular library
Generating bundle for @swimlane/ngx-datatable
Cleaning bundle build directory
Processing assets
Running ngc

BUILD ERROR
node.getFullStart is not a function
TypeError: node.getFullStart is not a function
    at Annotator.Rewriter.writeNode (/Users/austin/dev/ngx-datatable/node_modules/@angular/tsc-wrapped/node_modules/tsickle/build/src/rewriter.js:70:24)
    at Annotator.Rewriter.visit (/Users/austin/dev/ngx-datatable/node_modules/@angular/tsc-wrapped/node_modules/tsickle/build/src/rewriter.js:53:18)
    at Annotator.maybeProcessEnum (/Users/austin/dev/ngx-datatable/node_modules/@angular/tsc-wrapped/node_modules/tsickle/build/src/tsickle.js:1188:22)
    at Annotator.maybeProcess (/Users/austin/dev/ngx-datatable/node_modules/@angular/tsc-wrapped/node_modules/tsickle/build/src/tsickle.js:676:29)
    at Annotator.Rewriter.visit (/Users/austin/dev/ngx-datatable/node_modules/@angular/tsc-wrapped/node_modules/tsickle/build/src/rewriter.js:52:19)
    at /Users/austin/dev/ngx-datatable/node_modules/@angular/tsc-wrapped/node_modules/tsickle/build/src/rewriter.js:84:19
    at visitEachNode (/Users/austin/dev/ngx-datatable/node_modules/typescript/lib/typescript.js:15956:30)
    at Object.forEachChild (/Users/austin/dev/ngx-datatable/node_modules/typescript/lib/typescript.js:16136:24)
    at Annotator.Rewriter.writeNode (/Users/austin/dev/ngx-datatable/node_modules/@angular/tsc-wrapped/node_modules/tsickle/build/src/rewriter.js:82:12)
    at Annotator.Rewriter.visit (/Users/austin/dev/ngx-datatable/node_modules/@angular/tsc-wrapped/node_modules/tsickle/build/src/rewriter.js:53:18)
```

#### How To Reproduce
- Clone [https://github.com/swimlane/ngx-datatable](https://github.com/swimlane/ngx-datatable)
- Define `ngPackage` w/ entry point `src/index.ts`
- Run `ng-packagr -p ng-package.json`

#### Expected Behaviour
No errors

#### Version Information

```
ng-packagr: latest
node: v8
@angular: v5
"zone.js": "^0.8.18"
"rxjs": "^5.0.0"
```

**Comment by DavidParks8** [comment]
try ng-packagr@next. It should have fixed this issue.

**Comment by dherges** [comment]
yes, for Angular v5, please use the 2.0.0 release candidates. Please note the peerDependency on `"typescript": "~2.4.x"`!

**Comment by dherges** [comment]
Hi @amcdnl, followed your instructions and it confirmed your bug report in the 1.6.0 version.

I'll accept PRs for bug fixes in the `v1` branch.

Then, switched to Angular 5 and ng-packagr@next

```
$ cat node_modules/@angular/compiler-cli/package.json | grep version 
  "version": "5.1.0"
$ cat node_modules/@angular/compiler/package.json | grep version 
  "version": "5.1.0"
$ cat node_modules/tsickle/package.json | grep version
    "type": "version",
  "version": "0.25.5"
$ cat node_modules/ng-packagr/package.json | grep version
    "type": "version",
  "version": "2.0.0-rc.6"
$ npm run packagr 

> @swimlane/ngx-datatable@11.1.5 packagr /Users/David/Projects/github/swimlane/ngx-datatable
> ng-packagr -p package.json

Building Angular Package
Building from sources for entry point '@swimlane/ngx-datatable'
Cleaning build directory
Extracting templateUrl and styleUrls
Processing assets
Inlining templateUrl and styleUrls
Compiling with ngc

BUILD ERROR
src/types/table-column.type.ts(11,1): warning TS0: @type annotations are redundant with TypeScript equivalents
src/types/table-column.type.ts(17,3): warning TS0: @type annotations are redundant with TypeScript equivalents
src/types/table-column.type.ts(25,3): warning TS0: @type annotations are redundant with TypeScript equivalents
src/types/table-column.type.ts(33,3): warning TS0: @type annotations are redundant with TypeScript equivalents
```

So, that's at least one error further down the road!

Checked by direct ngc:

```bash
$ node_modules/.bin/ngc -p tsconfig-aot.json
src/types/table-column.type.ts(11,1): warning TS0: @type annotations are redundant with TypeScript equivalents
src/types/table-column.type.ts(17,3): warning TS0: @type annotations are redundant with TypeScript equivalents
src/types/table-column.type.ts(25,3): warning TS0: @type annotations are redundant with TypeScript equivalents
src/types/table-column.type.ts(33,3): warning TS0: @type annotations are redundant with TypeScript equivalents
src/types/table-column.type.ts(41,3): warning TS0: @type annotations are redundant with TypeScript equivalents
src/types/table-column.type.ts(49,3): warning TS0: @type annotations are redundant with TypeScript equivalents

$ echo $?
1
```

Same errors in Angular 5.

**Comment by Lexanius** [comment]
Same Problem here.

I create a Example for the `warning TS0: @type annotations are redundant with TypeScript equivalents`.
See: https://github.com/Lexanius/packagr-error-example

The `node_modules/.bin/ngc -p .\tsconfig.json` runs without error.

**Comment by Lexanius** [comment]
So i found a solution, its seems to be a dirty hack: 
I changed
`shouldIgnoreWarningsForPath: (filePath) => false,`
to
`shouldIgnoreWarningsForPath: (filePath) => true,`
in
https://github.com/dherges/ng-packagr/blob/f895782e1f2fc6c954880cbb99567546d9d7a139/src/lib/util/ngc-patches.ts#L36

**Comment by westphalen** [comment]
Is this really still a problem?

warning TS0: @type annotations are redundant with TypeScript equivalents.

in Angular 5 is completely breaking my ng-packagr build.

**Comment by Aaltuj** [comment]
I have the same issue with angular 5.2.7 and with ng-packagr 2.4.1

**Comment by zsagia** [comment]
BUILD ERROR
node_modules/angular-bootstrap-md/utils/component-loader/component-loader.factory.ts(18,3): warning TS0: the type annotation on @return is redundant with its TypeScript type, remove the {...} part

**Comment by ledicjp** [comment]
Same problem here, we have a big project with a lot of JSDoc annotations

**Comment by DenisVuyka** [comment]
Just upgraded a project to `^2.4.5` and now can't compile the project because of

```
the type annotation on @param is redundant with its TypeScript type, remove the {...} part
```

**Comment by elclanrs** [comment]
This is a problem in our project as well. I'm using the latest angular-cli with ng-packgr@3.0.0-rc.2 and cannot compile the library due to these errors.

Any way to turn this into a a warning instead?

**Comment by chillinski** [comment]
I also have this problem. We are working on a large project using a common components library and testing tools which need a good documentations as the common code is shared among teams and locations in our company.

Is there some progress on this?

**Comment by mattezell** [comment]
@chillinski still an issue for me with v3.0.1... Same boat - large project that we're in the process of migrating to 6.0 and I have a wall of this warning turned build breaking error exceeding my console's buffer to deal with...

**Comment by jorgeriv** [comment]
Using v3.0.3 and facing the exact same issue. u_u

**Comment by jscharett** [comment]
What's preventing this from being fixed?  According to tsickle, they are just throwing warnings not errors, so why is this lib converting them to errors?  This is an annoying problem considering it involves comments preventing the package being built.

**Comment by alan-agius4** [comment]
Tsickle shouldn’t be used outside of Google. Unless we explicitly use closure compiler.
