### ISSUE TITLE
[PR WELCOME] Control naming of secondary entry points?

### ISSUE THREAD

**Issue by ClemensSchneider** [ng-packagr/ng-packagr#315]
## Type of Issue

```
[ ] Bug Report
[ x] Feature Request
```

## Description

Is it somehow possible to control the naming of secondary entry points?

So if a library is named `@myCompany/awesomeLib` and if an entry point is placed inside `src/snd` it is currenty being bundled as `@myCompany/awesomeLib/src/snd`.

It would be nice to define that the secondary entry point gets named `@myCompany/awesomeLib/snd` in this case, which seems only possible by moving the `snd` folder to the root of the lib (outside of `src`).

#### Version Information

```
ng-packagr: v2.0.0.rc2
node: v8.7.0
@angular: v5.0.2
rxjs:
zone.js:
```

**Comment by dherges** [comment]
Hi @ClemensSchneider,

this is a valid and good point!

There was a discussion in https://github.com/dherges/ng-packagr/issues/190#issuecomment-339994677 regarding this.

My proposal for `ng-package.json` / `package.json $.ngPackage`:

Default "auto" implements the current behaviour (auto discovery):
```json
  "lib": {
    "secondaries": "auto"
  }
```

Declarative config `Array<{}>` with objects implements the behaviour as described above:
```json
  "lib": {
    "secondaries: [
      {
         "path": "foo"
         "entryFile": "foo.ts"
      }
     ]
  }
```

`path` is the "sub-path" under the root package, e.g.: when root package is `@org/sample`, the secondary package will be `@org/sample/foo`.

`entryFile` is the public API surface of the secondary entry point.

**Comment by ClemensSchneider** [comment]
Sounds good to me!

**Comment by matheo** [comment]
Thanks for the great stuff!

I wonder how to handle the dependencies here. I have a `@org/components` root package, and I would like to have `@org/components/shared` for shared utilities and stuff.

The root package can import stuff from `shared` without generating duplicated compile code?
Is there a way to set up this kind of "dependency"?

**Comment by dherges** [comment]
@matheo Currently not. Discussions and ideas for that in #379.

For the initial idea of @ClemensSchneider, a pull request is welcome! 😄

**Comment by CSchulz** [comment]
I think the issue with src in package name is resolved, but in general it is not possible to define a custom name because it is set hard coded:

https://github.com/ng-packagr/ng-packagr/blob/d02142b23201bda87e06b7cd981a565a1b227b5a/src/lib/ng-v5/discover-packages.ts#L139

It would be nice if the user is able to override that path, because sometimes you are creating some folders for structuring which should not take into account for the package name.

**Comment by alan-agius4** [comment]
Closing as this is out of scope.
