### ISSUE TITLE
[PR WELCOME] Angular package format 5: Metadata version mismatch

### ISSUE THREAD

**Issue by Ks89** [ng-packagr/ng-packagr#344]
## Type of Issue

This is not a real bug/feature, but I want to show that libs built with Angular package format 5 (ng-packgr 2.0.0-rc.4) don't compile with Angular 4 + AOT.
When you try to build your project with Angular 4 and AOT you'll get this error: 
`Angular package format 5: Error: Metadata version mismatch for module "..." found version 4, expected 3`

However, both Angular 4 (only JIT, but not AOT) and Angular 5 will work without problems.

This could be a problem, because If you have a library you cannot remove Angular 4 support today.

#### Version Information

```
ng-packagr: v2.0.0-rc.4
node: v8.9.0
@angular: v4.4.6
rxjs: latest version
zone.js: latest version
```

**Comment by dherges** [comment]
Hi Stefano,

Thanks for reporting! You give a good issue description / error report.

The behaviour is in effect intended with the 2.x RC. For Angular 4, my personal reco is to stick with ng-packagr 1.x. If you go dual-support angular 5 and 4 (which personally I’d try to avoid), it also stretches out to the typescript version: typescript 2.3 for angular 4 and 2.4 for angular 5. 

Cheers, David

**Comment by Ks89** [comment]
Ok thank u for the explanation.

Probably I'll force my lib to angular 4 and ng-packagr 1.x until angular 6.0.0. I'm agree with you, in fact, all users can compile also with Angular 5 without issues. 

Are you thinking to push updates also for ng-packagr 1.x until angular 6,or did you decide to deprecated that version?

**Comment by dherges** [comment]
It's not really deprecated. It's just an "older" version which you can keep using.

If you go dual-support different Angular versions, you also likely have support branches like `version/4.x`, `version/5.x`, `master`, and so on. If you do so, I'd keep on the `version/4.x` the 1.x dependency and on `version/5.x` the 2.x (rcs).

At most, we can print an error message or fail the build, when compilation encounters Angular 4 sources.

**Comment by Ks89** [comment]
Ok.. Mmm yes a warning or an error could be really usefull.

**Comment by alan-agius4** [comment]
Addressed alresdy
