### ISSUE TITLE
Dynamic service injection not working after packaging

### ISSUE THREAD

**Issue by cathy02** [ng-packagr/ng-packagr#350]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

Dynamic service injection not working after packaging.

#### How To Reproduce

// NPM Package 1:
@Injectable() 
export abstract class BaseService { ... }
@Injectable()
export class ServiceA extends BaseService { ... }
@Injectable()
export class ServiceB extends BaseService { ... }

// NPM Package 2: depend on Package 1
// nav.module.ts
@NgModule({
    imports: [ ... ],
    declarations: [
        NavComponent
    ],
    exports: [
        NavComponent
    ],
    providers: []
})
export class NavModule { }

// nav.component.ts
@Component({
    selector: 'app-nav',
    ...
})
export class NavComponent {
    constructor(private baseService: BaseService) { ... }
}

// main project: depend on both Package 1 and 2
// app.module.ts:
@NgModule({
    declarations: [
        AppComponent
    ],
    imports: [
        NavModule
    ],
    providers: [
        {provide: BaseService, useClass: ServiceB }
    ],
    bootstrap: [AppComponent]
})
export class AppModule { }

// app.component.ts
@Component({ ... })
export class AppComponent implements OnInit {
    constructor(private baseService: BaseService) { }
    ...
}

// app.component.html
<app-nav></app-nav>

#### Expected Behaviour

The BaseService should get injected with ServiceB in package 2.

When running the project, I got the error:
     Error: No provider for BaseService!
The service is not injected into the NPM package 2.

If I directly include the code for NPM package 2 in the main project, there is no problem. The BaseService will get injected as ServiceB.

#### Version Information

```
ng-packagr: v1.6.2
node: v8.x.y
@angular: v4.2.4
rxjs:
zone.js:
```

_please include any version information that might be relevant, e.g. other third-party libraries_

**Comment by alan-agius4** [comment]
I am not sure if its a mistake in the example but in `NPM Package 2:` you are not specifying any `provider` for `BaseService`

**Comment by alan-agius4** [comment]
I am not sure if it's the problem but in the example but in `NPM Package 2` you are not specifying any `provider` for `BaseService` I might be wrong but AFAIK, you should include a `default` one, and than if you want to override it, you can do so in the `AppModule`. When you are moving your code to the main project are you combine the the package 2 in `AppModule` or still using `NavModule`?

It would be great if you can provide a minimal re-production.

**Comment by cathy02** [comment]
First, I can't specify service provider at NPM package 2. If I am doing, that, there will be two instances of the service in the application which is not I want.

Second, I don't know exactly which service to provide at the NPM package 2. It is a generic component and which service to use is decided at the application level. This is why I used abstract service/class.

**Comment by alan-agius4** [comment]
Not really, since all providers are singelons unless specified other
wise.  When
there are multiple providers for the same injection token, the last
registration wins.

My 2 cents are on the fact that at compilation package 2 doesn’t know of
BaseService as it’s not declared as provider.

That said, it would be more helpful if you create a sample project.

**Comment by cathy02** [comment]
I think the problem is that when NPM Package 2 was used, it is creating its own scope of providers. Looks like a lazy-loading module, but I imported the module in the App.Module.ts. So it should not be lazy loaded.

Try to see whether I can create sample project. It needs some work to set it up.

**Comment by alan-agius4** [comment]
Closing as this should not longer be a problem
