### ISSUE TITLE
[AoT] can't resolve all parameters for [lib] in [lib].d.ts: (?, ?, ?)

### ISSUE THREAD

**Issue by ghiscoding** [ng-packagr/ng-packagr#377]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I can compile my lib successfully with `ng-packagr` (version `1.6`) and I then published it to NPM and it's all good. Except when I'm trying to compile the external app as AOT/Prod, I get the following error:
```bash
ERROR in Error: Can't resolve all parameters for AngularSlickgridComponent in C:/sourcecode/Angular-Slickgrid-PackageTest/node_modules/angular-slickgrid/angular-slickgrid.d.ts: (?, ?, ?, ?, ?, ?).
    at syntaxError (C:\sourcecode\Angular-Slickgrid-PackageTest\node_modules\@angular\compiler\bundles\compiler.umd.js:1729:34)
    at CompileMetadataResolver._getDependenciesMetadata (C:\sourcecode\Angular-Slickgrid-PackageTest\node_modules\@angular\compiler\bundles\compiler.umd.js:15816:35)
    at CompileMetadataResolver._getTypeMetadata (C:\sourcecode\Angular-Slickgrid-PackageTest\node_modules\@angular\compiler\bundles\compiler.umd.js:15684:26)
    at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (C:\sourcecode\Angular-Slickgrid-PackageTest\node_modules\@angular\compiler\bundles\compiler.umd.js:15279:24)
    at CompileMetadataResolver.loadDirectiveMetadata (C:\sourcecode\Angular-Slickgrid-PackageTest\node_modules\@angular\compiler\bundles\compiler.umd.js:15141:25)
    at C:\sourcecode\Angular-Slickgrid-PackageTest\node_modules\@angular\compiler\bundles\compiler.umd.js:15380:54
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.loadNgModuleDirectiveAndPipeMetadata (C:\sourcecode\Angular-Slickgrid-PackageTest\node_modules\@angular\compiler\bundles\compiler.umd.js:15379:41)
    at C:\sourcecode\Angular-Slickgrid-PackageTest\node_modules\@angular\compiler\bundles\compiler.umd.js:23799:99
    at Array.map (<anonymous>)
    at AotCompiler.analyzeModulesAsync (C:\sourcecode\Angular-Slickgrid-PackageTest\node_modules\@angular\compiler\bundles\compiler.umd.js:23799:42)
    at CodeGenerator.codegen (C:\sourcecode\Angular-Slickgrid-PackageTest\node_modules\@angular\compiler-cli\src\codegen.js:32:14)
    at Function.NgTools_InternalApi_NG_2.codeGen (C:\sourcecode\Angular-Slickgrid-PackageTest\node_modules\@angular\compiler-cli\src\ngtools_api.js:73:30)
    at _donePromise.Promise.resolve.then (C:\sourcecode\Angular-Slickgrid-PackageTest\node_modules\@angular\cli\node_modules\@ngtools\webpack\src\plugin.js:386:44)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

#### How To Reproduce

Install my lib, [Angular-Slickgrid](https://github.com/ghiscoding/Angular-Slickgrid) from [NPM](https://www.npmjs.com/package/angular-slickgrid) and try to compile in AOT, you will get the error shown on top. You can also see the [dist](https://github.com/ghiscoding/Angular-Slickgrid/tree/master/dist) folder of the `ng-packagr` compilation (which is run through `ng-packagr -p ng-package.json`). I also know that the (?, ?, ?, ...) are the Services dependency injections, but I don't know why it only shows up in AOT compilation

I am fairly new to Angular 4+ (just a couple months since I started) and I'm confused with all these JIT, AOT, .. and I don't know what could be the problem or where to look. The search that I have done brings nowhere, I thought it was cyclical dependencies as shown [here](https://github.com/angular/angular-cli/issues/6997) but it can't be it since `showCyclicalDependencies` is enabled by default in Angular-CLI since `1.3`. I believe that I have this problem since long time but it works all good in Dev environment, it's really just AOT that fails. 

Any help is appreciated, I really need to resolve this issue. 

#### Expected Behaviour

No error thrown

#### Version Information

```
ng-packagr: 1.6.0
@angular/*: 4.x.x
typescript: 2.3.4
rxjs: 5.4.2
node: 8.70
npm: 5.4.1
```

_please include any version information that might be relevant, e.g. other third-party libraries_

**Comment by dherges** [comment]
Hi @ghiscoding,

usually ... the error messages (?, ?, ?, ... ) appears due to cyclic dependencies and when the `import { foo } from 'bar'` results in `foo = undefined`. 

Ok. The constructors params of the component you mentioned are:

```js
/**
 * @nocollapse
 */
AngularSlickgridComponent.ctorParameters = function () { return [
    { type: ControlAndPluginService, },
    { type: GridEventService, },
    { type: GridExtraService, },
    { type: FilterService, },
    { type: ResizerService, },
    { type: SortService, },
]; };
```

What makes me alittle wonder and looks strange is the bundle index you posted:

```
/**
 * Generated bundle index. Do not edit.
 */
export {
/* ... */,
FilterService, GridEventService, GridExtraService,
/* ... */,
AngularSlickgridComponent, AngularSlickgridModule,
/* ... */
FilterService as ɵe, GridEventService as ɵc, GridExtraService as ɵd
/* ... */
};
```

It happened here – https://github.com/dherges/ng-packagr/issues/382#issuecomment-350434201 – too that symbols were exported twice in the bundle index?!?

That could be a starting point trying to get rid of the duplicate exports ... I don't know why it's happening...

**Comment by ghiscoding** [comment]
Thanks for posting some things to look into, I will take a look at that in the coming days. What I did try so far is to make sure that the Services are imported in the correct order (that is what I read about cyclical dependencies) but that didn't change a thing and I also read that in latest version of Angular/TypeScript, it doesn't really matter what the order is anymore. 

I did see the double export in the bundle but thought it was normal. However, I do have multiple exports in some areas, specifically I created some `index.ts` in some of my folders (Services, Models, ...) to make it easy to deal with, so I can have multiple models from 1 import. I also re-export them all in the main component itself, is that a wrong thing to do? If so, what approach would you suggest?

Thanks for your great packager. It does help in building library (even if the packaging of a library is still cumbersome in Angular, I got headache when looking at it the first time as I just started to switch from AngularJS to Angular. I'm still having hard time to connect all the dots (AOT, JIT, Tree Shacking, ...)

**Comment by ghiscoding** [comment]
@dherges thanks a lot for your help, you pointed me in the good direction of finding the real issue. I had double exports for some of the files in my lib and it works in most cases except for Services because of how they are exported by Angular itself. So basically, I had an `index.ts` in my Services folder (for convenience) and that was the cause of my problem, I removed it and import my services 1 by 1 in the lib component and now it works and there's no double export showing up in the bundle index (d.ts)

Thanks a lot for your amazing packager, if you ever create a "Used by" list, feel free to add my lib. 
My next move would be to upgrade to your latest `2.x-rc`, last time I tried it gave me a few errors but that's another story :)

**Comment by dherges** [comment]
@ghiscoding I

**Comment by dherges** [comment]
Hi @ghiscoding,

cool you found that out!

You say that your library "now works", right? Can you post the changes you made? If possible, just the minimal changeset needed to remove the issue. Also, to see the "working" metadata JSON file compared to the "non-working" metadata JSON would really help.

I don't know whether it's an issue in how ng-packagr is implemented and how it is using the Angular compiler `ngc` or whether it is an issue of ngc itself.

You'd help us with the above infos!

**Comment by ghiscoding** [comment]
Ah ok sure, see below for what I think were the errors in my case

1- I had an `index.ts` with export of all my Services. 
   - deleted the `index.ts` from Services folder

2- Inside my lib component, I was calling in a 1 liner all my Services
   - changed `import` to call the Services 1 by 1 
```diff
-import { ControlAndPluginService, FilterService, GridEventService, GridExtraService, SortService, ResizerService } from './../services';
+import { ControlAndPluginService } from './../services/controlAndPlugin.service';
+import { FilterService } from './../services/filter.service';
+import { GridEventService } from './../services/gridEvent.service';
+import { GridExtraService } from './../services/gridExtra.service';
+import { ResizerService } from './../services/resizer.service';
+import { SortService } from './../services/sort.service';

So I think the #2 is what caused the `can't resolve all parameters for [lib] in [lib].d.ts: (?, ?, ?, ?, ?, ?)`
There is no longer duplicates export in my `d.ts` file and the DI is working as expected. 

I had other errors to fix after but I don't think they are related at all to the original problem, so I won't post them here unless you want to see them too.

**Comment by dherges** [comment]
Is this the commit hash you refer to?  https://github.com/ghiscoding/Angular-Slickgrid/commit/dc8447d8aa503dace199587a5cfa31bbffae2595

**Comment by ghiscoding** [comment]
correct

**Comment by trentrand** [comment]
For me, the issue is that I was importing from the barrel, instead of directly from the files.

Check your `my-module.d.ts` file in the library distributable directory, in my case it was inside `/dist/lib`.

If you see any exports in addition to `export * from './public_api';`, and `./public_api` also exports those same exports; that is the cause of your issue. To stop these exports from being exported twice, you'll need to remove all imports from barrels inside your library.

## Example
A simple Find-all for the ending of my barrel path `myModule';` showed me all occurrences of where I was importing from the barrel; then I simply expanded these imports to import each file independently.

**Before**
```
import { MenuService, MenuItem } from '../menu-service';
```
**After**
```
import { MenuService } from '../menu-service/menu.service';
import { MenuItem } from '../menu-service/menu-item';
```

**Comment by SaturnTeam** [comment]
You should add this to FAQ. It takes a month to find this solution

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent ng-packagr.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
