### ISSUE TITLE
sass: "~" import not resolved to parent node_modules

### ISSUE THREAD

**Issue by kklimczak** [ng-packagr/ng-packagr#414]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

My library use the foundation sites dependency. When I install library as dependency in my main project, foundation sites dep has landed inside root node_modules instead of the library node_modules directory, so my sass import g.e. `@import "~foundation-sites/scss/util/util";` not working. NPM > v2 has new installer which flat dependencies as maximally as possible.

```
BUILD ERROR
File to import not found or unreadable: /home/klimczakk/workspace/oauth-client/node_modules/ng-shared-module/node_modules/foundation-sites/scss/util/util.
Parent style sheet: /home/klimczakk/workspace/oauth-client/node_modules/ng-shared-module/src/core/components/sidebar/sidebar.component.scss
Error: File to import not found or unreadable: /home/klimczakk/workspace/oauth-client/node_modules/ng-shared-module/node_modules/foundation-sites/scss/util/util.
Parent style sheet: /home/klimczakk/workspace/oauth-client/node_modules/ng-shared-module/src/core/components/sidebar/sidebar.component.scss
    at options.error (/home/klimczakk/workspace/oauth-client/node_modules/node-sass/lib/index.js:291:26)
```

#### How To Reproduce

Create app with library dependency, which has sass dependency (in my case foundation-sites) and not mentioned in app package.json. Next, import sass file from sass dependency any partial sass file with `~` and build in library postinstall hook.

#### Expected Behaviour

I think it's a problem with [https://www.npmjs.com/package/node-sass-tilde-importer](node-sass-tilde-importer) which search nearest parent node_modules, so ng-packagr couldn't found dep in root node_modules. Import with `~` could find module not only nearest node_modules.

#### Version Information

```
ng-packagr: 1.6.0
@angular/*: 5.0.0
typescript: 2.4.2
rxjs: 5.5.0
node: 8.9.1
npm/yarn: 5.5.1
foundation-sites: 5.4.1
```

**Comment by dherges** [comment]
For understanding and clarification, are there several node_modiles folder in the tree?

```
node_modules
  |- a
lib
  |- package.json
  |- ng-packagr.json
  |- src
      |- node_modules
```

For example like that?

**Comment by kklimczak** [comment]
The problem occures when use ng-packagr with postinstall hook (g.e. link your library as git repository inside app root package.json), so directory tree looks like:
```
app
  | - node_modules <--- dependency lands here
    | - my_library
      | - package.json
      | - ng-packagr.json
      | - node_modules <--- node-sass-tilde-importer search dependency here 
```
This solution works only when I add different version of foundation-sites in my library and app package.json.

**Comment by ennovum** [comment]
@dherges sorry to bug you, but is there a timeline for fixing this one? It's blocking my team and I'd like to know if it makes sense to wait.

**Comment by dherges** [comment]
@ennovum There's (`styleIncludePaths`)[https://github.com/dherges/ng-packagr/blob/master/src/ng-package.schema.json#L84-L90]. Does it solve your scenario?

**Comment by ennovum** [comment]
@dherges It might, but we ended up refactoring our dependencies and flattening the dependency tree. Thanks!

**Comment by vZanchiV** [comment]
@dherges 

i need your help plz, thx for ngpackagr is a amazing lib , but i have a problem

my config :

i use angular 4  an cli 1.6.5
src
 -- app
-- assets
    -- css
       _variables.scss


I use  in my file angular-cli.json 
```
"stylePreprocessorOptions": {
        "includePaths": [
          "./assets/css"
        ]
      },
```

so after that i can importe my file variable inside my component.scss.



in ng-package.json i add 

` "lib": {
        "entryFile": "public_api.ts",
        "styleIncludePaths": [
            "./assets/css"
        ],`




But when i try to npm run packagr  i had this errror

File to import not found or unreadable: variables.

> Error: File to import not found or unreadable: variables.
>     at options.error (C:\SIte\RISKOP_SOCLE_UI\orc-kernel-ui\src\main\ui\node_modules\node-sass\lib\index.js:291:26)



i don't find a solution, you can help me plz plz ?

**Comment by churchs19** [comment]
I'm also seeing the same issue as @vZanchiV here.

> BUILD ERROR
> File to import not found or unreadable: C:\dev\BTS\wm-lib-styles\node_modules\bootstrap\scss\mixins\index.
> Error: File to import not found or unreadable: C:\dev\BTS\wm-lib-styles\node_modules\bootstrap\scss\mixins\index.
>     at options.error (C:\dev\BTS\wm-lib-styles\node_modules\node-sass\lib\index.js:291:26) 

The "options.error" is really frustrating because it doesn't tell me which source file failed either for further debugging.

**Comment by simon-kunz** [comment]
@vZanchiV and @churchs19 
I ran into (almost) the same error.
Adding a `console.log(result)` statement to node_modules\node-sass\lib\index.js pointed me to the SCSS file that caused the problem.
Maybe it helps...

**Comment by TvrtkoM** [comment]
I managed to include my css (not scss, so it could be irrelevant) in library component inside `@Component` angular 9 metadata by simply adding full relative path to file in node_modules in `styleUrls` array. Couldn't figure out how `styleIncludePaths` are supposed to work.

It's file used with `:host` selector used for ShadowDom encapsulation

**Comment by andrasczeh** [comment]
This seems to be an issue with mixins, when not using full names for imports. Replacing them with full names seems to be a good workaround.
ie. 
```scss
@import "~foundation-sites/scss/util/_util.scss"
```
instead of 
```scss
@import "~foundation-sites/scss/util/util"
```

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent ng-packagr version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
