### ISSUE TITLE
[v1] npm run packagr error cant find files under .ng_pkg_build folder

### ISSUE THREAD

**Issue by foote-Greg** [ng-packagr/ng-packagr#464]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

This is the error out put when running npm run packagr:

It is looking for files under a    */.ng_pkg_build/**/ts folder structure + the real relative location of the files...

C:\Projects\FleetApp\shared-modules\gf-data-svcs-library>npm run packagr

> gf-data-svcs-library@0.0.0 packagr C:\Projects\FleetApp\shared-modules\gf-data-svcs-library
> ng-packagr -p ng-package.json

Building Angular library
Generating bundle for gf-data-svcs-library
Cleaning bundle build directory
Processing assets
Running ngc

BUILD ERROR
Error at C:/Projects/FleetApp/shared-modules/gf-data-svcs-library/.ng_pkg_build/gf-data-svcs-library/ts/public_api.ts:1:22: File 'C:/Projects/FleetApp/shared-modules/gf-data-svcs-library/.ng_pkg_build
/gf-data-svcs-library/ts/src/lib/services/data-services.module.ts' not found.
Error at C:/Projects/FleetApp/shared-modules/gf-data-svcs-library/.ng_pkg_build/gf-data-svcs-library/ts/public_api.ts:2:22: File 'C:/Projects/FleetApp/shared-modules/gf-data-svcs-library/.ng_pkg_build
/gf-data-svcs-library/ts/src/lib/services/interfaces/iequipmentinterfaces.ts' not found.
Error: Error at C:/Projects/FleetApp/shared-modules/gf-data-svcs-library/.ng_pkg_build/gf-data-svcs-library/ts/public_api.ts:1:22: File 'C:/Projects/FleetApp/shared-modules/gf-data-svcs-library/.ng_pk
g_build/gf-data-svcs-library/ts/src/lib/services/data-services.module.ts' not found.
Error at C:/Projects/FleetApp/shared-modules/gf-data-svcs-library/.ng_pkg_build/gf-data-svcs-library/ts/public_api.ts:2:22: File 'C:/Projects/FleetApp/shared-modules/gf-data-svcs-library/.ng_pkg_build
/gf-data-svcs-library/ts/src/lib/services/interfaces/iequipmentinterfaces.ts' not found.
    at new UserError (C:\Projects\FleetApp\shared-modules\gf-data-svcs-library\node_modules\@angular\tsc-wrapped\src\tsc.js:27:28)
    at check (C:\Projects\FleetApp\shared-modules\gf-data-svcs-library\node_modules\@angular\tsc-wrapped\src\tsc.js:93:15)
    at Tsc.typeCheck (C:\Projects\FleetApp\shared-modules\gf-data-svcs-library\node_modules\@angular\tsc-wrapped\src\tsc.js:173:9)
    at C:\Projects\FleetApp\shared-modules\gf-data-svcs-library\node_modules\@angular\tsc-wrapped\src\main.js:122:23
    at <anonymous>

npm ERR! code ELIFECYCLE
npm ERR! errno 111
npm ERR! gf-data-svcs-library@0.0.0 packagr: `ng-packagr -p ng-package.json`
npm ERR! Exit status 111
npm ERR!
npm ERR! Failed at the gf-data-svcs-library@0.0.0 packagr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

_for bugs: please describe the error that you encountered_

_for features: please describe your use case_

#### How To Reproduce

_for bugs: please include instructions how to reproduce_

_Can you reproduce the error in the integration tests in ng-packagr?_
_If possible, take a look at the [`integration/samples`](./integration/samples) and try to break one of these builds!_

_Is the error you faced in an application importing the library_
_Try to break the Angular CLI app in [`integration/consumers/ng-cli`](./integration/consumers/ng-cli)!_

#### Expected Behaviour

_for bugs: please describe what behaviour or result you expected_

_for features: do you have a first draft or an idea how to implement?_

#### Version Information

```
ng-packagr:  ng-packagr@1.6.0
@angular/*:  @angular/core@5.1.3
typescript:  2.4.2
rxjs: 5.5.2
node: 8.1.4
npm: 5.5.1
```

_please include any version information that might be relevant, e.g. other third-party libraries_

**Comment by foote-Greg** [comment]
Here is the CLI versions

 "@angular/cli": "1.6.3",
 "@angular/compiler-cli": "^5.0.0",

**Comment by jkyoutsey** [comment]
I even tried hacking the path in ng-package.json with "entryFile": "../../../public_api.ts" and it still cannot find the file, even though it evaluates the path to the root of the project, right where the file is...???

**Comment by jkyoutsey** [comment]
Okay, so I may have found a solution to this...
There may be an encoding/copy-paste issue with the configuration for packagr.
I put this into my package.json and then I DELETED AND RETYPED the "public-api.ts".
```
  "$schema": "./node_modules/ng-packagr/package.schema.json",
  "ngPackage": {
    "lib": {
      "entryFile": "public-api.ts"
    }
  },
```
My build is now working fine.
So, try typing your configuration in package.json from scratch.  See if that doesn't make a difference for you.

**Comment by dherges** [comment]
I see this is a v1 issue and I don't have time to maintain v1. If the issue goes away by migrating to v2, I recommend doing the migration. If not, you can eitjher provide a PR for v1 or customize your build set up (w/o ng-packagr)

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent ng-packagr version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
