### ISSUE TITLE
[v1] Feature Request: Scoped Externals

### ISSUE THREAD

**Issue by elliotleelewis** [ng-packagr/ng-packagr#465]
## Type of Issue

```
[ ] Bug Report
[*] Feature Request
```

## Description

Would be nice if we could have scoped externals, for example, if we had the following set of packages:
- `@example/package-a`
- `@example/package-b`
- `@example/package-c`

And we wanted all packages that are scoped under `@example` to be added to the externals array, then we would just have to set the config to:

```
{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "lib": {
    "entryFile": "./index.ts",
    "externals": {
      "@example/*": "example.*"
    }
  }
}
```

That way if we add another package from `@example`, then we wouldn't have to add it to the externals every time.

**Comment by dherges** [comment]
Hi @elliotleelewis,

thanks for reporting. Such a change will be for v1 and Angular 4. In v2, `lib.externals` is going to be dropped.

**Comment by elliotleelewis** [comment]
Legacy feature request, no longer relevant since V2.
