### ISSUE TITLE
package.json browser entry point for dependencies

### ISSUE THREAD

**Issue by rawsonm88** [ng-packagr/ng-packagr#469]
## Type of Issue
When the target library has dependencies which uses the "browser" field in package.json to denote a different entry-point for browser this is ignored by ng-packagr.

```
[ x ] Bug Report
[ x ] Feature Request
```

## Description

For example I created a library which used the firebase SDK, the "main" entry point makes use of the XMLHttpRequest library which relies on child_process which isn't supported in the browser.

There were no errors raised upon compilation but when the new package was included and used in a new app errors like 'Module not found: Error: Can't resolve 'child_process'' appeared.

#### How To Reproduce

1. Include firebase from npm or another npm package which has a seperate "browser" entry point in package.json
2. Compile to a package with ng-packagr
3. Include in another Angular app and run `ng build`

##### Potential fix

By setting the modulesOnly and browser variables to true in the object passed to nodeResolve on line 88 in 
https://github.com/dherges/ng-packagr/blob/62ae73c67fe6bf8e26ed737e5a7935fbed94d3b4/src/lib/steps/rollup.ts I was able to resolve the issue.

I won't raise a PR because I'm not familiar enough with the NPM/node/AngularJS to understand all of the use cases for this tool and don't want to present something which stops it working for anyone else.

#### Expected Behaviour

ng-packagr should use the "browser" entrypoint from package.json

#### Version Information

```
ng-packagr: 1.6.0
@angular/*: 5.0.0
typescript: 2.4.2
rxjs: x.y.z
node: 8.6.0
npm: 5.3.0
```

firebase: 4.8.0

**Comment by dherges** [comment]
Hi @rawsonm88,

I'm neither an expert regarding rollup. There've been too much module formats in JavaScript land... I'm afraid I do not have a use case in what I am doing and will not be able to focus on it. However...

I'd guess it's going to be non-breaking to enable `browser: true`. The rollup docs for `modulesOnly` say:

```ts
      // If true, inspect resolved files to check that they are
      // ES2015 modules
      modulesOnly: true, // Default: false
```

...suggesting that it's going to break for legacy JavaScript (commonjs, maybe even global-scoped third-party code).

When you or someone else comes up with a PR, including an integration test in `integration/samples`, we can discuss this further.

**Comment by jdbranham** [comment]
I think I have it. But not sure how to create a 'good' test.

**Comment by dherges** [comment]
What I was trying to say: setting `browser: true` by default looks safe. Setting `modulesOnly: true` by default looks like a breaking change.
