### ISSUE TITLE
Allow umdModuleIds to accept a function

### ISSUE THREAD

**Issue by geoff-mci** [ng-packagr/ng-packagr#476]
## Type of Issue

```
[ ] Bug Report
[X] Feature Request
```

## Description

It would be nice if the umdModuleIds option could take a function OR the existing array type (ala rollup).
This would help my scenario where I have a number of scoped modules with a consistent naming convention...instead of having to list all the inter-module dependencies, I can use a string replacement function on the moduleName.  Also, it would help when we want to adjust rules for matching angular and/or rxjs ids. 

#### Expected Behaviour

See rollupjs globals

#### Version Information

```
ng-packagr: 2.0.0-rc.9
@angular/*: 5
typescript: 2.4
```

**Comment by alan-agius4** [comment]
Out of scope as UMDs are deprecated
