### ISSUE TITLE
Problems with routerLink in exported components

### ISSUE THREAD

**Issue by vapits** [ng-packagr/ng-packagr#478]
## Type of Issue
When I'm trying to use my created library with an application I get errors for example for routerLink.

```
[x] Bug Report
[ ] Feature Request
```

## Description & How to reproduce
I have a very simple component in my library that looks like:
HTML:
```html
<div class="footer-container">
    <div class="wrapper">
        <div class="content">
            <div class="link" *ngFor="let link of links">
                <a [routerLink]="link.path" routerLinkActive="active">{{link.title}}</a>
            </div>
        </div>
        <div class="logo"></div>
    </div>
</div>
```
TS Component:
```js
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'lex-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss']
})
export class FooterComponent {

  @Input() links;
  constructor() { }
}
```
TS Module:
```js
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FooterComponent } from './footer.component';

@NgModule({
    imports: [
        CommonModule
    ],
    declarations: [
        FooterComponent
    ],
    exports: [
        FooterComponent
    ]
})
export class LexFooterModule { }
```
Then in my application I import this module in my `imports` like: `import {LexFooterModule} from '@myLib/lex-ng';`.

I don't get any errors on the import and I already importing RouterModule in my app (I'm using routerLink in a lot of places but I get the follwoing errors:
>Uncaught Error: Template parse errors:
Can't bind to 'routerLink' since it isn't a known property of 'a'. ("ass="content">
                <div class="link" *ngFor="let link of links">
                    <a [ERROR ->][routerLink]="link.path" routerLinkActive="active">{{link.title}}</a>
                </div>
        "): ng:///LexFooterModule/FooterComponent.html@5:23

#### Expected Behaviour

My library components that are working with angular options like `routerLink` in the Library docs correctly should work the same when I import them into another app.

#### Version Information

```
ng-packagr: 1.6.0 (update, now  I am at 2.0.0-rc.9, still same issue)
@angular/*: 5.0.2 (I tried also with 5.1.2)
typescript: 2.6.2
rxjs: 5.5.2
node: 6.11.1 (tried also with LTS)
npm: 5.2.0
```

**Comment by vapits** [comment]
If I import . RouterModule in my exportable module then in the app that I'm using the component/module I get this error:

![image](https://user-images.githubusercontent.com/8594758/35279700-111051fa-004e-11e8-9245-d2b47740ffa4.png)

Does anyone have ANY idea? We have similar issues with the rest of the components.

**Comment by vapits** [comment]
@dherges any ideas on this one?

**Comment by dherges** [comment]
Can you give access to a repro, e.g. on GitHub?

**Comment by deebloo** [comment]
@vapits yes you will definitely have to import the router module if you plan on using it in your packaged module. as far as the injector error can you do a @dherges suggests and provide us with a minimal repo that reproduces this error?

**Comment by vapits** [comment]
@deebloo I'm doing this but If I import ANY module or functionality  from Angular I get the message above. I will try to reproduce it with two projects but it's quite straight forward IMO. any library that I have created . if you even use a simple ngIf in the library the the app that it's using it gets the error above.

**Comment by alan-agius4** [comment]
Closing as no reproduction provided.
