### ISSUE TITLE
Problem building TS code with JSDoc comments

### ISSUE THREAD

**Issue by matheo** [ng-packagr/ng-packagr#485]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I'm trying to compile a code with JSDoc block comments, and I'm getting errors because the ngc transpiled code produces a faulty output:

Typescript:
```
  /**
   * Parses a date from a value.
   * @param value The value to parse.
   * @param parseFormat The expected format of the value being parsed
   *     (type is implementation-dependent).
   * @returns The parsed date.
   */
  abstract parse(value: any, parseFormat: any): D | null;
```

Transpiled:
```
    /**
     * Parses a date from a value.
     * @abstract
     * @param {?} value The value to parse.
     * @param {?} parseFormat The expected format of the value being parsed
     *     (type is implementation-dependent).
     * @return {?}
     */
    DateAdapter.prototype.parse = function (value, parseFormat) { };
```

Error:
```
Compiling with ngc

BUILD ERROR
.../date-adapter.ts(274,3): warning TS0:
the type annotation on @return is redundant with its TypeScript type, remove the {...} part
```

#### Expected Behaviour

Be able to build my lib successfully. Any config I can move?

#### Version Information

```
ng-packagr: 2.0.0-rc.10
@angular/*: ~5.1.1
typescript: ~2.6.1
rxjs: ^5.5.6
node: v6.11.5
yarn: v1.3.2
```

**Comment by matheo** [comment]
The available workaround is to disable the warnings it seems:
https://github.com/dherges/ng-packagr/issues/311#issuecomment-351449412

**Comment by madoar** [comment]
I have the same problem in a project of mine.

**Comment by NiKlimenko** [comment]
Have the same problem too, @dherges would be great if you can comment on it.

**Comment by 82antu** [comment]
Same problem here,
Appreciate the help

**Comment by dherges** [comment]
Hi all,

the error is being reported from tsickle. It tells you too not include type information is in the jsdoc comment, as it is redundant information to typescript.

It looks like the error should not have been thrown, because the annotation `@returns Prose description text` doesn't include a type paaram (`@returns {boolean} Prose description text`). If that is the error, the best is to  reproduce it w/o ng-packagr and file an issue against [tsickle](https://github.com/angular/tsickle)

**Comment by NiKlimenko** [comment]
@dherges thank you for the information, how about to disable tsickle checks through the configuration settings?

**Comment by das974** [comment]
I updated the rollup plugin dep in the package.lock file manually. Luckily I created a test project last night and was able to diff.
 
1. Removed rollup-plugin-commonjs and replaced with:

    "rollup-plugin-commonjs": {
      "version": "8.3.0",
      "resolved": "https://registry.npmjs.org/rollup-plugin-commonjs/-/rollup-plugin-commonjs-8.3.0.tgz",
      "integrity": "sha512-PYs3OiYgENFYEmI3vOEm5nrp3eY90YZqd5vGmQqeXmhJsAWFIrFdROCvOasqJ1HgeTvqyYo9IGXnFDyoboNcgQ==",
      "dev": true,
      "requires": {
        "acorn": "5.5.0",
        "estree-walker": "0.5.1",
        "magic-string": "0.22.4",
        "resolve": "1.5.0",
        "rollup-pluginutils": "2.0.1"
      },
      "dependencies": {
        "estree-walker": {
          "version": "0.5.1",
          "resolved": "https://registry.npmjs.org/estree-walker/-/estree-walker-0.5.1.tgz",
          "integrity": "sha512-7HgCgz1axW7w5aOvgOQkoR1RMBkllygJrssU3BvymKQ95lxXYv6Pon17fBRDm9qhkvXZGijOULoSF9ShOk/ZLg==",
          "dev": true
        }
      }
    },

2. Update the ng-packagr dependency and replace with 
 "rollup-plugin-commonjs": "8.3.0"
3. Run NPM Install

**Comment by rhalff** [comment]
Can confirm that the suggestion from https://github.com/dherges/ng-packagr/issues/311#issuecomment-351449412 does make the code compile.

Btw, that portion of the code has been moved to: https://github.com/dherges/ng-packagr/blob/master/src/lib/ngc/create-emit-callback.ts#L47

When I do a custom build using ng-packagr's api, I can also succesfully compile:

build.ts:
```typescript
import { ngPackagr } from 'ng-packagr';
import { readConfiguration } from '@angular/compiler-cli';
import * as path from 'path';

const projectDir = './src/lib'; // << dir of my project in this case.

const project = path.join(
  __dirname,
  projectDir,
  'ng-package.json'
);

const config = readConfiguration(
  path.join(
    __dirname,
    projectDir,
    'tsconfig.ngc.json'
  )
);

ngPackagr()
  .forProject(project)
  .withTsConfig(config)
  .build()
  .catch(error => {
    console.error(error);
    process.exit(1);
  });
```

tsconfig.ngc.json:
```typescript
{
  "extends": "../../node_modules/ng-packagr/lib/ts/conf/tsconfig.ngc.json",
  "angularCompilerOptions": {
    "annotateForClosureCompiler": false
  }
}
```
You probably don't want to set this to false permanently, but at least the lib gets build.

I have seen no way to just modify the config file itself, hence this custom script.

**Comment by ersimont** [comment]
@rhalff Thank you for pointing out the new path to use for this hack as a workaround for now.

**Comment by panchalkalpesh** [comment]
@rhalff Thanks a tonn for sharing this workout. 
This also fixes a **BUILD ERROR** if we try to import `.json` files after enabling/setting `resolveJsonModule: true` in tsconfig.json
