### ISSUE TITLE
How long does it take to build a package?

### ISSUE THREAD

**Issue by kambbado** [ng-packagr/ng-packagr#491]
I'm sorry if this is the wrong place to ask this question.

i'm trying to package a library and it's taking a long time for ng-packagr to complete.

```
 .\node_modules\.bin\ng-packagr.cmd -p .\src\package.json
Building Angular library
Generating bundle for @ramp/library
Cleaning bundle build directory
Processing assets
Running ngc
Compiling to FESM15
'ErrorHandler' is imported from external module '@angular/core' but never used
'HttpResponse', 'HttpXhrBackend' and 'HttpErrorResponse' are imported from external module '@angular/common/http' but never used
'keyframes' and 'group' are imported from external module '@angular/animations' but never used
```

it just sit there, Nod.js is running and consuming system resources, is there a way to debug and see where it's hanging?

Thank you

**Comment by dherges** [comment]
`DEBUG=true node_modules/.bin/ng-packagr -p <path/to/package.json>`

**Comment by kambbado** [comment]
Here's the results

> PS D:\temp\mylibrary> [Environment]::SetEnvironmentVariable("DEBUG", "true")
> PS D:\temp\mylibrary> node_modules/.bin/ng-packagr -p .\package.json
> Building Angular library
> [debug] Searching for ng-package config at D:\temp\mylibrary\package.json
> [debug] Ng-package config found at D:\temp\mylibrary\package.json
> [debug] Searching for ng-package config at D:\temp\mylibrary\ng-package.json
> [debug] Ng-package config found at D:\temp\mylibrary\ng-package.json
> [debug] loading package.json
> [debug] Beginning package search from root D:\temp\mylibrary
> [debug] Resolved secondary package paths:
> [debug] rimraf D:\temp\mylibrary\dist
> Generating bundle for @mylibrary/mylibrary-angular-library
> Cleaning bundle build directory
> [debug] rimraf D:\temp\mylibrary\.ng_pkg_build\@mylibrary-mylibrary-angular-library
> Processing assets
> [debug] processAssets D:\temp\mylibrary to D:\temp\mylibrary\.ng_pkg_build\@mylibrary-mylibrary-angular-library/ts
> [debug] render stylesheet D:\temp\mylibrary\src\error\error.component.scss
> [debug] rendering sass for D:\temp\mylibrary\src\error\error.component.scss
> [debug] postcss with autoprefixer for D:\temp\mylibrary\src\error\error.component.scss
> [debug] render stylesheet D:\temp\mylibrary\src\login\login-reset.component.scss
> [debug] rendering sass for D:\temp\mylibrary\src\login\login-reset.component.scss
> [debug] postcss with autoprefixer for D:\temp\mylibrary\src\login\login-reset.component.scss
> [debug] render stylesheet D:\temp\mylibrary\src\login\login.component.scss
> [debug] rendering sass for D:\temp\mylibrary\src\login\login.component.scss
> [debug] postcss with autoprefixer for D:\temp\mylibrary\src\login\login.component.scss
> [debug] render stylesheet D:\temp\mylibrary\src\shared\currency\currency.component.scss
> [debug] rendering sass for D:\temp\mylibrary\src\shared\currency\currency.component.scss
> [debug] postcss with autoprefixer for D:\temp\mylibrary\src\shared\currency\currency.component.scss
> [debug] render stylesheet D:\temp\mylibrary\src\shared\notifications\notification.component.scss
> [debug] rendering sass for D:\temp\mylibrary\src\shared\notifications\notification.component.scss
> [debug] postcss with autoprefixer for D:\temp\mylibrary\src\shared\notifications\notification.component.scss
> Running ngc
> [debug] ngc D:\temp\mylibrary\.ng_pkg_build\@mylibrary-mylibrary-angular-library/ts/tsconfig.lib.json, { basePath: D:\temp\mylibrary\.ng_pkg_build\@mylibrary-mylibrary-angular-library/ts })
> [debug] prepareTsConfig: Resolved tsconfig path to D:\temp\mylibrary\node_modules\ng-packagr\lib\conf\tsconfig.ngc.json
> [debug] Reading tsconfig from D:\temp\mylibrary\.ng_pkg_build\@mylibrary-mylibrary-angular-library/ts/tsconfig.lib.json
> [debug] re-mapping sources for D:\temp\mylibrary\.ng_pkg_build\@mylibrary-mylibrary-angular-library/ts/mylibrary-angular-library.js
> Compiling to FESM15
> [debug] rollup D:\temp\mylibrary\.ng_pkg_build\@mylibrary-mylibrary-angular-library/ts//mylibrary-angular-library.js to D:\temp\mylibrary\.ng_pkg_build\@mylibrary-mylibrary-angular-library\@mylibrary\mylibrary-angular-library.js (es)
> 'ErrorHandler' is imported from external module '@angular/core' but never used
> [debug] re-mapping sources for D:\temp\mylibrary\.ng_pkg_build\@mylibrary-mylibrary-angular-library\@mylibrary\mylibrary-angular-library.js
> 

At stops at the re-mapping

**Comment by dherges** [comment]
What is your version? v1?

Can you confirm this is a windows path issue?

```
D:\temp\mylibrary.ng_pkg_build@mylibrary-mylibrary-angular-library@mylibrary\
```

**Comment by kambbado** [comment]
I have spent some time trying to debug and figuring out how it works.  Here's what I have found.

In regards to the path, I suggest that use path to join paths and filenames to resolve the windows/linux environments

example for the **bundler.js** file
 
```
....
const path = require('path');
....
const baseBuildPath = path.join(ngPkg.buildDirectory, 'ts', ngPkg.pathOffsetFromSourceRoot);
....
yield sorcery_1.remapSourceMap(path.join(baseBuildPath, `${ngPkg.flatModuleFileName}.js`));
```
Hanging process

I have identified to subsequent calls to **remapSourceMap** , the first call succeeds however, the rest fail.

Hangs of this call, if I comment this it will hang on the next

`yield sorcery_1.remapSourceMap(artifactPaths.es2015);`

if I comment all **remapSourceMap** except the first it completes.

I changed my library name, I removed **_@mylibrary_**, here is the output


> PS D:\temp\mylibrary> node_modules/.bin/ng-packagr -p .\package.json
> Building Angular library
> [debug] Searching for ng-package config at D:\temp\mylibrary\package.json
> [debug] Ng-package config found at D:\temp\mylibrary\package.json
> [debug] Searching for ng-package config at D:\temp\mylibrary\ng-package.json
> [debug] Ng-package config found at D:\temp\mylibrary\ng-package.json
> [debug] loading package.json
> [debug] Beginning package search from root D:\temp\mylibrary
> [debug] Resolved secondary package paths:
> [debug] rimraf D:\temp\mylibrary\dist
> Generating bundle for mylibrary-angular-library
> Cleaning bundle build directory
> [debug] rimraf D:\temp\mylibrary\.ng_pkg_build\mylibrary-angular-library
> Processing assets
> [debug] processAssets D:\temp\mylibrary to D:\temp\mylibrary\.ng_pkg_build\mylibrary-angular-library\ts
> [debug] render stylesheet D:\temp\mylibrary\src\error\error.component.scss
> [debug] rendering sass for D:\temp\mylibrary\src\error\error.component.scss
> [debug] postcss with autoprefixer for D:\temp\mylibrary\src\error\error.component.scss
> [debug] render stylesheet D:\temp\mylibrary\src\login\login-reset.component.scss
> [debug] rendering sass for D:\temp\mylibrary\src\login\login-reset.component.scss
> [debug] postcss with autoprefixer for D:\temp\mylibrary\src\login\login-reset.component.scss
> [debug] render stylesheet D:\temp\mylibrary\src\login\login.component.scss
> [debug] rendering sass for D:\temp\mylibrary\src\login\login.component.scss
> [debug] postcss with autoprefixer for D:\temp\mylibrary\src\login\login.component.scss
> [debug] render stylesheet D:\temp\mylibrary\src\shared\currency\currency.component.scss
> [debug] rendering sass for D:\temp\mylibrary\src\shared\currency\currency.component.scss
> [debug] postcss with autoprefixer for D:\temp\mylibrary\src\shared\currency\currency.component.scss
> [debug] render stylesheet D:\temp\mylibrary\src\shared\notifications\notification.component.scss
> [debug] rendering sass for D:\temp\mylibrary\src\shared\notifications\notification.component.scss
> [debug] postcss with autoprefixer for D:\temp\mylibrary\src\shared\notifications\notification.component.scss
> Running ngc
> [debug] ngc D:\temp\mylibrary\.ng_pkg_build\mylibrary-angular-library\ts/tsconfig.lib.json, { basePath: D:\temp\mylibrary\.ng_pkg_build\mylibrary-angular-library\ts })
> [debug] prepareTsConfig: Resolved tsconfig path to D:\temp\mylibrary\node_modules\ng-packagr\lib\conf\tsconfig.ngc.json
> [debug] Reading tsconfig from D:\temp\mylibrary\.ng_pkg_build\mylibrary-angular-library\ts/tsconfig.lib.json
> [debug] re-mapping sources for D:\temp\mylibrary\.ng_pkg_build\mylibrary-angular-library\ts\mylibrary-angular-library.js
> ******** about to write chain
> Compiling to FESM15
> [debug] rollup D:\temp\mylibrary\.ng_pkg_build\mylibrary-angular-library\ts//mylibrary-angular-library.js to D:\temp\mylibrary\.ng_pkg_build\mylibrary-angular-library\mylibrary-angular-library.js (es)
> 'ErrorHandler' is imported from external module '@angular/core' but never used
> Compiling to FESM5
> [debug] tsc D:\temp\mylibrary\.ng_pkg_build\mylibrary-angular-library\mylibrary-angular-library.js to D:\temp\mylibrary\.ng_pkg_build\mylibrary-angular-library\mylibrary-angular-library.es5.js
> Compiling to UMD
> [debug] rollup D:\temp\mylibrary\.ng_pkg_build\mylibrary-angular-library\mylibrary-angular-library.es5.js to D:\temp\mylibrary\.ng_pkg_build\mylibrary-angular-library\bundles\mylibrary-angular-library.umd.js (umd)
> Minifying UMD bundle
> [debug] minifyJsFile: D:\temp\mylibrary\.ng_pkg_build\mylibrary-angular-library\bundles\mylibrary-angular-library.umd.js
> Side effects in initialization of unused variable data [0:1975,37]
> Side effects in initialization of unused variable data [0:1993,37]
> Dropping unreachable code [0:7070,12]
> Declarations in unreachable code! [0:7070,12]
> Dropping unreachable code [0:8015,12]
> Declarations in unreachable code! [0:8015,12]
> Side effects in initialization of unused variable data [0:11042,33]
> Side effects in initialization of unused variable ComponentMessages [0:2847,4]
> Side effects in initialization of unused variable L10N_PREFIX [0:2870,4]
> Remapping source maps
> [debug] modifyJsonFiles
> Copying staged files
> [debug] copyFiles from D:\temp\mylibrary\.ng_pkg_build\mylibrary-angular-library/mylibrary-angular-library*.{js,js.map} to D:\temp\mylibrary\dist
> [debug] copyFiles from D:\temp\mylibrary\.ng_pkg_build\mylibrary-angular-library/bundles/**/*.{js,js.map} to D:\temp\mylibrary\dist/bundles
> [debug] copyFiles from D:\temp\mylibrary\.ng_pkg_build\mylibrary-angular-library\ts/**/*.{d.ts,metadata.json} to D:\temp\mylibrary\dist
> Writing package metadata
> [debug] writePackage
> Built Angular bundle for mylibrary-angular-library
> [debug] copyFiles from D:\temp\mylibrary/README.md to D:\temp\mylibrary\dist
> [debug] copyFiles from D:\temp\mylibrary/LICENSE to D:\temp\mylibrary\dist
> Built Angular library from D:\temp\mylibrary, written to D:\temp\mylibrary\dist
> [debug] rimraf D:\temp\mylibrary\.ng_pkg_build\
> 

Please let me know if you want me to try something new or different.
