### ISSUE TITLE
[v1] "gulp-util@3.0.8: gulp-util is deprecated - replace it,"

### ISSUE THREAD

**Issue by kylecordes** [ng-packagr/ng-packagr#511]
## Type of Issue

Bug Report

## Description

```
warning ng-packagr > gulp-inline-ng2-template > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
```

#### How To Reproduce

```
yarn
```

(maybe also `npm`)

#### Expected Behaviour

Upgrade dependencies so that no transitive dependencies are deprecated or otherwise problematic.

#### Version Information

```
ng-packagr: 1.6.0
```

Yarn 1.3.2, though I don't think it matters.

**Comment by dherges** [comment]
Hi @kylecordes,

it's a v1 issue that will go away in v2.

I am going to not actively maintain v1.

**Comment by kylecordes** [comment]
@dherges I've been staying away from v2 for "real work", perhaps now is the time to go that direction even though it is still marked RC.  At the moment I don't see any way to find open issues etc. to understand what is still in the way of making v2 the released version, Hopefully because such a list is so short as to barely exist. :-)

**Comment by dherges** [comment]
It's #443

**Comment by dherges** [comment]
In specific, [include additional typings in compilation, write such typings to distributables](https://github.com/dherges/ng-packagr/pull/443#pullrequestreview-91661105)
