### ISSUE TITLE
Create UI Library

### ISSUE THREAD

**Issue by rkusuma** [ng-packagr/ng-packagr#515]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

Tutorial how to create UI library like `ngx-bootstrap` or `@angular/material` and tree shakable.
For instance i have to 2 module: `ToasterModule` and `SpinnerModule`. I want my library can import those module in 2 ways:
```
import { ToasterModule, SpinnerModule } from '@mylib/ui`
```
or
```
import { ToasterModule } from '@mylib/ui/toaster'
```
For 2nd example, build bundles for my angular application that consume my lib should exclude `SpinnerModule` because i'm not imported it.

#### Version Information

```
ng-packagr: 2.0.0-rc11
@angular/*: 5.2.0
typescript: 2.5.x
rxjs: 5.5.6
node: 8.9.2
yarn: 1.3.2
```

**Comment by deebloo** [comment]
@rkusuma take a look at the "Secondary entry points" section of the Readme. https://github.com/dherges/ng-packagr#secondary-entry-points
