### ISSUE TITLE
UnhandledPromiseRejectionWarning on ng-packagr@2.0.0-rc.13

### ISSUE THREAD

**Issue by NeoLSN** [ng-packagr/ng-packagr#589]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description

1st
```
(node:54348) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '.ng_build/<library_name>/out/node_modules/license-webpack-plugin/dist/FileUtils.d.ts'
```
2nd
```
(node:48908) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, chmod '.ng_build/<library_name>/out/node_modules/ionic-angular/util/debouncer.d.ts'
```
3rd
```
(node:48800) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '.ng_build/<library_name>/out/node_modules/rxjs/operator/findIndex.d.ts'
```
Other logs
```
(node:54348) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:54348) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with anon-zero exit code.
```

#### How To Reproduce

After my library update `ng-packagr` to version `2.0.0-rc.13`, it always be built failed.
Those error won't be the same everytime.
Downgrade to `2.0.0-rc.12` is fine.

#### Expected Behaviour

Can build my app

#### Version Information

```
ng-packagr: 2.0.0-rc.13
@angular/*: 5.0.3
typescript: 2.4.2
rxjs: 5.5.2
node: 9.4.0
npm/yarn: 5.6.0
```

_please include any version information that might be relevant, e.g. other third-party libraries_

**Comment by lacolaco** [comment]
I'm in the same situation after upgrading from 2.0.0 beta.9 to 2.0.0.

**Comment by bnymncoskuner** [comment]
Same problem here with 2.0.0 as well.

**Comment by nedzvedz** [comment]
It seems that the error occurs when rimraf is removing build output from `.ng_pkg_build` folder.

**Comment by iamthechad** [comment]
I don't get the error once I move `public_api.ts` into the `src` directory. I'm not sure why the location matters, but it works for me.

**Comment by dherges** [comment]
Please provide a repro, best in a github source code repo.

**Comment by iamthechad** [comment]
This repo shows the issue for me: https://github.com/iamthechad/sample-module-packagr

**Comment by syerrawa** [comment]
I have the same issue too. It worked if i changed the version of ng-packagr to 1.6.0
But with the latest version it fails and gives a different error each time.

**Comment by vlad-p** [comment]
@iamthechad  I moved `public_api.ts` to `src` directory as well and the error is gone. Very strange.

**Comment by lishichao1002** [comment]
same question with 2.2.0

```
> ng-packagr -p package.json

Building Angular Package
Building entry point '@angular/router'
Cleaning build directory
Rendering Stylesheets
Rendering Templates
Compiling TypeScript sources through ngc
Bundling to FESM15
'QueryList' is imported from external module '@angular/core' but never used
Bundling to FESM5
Bundling to UMD
Minifying UMD bundle
Dropping unreachable code [0:753,20]
Declarations in unreachable code! [0:753,20]
Dropping duplicated definition of variable Me [0:1074,20]
Relocating source maps
Copying staged files
Writing package metadata
Built @angular/router
Built Angular Package!
- from: D:\workspaces\test\angular-router-mock
- to:   D:\workspaces\test\angular-router-mock\dist
(node:20868) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open 'D:\workspaces\test\angular-router-mock\.ng_pkg_build\angular-router\out\node_modules\reflect-metadata\standalone.d
.ts'
(node:20868) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ghiscoding** [comment]
I also get some of these errors, with version `2.2.0`, but it still finishes the build and my package still end up working, so I didn't care much. 

However I tried the quick fix mentioned in the comments by moving the `public_api.ts` file into the `./src` folder and I get other kind of errors and the build just stops. So it doesn't look like this quick fix is good for all, am I the only one with that supposedly fix that doesn't work?

**Comment by NeoLSN** [comment]
@ghiscoding Did you modify your the `entryFile` path in `ng-packagr.json` after you move the `index.js`?

**Comment by ghiscoding** [comment]
@NeoLSN  Yes I did

**Comment by cdutta** [comment]
I am getting an issue which says a file is not under 'is not under 'rootDir'' . After moving the public_api.ts to src folder that has app.

**Comment by cdutta** [comment]
@NeoLSN yes .. I did .. I think I am getting the issues because of ts files in node_modules. So I think this weird solution should work for me.

**Comment by ghiscoding** [comment]
@NeoLSN and others if you still have the issues.

I give another shot at moving again the `public_api.ts` into the `src/` folder and it now works. The reason of why it wasn't working before is quite silly from my side, I had forgot to update the pointer of the `export` within the `public_api.ts` since the folder structure changed. 

Just to resume the steps, I did the following:
1. move the `public_api.ts` into `src/` folder
2. update the `entryFile` in `ng-package.json` like so
    - `"entryFile": "src/public_api.ts"`
3. update your exports inside the `public_api.ts`

Also note that after doing this changes, not only did it fixed the errors, the build runs **much faster** than before.

**Comment by noelmace** [comment]
@ghiscoding I tried exactly the same workaroung, and I still get this error :

```
Building entry point 'foo'
Cleaning build directory
Rendering Stylesheets
Rendering Templates
Compiling TypeScript sources through ngc
Bundling to FESM15

BUILD ERROR
ENOENT: no such file or directory, open '[foo-path]\libs\core\.ng_pkg_build\foo-core\out\alert\alert.component.ts'
Error: ENOENT: no such file or directory, open '[foo-path]libs\core\.ng_pkg_build\foo-core\out\alert\alert.component.ts'
```
but I get this error using the programatic API, not with the CLI.

I followed https://github.com/dherges/ng-packagr/issues/256#issuecomment-360601173 (see https://github.com/dherges/ng-packagr/blob/master/src/lib/ng-v5/packagr.ts) in order to permit to use a custom tsconfig file in [packagr-for-nx](https://github.com/noelmace/packagr-for-nx)

**Comment by allenhwkim** [comment]
The location of entry file and dest matters.
I was having the error with this setup
```
  "ngPackage": {
    "lib": {
      "entryFile": "index.ts"
    },
    "deleteDestPath": true,
    "dest": "modules/dist"
  },
```
but it disappears with the following setup.
```
  "ngPackage": {
    "lib": {
      "entryFile": "modules/index.ts"
    },
    "deleteDestPath": true,
    "dest": "modules/dist"
  },
```

**Comment by niccolascosta** [comment]
The solution that works for me is to put the file package.json in the same folder as public_api.ts

`"ngPackage": {
    "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
    "workingDirectory": "../.ng_build",
    "lib": {
      "entryFile": "public_api.ts"
    },
    "dest": "../dist/lib"
  }`

**Comment by noelmace** [comment]
I encoutered this issue twice, both using the programmatic API : 
* when trying to use the programmatic API in noelmace/packagr-for-nx (https://github.com/noelmace/packagr-for-nx/commit/6512e29a1d5c6aa314fca5995b95c20a4c3e622a)
* when adding a withTsConfig in the ng-packagr architect (https://github.com/angular/devkit/pull/750/commits/ee2e2ace8892e93204eb92b6c5d849fb4e844121)

I think #786 (see [this line](https://github.com/dherges/ng-packagr/pull/786/files#diff-00ca38ddf855188086af3b546fb855cfR74)) could solve this.

In the mean time, you can test this in your project by using a custom tsconfig looking like this one : 
https://github.com/angular/devkit/pull/750/files#diff-fce66255aa6a3ef162bcacc08960d5fcR1

In fact, you'll need at least this if you are facing the same issue than me : 
```
    "sourceMap": true,
    "inlineSources": true,
```

**Comment by BamiGorengo** [comment]
Any updates here? Got still the same bug with latest version.

**Comment by ghiscoding** [comment]
@BamiGorengo 
Well the question would be... what have you tried so far? 
There's a lot of info in this thread for you to try

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent ng-packagr version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
