### ISSUE TITLE
[v1] TestBed error: ENOENT: no such file or directory,...   ...\node_modules\packages\core\esm5\testing\src\async.js.map

### ISSUE THREAD

**Issue by deKaantje** [ng-packagr/ng-packagr#590]
## Type of Issue

```
[X ] Bug Report
[ ] Feature Request
```

## Description
I'm trying to package a small component thats using Angular's **TestBed**. When it reaches the **Compiling to FESM15** step, it throws an error:
```
BUILD ERROR
ENOENT: no such file or directory, open 'd:\path\to\project\node_modules\packages\core\esm5\testing\src\async.js.map'
Error: ENOENT: no such file or directory, open 'd:\path\to\project\node_modules\packages\core\esm5\testing\src\async.js.map'
    at Error (native)
```

I've narrowed the problem down to the configuration and usage of the TestBed. When I comment out the TestBed, my component compiles just fine. When I use it, I get the error.

If you closely examine the path, you will find it is trying to find the **async.js.map** in **\packages\core\esm5\testing\src**. 

2 strange things: 
1. it does not search the **@angular** folder, but it tries to search for the file in the **packages** folder
2. The actual **async.js.map** resides in the **\@angular\core\testing\src** folder. So it puts the **esm5** in between the **core** and **testing** part of the path  for some reason.

#### How To Reproduce
1. Create a folder **my-testing** within **src/app/**
2. Add a **my-testing.ts** to folder
3. Enter code in this file:

```javascript
import { TestBed, ComponentFixture } from '@angular/core/testing';

import { Component } from '@angular/core';

@Component({
    selector: 'app-test-component',
    template: '<div></div>'
})
export class TestComponent {
}

export class PrivaComponentTester {

    private fixture: ComponentFixture<TestComponent>;
    public element: any;

    public initialize(init: any) {
        TestBed.configureTestingModule(init);
    }
}
```

4. setup ng-package.json:

```json
{
    "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
    "src": "src/app/my-testing",
    "dest": "package/lib",
    "lib": {
        "entryFile": "my-testing.ts",
        "flatModuleFile": "my-testing"
    }
}
```

5. run ```ng-packagr -p ng-package.json```

#### Expected Behaviour
I expect it to build my package without errors ;-)

#### Version Information

```
ng-packagr: 1.7.0
@angular/*: 5.0.3
typescript: 2.4.2
rxjs: 5.5.2
node: 6.9.5
npm: 5.6.0

Specific for TestBed: 
@angular/core: 5.0.3


Thanks in advance!!

**Comment by deKaantje** [comment]
I would love to know the status of this issue. Did anyone reproduce it and / or can explain this happening?

I'm currently stuck. It would be great if someone could help me further.

Thanks!

**Comment by dherges** [comment]
Hi @deKaantje,

you wrote that you use v1. Can you confirm whether the issue persists in v2?

If it's in v2, you could eihter migrate to v2 or submit a PR for v1 or customize your build w/o ng-packagr. I will not have time to maintain v1.

**Comment by dherges** [comment]
In v1, there is a hard-coded list of "default externals". Is `@angular/core/testing` missing in that list?

**Comment by deKaantje** [comment]
@dherges  
Thank you for the response! I will look into that and let you know of any progress / findings.

**Comment by SerkanSipahi** [comment]
@dherges any updates?

**Comment by alan-agius4** [comment]
Closing as should be solved. Please file a new issue if the problem persists.
