### ISSUE TITLE
npm link: The built library contains a node_module directory with tslib installed in

### ISSUE THREAD

**Issue by sbourouis** [ng-packagr/ng-packagr#596]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

After building the library with ng-packagr 2.0.0, the package.json contains a tslib dependency and it is installed in a node_modules directory.

```
dist
└── lib
    ├── bundles
    ├── core
    ├── esm5
    ├── esm2015
    ├── node_modules
    |   └── tslib
    ├── package.json
    └──  ...
```

#### How To Reproduce

Just build a lib.

#### Expected Behaviour

My package.json shouldn't have tslib dependency as I haven't added it myself.  

#### Version Information

```
ng-packagr: 2.0.0
@angular/*: 5.2.1
typescript: 2.5.3
rxjs: 5.5.6
node: 8.1.4
npm: 5.6.0
```

**Comment by iamthechad** [comment]
I'm having a similar issue after installing 2.0.0. My `node_modules` contains `array-flatten`, `camel-case`, and `codelyzer` - none of which are direct dependencies. (`codelyzer` is a dev dependency)

**Comment by dherges** [comment]
Hi @sbourouis,

in the version 2, the way of bundling the esm5 and esm2015 is changed and `tslib` is added intentionally to the `dependencies` section of `dist/lib/package.json`.

How does it come that `dist/lib/node_modules` get installed? Can you show me a reproduction?

Relevant code: https://github.com/dherges/ng-packagr/blob/master/src/lib/ng-v5/entry-point/write-package.transform.ts#L64-L69

---

Hi @iamthechad,

this should not happen, unless you specified those dependencies. Can you show me a reproduction?

**Comment by avatsaev** [comment]
Same issue here David, we'll have a repro for you tomorrow afternoon

**Comment by avatsaev** [comment]
@dherges, could the reason be scoped package names? We're using @scope/package-name naming convention

**Comment by sbourouis** [comment]
During the e2e tests, we run `npm link` on the ci and it installs the `dist/lib/node_modules`

**Comment by iamthechad** [comment]
@dherges Here's a repo that shows the issue: https://github.com/iamthechad/sample-module-packagr. I always get the 3 extra entries in `node_modules`, plus I get `UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory` each time I run the packager. The file that cannot be found changes each time I run the packager.

**Comment by NeoLSN** [comment]
I also have the same issue after `ng-packagr@2.0.0-rc.13`.

https://github.com/dherges/ng-packagr/issues/589

I have a workaround is move your `index.ts` or `public_api.ts` under `<project_root>/src` folder, then it is fine.

**Comment by avatsaev** [comment]
@dherges I can confirm that node_modules appears only when you cd into the `dist` folder and do `npm link`

**Comment by dherges** [comment]
Hi Sabrina @sbourouis, Alan @avatsaev,

this is an issue of `npm link` running an install in the symlinked directory. In the [integration tests](https://github.com/dherges/ng-packagr/blob/master/integration/consumers.sh#L8-L22) `yarn link` works just fine.

Similar issues / questions:
- https://stackoverflow.com/questions/14381898/local-dependency-in-package-json
- for yarn link, here is a description where they say yarn has different behaviour than npm: https://github.com/yarnpkg/yarn/issues/2914

Including the `tslib` dependency is intended and in line with Angular Package Format. Compare to angular builds: https://github.com/angular/common-builds/blob/master/package.json#L11-L13
