### ISSUE TITLE
Having trouble with sourcemaps

### ISSUE THREAD

**Issue by iamthechad** [ng-packagr/ng-packagr#616]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
[X] Clarification?
```

## Description

We are having trouble using sourcemaps from modules generated by `ng-packagr`.

#### How To Reproduce

We have many in-house modules in our application. Each lives in its own Git repo and is published separately after being built with `ng-packagr`. I can see in the module's distribution that sourcemaps are generated and included, but I am unable to access them in the browser.

1. Build and publish a module. (https://github.com/iamthechad/sample-module-packagr) is an example of a module we build.
1. Add the module as a dependency to another app and install it
1. Run the app and try to see the original TS code

#### Expected Behaviour

I'm used to being able to open sources in Chrome via Command-P. I cannot open individual TS files from the included module in this manner, but must open the concatenated source for the whole module by navigating into `webpack://` and finding the transpiled source. I can get to the HTML templates under `ng://`, but the only source files there are `ngfactory` files which are pretty useless for me. I can't find any way to get to the actual TS source even though it's in the module and the sourcemap definition.

#### Version Information

```
$ ./node_modules/.bin/ng-packagr --version
ng-packagr:            2.0.0
@angular/compiler:     5.2.3
@angular/compiler-cli: 5.2.3
rollup:                0.55.3
tsickle:               0.26.0
typescript:            2.4.2
```

**Comment by ceeliro** [comment]
I am facing the same...

Thanks for the help

**Comment by andrea-spotsoftware** [comment]
@iamthechad any update on this issue? same here

**Comment by iamthechad** [comment]
@andrea-spotsoftware No updates yet. I'm not sure what I need to do to increase visibility of this issue.

**Comment by andrea-spotsoftware** [comment]
Looks like it's a v2 only problem, right? I'm trying the 1.x version in an old project and generated sourcemaps looks like correct

**Comment by sandeshdanwale** [comment]
Any updates?

**Comment by ViceIce** [comment]
Using ng-packagr v4.1, only the bundled fesm5 js file is available on chrome dev tools.

```

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.1.4
Node: 8.11.4
OS: win32 x64
Angular: 6.1.3
... animations, common, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.7.4
@angular-devkit/build-angular      0.7.4
@angular-devkit/build-ng-packagr   0.7.4
@angular-devkit/build-optimizer    0.7.4
@angular-devkit/build-webpack      0.7.4
@angular-devkit/core               0.7.4
@angular-devkit/schematics         0.7.4
@angular/cli                       6.1.4
@angular/compiler                  6.1.1
@ngtools/json-schema               1.2.0
@ngtools/webpack                   6.1.4
@schematics/angular                0.7.4
@schematics/update                 0.7.4
ng-packagr                         4.1.0
rxjs                               6.2.2
typescript                         2.9.2
webpack                            4.9.2
```

**Comment by myrddraall** [comment]
I've added 
```json

 "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "vendorSourceMap": true,
            "sourceMap": true,
            "evalSourceMap": true,
            ...
         }
}

this causes the ts files to show up, but on many lines i can't add breakpoints and even when i can inspecting variables gives all kinds of strange reference errors (

```
"XXXX is not defined"
```
where XXX seems to be random snippets of minified  code

**Comment by 82antu** [comment]
Hi, Same Issue Here. for minified version.

Seems to me that there is no alignment between the `min.js.map` and the` .min.js`.

For the non minified version works as expect

**Comment by alan-agius4** [comment]
@myrddraall and @82antu, can you provide a repo? What versions of Angular CLI and ng-packagr as you using? Are you on the latest versions?


Thanks

**Comment by bharathmuppa** [comment]
@myrddraall, There was an issue as mentioned  [here ](https://survivejs.com/webpack/building/source-maps/#-sourcemapdevtoolplugin-and-evalsourcemapdevtoolplugin-) 
` the eval-based options won't work in Chrome!`  So  removing
```json
"evalSourceMap": true,
```
should work.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem.
