### ISSUE TITLE
sourcemaps not working for dependencies

### ISSUE THREAD

**Issue by DChau10** [ng-packagr/ng-packagr#617]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I have many repositories that have angular modules packaged using ng-packagr. When I specify any one of those packages as a dependency and import it into an application (which also uses ng-packagr), none of my **dependencies** have working source maps in the browser.

#### How To Reproduce

I checked out the **master** branch of [ng-packaged](https://github.com/dherges/ng-packaged) repo and updated it to import another module packaged with ng-packagr. In this case, I used [ng-packaged-ticktock-demo](ng-packaged-ticktock-demo) which is published on npm.

First, I added the **"ng-packaged-ticktock-demo"** dependency to **ng-packaged**:

**package.json**
```js
"dependencies": {
  ...
    "ng-packaged-ticktock-demo": "^0.1.0",
  ...
}
```

Next, I imported the **TickTockModule** into the **src/app/app.module.ts**:

```ts
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';

import { AppComponent } from './app.component';
import { MyLibModule } from '@my/lib';
import { TickTockModule } from 'ng-packaged-ticktock-demo';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    MyLibModule.forRoot(),
    TickTockModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

And lastly, I add the **tick-tock** component to the template of **src/app/app.component.ts**

```ts
import { Component } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import { BarService } from '@my/lib';

@Component({
  selector: 'app-root',
  template: `
<my-foo></my-foo>
<hr>
<marquee>{{ value$ | async }}</marquee>
<tick-tock></tick-tock>
`,
  styleUrls: ['./app.component.css']
})
export class AppComponent {

  value$: Observable<string>;

  constructor (
    bar: BarService
  ) {
     this.value$ = bar.value;
  }

}

```

After installing all dependencies and serving up the app, I get the following in the browser:

![tick-tock-viewport](https://user-images.githubusercontent.com/2339766/36116893-22afbfde-0ff5-11e8-912f-cea3949f1f1a.png)
![tick-tock-console](https://user-images.githubusercontent.com/2339766/36116898-24d0f602-0ff5-11e8-957c-6f57c2a963e4.png)

I have tested and replicated this issue on:
- Chrome (64.0.3282.140)
- Firefox Developer Edition 59.0b8 (64-bit)
- Microsoft Edge 40.15063.674.0

#### Expected Behaviour

Source maps for dependency packages should work. When each package's test application is served up, each package has working source maps. However, when using a package as a dependency, its source maps fail to work in the browser.

#### Version Information

```js
{
  "name": "ng-packaged",
  "version": "0.0.0",
  "private": true,
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "build:app": "cpr dist/my-lib src/@my/lib && ng build --app packages && rimraf src/@my",
    "build:lib": "rimraf dist && ng-packagr -p my-lib/package.json",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "dependencies": {
    "@angular/common": "~5.2.0",
    "@angular/compiler": "~5.2.0",
    "@angular/core": "~5.2.0",
    "@angular/forms": "~5.2.0",
    "@angular/http": "~5.2.0",
    "@angular/platform-browser": "~5.2.0",
    "@angular/platform-browser-dynamic": "~5.2.0",
    "@angular/router": "~5.2.0",
    "ng-packaged-ticktock-demo": "^0.1.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular-devkit/schematics": "^0.3.0",
    "@angular/cli": "~1.6.0",
    "@angular/compiler-cli": "~5.2.0",
    "@angular/language-service": "~5.2.0",
    "@types/jasmine": "~2.8.0",
    "@types/node": "~9.4.0",
    "codelyzer": "~4.1.0",
    "cpr": "^3.0.0",
    "jasmine-core": "~3.0.0",
    "jasmine-spec-reporter": "~4.2.0",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.3.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ng-packagr": "2.0.0",
    "protractor": "~5.3.0",
    "rimraf": "^2.6.1",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.0",
    "tsickle": "^0.26.0",
    "typescript": "~2.7.1"
  }
}
```

**Comment by TheILPlace** [comment]
i am interested in this too...
ive looked at
https://www.tsmean.com/articles/how-to-write-a-typescript-library/angular/

and they indicate that

Important: Another thing you'll have to do, starting with Angular 5, is to include your files. So in the tsconfig.json you'll need:

"include": [
  "src/**/*",
  “node_modules/your-library/index.ts",
]

does this make sense in your situation ?

**Comment by AntonAnikeev** [comment]
Did @TheILPlace solution help for anyone?

**Comment by pavel-agarkov** [comment]
I only managed to succeed by adding separate `tsconfig.app.debug.json` and referencing it in new build:debug configuration in `angular.json`
```json
...
      "architect": {
        "build": {
...
          "configurations": {
            "debug": {
              "tsConfig": "src/tsconfig.app.debug.json"
            },
...
```
In this config I do override paths to my libraries so they get included directly into the main build process and thus covered by main source-maps:
```json
...
  "angularCompilerOptions": {
    "paths": {
      "shared": [
        "projects/shared/src/public_api"
      ],
      "core": [
        "projects/core/src/public_api"
      ]
    }
  }
...
```
This configuration is used only for debugging so I decided it is not that bad since I couldn't find anything better.

**Comment by dkonasov** [comment]
Adding "vendorSourceMap" option in the Angular.json resolved this issue for me. Example:
`{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "angular-new-ui": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "prefix": "app",
      "schematics": {
        "@schematics/angular:component": {
          "styleext": "scss"
        }
      },
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/angular-new-ui",
            "index": "src/index.html",
            "vendorSourceMap": true,
...
`

**Comment by alan-agius4** [comment]
Closing as per above comment.
