### ISSUE TITLE
Importing SVG.JS library as an external dependency

### ISSUE THREAD

**Issue by vvaldersteins** [ng-packagr/ng-packagr#618]
Hello,

I'm trying to build a package which uses svgjs as a core library for the package. I have included it in the peerDependencies, as well as, in the ng-package.json file in the external section with the format -

```
    "externals": {
      "svgjs": "SVG"
    }
```

In the code I'm using -
```
import * as SVG from 'svgjs';
```

But when I run the build script it returns the following error message - 

```
Cannot call a namespace ('SVG')
```

I have tried the following -
```
import * as SVG_ from 'svgjs';
const SVG = SVG_;
```

This works like a charm, but is not a solution, since it gives me some type definition errors in the code itself. I would liek to stick with just import * as SVG from 'svgjs'. Might be that the key-value pair is incorrect, but I can't seem to figure out what should be the value. I checked their packaged files, but was not able to figure out from it.

Any suggestions?

**Comment by vvaldersteins** [comment]
Noticed that `externals` was renamed to `umdModuleIds` in latest version. Tried that as well, without any success.

**Comment by vvaldersteins** [comment]
Any other suggestions?

**Comment by andrea-spotsoftware** [comment]
I had a similar problem with moment library.
After surfing github pages, I ended up with a tricky and un-elegant solution.
Here it is:
```
import * as moment from 'moment';
const momentFunc: typeof moment = 'default' in moment ? moment['default'] : moment;

@Component({
  selector: 'ngx-custom',
  templateUrl: './custom.component.html'
})
export class CustomComponent implements OnInit {
  constructor() {
    const momentString = momentFunc().format('LLL');
  }
}
```

**Comment by lishichao1002** [comment]
same question .

import * as pathToRegexp from 'path-to-regexp';
import * as URI from 'urijs';

```
BUILD ERROR
Cannot call a namespace ('pathToRegexp')
Error: Cannot call a namespace ('pathToRegexp')
    at error (D:\workspaces\test\angular-router-mock\node_modules\rollup\dist\rollup.js:170:15)
    at Module.error (D:\workspaces\test\angular-router-mock\node_modules\rollup\dist\rollup.js:17195:9)
    at Node.CallExpression.bindNode (D:\workspaces\test\angular-router-mock\node_modules\rollup\dist\rollup.js:12261:29)
    at NodeBase.bind (D:\workspaces\test\angular-router-mock\node_modules\rollup\dist\rollup.js:11072:14)
    at D:\workspaces\test\angular-router-mock\node_modules\rollup\dist\rollup.js:11078:56
    at D:\workspaces\test\angular-router-mock\node_modules\rollup\dist\rollup.js:11092:66
    at Array.forEach (<anonymous>)
    at D:\workspaces\test\angular-router-mock\node_modules\rollup\dist\rollup.js:11092:23
    at Array.forEach (<anonymous>)
    at NodeBase.eachChild (D:\workspaces\test\angular-router-mock\node_modules\rollup\dist\rollup.js:11087:19)

```

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent version.
