### ISSUE TITLE
Component B extends Component A without constructor and super call results in no ctorParameters in UMD bundle

### ISSUE THREAD

**Issue by janerikmai** [ng-packagr/ng-packagr#631]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description
First, if this is something related to tsc / tsickle or angular/compiler, please point me in the right direction.

When extending class A with class B without constructor in B and super A, B is missing ctor parameters in UMD bundle, wich results in B not having construction providers. When extending class A with class C, having constructor and super call, umd bundle of class C has ctor parameters and the correct (needed) providers. So if you use this umd bundle in an other lib/project it will result in not having cdr and m for B.

See example repository: [janerikmai/ctor-inheritance-test](https://github.com/janerikmai/ctor-inheritance-test)

#### How To Reproduce

See example repository: [janerikmai/ctor-inheritance-test](https://github.com/janerikmai/ctor-inheritance-test)

#### Expected Behaviour

Class B should contain ctor parameters inherited from class A without own constructor and super call.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            2.0.0
@angular/compiler:     5.2.5
@angular/compiler-cli: 5.2.5
rollup:                0.55.5
tsickle:               0.26.0
typescript:            2.5.3
```

**Comment by deadalusai** [comment]
I think this is an issue in `tsickle` specifically: https://github.com/angular/tsickle/pull/760

**Comment by dherges** [comment]
Duped by  #679

**Comment by Swiftwork** [comment]
Should be resolved by a [tsickle update](https://github.com/dherges/ng-packagr/issues/679#issuecomment-379665166).

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases.
