### ISSUE TITLE
Add support for postcss-import

### ISSUE THREAD

**Issue by smithad15** [ng-packagr/ng-packagr#643]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
[x] Support
```

## Description

First of all, thank you so much for all of the time that you are putting into this library. It's filling a huge need in the community and as someone who has wrestled with creating a few too many custom build steps for Angular projects, I appreciate the amount of work it takes to get it right.

I am currently working on publishing a component library that uses some advanced postcss features through the use of `postcss-cssnext` and `postcss-import`. We use `@import` statements inside of our component style files in order to import global values like CSS variables declared using `:root`. Those import statements do not currently get resolved when the library is built which is causing some troubles with the webpack loader setups with consuming applications as most build chains assume that any component CSS in a dependent library should already be fully processed and easily imported as a raw string.

I noticed that you had recently re-architected the library to be more pluggable through the use of Transforms and DI and was trying to figure out if I could somehow inject my own transform function to run `postcss-import` over the component stylesheets. Based upon the [public-api file](https://github.com/dherges/ng-packagr/blob/master/src/public_api.ts), it doesn't look like you have exposed the injection tokens for [STYLESHEET_TRANSFORM_TOKEN](https://github.com/dherges/ng-packagr/blob/master/src/lib/ng-v5/entry-point/resources/stylesheet.di.ts#L6) or the original implementation of [stylesheetTransform](https://github.com/dherges/ng-packagr/blob/master/src/lib/ng-v5/entry-point/resources/stylesheet.transform.ts#L20) which might allow me to override or extend the providers.

My request is either, is there a way for me to leverage your current DI system to be able to write the custom transform that I want (which it is fully plausible that I have not completely wrapped my head around its implementation), or would you find it acceptable to receive a PR with `postcss-import` added as a plugin. Any guidance you can provide would be greatly appreciated.

Many Thanks.

**Comment by dherges** [comment]
Hi @smithad15,

similar to `forProject()` and `withTsConfig()` will be a good way. The question is how to expose?

`withPostCssPlugin(plugins: Plugin | pluginFunction | Processor[])` pass an array of processors, then add ot poscss

```ts
postcss = plugins.reduce((plugin, postcss) => {
  return postcss.use(plugin);
}, postcss)
```

?

http://api.postcss.org/Processor.html#use

**Comment by dherges** [comment]
On that notice, it's also a good idea to initialize the css tooling per ngPackage and not ["per stylesheet file"](https://github.com/dherges/ng-packagr/blob/master/src/lib/ng-v5/entry-point/resources/stylesheet.transform.ts#L40-L41). Currently., it's wasting a lot of resources by re-initializing the css tooling.

So my current idea is to create a

```ts
interface PostCssRenderer {
  (stylePath: string, css: string): string;
}

class Stylesheets {

  createPostCssProcessor(entryPoint: NgEntryPoint): PostCssRenderer {

    return (filePath, cssString): string => {
      /* .. postcss processing here ... */
      return resultCssString;
    };
  }
}
```

Then we would need the programmatic API to provide "factory-like" functions.


```ts
  withPostCssPlugin(factoryFn: (entryPoint: NgEntryPoint) => PostCssRenderer)
```

???

**Comment by dherges** [comment]
See my comments in https://github.com/dherges/ng-packagr/commit/75907dc9451f83c6165a8eff3824eeb99deba0fa

Should we make it a `withPostCssPlugin()` where you override factories for plugins or rather a with `withPostCss()` where you override the full post-css rendering?

**Comment by dherges** [comment]
After breakfast coffee, why not `withStylesheetRenderer(fn: RendererFactory)` and `withTemplateRenderer(fn: RendererFactory)`?

A renderer factory would look like:

```ts
.withStylesheetRenderer((entryPoint: NgEntryPoint) => {
  return ({ filePath, data }: { filePath: string, data: string }) => {
     return '.. pre-processed and post-css'ed styleshet here ..';
  };
})
```

**Comment by dherges** [comment]
After all that, I refactored the stylesheet transform and added some utilities to the Graph / Node API.

https://github.com/dherges/ng-packagr/blob/26accf9/src/lib/ng-v5/entry-point/resources/stylesheet.transform.ts#L20-L27

`Graph`, `Node`, `StylesheetNode`, `EntryPointNode`, `isEntryPointInProgress()`, and so on should be added to the public API. Do you think that will empower you to override the stylesheet transformation? 

```ts
import { ngPackagr } from 'ng-packagr';

ngPackagr()
  .withStylesheetTransform(transformFromPromise(async graph => {
    /* you will be in charge of the full stylesheet rendering */
    const entryPoint = /* current entry point */;
    const stylesheets = /* stylesheets in entry point */;

    for (let stylesheet of stylesheets) {
      stylesheets.data.content = /* store rendered css here */;
    }
  }))
  /* .. */
```

**Comment by dherges** [comment]
To summarize, how do you like to customize?

- the full transformation: most flexibility, no re-use of defaults, implement with graph api
- override postcss plugins: less flexible, re-use default rendering but do not re-use default postcss plugins, implement with entrypoint and string api
- add postcss plugins: least flexible, just add plugins to default postcss plugins, not be able to control order of postcss plugins, implement with entrypoint and string api

**Comment by dherges** [comment]
FYI / CC @alan-agius4 What do you think? You mentioned the HTML minifying in #614. By giving access to the full template transform, you'd be able to customize like so:

```ts
ngPackagr()
  .withTemplateTransform(  transformFromPromise(async graph => {
    const entryPoint = /* current entry point from graph */;
    const templates = /* templates in entry point */;

    for (let template of templates) {
      template.data.content = '...rendered and minified html here...';
    }
  })
```

---

FYI / CC @DavidParks8 @deebloo Regarding the typescrript config customization, by giving you access to the full transform, you'd be able to customize not only the defaults but rather the generated tsconfig for an entry point like so:

```ts
import { ParsedConfiguration } from '@angular/compiler-cli';

ngPackagr()
  .withTemplateTransform(  transformFromPromise(async graph => {
    const entryPoint = /* current entry point from graph */;
    entryPoint.data.tsConfig = /* set a `ParsedConfiguration` specific to the current entry point here */;
  })
```

**Comment by alan-agius4** [comment]
I love the idea

**Comment by smithad15** [comment]
I think that the `withStylesheetRenderer(fn: RendererFactory)` and `withTemplateRenderer(fn: RendererFactory)` APIs are probably the best of all worlds. Being supplied the string content of the file (stylesheet or template) with some additional context (entry point and file path/name), it allows the maximum flexibility for library consumers to implement whatever transform they wish while not exposing such low level concerns as nodes and graphs, which will allow you freedom to refactor the inner workings easier at a later time if desired. If it is possible to just supply the renderer function directly instead of using a factory pattern, that would help with ease of adoption as well. Thanks so much for the speedy response and open discussion!

**Comment by smithad15** [comment]
I like it. That's a great compromise

**Comment by junyper** [comment]
I would prefer something like using https://github.com/michael-ciniawsky/postcss-load-config to detect if I have a config file in the package directory and fall back to some defaults if not.

**Comment by gquinteros93** [comment]
Hi @dherges, @smithad15 and @alan-agius4. These features seem to be what we the developers needs to use postcss with ng-packagr. 
I see that the branch has not been merged yet.

Do you know if it's ready to merge?
When is going to be ready to use?

Thanks in advance.

**Comment by futbolsalas15** [comment]
Is there any way you can merge the branch that @gquinteros93  mentioned?

**Comment by unicornist** [comment]
@gquinteros93 @futbolsalas15 which branch are you talking about I don't see any branch other than released versions and master. if there is a branch that fixes postcss issue we can fork it and use our forked version as a git dependency until it's merged. But I can't find it.
