### ISSUE TITLE
How do I add a raw JavaScript file to be processed by ng-packagr

### ISSUE THREAD

**Issue by MahiK14** [ng-packagr/ng-packagr#650]
Hello ,

 I am facing the following error:BUILD ERROR
Could not resolve '../../code-editor/code-editor/wetty.js' from .ng_pkg_build/code-editor-module/ts/code-editor/code-editor/code-editor.component.js
Error: Could not resolve '../../code-editor/code-editor/wetty.js' from .ng_pkg_build/code-editor-module/ts/code-editor/code-editor/code-editor.component.js
    at error (/Users/mahender/git/code-editormodule/code-editor-module/node_modules/rollup/dist/rollup.js:185:14)
    at then.resolve

Wetty.js is simple js file.
How can I include external js files in the ng-packagr process?

**Comment by alan-agius4** [comment]
That is not possible by TypeScript at the moment.

https://github.com/dherges/ng-packagr/issues/540

**Comment by scott-ho** [comment]
@alan-agius4 it's incorrect that TypeScript doesn't support it. It just doesn't support `allowJs` and `declaration` at the same time.

However, after I managed to **disable the declaration generation in ng-packagr(it's hardcoded)**, I still can't find the raw js module in output dir and errors prompt.

I think this might a ng-packagr issue to output the raw js module in the bundle.

/cc @dherges

**Comment by alan-agius4** [comment]
As explained in the issue linked that’s why it’s not supported, ie: allowJS with declarations.

When generating a valid library you always need to generate declarations.

**Comment by METACEO** [comment]
@alan-agius4 @dherges - what would the plan be if I want my ng-packagr library to consume protobufjs output? I've got a project as follows below. If `app.component.ts` used the shared client library where `client.service.ts` could consume the `protobufjs/client.js` output, how would I achieve this? Most importantly my `client.service.ts` and `src-server/index.ts` would consume the same protobufjs output.

Any ideas?
 
```
ng6-workspace-root
  projects
    shared-client
      src
        public_api.ts
        lib
          client.service.ts
          protobufjs
            client.d.ts
            client.js
            client.proto
  src
    app
      app.component.ts
  src-server
    index.ts
```

**Comment by alan-agius4** [comment]
Blocked on Angular supporting TS 3.7

**Comment by eric-simonton-sama** [comment]
Am I interpreting correctly that the TS blocker is resolved now (from [this](https://github.com/microsoft/TypeScript/pull/32372))? And if so, is `allowJs` being considered for `ng-packagr` now?

**Comment by ocombe** [comment]
It doesn't seem to work by default, but adding `allowJs: true` to this https://github.com/ng-packagr/ng-packagr/blob/master/src/lib/ts/tsconfig.ts#L16 makes it work

**Comment by eric-simonton-sama** [comment]
@alan-agius4 What prompted closing this PR? Should I be excited that it's going to work now? Disappointed that it never will? :)

**Comment by alan-agius4** [comment]
This should now work if you use Typescripts `allowjs` option.
