### ISSUE TITLE
How to create dependent packages using nx-packaged 

### ISSUE THREAD

**Issue by moattarwork** [ng-packagr/ng-packagr#661]
## Type of Issue

```
[ ] Bug Report
[ ] Feature Request
[*] Question
```

## Description

I have multiple libs in a nx project. Some of them are dependent to one lib which is the core lib.

When I try to build the lib using packager it will end up with throwing exception on finding the referenced module in import.

I couldn’t find any sample related to dependent module in your documentation or samples and I don’t even now if that is a supported case or not. Could you please share some samples related to this?

**Comment by dherges** [comment]
The workaround is to built A first, then publish to `node_modules/A` and then build B that depends on A.

There may something be coming. First for entry points, see #685, later for packages.

**Comment by moattarwork** [comment]
Thanks. I’ve had look and I think it’s exactly what I’m looking for. I can wait for the merge of PR.
