### ISSUE TITLE
Need to define custom named exports for commonjs dependencies

### ISSUE THREAD

**Issue by dherges** [ng-packagr/ng-packagr#671]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

Custom Named Exports: https://github.com/rollup/rollup-plugin-commonjs#custom-named-exports

As ng-packagr doesn't specify `namedExports` option to the common js plugin, this leads to rollup errors with third-party dependencies that are converted from commonjs. Rollup bundling fails when writing the fesm bundles as it can't see the custom named exports.

#### How To Reproduce

Related issues

- https://github.com/dherges/ng-packagr/issues/310
- https://github.com/dherges/ng-packagr/issues/301

#### Expected Behaviour

tbd

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 2.2.0
```

**Comment by alan-agius4** [comment]
Obsolete due to recent changes that removed UMDs
