### ISSUE TITLE
View typescript source files during debug packaged module

### ISSUE THREAD

**Issue by markne** [ng-packagr/ng-packagr#672]
## Type of Issue

```
[x ] Feature Request
```

## Description

Hello
During debug a packaged module, browser shows javascript code.
How can I see the typescript mapped code?

#### How To Reproduce

I run a great step-by-step example of making an Angular CLI project with a library distributed separate from the app: https://github.com/jasonaden/angular-cli-lib-example

#### Expected Behaviour

_A bug: please describe what behaviour or result you expected_

_A feature: do you have a first draft or an idea how to implement?_

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 2.0.0
@angular/*: 5.2.1
typescript: 2.5.3
rxjs: x.y.z
node: v.8.9.4
npm/yarn: x.y.z
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by JBoothUA** [comment]
I think this is the correct place to add my 2 cents.  I'm a new user and big fan of this project :) it's already gotten us out of one bind, and gotten me into the world of packaged modules...

but we quickly ran into another bind..  how do we debug these packaged modules...  I'm assuming it's not possible at this time??  

for our non-modular code, we just run ng build without the prod flag so nothing gets minified, etc.  I was expecting a similar command or option for this packager.

It would definitely be my biggest / only request for the project if this is the case :)  thanks for everything!

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.
