### ISSUE TITLE
External template file inlining doesn't work

### ISSUE THREAD

**Issue by alexisdoualle** [ng-packagr/ng-packagr#674]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

When packaging, the file linked by templateUrl is not bundled into the output file.

For example, my-component.umd.js (in dist/bundles) has this:

```

HeaderComponent.decorators = [

    { type: core.Component, args: [{
                selector: 'my-header',
                templateUrl: 'my-header.html',
                styleUrls: ['my-style.css]
            },] },

];
```
The result is that when I ng-serve the app, I get a 404 (couldn't get my-header.html). There are apparently no errors when running ng-packagr.

#### Expected Behaviour

The output should look something like this:

```
HeaderComponent.decorators = [

    { type: core.Component, args: [{
                selector: 'my-header',
                template: '<h1>My header</h1>',
                ...
            },] },
];
```

#### Version Information

```
"dependencies": {
    "@angular/animations": "^5.2.6",
    "@angular/cdk": "^5.2.3",
    "@angular/common": "^5.2.6",
    "@angular/compiler": "^5.2.6",
    "@angular/core": "^5.2.6",
    "@angular/forms": "^5.2.6",
    "@angular/http": "^5.2.6",
    "@angular/material": "^5.2.2",
    "@angular/platform-browser": "^5.2.6",
    "@angular/platform-browser-dynamic": "^5.2.6",
    "@angular/platform-server": "^5.2.6",
    "@angular/router": "^5.2.6",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "^1.7.1",
    "@angular/compiler-cli": "^5.2.6",
    "@angular/language-service": "^4.2.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.1.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "npm": "^5.7.1",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.3.2",
    "typescript": "2.4.2"
  }
```
I tried using an older version of ng-packagr, didn't change anything. But I don't know what else it could be, I also tries changing rollup versions.

The workaround I have for now is this one: https://stackoverflow.com/a/48253259/7173967
This works, but it's inconvenient to have ts files instead of html/css files.

**Comment by dherges** [comment]
Imo, that can happen when the TypeScript AST traversal doesn't recognize the component decorator. The [implementation is spec'ed here](https://github.com/dherges/ng-packagr/blob/master/src/lib/ts/ng-ts-ast.spec.ts). What is the source code of the faulty component (full source file incl. imports please)?

**Comment by alexisdoualle** [comment]
header.component.html: 

`<mat-toolbar color="accent" id="main-bar">
  <div style="height: 50px;">
    <a href="/"><span class="logo"></span></a>
  </div>

  <span style="width:100%"></span>
  <div layout="column">
    <a href="/WS-CNS-AUTH/logout">
      <button mat-button class="md-icon-button menu-button delete-button" title="Logout">
        <i class="material-icons" aria-label="Logout">power_settings_new</i>
      </button>
    </a>
  </div>
</mat-toolbar>`

header.component.ts:

`import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'wezen-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}`

header.module.ts:

`import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HeaderComponent } from './header.component';
import { MatToolbarModule, MatButtonModule } from '@angular/material'

@NgModule({
  imports: [
    CommonModule,
    MatToolbarModule,
    MatButtonModule
  ],
  declarations: [HeaderComponent],
  exports: [
    HeaderComponent
  ]
})
export class HeaderModule { }`

Packaging works without problems on my Angular4-legacy branch, with ng-packagr@1.7.0, and with the same source code.

**Comment by dherges** [comment]
Repro in #678

**Comment by dherges** [comment]
I tried to reproduce from your code example and initially thought I had it ... well, i included your component source in the ts ast specs, see here https://github.com/dherges/ng-packagr/commit/3d3fef4ffcd541bd4a8eb0f593be90938f98c7ff#diff-7de602fd42dd81a1add746f70b477796R208 - but that is not the issue. Looks like the decorator and the template and styles are recognized.

Do you have a github repro that shows your error?

**Comment by alexisdoualle** [comment]
Here is is:
https://github.com/alexisdoualle/sample-app

You're probably going to comment on the following script

```
"scripts": {
    "custom-script": "npm install git+https://github.com/alexisdoualle/custom-component-library && npm run custom-script2",
    "custom-script2": "cd node_modules/custom-component-library && npm install ng-packagr && npm run packagr"
}
```

I run it in order to package the library after I fetch it. The reason is that I don't have a private npm repo, and I don't want to commit the bundles, only the source code.
This is were it breaks obviously. The thing is, I don't understand why. In the repo I linked, I added two components in the library: the <custom-div>, which uses the workaround of changing the template and styles to .ts files which are then imported in the component, -this works fine; and the <custom-header>, which doesn't use the workaround, and breaks (I commented it out in the example, if I don't I get a 404).

If I run packagr from the sandbox app in the component library, it works fine. So it's obviously my workaround that's causing this, though I don't see a way around it right now. I even tried to npm install the component library inside the node_modules folder, didn't work either.

**Comment by JanEggers** [comment]
same issue here i updated from 1.6 to 2.2 going back to the old version for now

**Comment by dherges** [comment]
```bash
$ git clone https://github.com/alexisdoualle/custom-component-library
$ cd custom-component-library
$ npm install
$ npm run packagr
```


ESM5 Bundle:

```js
import { Component, NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

var CustomHeaderComponent = /** @class */ (function () {
    function CustomHeaderComponent() {
    }
    CustomHeaderComponent.prototype.ngOnInit = function () {
    };
    return CustomHeaderComponent;
}());
CustomHeaderComponent.decorators = [
    { type: Component, args: [{
                selector: 'custom-header',
                template: "<h1>Custom Header</h1>",
                styles: [""]
            },] },
];
CustomHeaderComponent.ctorParameters = function () { return []; };
var CustomHeaderModule = /** @class */ (function () {
    function CustomHeaderModule() {
    }
    return CustomHeaderModule;
}());
CustomHeaderModule.decorators = [
    { type: NgModule, args: [{
                imports: [
                    CommonModule
                ],
                declarations: [CustomHeaderComponent],
                exports: [CustomHeaderComponent]
            },] },
];
CustomHeaderModule.ctorParameters = function () { return []; };
var template = "\n<div>\n  Custom div\n</div>\n";
var style = "\ndiv {\n  background-color: lightblue;\n}\n";
var CustomDivComponent = /** @class */ (function () {
    function CustomDivComponent() {
    }
    CustomDivComponent.prototype.ngOnInit = function () {
    };
    return CustomDivComponent;
}());
CustomDivComponent.decorators = [
    { type: Component, args: [{
                selector: 'custom-div',
                template: template + '',
                styles: [style + '']
            },] },
];
CustomDivComponent.ctorParameters = function () { return []; };
var CustomDivModule = /** @class */ (function () {
    function CustomDivModule() {
    }
    return CustomDivModule;
}());
CustomDivModule.decorators = [
    { type: NgModule, args: [{
                imports: [
                    CommonModule
                ],
                declarations: [CustomDivComponent],
                exports: [CustomDivComponent]
            },] },
];
CustomDivModule.ctorParameters = function () { return []; };

export { CustomHeaderModule, CustomDivModule, CustomDivComponent as ɵb, CustomHeaderComponent as ɵa };
//# sourceMappingURL=custom-component-library.js.map
```

ESM2015 Bundle:

```js
import { Component, NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

/**
 * @fileoverview added by tsickle
 * @suppress {checkTypes} checked by tsc
 */
class CustomHeaderComponent {
    constructor() { }
    /**
     * @return {?}
     */
    ngOnInit() {
    }
}
CustomHeaderComponent.decorators = [
    { type: Component, args: [{
                selector: 'custom-header',
                template: `<h1>Custom Header</h1>`,
                styles: [``]
            },] },
];
/** @nocollapse */
CustomHeaderComponent.ctorParameters = () => [];

/**
 * @fileoverview added by tsickle
 * @suppress {checkTypes} checked by tsc
 */
class CustomHeaderModule {
}
CustomHeaderModule.decorators = [
    { type: NgModule, args: [{
                imports: [
                    CommonModule
                ],
                declarations: [CustomHeaderComponent],
                exports: [CustomHeaderComponent]
            },] },
];
/** @nocollapse */
CustomHeaderModule.ctorParameters = () => [];

/**
 * @fileoverview added by tsickle
 * @suppress {checkTypes} checked by tsc
 */
var template = `
<div>
  Custom div
</div>
`;

/**
 * @fileoverview added by tsickle
 * @suppress {checkTypes} checked by tsc
 */
var style = `
div {
  background-color: lightblue;
}
`;

/**
 * @fileoverview added by tsickle
 * @suppress {checkTypes} checked by tsc
 */
class CustomDivComponent {
    constructor() { }
    /**
     * @return {?}
     */
    ngOnInit() {
    }
}
CustomDivComponent.decorators = [
    { type: Component, args: [{
                selector: 'custom-div',
                template: template + '',
                styles: [style + '']
            },] },
];
/** @nocollapse */
CustomDivComponent.ctorParameters = () => [];

/**
 * @fileoverview added by tsickle
 * @suppress {checkTypes} checked by tsc
 */
class CustomDivModule {
}
CustomDivModule.decorators = [
    { type: NgModule, args: [{
                imports: [
                    CommonModule
                ],
                declarations: [CustomDivComponent],
                exports: [CustomDivComponent]
            },] },
];
/** @nocollapse */
CustomDivModule.ctorParameters = () => [];

/**
 * @fileoverview added by tsickle
 * @suppress {checkTypes} checked by tsc
 */

/**
 * @fileoverview added by tsickle
 * @suppress {checkTypes} checked by tsc
 */
/**
 * Generated bundle index. Do not edit.
 */

export { CustomHeaderModule, CustomDivModule, CustomDivComponent as ɵb, CustomHeaderComponent as ɵa };
//# sourceMappingURL=custom-component-library.js.map
```


Looks good to me.

**Comment by pegpeg** [comment]
Hey

I have the same issue when I try to build my dependency with a postinstall script.

I think, the issue is related to _transform-component.ts_ where files in node_modules are ignored.
```
  if (sourceFile.fileName.includes('node_modules')) {
    return sourceFile;
  }
```

If I remove this lines, that works for me.

Do you have an idea or a lead to improve this feature and don't ignore sources of the dependency that we are building ?

**Comment by extrememito** [comment]
Same for me. Downgraded to 3.x.x and it works fine

**Comment by nasaleanhorea** [comment]
Can confirm , external templates worked up until version 4.0.0.
My biggest issue is that i really enjoy @alan-agius4  (Hey Alan ::D ) incremental build. and don't want to downgrade to version 3.x.x

**Comment by alan-agius4** [comment]
@nasaleanhorea can you provide a repo?

**Comment by nasaleanhorea** [comment]
@alan-agius4 

Here's a sample library https://github.com/nasaleanhorea/ng-packagrIssue

**Comment by alan-agius4** [comment]
Thanks, the problem is that you are using an older version of Angular and
ng-packagr version 4 only supports Angular 6+

**Comment by dalelotts** [comment]
@alan-agius4 what do you think about a change that will fail the build (or simply output a message) if the Angular < 6 is detected?

**Comment by alan-agius4** [comment]
Closing due to lack of feedback.
