### ISSUE TITLE
Copy README and LICENSE if package.json not in root folder

### ISSUE THREAD

**Issue by hansmaad** [ng-packagr/ng-packagr#689]
## Type of Issue

```
[ ] Bug Report
[ ] Feature Request
[*] Question
```

## Description

My lib package.json is in a lib subfolder (as in the ng-packaged example). The package.json in the root folder has dependencies that should not be dependencies of the package (The rep contains a demo page).
The package builds fine, but the README.md and LICENSE file from the root folder won't get copied into dest. Is there a way to configure the location of the readme file, or where should I put the configuration file, when I want to use the main README but not the main package.json?

The lib repo: https://github.com/hansmaad/ng-units

The lib/package.json
```
{
  "repository": {
    "type": "git",
    "url": "https://github.com/hansmaad/ng-units.git"
  },
  "private": false,
  "peerDependencies": {
    "@angular/core": "^5.2.0",
    "@angular/common": "^5.2.0"
  },
  "ngPackage": {
    "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
    "lib": {
      "entryFile": "../public_api.ts"
    },
    "dest": "../dist"
  }
}
```
#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            2.2.0
@angular/compiler:     5.2.7
@angular/compiler-cli: 5.2.7
rollup:                0.55.5
tsickle:               0.27.2
typescript:            2.5.3
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by georgiee** [comment]
After running you pack task you will get a working dist folder. The only thing left to do is copying your files manually in there. This is nothing ng-packagr needs to do.

To do you can use a shell script you call with npm or everything in npm like this.
```
"copy": "cp README.md dist",
"pack": "ng-packagr -p ng-units/package.json && npm run copy"
```

**Comment by hansmaad** [comment]
@georgiee thanks for this suggestion, I'll go with this solution.

> This is nothing ng-packagr needs to do.

I think it actually does do it, if the README is next to the ng package file...

**Comment by e-cloud** [comment]
provide a external options to copy external resource would be great.

**Comment by cyrilletuzi** [comment]
Now that `ng-packagr` is used inside Angular CLI, libraries generated by the CLI are in this exact scenario: `README.md` and `LICENSE` are in the root folder (for Github), and not in the library directory, and so they are not copied when building.

**Comment by odahcam** [comment]
What @cyrilletuzi is exactly true, `ng packagr` could parse `readme` and `license` fields to accomplish that.

**Comment by davidwuerfel** [comment]
I manually copy over a README for my lib into the dist folder in a postbuild script. I feel like a lot of library publishers will do the same. Wouldn't it be cool if the ng-package.json had an entry like "readme" with a path e.g. defaulted to the lib root that would be copied so that no additionally dependencies had to be added by myself?

**Comment by dhilt** [comment]
The following solves the issue for me.

./myLib/ng-package.json

```json
{
  "$schema": "../node_modules/ng-packagr/ng-package.schema.json",
  "dest": "../dist/myLib",
  "lib": {
    "entryFile": "public-api.ts"
  },
  "assets": [
    "../LICENSE",
    "../README.md"
  ]
}

```
