### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by leonixyz** [ng-packagr/ng-packagr#695]
## Type of Issue

```
[ ] Bug Report
[X] Feature Request
```

## Description

I'd like to be able to package a component library whose components have internationalization/localization support ([i18n](https://angular.io/guide/i18n)).  

## Expected Behaviour

If I build an app that uses i18n, my components should be translated as well. I would like to be able to ship translation files among with my library, and any app using my library should be able to be AOT compiled including those translation files.

**Comment by codegagan** [comment]
We too need this feature. Because of this feature we are stuck on shipping our Angular 5 app as library for other app. Please let me know if there are any workarounds.

**Comment by kylecordes** [comment]
So far, the documented Angular Package Format latest and greatest:

https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/edit#!

Does not specify anything about i18n or translation files. It doesn't ban them, but it doesn't mention them. It's going to be tough to have interoperable results between packaging tools and consuming tools until that happens, but to get started in the right direction: is there any open source example component library outfitter which arrives with translation files, Which are then consumed automatically by the downstream tooling (CLI)?

**Comment by rg1220** [comment]
This would be a good feature so that our shared library can maintain it's own translations and the apps that import it can simply import the correct language build.

**Comment by xiaoxiangmoe** [comment]
Any update on this? @alan-agius4

**Comment by vgb1993** [comment]
I also need somethihng like this. It would prevent us from having the same translation in many apps.

**Comment by nelisbijl** [comment]
My workaround:
Place a minimal dummy application project next to your library project
Import your library in app.module.ts
Fiddle with tsconfig.json paths to be able to find your library
Add localization to your dummy application
Change destination path in angular.json to point to library/src/i18n
Add i18n folder to assets in ng-package.json

**Comment by PowerKiKi** [comment]
> merge your translations in it's own translation file

Have you considered using implicit merging as described in https://github.com/angular/angular/pull/32912#issuecomment-703074273 ? It might simplify your setup.

**Comment by alan-agius4** [comment]
Let continue tracking this in https://github.com/angular/angular-cli/issues/17140
