### ISSUE TITLE
Develop node API

### ISSUE THREAD

**Issue by gravitypersists** [ng-packagr/ng-packagr#700]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

I've seen [this issue](https://github.com/dherges/ng-packagr/issues/341) but this is more a request to expose and support a node api for the future of this lib. 

The reporter of that issue had a mono-repo for multiple packages, adding ng-packagr to each child is a chore. I have a similar situation (I'm writing a CLI to turn a bunch of non-angular libs into angular libs, which in this case, is even more a chore because with it I need to include all of the peers of ng-packagr, from all the @angular/libs to typescript).

I understand there's a public_api.js linked from main, but there's no documentation for that and it seems like the api which that issue linked above has already been changed.

**Comment by alan-agius4** [comment]
The API is available, take a look how I am using it here https://github.com/alan-agius4/ng-mono-repo-starter/blob/master/tools/tasks/build.ts

**Comment by gravitypersists** [comment]
Ah, that's good - might be a matter of just formally declaring and documenting it then?

**Comment by alan-agius4** [comment]
Yep, that said the API is still not to be considered as stable.
