### ISSUE TITLE
Template compile error when ` character is inside .html files

### ISSUE THREAD

**Issue by ffriedl89** [ng-packagr/ng-packagr#706]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description
Depending on the position of the ` character in the .html template a different error might be thrown during compilation. 

e.g. `error TS1161: Unterminated regular expression literal.` or `error TS1005: ',' expected.`

Example:
```html
<span>`</span>
```
or

```html
<!--
  Set `aria-hidden` on ...
-->
```
#### How To Reproduce

Insert ` character somewhere in the template html.

Example:
```html
<span>`</span>
```
or

```html
<!--
  Set `aria-hidden` on ...
-->
```

Note: If we do the same with the build angular material has, it works fine.

#### Expected Behaviour
` characters should not break the build

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: master
```

**Comment by rafaelblink** [comment]
Check this answer.

https://stackoverflow.com/questions/45842731/unterminated-string-literal-error-in-nativescript-typescript-app-component-ts

> The value you are assigning to the template property is a multi line string. Those are not permitted in Typescript. It's usually not a good idea to have strings longer than 140 characters (you can use the wonderful tslint to help you with this), so it's better to put the template in the html file.
If however you still want to keep it in the file you have to use the ` (backtick - alt+0096 on windows) character to delimit the string instead of the ' (single quote).

**Comment by ffriedl89** [comment]
@rafaelblink unfortunately the title might be a bit misleading. This issue occurs in the .html files and not in the template: attribute on the component.

**Comment by alan-agius4** [comment]
Closing as this should no longer be an issue.
