### ISSUE TITLE
embedded is not working for require

### ISSUE THREAD

**Issue by unlight** [ng-packagr/ng-packagr#707]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I'm trying to bundle 3rd party lib.
```
  "ngPackage": {
    "lib": {
      "entryFile": "src/index.ts",
      "embedded": [
        "fg-loadcss",
        "load-script"
      ]
    }
  },
```
Code:
```
export function loadStyle() {
    return require('fg-loadcss').loadCSS;
}

export function loadScript() {
    return require('load-script');
}
```
After build I do not see 3rd party libs in result bundle.
However, If I change `require` to `import` it works.

The problem is that I can't replace require by import, because these packages are not esm modules, but commonjs. And `import` is not applicable for them.

#### Expected Behaviour

embedded should work with require too.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            2.2.0
@angular/compiler:     5.2.9
@angular/compiler-cli: 5.2.9
rollup:                0.55.5
tsickle:               0.27.2
typescript:            2.8.0-rc
```

**Comment by alan-agius4** [comment]
Closing as this is working as expected.
