### ISSUE TITLE
nx-workspace how to add dependency of other libmodule under libs

### ISSUE THREAD

**Issue by xmlking** [ng-packagr/ng-packagr#709]
## Type of Issue

```
[ ] Bug Report
[x ] Feature Request
```

## Description

 feature: 

How do I add dependency of internal lib in case of `nx-workspace` 
for example: I am building  `scroll-to-top` lib that depends on other lib `@nx-starter-kit/animations`

https://github.com/xmlking/nx-starter-kit/blob/master/libs/scroll-to-top/src/scroll-to-top.component.ts#L3

#### How To Reproduce

repo : https://github.com/xmlking 

```
{
  "$schema": "../../node_modules/ng-packagr/package.schema.json",
  "name": "@xmlking/scroll-to-top",
  "version": "0.1.0",
  "ngPackage": {
    "lib": {
      "entryFile": "index.ts",
      "embedded": ["@nx-starter-kit/animations"]
    },
    "dest": "../../@nx-packaged/scroll-to-top"
  }
}
```

error 
```
ng-packagr -p libs/scroll-to-top/package.json

Building Angular Package
Building entry point '@xmlking/scroll-to-top'
Cleaning build directory
Rendering Stylesheets
Rendering Templates
Compiling TypeScript sources through ngc

BUILD ERROR
libs/scroll-to-top/src/scroll-to-top.component.ts(3,36): error TS2307: Cannot find module '@nx-starter-kit/animations'.

Error: libs/scroll-to-top/src/scroll-to-top.component.ts(3,36): error TS2307: Cannot find module '@nx-starter-kit/animations'.

    at Object.<anonymous> (/Developer/Work/SPA/is360-nx/node_modules/ng-packagr/lib/ngc/compile-source-files.js:69:35)
    at Generator.next (<anonymous>)
    at /Developer/Work/SPA/is360-nx/node_modules/ng-packagr/lib/ngc/compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Developer/Work/SPA/is360-nx/node_modules/ng-packagr/lib/ngc/compile-source-files.js:3:12)
    at Object.compileSourceFiles (/Developer/Work/SPA/is360-nx/node_modules/ng-packagr/lib/ngc/compile-source-files.js:19:12)
    at Object.<anonymous> (/Developer/Work/SPA/is360-nx/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:21:60)
    at Generator.next (<anonymous>)
    at /Developer/Work/SPA/is360-nx/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)


```

#### Expected Behaviour

_A bug: please describe what behaviour or result you expected_

_A feature: do you have a first draft or an idea how to implement?_

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            2.2.0
@angular/compiler:     6.0.0-rc.0
@angular/compiler-cli: 6.0.0-rc.0
rollup:                0.55.5
tsickle:               0.27.2
typescript:            2.7.2
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by Karankang007** [comment]
Running into same issue myself. I think if the author can provide an example how to cross reference secondary entry points, that would help.

**Comment by tbuffry** [comment]
add path in your tsconfig:

"paths": {
        "@ng-packagr/*": [
          "../../@ng-packagr/*"
        ]
      }

**Comment by dgroh** [comment]
I'm also trying to reference a lib inside another lib. it works with `ng build` but not for `ng-packagr -p`

I get the following error:

> BUILD ERROR
libs/dnb-map/src/lib/map/map.module.ts(2,39): error TS2307: Cannot find module '@scope/datepicker'.
libs\dnb-map\src\lib\map\map.module.ts(17,27): Error during template compile of 'MapModule'
  Could not resolve @scope/datepicker relative to D:/Projekte/Git/maps/libs/map/src/lib/map/map.module.ts..
libs\dnb-map\src\lib\map\map.module.ts(17,27): Error during template compile of 'MapModule'
  Could not resolve @scope/datepicker relative to D:/Projekte/Git/maps/libs/dnb-map/src/lib/map/map.module.ts..
: 'datepicker' is not a known element:

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `ng-packagr`.
