### ISSUE TITLE
How do you debug through a package?

### ISSUE THREAD

**Issue by JBoothUA** [ng-packagr/ng-packagr#713]
## Type of Issue

```
[ ] Bug Report
[X] Feature Request
```

## Description

How do you debug through a package?
Are there any command or parameters that can create a "debug" (non-minified) bundle?

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.
