### ISSUE TITLE
Document public_api exported index barrel

### ISSUE THREAD

**Issue by scott-wyatt** [ng-packagr/ng-packagr#720]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

_A feature: please describe your use case and motivation_

Document exported index barrels.

#### Expected Behaviour

_A feature: do you have a first draft or an idea how to implement?_

When creating a library, if an index barrel is used, the public_api needs to export the index specifically. Otherwise unexpected behaviour will occur.  Eg. `please use @NgModule Annotation` and `Only initialized variables and constants can be referenced because the value of this variable is needed by the template compiler`. 

This documented case should help people who bump into this issue from a search engine.

Correct Example:
```ts
// public_api.ts

export * from './src/app/ng-intercom/index'

```
It may also be a nice feature to detect if there is an index barrel and if it was not specified by the export.

This would likely fix #317 and #355

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete.
