### ISSUE TITLE
How to refer global stylesheets which has media queries

### ISSUE THREAD

**Issue by ramuda** [ng-packagr/ng-packagr#723]
## Type of Issue

```
[ ] Bug Report
```

## Description
I have a globals.css file as below 

``
:root {
  --menu-z-index: 1000;
  --dropdown-menu-z-index: 1500;
   --page-not-found-border-color: #faa519;
}
@custom-media --screenIsXS not all and (min-width: 768px);
@custom-media --screenIsNotXS (min-width: 768px);
@custom-media --screenIsSM not all and (min-width: 992px);
``

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:2.2.0
@angular/*: 5.1.0
typescript: 2.4.2
rxjs: 5.6.0
node: 8.9.2
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
