### ISSUE TITLE
Build Error TS1005: ',' expected.

### ISSUE THREAD

**Issue by KolbySisk** [ng-packagr/ng-packagr#726]
## Type of Issue

```
[ X] Bug Report
[ ] Feature Request
```

## Description

When running npm run packagr I get the bellow error. The project builds and works fine otherwise.

Building Angular Package
Building entry point 'a11y-modal-angular'
Cleaning build directory
Rendering Stylesheets
Rendering Templates
Compiling TypeScript sources through ngc

BUILD ERROR
src/lib/modal/modal.component.ts(9,25): error TS1005: ',' expected.
src/lib/modal/modal.component.ts(9,29): error TS1005: ':' expected.
src/lib/modal/modal.component.ts(9,36): error TS1005: ',' expected.
src/lib/modal/modal.component.ts(9,43): error TS1005: ':' expected.
src/lib/modal/modal.component.ts(11,38): error TS1005: ',' expected.
src/lib/modal/modal.component.ts(11,40): error TS1005: ':' expected.
src/lib/modal/modal.component.ts(11,77): error TS1005: ',' expected.
src/lib/modal/modal.component.ts(11,79): error TS1005: ':' expected.
src/lib/modal/modal.component.ts(17,27): error TS1005: ',' expected.

Error: src/lib/modal/modal.component.ts(9,25): error TS1005: ',' expected.
src/lib/modal/modal.component.ts(9,29): error TS1005: ':' expected.
src/lib/modal/modal.component.ts(9,36): error TS1005: ',' expected.
src/lib/modal/modal.component.ts(9,43): error TS1005: ':' expected.
src/lib/modal/modal.component.ts(11,38): error TS1005: ',' expected.
src/lib/modal/modal.component.ts(11,40): error TS1005: ':' expected.
src/lib/modal/modal.component.ts(11,77): error TS1005: ',' expected.
src/lib/modal/modal.component.ts(11,79): error TS1005: ':' expected.
src/lib/modal/modal.component.ts(17,27): error TS1005: ',' expected.

    at Object.<anonymous> (node_modules/ng-packagr/lib/ngc/compile-source-files.js:69:35)
    at Generator.next (<anonymous>)
    at node_modules/ng-packagr/lib/ngc/compile-source-files.js:7:71
    at Promise (<anonymous>)
    at __awaiter (node_modules/ng-packagr/lib/ngc/compile-source-files.js:3:12)
    at Object.compileSourceFiles (node_modules/ng-packagr/lib/ngc/compile-source-files.js:19:12)
    at Object.<anonymous> (node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:37:60)
    at Generator.next (<anonymous>)
    at node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:7:71
    at Promise (<anonymous>)

npm ERR! code ELIFECYCLE
npm ERR! errno 111
npm ERR! a11y-modal-angular@0.0.0 packagr: `ng-packagr -p ./src/lib/package.json`
npm ERR! Exit status 111
npm ERR!
npm ERR! Failed at the a11y-modal-angular@0.0.0 packagr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! .npm/_logs/2018-03-26T18_23_37_619Z-debug.log

#### How To Reproduce

After a day of debugging I found the culprit was a ` (backtick) in my component's html template.

**Comment by Sibiraj-S** [comment]
@KolbySisk . That was an issue with `ngc` itself I guess. Nothing to deal with `ng-packagr`

**Comment by C0ZEN** [comment]
I was struggling with similar errors.
The backtick in HTML files that @KolbySisk mention was the cause.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
