### ISSUE TITLE
ng-packagr works fine but with warnings!

### ISSUE THREAD

**Issue by SerkanSipahi** [ng-packagr/ng-packagr#729]
## Type of Issue

```
[ ] Bug Report
[ ] Feature Request
[x] Others
```

## Description

When we run `ng-packagr` we get warning from node. Is that a bug or do we something wrong?

ng-package.json
```
{
  "$schema": "./node_modules/ng-packagr/package.schema.json",
  "dest": "./",
  "deleteDestPath": false,
  "whitelistedNonPeerDependencies": ["."],
  "keepLifecycleScripts": true,
  "lib": {
    "entryFile": "./public_api.ts",
    "languageLevel": ["dom", "es2017"]
  }
}
```

Output:
```
> ng-packagr

Building Angular Package
Building entry point '@honey.glass/matmedia'
Cleaning build directory
Rendering Stylesheets
Rendering Templates
Compiling TypeScript sources through ngc
Bundling to FESM15
Bundling to FESM5
Bundling to UMD
Minifying UMD bundle
Relocating source maps
Copying staged files
Writing package metadata
You enabled keepLifecycleScripts explicitly. The scripts section in package.json will be published to npm.
Creating package .tgz
Built foo/matmedia
Built Angular Package!
- from: packages/matmedia
- to:   packages/matmedia

(node:75096) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, chmod '.ng_pkg_build/honey.glass-matmedia/out/node_modules/injection-js/metadata.d.ts'
(node:75096) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
on each run (ng-packagr) there are different warnings
```
(node:75725) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open '.ng_pkg_build/honey.glass-matmedia/out/node_modules/rxjs/operator/windowCount.d.ts'
(node:75725) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 2.4.1
@angular/compiler: 5.2.9
@angular/compiler-cli: 5.2.9
rollup: 0.55.5
tsickle: 0.27.2
typescript: 2.5.3
```

**Comment by ralberts** [comment]
I am seeing something similar though different error:
`
(node:14072) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'calendar-component\.ng_pkg_build\calendar-component\out\node_modules\ng-fullcalendar\ng-fullcalendar.d.ts'
(node:14072) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14072) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by igabesz** [comment]
Yep, same error here. I got this for `<project>\.ng_pkg_build\duelbox-jigs\out\node_modules\reflect-metadata\Reflect.d.ts'`. Then I added `import 'reflect-metadata';` to the entry file which solved the error. Now I'm wrestling with RxJs imports... Will report back if something found.

**Comment by C0ZEN** [comment]
Up.

**Comment by midryndhil** [comment]
Similar problem: 
```
(node:2359) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, chmod '.ng_pkg_build/<project>/out/node_modules/@angular/compiler-cli/ngtools2.d.ts'
(node:2359) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by ChamNouki** [comment]
Same problem here i think. With the following "not found" files changing each time I run the ng-packagr command : 
```Error: ENOENT: no such file or directory, open '.ng_pkg_build/ngx-oauth2/out/node_modules/rxjs/operators/partition.d.ts'```
```Error: ENOENT: no such file or directory, open '.ng_pkg_build/ngx-oauth2/out/node_modules/injection-js/injection_token.d.ts'```
```Error: ENOENT: no such file or directory, open '.ng_pkg_build/ngx-oauth2/out/node_modules/injection-js/injector.d.ts'```

**Comment by bjois** [comment]
was there a solution to this?

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
