### ISSUE TITLE
AOT Compilation Error when importing Secondary Entry Points

### ISSUE THREAD

**Issue by karan-kang** [ng-packagr/ng-packagr#731]
## Type of Issue

```
[x ] Bug Report
[ ] Feature Request
```

## Description
The following error is thrown when importing a secondary entry point in AOT mode.

ERROR in : Unexpected value 'TestLabelModule in C:/Users/kkang/Sources/tester/tester/node_modules/@amat/theme/spinner/spinner.module.d.ts' imported by the module 'AppModule in C:/Users/kkang/Sources/tester/tester/src/app/app.module.ts'. Please add a @NgModule annotation.

#### How To Reproduce

1. Create a library with secondary entry point.
2. Import the component in another Angular project using the secondary entry point.
3. Build using Angular CLI with --prod or --aot flag.
4. Import the same component using the primary entry point, build will work without any errors.

I have created a testing repo which can be used to reproduce this issue:
https://github.com/Karankang007/ng-packagr-testlib

```
import { TestLabelModule } from '@test/lib/label'; // Fails
import { TestLabelModule } from '@test/lib';          // Passes
```

#### Expected Behaviour
No compile or runtime errors in AOT mode.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            2.4.1
@angular/compiler:     5.2.9
@angular/compiler-cli: 5.2.9
rollup:                0.55.5
tsickle:               0.27.2
typescript:            2.5.3
```

**Comment by georgiee** [comment]
My top 3 checklist for some errors I had in ng-packagr. You might have an Typescript issue (2.5.3 vs 2.6) see the first bullet.

+ You need Typescript 2.6 to use submodules otherwise you get `module not found errors`
https://github.com/dherges/ng-packagr/issues/677

+ Always use `ng serve --follow-symlinks` when linked locally otherwise you get injection errors

+ Never rely on barrel files link directly or at least link directly to a barrel.
Don't do this:
```
import { something } 'folder-with/barrel/'
```

Do this instead:
```
import { something } 'folder-with/barrel/index'
```

**Comment by Karankang007** [comment]
None of those are cause of this issue. 

I was able resolve this issue by adding metadata redirect files in the root folder, similar to how Angular Material 2 project and other Angular libraries does it.

ngPackagr should add metadata redirect declaration and json file at the root folder (next to primary entry point) to resolve this issue.

**Comment by CarstenLeue** [comment]
@Karankang007 do you have an example for such redirect files?

**Comment by Karankang007** [comment]
**package.json**
```
{
    "name": "@test/button",
    "private": true,
    "ngPackage": {
        "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
        "lib": {
            "entryFile": "index.ts",
            "flatModuleFile": "test-button"
        }
    }
}
```

**index.ts**
```
export * from './button.module';
export * from './button.component';
```

On running ng-packagr for the above secondary entry point, a button folder will be created with test-button declaration and metadata. The following **two files** will need to be added to the root folder to get the AOT compilation to work for this secondary entry point in a target project:


**button.d.ts**
```
export * from './button/test-button';
```

**button.metadata.json**
```
{
	"__symbolic": "module",
	"version": 3,
	"metadata": {},
	"exports": [{
			"from": "./button/test-button"
		}
	],
	"flatModuleIndexRedirect": true
}
```

**Comment by thomaspink** [comment]
We got a similar build like material (every component is its own module and a secondary entry point;) and moved now to a build using ng-packagr. This issue basically breaks the whole library when being used and build in a CLI project in AOT mode.
Any updates on this issue?

**Comment by thomaspink** [comment]
Investigated a bit more. This is also reproducible when using the integration/samples/secondary project in a fresh CLI Project with AOT.

**Comment by LFeh** [comment]
Same here 😢

**Comment by ivorobioff** [comment]
aaaaa! any updates on this?

**Comment by ivorobioff** [comment]
Alright, after spending sometime comparing `@angular/common/http` with my package `@mypackage/core/account` packed by `ng-packagr` I found that 2 files are missing and after adding them everything worked like a charm! So, here's the structure I had:

```
- @mypackage
    - core
        - account
            - mypackage-core-account.d.ts
            - mypackage-core-account.metadata.json
            - ...
        - src
        - ...

```

What I did is added the following files to the `core` folder:

```
- core
    - ...
    - account.d.ts
    - account.metadata.json
    - ...
```

Here's the content of the files:

`account.d.ts`

```
export * from './account/mypackage-core-account';

```

`account.metadata.json`

```
{"__symbolic":"module","version":3,"metadata":{},"exports":[{"from":"./account/mypackage-core-account"}],"flatModuleIndexRedirect":true}

```
Note that names of the new files must match the name of the sub-package!

Not sure why it is so, it could be because of the current version of angular compiler which is 5.2.9

**Comment by alan-agius4** [comment]
This should no longer be an issue in v13.
