### ISSUE TITLE
Cannot export "non-angular" classes with non-initialized static attributes

### ISSUE THREAD

**Issue by WilliamChelman** [ng-packagr/ng-packagr#739]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

When trying to export (amongs other things) a "non-angular" class with an uninitiailized static attribute, the packaging of the library fails with the error:
```
 Error: C:/dev/ng-packagr-not-ng/src/app/core/my-class.ts:1:1: Error encountered in metadata generated for exported symbol 'MyClass':
 C:/dev/ng-packagr-not-ng/src/app/core/my-class.ts:2:18: Metadata collected contains an error that will be reported at runtime: Only initialized variables and constants can be referenced because the value of this variable is needed by the template compiler.
```

Maybe we could add something to the config to prevent metadata generation for specified files ?

#### How To Reproduce

Clone [this repository](https://github.com/WilliamChelman/ng-packagr-static-bug), do `yarn install` (`npm install` should do the trick too), then run `npm run build:lib`. The problematic file is `src/app/core/my-class.ts`

#### Expected Behaviour

The library is build without error

#### Version Information

```
ng-packagr: 2.4.1
@angular/compiler: 5.2.9
@angular/compiler-cli: 5.2.9
rollup: 0.55.5
tsickle: 0.27.2
typescript: 2.5.3
node: 8.9.0
yarn: 1.2.1
```

Kind regards,

**Comment by netsrotr** [comment]
Any progress on this issue? We used static getters a lot in our large project...

**Comment by alan-agius4** [comment]
`ng-packagr` under the hood uses `ngc` compiler, and such coding patterns are not allowed as code needs to be statically analysable.

This really is working as intended as the whole libraries need to be statically analysable to emit the metadata.

**Comment by huang12zheng** [comment]
However, how to solve this issue?

**Comment by huang12zheng** [comment]
if you use static in your class , you need // @dynamic.

**Comment by WilliamChelman** [comment]
@huang12zheng I'll have to test it again, but at the time even `@dynamic` didn't help in this case.

**Comment by huang12zheng** [comment]
@WilliamChelman 
Sorry,I couldn't npm i it.
However, today, I use my solution to solve an issue like yours
So, maybe I can fix it. It's just an accident -_-||
