### ISSUE TITLE
Is it possible to publish a package including its dependencies?

### ISSUE THREAD

**Issue by TMakaku** [ng-packagr/ng-packagr#744]
## Type of Issue

```
[ ] Bug Report
[x ] Feature Request / Question
```

## Description

__feature/question: Is it possible to package an publish a library A that depends on library B, without publishing library B?_

We have a common (internal) library that is to be shared among teams. 
We are now making a new library/component external use, that depends on this common library. We wish to package and publish this new component without having to publish our common library as a peerDependency. 

All attempts until now result in a package that is missing the code from our common library.

Is this possible?

I currently get the following error when using my package:
ERROR in : 'my-common-component' is not a known element:
1. If 'my-common-component' is an Angular component, then verify that it is part of this module.
2. If 'my-common-component' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("<p>
  mstviewer works!
  [ERROR ->]<my-common-component></my-common-component>
</p>
")

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:  newest versieon 
@angular/*: 5.x
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by tbuffry** [comment]
try: 

ngPackage": {
    "lib": {
       "embedded":

as per the documentation on first page, ( scroll down )

**Comment by TMakaku** [comment]
@tbuffry Thanks for the reply. I guess i missed that.
When using embedded, i expect to see the sourcecode of my embedded library in my dist, so i must still be doing something wrong.

In my package.json:
    "@test/my-lib-test": "0.0.1",

In my ng-package.json:
    "lib": {
      "entryFile": "public_api.ts",
      "embedded": ["@test/my-lib-test"]
    }

Is this syntax correct?

**Comment by TMakaku** [comment]
After some debugging I found the problem in my public_api.ts. I forgot to export one of the modules.

Now i'm on to the next problem, when trying to use my new lib:
```
ERROR in ..\@test\my-lib-test\my-lib-test.ts(10,9): Error during template compile of 'TestLibModule'
  Could not resolve @test/my-lib-test relative to C:/dev/test/node_modules/@test/my-lib-test/my-lib-test.d.ts..
```

**Comment by nchetbani** [comment]
@TMakaku, @tbuffry 

Currently when I try to packag (with ng-packagr) a module containing @angular/material tags (mat-toolbar), I get the following error (same as your's):

ERROR in : 'mat-toolbar' is not a known element:

If 'mat-toolbar' is an Angular component, then verify that it is part of this module.
If 'mat-toolbar' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("

I've added @angular/material as external libs in my ng-package.json

{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "lib": {
    "entryFile": "public_api.ts",
    "externals": {
      "@angular/material": "ng.material", 
      "@angular/material/autocomplete": "ng.material.autocomplete", 
      "@angular/material/toolbar": "ng.material.toolbar",
      "@angular/material/icon": "ng.material.icon"
    }
  },
  "whitelistedNonPeerDependencies": [
    "tslib",
    "oidc-client",
    "rxjs-compat",
    "ngx-contextmenu",
    "xlsx"
  ]
}

and I also add the lib as shown above:
 
{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "lib": {
    "entryFile": "public_api.ts",
    "externals": {
      "@angular/material": "ng.material", 
      "@angular/material/autocomplete": "ng.material.autocomplete", 
      "@angular/material/toolbar": "ng.material.toolbar",
      "@angular/material/icon": "ng.material.icon"
    }
  },
  "embedded": ["@angular/material"],
  "whitelistedNonPeerDependencies": [
    "tslib",
    "oidc-client",
    "rxjs-compat",
    "ngx-contextmenu",
    "xlsx"
  ]
}

But that did not solve my problem. so I would like to know if there is any other configuration to do to solve this problem

**Comment by collindutter** [comment]
@TMakaku @nchetbani did you guys ever end up finding a solution? No matter what I do I can't seem to get the dependencies to appear in the bundle.

Thanks!

**Comment by TMakaku** [comment]
@collindutter I ended up publishing a seperate package in npm to work around this problem and using that as a peer dependency

**Comment by raphael22** [comment]
Do I seriously have to combine another bundling stack in order to achieve these ?
Jeez..

**Comment by alan-agius4** [comment]
See: https://github.com/ng-packagr/ng-packagr/issues/1106

**Comment by raphael22** [comment]
"bundledDependencies" is not a viable solution for my problem.
I need my final umd bundle to be embed with it's dependencies in order to be used on the fly on a deployed angular application.

**Comment by lzgrzebski** [comment]
same problem as @raphael22
