### ISSUE TITLE
Use of a Package Object instead of a path that points to a package.json

### ISSUE THREAD

**Issue by tbuffry** [ng-packagr/ng-packagr#745]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

I am building a list of libraries, and I want them all be published in my prIvate repository
and i am adding this in all package.json. I would like to do it only once.

  "private": false,
  "publishConfig": {
    "registry": "mynicerepo/npm/registry/"
  }

#### How To Reproduce

   ngPackagr()
   .forProject(path.resolve(pathLib, 'package.json'))
   .withTsConfig(path.resolve(__dirname, 'tsconfig-pack.json'))
    .build();

#### Expected Behaviour

 let myJsonPackage = JSON.parse(fs.readFileSync('package.json'', 'utf8'));
myJsonPackage.private = false;
myJsonPackage.publishConfig": {
    "registry": "mynicerepo/npm/registry/"
  };

    ngPackagr()
   .forProject(myJsonPackage )
   .withTsConfig(path.resolve(__dirname, 'tsconfig-pack.json'))
    .build();

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 2.4.1
@angular/*: 5.2.6
typescript: 2.7.2
rxjs: x.y.z
node: x.y.z
npm/yarn: 5.6.0
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. Luckily, it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.
