### ISSUE TITLE
Invalid metadata file generated

### ISSUE THREAD

**Issue by Alorel** [ng-packagr/ng-packagr#749]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

ng-packagr generates an invalid metadata file as reported in this issue: https://github.com/Alorel/ngforage/issues/57

Related issue:  https://github.com/Alorel/ngforage/issues/56

Projects depending on that package compile fine in JiT mode, but fail in AoT.

#### How To Reproduce

_A bug: please include instructions how to reproduce. Issues without reproduction are likely to receive no feedback._:

* Initialise a new project
* Install the problem version of ngforage
   * **Angular 5**: npm install localforage@^1.7.1 ngforage@2.0.2
   * **Angular 6**: npm install localforage@^1.7.1 ngforage@3.0.3
* Import and configure `ngforage` in your app module:

```typescript
  import {NgForageModule, NgForageConfig} from 'ngforage';
  
  @NgModule({
    imports: [
      NgForageModule.forRoot()
    ]
  })
  export class AppModule{
    public constructor(ngfConfig: NgForageConfig) {
      ngfConfig.configure({
        name: 'MyApp'
      });
    }
  }
```

* AoT compile

_Can you reproduce the error in the integration tests in ng-packagr?_: no

_Is the error you faced in an application importing the library_: yes
_Try to break the Angular CLI app in [`integration/consumers/ng-cli`](./integration/consumers/ng-cli)!_

#### Expected Behaviour

The problem line as shown in https://github.com/Alorel/ngforage/issues/57 does not get generated

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            2.4.1
@angular/compiler:     5.2.9
@angular/compiler-cli: 5.2.9
rollup:                0.55.5
tsickle:               0.27.2
typescript:            2.8.1
```

Note: setting typescript to `>=2.4.2 <2.7` as required by Angular made no difference.

#### Rough fix on my end:

https://github.com/Alorel/ngforage/blob/791e2a6e79a42b3c3b1faa935063edc90b5df77d/build/package.js#L15

**Comment by alan-agius4** [comment]
Obsolete
