### ISSUE TITLE
Allow to name generated .tgz or name it using package version

### ISSUE THREAD

**Issue by karlos1337** [ng-packagr/ng-packagr#755]
## Type of Issue

```
[ ] Bug Report
[X] Feature Request
```

## Description

I'm already generating a .tgz with `npm pack ./dist` but it generates a file like `[package-name][package-version].tgz`, I want to maintaing versioning to allow library dependant apps to adapt in case of breaking changes and can't do it if always generate a `dist.tgz`.

#### How To Reproduce
 `ng-packagr -p package.json`

#### Expected Behaviour

Generate a dist folder and a .tgz package named using package name and version or allow to do that using a flag.

**Comment by alan-agius4** [comment]
The `tgz` generation feature was dropped in ng-packagr V3 RC.0 in favor of `npm pack` as the later does more than just generate a `tgz` file
