### ISSUE TITLE
Allow extending base types

### ISSUE THREAD

**Issue by Fraktalite** [ng-packagr/ng-packagr#756]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I'm trying to build a library inside of which I extend string for internal purpose. It doesn't build with ng-packager but succeed with ng build.

Here is the content of the internal type definition file (extenders.d.ts): 

```
declare interface String {
    capitalize(): string;
}
```

Here is the implementation (string.prototypes.ts)
```
String.prototype.capitalize = function(this:string) : string {
    if(!this || this.length <= 1){
        return this;
    }
    return this.charAt(0).toUpperCase() + this.slice(1);
};
```

I include it using this line inside a module:
`import '../core/extenders/string.prototype';`

Then when I build using **ng-packagr -p ng-package.json**, it start compiling then it gave the following error:
```
BUILD ERROR
src/app/services/permission.service.ts(69,57): error TS2339: Property 'capitalize' does not exist on type 'string'.
src/app/core/extenders/string.prototype.ts(1,18): error TS2339: Property 'capitalize' does not exist on type 'String'.
```

#### How To Reproduce

Just add the files listed above inside a ng-packagr project, don't forget to import the prototype file inside a module, use the method capitalize on a string in your project and just build using the command above.

#### Expected Behaviour

I expect the same behavior as an angular-cli project, so it should build and allows usage of base types extenders inside the library.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 2.4.1
@angular/*: 5.2.0
typescript: 2.5.3
rxjs: 5.5.6
npm: 3.10.10
```

**Comment by parteek111269** [comment]
trying to make an npm lib using npm run packagr but getting error 
BUILD ERROR
src/app/modules/searchbar/searchbar.component.ts(58,49): error TS2304: Cannot find name 'Array'.
src/app/modules/searchbar/searchbar.component.ts(95,46): error TS2339: Property 'length' does not exist on type '{}'.
src/app/modules/searchbar/searchbar.component.ts(100,44): error TS2339: Property 'length' does not exist on type '{}'.
src/app/modules/searchbar/searchbar.component.ts(172,41): error TS2304: Cannot find name 'Object'.
src/app/modules/searchbar/searchbar.component.ts(175,24): error TS2304: Cannot find name 'Object'.
src/app/modules/searchbar/searchbar.component.ts(180,68): error TS2304: Cannot find name 'Array'.
src/app/pipes/filter/filter.pipe.ts(8,36): error TS2304: Cannot find name 'Array'.
src/app/pipes/filter/filter.pipe.ts(12,23): error TS2339: Property 'filter' does not exist on type '{}'.
src/app/pipes/filter/filter.pipe.ts(12,78): error TS2339: Property 'toLowerCase' does not exist on type 'string'.
src/app/pipes/filter/filter.pipe.ts(17,23): error TS2339: Property 'filter' does not exist on type '{}'.
src/app/pipes/filter/filter.pipe.ts(19,108): error TS2339: Property 'toLowerCase' does not exist on type 'string'.
src/app/pipes/filter/filter.pipe.ts(26,23): error TS2339: Property 'filter' does not exist on type '{}'.
src/app/pipes/filter/filter.pipe.ts(27,113): error TS2339: Property 'toLowerCase' does not exist on type 'string'.
src/app/pipes/limitto/limitto.pipe.ts(8,11): error TS2304: Cannot find name 'Array'.
src/app/pipes/limitto/limitto.pipe.ts(11,19): error TS2339: Property 'slice' does not exist on type '{}'.

Error: src/app/modules/searchbar/searchbar.component.ts(58,49): error TS2304: Cannot find name 'Array'.
src/app/modules/searchbar/searchbar.component.ts(95,46): error TS2339: Property 'length' does not exist on type '{}'.
src/app/modules/searchbar/searchbar.component.ts(100,44): error TS2339: Property 'length' does not exist on type '{}'.
src/app/modules/searchbar/searchbar.component.ts(172,41): error TS2304: Cannot find name 'Object'.
src/app/modules/searchbar/searchbar.component.ts(175,24): error TS2304: Cannot find name 'Object'.
src/app/modules/searchbar/searchbar.component.ts(180,68): error TS2304: Cannot find name 'Array'.
src/app/pipes/filter/filter.pipe.ts(8,36): error TS2304: Cannot find name 'Array'.
src/app/pipes/filter/filter.pipe.ts(12,23): error TS2339: Property 'filter' does not exist on type '{}'.
src/app/pipes/filter/filter.pipe.ts(12,78): error TS2339: Property 'toLowerCase' does not exist on type 'string'.
src/app/pipes/filter/filter.pipe.ts(17,23): error TS2339: Property 'filter' does not exist on type '{}'.
src/app/pipes/filter/filter.pipe.ts(19,108): error TS2339: Property 'toLowerCase' does not exist on type 'string'.
src/app/pipes/filter/filter.pipe.ts(26,23): error TS2339: Property 'filter' does not exist on type '{}'.
src/app/pipes/filter/filter.pipe.ts(27,113): error TS2339: Property 'toLowerCase' does not exist on type 'string'.
src/app/pipes/limitto/limitto.pipe.ts(8,11): error TS2304: Cannot find name 'Array'.
src/app/pipes/limitto/limitto.pipe.ts(11,19): error TS2339: Property 'slice' does not exist on type '{}'.

    at Object.<anonymous> (/home/uimatic/Documents/modified_npm_lib/libraries/searchbar/node_modules/ng-packagr/lib/ngc/compile-source-files.js:40:68)
    at next (native)
    at /home/uimatic/Documents/modified_npm_lib/libraries/searchbar/node_modules/ng-packagr/lib/ngc/compile-source-files.js:7:71
    at __awaiter (/home/uimatic/Documents/modified_npm_lib/libraries/searchbar/node_modules/ng-packagr/lib/ngc/compile-source-files.js:3:12)
    at Object.compileSourceFiles (/home/uimatic/Documents/modified_npm_lib/libraries/searchbar/node_modules/ng-packagr/lib/ngc/compile-source-files.js:17:12)
    at Object.<anonymous> (/home/uimatic/Documents/modified_npm_lib/libraries/searchbar/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:31:32)
    at next (native)
    at /home/uimatic/Documents/modified_npm_lib/libraries/searchbar/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:7:71
    at __awaiter (/home/uimatic/Documents/modified_npm_lib/libraries/searchbar/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:3:12)
    at exports.compileNgcTransform.transform_1.transformFromPromise (/home/uimatic/Documents/modified_npm_lib/libraries/searchbar/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:19:75)

plz help me out on it

**Comment by Steven-Harris** [comment]
sorry to bump an old thread but I am also having issues publishing a module with custom prototypes defined. The Object.prototype.* declarations are being striped

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases.
