### ISSUE TITLE
Subpackage not generate metadata

### ISSUE THREAD

**Issue by dareksob** [ng-packagr/ng-packagr#757]
## Description
I generate a library with some submodules, all entry points was recognized but the metadata is still missing. 

#### How To Reproduce

Library with submodules that some sub package.json for each module.

#### command line

> ng-packagr -p ng-package.json

Building Angular Package
Building entry point '@PROJECT/framework'
Cleaning build directory
Rendering Stylesheets
Rendering Templates
Compiling TypeScript sources through ngc
Bundling to FESM15
'QueryList' is imported from external module '@angular/core' but never used
'Observable' is imported from external module 'rxjs' but never used
'MatButtonToggleGroup' is imported from external module '@angular/material' but never used
Bundling to FESM5
Bundling to UMD
No name was provided for external module 'rxjs' in options.globals – guessing 'rxjs'
No name was provided for external module 'ng2-charts' in options.globals – guessing 'ng2Charts'
No name was provided for external module 'ng2-charts/ng2-charts' in options.globals – guessing 'ng2Charts$1'
Minifying UMD bundle
Dropping unreachable code [0:153,0]
Declarations in unreachable code! [0:153,0]
Relocating source maps
Copying staged files
Writing package metadata
Removing scripts section in package.json as it's considered a potential security vulnerability.
Creating package .tgz
Built @PROJECT/framework
Building entry point '@PROJECT/framework/src/PROJECT-ui/cards' **< thats the submodule**
Cleaning build directory
Rendering Stylesheets
Rendering Templates
Compiling TypeScript sources through ngc
Bundling to FESM15
Bundling to FESM5
Bundling to UMD
Minifying UMD bundle
Relocating source maps
Copying staged files
Writing package metadata
Removing scripts section in package.json as it's considered a potential security vulnerability.
Creating package .tgz
Built @PROJECT/app-framework/src/PROJECT-ui/cards
Built Angular Package!

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 2.4.1
```

**Comment by dareksob** [comment]
Now i get a result with some submodules but i have an other problem in transpile time.

error TS6059: File 'framework/core/utilities/strings/index.ts' is not under 'rootDir' 'framework/ui/submoduleB\avatars'. 'rootDir' is expected to contain all source files.

In my case i have framework as module with all submodules
the ui module require has core module as requirement 

Who can I define it as external resource?

**Comment by xino1010** [comment]
any solution?

**Comment by alan-agius4** [comment]
Closing as it's without a reproduction.
