### ISSUE TITLE
ng-packagr does not transpile or bundle project with version 2.3.0 and 2.4.x

### ISSUE THREAD

**Issue by brandony-pn** [ng-packagr/ng-packagr#761]
## Type of Issue

```
[ x] Bug Report
[ ] Feature Request
```

## Description

With version 2.2.0 my library is properly bundled. With 2.3.0 and above the output is:
```
/home/brandony/.nvm/versions/node/v8.11.1/bin/node /home/brandony/.nvm/versions/node/v8.11.1/lib/node_modules/npm/bin/npm-cli.js run build:lib --scripts-prepend-node-path=auto

> tabular-view@0.0.0 build:lib /home/brandony/Development/repo/tabular-view
> ng-packagr -p libs/tabular-view/package.json

Building Angular Package

Process finished with exit code 0
```

#### How To Reproduce
`ng-packagr -p libs/tabular-view/package.json`

#### Expected Behaviour

A bundle to be created in the configured output directory or information about why it was not successful.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            2.4.2
@angular/compiler:     5.2.9
@angular/compiler-cli: 5.2.9
rollup:                0.55.5
tsickle:               0.27.5
typescript:            2.6.2
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by alan-agius4** [comment]
Can you please provide a reproduction?

**Comment by alan-agius4** [comment]
Closing as inactive.
