### ISSUE TITLE
Allow package consumption from the root of my development directory for `package.json`s which point at git revisions. 

### ISSUE THREAD

**Issue by pixelpax** [ng-packagr/ng-packagr#766]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

_Please describe your use case and motivation_
I'd like for consumers of my package to be able to point their package.json to a specific revision on github (or another repository) and receive valid code. 

As it is, the dist folder is only produced on build, and the consumable package is in a subdirectory, so I can't just run a post-install script and expect it to work. 

The only things I can think of to do are

1. Run a post-install to produce the dist, remove everything but the package, and move the package contents to the top level.
2. Track the dist folder (non-ideal)
3. Provide an index.ts file in the repo root to point at this dist folder. This seems to prevent ng s from running in the repo, disallowing me from developing the package. 

#### Expected Behaviour

Provide a standard way of pointing a consuming app to the dist folder to allow consumption directly from a git revision stored in a repository. 

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            2.4.2
@angular/compiler:     5.2.9
@angular/compiler-cli: 5.2.9
rollup:                0.55.5
tsickle:               0.27.5
typescript:            2.5.3

node: 7.10
yarn: 1.5.1
```

**Comment by alan-agius4** [comment]
Out of scope of ng-packagr.

You can build and publish the built libraries on GitHub similar to https://github.com/angular/cli-builds
