### ISSUE TITLE
[AoT]  Function calls are not supported in decorators

### ISSUE THREAD

**Issue by amcdnl** [ng-packagr/ng-packagr#767]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description
When running the build, I receive this error:

```
BUILD ERROR
Error during template compile of 'NgxsRouterPluginModule'
  Function calls are not supported in decorators but 'NgxsModule' was called.

Error: Error during template compile of 'NgxsRouterPluginModule'
  Function calls are not supported in decorators but 'NgxsModule' was called.

    at Object.<anonymous> (/Users/austin/dev/ngxs/node_modules/src/lib/ngc/compile-source-files.ts:66:27)
    at Generator.next (<anonymous>)
    at /Users/austin/dev/ngxs/node_modules/ng-packagr/lib/ngc/compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/austin/dev/ngxs/node_modules/ng-packagr/lib/ngc/compile-source-files.js:3:12)
    at Object.compileSourceFiles (/Users/austin/dev/ngxs/node_modules/ng-packagr/lib/ngc/compile-source-files.js:19:12)
    at Object.<anonymous> (/Users/austin/dev/ngxs/node_modules/src/lib/ng-v5/entry-point/ts/compile-ngc.transform.ts:36:35)
    at Generator.next (<anonymous>)
    at /Users/austin/dev/ngxs/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)
```

You can clone this PR and reproduce it: https://github.com/ngxs/store/pull/287

In this use case, we have a module that provides a `forRoot` implementation being used in another module that provides a `forRoot`.

```TS
@NgModule({
  imports: [NgxsModule.forFeature([RouterState])]
})
export class NgxsRouterPluginModule {
  static forRoot(options?: NgxsRouterPluginOptions): ModuleWithProviders {
    return {
      ngModule: NgxsRouterPluginModule,
      providers: [
        {
          provide: USER_OPTIONS,
          useValue: options
        },
        {
          provide: NGXS_ROUTER_PLUGIN_OPTIONS,
          useFactory: routerOptionsFactory,
          deps: [USER_OPTIONS]
        },
        {
          provide: RouterStateSerializer,
          useClass: DefaultRouterStateSerializer
        }
      ]
    };
  }
}
```

If you remove `imports: [NgxsModule.forFeature([RouterState])]` it works fine but with it it throws the error. This code compiles fine with just plain ngc.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 2.4.2
@angular/*:6.rc3
typescript: 2.72
rxjs: 6rc2
node: 8x
npm/yarn: x5x
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by ghost81** [comment]
check here https://github.com/dherges/ng-packagr/issues/778#issuecomment-382353997

**Comment by dherges** [comment]
List of related issues (possible duplicates):

- #778 
- #765 
- #727

**Comment by fxck** [comment]
`// @dynamic` doesn't seem to help in my case

**Comment by alan-agius4** [comment]
Please check this angular issue, https://github.com/angular/angular/issues/23609

**Comment by shairez** [comment]
I had a similar error which only happened using `yarn link`.
I fixed it by installing from the source.

**Comment by tabareh** [comment]
For those who use symlink, this issue is related to that. This is a completely unrelated error message.

We removed the node_modules folder under the linked folder and it works now.

If you wonder how can we develop without node_modules under a linked pacakge,then read about preserveSymlinks attribute in angular.json

**Comment by alxpsr** [comment]
Try this https://github.com/angular/angular/issues/23609#issuecomment-510871378
