### ISSUE TITLE
Having problem on stackblitz with the way ng-packagr bundles..

### ISSUE THREAD

**Issue by msalehisedeh** [ng-packagr/ng-packagr#777]
## Type of Issue
referring to the issues filed on stackblitz:
https://github.com/stackblitz/core/issues/374

Directives will receive "NullInjectorError: No provider for Renderer!" exception if injecting classes in the Directive's constructor. Please Advise on alternative course of action or fix the bug.

```
[X] Bug Report
[ ] Feature Request
```

## Description

 https://stackblitz.com/edit/free-json and https://stackblitz.com/edit/popup-lite and https://stackblitz.com/edit/flexible-table --- all three are using "drag-enabled" which is using directives with injection in its constructor...

#### How To Reproduce
Go to the links provided and do a inspection on page and see the console log

#### Expected Behaviour

Expect no issues

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: x.y.z
@angular/*: x.y.z
typescript: x.y.z
rxjs: x.y.z
node: x.y.z
npm/yarn: x.y.z
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by qballer** [comment]
any updates on this issue because this is happening to me as well ?

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.
