### ISSUE TITLE
How to add static folders from the app to dist via configuarion 

### ISSUE THREAD

**Issue by liliom55** [ng-packagr/ng-packagr#792]
## Type of Issue

```
[x] Feature Request
```

## Description

I want to create a Library which has some modules and components and also some important folders that I want to add them in dist folder. I'm able to implement it without those folders but  how to implement it that contains those folders ? 

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: ^2.4.2
@angular/cli: ~1.7.4
@angular/core: ^5.2.0
typescript:~2.5.3
rxjs: ^5.5.6
node: 8.11.1
npm: ^5.5.6
```

**Comment by liliom55** [comment]
I found the solution via [#123](https://github.com/dherges/ng-packagr/issues/123)

**Comment by alan-agius4** [comment]
Kindly see: https://github.com/ng-packagr/ng-packagr/blob/master/docs/copy-assets.md
