### ISSUE TITLE
Cannot file primeng\src\app\components\dom\domhandler.ts and Unable to get property Injectable' of undefined or null reference

### ISSUE THREAD

**Issue by thelegendofdeep** [ng-packagr/ng-packagr#806]
## Type of Issue

```
[ X] Bug Report
[ ] Feature Request
```

## Description

_A bug: please describe the error that you encountered_
Two bugs I have encounted. The first is when I run the packagr command, it looks for `primeng\src\app\components\dom\domhandler.ts `

so I get a file not found error. In my application I do use domhandler, but when I import domhandler  use the path 
'`primeng/components/dom/domhandler'.  `

So I add the primeng\src folder to the node modules which fixes the error and allows the package to be built, but its possible it causes errors later on. 

The bug I faced is after the package is built and imported in my application. 
`Unable to get property Injectable' of undefined or null reference`
which prevents the module from being created. 
 ```
 DomHandler = __decorate([
        core_1.Injectable()
    ], DomHandler);
    exports.DomHandler = DomHandler;
```

If I comment out the code, Ill end up getting others variables as undefined or null such as 'Component' and 'Input'.
#### How To Reproduce

I ran the packagr command to build the pacakge. After the package is built, I import the package from the packaged module. 

import {testModule} * from 'test';

When I start the application, I get the undefined errors that I listed above.

#### Expected Behaviour

_A bug: please describe what behaviour or result you expected_

The expected behavior is that the application loads with the module loading. 

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 1.7.0
typescript: 2.3.4
rxjs: 5.0.2
node: 7.2.1
npm: 6.0.0
uglify-js : 3.3.18

**Comment by alan-agius4** [comment]
Closing as this should no longer be an issue.
