### ISSUE TITLE
Update example on how to package lib SCSS in ng v6

### ISSUE THREAD

**Issue by tomgruszowski** [ng-packagr/ng-packagr#839]
## Type of Issue

Is it possible to generate css from scss in a new library project? The new angular.json file & recent cli packagr integration could perhaps expand on styling.

Is sass-bundle the way to do this? #273  How would we hook this into new project format?

Angular CLI [docs](https://github.com/angular/angular-cli/wiki/stories-global-styles) on this doesn't seem to work either.

I'm sure you're in the process of pushing a final bits out, and docs take a backseat, but I think this is something many issues relate to, a comprehensive guide on how to integrate styles and possibly re-package them in a library so it's emitted as a unified some-theme.css.

In my case specifically, we're tweaking bootstrap to match our theme as well as various custom & re-wrapped components and styling is a big part of all this.

Thank you

```
[ ] Bug Report
[X ] Feature Request
```

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 3.0.0-rc2
@angular/*: 6.0.0
typescript: 2.7.2
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by alan-agius4** [comment]
At the moment, `ng-packagr` doesn't offer bundling /flattening of scss files.

In my opinion yes, [scss-bundle](https://github.com/SimplrJS/scss-bundle) is the way to go. in order to hook it up you'd need to do a `postbuild` script that will bundle the theming. 

Example;
```json
{
 "build": "ng-packagr -p package.json",
 "postbuild": "tsnode ./bundle-scss"
}
```

Or if you can use `ng-packagr` API and do something like;

```ts
ngPackagr()
	.forProject("./ng-package.js")
	.withTsConfig("../../tsconfig.build.json")
	.build()
	.then(bundleScss)
	.catch(() => process.exitCode = 1);
```

And working example can be found here; https://github.com/alan-agius4/ng-mono-repo-starter/blob/master/tools/tasks/build.ts

**Comment by Dor3nz** [comment]
Where should the script definitions @alan-agius4 mentions? 

I've tried including them in the `package.json` `ng-package.json` and `ng-package.prod.json` inside the library's directory (`/projects/<library>`) but I can't get them to be hooked and run after the `ng build <library> --prod` command from the root of the ng6 project.

Am I missing something? Thank you.

**Comment by Dor3nz** [comment]
@alan-agius4 Ok, thank you. I knew I could go that way, I just was hoping I could hook the scripts from the angular-cli command instead of building from the package dir. But I made it work anyways, so thank you! <3

**Comment by Itrulia** [comment]
@Dor3nz you actually can, but you will need to extend the NgPackagrBuilder from angular-devkit/build-ng-packagr

**Comment by hughanderson4** [comment]
I dislike these solutions involving a post build step.
None of this can be applied when using `ng build --watch=true`
Developer workflow with HMR goodness is lost.
We need a built-in way to copy scss to dist without the post build hack.

**Comment by Itrulia** [comment]
@hughanderson4  have you seen my comment? This makes it all possible.

**Comment by chlab** [comment]
@Itrulia could you provide an example on how to achieve this?

**Comment by Splaktar** [comment]
I used `scss-bundle` in a different way, but I did get it working. Here is a [working example](https://github.com/DevIntent/dev).

**Comment by Ismaestro** [comment]
@Splaktar I like your solution, can someone else check it?? because I need to do the same thing...

**Comment by musso** [comment]
@hughanderson4 
You could try [concurrently](https://www.npmjs.com/package/concurrently) library. They supports concurrent watch.

**Comment by KhaledSamir** [comment]
@Splaktar Hey Michael, could you please clarify more to me how you used scss-bundle.config.json to let the library package the scss? I wanna use scss in my library instead of css which is the default option.

**Comment by Splaktar** [comment]
@KhaledSamir there were some breaking changes in `scss-bundle@3`. [This commit](https://github.com/DevIntent/dev/commit/ef8337f4079ddc9bee54351f63fbe14b0a689a14) shows what I needed to change and demonstrates the configuration that I use for my library.
