### ISSUE TITLE
Add ability to compile without bundle

### ISSUE THREAD

**Issue by ihym** [ng-packagr/ng-packagr#841]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description
There are cases where a part of the lib should be imported on demand and is not in the public_api.
For example, providing i18n strings that should be compiled but not bundled, as they are supposed to be conditionally imported, or not used at all.
What is the approach there? Is there any support for this currently?

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 3.0.0-rc.2
```

**Comment by kevupton** [comment]
I think in my scenario what would be idea is having both a bundled version, as well as each individual file next to their `.d.ts` file. This way a user could import directly from `'package/path/file'`. As well as `'package'` if they really wanted.

**Comment by alan-agius4** [comment]
This is not something we are going to look into anytime soon, as we strictly follow APF
