### ISSUE TITLE
how to package assets into dist?

### ISSUE THREAD

**Issue by dyh333** [ng-packagr/ng-packagr#857]
## Type of Issue

```
[ ] Bug Report
[*] Feature Request
```

## Description

if my library contains some assets, how can package them into dist? thanks

**Comment by totkeks** [comment]
For now I would suggest as a workaround to copy the asset files to the output directory using gulp/grunt, a short npm script using ncp or cpx.

In the future a configuration parameter like in the angular.json file would be a great addition to the ng-packagr.json:
```
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
```

**Comment by isanka88** [comment]
I also got same problem when I packaging using ngPackagr. So I wrote my own small node script to copy them to the dist folder manually.

> npm install wrench

create new js file in the root **assets-copy.js**





    var wrench = require("wrench"),
      util = require("util");

    var source = "./src/assets";
    var target = "./dist/src/assets";

    wrench.copyDirSyncRecursive(source, target, {
      forceDelete: true
    });

    console.log("Asset files successfully copied!");




add build script to **package.json** like below,I called it as **manual:assets-copy**





      "scripts": {
        "ng": "ng",
        "start": "ng serve",
        "build": "ng build",
        "test": "ng test",
        "lint": "ng lint",
        "e2e": "ng e2e",
        "packagr": "ng-packagr -p ng-package.json",
        "assets-copy": "node assets-copy.js"
      }




After you run
> npm run packagr

Also run our script
> npm run manual:assets-copy

It'll copy them to the dist folder manually.

**Comment by totkeks** [comment]
@alan-agius4 could you elaborate on the close? was it because that will never come or because it is already done?

**Comment by alan-agius4** [comment]
We're going to track this in here https://github.com/ng-packagr/ng-packagr/issues/1092
