### ISSUE TITLE
Run NPM AUDIT

### ISSUE THREAD

**Issue by AdamKernig** [ng-packagr/ng-packagr#871]
## Type of Issue
Run NPM Audit
```
[ ] Bug Report
[ X ] Feature Request
```

## Description

With the new launch on NPM 6 and the security audit feature, I have ran this and it appears that NG-Packagr has som moderate vulnerabilities, this is due to a dependancy.

#### How To Reproduce

run NPM AUDIT
To pass audit

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 2.4.4
@angular/*: 5.2.10
node: 8.10.11
npm/yarn: 6.0.1
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by Sibiraj-S** [comment]
Fixed in [v4.1.0](https://github.com/ng-packagr/ng-packagr/blob/master/CHANGELOG.md#410-2018-08-12)
