### ISSUE TITLE
Output structure of secondary endpoints is invalid. 

### ISSUE THREAD

**Issue by shlomiassaf** [ng-packagr/ng-packagr#891]
Because resolving the **package.json** of a module is done using the file system the current structure of **secondary** packages (e.g. `@angular/core/testing`) is invalid.

When webpack/ts resolves `@angular/core/testing` it will get it from 

`node_modules/@angular/core/testing/package.json`

Which has `  "module": "../fesm5/testing.js" `

so the resolved module is:

`node_modules/@angular/core/fesm5/testing.js`

Later, when webpack wants to find the `sideEffects` it will search for **package.json** and the logic for that is simple, search for the file if not exist go up 1 folder and repeat.

This will end up with the **package.json** of `@angular/core`.

This means that `sideEffects` can not be set on secondary packages, it will always be taking from the root package.

Fore more details see the issue I opened (webpack/webpack#7327) and @sokra s response.

I know that this is how `@angular` does the build and it's identical to it, but according to the answer I got from the webpack team it seems that the structure should change.

Also see angular/angular#24020

**Comment by alan-agius4** [comment]
Thanks for reporting this, I'll see what the guys at Angular have to say, as it more a general APF structure issue.

**Comment by alan-agius4** [comment]
Please see https://github.com/angular/angular/issues/24020#issuecomment-410089230
