### ISSUE TITLE
BUILD ERROR ENOENT: no such file or directory, open '...nomination-comparison-type.ts'

### ISSUE THREAD

**Issue by ybarbaria** [ng-packagr/ng-packagr#899]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

Currently, I use ng-packagr in my lib, this lib consume an another module builded by ng-packagr. This module export an Enum file. "nomination-comparison-type.ts". I have imported this module in the other lib. When I try to build the module with ng-packagr, I obtain this error : 

> BUILD ERROR
ENOENT: no such file or directory, open '...nomination-comparison-type.ts'

#### How To Reproduce

Just build one package which import an second one with an enum exported. 

#### Expected Behaviour

I wish I could build the package.  

#### Version Information
First lib (where the bug appear)

> "ng-packagr":
>  "1.7.0"
 > "@angular/cli": "1.3.2",
>  "@angular/compiler": "4.4.6",
>  "@angular/compiler-cli": "4.4.6",
 > "typescript": "2.7.2"

Second lib
  > "typescript": "2.3.0",
 >  "ng-packagr": "1.7.0"

**Comment by ybarbaria** [comment]
For more details, this is my enum file. 

`export enum NominationComparisonType {
    COMPARE_DB_SENT = 0,
    COMPARE_SENT_COUNTERPART = 1,
    COMPARE_SENT_TSO = 2,
}
`


And it is exported in my index.ts : 

`export {NominationComparisonType} from './nomination-comparison-type';`

**Comment by ybarbaria** [comment]
Fixed by this issue #758, I downgraded the version of  "uglify-js"

**Comment by alan-agius4** [comment]
Closing as this should be obsolete.
