### ISSUE TITLE
environment.ts inside code replace with environment.prod.ts or environment.sqa.ts in angular 4

### ISSUE THREAD

**Issue by SIMHACHALAM1001** [ng-packagr/ng-packagr#903]
I am using two projects for multi-tenant .one app is Video Media and using in another app (new App) .

so I created the shared services and models as a common code and I am using in both the apps ,Here the problem with environments.

In shared services we have 4 environments files like environment.ts(local), environment.dev.ts(dev),environment.prod.ts(prod).

In old app services and models consists only the local file environment.ts .so how can i replace the file or code only in environment.ts when running this command ng-packagr -p package.json.
below my enviroment.ts file.

const environment = { serverUrl:"http://localhost:8990", secureKeys:{ secretKey:'xxxxxxxxxxxxxxxxxxxxxxx' }

        }

**Comment by tonysamperi** [comment]
I'd need this too. News?

**Comment by alan-agius4** [comment]
File replacements is not available in my-packagr.

Use dependency injection instead to inject the needed config from the application.
