### ISSUE TITLE
v2: Incompatiable with tsickle 0.29

### ISSUE THREAD

**Issue by Karankang007** [ng-packagr/ng-packagr#905]
## Type of Issue
Empty bundles are generated with tsickle 0.29

```
[x ] Bug Report
[ ] Feature Request
```

#### How To Reproduce
Create a package and ensure the above mentioned versions are used. The following warning is logged:
```
Generated an empty bundle
```

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            2.4.5
@angular/compiler:     5.2.11
@angular/compiler-cli: 5.2.11
rollup:                0.55.5
tsickle:               0.29.0
typescript:            2.5.3
```

**Comment by dherges** [comment]
Hi @Karankang007,

thanks for reporting. It's unlikely I will actively maintain v2. However, pull requests are always welcome. Please make a precise description of what and why you change and it'll be in a release.

I'd recommend to either use v3 (which works for Angular 5) or use another version of tsickle and keep this issue open for documentation.

**Comment by alan-agius4** [comment]
Closing as per above comment.
