### ISSUE TITLE
Typings are not generated if external lib contains .ts files

### ISSUE THREAD

**Issue by OleksiiKravtsov** [ng-packagr/ng-packagr#907]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I created test component from the example: https://medium.com/@nikolasleblanc/building-an-angular-4-component-library-with-the-angular-cli-and-ng-packagr-53b2ade0701e and it works properly. All files in lib generated including typings for my module and component (_HeaderComponent_ and _HeaderModule_)

But if I make import from external lib (_ng2-cache_ in my case) that contains **.ts** files in my module then typings for my component and module are not generated.

```
import { CacheService } from 'ng2-cache/ng2-cache';
```

If I remove all the **.ts** files from external lib (_ng2-cache.ts_, _cache-storages.enum.ts_, etc) manually then the typings for my component and module are generated successfully.

#### How To Reproduce

Example of my lib is in the repo: https://github.com/OleksiiKravtsov/packagr-usage
Just do:
```
npm i
npm run packagr
```
Go to _dist_ folder and see that _src_ folder does not exist

Go to _header.module.ts_ and remove the line with import of _CacheService_
```
npm run packagr
```
Go to _dist_ folder and see that _src_ folder with typings for _HeaderComponent_ and _HeaderModule_ exists

#### Expected Behaviour

All files in lib generated including typings for my module and component regardless of existing **.ts** in external lib

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 1.7.0
@angular/*: 4.3.0
typescript: 2.1.6
rxjs: ^5.0.1
node: 6.14.2
npm: 3.10.10
```

Is this a problem with the **ng-packagr** or some configuration problem?
Please, advise.

Thanks in advance.

**Comment by OleksiiKravtsov** [comment]
@alan-agius4, as far as I understand the ng-packagr from >v2 is targeting Angular 5, but my project needs is Angular 4, that's why I am using v1.7.0

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases.
