### ISSUE TITLE
[Question] Nrwl and ng-packagr

### ISSUE THREAD

**Issue by brunano21** [ng-packagr/ng-packagr#911]
## Type of Issue

```
[ ] Bug Report
[ ] Feature Request
[x] Question
```

## Description
I already had a look to [ng-packged](https://github.com/dherges/ng-packaged) and [nx-packaged](https://github.com/dherges/nx-packaged).

I'm thinking to adopt [Nrwl](https://github.com/nrwl/nx) and ng-packagr for enterprise applications.  One of this application could potentially be structured as below (Nrwl scaffolding):
```
root/
   -- apps/
   --- myApp1/src
   - libs/
   -- core/
   -- commons/
   -- features/
   --- featureA/src/
   ---- featureA1/src/
   ---- featureA2/src/
   --- featureB/src/
   --- featureC/src/
```
The application (myApp) should be built with lazy loading in mind. Indeed, (almost) all features are Angular features which are set up in order to be lazy loaded. Also, certains features (_featureA_ here), may be configured in a way that it's a _composition_ of other features (_A1_ and _A2_). 

However some questions came to my mind:  
- do you think this folder structure is good enough?
  - do you think it worth to move featureA1 and featureA2 away from featureA and bring them at the same folder level of featureA, featureB and featureC?
- does each feature need a package.json (with a ng-packagr configuration)?
  - should featureA's package.json refer to featureA1 and featureA2 as peerDependencies?
- would you suggest a better architecture/folder structure?

**Comment by alan-agius4** [comment]
> do you think this folder structure is good enough?
The structure it's quite neat. 

> do you think it worth to move featureA1 and featureA2 away from featureA and bring them at the same folder level of featureA, featureB and featureC?
I think this all depends on what features they are, for instance, if the are sub features of `A` and cannot be used on their own. I think it's okay from an architectural point of view, that said, it also depends how many sub-folder feature A1 will have, as in order to access a particular feature, it will be hard to find it, even from the idea. (requires a lot of clicks)

> does each feature need a package.json (with a ng-packagr configuration)? Yes
> should featureA's package.json refer to featureA1 and featureA2 as peerDependencies?, No, `dependencies`, `peerDependencies` and `devDependencies` should only be specified in the primary entrypoint `package.json`. (in the above example: I'd assume it is `features/package.json`). This is because only the main package will get installed, the `package.json` in the secondary entrypoints are mainly used for resolutions.

> would you suggest a better architecture/folder structure? I think the whole thing that you illustrated above, is quite clean, and I wouldn't suggest any different. Apart from the fact that you should set a limit of nesting for entrypoints, ie not to end up something like the below;

Also it will depend if you'll have sort of testing modules, as you'll end up with massive imports example;
```ts
import { foo } from  "@mylib/feature/feature-a/feature-a-1/testing"
```

**Comment by brunano21** [comment]
@alan-agius4 thank you very much for the response.
Regarding the concerns coming from 
> _does each feature need a package.json (with a ng-packagr configuration)?_
bear in mind that 1-level features, (featureA|B|C) are kinda of application business boundaries, which means each feature will be owned by a _department_. Then each sub-feature (featureA1|A2) are developed by a team within the _department_. This is the reason I have strucured the libs/features in this way...also I want to stress once more that each feature (indipendently by its level) is a lazy-loaded module. All the 1-level features will be used (for the moment) by `root/apps/myApp` application.

Thinking back to the ng-packagr goal, its purpose (among others) is to create a _package-able_ library that can be pontentially published and then imported into other projects. 
I was thinking however if there could be a way to set up this mono-repo in a way that _myApp_ application could depend on versioned features, like @features/featureA@1.0.0, @features/featureB@1.0.2. Any idea on this?

>_should featureA's package.json refer to featureA1 and featureA2 as peerDependencies?_
>No, dependencies, peerDependencies and devDependencies should only be specified in the primary entrypoint package.json. (in the above example: I'd assume it is features/package.json). This is because only the main package will get installed, the package.json in the secondary entrypoints are mainly used for resolutions.
As today I don't have any `features/package.json`.

**Comment by alan-agius4** [comment]
If you don't have `features/package.json`, which is the main entrypoint of your library?

I was under the assumption that the below are all primary entrypoints;
```
libs/core
libs/common
libs/feature
```

If you want that each feature is versioned, it wouldn't do with secondary entrypoints for them, I would stick with primary entrypoints. 

At work, we have a mono repo structure with `ng-packagr`, we don't use `Nrwl`, nor Angular CLI yet for this. It is based on https://github.com/alan-agius4/ng-mono-repo-starter

**Comment by alan-agius4** [comment]
While you won't need to publish and package. A `package.json`, has more information to it, such as path mapping for various module formats, if your library has `sideEffects` or no, which will be used for `Webpack`

Tbh, I am looking at their examples https://github.com/nrwl/nx-examples, and it seems that they are not updated. As for instance their libraries https://github.com/nrwl/nx-examples/blob/master/angular.json#L811 are still configured to use `"projectType": "application",` instead of `"projectType": "library",`, which should trigger the `ng-packagr` build

**Comment by brunano21** [comment]
OK, let's assume them that I add a `package.json` for each feature and sub-feature and libs. How could make the `myApp` application depending on a specific version of a feature (`featureA`) / lib (`common`)?

**Comment by alan-agius4** [comment]
In that case you would need to publish your library to npm. That is the
only way I am aware of. That said only the primary enteypoints can be
versioned.

**Comment by matheo** [comment]
For the record:
In recent Nx versions, a `-- publishable` library has a `ng-package.json` and a `package.json` to configure everything. If you forget to create the lib as publishable, you will have to add them manually (I'm not sure if there's a schematic for that) and to add the `build` command in the `angular.json`.
