### ISSUE TITLE
Packaging typescript objects and interfaces

### ISSUE THREAD

**Issue by madmandrew** [ng-packagr/ng-packagr#914]
## Type of Issue

```
[?] Bug Report
[ ] Feature Request
[x] Question
```

## Description

I'm trying to package a couple simple typescript objects and interfaces.  It doesn't seem to be working and I'm not sure if it's packaging it correctly. Or maybe I'm not importing them correctly

#### How To Reproduce

ng-package.json
```
{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "lib": {
    "entryFile": "public_api.ts"
  }
}
```
public_api.ts
```
export * from './src/app/demo/demo.module';
export * from './src/app/demo/objects/FooObjects';
```

FooObjects
```
export interface FooInterface
{
   value1: boolean;
   value2?: string;
}

export class FooObject
{
    value1: boolean;
    value2?: string;

    constructor(input: FooInterface)
   {
       value1 = input.value1;
       value2 = input.value2;
   }
}
```

Example usage (not working)
```
import { FooObject } from "demo/src/app/demo/objects/FooObjects";
```
I'm also getting this error 
```
error TS2390: Constructor implementation is missing.
error TS2369: A parameter property is only allowed in a constructor implementation.
```
#### Version Information

```
"ng-packagr": "3.0.0",
"@angular/animations": "6.0.3",
"@angular/cdk": "6.1.0",
"@angular/common": "6.0.3",
"@angular/compiler": "6.0.3",
"@angular/core": "6.0.3",
"@angular/forms": "6.0.3",
"@angular/http": "6.0.3",
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by alan-agius4** [comment]
In the constructure you should use `this` to reference class members
```
   constructor(input: FooInterface) {
       this.value1 = input.value1;
       this.value2 = input.value2;
   }

```

**Comment by madmandrew** [comment]
ok... yes. But that was just a typo in the example.  Has nothing to do with the reported question/potential bug.

I did see in the packaged files in node_modules that the contructor gets lopped off and looks like this

```
constructor(input: FooInterface);
```

**Comment by alan-agius4** [comment]
I think you are referring to emitted `.d.ts`, which is the correct behaviour as it should be

```ts
export declare class FooObject {
    value1: boolean;
    value2?: string;
    constructor(input: FooInterface);
}
```

Can you provide a reproduction please, how you are getting the error at consumer level?

**Comment by madmandrew** [comment]
Example usage (not working)
```
import { FooObject } from "demo/src/app/demo/objects/FooObjects";
```
(referenced in original question)
I'm using webstorm and this is suggested import path. Which refers to the .d.ts file.  I don't see anything else that I can import?

**Comment by madmandrew** [comment]
Looks like what it's exporting, when I have the package installed, is

For demo.d.ts
```
/**
 * Generated bundle index. Do not edit.
 */
export * from './public_api';
export { demoComponent as ɵa } from './src/app/demo/components/demo/demo.component';
```
public_api.d.ts
```
export * from './src/app/demo/demo.module';
```
So like I suspected it's not exporting any reference FooObjects file or classes.  Only another angular component that I'm also using that is working correctly

**Comment by alan-agius4** [comment]
That shouldn't be the case. And there is a test covering this case https://github.com/dherges/ng-packagr/commit/251dcfbf8e7e6c05ee821870f9ca0dd17699bdc4

**Comment by madmandrew** [comment]
Well shoot... I think all it was is a npm cache issue.  I was using npm to install the package from a tar so I thought if I cleared node_modules it would re-install from the replaced tar.  But apparently it wasn't. 

I bumped the version to 0.0.1 and it replaced the public_api.d.ts to correct one vs wrong cached version

**Comment by alan-agius4** [comment]
Glad you managed to fix the issue
