### ISSUE TITLE
AOT: Unexpected value 'undefined' exported by the module when using barrel index.ts

### ISSUE THREAD

**Issue by kepennar** [ng-packagr/ng-packagr#917]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I'm trying to migrate an existing library to the new Angular-cli library support
This library has a lot of barrels `index.ts` files
I'm experiencing error on build with AOT enabled

#### How To Reproduce

https://github.com/kepennar/ng-cli-lib-issue-repro

Given a library managed by the new angular-cli v6 library management system.

Given a component `Comp1Component` of this lib imported from a barrel `index.ts` in a module `LibModule`

`projects/lib1/src/lib/components/index.ts`

```ts
export * from './comp1.component';
```

`projects/lib1/src/lib/lib.module.ts`

```ts
import { Comp1Component } from './components';
// ...

@NgModule({
  declarations: [Comp1Component],
  exports: [Comp1Component]
})
export class LibModule {}
```

When an application using this lib is launched in `prod` mode

Then build crash with the error

```log
ERROR in : Unexpected value 'undefined' exported by the module 'Lib1Module ...
```

If the component is directly imported from it's own file. It's work

`projects/lib1/src/lib/lib.module.ts`
```ts
import { Comp1Component } from './components/comp1.component';
@NgModule({
  declarations: [Comp1Component],
  exports: [Comp1Component]
})
export class LibModule {}
```

##### Reproduction steps
From the repo https://github.com/kepennar/ng-cli-lib-issue-repro

`npm run build:lib`
`npm run start:prod`

#### Expected Behaviour

I would like ng-packagr to support correctly barrels files

#### Version Information

Output from: `ng --version`.

```log
Angular CLI: 6.0.7
Node: 10.3.0
OS: linux x64
Angular: 6.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.7
@angular-devkit/build-angular      0.6.7
@angular-devkit/build-ng-packagr   0.6.7
@angular-devkit/build-optimizer    0.6.7
@angular-devkit/core               0.6.7
@angular-devkit/schematics         0.6.7
@angular/cli                       6.0.7
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.7
@schematics/angular                0.6.7
@schematics/update                 0.6.7
ng-packagr                         3.0.0
rxjs                               6.2.0
typescript                         2.7.2
webpack                            4.8.3
```

**Comment by kepennar** [comment]
Similar issues:
https://github.com/angular/angular/issues/23713
https://github.com/dherges/ng-packagr/issues/195
https://github.com/dherges/ng-packagr/issues/382
https://github.com/dherges/ng-packagr/issues/727
https://github.com/dherges/ng-packagr/issues/355

**Comment by alan-agius4** [comment]
Can you try to import like this works?

```ts
import { Comp1Component } from './components/index';
```

**Comment by kepennar** [comment]
When I change import to

```ts
import { Comp1Component } from './components/index';

```

I have this error:

```log
BUILD ERROR
Cannot read property 'module' of undefined
TypeError: Cannot read property 'module' of undefined
    at MetadataBundler.convertSymbol (.../node_modules/@angular/compiler-cli/src/metadata/bundler.js:312:61)
```

**Comment by Itrulia** [comment]
@kepennar Importing it from where it is defined will fix it. It seems like ng-packagr has problems with barrel files.

**Comment by kepennar** [comment]
My lib is 50+ components. I definitely can't refactor all imports to make it work with ng-packagr.
Never mind I fallback to our custom packaging tooling

**Comment by alan-agius4** [comment]
@Itrulia, It's rather strange that you fixed your issue by migrating to `angular-cli` As, Angular-CLI is using `ng-packagr` to support libraries.

**Comment by Itrulia** [comment]
Yeah was also confused, angular/cli is using .rc2, tried migrating to that and had the same issue, but then migrating to Angular CLI worked like a charm.

I was using tsickle @latest (0.29.0), angular/cli requires 0.27.5, **but** my migration to angular/cli also includes tsickle 0.29.0.

Those version numbers all come from package-lock.json so they should be correct.

**Comment by alan-agius4** [comment]
Which cli version are you using? Can you confirm if you have a
tsconfig.lib.json?

I am just trying to figure out if it’s related to one of the tsconfig flags
or something else.

**Comment by alan-agius4** [comment]
@kepennar, I had a look at this, and I managed to replicate both the errors using `ngc` directly in your project.

IE: `ERROR in : Unexpected value 'undefined' exported by the module 'Lib1Module ...` and `TypeError: Cannot read property 'module' of undefined`

**Comment by alan-agius4** [comment]
What I noticed is that in one case you used Angular 5 and Angular 6. This
is quite a change as the Angular Compiler has changed a bit and there are
some regressions.

**Comment by Itrulia** [comment]
That shouldn't matter tho, shouldn't it? NGC works (ng-packagr v1 spits outs just fine for example) via CLI

**Comment by alan-agius4** [comment]
It matters and quite a lot, in v6 there were a lot of changes in angular compiler-cli (ngc). Unless of course with ngc v6 it works as expected.

**Comment by Siderite** [comment]
This is not related to index.ts only. I have code that looks like this:
```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LocationService } from './services/location.service';
import { LocationModel } from './models/location-model';

@NgModule({
  imports: [ CommonModule ],
  providers: [ LocationService ]
})
export class LocationModule { }

export { LocationModel, LocationService };
```

, the idea being that I want to import every single thing in the location module from location.module.ts, not from their individual files. And it works, it just breaks ng-packagr in bundler.js:

> BUILD ERROR
> Cannot read property 'module' of undefined
> TypeError: Cannot read property 'module' of undefined
>     at MetadataBundler.convertSymbol (D:\_Projects\Bitomatique\biTomatiQE.Admin\node_modules\@angular\compiler-cli\src\metadata\bundler.js:264:57)
>     at createReference (D:\_Projects\Bitomatique\biTomatiQE.Admin\node_modules\@angular\compiler-cli\src\metadata\bundler.js:390:23)
>     at MetadataBundler.convertReference (D:\_Projects\Bitomatique\biTomatiQE.Admin\node_modules\@angular\compiler-cli\src\metadata\bundler.js:438:24)
>     at MetadataBundler.convertExpression (D:\_Projects\Bitomatique\biTomatiQE.Admin\node_modules\@angular\compiler-cli\src\metadata\bundler.js:367:33)
>     at D:\_Projects\Bitomatique\biTomatiQE.Admin\node_modules\@angular\compiler-cli\src\metadata\bundler.js:316:75
>     at Array.map (<anonymous>)
>     at MetadataBundler.convertMember (D:\_Projects\Bitomatique\biTomatiQE.Admin\node_modules\@angular\compiler-cli\src\metadata\bundler.js:316:43)
>     at D:\_Projects\Bitomatique\biTomatiQE.Admin\node_modules\@angular\compiler-cli\src\metadata\bundler.js:301:68
>     at Array.map (<anonymous>)
>     at MetadataBundler.convertMembers (D:\_Projects\Bitomatique\biTomatiQE.Admin\node_modules\@angular\compiler-cli\src\metadata\bundler.js:301:36)
> 

I could fix it manually in bundler.js line 264 like this:
```
var declaration = canonicalSymbol.declaration;
if (!declaration) declaration = canonicalSymbol; // added this line
```
although I don't know if it generated a usable package, just that the exception goes away.

**Comment by Siderite** [comment]
This is not related to index.ts only. I have code that looks like this:
```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LocationService } from './services/location.service';
import { LocationModel } from './models/location-model';

@NgModule({
  imports: [ CommonModule ],
  providers: [ LocationService ]
})
export class LocationModule { }

export { LocationModel, LocationService };
```

, the idea being that I want to import every single thing in the location module from location.module.ts, not from their individual files. And it works, it just breaks ng-packagr in bundler.js:

> BUILD ERROR
> Cannot read property 'module' of undefined
> TypeError: Cannot read property 'module' of undefined
>     at MetadataBundler.convertSymbol (D:\_Projects\MyProject\MyProject.Admin\node_modules\@angular\compiler-cli\src\metadata\bundler.js:264:57)
>     at createReference (D:\_Projects\MyProject\MyProject.Admin\node_modules\@angular\compiler-cli\src\metadata\bundler.js:390:23)
>     at MetadataBundler.convertReference (D:\_Projects\MyProject\MyProject.Admin\node_modules\@angular\compiler-cli\src\metadata\bundler.js:438:24)
>     at MetadataBundler.convertExpression (D:\_Projects\MyProject\MyProject.Admin\node_modules\@angular\compiler-cli\src\metadata\bundler.js:367:33)
>     at D:\_Projects\MyProject\MyProject.Admin\node_modules\@angular\compiler-cli\src\metadata\bundler.js:316:75
>     at Array.map (<anonymous>)
>     at MetadataBundler.convertMember (D:\_Projects\MyProject\MyProject.Admin\node_modules\@angular\compiler-cli\src\metadata\bundler.js:316:43)
>     at D:\_Projects\MyProject\MyProject.Admin\node_modules\@angular\compiler-cli\src\metadata\bundler.js:301:68
>     at Array.map (<anonymous>)
>     at MetadataBundler.convertMembers (D:\_Projects\MyProject\MyProject.Admin\node_modules\@angular\compiler-cli\src\metadata\bundler.js:301:36)
> 

I could fix it manually in bundler.js line 264 like this:
```
var declaration = canonicalSymbol.declaration;
if (!declaration) declaration = canonicalSymbol; // added this line
```
although I don't know if it generated a usable package, just that the exception goes away.

**Comment by alan-agius4** [comment]
@Siderite, I believe that will break the consumers as they might have runtime errors

Ideally this discussion is continued in the original issue post
https://github.com/angular/angular/issues/20931

**Comment by deepthan** [comment]
One reference at a time will succeed.

import a from 'AComponent';
import b from 'BComponent';

**Comment by alxpsr** [comment]
> Importing it from where it is defined is work for me.
@deepthan what you mean?

**Comment by blemaire** [comment]
To fix this, you must import the directive/component from the actual file into the module (not from an index.ts file)

**Comment by ytilis** [comment]
@blemaire @deepthan Yes, we know. It literally says that direct imports work in the original ticket description: 

> If the component is directly imported from it's own file. It's work

The bug is that barrel imports (index.ts) **_don't_** work, but they **_should_**.

**Comment by aruballo** [comment]
So if we are porting over an existing set of reusable components that are using barrel imports and converting them into a library, we will need to forgo the barrel imports? Thats cumbersome.

**Comment by ytilis** [comment]
> @ytilis have you tried from a `public-api` file, that might work...

The issue in question occurs when importing from a barrel into a module. public-api files are for exporting classes. What you're describing is not what this bug is about.

**Comment by rraziel** [comment]
Seems like something that should have been working long ago (barrel files are not exactly new) and there have been numerous tickets with 0 fix. More generally, it seems odd to go with TypeScript then be fine with a compiler that breaks with a pretty much meaningless error message whenever it encounters something like a barrel file or an extra comma.

I have a monorepo with 50+ modules and barrel files all over the place, adding /index everywhere is not exactly a solution, especially when some of those barrel files export hundreds of classes. And I assume I'm far from the only one with such a project size.

Can someone from the ng-packagr project give some hints on where (as in which project) the fix is needed so that someone can at least try to take a look and fix it? Should it be in ng-packagr, in angular/cli? There seems to have been a PR that may help a bit but didn't quite fix the issue: https://github.com/angular/angular/pull/22856

**Comment by rraziel** [comment]
Ok, had a look through the code of @angular/compiler-cli, change some things here and there to see what was going on, etc.: https://github.com/angular/angular/issues/33121

**Comment by rraziel** [comment]
Note: switching to Ivy also seems to fix the issue (the metadata still isn't exported but Ivy does not seem to require it)

**Comment by tcoz** [comment]
I’m pretty sure barrel files were put on the “not recommended” way of working with modules a long time ago. To me they’re nothing but trouble; circular references, etc. etc. If possible, my first recommendation would be to switch to a standard module file. 

However, I have seen the error you mention, though possibly in another context. Using the “@dynamic” annotation was the fix.

**Comment by BoneShooter** [comment]
@kepennar did you resolve it？I hava the same problem with barrel `index.ts`

**Comment by tibinthomas** [comment]
For now, we can export all the Module classes directly from the publuc api. For all other types of files where only time definition is taken can be used in barrels.

**Comment by stevefiedler** [comment]
My library is pretty big and I have many many barrel files.  I am still getting that crazy error:

ERROR in Unexpected value 'undefined' exported by the module 

I have ready through everything multiple times, and the recommendation is to remove them.  I wish there was a way to know what will work before I do all the effort.  Ideas?
