### ISSUE TITLE
Building dynamic secondary entry points manually

### ISSUE THREAD

**Issue by elclanrs** [ng-packagr/ng-packagr#925]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

I have a library of about 60 components each as a secondary entry point that is figured out dynamically by ng-packagr with a package.json as described in the instructions.

This works fine if I trigger the build like `ng build components`; it creates all the secondary entry points and I can import them in my app.

However, I cannot build secondary entry points manually. When I try building a single component with:

```
$(npm bin)/ng-packagr -p projects/components/button
```

I get the following error:

```
BUILD ERROR
Cannot read property 'startsWith' of undefined
TypeError: Cannot read property 'startsWith' of undefined
    at NgEntryPoint.flattenModuleId (/home/elclanrs/Documents/ng-packagr-manual-compilation/node_modules/ng-packagr/lib/ng-package-format/entry-point.js:142:27)
    at NgEntryPoint.get flatModuleFile [as flatModuleFile] (/home/elclanrs/Documents/ng-packagr-manual-compilation/node_modules/ng-packagr/lib/ng-package-format/entry-point.js:104:56)
    at NgEntryPoint.get destinationFiles [as destinationFiles] (/home/elclanrs/Documents/ng-packagr-manual-compilation/node_modules/ng-packagr/lib/ng-package-format/entry-point.js:75:37)
    at entryPoints.map.entryPoint (/home/elclanrs/Documents/ng-packagr-manual-compilation/node_modules/ng-packagr/lib/ng-v5/package.transform.js:50:52)
    at Array.map (<anonymous>)
    at MapSubscriber.source$.pipe.operators_1.map.graph [as project] (/home/elclanrs/Documents/ng-packagr-manual-compilation/node_modules/ng-packagr/lib/ng-v5/package.transform.js:49:77)
    at MapSubscriber._next (/home/elclanrs/Documents/ng-packagr-manual-compilation/node_modules/rxjs/internal/operators/map.js:86:35)
    at MapSubscriber.Subscriber.next (/home/elclanrs/Documents/ng-packagr-manual-compilation/node_modules/rxjs/internal/Subscriber.js:103:18)
    at SwitchMapSubscriber.notifyNext (/home/elclanrs/Documents/ng-packagr-manual-compilation/node_modules/rxjs/internal/operators/switchMap.js:122:26)
    at InnerSubscriber._next (/home/elclanrs/Documents/ng-packagr-manual-compilation/node_modules/rxjs/internal/InnerSubscriber.js:30:21)
```

#### How To Reproduce

1) Clone this repo: https://github.com/elclanrs/ng-packagr-manual-compilation
2) Try compiling a single component with `$(npm bin)/ng-packagr -p projects/components/button`

#### Expected Behaviour

I  expect the button component to be compiled in the dist folder overriding what was there previously.

Ideally, it would be nice to be able to do `ng build components/button` or `ng build components --entry=button` or something like that.

#### Version Information

```
ng-packagr:            3.0.1
@angular/compiler:     6.0.3
rollup:                0.59.4
tsickle:               0.27.5
typescript:            2.7.2
```

**Comment by alan-agius4** [comment]
This is currently not supported. You always need to build the primary entry point first

**Comment by alan-agius4** [comment]
Also, I am not sure if this is how you wanted it. But at the moment, the primary entry point will compile all code for instance `button` will be compiled and bundled in `components ` and `components/button`, due to the fact that in `public-api` you are referencing files instead of secondary entry points https://github.com/elclanrs/ng-packagr-manual-compilation/blob/master/projects/components/public_api.ts

**Comment by karpoff** [comment]
Hi @alan-agius4, Is there any plans to add ability for parallel builds?
I have a lot of secondary endpoints and most of them doesn't depend on each other. Currently every build takes too much time for me

**Comment by shlomiassaf** [comment]
This is very tricky because the `tsconfig` in secondary entry points must be able to resolve other packages (other secondaries or the primary).

It needs to resolve it in the dist (resolve the output lib) and not from the actual source code.

I have built a replacement for `@angular-devkit/build-ng-packagr:build` called [ng-cli-packagr-tasks](https://github.com/shlomiassaf/ng-cli-packagr-tasks) that provide hooks to customise `ng-packagr` at various points in the build process.

One of the examples I show is how to [modify `tsconfig` settings in secondary entry points](https://github.com/shlomiassaf/ng-cli-packagr-tasks/blob/master/examples/update-tsconfig-for-secondary-entry-points.ts)

It's quite simple.

**Comment by dalemanthei** [comment]
> Also, I am not sure if this is how you want it or no. But, at the moment each secondary entrypoints is being compiled and bundled twice ie in `components` and `components/button` for instance. As from the primary entrypoint `public_api` you are referencing these as files and not packages https://github.com/elclanrs/ng-packagr-manual-compilation/blob/master/projects/components/public_api.ts

I'm trying to do much the same thing. The building of the component twice is what happens in the angular material build where you get one large bundle with everything (for convenience I think) and a bundle for each of the components in the material library.

We could live without the `components` module if we could get the `components/button`, `components/tree`, etc to build.

@elclanrs did you find a solution to this?

We do have `ts-config-build.json` files in each of our components. Pretty much the same as the ones in material here: https://github.com/angular/components/blob/master/src/material/button/tsconfig-build.json. Perhaps these could be leveraged with the packagr tasks @shlomiassaf provides in his repo?

**Comment by elclanrs** [comment]
@dalemanthei unfortunately I didn't find a solution but for now it works fine for us because you can still import a single component even if the package contains them all.

**Comment by alan-agius4** [comment]
Thanks for this request, but this is currently not planned.
