### ISSUE TITLE
[Question] Use Sass from another package

### ISSUE THREAD

**Issue by HoplaGeiss** [ng-packagr/ng-packagr#927]
## Type of Issue

```
[ ] Bug Report
[ ] Feature Request
[x] Question
```

## Description
I have a Sass file that I packaged in an npm package. (`pie-theme.scss`)
This is a dependency of my `pie-carousel` component.
I am able to use the style in that component by doing an `@import '~pie-theme/pie-theme.scss';`

However when I package `pie-carousel` and try to use it in another application the style are not there.
I am probably missing something obvious.. Please can you help?

#### Version Information

```
node_modules/.bin/ng-packagr --version
ng-packagr:            3.0.1
@angular/compiler:     5.2.11
rollup:                0.59.4
tsickle:               0.27.5
typescript:            2.5.3
```

**Comment by HoplaGeiss** [comment]
While trying to provide a reproduction example, I solved my issue!
However, I found another very similar.

It seems the assets (images) are not packaged by default.
Please have a look at this repo: [https://github.com/HoplaGeiss/packagr-example](https://github.com/HoplaGeiss/packagr-example) 
I created a component that has a div with a background color from another dependency and an icon.
That component is then package and used in another application, the div appears fine, but the icon doesn't.
More details in the readme of that repo.

**Comment by alan-agius4** [comment]
That is not a bug, image don’t get embedded unless they are background
images. In order to embed background images check the section ‘How to embed
assets in CSS’ In the main readme.

**Comment by Branhammer** [comment]
I am seeing a similar issue as the original post. I am importing a scss file (into a component scss file) from a dependency. When I attempt to build I get the following build error:
`BUILD ERROR
returned value of `file` must be a string
Error: returned value of `file` must be a string
    at options.error (C:\MY\ABSOLUTE\PATH\node_modules\node-sass\lib\index.js:291:26)`

Any thoughts?

@HoplaGeiss, what was it that fixed your issue?

**Comment by HoplaGeiss** [comment]
Sorry, I can't help you. My issue was quite different, I didn't get an error, the style just didn't appear.
I am not sure how I fixed it.. It just worked when I tried to create a simple reproduction example - Happy to close that issue.

**Comment by baerree** [comment]
>     1. Can you try to remove the `.scss` extentions?, in general these should not be used.
> 
>     2. I assume that `node_modules/pie-theme/pie-theme.scss` does exist correct?
> 
>     3. Can you provide a small reproduction?

How did you solve it??

**Comment by baerree** [comment]
> While trying to provide a reproduction example, I solved my issue!
> However, I found another very similar.
> 
> It seems the assets (images) are not packaged by default.
> Please have a look at this repo: https://github.com/HoplaGeiss/packagr-example
> I created a component that has a div with a background color from another dependency and an icon.
> That component is then package and used in another application, the div appears fine, but the icon doesn't.
> More details in the readme of that repo.

how did you solve it??
