### ISSUE TITLE
undefined return using es5 transpiled output when comment precedes the return value of arrow function

### ISSUE THREAD

**Issue by zakhenry** [ng-packagr/ng-packagr#941]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description
I have a comment before the return of an arrow function, and rather than correctly returning the value, undefined is returned instead when using the output es5 module. Basically the transpilation is incorrect with the es5 target. I'm unsure where it is coming from as checking the output for the simple test case against typescript playground and babel yields the correct output.

#### How To Reproduce

Create a function with the following pattern of comment before the returned expression
```ts
(_ =>
    /**
     * Some comment here
     */
    1 + 1
)();
```

This transpiles to
```js
(function (_) {
    /**
     * Some comment here
     */
    return /**
         * Some comment here
         */
    1 + 1;
})();
```

which returns `undefined`, not 2.

Interestingly, the return value *must* be an expression, otherwise the output is ok.

#### Expected Behaviour
The transpilation in es5 should give a function that yields `1`

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 3.0.0
@angular/*: 6.0.2
typescript: 2.7.2
```

**Comment by alan-agius4** [comment]
This is an Angular bug. Take a look at https://github.com/angular/angular/issues/23829

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases.
