### ISSUE TITLE
[Question] Is there possibility to inline json files?

### ISSUE THREAD

**Issue by m-tomczyk** [ng-packagr/ng-packagr#966]
## Type of Issue

```
[ ] Bug Report
[ ] Feature Request
[x] Question
```

## Description

Is there a possibility to inline contents of *.json (or other) files as string in output code of packagr?
My usecase is that I have some of json schemas that I'd like to keep as separate files in source rather than inline them in *.ts files.
As workaround I could require() them and leave resolving for consumer project but that means i need to copy files 'by hand' to each angular package format directories. It could work for esm5 and esm2015 but for flat version it creates problem where relative path of require will resolve to format root directory. And that will break if I happen to have files of same name. There is workaround to this - unique name policy but it feels wrong and makes my build less stable.

#### Version Information

```
ng-packagr: 3.0.3
@angular/compiler: 6.0.5
rollup: 0.59.4
tsickle:  0.29.0
typescript: 2.7.2
rxjs: ^6.0.0
node: 10.4.0
npm/yarn: yarn1.7.0
```

**Comment by alan-agius4** [comment]
As you mentioned something like this get tricky considered the different modules format. I believe we had this feature some time ago, but was dropped for the same reasons. Using ‘require’ I am not sure if that would work for all module formats and bundlers.

May I ask why not use json files instead of json objects in typescript files?

**Comment by m-tomczyk** [comment]
You're right, require is not universal solution, but it works for my buildprocess right now.

> May I ask why not use json files instead of json objects in typescript files?

I guess you meant another way around? Json files are external to frontend part of project. I have this files as 'single source of truth' shared by multiple modules (in different languages).

From my perspective solution is to inline this files, similar to what's happening to html templates. That way it will work in any format. Of course it's solution for static imports only. That said it's enough for my usecase.

**Comment by alan-agius4** [comment]
Yeah I meant the other way wrong.

In case you have a json schema. Another approach is to convert this to TypeScript via an addition step.

Take a look at this library https://www.npmjs.com/package/json-schema-to-typescript

**Comment by m-tomczyk** [comment]
I'm already using typescript definitions but I need runtime check of incoming data - so I'm using schema to validate data against it.
