### ISSUE TITLE
How to export type definition file

### ISSUE THREAD

**Issue by Humberd** [ng-packagr/ng-packagr#997]
## Type of Issue

```
[ ] Bug Report
[ ] Feature Request
[x] Question
```

## Description

Let's say I have a type definition file `foo.d.ts`. How do I export this file, so that it is accessible from a built bundle?

**Comment by alan-agius4** [comment]
You need to use the triple slash reference 
https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html
